import json, os, sys
sys.path.insert(0, os.getcwd())
from scripts.generators.concept_factory import raw_mcq, raw_stmt, raw_ar, raw_match, raw_seq
from scripts.generators.test_expand import expand_concept

CH_DEMO = "The Demographic Structure of the Indian Society"

concepts = [
    # 1. Malthusian Theory
    ("Malthusian Theory of Population",
     ("According to Thomas Robert Malthus in his 1798 Essay on Population, at what rates do human population and food supply grow?",
      "Population grows geometrically (1, 2, 4, 8, 16...) while food production grows arithmetically (1, 2, 3, 4, 5...)",
      ["Population grows arithmetically while agricultural food production increases geometrically",
       "Both human population and food output expand at an identical exponential trajectory",
       "Food production expands exponentially while human population remains stationary over centuries"],
      "Malthus argued that unchecked population grows geometrically while food subsistence increases only arithmetically, leading to catastrophic imbalances.",
      "Identifies Malthusian geometric vs arithmetic growth rates."),
     ("Malthus classified famine, war, and epidemics as 'positive checks' that nature imposes when population outstrips food supply.",
      "Malthus advocated that the state must distribute unlimited cash subsidies to prevent natural checks from operating.",
      3,
      "Statement I is correct because Malthus identified famines, wars, and disease outbreaks as positive checks. Statement II is incorrect because Malthus opposed state welfare subsidies, arguing they would worsen population growth.",
      "Distinguishes positive checks from welfare critiques."),
     ("Marxist and liberal social theorists fundamentally criticized Malthus's theory of population.",
      "Historical developments demonstrated that agricultural technology and equitable distribution could increase food output faster than population growth.",
      1,
      "Both (A) and (R) are true, and (R) correctly explains (A). Critics proved that famines were caused by unequal distribution and colonial poverty rather than absolute lack of food production.",
      "Understands the critical rebuttals to Malthusian population theory."),
     ("seq", "Arrange the stages of the classic Malthusian catastrophe cycle in logical sequence:",
      [("A", "Agricultural abundance and low mortality spark rapid population growth"),
       ("B", "Geometric population expansion overtakes arithmetic food production"),
       ("C", "Severe food scarcity and starvation emerge across society"),
       ("D", "Positive checks (famines/epidemics) contract population back to subsistence level")],
      "A, B, C, D",
      "The Malthusian cycle begins with abundance, followed by geometric growth outstripping food, triggering positive checks (scarcity/epidemics), which forcibly resets population.",
      "Sequences the Malthusian cyclical process.")),

    # 2. Demographic Transition Theory Overview
    ("Demographic Transition Theory Overview",
     ("The Demographic Transition Theory explains the long-term population dynamics associated with which major societal transformation?",
      "The transition from an agrarian, technologically backward society to an advanced, industrialized, and urbanized society",
      ["The shift from a nomadic hunting band to a feudal pastoral chieftainship",
       "The replacement of paper currency by electronic digital cryptocurrency systems",
       "The migration of entire national populations across continental mountain ranges"],
      "Demographic Transition Theory links demographic changes (fertility and mortality declines) directly to economic development, industrialization, and urbanization.",
      "Identifies economic modernization as the driver of demographic transition."),
     ("In the Demographic Transition Model, death rates typically decline before birth rates begin to fall.",
      "Society takes considerable time to adjust its cultural values and reproductive norms toward smaller family sizes.",
      1,
      "Both statements are correct. Technological improvements in medicine and sanitation reduce mortality quickly, whereas social norms regarding fertility change slowly.",
      "Analyzes the lag between mortality decline and fertility reduction."),
     ("The transition from high birth and death rates to low birth and death rates occurs in distinct developmental stages.",
      "Different countries progress through the demographic transition at identical historical speeds and identical chronological dates.",
      3,
      "(A) is true because demographic transition progresses through distinct stages. (R) is false because countries experience transition at widely varying speeds and historical periods.",
      "Evaluates variable pacing of demographic transitions."),
     ("match", "Match the demographic transition stages in List I with their defining characteristics in List II:",
      [("A", "Stage 1 (Pre-industrial)"), ("B", "Stage 2 (Early industrial)"), ("C", "Stage 3 (Post-industrial)"), ("D", "Demographic Lag")],
      [("I", "Low birth rate and low death rate, population stable"),
       ("II", "High birth rate and high death rate, slow population growth"),
       ("III", "Falling death rate with high birth rate, population explosion"),
       ("IV", "Time gap between decline in mortality and decline in fertility")],
      "A-II, B-III, C-I, D-IV",
      "Stage 1 is high-high; Stage 2 is falling mortality with high fertility; Stage 3 is low-low; demographic lag is the cultural delay in fertility reduction.",
      "Matches demographic transition stages to vital rate dynamics.")),

    # 3. Stage 1 Demographic Transition
    ("Stage 1 Demographic Transition",
     ("Why is population growth slow and fluctuating in Stage 1 of the demographic transition?",
      "High birth rates are offset by high death rates caused by frequent famines, epidemics, and lack of modern medicine",
      ["Couples deliberately choose to have zero children due to high educational costs",
       "The state strictly enforces statutory laws limiting families to a single child",
       "Massive emigration drains more than fifty percent of the youth population annually"],
      "Stage 1 features high fertility balanced by high mortality, resulting in negligible net population growth.",
      "Explains vital balance in Stage 1 pre-industrial societies."),
     ("In Stage 1 societies, high birth rates are culturally necessary because infant mortality is exceedingly high.",
      "In agrarian economies of Stage 1, children are economic liabilities who cannot contribute to farming tasks.",
      3,
      "Statement I is correct as high fertility ensures survival of lineage under high infant mortality. Statement II is incorrect as children are economic assets in labor-intensive peasant agriculture.",
      "Recognizes economic role of children in pre-industrial societies."),
     ("Prior to the 1920s, India was in the first stage of the demographic transition.",
      "The year 1921 is known as the 'Year of the Great Divide' because after 1921, India's population grew consistently without major contractions.",
      1,
      "Both (A) and (R) are true, and (R) correctly explains (A). Prior to 1921, famines and the 1918 influenza epidemic caused mortality spikes, keeping growth stagnant.",
      "Connects 1921 Great Divide to demographic transition stages."),
     ("seq", "Arrange the historical mortality events affecting pre-1921 Indian demography in chronological order:",
      [("A", "First synchronous decennial Census of India"),
       ("B", "Famines of the late nineteenth century documented by colonial commissions"),
       ("C", "The catastrophic Influenza Pandemic (Spanish Flu) in India"),
       ("D", "The Census marking the 'Year of the Great Divide'")],
      "A, B, C, D",
      "Census began in 1881, late 19th-century famines occurred in 1896-1900, Influenza in 1918-19, and 1921 Census marked the Great Divide.",
      "Chronologically orders historical demographic milestones.")),

    # 4. Stage 2 Demographic Transition & Population Explosion
    ("Stage 2 Population Explosion",
     ("What demographic mechanism directly causes the 'population explosion' characteristic of Stage 2 of transition?",
      "A sharp decline in mortality rates due to public health improvements while fertility rates remain persistently high",
      ["A sudden biological doubling of female fertility rates while mortality remains constant",
       "A complete influx of immigrant refugees quadrupling the national population in five years",
       "A total ban on the manufacture and import of contraceptive devices"],
      "Stage 2 explosion is caused by falling mortality (via sanitation and antibiotics) combined with traditional high birth rates.",
      "Identifies the precise driver of population explosion."),
     ("Mortality rates can be brought down relatively quickly through external public health interventions like vaccinations and clean water.",
      "Birth rates decline simultaneously because reproductive norms automatically change overnight with the arrival of modern medicine.",
      3,
      "Statement I is correct as public health measures reduce deaths rapidly. Statement II is incorrect because cultural beliefs about childbearing take generations to change.",
      "Contrasts rapid medical mortality control with slow cultural fertility change."),
     ("Most developing countries experienced a population explosion in the middle decades of the twentieth century.",
      "Colonial and post-colonial governments introduced modern disease control before economic development had altered traditional family structures.",
      1,
      "Both (A) and (R) are true, and (R) correctly explains (A). Rapid diffusion of antibiotics and vector control reduced death rates before urbanization reduced family sizes.",
      "Explains why developing nations entered Stage 2 mid-twentieth century."),
     ("match", "Match the vital rate indicators in List I with their definitions in List II:",
      [("A", "Crude Birth Rate (CBR)"), ("B", "Crude Death Rate (CDR)"), ("C", "Rate of Natural Increase"), ("D", "Infant Mortality Rate (IMR)")],
      [("I", "Number of deaths of children under 1 year of age per 1,000 live births"),
       ("II", "Number of live births per 1,000 population in a given year"),
       ("III", "Number of deaths per 1,000 population in a given year"),
       ("IV", "The difference between crude birth rate and crude death rate per 1,000 population")],
      "A-II, B-III, C-IV, D-I",
      "CBR is live births per 1,000; CDR is deaths per 1,000; Natural Increase is CBR minus CDR; IMR is infant deaths under 1 year per 1,000 live births.",
      "Matches vital demographic rates to standardized definitions.")),

    # 5. Stage 3 Demographic Transition
    ("Stage 3 Demographic Transition",
     ("Which demographic condition characterizes Stage 3 of demographic transition in fully developed societies?",
      "Low birth rates and low death rates resulting in stable population or near-zero population growth",
      ["Extremely high birth rates matched by widespread famine and infectious plagues",
       "A rapid doubling of the population every ten years due to mandatory state parenthood",
       "A massive pyramidal base where children under five constitute over forty percent of the total population"],
      "In Stage 3, urbanization, female education, and high living costs drive fertility down to balance low mortality.",
      "Identifies the low-equilibrium condition of Stage 3."),
     ("In Stage 3 societies, the widespread availability of contraceptives and female economic empowerment lead to declining fertility.",
      "Stage 3 countries frequently encounter social challenges related to an aging population and shrinking labor supply.",
      1,
      "Both statements are correct. High female education and contraception lower birth rates, eventually leading to population aging and labor shortages.",
      "Analyzes societal implications of late demographic transition."),
     ("Several European nations and Japan currently exhibit Total Fertility Rates below the replacement level of 2.1.",
      "Sub-replacement fertility in advanced economies can lead to negative population growth and rising dependency burdens of the elderly.",
      1,
      "Both (A) and (R) are true, and (R) correctly explains (A). Low fertility over decades causes population contraction and higher old-age dependency.",
      "Understands demographic consequences of sub-replacement fertility."),
     ("seq", "Arrange the historical trajectory of a society traversing the Demographic Transition Model from first to last:",
      [("A", "High birth and death rates keeping population stationary"),
       ("B", "Death rates plunge due to epidemic control while births stay high"),
       ("C", "Birth rates begin falling as urbanization and education expand"),
       ("D", "Birth and death rates reach low equilibrium with an aging age structure")],
      "A, B, C, D",
      "The four phases move sequentially: pre-transition equilibrium, mortality drop (explosion), fertility decline, and post-transition low equilibrium.",
      "Sequences the chronological stages of demographic transition."))
]

print(f"Loaded {len(concepts)} concepts for Unit 1. Total questions so far: {len(concepts) * 4}")
