"use client";

import { useEffect, useState } from "react";
import { Check, Download, FileText, Flag, Search, Save } from "lucide-react";

type Row = { id: string; normalized_question_text: string; subject_name: string; filename: string; source_page: number; extraction_confidence: number; requires_review: number; review_reasons_json: string; source_image?: string };
type Detail = Row & { year: number | null; extraction_method: string; raw_question_text: string; options: Record<string, { raw_text: string; normalized_text: string; is_correct: number }>; metadata: Record<string, string>; answer_key: { correct_option: string | null; source_type: string } | null; source_page_image: string | null; source_page_images: Array<{ page_number: number; page_image_path: string }> };

export default function PYQAdminPage() {
  const [token, setToken] = useState("");
  const [ready, setReady] = useState(false);
  const [rows, setRows] = useState<Row[]>([]);
  const [stats, setStats] = useState<any>(null);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("review");
  const [offset, setOffset] = useState(0);
  const [total, setTotal] = useState(0);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");

  useEffect(() => { setToken(sessionStorage.getItem("pyq-admin-token") || ""); setReady(true); }, []);
  const request = async (url: string, init?: RequestInit) => fetch(url, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...init?.headers } });
  const refresh = async () => {
    if (!token) return;
    sessionStorage.setItem("pyq-admin-token", token);
    const [listRes, statRes] = await Promise.all([request(`/api/admin/pyq?status=${status}&search=${encodeURIComponent(search)}&offset=${offset}&limit=50`), request("/api/admin/pyq?stats=1")]);
    if (!listRes.ok) { setMessage((await listRes.json()).error || "Unable to load data"); return; }
    const data = await listRes.json(); setRows(data.questions || []); setTotal(data.total || 0); setStats((await statRes.json()).stats);
    if (detail) await openQuestion(detail.id);
  };
  const openQuestion = async (id: string) => { const res = await request(`/api/admin/pyq?id=${encodeURIComponent(id)}`); const data = await res.json(); if (data.question) setDetail(data.question); };
  const download = async (format: "json" | "jsonl") => { const res = await request(`/api/admin/pyq/export?format=${format}`); if (!res.ok) { setMessage((await res.json()).error || "Export failed"); return; } const url = URL.createObjectURL(await res.blob()); const a = document.createElement("a"); a.href=url; a.download=`cuet-pyq.${format}`; a.click(); URL.revokeObjectURL(url); };
  useEffect(() => { if (ready && token) void refresh(); }, [ready, status, offset]);
  const patch = async (payload: any) => { setBusy(true); const res = await request("/api/admin/pyq", { method: "PATCH", body: JSON.stringify(payload) }); const data = await res.json(); setBusy(false); setMessage(res.ok ? "Saved" : data.error || "Save failed"); if (res.ok) { await refresh(); if (payload.action) await openQuestion(payload.id); } };
  if (!ready) return null;

  return <div className="mx-auto max-w-7xl p-5 md:p-8 text-slate-900">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Stage 1 · Source grounded</p><h1 className="mt-2 text-3xl font-black">PYQ ingestion review</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Inspect extracted text beside its PDF page. Missing answers stay unknown until verified. Approving marks the extraction reviewed; it does not create an answer key.</p></div>
    <div className="flex gap-2"><button onClick={()=>void download("json")} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm font-bold"><Download size={16}/> JSON</button><button onClick={()=>void download("jsonl")} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm font-bold">JSONL</button></div></div>
    <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4"><label className="text-xs font-bold uppercase text-amber-900">Admin access token</label><div className="mt-2 flex gap-2"><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="PYQ_ADMIN_TOKEN" className="min-w-0 flex-1 rounded-lg border border-amber-200 bg-white px-3 py-2 text-sm"/><button onClick={()=>void refresh()} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">Connect</button></div><p className="mt-2 text-xs text-amber-900">Configure the same secret as <code>PYQ_ADMIN_TOKEN</code> on the server. It is kept in this browser session only.</p></div>
    {stats && <div className="my-5 grid grid-cols-2 gap-3 md:grid-cols-5">{[["PDFs",stats.total_documents],["Pages",stats.total_pages],["Questions",stats.total_questions],["Needs review",stats.needs_review],["Avg. confidence",`${stats.average_confidence}%`]].map(([k,v])=><div key={String(k)} className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">{k}</div><div className="mt-1 text-2xl font-black">{v}</div></div>)}</div>}
    <div className="grid gap-5 lg:grid-cols-[340px_minmax(0,1fr)]">
      <aside className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-3"><div className="flex gap-2"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void refresh()} placeholder="Find question" className="w-full rounded-lg border py-2 pl-9 pr-2 text-sm"/></div><button onClick={()=>void refresh()} className="rounded-lg bg-slate-900 px-3 text-white">Go</button></div><select value={status} onChange={e=>setStatus(e.target.value)} className="mt-2 w-full rounded-lg border p-2 text-sm"><option value="review">Needs review</option><option value="all">All questions</option><option value="validated">Approved</option><option value="duplicate">Duplicates</option></select></div>
      <div className="max-h-[70vh] overflow-y-auto">{rows.map(row=><button key={row.id} onClick={()=>void openQuestion(row.id)} className={`block w-full border-b p-3 text-left hover:bg-emerald-50 ${detail?.id===row.id?"bg-emerald-50":""}`}><div className="flex justify-between gap-2"><span className="text-xs font-bold text-emerald-800">{row.subject_name} · Q{row.id.split("_").at(-1)}</span><span className="text-xs text-slate-500">{Math.round(row.extraction_confidence*100)}%</span></div><p className="mt-1 line-clamp-2 text-sm">{row.normalized_question_text}</p><span className="mt-1 block truncate text-[11px] text-slate-500">{row.filename} · page {row.source_page}</span></button>)}{rows.length===0&&<div className="p-6 text-center text-sm text-slate-500">No matching questions. Connect with a valid token or change filters.</div>}</div><div className="flex items-center justify-between border-t p-3 text-xs"><span>{total ? `${offset + 1}–${Math.min(offset + rows.length, total)} of ${total}` : "0 questions"}</span><div className="flex gap-2"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-50))} className="rounded border px-3 py-1 disabled:opacity-40">Previous</button><button disabled={offset+rows.length>=total} onClick={()=>setOffset(offset+50)} className="rounded border px-3 py-1 disabled:opacity-40">Next</button></div></div></aside>
      <section className="min-w-0 rounded-2xl border bg-white p-4 md:p-6">{detail ? <Review detail={detail} busy={busy} patch={patch} /> : <div className="flex min-h-64 flex-col items-center justify-center text-center text-slate-500"><FileText/><p className="mt-2">Choose a question to review its source and extracted fields.</p></div>}</section>
    </div>{message&&<p className="fixed bottom-5 right-5 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white shadow-lg">{message}</p>}
  </div>;
}

function Review({detail,busy,patch}: {detail:Detail;busy:boolean;patch:(x:any)=>Promise<void>}) {
  const [text,setText]=useState(detail.normalized_question_text); const [opts,setOpts]=useState<Record<string,string>>(Object.fromEntries(["A","B","C","D"].map(k=>[k,detail.options[k]?.normalized_text||""]))); const [answer,setAnswer]=useState(detail.answer_key?.correct_option||""); const [chapter,setChapter]=useState(detail.metadata.chapter||""); const [topic,setTopic]=useState(detail.metadata.topic||""); const [concept,setConcept]=useState(detail.metadata.concept||"");
  useEffect(()=>{setText(detail.normalized_question_text);setOpts(Object.fromEntries(["A","B","C","D"].map(k=>[k,detail.options[k]?.normalized_text||""])));setAnswer(detail.answer_key?.correct_option||"");setChapter(detail.metadata.chapter||"");setTopic(detail.metadata.topic||"");setConcept(detail.metadata.concept||"");},[detail.id]);
  return <><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-wider text-slate-500">{detail.subject_name} · {detail.year || "Year unknown"} · page {detail.source_page}</div><h2 className="mt-1 text-xl font-black">{detail.filename}</h2><p className="mt-1 text-xs text-slate-500">Confidence {Math.round(detail.extraction_confidence*100)}% · {detail.extraction_method} · {detail.answer_key?.source_type ? `Answer key: ${detail.answer_key.source_type}` : "No verified answer key"}</p></div><div className="flex gap-2"><button onClick={()=>void patch({id:detail.id,action:"flag",notes:"Requires manual source review"})} className="rounded-lg border px-3 py-2 text-sm"><Flag size={15}/></button><button onClick={()=>void patch({id:detail.id,action:"approve"})} className="flex items-center gap-2 rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white"><Check size={16}/> Approve</button></div></div>
    {(detail.source_page_images?.length ? detail.source_page_images : detail.source_page_image ? [{ page_number: detail.source_page, page_image_path: detail.source_page_image }] : []).map(page => <a key={page.page_number} target="_blank" rel="noreferrer" href={page.page_image_path} className="mt-4 block max-h-[420px] overflow-auto rounded-xl border bg-slate-100"><div className="sticky top-0 bg-slate-900/80 p-2 text-xs font-bold text-white">Original PDF page {page.page_number}</div><img src={page.page_image_path} alt={`Original PDF page ${page.page_number}`} className="mx-auto h-auto max-w-full"/></a>)}
    <p className="mt-3 text-xs font-semibold text-slate-500">Raw extraction (preserved)</p><pre className="mt-1 max-h-36 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-xs">{detail.raw_question_text}</pre>
    <label className="mt-4 block text-sm font-bold">Clean question text</label><textarea value={text} onChange={e=>setText(e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border p-3 text-sm"/>
    <div className="mt-3 grid gap-3 md:grid-cols-2">{["A","B","C","D"].map(k=><label key={k} className="text-sm font-bold">Option {k}<textarea value={opts[k]} onChange={e=>setOpts({...opts,[k]:e.target.value})} className="mt-1 min-h-16 w-full rounded-lg border p-2 text-sm font-normal"/></label>)}</div>
    <div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-sm font-bold">Verified answer key<select value={answer} onChange={e=>setAnswer(e.target.value)} className="mt-1 w-full rounded-lg border p-2 font-normal"><option value="">Unknown / no key</option>{["A","B","C","D"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-bold">Chapter<input value={chapter} onChange={e=>setChapter(e.target.value)} className="mt-1 w-full rounded-lg border p-2 font-normal"/></label><label className="text-sm font-bold">Topic<input value={topic} onChange={e=>setTopic(e.target.value)} className="mt-1 w-full rounded-lg border p-2 font-normal"/></label><label className="text-sm font-bold">Concept<input value={concept} onChange={e=>setConcept(e.target.value)} className="mt-1 w-full rounded-lg border p-2 font-normal"/></label></div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-2"><div className="text-xs text-slate-500">Review flags: {JSON.parse(detail.review_reasons_json||"[]").join(", ")||"none"}</div><button disabled={busy} onClick={()=>void patch({id:detail.id,question_text:text,options:opts,correct_option:answer||null,chapter:chapter||null,topic:topic||null,concept:concept||null})} className="flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><Save size={15}/> Save edits</button></div></>;
}
