import json, os, sys

CH_DEMO = "The Demographic Structure of the Indian Society"
CH_INST = "Social Institutions: Continuity and Change"
CH_MARKET = "The Market as a Social Institution"
CH_INEQ = "Patterns of Social Inequality and Exclusion"

slots = {}

# Slot 5: Population Policies & Census (20 items)
s5 = [
    ("mcq", CH_DEMO, "First National Family Planning Programme",
     "Which country was the first in the developing world to launch an official state-sponsored National Family Planning Programme in 1952?",
     "India", ["China", "United States", "Japan"],
     "India was the first country to launch an official National Family Planning Programme in 1952.\\nHence, Option {{CORR}} is correct.", "Recalls India's priority in family planning."),
    ("mcq", CH_DEMO, "NPP 2000 Target-Free Approach",
     "What is the core approach of the National Population Policy (NPP) 2000 regarding fertility control?",
     "A target-free, voluntary approach focused on reproductive and child health needs",
     ["Coercive sterilizations enforced by police quotas", "A complete statutory ban on all contraceptive advertising", "Mandatory monetary fines on all third-born children"],
     "NPP 2000 marked a shift to voluntary, target-free reproductive healthcare.\\nHence, Option {{CORR}} is correct.", "Identifies target-free paradigm of NPP 2000."),
    ("stmt", CH_DEMO, "Emergency Sterilization Backlash",
     "During the National Emergency (1975-77), family planning quotas were enforced coercively by state administrative machinery.",
     "The widespread public anger over Emergency sterilization abuses led to the political defeat of the ruling party in 1977.", 1,
     "Both statements are correct: Coercive mass vasectomy drives caused intense public resentment that ousted the government in 1977.\\nHence, Option {{CORR}} is correct.", "Analyzes political consequences of Emergency sterilization."),
    ("ar", CH_DEMO, "Shift to Family Welfare",
     "In 1977, the National Family Planning Programme was renamed the Family Welfare Programme.",
     "The government sought to shed the stigma of Emergency coercion and promote a comprehensive health and welfare approach.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The renaming reflected a holistic approach to reproductive health.\\nHence, Option {{CORR}} is correct.", "Explains the shift from family planning to family welfare."),
    ("match", CH_DEMO, "Historical Population Policy Milestones",
     "Match the population policy milestones in List I with their corresponding years in List II:",
     [("A", "Launch of official Family Planning Programme"), ("B", "National Emergency coercive drives"), ("C", "Enactment of PCPNDT Act"), ("D", "Adoption of National Population Policy")],
     [("I", "1952"), ("II", "1975-1977"), ("III", "1994"), ("IV", "2000")],
     "A-I, B-II, C-III, D-IV",
     "Family planning began in 1952, Emergency in 1975-77, PCPNDT in 1994, NPP in 2000.\\nHence, Option {{CORR}} is correct.", "Matches demographic policy milestones to dates."),
    ("seq", CH_DEMO, "Phases of Population Policy in India",
     "Arrange the historical phases of Indian population policy in chronological sequence:",
     [("A", "Initial clinical approach providing clinic-based advice"),
      ("B", "Extension education and camp vasectomy target approach"),
      ("C", "Coercive mass sterilization quotas during the Emergency"),
      ("D", "Target-free reproductive and child health (RCH) framework")],
     "A, B, C, D",
     "Indian family planning evolved from clinical to extension/camps, Emergency targets, and modern RCH.\\nHence, Option {{CORR}} is correct.", "Sequences policy phases chronologically."),
    ("mcq", CH_DEMO, "First Synchronous Indian Census",
     "In which year was the first synchronous, all-India decennial Census conducted under British rule?",
     "1881", ["1857", "1901", "1947"], "The first complete synchronous Census across British India took place in 1881.\\nHence, Option {{CORR}} is correct.", "Identifies 1881 Census milestone."),
    ("mcq", CH_DEMO, "Statutory Framework for Census",
     "Under which statutory act is the decennial Census of independent India conducted?",
     "The Census Act, 1948", ["The Government of India Act, 1935", "The Representation of the People Act, 1951", "The Disaster Management Act, 2005"],
     "The Census Act 1948 provides the statutory basis for all decennial censuses in India.\\nHence, Option {{CORR}} is correct.", "Identifies Census Act 1948."),
    ("mcq", CH_DEMO, "Census Administrative Ministry",
     "Which ministry of the Government of India houses the Office of the Registrar General and Census Commissioner?",
     "Ministry of Home Affairs", ["Ministry of Finance", "Ministry of Health and Family Welfare", "Ministry of Statistics"],
     "The Registrar General and Census Commissioner functions under the Ministry of Home Affairs.\\nHence, Option {{CORR}} is correct.", "Names the administrative ministry of the Census."),
    ("mcq", CH_DEMO, "NFHS-5 National TFR",
     "According to the National Family Health Survey-5 (2019-21), India's national Total Fertility Rate (TFR) stood at:",
     "2.0 children per woman (below replacement level)", ["3.2 children per woman", "4.1 children per woman", "1.1 children per woman"],
     "NFHS-5 recorded a national TFR of 2.0, dropping below replacement level of 2.1.\\nHence, Option {{CORR}} is correct.", "Recalls NFHS-5 fertility finding."),
    ("mcq", CH_DEMO, "Janani Suraksha Yojana Role",
     "What is the primary intervention of the Janani Suraksha Yojana (JSY) under the National Health Mission?",
     "Conditional cash transfers to incentivize pregnant women to deliver in healthcare institutions",
     ["Free overseas airfare for pediatric specialists", "Mandatory home childbirth for all rural mothers", "Free private vehicles for all expectant fathers"],
     "JSY provides cash transfers to encourage institutional deliveries and reduce maternal mortality.\\nHence, Option {{CORR}} is correct.", "Explains Janani Suraksha Yojana."),
    ("stmt", CH_DEMO, "Sample Registration System (SRS)",
     "The Sample Registration System (SRS) provides continuous annual estimates of birth and death rates in India.",
     "The SRS relies strictly on an unverified single-survey postcard questionnaire once every twenty years.", 3,
     "Statement I is correct; Statement II is incorrect as SRS is a dual-record system with continuous registration.\\nHence, Option {{CORR}} is correct.", "Defines Sample Registration System."),
    ("ar", CH_DEMO, "Population Momentum Reality",
     "India's population will continue to grow for several decades even after achieving replacement fertility.",
     "A large youth cohort entering reproductive age generates demographic momentum despite lower individual family sizes.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Population momentum ensures growth even after TFR reaches 2.1.\\nHence, Option {{CORR}} is correct.", "Explains population momentum mechanics."),
    ("mcq", CH_DEMO, "1931 Census Historical Significance",
     "Why does the 1931 British Indian Census under J.H. Hutton remain historic in Indian sociological studies?",
     "It was the last decennial census to carry out and publish complete caste-wise enumeration for all social groups",
     ["It was the first census conducted entirely via electronic mainframe computers", "It completely omitted counting women and children nationwide", "It recorded zero deaths across the entire subcontinent"],
     "The 1931 Census was the last to publish comprehensive caste-wise enumeration data for all communities.\\nHence, Option {{CORR}} is correct.", "Recognizes 1931 Census significance."),
    ("mcq", CH_DEMO, "Two-Child Norm Critique",
     "Sociological critiques of the 'two-child norm' for contesting local Panchayat elections argue that:",
     "It disproportionately discriminates against women and marginalized castes who have limited reproductive autonomy",
     ["It encourages large corporate monopolies to take over village agriculture", "It bans all village sarpanches from owning tractors", "It forces village panchayats to speak foreign languages"],
     "The norm penalizes women and disadvantaged groups who lack control over family planning decisions.\\nHence, Option {{CORR}} is correct.", "Understands critique of two-child norm in local polls."),
    ("mcq", CH_DEMO, "SECC 2011 Distinction",
     "How did the Socio-Economic and Caste Census (SECC) 2011 differ fundamentally from the regular decennial Census?",
     "SECC was an open enumeration to determine welfare beneficiary eligibility, unlike the confidential statutory Census",
     ["SECC counted only domestic pets and dairy cattle", "SECC was conducted exclusively in foreign universities", "SECC had zero government involvement or financing"],
     "SECC was an open survey to identify poor households for targeted welfare programmes.\\nHence, Option {{CORR}} is correct.", "Contrasts SECC 2011 with decennial census."),
    ("stmt", CH_DEMO, "National Population Stabilization Fund",
     "The Jansankhya Sthirata Kosh (JSK) was established to promote civil society participation in population stabilization.",
     "The JSK is empowered to deploy armed police units to enforce compulsory vasectomies in rural districts.", 3,
     "Statement I is correct; Statement II is incorrect as JSK promotes voluntary reproductive health initiatives.\\nHence, Option {{CORR}} is correct.", "Clarifies role of Jansankhya Sthirata Kosh."),
    ("ar", CH_DEMO, "Target-Free Approach Benefits",
     "Target-free reproductive health approaches achieved higher public trust and voluntary contraceptive adoption.",
     "Coercive administrative targets historically led to falsified records and widespread public alienation from health clinics.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Voluntary client-centered care is more sustainable than quotas.\\nHence, Option {{CORR}} is correct.", "Explains efficacy of target-free reproductive care."),
    ("mcq", CH_DEMO, "Hum Do Hamare Do Slogan",
     "The iconic slogan 'Hum Do, Hamare Do' and the inverted red triangle symbol represented:",
     "The Indian state's campaign promoting the small two-child family norm",
     ["A campaign encouraging families to own two commercial automobiles", "A promotional drive for industrial steel production", "An advertising campaign for railway ticketing"],
     "'Hum Do, Hamare Do' popularized the small family norm in post-independence India.\\nHence, Option {{CORR}} is correct.", "Identifies 'Hum Do, Hamare Do' symbolism."),
    ("mcq", CH_DEMO, "Replacement Level TFR Threshold",
     "Demographers universally define 'Replacement Level Fertility' as a Total Fertility Rate of approximately:",
     "2.1 children per woman", ["1.0 children per woman", "3.5 children per woman", "5.0 children per woman"],
     "A TFR of 2.1 ensures population replacement accounting for infant and child mortality.\\nHence, Option {{CORR}} is correct.", "Defines 2.1 replacement level threshold.")
]
assert len(s5) == 20
slots[5] = s5

print("Slot 5 constructed.")
