# Script to write Slots 3 to 6
s3_to_6 = '''
# ==============================================================================
# Slot 3: Carrying Capacity, Ecological Footprint & Urbanization
# ==============================================================================
s3_raw = [
    ("mcq", "Carrying Capacity Definition",
     "In ecology, Carrying Capacity (K) is defined as the maximum population size of a biological species that can be sustained in a specific environment indefinitely, given the:",
     "Food, habitat, water, and other necessities available in the environment",
     ["Absolute physical volume of geological continental crust", "Total photosynthetic solar flux reaching the upper atmosphere", "Rate of industrial energy generation in urban zones"],
     "Carrying capacity represents the maximum population an ecosystem can support without environmental degradation."),
    ("stmt", "Ecological Footprint and Biocapacity",
     "The Ecological Footprint measures the ecological assets that a given population or product requires to produce the natural resources it consumes and to absorb its waste.",
     "Biocapacity represents the productivity of an area's ecological assets, including cropland, grazing land, forest land, and fishing grounds.", 1,
     "Both Statement I and Statement II are correct. Ecological footprint evaluates human demand, whereas biocapacity evaluates nature's regenerative supply."),
    ("ar", "Global Ecological Deficit",
     "An ecological deficit occurs when a nation's ecological footprint exceeds the biocapacity of the area available to that nation.",
     "A nation in ecological deficit meets its demand by importing goods, liquidating its own ecological assets, and emitting carbon dioxide into the global commons.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Exceeding local biocapacity forces a population to draw upon external resources or degrade its natural capital."),
    ("match", "Urbanization Concepts and Environmental Impacts",
     "Match the urbanization phenomenon in List I with its ecological effect in List II:",
     [("A", "Urban Heat Island (UHI)"),
      ("B", "Impervious Surface Runoff"),
      ("C", "Urban Slum Settlements"),
      ("D", "Light Pollution")],
     [("I", "Elevated ambient surface temperatures caused by asphalt, concrete, and waste anthropogenic heat"),
      ("II", "Reduced groundwater recharge and amplified flash flooding due to paved urban soil"),
      ("III", "Severe sanitation deficits, untreated sewage discharge, and waterborne disease outbreaks"),
      ("IV", "Disruption of nocturnal wildlife behavior, bird navigation, and human circadian rhythms")],
     "A-I, B-II, C-III, D-IV",
     "UHI raises city temperatures, paved surfaces cause runoff flooding, slums suffer sanitation crises, and light pollution disrupts nocturnal ecology."),
    ("mcq", "Earth Overshoot Day",
     "What does 'Earth Overshoot Day', calculated annually by the Global Footprint Network, signify?",
     "The calendar date on which humanity's resource consumption exceeds what Earth can regenerate in that entire year",
     ["The day when Earth reaches its closest orbital approach to the Sun", "The global date when atmospheric carbon dioxide crosses 450 ppm", "The date when all global coal and petroleum reserves are exhausted"],
     "Earth Overshoot Day marks the date when humanity's annual demand on ecological resources exceeds the planet's biocapacity for that year."),
    ("mcq", "Global Footprint Unit of Measurement",
     "In what standardized unit is the Ecological Footprint formally measured and reported?",
     "Global hectares (gha)",
     ["Metric tons of carbon equivalent", "Kilowatt hours per capita", "Parts per million (ppm)"],
     "Ecological Footprint and biocapacity are expressed in 'global hectares' (gha), standardized hectares with world-average biological productivity."),
    ("stmt", "IPAT Equation Components",
     "The IPAT equation, formulated by Paul Ehrlich and John Holdren, models human environmental impact as: Impact = Population x Affluence x Technology.",
     "In the IPAT model, 'Affluence' represents average per capita consumption of resources, while 'Technology' represents the environmental damage per unit of consumption.", 1,
     "Both Statement I and Statement II are correct. I = P x A x T quantifies how population, per capita consumption (affluence), and technology drive environmental impact."),
    ("seq", "Sequence of Urban Hydrological Impact",
     "Arrange the stages illustrating how rapid, unplanned urbanization degrades natural drainage basins:",
     ["Replacement of permeable soils and vegetative cover with impermeable asphalt and concrete", "Loss of natural rainfall infiltration and depletion of local groundwater aquifers", "Drastic acceleration of peak surface runoff during intense monsoon precipitation", "Severe urban flash flooding and submergence of low-lying settlements"],
     "I -> II -> III -> IV",
     "Paving soil prevents infiltration, depleting aquifers, accelerating runoff volumes, and resulting in devastating urban flash floods."),
    ("mcq", "Sink vs Source Functions of Ecosystem",
     "The capacity of natural ecosystems to absorb, assimilate, and render harmless anthropogenic wastes and pollutants without collapsing is known as the:",
     "Sink function of the ecosystem",
     ["Source function of the ecosystem", "Consumptive use value", "Productive use value"],
     "The sink function refers to the environment's ability to absorb, buffer, and process waste products generated by human economic activity."),
    ("ar", "Urban Heat Island Mitigation",
     "Installing green vegetative roofs and planting continuous urban tree canopies significantly cools metropolitan microclimates.",
     "Vegetation actively lowers ambient air temperatures through evapotranspiration and shades building surfaces from solar radiation absorption.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Evapotranspiration converts solar heat into latent heat, actively lowering city temperatures."),
    ("mcq", "Ecological Overshoot Consequence",
     "When a population's consumption levels exceed the environment's carrying capacity for a prolonged duration, the eventual ecological consequence is typically:",
     "Ecosystem degradation followed by a severe population crash or dieback",
     ["Instantaneous biological evolution of new perpetual food sources", "Permanent stabilization of the carrying capacity at higher levels", "Complete elimination of all biotic and abiotic competition"],
     "Prolonged ecological overshoot depletes life-support capital, triggering resource collapse and subsequent population dieback."),
    ("mcq", "Urban Sprawl Environmental Cost",
     "The low-density, car-dependent geographic expansion of cities into surrounding agricultural and forested landscapes is termed:",
     "Urban sprawl",
     ["Vertical densification", "Brownfield redevelopment", "Ecological succession"],
     "Urban sprawl consumes arable farm lands, fragments natural habitats, and sharply escalates per capita transport emissions."),
    ("match", "Environmental Footprints and Indicators",
     "Match the ecological footprint indicator in List I with its specific focus in List II:",
     [("A", "Carbon Footprint"),
      ("B", "Water Footprint"),
      ("C", "Nitrogen Footprint"),
      ("D", "Material Footprint")],
     [("I", "Total greenhouse gas emissions caused directly and indirectly by an entity, expressed as CO2 equivalent"),
      ("II", "Volume of freshwater utilized to produce goods and services, divided into blue, green, and grey water"),
      ("III", "Amount of reactive nitrogen lost to the environment from food production and fossil fuel burning"),
      ("IV", "Total raw material extraction (biomass, minerals, fossil fuels) required to meet final consumption")],
     "A-I, B-II, C-III, D-IV",
     "Carbon footprint tracks greenhouse gases, water footprint tracks freshwater consumption, nitrogen footprint measures reactive N releases, and material footprint quantifies raw resources."),
    ("mcq", "Virtual Water Concept",
     "The hidden volume of freshwater consumed, evaporated, or polluted in the step-by-step production of an agricultural or industrial commodity is known as:",
     "Virtual water / Embedded water",
     ["Distilled water", "Heavy water", "Leachate water"],
     "Virtual water refers to the total freshwater embedded invisibly within a product across its entire supply chain (e.g., ~2,500 liters for 1 kg of rice)."),
    ("mcq", "Grey Water Footprint Definition",
     "In the water footprint methodology, what does the 'Grey Water Footprint' represent?",
     "The volume of freshwater required to assimilate the load of pollutants to reach agreed water quality standards",
     ["The volume of rainwater consumed during crop growth stored in the soil", "The volume of surface and groundwater consumed for industrial processing", "The volume of untreated seawater used in thermal cooling towers"],
     "Grey water footprint quantifies the freshwater volume needed to dilute discharged pollutants back to acceptable ambient standards."),
    ("stmt", "Urban Solid Waste Composition in Developing Nations",
     "Municipal solid waste generated in developing nations typically contains a high proportion of organic, biodegradable food waste (over 50%).",
     "Developed nations typically generate waste streams dominated by higher percentages of paper, packaging, plastics, and discarded electronics.", 1,
     "Both Statement I and Statement II are correct. Low/middle-income cities generate predominantly organic moisture-heavy waste, whereas wealthy nations produce more packaging and e-waste."),
    ("mcq", "Smart Cities and Environmental Sustainability",
     "Under India's Smart Cities Mission, which urban planning strategy is emphasized to reduce vehicular carbon emissions and smog?",
     "Non-motorized transport (NMT), integrated cycling lanes, and electric mass transit networks",
     ["Constructing multi-tier elevated expressways cutting through urban biodiversity parks", "Banning all pedestrian walkways to speed up private car traffic", "Mandating daily diesel generator backups across all residential sectors"],
     "Sustainable smart city planning focuses on high-capacity mass transit, non-motorized infrastructure, and walking/cycling networks to curb emissions."),
    ("seq", "Stages of Environmental Impact of Megacities",
     "Arrange the historical progression of urban environmental challenges as cities develop from low to high income:",
     ["Local sanitary crises: unsafe drinking water, open sewage, and indoor biomass smoke", "Regional industrial pollution: severe urban sulfur dioxide, particulate smog, and toxic river discharge", "Metropolitan automotive emissions: nitrogen oxides, photochemical smog, and suburban sprawl", "Global consumer footprints: excessive per capita carbon emissions, electronic waste, and embodied resource imports"],
     "I -> II -> III -> IV",
     "The urban environmental evolution progresses from basic poverty-related sanitation deficits to industrial pollution, automotive smog, and finally high-consumption global impacts."),
    ("mcq", "Circular Economy Core Philosophy",
     "A sustainable 'Circular Economy' replaces the traditional linear 'take-make-dispose' industrial model by prioritizing:",
     "Designing out waste, keeping products and materials in high-value use, and regenerating natural systems",
     ["Increasing mining output to flood manufacturing with ultra-cheap raw materials", "Incinerating all plastics in open cement kilns to bypass recycling facilities", "Maximizing planned obsolescence to accelerate consumer gadget replacement"],
     "A circular economy decouples economic activity from finite resource consumption through reuse, repair, remanufacturing, and closed-loop recycling."),
    ("mcq", "Ecological Rucksack Definition",
     "The total weight of all natural materials displaced and consumed to produce, use, and dispose of a consumer product (minus the weight of the product itself) is called its:",
     "Ecological rucksack",
     ["Biomass quotient", "Trophic yield", "Carrying coefficient"],
     "Ecological rucksack (developed by Friedrich Schmidt-Bleek at the Wuppertal Institute) quantifies the hidden material baggage displaced during manufacture.")
]

# ==============================================================================
# Slot 4: Traditional Ecological Wisdom & Indigenous Water Harvesting
# ==============================================================================
s4_raw = [
    ("mcq", "Ahar-Pyne System of Bihar",
     "The traditional indigenous irrigation and rainwater harvesting system indigenous to south Bihar, comprising an embankment catchment and canal network, is known as:",
     "Ahar-Pyne system",
     ["Kulh system", "Johad system", "Surangam system"],
     "The Ahar-Pyne system is a floodwater harvesting network in South Bihar where 'Ahars' are catchments with 3-sided embankments and 'Pynes' are diversion channels."),
    ("stmt", "Kulhs of Himachal Pradesh",
     "Kulhs are traditional community-managed water channels in the mountainous regions of Himachal Pradesh that carry meltwater from glaciers to village fields.",
     "The distribution of water in a Kulh system was historically negotiated communally without private water monopolies.", 1,
     "Both Statement I and Statement II are correct. Kulhs channel Himalayan snowmelt across contours, managed by traditional village water masters (Kohlis)."),
    ("ar", "Johads of Rajasthan and River Rejuvenation",
     "The construction of traditional earthen check-dams known as Johads in Alwar, Rajasthan, successfully revived perennial flow in dried-up rivers like Arvari.",
     "Johads capture monsoon runoff, retarding surface flow and facilitating deep percolation to recharge underlying groundwater aquifers.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Revived groundwater from Johads maintains baseflow in streams long after the monsoon ends, as demonstrated by Rajendra Singh."),
    ("match", "Traditional Water Harvesting Systems and States",
     "Match the traditional water harvesting system in List I with its native Indian state/region in List II:",
     [("A", "Ahar-Pyne"),
      ("B", "Johad"),
      ("C", "Surangam"),
      ("D", "Zing")],
     [("I", "Bihar"),
      ("II", "Rajasthan"),
      ("III", "Kerala / Karnataka border (Kasargod)"),
      ("IV", "Ladakh")],
     "A-I, B-II, C-III, D-IV",
     "Ahar-Pyne belongs to Bihar, Johad to Rajasthan, Surangam (horizontal cave wells) to Kasargod in Kerala/Karnataka, and Zing (meltwater tanks) to Ladakh."),
    ("mcq", "Waterman of India",
     "Which environmental activist received the Ramon Magsaysay Award and Stockholm Water Prize for mobilizing rural communities to build thousands of Johads in Rajasthan?",
     "Rajendra Singh",
     ["Sundarlal Bahuguna", "Chandi Prasad Bhatt", "Anil Agarwal"],
     "Rajendra Singh, known as the 'Waterman of India' and founder of Tarun Bharat Sangh, revived arid rivers in Rajasthan using traditional Johads."),
    ("mcq", "Sacred Groves Ecological Significance",
     "Sacred Groves (e.g. Deorais in Maharashtra, Orans in Rajasthan, Kavu in Kerala, Law Kyntang in Meghalaya) represent traditional conservation practices because they:",
     "Protect pristine climax vegetation and endemic biodiversity through community-enforced religious and cultural taboos against felling and hunting",
     ["Provide government-designated land for private commercial eucalyptus plantations", "Function as open-pit gravel extraction sites for public works", "Serve exclusively as industrial wood-pulp processing centers"],
     "Sacred groves are community-protected forest patches preserved through religious sanctions, serving as crucial refugia for rare and threatened flora and fauna."),
    ("stmt", "Baolis and Stepwells",
     "Baolis or Vavs are traditional subterranean stepwells built extensively in Gujarat and Rajasthan to access deep water tables and provide cool communal resting spaces.",
     "Rani ki Vav in Patan, Gujarat, is a UNESCO World Heritage site exemplifying the architectural and hydrological sophistication of historic Indian stepwells.", 1,
     "Both Statement I and Statement II are correct. Stepwells (Baolis/Vavs) allowed multi-level seasonal access to fluctuating groundwater in arid Western India."),
    ("seq", "Working Principle of a Johad Water System",
     "Arrange the hydrological steps involved in groundwater revitalization via a traditional earthen Johad:",
     ["Heavy, episodic monsoon rainfall falls over undulating, degraded arid slopes", "The curved earthen embankment constructed across the natural contour traps and pools the rushing surface runoff", "The impounded water is held in the basin, retarding destructive erosion and enabling steady percolation into the subsoil", "The local unconfined water table rises, recharging nearby open drinking wells and reviving dry stream baseflows"],
     "I -> II -> III -> IV",
     "Johads catch runoff on contours, retain water in basins, promote steady infiltration, and recharge the regional water table."),
    ("mcq", "Bamboo Drip Irrigation of Meghalaya",
     "In the Jaintia and Khasi hills of Meghalaya, a centuries-old indigenous system utilizes bamboo pipes to divert perennial spring water directly to:",
     "Black pepper and betel-leaf roots drop-by-drop over hundreds of meters",
     ["Submerged lowland paddy fields with continuous flooding", "Deep underground municipal water storage cisterns", "Industrial coal washing operations"],
     "The bamboo drip irrigation system of Meghalaya channels 18–20 liters per minute from hill springs, delivering it drop-by-drop (20–80 drops/min) to betel vines."),
    ("ar", "Sacred Groves and Microclimate",
     "Sacred groves frequently conserve perennial water springs and maintain a humid local microclimate during severe droughts.",
     "The dense, multi-tiered forest canopy and undisturbed leaf litter inside sacred groves maximize soil water retention and minimize evaporative losses.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The intact climax forest structure preserves soil sponges, sustaining perennial spring discharge."),
    ("mcq", "Tankas of Thar Desert",
     "In the arid regions of Rajasthan, an underground circular cistern built inside household courtyards to harvest rainwater from clean artificial catchments is called a:",
     "Tanka",
     ["Khadin", "Bandhara", "Eri"],
     "A Tanka is an underground rainwater storage tank built in courtyards or fields in the Thar desert, providing pure drinking water throughout dry months."),
    ("mcq", "Khadin System of Jaisalmer",
     "The 'Khadin' (also called Dhora) system, designed by the Paliwal Brahmins of Jaisalmer in the 15th century, is an ingenious combination of:",
     "Rainwater harvesting and runoff-fed agriculture on moisture-retaining soils",
     ["Geothermal power extraction and sulfur refining", "Open canal irrigation carrying river water across thousands of kilometers", "Commercial freshwater fish breeding in hyper-saline desert depressions"],
     "Khadins impound monsoon runoff behind an earthen bund; when water dries, crops like wheat and chickpea are cultivated on the saturated fertile silt."),
    ("match", "Regional Water Harvesting Terms in India",
     "Match the indigenous water harvesting structure in List I with its regional location in List II:",
     [("A", "Khadin"),
      ("B", "Eri (Tank)"),
      ("C", "Bandhara"),
      ("D", "Surangam")],
     [("I", "Jaisalmer, Rajasthan"),
      ("II", "Tamil Nadu"),
      ("III", "Maharashtra"),
      ("IV", "Western Ghats, Kerala")],
     "A-I, B-II, C-III, D-IV",
     "Khadins are found in Jaisalmer, Eris are cascade tanks in Tamil Nadu, Bandharas are check weirs in Maharashtra, and Surangams are horizontal tunnel wells in Kerala."),
    ("mcq", "Zing System of Cold Deserts",
     "In the cold desert of Ladakh, how does the traditional 'Zing' water system manage glacial meltwater?",
     "It collects trickle meltwater in a small reservoir overnight to irrigate barley fields early the following morning",
     ["It boils subsurface permafrost using concentrated wood combustion", "It pumps groundwater using high-altitude solar-powered submersible pumps", "It transports river water via insulated plastic pipelines over mountain passes"],
     "In Ladakh, glacial streams trickle slowly in morning cold; Zings collect meltwater during the day and night so farmers can irrigate fields efficiently."),
    ("mcq", "Bandharas of Maharashtra",
     "In Maharashtra, 'Bandharas' are traditional check weirs constructed across streams primarily to:",
     "Raise the water level of rivers so that water can flow directly into diversion irrigation channels (phads)",
     ["Generate hydroelectric power for sugar cooperatives", "Trap migratory marine fish during monsoon spawning", "Store chemical effluents from nearby chemical manufacturing plants"],
     "Bandharas are masonry or earthen check-dams built across rivers in Maharashtra to divert water into canal networks known as the Phad irrigation system."),
    ("stmt", "Bishnoi Ecological Tradition",
     "The Bishnoi community of Rajasthan follows 29 religious principles laid down by Guru Jambheshwar in the 15th century.",
     "A central tenet of the Bishnoi faith prohibits the felling of any green tree (especially Khejri) and forbids the hunting of all wild animals.", 1,
     "Both Statement I and Statement II are correct. The Bishnois have protected Khejri trees and blackbucks for centuries, leading to the historic 1730 Khejarli sacrifice."),
    ("mcq", "Amrita Devi Khejarli Massacre",
     "In 1730 at Khejarli village near Jodhpur, Amrita Devi Bishnoi and 362 other Bishnois sacrificed their lives to protect which sacred tree from the Maharaja's axemen?",
     "Prosopis cineraria (Khejri tree)",
     ["Ficus religiosa (Peepal tree)", "Azadirachta indica (Neem tree)", "Tectona grandis (Teak tree)"],
     "Amrita Devi and 362 Bishnois were martyred in 1730 hugging Khejri trees (Prosopis cineraria), an act that inspired modern eco-movements like Chipko."),
    ("seq", "Traditional Rainwater Cascade Architecture",
     "Arrange the connected elements of a traditional South Indian 'Eri' (cascade tank) system from upland to valley:",
     ["Forested hill catchment generating clean surface runoff", "Upper feeder channel diverting water into the primary reservoir", "Interconnected chain of downstream irrigation tanks capturing overflow", "Sluice gates releasing regulated gravity-fed water into communal agricultural fields"],
     "I -> II -> III -> IV",
     "The traditional Eri system captures runoff from hills, fills a series of cascading tanks, and irrigates paddy fields via regulated sluices."),
    ("mcq", "Surangam Horizontal Wells",
     "What geological feature enables the construction of traditional 'Surangam' horizontal cave wells in northern Kerala and southern Karnataka?",
     "Porous, hard laterite hill formations that yield steady groundwater filtration along horizontal adits without roof collapse",
     ["Loose, shifting sand dunes requiring timber support framing", "Impermeable basaltic trap rock completely devoid of fractures", "Deep alluvial riverbeds prone to annual seasonal flooding"],
     "Laterite hills in Kasargod allow digging horizontal cave tunnels (Surangams) up to several hundred meters that tap groundwater seeping through laterite pores."),
    ("mcq", "National Water Mission Slogan",
     "Which contemporary national campaign by the Ministry of Jal Shakti draws inspiration from India's traditional rainwater harvesting legacy?",
     "'Catch the Rain, where it falls, when it falls'",
     ["'Water for Industries, Dams for Growth'", "'Export Water, Import Food'", "'Pump Deep, Farm Fast'"],
     "The 'Catch the Rain' campaign emphasizes decentralized, community-based rainwater harvesting and revival of traditional water bodies.")
]

# ==============================================================================
# Slot 5: Population Ecology (Attributes, Age Structure, Survivorship, r/K)
# ==============================================================================
s5_raw = [
    ("mcq", "Population Attributes vs Individual Attributes",
     "Which of the following biological attributes applies exclusively to an ecological population and NOT to an individual organism?",
     "Birth rate, death rate, and sex ratio",
     ["Birth, death, and respiration", "Cellular metabolism and growth", "Thermoregulation and excretion"],
     "An individual is born and dies, but a population possesses birth rates, death rates, sex ratios, and age structures."),
    ("stmt", "Natality and Mortality Rates",
     "Natality refers to the number of births per unit of population per unit time in a given habitat.",
     "Mortality refers to the number of deaths per unit of population per unit time in a given habitat.", 1,
     "Both Statement I and Statement II are correct. Natality and mortality represent the primary demographic vital rates of population ecology."),
    ("ar", "Age Pyramids and Population Projection",
     "An age pyramid with a broad base of pre-reproductive individuals indicates a rapidly growing and expanding population.",
     "When a high percentage of individuals are in young, prereproductive age classes, a large cohort will soon enter their reproductive lifespan.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Triangular age pyramids with broad bases reflect high birth rates and rapid future momentum."),
    ("match", "Age Pyramid Types and Population Trajectories",
     "Match the age pyramid shape in List I with its demographic growth trajectory in List II:",
     [("A", "Triangular pyramid with wide base"),
      ("B", "Bell-shaped pyramid with even cohorts"),
      ("C", "Urn-shaped pyramid with narrow base"),
      ("D", "Inverted pyramid")],
     [("I", "Expanding population with high percentage of young individuals"),
      ("II", "Stable population where pre-reproductive and reproductive cohorts are roughly equal"),
      ("III", "Declining population with very low proportion of prereproductive individuals"),
      ("IV", "Severely contracting population with an elderly demographic bulge")],
     "A-I, B-II, C-III, D-IV",
     "Triangular represents expanding growth, bell-shaped is stable, urn-shaped is declining, and inverted represents severe contraction."),
    ("mcq", "Vital Factors Determining Population Density",
     "If 'N' is population density at time 't', which formula correctly calculates population density at time 't+1' incorporating all four vital demographic processes?",
     "N(t+1) = N(t) + [(B + I) - (D + E)]",
     ["N(t+1) = N(t) + [(B + D) - (I + E)]", "N(t+1) = N(t) x [(B + I) / (D + E)]", "N(t+1) = N(t) - [(B + I) + (D + E)]"],
     "Population growth formula is N(t+1) = N(t) + [(B + I) - (D + E)], where B = Births, I = Immigration, D = Deaths, and E = Emigration."),
    ("mcq", "Survivorship Curve Type I",
     "A Type I survivorship curve (convex shape) is characteristic of species like humans and large mammals that exhibit:",
     "High survival rates throughout early and middle life, followed by high mortality primarily in old age",
     ["High early juvenile mortality with very few individuals reaching maturity", "A constant, uniform mortality rate across all life stages", "Zero mortality until an instantaneous mass die-off occurs"],
     "Type I survivorship (e.g. humans, elephants) features high parental investment, low juvenile mortality, and death concentrated in old age."),
    ("stmt", "Type II and Type III Survivorship Curves",
     "A Type II survivorship curve shows a constant mortality rate throughout an organism's entire lifespan (diagonal linear decline).",
     "A Type III survivorship curve (concave shape) shows extremely high mortality among juveniles, but individuals that survive to maturity live relatively long lives.", 1,
     "Both Statement I and Statement II are correct. Songbirds and hydra show Type II; oysters, pelagic fish, and oak trees exhibit Type III."),
    ("seq", "Sequence of Population Demographic Processes",
     "Arrange the demographic events that cause an ecological population to transition from initial colonization to stabilization:",
     ["Immigration of initial founder individuals into an unoccupied, resource-rich habitat", "Rapid natality exceeding mortality in the absence of density-dependent limits", "Emergence of environmental resistance as resources become limited near carrying capacity", "Natality plus immigration equals mortality plus emigration, achieving demographic equilibrium"],
     "I -> II -> III -> IV",
     "Colonization begins with immigration, explosive growth follows, environmental resistance sets in, and vital rates balance at carrying capacity."),
    ("mcq", "r-Selected Species Characteristics",
     "Which suite of biological traits is characteristic of 'r-selected' opportunistic species (e.g., bacteria, weeds, insects)?",
     "Small body size, rapid development, early sexual maturity, production of numerous small offspring, and minimal parental care",
     ["Large body size, delayed maturity, long lifespan, production of one or two offspring, and intense parental care", "Constant population size hovering precisely at carrying capacity", "Specialized ecological niches with high competitive dominance in climax communities"],
     "r-selected species maximize intrinsic rate of increase (r) by producing many offspring rapidly with minimal investment per offspring."),
    ("ar", "K-Selected Species Vulnerability to Extinction",
     "K-selected species (e.g., tigers, elephants, blue whales) are far more susceptible to human-induced extinction than r-selected species.",
     "K-selected species have long generation times, low reproductive outputs, large body sizes, and require extensive home ranges.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Low reproductive turnover and specialized habitat needs make K-selected species slow to recover from hunting and habitat loss."),
    ("mcq", "Biotic Potential Definition",
     "Biotic potential (r_max) represents the maximum reproductive capacity of a population under:",
     "Ideal, unrestricted environmental conditions with unlimited resources and absence of disease and predation",
     ["Severe, prolonged drought and famine conditions", "Intense interspecific competition at carrying capacity", "Sub-zero temperatures and toxic chemical pollution"],
     "Biotic potential is the maximum rate of natural increase an organism can achieve under completely optimal, unrestricted environmental conditions."),
    ("mcq", "Environmental Resistance Concept",
     "The sum total of all limiting factors (abiotic and biotic) that act together to prevent a population from achieving its theoretical biotic potential is called:",
     "Environmental resistance",
     ["Carrying capacity surplus", "Biotic enhancement", "Demographic dividend"],
     "Environmental resistance encompasses all factors (food scarcity, predation, parasitism, space limits, disease) that constrain population growth."),
    ("match", "r-Selected vs K-Selected Traits",
     "Match the life-history trait in List I with its corresponding evolutionary strategy in List II:",
     [("A", "High fecundity with tiny propagules"),
      ("B", "Intensive parental care and investment"),
      ("C", "Type III survivorship curve"),
      ("D", "Population density regulated near carrying capacity (K)")],
     [("I", "r-selection"),
      ("II", "K-selection"),
      ("III", "r-selection"),
      ("IV", "K-selection")],
     "A-I, B-II, C-III, D-IV",
     "r-selection favors high fecundity and Type III survivorship; K-selection favors parental care and density maintenance near K."),
    ("mcq", "Density-Dependent Limiting Factors",
     "Which of the following is a classic 'density-dependent' limiting factor whose per-capita effect increases as population density rises?",
     "Contagious disease transmission and intraspecific competition for food",
     ["Volcanic eruption covering habitat in ash", "Severe hurricane blowing through a forest", "Unprecedented frost freezing an entire lake"],
     "Density-dependent factors (disease, competition, predation, waste buildup) intensify as population density increases, unlike abiotic catastrophes."),
    ("mcq", "Density-Independent Limiting Factors",
     "A forest fire that incinerates an ecosystem regardless of whether there are 10 or 10,000 deer living in the valley is an example of a:",
     "Density-independent factor",
     ["Density-dependent factor", "Biotic potential factor", "K-selection factor"],
     "Density-independent factors (frosts, floods, volcanic eruptions, forest fires) affect population mortality independently of local density."),
    ("stmt", "Allee Effect in Population Ecology",
     "The Allee effect describes a biological phenomenon where individual fitness and per capita population growth rate decline at very low population densities.",
     "At extremely low population densities, individuals may struggle to locate mates, maintain group foraging defenses, or prevent inbreeding depression.", 1,
     "Both Statement I and Statement II are correct. The Allee effect highlights that underpopulated species face increased extinction risks due to social or reproductive breakdown."),
    ("mcq", "Dispersal Mechanisms: Emigration vs Immigration",
     "The permanent outward movement of individuals from their native local population into a new geographic territory is termed:",
     "Emigration",
     ["Immigration", "Natality", "Biotic potential"],
     "Emigration is outward dispersal from a population, whereas immigration is inward arrival of individuals from another area."),
    ("seq", "Evolutionary Transition from Colonizer to Climax Dominant",
     "Arrange the stages of population strategy succession following an ecological disturbance:",
     ["Disturbed barren substrate is colonized by opportunistic r-selected annual pioneer species", "Pioneer species rapidly reproduce, stabilize topsoil, and enrich organic detritus", "Intermediate perennial species establish, increasing community competition for light and nutrients", "Highly competitive, long-lived K-selected species establish and dominate the mature climax community"],
     "I -> II -> III -> IV",
     "Ecological succession begins with r-selected pioneers, progresses through intermediate perennials, and culminates in K-selected climax species."),
    ("mcq", "Age Pyramid of India Today",
     "Based on recent National Family Health Survey (NFHS-5) and demographic data, India's overall age pyramid is currently transitioning from:",
     "A rapid broad-based triangular pyramid toward a stationary bell-shaped structure",
     ["An urn-shaped pyramid directly to an inverted pyramid", "A bell-shaped pyramid back to a steep pre-industrial triangle", "A completely flat rectangle with zero infants"],
     "India's TFR has declined to 2.0 (below replacement level 2.1), shifting its demographic pyramid from a wide-base triangle to a stabilizing bell shape."),
    ("mcq", "Minimum Viable Population (MVP)",
     "The smallest isolated population size that has a 99% probability of persisting for 1,000 years despite environmental, genetic, and demographic stochasticity is known as:",
     "Minimum Viable Population (MVP)",
     ["Carrying capacity", "Biotic potential", "Optimum sustainable yield"],
     "Minimum Viable Population (MVP), formulated by Mark Shaffer, is the ecological threshold below which a population faces high extinction risk.")
]

# ==============================================================================
# Slot 6: Population Growth Models (Exponential, Logistic, Interactions)
# ==============================================================================
s6_raw = [
    ("mcq", "Exponential Growth Equation",
     "Under conditions of unlimited food, space, and absence of environmental resistance, population growth is geometric and described by which differential equation?",
     "dN / dt = rN",
     ["dN / dt = rN ((K - N) / K)", "dN / dt = r / N", "dN / dt = (B - D) / K"],
     "Exponential growth is modeled by dN/dt = rN, where r is the intrinsic rate of natural increase and N is population size."),
    ("stmt", "J-Shaped vs S-Shaped Growth Curves",
     "Exponential population growth yields a J-shaped curve when population density is plotted against time.",
     "Logistic population growth yields an S-shaped (sigmoid) curve as environmental resistance slows growth near carrying capacity.", 1,
     "Both Statement I and Statement II are correct. Exponential growth produces a J-curve, whereas logistic density-dependent growth forms a sigmoid S-curve."),
    ("ar", "Logistic Growth Realism",
     "In nature, logistic growth is considered a far more realistic model of population dynamics than exponential growth.",
     "No habitat on Earth has infinite resources to sustain uninhibited exponential population growth indefinitely.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Finite resources (food, shelter, space) invariably impose density-dependent limits, making the logistic model realistic."),
    ("match", "Mathematical Variables in Logistic Growth",
     "Match the mathematical symbol in List I from the Verhulst-Pearl logistic equation with its biological meaning in List II:",
     [("A", "N"),
      ("B", "r"),
      ("C", "K"),
      ("D", "(K - N) / K")],
     [("I", "Population density at time t"),
      ("II", "Intrinsic rate of natural increase"),
      ("III", "Carrying capacity of the environment"),
      ("IV", "Fraction of environmental resources still available for growth (environmental resistance factor)")],
     "A-I, B-II, C-III, D-IV",
     "In dN/dt = rN((K-N)/K), N is density, r is intrinsic growth rate, K is carrying capacity, and (K-N)/K represents remaining resource capacity."),
    ("mcq", "Inflection Point in Logistic Growth",
     "At what population size does a population following the logistic growth model experience its maximum absolute growth rate (dN/dt)?",
     "At N = K / 2 (half of the carrying capacity)",
     ["At N = K (at the carrying capacity)", "At N = 0 (at initial colonization)", "At N = 2K (in population overshoot)"],
     "The maximum rate of population increase occurs at the inflection point of the sigmoid curve, exactly at N = K/2 (Maximum Sustainable Yield point)."),
    ("mcq", "Verhulst-Pearl Logistic Equation",
     "The standard mathematical formula describing logistic population growth in nature is formally known as the:",
     "Verhulst-Pearl Logistic equation: dN/dt = rN ((K - N) / K)",
     ["Lotka-Volterra predator equation: dN/dt = rN - aNP", "Hardy-Weinberg equilibrium: p^2 + 2pq + q^2 = 1", "Michaelis-Menten equation: v = (Vmax [S]) / (Km + [S])"],
     "The logistic equation was formulated by Pierre François Verhulst (1838) and independently by Raymond Pearl (1920)."),
    ("stmt", "Gause Competitive Exclusion Principle",
     "Gause's Competitive Exclusion Principle states that two species competing for the exact same limiting resources cannot stably coexist indefinitely.",
     "The competitively inferior species will ultimately be eliminated from the ecological niche or forced to adapt.", 1,
     "Both Statement I and Statement II are correct. Gause demonstrated with Paramecium that complete competitors cannot coexist in the same niche."),
    ("seq", "Phases of Sigmoid Logistic Growth",
     "Arrange the sequential phases of an S-shaped logistic population growth curve over time:",
     ["Lag phase: slow initial growth as colonizing individuals adapt to the new environment", "Log / Exponential acceleration phase: rapid population expansion as births far exceed deaths", "Deceleration phase: growth rate slows down as resources become increasingly scarce", "Asymptote / Stationary phase: population stabilizes around carrying capacity (K) in dynamic equilibrium"],
     "I -> II -> III -> IV",
     "Logistic growth transitions from lag phase to exponential growth, deceleration, and finally the carrying capacity asymptote."),
    ("mcq", "Resource Partitioning Mechanism",
     "MacArthur's famous 1958 study on five warbler species coexisting on the same spruce tree demonstrated that competition can be minimized through:",
     "Resource partitioning (foraging in different micro-zones of the tree canopy at different times)",
     ["Predator-induced mass mortality of all competing species", "Complete destruction of the coniferous forest habitat", "Synchronous feeding on the exact same needle clusters"],
     "Robert MacArthur showed that warblers avoid competitive exclusion through behavioral resource partitioning across different canopy zones."),
    ("ar", "Mutualism and Co-evolution",
     "Obligate mutualistic interactions often lead to tight reciprocal co-evolution between the two interacting species.",
     "Neither species can complete its life cycle or reproduce successfully in the absence of its specific mutualistic partner.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Obligate mutualists (e.g. Fig tree and Fig wasp) co-evolve specialized adaptations because their survival is interdependent."),
    ("mcq", "Commensalism Biological Definition",
     "In population ecology, Commensalism is defined as an interspecific interaction in which:",
     "One species benefits while the other species is neither harmed nor benefited (+, 0)",
     ["Both interacting species derive substantial mutual benefits (+, +)", "One species derives nutrition at the direct metabolic expense of the host (+, -)", "One species is inhibited or harmed while the other remains completely unaffected (-, 0)"],
     "Commensalism is a (+, 0) interaction (e.g., orchid growing as an epiphyte on a mango branch, or barnacles on a whale)."),
    ("mcq", "Amensalism Example",
     "Which of the following ecological relationships represents 'Amensalism' (-, 0)?",
     "Penicillium mold secreting penicillin antibiotic that inhibits surrounding bacteria without gaining direct nutritional benefit",
     ["Lichen association between an alga and a fungus", "Tiger preying upon a spotted deer in a grassland", "Cuckoo laying eggs in a crow's nest"],
     "Amensalism is a (-, 0) interaction where one species damages another without benefiting, as when Penicillium inhibits bacterial growth."),
    ("match", "Interspecific Population Interactions and Signs",
     "Match the population interaction in List I with its ecological cost-benefit notation in List II:",
     [("A", "Mutualism"),
      ("B", "Competition"),
      ("C", "Parasitism / Predation"),
      ("D", "Amensalism")],
     [("I", "(+, +) Both species benefit"),
      ("II", "(-, -) Both species suffer detrimental effects"),
      ("III", "(+, -) One species benefits, the other is harmed"),
      ("IV", "(-, 0) One species is harmed, the other is unaffected")],
     "A-I, B-II, C-III, D-IV",
     "Mutualism is (+,+), competition is (-,-), parasitism/predation is (+,-), and amensalism is (-,0). Commensalism is (+,0)."),
    ("mcq", "Brood Parasitism in Birds",
     "The reproductive phenomenon in which the koel (cuckoo) lays its eggs in the nest of a crow, leaving the host to incubate and rear its hatchlings, is called:",
     "Brood parasitism",
     ["Hyperparasitism", "Ectoparasitism", "Adelphoparasitism"],
     "Brood parasitism occurs when a bird species lays eggs in another species' nest, relying on the host parent to raise the young."),
    ("mcq", "Keystone Predation Paine Experiment",
     "Robert Paine's classic 1966 removal experiment of the predatory starfish Pisaster ochraceus from rocky intertidal zones demonstrated that:",
     "Removing the keystone predator caused the extinction of more than 10 invertebrate species due to unconstrained mussel competition",
     ["Removing the predator caused an immediate 100-fold increase in species diversity", "The intertidal ecosystem collapsed completely due to lack of wave energy", "Prey species lived in peaceful coexistence without any competition"],
     "Paine proved that keystone predators maintain community diversity by suppressing dominant competitors (Mytilus mussels) that would otherwise exclude other species."),
    ("stmt", "Fundamental vs Realized Niche",
     "The Fundamental Niche is the full potential range of physical, chemical, and biological conditions an organism can occupy in the total absence of competitors and predators.",
     "The Realized Niche is the actual, narrower niche space the species occupies in nature due to pressure from interspecific competition and predation.", 1,
     "Both Statement I and Statement II are correct. Joseph Connell's classic barnacle experiments (Chthamalus vs Balanus) proved the distinction between fundamental and realized niches."),
    ("mcq", "Character Displacement Concept",
     "When two closely related competing species become sympatric (geographically overlapping), natural selection often favors evolutionary divergence in their morphological feeding traits. This is termed:",
     "Character displacement",
     ["Competitive exclusion", "Convergent evolution", "Demographic momentum"],
     "Character displacement (e.g. Darwin's finch beak sizes on the Galapagos) occurs when competition drives divergent morphological adaptations in sympatry."),
    ("seq", "Lotka-Volterra Predator-Prey Oscillation Cycle",
     "Arrange the sequential phases of coupled predator-prey population oscillations (e.g. Lynx and Snowshoe Hare):",
     ["Abundant prey population expands rapidly due to low predator density and favorable forage", "Predator population responds with increased natality and survival as prey availability surges", "Elevated predator density exerts heavy predation pressure, causing prey population to plummet", "Predator population crashes due to starvation following the collapse of its primary prey base"],
     "I -> II -> III -> IV",
     "Prey boom is followed by predator boom, which drives prey collapse, in turn causing predator collapse, generating rhythmic population cycles."),
    ("mcq", "Endoparasite Adaptations",
     "Which of the following morphological and physiological adaptations is characteristic of human internal endoparasites like tapeworms (Taenia solium)?",
     "Loss of unnecessary digestive organs, presence of suckers and hooks, and extraordinarily high reproductive capacity",
     ["Highly developed compound eyes and complex sensory organs", "Elaborate muscular wings and high locomotive speed", "Active photosynthetic chlorophyll pigments in outer tegument"],
     "Endoparasites simplify body morphology (losing gut and sense organs) while evolving attachment hooks, suckers, and massive egg production."),
    ("mcq", "Competitive Release Phenomenon",
     "When a species whose distribution is restricted to a small geographic zone by a competitively superior competitor dramatically expands its range when the competitor is removed, it demonstrates:",
     "Competitive release",
     ["Co-extinction", "Biomagnification", "Competitive exclusion"],
     "Competitive release occurs when a species dramatically expands its niche and distribution following the removal of a superior competitor.")
]
'''

with open('scripts/subject_generators/append_evs_s3_6.py', 'w') as f:
    f.write(s3_to_6)

print("append_evs_s3_6.py written.")
