#!/usr/bin/env python3
"""
append_mmc_s26_30.py
Appends Slots 26 to 30 to mmc_s21_30.py for Mass Media & Mass Communication (Code 318).
"""

import sys, os

out_path = "scripts/subject_generators/mmc_s21_30.py"

content = '''
# ==============================================================================
# SLOT 26: Television Program Formats & Genres
# ==============================================================================
SLOTS_21_30[26] = [
    mcq("TV Genres", "Daily Soap Opera Characteristics",
        "What narrative hallmark distinguishes television 'Daily Soap Operas' from finite television miniseries?",
        "Continuous open-ended serialization with multiple interwoven subplots, domestic emotional conflicts, and daily cliffhangers that delay narrative resolution",
        ["A complete standalone crime mystery solved every single episode",
         "The complete absence of female characters on screen",
         "Broadcast exclusively in black-and-white without sound"],
        "Daily soap operas feature sprawling, open-ended serialization with multi-strand domestic narratives and cliffhangers designed for daily loyalty.",
        "Defines the narrative hallmarks of television soap operas."),
    mcq("TV Genres", "Docudrama Definition",
        "What characterizes the television genre designated as 'Docudrama'?",
        "A hybrid non-fiction genre that dramatizes real historical events and real persons using professional actors, scripts, and dramatic staging based on verified facts",
        ["A fictional cartoon involving talking superhero animals",
         "A live broadcast of stock market commodity auctions",
         "An unedited five-hour video of empty highway traffic"],
        "Docudrama blends documentary factual accuracy with dramatic storytelling, reenacting real-world historical events.",
        "Defines docudrama in television programming."),
    stmt("TV Genres", "Reality Television Mechanisms",
        "Reality television formats (like Bigg Boss or Indian Idol) place ordinary citizens or celebrities in unscripted, high-stakes competitive environments.",
        "Reality television eliminates all post-production editing, broadcasting every second of raw footage continuously without narrative curation.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because reality TV relies heavily on dramatic post-production editing, confessionals, and music scoring to craft story arcs.",
        "Evaluates the structural mechanics of reality television."),
    ar("TV Genres", "Cliffhangers in Daily Soaps",
        "Soap opera writers end daily episodes on an abrupt emotional cliffhanger (a dramatic revelation, slap, or secret discovery).",
        "Cliffhangers stimulate psychological curiosity and Zeigarnik effect tension, ensuring viewers return for the subsequent broadcast episode.",
        "both_correct_explain",
        "Ending on unresolved dramatic tension drives anticipation and secures ongoing viewing loyalty.",
        "Analyzes the dramatic function of cliffhangers in soap operas."),
    match("TV Genres", "Television Formats",
        "Match the television format in List-I with its distinctive genre signature in List-II:",
        ["Sitcom (Situation Comedy)", "Telenovela / Soap Opera", "Reality Talent Competition", "Infotainment Documentary"],
        ["Fixed cast in recurring domestic/workplace setting with laugh track or comedic irony", "Sprawling multi-generational domestic melodrama with emotional conflict", "Audition rounds, celebrity judging panels, and viewer SMS voting elimination", "Blending scientific inquiry and exploration with cinematic visual entertainment"],
        "A-I, B-II, C-III, D-IV",
        "Sitcom = recurring comedic setting; Soap opera = domestic melodrama; Reality competition = judging/voting; Infotainment = science/visual entertainment.",
        "Matches television formats to genre signatures."),
    mcq("TV Genres", "The Game Show Format",
        "Which landmark Indian television game show, hosted by Amitabh Bachchan in 2000, revitalized Star Plus and revolutionized prime-time viewership?",
        "Kaun Banega Crorepati (KBC)",
        ["Bournvita Quiz Contest", "Tol Mol Ke Bol", "Antakshari"],
        "Kaun Banega Crorepati (adapted from Who Wants to Be a Millionaire?) shattered viewership records in 2000, establishing the mega-budget game show in India.",
        "Identifies Kaun Banega Crorepati as the breakthrough game show."),
    stmt("TV Genres", "Infotainment Channels",
        "Channels like National Geographic, Discovery Channel, and Animal Planet are categorized as 'Infotainment' broadcasters.",
        "Infotainment programming is legally required to contain 0% scientific or historical content.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because infotainment blends factual educational information with engaging entertainment value.",
        "Classifies infotainment channels and content."),
    ar("TV Genres", "Audience Participation in Reality TV",
        "Viewer voting via mobile apps and SMS is a central monetization and engagement driver in reality talent shows.",
        "Audience voting creates active emotional investment in contestants, driving higher television ratings and digital engagement.",
        "both_correct_explain",
        "Empowering viewers with voting agency drives personal emotional stakes and boosts multi-platform audience engagement.",
        "Explains the strategic role of audience voting in reality TV."),
    seq("TV Genres", "Reality Show Production Lifecycle",
        "Arrange the operational phases of producing a nationwide televised talent reality show:",
        ["Multi-city open ground auditions and initial contestant scouting", "Studio mega-auditions filmed before celebrity judge panels", "Intensive grooming, bootcamps, and weekly themed performance rounds", "Public voting phases with weekly eliminations based on combined scores", "Grand Finale live broadcast crowning the national winner"],
        "I -> II -> III -> IV -> V",
        "Reality cycle: City auditions -> Mega-auditions -> Weekly performances -> Public voting/eliminations -> Live grand finale.",
        "Sequences the production lifecycle of a reality talent show."),
    mcq("TV Genres", "B-Roll in Documentaries",
        "Why is contextual B-roll footage indispensable in historical and environmental television documentaries?",
        "It provides compelling visual evidence, recreations, and archival imagery that illustrates the spoken voiceover narration",
        ["It allows the cameraman to fall asleep during production",
         "It turns the television receiver screen completely blank",
         "It eliminates all spoken dialogue from the program"],
        "B-roll footage illustrates abstract narration, grounding historical or ecological narratives in visual reality.",
        "Explains the role of B-roll in television documentaries."),
    stmt("TV Genres", "Telenovela vs Anglo-American Soap Opera",
        "Latin American 'Telenovelas' differ from traditional US/UK soap operas because telenovelas have a predetermined finite ending (typically 100-150 episodes).",
        "Anglo-American daytime soap operas are designed to run indefinitely for decades without a planned conclusion.",
        "both_true",
        "Both statements accurately distinguish finite Latin American telenovelas from open-ended multi-decade soap operas.",
        "Contrasts Latin American telenovelas with ongoing soap operas."),
    ar("TV Genres", "Confessional Room / Diary Room",
        "Reality television formats incorporate a 'Confessional' or 'Diary Room' booth where contestants speak directly into a private camera.",
        "Confessionals reveal a participant's private psychological motivations, conspiracies, and true feelings uninhibited by other housemates.",
        "both_correct_explain",
        "The confessional provides intimate first-person psychological exposition, driving audience empathy and interpersonal drama.",
        "Analyzes the dramatic necessity of the diary room in reality TV."),
    match("TV Genres", "Pioneering Indian Shows",
        "Match the historic Indian television show in List-I with its genre milestone in List-II:",
        ["Turning Point", "Surabhi", "Dekh Bhai Dekh", "Kyunki Saas Bhi Kabhi Bahu Thi"],
        ["Flagship science magazine show presented by Prof. Yash Pal", "Iconic cultural magazine show hosted by Siddharth Kak and Renuka Shahane", "Classic prime-time situation comedy directed by Anand Mahendroo", "Record-breaking Ekta Kapoor daily soap opera defining 2000s K-serials"],
        "A-I, B-II, C-III, D-IV",
        "Turning Point = science magazine; Surabhi = cultural magazine; Dekh Bhai Dekh = sitcom; Kyunki Saas = 2000s daily soap.",
        "Matches pioneering Indian television shows to genre milestones."),
    mcq("TV Genres", "Television Anthology Series",
        "What characterizes a television 'Anthology Series' (such as Satyajit Ray Presents or Black Mirror)?",
        "Each individual episode or season features completely different characters, settings, and standalone self-contained plots",
        ["A show where the same five actors play identical scenes for fifty years",
         "A news broadcast dedicated solely to floral flower arrangements",
         "A commercial advertisement that lasts forty days without stopping"],
        "Anthology series offer thematic unity while presenting fresh storylines, actors, and self-contained worlds in each episode.",
        "Defines an anthology series in television drama."),
    stmt("TV Genres", "Prime-Time Television Debates",
        "Prime-time news debates in India typically assemble 6 to 10 panelists on a multi-split screen under an assertive celebrity anchor.",
        "Prime-time debate shows are cheaper to produce than investigative field documentary journalism.",
        "both_true",
        "Both statements are true. Studio shouting debates are far less expensive than sustained investigative field journalism, driving their ubiquity.",
        "Analyzes the economic and structural prevalence of studio debate shows."),
    ar("TV Genres", "Social Realism in TV Documentaries",
        "Documentary filmmakers on television frequently employ handheld cinema verité camera techniques.",
        "Handheld unpolished camera movement imparts a sense of raw immediacy, visual authenticity, and journalistic intimacy.",
        "both_correct_explain",
        "Cinema verité and handheld cinematography strip away artificial gloss, signaling unfiltered truth to viewers.",
        "Explains the aesthetic choice of cinema verité in documentaries."),
    mcq("TV Genres", "Format Licensing in Television",
        "What is 'Format Licensing' in international television (e.g. licensing Idols, Big Brother, or Strictly Come Dancing across 50 countries)?",
        "Purchasing the legal production blueprint, rules, set design, and branding of a proven show concept to produce a localized domestic version",
        ["Buying secondhand television studio cameras from foreign broadcasters",
         "Translating foreign newspapers into Indian languages",
         "Exporting video cassette tapes to overseas libraries"],
        "Format franchising sells the production 'bible' (rules, graphics, format engine) for local adaptation across global markets.",
        "Explains global format licensing in television."),
    match("TV Genres", "Television Talk Formats",
        "Match the talk show sub-genre in List-I with its primary objective in List-II:",
        ["Late-Night Comedy Talk Show", "Celebrity Sofa Chat Show (e.g. Koffee with Karan)", "Sunday Morning Political Show", "Issue-Based Public Forum (e.g. Satyamev Jayate)"],
        ["Satirical monologue on daily news followed by celebrity guests and skits", "Glamorous, gossipy personal lifestyle banter with film stars", "In-depth grilling of cabinet ministers and policy analysts", "Investigating severe social ills with survivor testimonies and reform advocacy"],
        "A-I, B-II, C-III, D-IV",
        "Late-night = comedy/satire; Celebrity chat = lifestyle gossip; Political show = policy grilling; Social forum = investigative reform.",
        "Matches talk show varieties to editorial objectives."),
    seq("TV Genres", "Soap Opera Narrative Arc",
        "Arrange the structural development of a major conflict in a serialized television drama:",
        ["Introduction of a disruptive secret or antagonist into the joint family", "Mounting misunderstandings, secret conspiracies, and interpersonal frictions", "Major festive ritual or wedding gathering where confrontation escalates", "Public revelation of truth at dramatic cliffhanger moment", "Repercussions, family fractures, and emotional realignment across subsequent episodes"],
        "I -> II -> III -> IV -> V",
        "Soap drama arc: Disruption -> Rising tension -> Festive showdown -> Cliffhanger revelation -> Narrative fallout.",
        "Sequences the narrative escalation arc in serialized television drama."),
    mcq("TV Genres", "Mockumentary",
        "A television comedy (such as The Office or Parks and Recreation) that adopts documentary film conventions like straight-to-camera confessionals is called a:",
        "Mockumentary",
        ["Melodrama", "Tragedy", "Docudrama"],
        "A mockumentary is a comedic parody that adopts documentary visual styles (shaky cam, talking heads) to satirize its subjects.",
        "Identifies the mockumentary television comedy genre.")
]

# ==============================================================================
# SLOT 27: Scriptwriting for Television (Two-Column AV Script, Rundown, Visual Cues)
# ==============================================================================
SLOTS_21_30[27] = [
    mcq("TV Scriptwriting", "Two-Column AV Script Format",
        "In professional television scriptwriting, what is the standard layout of a 'Two-Column AV Script'?",
        "Video instructions, camera shots, and graphics on the left column; Spoken dialogue, voiceover, and audio cues on the right column",
        ["Video instructions on top of the page; Audio instructions in the margins",
         "English dialogue on the left; Latin translations on the right",
         "Commercial prices on the left; Actor salaries on the right"],
        "The two-column format places Video (shots, framing, camera moves, CG) on the Left and Audio (voice, SFX, music) aligned on the Right.",
        "Identifies the structure of a two-column television AV script."),
    mcq("TV Scriptwriting", "The Rundown Sheet",
        "What is a television 'Rundown Sheet' (also called a line-up or run-order) in a live news broadcast?",
        "A minute-by-minute sequential spreadsheet detailing story slugs, segments, presenters, video sources, graphics, and exact running times for the broadcast",
        ["A list of technical repairs needed on the television station van",
         "A physical sheet of paper showing actor shoe sizes",
         "A record of electrical power bills paid by the studio"],
        "The rundown is the structural blueprint of a live broadcast show, tracking timing, slugs, sources, and story order.",
        "Defines a television broadcast rundown sheet."),
    stmt("TV Scriptwriting", "Writing for Video / Complementarity",
        "A television scriptwriter should avoid describing what the viewer can already clearly see on screen.",
        "The script's voiceover should interpret, contextualize, and add background meaning that complements the visual imagery.",
        "both_true",
        "Both statements reflect the golden rule of television writing: let the visuals tell what happened; use words to explain why and how.",
        "Validates the principle of complementary audio-visual scripting."),
    ar("TV Scriptwriting", "Back-Timing in Rundowns",
        "News producers constantly practice 'Back-Timing' throughout a live news broadcast.",
        "Back-timing calculates the remaining time needed to hit commercial breaks and the hard satellite network sign-off with split-second precision.",
        "both_correct_explain",
        "Because satellite uplinks and commercials have rigid hard stop times, back-timing tells producers whether to pad or drop stories.",
        "Explains the operational necessity of back-timing in live broadcasts."),
    match("TV Scriptwriting", "Screen Graphic Terminology",
        "Match the on-screen television graphic in List-I with its display function in List-II:",
        ["Ticker / Crawl", "Lower Third / Super", "Over the Shoulder (OTS)", "Full Frame Graphic (FS)"],
        ["Continuously scrolling text banner at bottom of screen displaying headlines", "Graphic band on lower third displaying person's name and designation", "A visual graphic or photo displayed in a box over the anchor's shoulder", "A full-screen informational slide displaying maps, charts, or bullet points"],
        "A-I, B-II, C-III, D-IV",
        "Ticker = scrolling headline crawl; Lower third = name/title band; OTS = box over shoulder; Full frame = full-screen data/maps.",
        "Matches television graphics terminology to visual manifestations."),
    mcq("TV Scriptwriting", "Story Slug",
        "In broadcast journalism, what is a 'Slug' assigned to every news story?",
        "A short, unique, one-or-two word code name (e.g. 'FLOODS-DELHI' or 'ELECTION-RALLY') used by the entire production team to track the story",
        ["A poisonous garden insect found inside television studios",
         "A heavy steel bullet fired into an old camera",
         "A penalty fee deducted from an editor's paycheck"],
        "The slug is the universal shorthand label identifying the script, raw footage, edited video, and graphics across the newsroom.",
        "Defines a news story slug in television production."),
    stmt("TV Scriptwriting", "Wall-to-Wall Voiceover Error",
        "A 'Wall-to-Wall' script is one where the voiceover talks incessantly from the first second to the last without allowing natural ambient sound to breathe.",
        "Television sound design should incorporate 'visual pauses' where video footage and natural sound (NatSound) tell the story without spoken words.",
        "both_true",
        "Both statements correctly critique over-written wall-to-wall voiceovers and advocate for visual breathing room.",
        "Critiques wall-to-wall voiceover and highlights the value of natural sound pauses."),
    ar("TV Scriptwriting", "Camera Shot Abbreviations",
        "Broadcast scriptwriters use standardized camera shot abbreviations in the left column (e.g. WS, MS, CU, ECU).",
        "Standardized technical abbreviations allow directors, camera operators, and video editors to interpret shot requirements instantly without ambiguity.",
        "both_correct_explain",
        "Standardized shorthand (WS, CU, PAN, TILT) facilitates split-second communication across production crews.",
        "Explains the utility of standardized camera shot abbreviations in scripts."),
    seq("TV Scriptwriting", "Television Package Scripting Flow",
        "Arrange the stages of drafting an edited news package from raw footage:",
        ["Reviewing and logging recorded field footage, sound bites, and visual assets", "Selecting the most compelling sound bites and noting exact timecodes", "Drafting the audio voiceover around the bites using complementary storytelling", "Specifying precise visual B-roll cuts and graphics in the left video column", "Reading audio script aloud against a stopwatch to ensure strict time adherence"],
        "I -> II -> III -> IV -> V",
        "Package scripting: Footage logging -> Bite selection -> Audio drafting -> Visual shot specification -> Timing read-through.",
        "Sequences television news package scriptwriting workflow."),
    mcq("TV Scriptwriting", "Pad / Filler in Rundown",
        "In a live news rundown, what is a 'Pad' (or Filler) story?",
        "A non-essential, soft news item placed near the end of the show that can be easily dropped or expanded to balance broadcast timing",
        ["A sponge used by the makeup artist to powder the presenter",
         "A cushion placed on the anchor's chair",
         "A commercial advertisement that is broadcast upside down"],
        "Pads are expendable cushion stories that producers expand or cut in real-time to ensure the show ends exactly on the second.",
        "Identifies a pad/filler story in television rundown management."),
    stmt("TV Scriptwriting", "Split-Page Alignment",
        "In a two-column AV script, visual cues in the left column must be precisely horizontal-aligned with the corresponding spoken words in the right column.",
        "Video cues should be written in alphabetical order on the last page of the manuscript.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because video cues must align horizontally with their exact corresponding audio phrases.",
        "Validates horizontal alignment in two-column script formatting."),
    ar("TV Scriptwriting", "Conversational Style in TV",
        "Television broadcast writing should sound spoken and conversational rather than literary and academic.",
        "Viewers absorb broadcast scripts through the ear in real-time; convoluted, nested syntax causes cognitive overload and loss of meaning.",
        "both_correct_explain",
        "Because audiences listen in linear time without the ability to re-read, simple conversational language is cognitively necessary.",
        "Analyzes why television scripts require conversational sentence structure."),
    match("TV Scriptwriting", "Script Abbreviations",
        "Match the technical script abbreviation in List-I with its full designation in List-II:",
        ["WS / ELS", "CU / ECU", "POV", "OS / OTS"],
        ["Wide Shot / Extreme Long Shot", "Close-Up / Extreme Close-Up", "Point of View Shot", "Over-the-Shoulder Shot"],
        "A-I, B-II, C-III, D-IV",
        "WS = Wide Shot; CU = Close-Up; POV = Point of View; OTS = Over-the-Shoulder.",
        "Matches television script camera abbreviations to full terms."),
    mcq("TV Scriptwriting", "Toss / Handover",
        "In multi-anchor broadcasts or live coverage, what is a 'Toss' (or Handover)?",
        "The verbal transition sentence spoken by the main studio anchor passing the presentation to a co-anchor or field reporter",
        ["Throwing physical papers across the news desk during an argument",
         "Discarding unprinted copies of the daily newspaper",
         "A coin flip used to decide which political party to cover"],
        "A toss smoothly transfers broadcast command from one presenter to another or to a live field reporter.",
        "Defines a toss/handover in broadcast presentation."),
    stmt("TV Scriptwriting", "Writing into the Bite",
        "A reporter should never repeat the exact words of an interviewee when introducing an incoming sound bite.",
        "The script should introduce the speaker and context, allowing the sound bite to deliver its unique emotional or factual punch independently.",
        "both_true",
        "Both statements are true. 'Parroting the bite' is a classic amateur scripting error that blunts the impact of the sound bite.",
        "Warns against parroting sound bites in script introductions."),
    ar("TV Scriptwriting", "Timecode Logging in Editing",
        "Video loggers record exact 'Timecodes' (Hours:Minutes:Seconds:Frames) for every usable sound bite and visual sequence.",
        "Precise timecode logging allows the video editor to locate and assemble required clips on the non-linear editing timeline in seconds.",
        "both_correct_explain",
        "SMPTE timecodes provide unique frame addresses, enabling rapid clip retrieval and seamless non-linear assembly.",
        "Explains the operational necessity of SMPTE timecodes in television production."),
    mcq("TV Scriptwriting", "Cold Open / Tease",
        "What is a 'Cold Open' (or Tease) in television programming?",
        "Jumping straight into a high-intensity dramatic scene or breaking headline before the show title sequence or opening commercials air",
        ["Broadcasting from an unheated studio in the middle of winter",
         "A television set that refuses to turn on",
         "A reporter eating ice cream on air"],
        "A cold open hooks audience attention immediately with dramatic action before the opening credits or title sting.",
        "Identifies a cold open/tease in television storytelling."),
    match("TV Scriptwriting", "Transitions in Script",
        "Match the visual transition command in List-I with its optical effect in List-II:",
        ["Cut", "Dissolve / Mix", "Wipe", "Fade to Black"],
        ["Instantaneous switch from one shot to another", "Gradual superimposition where one image fades into the next, signaling passage of time", "A geometric line or pattern that sweeps across the screen replacing the image", "Image gradually darkens to complete blackness, signaling major dramatic conclusion"],
        "A-I, B-II, C-III, D-IV",
        "Cut = instant switch; Dissolve = gradual blend/time passage; Wipe = geometric sweep; Fade to black = dramatic closure.",
        "Matches visual transition commands to optical effects."),
    seq("TV Scriptwriting", "Writing a Breaking News VO-SOT Script",
        "Arrange the components of an emergency Breaking News VO-SOT in correct structural order:",
        ["Anchor on camera delivers urgent breaking headline alert", "Video B-roll rolls as anchor reads voiceover explaining basic verified facts", "Sound bite (SOT) from official authority or eyewitness plays full on air", "Anchor on camera returns to summarize status and toss to commercial or next story"],
        "I -> II -> III -> IV",
        "VO-SOT order: Anchor alert -> Voiceover over B-roll -> SOT bite -> Anchor return/summary.",
        "Sequences a television VO-SOT script structure."),
    mcq("TV Scriptwriting", "Supers / Lower Third Timing",
        "As a professional rule of thumb, how long should a name-and-title lower-third graphic (Super) remain visible on screen?",
        "Around 4 to 6 seconds (long enough for an average viewer to read the text twice comfortably)",
        ["Exactly 60 minutes", "One tenth of a millisecond", "Until the viewer turns off the television set"],
        "Lower thirds typically stay on screen for 4-6 seconds, allowing comfortable reading without obstructing the lower frame indefinitely.",
        "Identifies optimal screen duration for lower-third graphics.")
]

# ==============================================================================
# SLOT 28: History of Indian Cinema - Early Era
# ==============================================================================
SLOTS_21_30[28] = [
    mcq("Cinema History", "First Motion Picture Screening in India",
        "When and where were moving pictures screened for the very first time in India, hosted by the Lumière brothers' cinematographe agent Marius Sestier?",
        "July 7, 1896, at Watson's Hotel in Bombay",
        ["January 26, 1910, in Calcutta", "August 15, 1920, in Madras", "December 25, 1885, in Delhi"],
        "Marius Sestier screened six short Lumière brothers films at Watson's Hotel, Bombay, on July 7, 1896, heralded as the 'marvel of the century'.",
        "Recalls the first motion picture screening in India at Watson's Hotel in 1896."),
    mcq("Cinema History", "Dadasaheb Phalke & Raja Harishchandra",
        "Dhundiraj Govind Phalke (Dadasaheb Phalke), celebrated as the 'Father of Indian Cinema', released which foundational silent feature film on May 3, 1913?",
        "Raja Harishchandra",
        ["Alam Ara", "Kaliya Mardan", "Bhakta Prahlad"],
        "Phalke's full-length indigenous silent feature 'Raja Harishchandra' premiered at the Coronation Cinema in Bombay on May 3, 1913.",
        "Identifies Dadasaheb Phalke's Raja Harishchandra (1913)."),
    stmt("Cinema History", "First Indian Talkie (1931)",
        "Ardeshir Irani produced and directed India's first sound/talking motion picture, 'Alam Ara', released at the Majestic Cinema in Bombay on March 14, 1931.",
        "The popular song 'De De Khuda Ke Naam Pe Pyaare', sung by W. M. Khan in Alam Ara, is celebrated as the first playback/recorded song of Indian cinema.",
        "both_true",
        "Both statements are historical facts marking the birth of Indian sound cinema (Talkies) in 1931.",
        "Evaluates the historic release and songs of Alam Ara (1931)."),
    ar("Cinema History", "Mythological Themes in Silent Era",
        "Early Indian silent films drew overwhelmingly upon Hindu mythological narratives from the Ramayana, Mahabharata, and Puranas.",
        "Mythological stories were deeply ingrained in public cultural consciousness, allowing illiterate audiences to follow silent plots without needing translated intertitles.",
        "both_correct_explain",
        "Familiarity with mythological lore allowed viewers to decode silent pantomime easily, making it the most commercially viable early genre.",
        "Analyzes why early Indian cinema drew heavily upon mythological narratives."),
    match("Cinema History", "Studio Era Giants",
        "Match the historic Indian film studio of the 1930s in List-I with its founding base and signature hallmark in List-II:",
        ["Prabhat Film Company (Pune/Kolhapur)", "New Theatres (Calcutta)", "Bombay Talkies (Mumbai)", "Wadia Movietone (Mumbai)"],
        ["Founded by V. Shantaram and partners; produced socially progressive masterpieces like Sant Tukaram", "Founded by B. N. Sircar; pioneered playback singing and literary adaptations (Devdas)", "Founded by Himanshu Rai and Devika Rani; introduced European studio disciplines and cosmopolitan stars", "Founded by J.B.H. and Homi Wadia; famous for stunt action cinema starring Fearless Nadia (Hunterwali)"],
        "A-I, B-II, C-III, D-IV",
        "Prabhat = V. Shantaram/Sant Tukaram; New Theatres = B.N. Sircar/Devdas/playback; Bombay Talkies = Himanshu Rai/Devika Rani; Wadia = Fearless Nadia stunts.",
        "Matches legendary 1930s Indian film studios to their historical hallmarks."),
    mcq("Cinema History", "Invention of Playback Singing",
        "Which studio sound engineer and director pioneered 'Playback Singing' in Indian cinema in the 1935 film 'Dhoop Chhaon' (Bhagya Chakra) at New Theatres?",
        "Nitin Bose and Mukul Bose",
        ["R. C. Boral and K. L. Saigal", "Dadasaheb Phalke", "Ardeshir Irani"],
        "Director Nitin Bose and his sound recordist brother Mukul Bose invented playback recording at Calcutta's New Theatres in 1935, freeing actors from singing live on set.",
        "Identifies the invention of playback singing by Nitin Bose at New Theatres."),
    stmt("Cinema History", "Female Roles in Silent Cinema",
        "In Dadasaheb Phalke's 1913 film Raja Harishchandra, the female role of Queen Taramati was played by a young male actor named Anna Salunke.",
        "In the early 1910s, strong social taboos prevented women from respectable families from acting in motion pictures.",
        "both_true",
        "Both statements are true. Phalke could find no female actors, leading Anna Salunke to play Queen Taramati.",
        "Reflects the historical gender dynamics of early silent cinema."),
    ar("Cinema History", "Demise of the Studio System",
        "The monolithic studio system in India disintegrated rapidly in the aftermath of World War II.",
        "Wartime black-market profiteering fueled the rise of independent, speculative freelance financiers who paid astronomical fees to individual star actors.",
        "both_correct_explain",
        "Black money financing dismantled long-term studio actor contracts, birthing the star-centric freelance system of modern Indian cinema.",
        "Explains the economic collapse of the Indian studio system post-WWII."),
    seq("Cinema History", "Early Indian Cinema Milestones",
        "Arrange the milestones of early Indian cinema in chronological order:",
        ["Lumière brothers' moving pictures screened at Watson's Hotel (1896)", "Hiralal Sen and H. S. Bhatavdekar capture early indigenous short footage (1898-1901)", "Dadasaheb Phalke releases India's first full-length silent feature 'Raja Harishchandra' (1913)", "Ardeshir Irani releases India's first sound talkie 'Alam Ara' (1931)", "Nitin Bose introduces playback singing in 'Dhoop Chhaon' (1935)"],
        "I -> II -> III -> IV -> V",
        "Chronology: Lumière (1896) -> Early shorts -> Phalke Harishchandra (1913) -> Alam Ara (1931) -> Playback singing (1935).",
        "Sequences foundational milestones of early Indian cinema history."),
    mcq("Cinema History", "Fearless Nadia & Hunterwali",
        "Mary Ann Evans, an Australian-born actress who became a trailblazing action icon of 1930s stunt cinema at Wadia Movietone, was famously known as:",
        "Fearless Nadia (star of Hunterwali, 1935)",
        ["Ruby Myers (Sulochana)", "Devika Rani", "Fatma Begum"],
        "Fearless Nadia captured public imagination performing daredevil horse stunts, whip-cracking, and top-of-train fights in 'Hunterwali' (1935).",
        "Identifies Fearless Nadia and her iconic film Hunterwali."),
    stmt("Cinema History", "First Female Director",
        "Fatma Begum is celebrated as the first female film director in Indian cinema, writing and directing 'Bulbul-e-Paristan' in 1926.",
        "Fatma Begum was officially appointed Supreme Court Chief Justice by the Viceroy.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because Fatma Begum was a pioneering cinema artist and producer, not a judicial officer.",
        "Recognizes Fatma Begum as India's first female film director."),
    ar("Cinema History", "Sant Tukaram at Venice (1937)",
        "Prabhat Film Company's Marathi film 'Sant Tukaram' (1936), directed by V. Damle and S. Fattelal, won a special award at the 5th Venice International Film Festival in 1937.",
        "Sant Tukaram was the first Indian film to gain major critical recognition and an international award at a global European film festival.",
        "both_correct_explain",
        "Sant Tukaram's humanist storytelling and spiritual lyricism captivated the 1937 Venice Film Festival, marking India's entry onto the world cinema stage.",
        "Celebrates the international milestone of Sant Tukaram at Venice 1937."),
    match("Cinema History", "Pioneering Figures",
        "Match the cinema pioneer in List-I with their historical milestone in List-II:",
        ["Dadasaheb Phalke", "Ardeshir Irani", "Devika Rani", "H. S. Bhatavdekar (Save Dada)"],
        ["Directed Raja Harishchandra (1913); Father of Indian Cinema", "Directed first sound talkie Alam Ara (1931)", "First Lady of Indian Cinema; co-founder of Bombay Talkies; first recipient of Dadasaheb Phalke Award (1969)", "Shot first Indian documentary actuality footage of a wrestling bout in Mumbai (1899)"],
        "A-I, B-II, C-III, D-IV",
        "Phalke = Harishchandra; Irani = Alam Ara; Devika Rani = First Phalke awardee; Bhatavdekar = first wrestling actuality.",
        "Matches cinema pioneers to historic achievements."),
    mcq("Cinema History", "First Recipient of Dadasaheb Phalke Award",
        "When the Government of India instituted the prestigious Dadasaheb Phalke Award in 1969 to honor lifetime contribution to cinema, who was its inaugural recipient?",
        "Devika Rani",
        ["Prithviraj Kapoor", "Satyajit Ray", "Lata Mangeshkar"],
        "Actress and studio pioneer Devika Rani was honored as the first recipient of the Dadasaheb Phalke Award in 1969.",
        "Identifies Devika Rani as the first Dadasaheb Phalke Award winner."),
    stmt("Cinema History", "Kundan Lal Saigal",
        "K. L. Saigal was the first undisputed superstar singer-actor of Indian talkie cinema in the 1930s and 1940s, immortalized by his role in P. C. Barua's 'Devdas' (1935).",
        "K. L. Saigal never sang any songs and performed exclusively in silent mime pantomime.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because Saigal was legendary for his resonant, melancholic singing voice that defined an era of music.",
        "Validates K. L. Saigal's legendary singing-acting status."),
    ar("Cinema History", "Talkies as Linguistic Barrier",
        "The arrival of sound cinema in 1931 fragmented the unified all-India market that silent cinema had enjoyed.",
        "Silent films could be screened anywhere in the country with simple local language title slides, whereas spoken dialogues restricted talkies to specific linguistic regions.",
        "both_correct_explain",
        "Sound created regional linguistic boundaries, requiring films to be produced separately in Hindi/Hindustani, Bengali, Tamil, Telugu, and Marathi.",
        "Explains the linguistic fragmentation caused by the arrival of talkies."),
    mcq("Cinema History", "Hindustani as the Film Language",
        "Why did early Bombay talkie filmmakers choose 'Hindustani' (a colloquial blend of Hindi and Urdu) as the primary language for popular cinema?",
        "Because Hindustani was widely understood across north, central, and western India and carried rich poetic traditions of ghazals, nautanki, and Parsi theatre",
        ["Because British colonial law prohibited the use of all other languages",
         "Because microphones in 1931 could only record vowels found in Urdu",
         "Because movie tickets were priced cheaper for Hindustani films"],
        "Hindustani was an accessible lingua franca rich in Parsi theatre dramatic vocabulary and musical lyricism, maximizing audience reach.",
        "Explains the adoption of Hindustani as the dominant language of popular cinema."),
    match("Cinema History", "Classic Film Studios & Films",
        "Match the classic studio in List-I with its iconic production in List-II:",
        ["Prabhat Film Company", "New Theatres", "Bombay Talkies", "Imperial Movietone"],
        ["Duniya Na Mane (The Unexpected)", "Devdas (1935)", "Achhut Kanya (1936)", "Alam Ara (1931)"],
        "A-I, B-II, C-III, D-IV",
        "Prabhat = Duniya Na Mane; New Theatres = Devdas; Bombay Talkies = Achhut Kanya; Imperial = Alam Ara.",
        "Matches classic film studios to their iconic film titles."),
    seq("Cinema History", "Dadasaheb Phalke Award Recipients",
        "Arrange the first five recipients of the prestigious Dadasaheb Phalke Award in historical sequence:",
        ["Devika Rani (1969)", "Birendranath Sircar (1970)", "Prithviraj Kapoor (1971 - posthumous)", "Pankaj Mullick (1972)", "Ruby Myers / Sulochana (1973)"],
        "I -> II -> III -> IV -> V",
        "Award sequence: Devika Rani (1969) -> B.N. Sircar (1970) -> Prithviraj Kapoor (1971) -> Pankaj Mullick (1972) -> Sulochana (1973).",
        "Sequences early recipients of the Dadasaheb Phalke Award."),
    mcq("Cinema History", "Parsi Theatre Influence",
        "Which major 19th-century performing arts tradition profoundly influenced early Indian cinema's narrative structure, high-flown dialogue, songs, and melodrama?",
        "Parsi Theatre",
        ["French Ballet", "Classical Japanese Kabuki", "Russian Constructivist Mime"],
        "Parsi theatre, with its blend of Shakespearean drama, Persian romantic legends, melodramatic declamation, and songs, formed the DNA of early Indian cinema.",
        "Identifies Parsi theatre as the foundational stylistic influence on early Indian cinema.")
]

# ==============================================================================
# SLOT 29: Golden Age & Parallel Cinema (1950s Cinema, Ray, New Wave)
# ==============================================================================
SLOTS_21_30[29] = [
    mcq("Golden Age & Parallel Cinema", "Pather Panchali Milestone",
        "Satyajit Ray's directorial debut 'Pather Panchali' (1955), which won the 'Best Human Document' award at the Cannes Film Festival, marked the arrival of:",
        "Indian Neo-Realism and authorial art-house cinema on the global cinematic stage",
        ["Commercial science-fiction space travel epics",
         "The elimination of all cameras from film sets",
         "The invention of automated digital computer animation"],
        "Pather Panchali was a watershed moment, introducing lyrical neo-realism, on-location shooting, and non-professional casting to world cinema.",
        "Identifies Pather Panchali as the milestone of Indian neo-realism."),
    mcq("Golden Age & Parallel Cinema", "Bimal Roy & Italian Neo-Realism",
        "Inspired by Vittorio De Sica's 'Bicycle Thieves' at the 1952 International Film Festival of India (IFFI), which landmark neo-realist film did Bimal Roy direct in 1953?",
        "Do Bigha Zamin",
        ["Madhumati", "Devdas", "Sujata"],
        "Do Bigha Zamin portrayed the harrowing urban migration and exploitation of an impoverished peasant (Balraj Sahni), winning the Prix International at Cannes in 1954.",
        "Identifies Bimal Roy's Do Bigha Zamin as influenced by Italian Neo-Realism."),
    stmt("Golden Age & Parallel Cinema", "The Holy Trinity of Golden Age Cinema",
        "The 1950s 'Golden Age' of popular Hindi cinema was defined by the directorial and acting triumvirate of Raj Kapoor, Dilip Kumar, and Dev Anand.",
        "Raj Kapoor crafted his iconic screen persona on Charlie Chaplin's 'Tramp' archetype in films like Awaara (1951) and Shree 420 (1955).",
        "both_true",
        "Both statements are true. The triumvirate dominated the 1950s, with Raj Kapoor celebrated worldwide for his Chaplinesque humanist tramp persona.",
        "Evaluates the 1950s triumvirate and Raj Kapoor's Chaplinesque persona."),
    ar("Golden Age & Parallel Cinema", "Guru Dutt's Melancholia",
        "Guru Dutt's masterpieces 'Pyaasa' (1957) and 'Kaagaz Ke Phool' (1959) are acclaimed as peaks of poetic cinema.",
        "Guru Dutt used exquisite light-and-shade cinematography, close-ups, and Sahir Ludhianvi's poetry to critique the materialism and heartlessness of post-colonial society.",
        "both_correct_explain",
        "Guru Dutt's aesthetic mastery and visual melancholy profoundly critiqued commercial greed and the disillusionment of the post-independence era.",
        "Analyzes Guru Dutt's cinematic themes and aesthetic mastery."),
    match("Golden Age & Parallel Cinema", "Auteurs and Masterpieces",
        "Match the acclaimed film director in List-I with their signature classic in List-II:",
        ["Satyajit Ray", "Ritwik Ghatak", "Guru Dutt", "Mehboob Khan"],
        ["The Apu Trilogy (Pather Panchali, Aparajito, Apur Sansar)", "Meghe Dhaka Tara (The Cloud-Capped Star)", "Pyaasa / Kaagaz Ke Phool", "Mother India (1957)"],
        "A-I, B-II, C-III, D-IV",
        "Ray = Apu Trilogy; Ghatak = Meghe Dhaka Tara; Guru Dutt = Pyaasa; Mehboob Khan = Mother India.",
        "Matches Golden Age auteurs to their signature masterpieces."),
    mcq("Golden Age & Parallel Cinema", "Mother India (1957) Milestone",
        "Mehboob Khan's epic film 'Mother India' (1957), starring Nargis as the indomitable Radha, achieved which historic international milestone?",
        "It was India's first submission to be nominated for the Academy Award (Oscar) for Best Foreign Language Film",
        ["It was the first film shot entirely on the moon",
         "It won the Nobel Prize in Literature",
         "It was screened continuously for one hundred years in Paris"],
        "Mother India made history as India's first Oscar-nominated film, losing by a single vote to Fellini's Nights of Cabiria.",
        "Recalls Mother India's historic Academy Award nomination."),
    stmt("Golden Age & Parallel Cinema", "Ritwik Ghatak's Partition Cinema",
        "Ritwik Ghatak's cinema (including Meghe Dhaka Tara, Komal Gandhar, Subarnarekha) explored the profound psychological, social, and cultural trauma of the 1947 Partition of Bengal.",
        "Ritwik Ghatak directed light-hearted slapstick silent comedies celebrating British colonial taxation.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because Ghatak was a fiercely political, tragic filmmaker obsessed with the agony of partition.",
        "Evaluates Ritwik Ghatak's thematic focus on Partition trauma."),
    ar("Golden Age & Parallel Cinema", "Birth of Indian New Wave (1969)",
        "The year 1969 is widely heralded by film historians as the official birth of the 'Indian New Wave' (Parallel Cinema).",
        "In 1969, the Film Finance Corporation (FFC) funded low-budget, pathbreaking realistic films: Mrinal Sen's 'Bhuvan Shome' and Mani Kaul's 'Uski Roti'.",
        "both_correct_explain",
        "State funding via the FFC enabled radical artistic experimentation, launching the parallel cinema movement in 1969.",
        "Analyzes the catalyst for the 1969 Indian New Wave."),
    seq("Golden Age & Parallel Cinema", "Milestones of Parallel Cinema",
        "Arrange the milestones of Indian parallel/realist cinema in chronological order:",
        ["Satyajit Ray releases 'Pather Panchali' (1955)", "Mrinal Sen directs 'Bhuvan Shome', launching the New Wave (1969)", "Adoor Gopalakrishnan directs Malayalam masterpiece 'Swayamvaram' (1972)", "Shyam Benegal directs 'Ankur', inaugurating the Hindi middle cinema (1974)", "Govind Nihalani releases hard-hitting socio-political drama 'Ardh Satya' (1983)"],
        "I -> II -> III -> IV -> V",
        "Chronology: Pather Panchali (1955) -> Bhuvan Shome (1969) -> Swayamvaram (1972) -> Ankur (1974) -> Ardh Satya (1983).",
        "Sequences the chronological evolution of the Indian Parallel Cinema movement."),
    mcq("Golden Age & Parallel Cinema", "Shyam Benegal & Middle Cinema",
        "Which acclaimed director pioneered 'Middle Cinema' (bridging art-house realism with accessible narrative drama) through films like Ankur, Nishant, Manthan, and Bhumika?",
        "Shyam Benegal",
        ["Manmohan Desai", "Prakash Mehra", "Subhash Ghai"],
        "Shyam Benegal revitalized 1970s Indian cinema, introducing social realism, feudal critiques, and stellar actors like Shabana Azmi, Smita Patil, and Naseeruddin Shah.",
        "Identifies Shyam Benegal as the pioneer of Indian Middle Cinema."),
    stmt("Golden Age & Parallel Cinema", "Manthan (1976) Crowd-Funding",
        "Shyam Benegal's 1976 film 'Manthan' (The Churning) was famously crowd-funded by 500,000 rural dairy farmers of Gujarat, who each contributed two rupees.",
        "Manthan depicted the origins of the White Revolution and the milk cooperative movement led by Dr. Verghese Kurien.",
        "both_true",
        "Both statements are true. Manthan stands as an unprecedented triumph of collective public crowd-funding in cinematic history.",
        "Highlights the crowd-funded history of Shyam Benegal's Manthan."),
    ar("Golden Age & Parallel Cinema", "Characteristics of Parallel Cinema",
        "Parallel Cinema fundamentally rejected the formulaic song-and-dance routines and escapist melodrama of mainstream commercial Bollywood.",
        "Parallel filmmakers sought to confront urgent socio-economic realities such as feudal oppression, caste discrimination, poverty, and state corruption.",
        "both_correct_explain",
        "Rejecting escapism was an intentional aesthetic choice to address authentic social issues and class struggles.",
        "Explains the ideological rejection of escapist tropes in Parallel Cinema."),
    match("Golden Age & Parallel Cinema", "Parallel Cinema Pioneers Across India",
        "Match the New Wave / Parallel cinema pioneer in List-I with their primary language realm in List-II:",
        ["Adoor Gopalakrishnan", "G. Aravindan", "Girish Karnad & B. V. Karanth", "Mrinal Sen"],
        ["Malayalam (Swayamvaram, Elippathayam)", "Malayalam (Kanchana Sita, Thampu)", "Kannada (Samskara, Chomana Dudi)", "Bengali / Hindi (Bhuvan Shome, Chorus, Khandhar)"],
        "A-I, B-II, C-III, D-IV",
        "Adoor = Malayalam auteur; Aravindan = poetic Malayalam; Karnad/Karanth = Kannada new wave; Mrinal Sen = Bengali/Hindi political cinema.",
        "Matches regional pioneers of the Indian New Wave to their language realms."),
    mcq("Golden Age & Parallel Cinema", "Adoor Gopalakrishnan's Elippathayam",
        "Which landmark 1981 Malayalam film by Adoor Gopalakrishnan utilized the metaphor of a 'Rat-Trap' to critique the decaying, paralyzed feudal order of Kerala?",
        "Elippathayam (The Rat-Trap)",
        ["Mukhamukham", "Kodiyettam", "Vidheyan"],
        "Elippathayam won the prestigious British Film Institute Award in 1982 for its profound allegory of feudal inertia and psychological entrapment.",
        "Identifies Adoor Gopalakrishnan's Elippathayam."),
    stmt("Golden Age & Parallel Cinema", "The Angry Young Man Phenomenon",
        "In the 1970s, screenwriters Salim-Javed created the iconic 'Angry Young Man' persona, personified by Amitabh Bachchan in Zanjeer, Deewaar, and Sholay.",
        "The Angry Young Man reflected the deep socio-economic disillusionment of Indian youth facing unemployment, inflation, and political corruption.",
        "both_true",
        "Both statements are true. The Angry Young Man was a cultural phenomenon channeling working-class rage against systemic injustice.",
        "Evaluates the socio-political resonance of the 1970s 'Angry Young Man' persona."),
    ar("Golden Age & Parallel Cinema", "FTII as Breeding Ground for Talent",
        "The Film and Television Institute of India (FTII), established in Pune in 1960, served as the primary nursery for the Indian New Wave.",
        "FTII graduates like Mani Kaul, Kumar Shahani, Shabana Azmi, Naseeruddin Shah, and Om Puri brought rigorous film grammar and modernist sensibilities to Indian screens.",
        "both_correct_explain",
        "Formal film education at FTII transformed Indian cinema by supplying educated technicians and method actors committed to artistic realism.",
        "Analyzes the role of FTII Pune in incubating the Indian New Wave."),
    mcq("Golden Age & Parallel Cinema", "Satyajit Ray's Honorary Oscar",
        "In 1992, on his deathbed in Kolkata, Satyajit Ray was awarded which supreme global cinematic honor by the Academy of Motion Picture Arts and Sciences?",
        "An Honorary Lifetime Achievement Academy Award (Oscar)",
        ["The Nobel Prize in Physics", "The Booker Prize for Poetry", "The Olympic Gold Medal in Rowing"],
        "Audrey Hepburn announced Ray's Lifetime Achievement Oscar in 1992, recognizing his peerless mastery of the cinematic art.",
        "Recalls Satyajit Ray's 1992 Honorary Lifetime Achievement Oscar."),
    match("Golden Age & Parallel Cinema", "Iconic Actors of Parallel Cinema",
        "Match the iconic actor of Indian New Wave cinema in List-I with their signature performance in List-II:",
        ["Smita Patil", "Shabana Azmi", "Naseeruddin Shah", "Balraj Sahni"],
        ["Bhumika / Mirch Masala", "Ankur / Arth / Mandi", "Jaane Bhi Do Yaaro / Sparsh", "Do Bigha Zamin / Garam Hawa"],
        "A-I, B-II, C-III, D-IV",
        "Smita Patil = Bhumika/Mirch Masala; Shabana Azmi = Ankur/Arth; Naseeruddin Shah = Jaane Bhi Do Yaaro/Sparsh; Balraj Sahni = Do Bigha Zamin/Garam Hawa.",
        "Matches parallel cinema actors to their landmark performances."),
    seq("Golden Age & Parallel Cinema", "The Apu Trilogy Sequence",
        "Arrange the three films of Satyajit Ray's celebrated 'Apu Trilogy' in narrative sequence:",
        ["Pather Panchali (Song of the Little Road, 1955)", "Aparajito (The Unvanquished, 1956)", "Apur Sansar (The World of Apu, 1959)"],
        "I -> II -> III",
        "The trilogy charts Apu's life: rural childhood (Pather Panchali) -> adolescence/education (Aparajito) -> adulthood/marriage (Apur Sansar).",
        "Sequences Satyajit Ray's Apu Trilogy."),
    mcq("Golden Age & Parallel Cinema", "Garam Hawa (1973)",
        "M. S. Sathyu's landmark film 'Garam Hawa' (Scorching Winds, 1973), featuring Balraj Sahni's final performance, addressed which sensitive historical reality?",
        "The agonizing dilemma, social alienation, and identity crisis of North Indian Muslim families in post-Partition Agra",
        ["The construction of the Bhakra Nangal dam",
         "The space race between the Soviet Union and America",
         "The arrival of digital wristwatches in India"],
        "Garam Hawa, scripted by Kaifi Azmi and Ismat Chughtai, remains the definitive cinematic masterpiece exploring the human tragedy of Partition for Indian Muslims.",
        "Identifies M. S. Sathyu's Garam Hawa and its historical themes.")
]

# ==============================================================================
# SLOT 30: Film Language & Visual Grammar - Shots & Angles
# ==============================================================================
SLOTS_21_30[30] = [
    mcq("Film Grammar", "Extreme Long Shot (ELS) Function",
        "In film visual grammar, what is the primary narrative function of an 'Extreme Long Shot' (ELS), often utilized as an 'Establishing Shot'?",
        "To establish the geographic setting, vast landscape, or urban environment, placing human subjects as tiny elements within the wider spatial context",
        ["To inspect the pores on an actor's nose",
         "To blur the entire image so the audience cannot see the screen",
         "To record audio dialogue without any visual picture"],
        "An ELS establishes location, scale, and environmental scope, orienting the viewer to the physical setting before closer action unfolds.",
        "Defines the function of an Extreme Long Shot / Establishing Shot."),
    mcq("Film Grammar", "Close-Up (CU) Emotional Power",
        "Why is the 'Close-Up' (CU) regarded as cinema's most powerful and intimate visual tool?",
        "It isolates the human face from forehead to chin, magnifying subtle emotional expressions, eye glances, and psychological vulnerability for the viewer",
        ["It allows the actor to hide behind large furniture",
         "It forces the projectionist to turn down the theatre lights",
         "It proves that the camera has run out of battery power"],
        "The close-up creates emotional intimacy by capturing micro-expressions and inner psychological states invisible in theatre or wide shots.",
        "Explains the emotional impact of the close-up in cinema."),
    stmt("Film Grammar", "Low Angle vs High Angle Psychological Effects",
        "A 'Low Angle Shot' (camera looking up at the subject) typically makes the character appear powerful, dominant, imposing, or heroic.",
        "A 'High Angle Shot' (camera looking down at the subject) typically makes the character appear vulnerable, weak, isolated, or diminished.",
        "both_true",
        "Both statements correctly explain the universal psychological and semiotic effects of camera angles on perceived power dynamics.",
        "Evaluates the psychological effects of low and high camera angles."),
    ar("Film Grammar", "Canted / Dutch Angle Function",
        "Filmmakers employ a 'Canted Angle' (also known as a Dutch Angle or oblique tilt) during psychological thrillers or moments of horror.",
        "Tilting the camera diagonally off its horizontal axis induces a feeling of disorientation, psychological imbalance, unease, and impending danger.",
        "both_correct_explain",
        "Tilting the horizon line subverts visual equilibrium, signaling internal psychic distress or external chaos to the audience.",
        "Analyzes the psychological purpose of a Canted / Dutch angle."),
    match("Film Grammar", "Camera Shots",
        "Match the camera shot in List-I with its standard anatomical framing in List-II:",
        ["Extreme Close-Up (ECU)", "Close-Up (CU)", "Medium Shot (MS)", "Long Shot (LS)"],
        ["Isolates a single facial detail (e.g. eyes or mouth) or a small object (a ticking clock)", "Frames the face from top of head to neck/collarbones", "Frames the human figure from the waist or hips upward", "Captures the complete human figure from head to toe with surrounding environment"],
        "A-I, B-II, C-III, D-IV",
        "ECU = single detail/eyes; CU = head to shoulders; MS = waist up; LS = complete body head-to-toe.",
        "Matches camera shot types to anatomical framing definitions."),
    mcq("Film Grammar", "Bird's Eye View",
        "What is a 'Bird's Eye View' (overhead God's eye shot) in cinematography?",
        "An extreme high-angle shot positioned directly 90 degrees overhead looking straight down at the action below",
        ["A shot filmed from inside a bird's stomach",
         "A camera mounted on an actor's sunglasses",
         "A shot filmed in pitch darkness"],
        "A bird's eye view looks straight down from a 90-degree zenith, creating abstract spatial patterns and emphasizing fate or detachment.",
        "Defines a Bird's Eye View in cinematography."),
    stmt("Film Grammar", "Two-Shot and Over-the-Shoulder (OTS)",
        "A 'Two-Shot' frames two characters within the same image, emphasizing their interpersonal dynamic, dialogue, or romantic connection.",
        "An 'Over-the-Shoulder' (OTS) shot looks over the back of one character's shoulder to frame the face of the speaking partner during a conversation.",
        "both_true",
        "Both statements accurately define classic conversational cinematic framings (Two-shot and OTS).",
        "Differentiates a Two-Shot from an Over-the-Shoulder shot."),
    ar("Film Grammar", "Eye-Level Shot Neutrality",
        "The 'Eye-Level Shot' is the most common default camera angle in narrative cinema.",
        "Positioning the camera at the actor's eye level mirrors natural human interpersonal perspective, creating an objective, neutral psychological connection.",
        "both_correct_explain",
        "Eye-level framing mirrors real-world human eye contact, maintaining neutral, realistic engagement without psychological distortion.",
        "Explains why the eye-level shot is the default narrative camera angle."),
    seq("Film Grammar", "Scene Shot Progression (Analytical Editing)",
        "Arrange the standard classical Hollywood shot progression used when introducing a new dramatic conversation:",
        ["Extreme Long / Establishing Shot setting up spatial geography of room", "Long Shot showing two characters seated opposite each other", "Medium Shot narrowing down to character as dialogue commences", "Over-the-Shoulder shot framing the conversational exchange", "Extreme Close-Up on character's eyes reacting to a shocking revelation"],
        "I -> II -> III -> IV -> V",
        "Classical shot progression: Establishing ELS -> Full/Long -> Medium -> Over-the-shoulder -> Dramatic ECU punch.",
        "Sequences classical analytical editing shot progression."),
    mcq("Film Grammar", "Point of View (POV) Shot",
        "In film visual grammar, what defines a 'POV (Point of View) Shot'?",
        "A shot that places the camera directly in the physical position of a character's eyes, showing the scene exactly as that character perceives it",
        ["A shot where the director shouts their personal opinions into a microphone",
         "A legal document written by the producer's lawyer",
         "A shot filmed from the underside of an automobile tire"],
        "A POV shot simulates subjective vision, aligning the audience's perception directly with the character's sensory gaze.",
        "Defines a subjective Point of View (POV) shot in cinema."),
    stmt("Film Grammar", "Medium Close-Up (MCU)",
        "A 'Medium Close-Up' (MCU) frames the human subject from the chest up, widely utilized for television news presentation and cinematic dialogue.",
        "A Medium Close-Up frames only the actor's leather shoes.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because an MCU frames the chest and head, not the feet.",
        "Identifies the framing of a Medium Close-Up."),
    ar("Film Grammar", "Worm's Eye View Effect",
        "A 'Worm's Eye View' is an extreme low angle shot where the camera is placed flat on the ground looking straight up.",
        "Worm's eye angles impart staggering monumentality, towering size, and overwhelming intimidation to buildings or characters.",
        "both_correct_explain",
        "Shooting from the ground up exaggerates vertical lines, making characters or structures appear colossal and overwhelming.",
        "Analyzes the dramatic effect of a Worm's Eye View."),
    match("Film Grammar", "Camera Angles and Semiotics",
        "Match the camera angle in List-I with its primary semiotic meaning in List-II:",
        ["Low Angle", "High Angle", "Canted / Dutch Angle", "Bird's Eye View"],
        ["Dominance, heroic power, and authority", "Vulnerability, entrapment, and weakness", "Psychological disorientation, madness, and unrest", "Detached, omniscient fatalism and abstract spatial patterns"],
        "A-I, B-II, C-III, D-IV",
        "Low = dominance/power; High = vulnerability; Canted = disorientation/madness; Bird's eye = detachment/omniscience.",
        "Matches camera angles to semiotic emotional meanings."),
    mcq("Film Grammar", "Cowboy Shot / American Shot (Plan Américain)",
        "What is a 'Cowboy Shot' (Plan Américain), originally popularized in Hollywood Westerns?",
        "Framing an actor from mid-thigh up, originally designed to keep both the actor's face and their holstered gun in the same frame",
        ["A shot of an actor riding a mechanical wooden horse",
         "A shot filmed exclusively in Texas without permission",
         "A panoramic landscape of desert sand dunes"],
        "Plan Américain frames from the mid-thigh upward, allowing Western heroes to draw guns while keeping facial expressions visible.",
        "Explains the historical origin of the Cowboy Shot."),
    stmt("Film Grammar", "Headroom and Lead Room",
        "'Headroom' refers to the visually comfortable amount of space left between the top of an actor's head and the upper border of the frame.",
        "'Lead Room' (Nose Room / Looking Room) refers to the open negative space left in the direction a profile subject is looking or walking.",
        "both_true",
        "Both statements are foundational guidelines of professional cinematic composition and framing.",
        "Validates headroom and lead room principles in camera composition."),
    ar("Film Grammar", "Insufficient Lead Room Flaw",
        "Framing a running character with their nose jammed right against the leading edge of the frame creates jarring visual discomfort for the viewer.",
        "Human vision naturally expects empty visual space ahead of a moving or gazing subject to anticipate their trajectory.",
        "both_correct_explain",
        "Denying looking/lead room visually traps the character against the screen edge, creating subconscious visual anxiety.",
        "Explains why adequate lead room is necessary in moving shots."),
    mcq("Film Grammar", "Choker Shot",
        "In film directing slang, what is a 'Choker' shot?",
        "An intense, tight close-up framing from just above the eyebrows to just below the mouth, intensifying claustrophobic tension",
        ["An actor wearing an extremely tight necktie",
         "A camera lens that is completely blocked by dust",
         "A scene where an actor pretends to swallow a key"],
        "A choker cuts off the chin and forehead, tightly compressing the face to heighten dramatic claustrophobia and emotional tension.",
        "Defines a choker shot in cinematography."),
    match("Film Grammar", "Composition Guidelines",
        "Match the compositional rule in List-I with its practical guideline in List-II:",
        ["Rule of Thirds", "Leading Lines", "Framing within a Frame", "Depth of Field (Selective Focus)"],
        ["Placing points of interest along imaginary 3x3 grid lines and intersections", "Using natural architectural lines (roads, fences) to draw the eye toward the subject", "Using doorways, windows, or arches to isolate and highlight the character", "Using shallow focus to blur the background while keeping the subject razor sharp"],
        "A-I, B-II, C-III, D-IV",
        "Rule of thirds = grid intersections; Leading lines = visual roads/fences; Frame within frame = doorways/arches; Depth of field = selective focus.",
        "Matches cinematic composition rules to artistic applications."),
    seq("Film Grammar", "Executing an Over-the-Shoulder Conversation",
        "Arrange the stages of shooting a standard two-person dialogue using the shot-reverse-shot method:",
        ["Master Two-Shot capturing the entire dialogue exchange and spatial layout", "Positioning camera behind Character A to shoot OTS coverage of Character B's lines", "Repositioning camera behind Character B (respecting 180-degree line) to shoot OTS coverage of Character A", "Shooting matching Close-Up reaction shots of both characters listening", "Shooting cutaways of hands or environmental objects for editing flexibility"],
        "I -> II -> III -> IV -> V",
        "Shot-reverse-shot workflow: Master two-shot -> OTS on Character B -> OTS on Character A -> Close-up reactions -> Cutaways.",
        "Sequences the shot-reverse-shot coverage workflow in filmmaking."),
    mcq("Film Grammar", "Deep Focus Cinematography",
        "What is 'Deep Focus' cinematography (mastered by Gregg Toland in Orson Welles's Citizen Kane)?",
        "A visual technique where foreground, middle ground, and deep background are all kept simultaneously in crisp, sharp focus",
        ["Focusing exclusively on underwater objects in a swimming pool",
         "Blurring every single object on screen until the image is dark gray",
         "A camera that can only shoot during a lunar eclipse"],
        "Deep focus maintains razor-sharp clarity across all three planes of depth, allowing viewers to choose where to look within the mise-en-scène.",
        "Defines deep focus cinematography.")
]

print("Mass Media Slots 26 to 30 compiled successfully: 5 slots (100 questions).")
'''

with open(out_path, "a", encoding="utf-8") as f:
    f.write(content)

print("Appended slots 26 to 30 successfully.")
