# Script to write Slots 7 to 10
s7_to_10 = '''
# ==============================================================================
# Slot 7: Biodiversity Levels, Gradients & Ecosystem Stability
# ==============================================================================
s7_raw = [
    ("mcq", "Three Levels of Biodiversity",
     "According to the Convention on Biological Diversity (CBD) and NCERT, biodiversity is formally studied at which three interconnected hierarchical levels?",
     "Genetic diversity, Species diversity, and Ecological / Ecosystem diversity",
     ["Atomic diversity, Cellular diversity, and Tissue diversity", "Urban diversity, Rural diversity, and Industrial diversity", "Atmospheric diversity, Lithospheric diversity, and Hydrospheric diversity"],
     "Biodiversity encompasses genetic diversity within species, species diversity within communities, and ecosystem diversity across biomes."),
    ("stmt", "Alpha, Beta and Gamma Diversity",
     "Alpha diversity refers to the species diversity within a specific local community or homogenous habitat.",
     "Beta diversity measures the rate of species turnover and differentiation between distinct communities along an environmental gradient.", 1,
     "Both Statement I and Statement II are correct. R.H. Whittaker categorized diversity into Alpha (within-habitat), Beta (between-habitats), and Gamma (regional landscape)."),
    ("ar", "Latitudinal Gradient in Biodiversity",
     "Species diversity generally peaks at the equator and steadily declines as one moves toward the polar regions.",
     "Tropical regions have experienced prolonged evolutionary time without major glaciations, receive constant solar energy, and exhibit less seasonal climatic variation.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Undisturbed evolutionary time, high solar irradiation, and climate stability foster exceptional tropical speciation."),
    ("match", "Biodiversity Hypotheses and Formulators",
     "Match the ecological concept in List I with its pioneering scientist in List II:",
     [("A", "Species-Area Relationship (log S = log C + Z log A)"),
      ("B", "Rivet Popper Hypothesis"),
      ("C", "Outdoor Plot Diversity-Stability Experiments"),
      ("D", "Biodiversity Hotspot Concept")],
     [("I", "Alexander von Humboldt"),
      ("II", "Paul Ehrlich"),
      ("III", "David Tilman"),
      ("IV", "Norman Myers")],
     "A-I, B-II, C-III, D-IV",
     "Humboldt discovered the species-area curve, Paul Ehrlich devised the rivet popper analogy, David Tilman proved stability plots, and Norman Myers coined hotspots."),
    ("mcq", "Species-Area Relationship Slope Z",
     "In Alexander von Humboldt's rectangular hyperbola species-area relationship (log S = log C + Z log A), what is the typical range of regression slope (Z) across small regional areas?",
     "0.1 to 0.2",
     ["0.6 to 1.2", "1.5 to 2.5", "3.0 to 5.0"],
     "For small regional taxonomic surveys (plants in Britain, birds in California), the Z-slope consistently falls between 0.1 and 0.2."),
    ("mcq", "Continental Slope Z Value",
     "When analyzing the species-area relationship across very large geographic domains such as entire continents (e.g. frugivorous birds and mammals in tropical forests), the regression slope (Z) becomes much steeper, with values around:",
     "1.15 (ranging between 0.6 and 1.2)",
     ["0.01 to 0.05", "2.5 to 3.5", "4.0 to 5.0"],
     "Over continental scales, the regression line steepens drastically to Z = 0.6–1.2 (specifically 1.15 for tropical frugivorous birds and mammals)."),
    ("stmt", "Paul Ehrlich Rivet Popper Hypothesis",
     "In the Rivet Popper hypothesis, an airplane represents the ecosystem and the rivets holding the airframe together represent individual species.",
     "The hypothesis argues that while losing a few rivets (minor species) may not immediately crash the plane, popping rivets on the wings (keystone species) poses an imminent catastrophe.", 1,
     "Both Statement I and Statement II are correct. Stanford ecologist Paul Ehrlich used this analogy to illustrate how cumulative species loss jeopardizes global ecosystem stability."),
    ("seq", "Whittaker Hierarchical Diversity Scales",
     "Arrange the scales of biological diversity from the most localized spatial scale to the broadest continental scale:",
     ["Genetic diversity among alleles within a local breeding population", "Alpha diversity within a single local habitat or forest patch", "Beta diversity measuring species turnover across adjacent ecological patches", "Gamma diversity representing the overall species richness across an entire biogeographic region"],
     "I -> II -> III -> IV",
     "Diversity scales hierarchically from genetic variation to alpha (local community), beta (cross-community), and gamma (regional landscape)."),
    ("mcq", "David Tilman Ecosystem Stability Findings",
     "David Tilman's long-term outdoor prairie plot experiments demonstrated that plots with greater species richness exhibited:",
     "Less year-to-year variation in total biomass and higher overall primary productivity",
     ["Extreme cyclical crashes and vulnerability to weed invasions", "Substantially reduced drought resistance and declining nutrient retention", "Complete dominance by a single aggressive monoculture grass"],
     "David Tilman proved empirically that species-rich communities show greater stability, resilience, and lower annual biomass fluctuations."),
    ("ar", "Genetic Diversity and Disease Resistance",
     "Agricultural crop monocultures lacking genetic diversity are extremely vulnerable to catastrophic epidemic pathogen outbreaks.",
     "Genetic uniformity means that if a pathogen successfully infects one individual, all individuals in the crop population lack resistance.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The 1845 Irish Potato Famine demonstrated the catastrophic vulnerability of genetically uniform clonal crops."),
    ("mcq", "Rauwolfia vomitoria Chemical Variation",
     "The medicinal plant Rauwolfia vomitoria growing across diverse Himalayan ranges shows substantial genetic variation in the potency and concentration of which active alkaloid?",
     "Reserpine",
     ["Quinine", "Morphine", "Azadirachtin"],
     "NCERT highlights Rauwolfia vomitoria as an example of genetic diversity, displaying different concentrations of reserpine across Himalayan altitudinal gradients."),
    ("mcq", "India Species Diversity Share",
     "Although India possesses only 2.4% of the world's total land area, its impressive share of global recorded species diversity is approximately:",
     "8.1%",
     ["1.2%", "15.6%", "25.0%"],
     "India is one of 17 megadiverse nations, housing 8.1% of global species diversity on just 2.4% of Earth's terrestrial surface."),
    ("match", "Diversity Levels and Specific Examples",
     "Match the level of biodiversity in List I with its biological example in List II:",
     [("A", "Genetic Diversity"),
      ("B", "Species Diversity"),
      ("C", "Ecological Diversity"),
      ("D", "Endemic Diversity")],
     [("I", "Over 50,000 genetically different strains of rice and 1,000 varieties of mango in India"),
      ("II", "Greater amphibian species richness in the Western Ghats compared to the Eastern Ghats"),
      ("III", "Presence of deserts, rainforests, mangroves, coral reefs, and alpine meadows in India"),
      ("IV", "Species like the Lion-tailed Macaque confined strictly to the Western Ghats evergreen forests")],
     "A-I, B-II, C-III, D-IV",
     "Rice strains exemplify genetic diversity; Western Ghats amphibians show species diversity; Indian biomes show ecological diversity; and the Lion-tailed Macaque illustrates endemism."),
    ("mcq", "Robert May Global Species Estimate",
     "Ecologist Robert May placed the most scientifically sound and conservative estimate of total global species richness at approximately:",
     "7 million species",
     ["1.5 million species", "20 to 50 million species", "100 million species"],
     "Robert May estimated global species richness at ~7 million, of which only ~1.7–1.8 million have been formally described by science."),
    ("mcq", "Most Taxonomically Rich Animal Group",
     "Among all described animal species on Earth, which taxonomic group comprises more than 70% of the total animal kingdom?",
     "Insects (Arthropods)",
     ["Mollusks", "Mammals", "Birds"],
     "Insects are the most species-rich group: out of every 10 animals on this planet, more than 7 are insects."),
    ("stmt", "Fungi Diversity vs Vertebrates",
     "According to global biodiversity inventories, the number of described fungi species in the world exceeds the combined total species of fishes, amphibians, reptiles, and mammals.",
     "Fungi play indispensable ecological roles as primary decomposers and mycorrhizal plant mutualists across all terrestrial biomes.", 1,
     "Both Statement I and Statement II are correct. Fungi diversity is astonishingly high, exceeding the total diversity of all vertebrate groups combined."),
    ("mcq", "Amazon Rainforest Biodiversity Record",
     "The Amazonian rainforest in South America harbors the greatest biodiversity on Earth, functioning ecologically as the:",
     "'Lungs of the planet' and harboring over 40,000 plant species and 3,000 fish species",
     ["Primary commercial producer of global nuclear isotopes", "Main global source of industrial synthetic microplastics", "Sole natural habitat of polar bears and penguins"],
     "The Amazon basin houses ~40,000 plant, 3,000 fish, 1,300 bird, and 427 mammal species, generating vast atmospheric moisture and oxygen."),
    ("seq", "Estimated Proportion of Living Species Groups",
     "Arrange the major vertebrate groups in descending order of their global described species richness (from highest number of species to lowest):",
     ["Fishes (over 30,000 species)", "Birds (approx. 10,000 species)", "Reptiles (approx. 10,000 species)", "Amphibians (approx. 7,000 species)", "Mammals (approx. 5,500 species)"],
     "I -> II -> III -> IV -> V",
     "Among vertebrates, species richness is highest in fishes, followed by birds, reptiles, amphibians, and mammals."),
    ("mcq", "Biogeographic Realms of the World",
     "According to Alfred Russel Wallace's biogeographic classification, the Indian subcontinent belongs primarily to which major faunal realm?",
     "Oriental / Indomalayan realm",
     ["Nearctic realm", "Neotropical realm", "Palearctic realm"],
     "India belongs predominantly to the Oriental (Indomalayan) biogeographical realm, characterized by diverse tropical and sub-tropical taxa."),
    ("mcq", "Biodiversity and Ecosystem Function (BEF)",
     "The consensus among contemporary ecologists regarding Biodiversity and Ecosystem Function (BEF) is that higher species richness:",
     "Enhances ecosystem resilience, nutrient cycling efficiency, and resistance to invasive alien species",
     ["Has zero measurable correlation with ecosystem stability or service flows", "Directly accelerates soil erosion and desertification across all biomes", "Invariably leads to immediate mass toxic algal blooms"],
     "Higher biodiversity stabilizes primary productivity, buffers against climatic shocks, and enhances community resistance to invasive weeds.")
]

# ==============================================================================
# Slot 8: Biodiversity Hotspots (Global & Indian, Endemism, Megadiversity)
# ==============================================================================
s8_raw = [
    ("mcq", "Norman Myers Hotspot Criteria",
     "British ecologist Norman Myers (1988) formulated the 'Biodiversity Hotspot' concept based on which two rigorous qualifying criteria?",
     "It must contain at least 1,500 species of endemic vascular plants, and must have lost at least 70% of its original primary habitat",
     ["It must contain active volcanic activity, and must have human population density exceeding 1,000 per km2", "It must harbor at least 500 species of marine mammals, and have zero terrestrial vegetation", "It must be situated exclusively within 5 degrees latitude of the equator with zero seasonal rainfall variation"],
     "Myers defined hotspots as regions harboring >= 1,500 endemic vascular plants that have lost >= 70% of their primary vegetation."),
    ("stmt", "Total Global Hotspots and Land Area",
     "Initially identified as 25, there are currently 36 recognized biodiversity hotspots across the globe.",
     "Collectively, these 36 hotspots originally covered 15.7% of the Earth's land surface, but today cover just 2.4% of land area while harboring over 50% of the world's endemic plant species.", 1,
     "Both Statement I and Statement II are correct. Though hotspots now occupy only ~2.4% of Earth's land surface, protecting them could reduce mass extinction rates by nearly 30%."),
    ("ar", "Western Ghats Endemism",
     "The Western Ghats of India are recognized globally as one of the hottest biodiversity hotspots.",
     "The mountain range exhibits exceptional levels of endemism, particularly among amphibians, reptiles, freshwater fishes, and flowering plants.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Over 75% of amphibian species and hundreds of tree species found in the Western Ghats are endemic nowhere else on Earth."),
    ("match", "Biodiversity Hotspots Covering India",
     "Match the Indian biodiversity hotspot in List I with its geographic coverage in List II:",
     [("A", "Western Ghats and Sri Lanka"),
      ("B", "Himalaya"),
      ("C", "Indo-Burma"),
      ("D", "Sundaland")],
     [("I", "Covers the continuous coastal mountain escarpment through Maharashtra, Goa, Karnataka, Kerala, and Tamil Nadu"),
      ("II", "Encompasses the entire Indian Himalayan region (Jammu & Kashmir, HP, Uttarakhand, Sikkim, Arunachal) and neighboring countries"),
      ("III", "Encompasses Northeastern India (south of the Brahmaputra), Manipur, Mizoram, Tripura, and parts of Myanmar/Southeast Asia"),
      ("IV", "Encompasses the Nicobar Islands of India, extending to Malaysia, Singapore, Brunei, and Indonesia")],
     "A-I, B-II, C-III, D-IV",
     "India is covered by 4 hotspots: Western Ghats, Himalaya, Indo-Burma, and Sundaland (which includes the Nicobar Islands)."),
    ("mcq", "Megadiverse Countries Concept",
     "The 'Like-Minded Megadiverse Countries' is an international alliance of 17 nations that together harbor what proportion of planetary biological diversity?",
     "More than 70% of the Earth's biological species diversity",
     ["Less than 10% of global species diversity", "Exactly 100% of all marine species", "Only high-altitude alpine biodiversity"],
     "The 17 megadiverse nations (identified by Conservation International) house >70% of planetary flora and fauna, led by nations like Brazil, Indonesia, Colombia, and India."),
    ("mcq", "Endemism Biological Meaning",
     "In biogeography, an 'endemic species' is defined as a species that is:",
     "Confined strictly to a specific geographic region and found naturally nowhere else in the world",
     ["Widely distributed across all seven continents through human introduction", "Capable of thriving exclusively in laboratory tissue-culture incubators", "Migrating annually between the Arctic and Antarctic poles"],
     "Endemic species are native and restricted to a unique defined geographic location (e.g. Lion-tailed Macaque to the Western Ghats, or Nilgiri Tahr)."),
    ("stmt", "Hottest of the Hotspots",
     "Among the global hotspots, Norman Myers identified eight 'Hottest Hotspots' characterized by extraordinary concentrations of endemic taxa under catastrophic threat.",
     "Both the Western Ghats/Sri Lanka and Madagascar are ranked among these elite 'Hottest Hotspots'.", 1,
     "Both Statement I and Statement II are correct. Western Ghats and Madagascar represent top-tier conservation priorities due to extreme endemism and severe habitat fragmentation."),
    ("seq", "Steps in Delineating a Global Biodiversity Hotspot",
     "Arrange the scientific evaluation steps required to designate an international biodiversity hotspot:",
     ["Botanical taxonomic survey confirming the presence of at least 1,500 endemic vascular plant species", "Satellite remote-sensing assessment documenting loss of 70% or more of original primary vegetation", "Peer-reviewed publication and formal submission to international bodies like Conservation International", "Mobilization of global philanthropic and governmental conservation funding to protect remaining habitat fragments"],
     "I -> II -> III -> IV",
     "Designating a hotspot involves proving botanical endemism, verifying severe habitat degradation, formal scientific review, and targeted funding deployment."),
    ("mcq", "Agasthyamalai Biosphere Reserve Endemism",
     "The Agasthyamalai hills at the southern tip of the Western Ghats are celebrated for harboring unique traditional ecological knowledge of which indigenous tribe?",
     "The Kani tribe (discoverers of the anti-fatigue properties of Arogyapacha / Trichopus zeylanicus)",
     ["The Sentinelese tribe", "The Santhal tribe", "The Toda pastoralists"],
     "The Kani tribe of Agasthyamalai shared knowledge of Arogyapacha with scientists (TBGRI), leading to India's pioneer benefit-sharing model (Jeevani drug)."),
    ("ar", "Tropical Deforestation in Hotspots",
     "Habitat loss in biodiversity hotspots triggers disproportionately high rates of global species extinctions.",
     "Because species in hotspots are highly endemic with narrow geographic ranges, the destruction of a single valley or forest fragment can wipe out entire species.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Endemic species with tiny geographic distributions cannot migrate elsewhere when their localized habitat is cleared."),
    ("mcq", "Hope Spots vs Hotspots",
     "While terrestrial priority conservation areas are known as 'Biodiversity Hotspots', ecologically critical marine areas championed by Sylvia Earle are termed:",
     "Hope Spots",
     ["Cold Spots", "Wetland sinks", "Dead zones"],
     "Marine biologist Sylvia Earle coined 'Hope Spots' through Mission Blue to designate marine protected areas critical to the health of global oceans."),
    ("mcq", "Madhav Gadgil Western Ghats Ecology Expert Panel",
     "The 2011 Western Ghats Ecology Expert Panel (WGEEP), chaired by Prof. Madhav Gadgil, recommended:",
     "Designating the entire Western Ghats mountain range as an Ecologically Sensitive Area (ESA) categorized into three sensitivity zones (ESZ-1, ESZ-2, ESZ-3)",
     ["Constructing an unbroken corridor of open-cast iron ore mines across all hill passes", "Abolishing all existing National Parks in the Western Ghats to boost commercial rubber production", "Permitting unregulated chemical pesticide manufacturing across the catchment of the Periyar river"],
     "The Gadgil Commission recommended democratic, multi-tiered ecological zoning (ESZ 1, 2, 3) with stringent curbs on mining, mega-dams, and polluting industries in the Western Ghats."),
    ("match", "Flagship Endemic Species and Indian Hotspots",
     "Match the endangered endemic species in List I with its native Indian biodiversity hotspot in List II:",
     [("A", "Lion-tailed Macaque (Macaca silenus)"),
      ("B", "Red Panda (Ailurus fulgens)"),
      ("C", "Nicobar Megapode (Megapodius nicobariensis)"),
      ("D", "Sangai Brow-antlered Deer (Rucervus eldii eldii)")],
     [("I", "Western Ghats"),
      ("II", "Eastern Himalaya"),
      ("III", "Sundaland (Nicobar Islands)"),
      ("IV", "Indo-Burma (Loktak Lake, Manipur)")],
     "A-I, B-II, C-III, D-IV",
     "Lion-tailed macaque is endemic to Western Ghats; Red Panda to Eastern Himalayas; Nicobar Megapode to Nicobar (Sundaland); and Sangai deer to Loktak Lake (Indo-Burma)."),
    ("mcq", "Kasturirangan Committee Compromise",
     "Following political contestation of the Madhav Gadgil report, the High Level Working Group chaired by Dr. K. Kasturirangan (2013) recommended:",
     "Designating approximately 37% of the total Western Ghats area as ecologically sensitive, rather than the entire range",
     ["Expanding mining concessions to cover 95% of the mountain crest", "Relocating all tribal communities out of South India into northern plains", "Declaring the entire Western Ghats as an industrial special economic zone"],
     "The Kasturirangan report reduced the proposed Ecologically Sensitive Area to ~37% (natural landscape), drawing criticism from conservationists for diluting Gadgil's recommendations."),
    ("mcq", "Indo-Burma Hotspot Geographic Extent",
     "The Indo-Burma biodiversity hotspot covers an immense region of tropical Asia that includes which Indian territories?",
     "Northeastern Indian states south of the Brahmaputra river and the Andaman Islands",
     ["The Thar Desert of Rajasthan and Rann of Kutch in Gujarat", "The Deccan Plateau and Chota Nagpur plateau", "The Ladakh high-altitude plateau"],
     "Indo-Burma encompasses NE India south of the Brahmaputra (Meghalaya, Assam plains, Manipur, Mizoram, Nagaland, Tripura) and the Andaman islands."),
    ("stmt", "Sundaland Hotspot Significance for India",
     "India's territory in the Sundaland biodiversity hotspot is confined to the southern Nicobar group of islands.",
     "The Great Nicobar Biosphere Reserve harbors pristine tropical wet evergreen forests, coral reefs, and endemic fauna like the Nicobar tree shrew and megapode.", 1,
     "Both Statement I and Statement II are correct. Great Nicobar sits at the northwestern edge of Sundaland, sharing rich Malaysian-Indonesian biogeographical affinities."),
    ("mcq", "Conservation International Role",
     "Which international environmental organization formally assesses, updates, and maps the 36 Global Biodiversity Hotspots?",
     "Conservation International (CI)",
     ["World Trade Organization (WTO)", "International Monetary Fund (IMF)", "International Atomic Energy Agency (IAEA)"],
     "Conservation International (CI), founded in 1987, adopted and institutionalized Norman Myers' hotspot methodology as an institutional conservation blueprint."),
    ("seq", "Regional Prioritization Framework for Hotspots",
     "Arrange the priority criteria used by conservation biologists to rank biodiversity hotspots for emergency intervention:",
     ["Quantitative calculation of total endemic plant and vertebrate species", "Measurement of historical percentage loss of original primary vegetative cover", "Assessment of ongoing human demographic and infrastructural conversion pressures", "Allocation of target emergency conservation reserves and anti-poaching patrol networks"],
     "I -> II -> III -> IV",
     "Hotspot prioritization begins with assessing endemism, calculating habitat loss, evaluating immediate threat vectors, and deploying targeted resources."),
    ("mcq", "Coldspots in Ecological Theory",
     "In conservation biology, 'Biodiversity Coldspots' refers to areas like polar tundras or salt flats that, despite having low species richness, are ecologically vital because:",
     "They support uniquely adapted extremophiles, perform critical global biogeochemical functions, or house high phylogenetic distinctiveness",
     ["They are barren wastelands that can be used for radioactive waste dumping without harm", "They have zero biological organisms living in them", "They are created purely by industrial chemical spills"],
     "Kareiva and Marvier emphasized that 'coldspots' (e.g. Arctic tundra, hyper-arid deserts) provide irreplaceable ecosystem services and unique evolutionary adaptations."),
    ("mcq", "Key Biodiversity Areas (KBAs)",
     "The global standard developed by the IUCN for identifying sites that contribute significantly to the global persistence of biodiversity across all biomes is known as:",
     "Key Biodiversity Areas (KBAs)",
     ["Special Economic Zones (SEZs)", "Brownfield industrial corridors", "Exclusive Economic Maritime Zones (EEZs)"],
     "Key Biodiversity Areas (KBAs) provide a standardized umbrella framework encompassing Important Bird Areas (IBAs), Alliance for Zero Extinction sites, and hotspots.")
]

# ==============================================================================
# Slot 9: Threats to Biodiversity (HIPPO, Evil Quartet, Invasive Species, IUCN)
# ==============================================================================
s9_raw = [
    ("mcq", "The Evil Quartet of Biodiversity Loss",
     "Renowned ecologist Jared Diamond coined 'The Evil Quartet' to designate the four major drivers of contemporary anthropogenic biodiversity loss, which are:",
     "Habitat loss and fragmentation, Over-exploitation, Alien species invasions, and Co-extinctions",
     ["Floods, Earthquakes, Volcanic eruptions, and Tsunamis", "Deforestation, Nuclear radiation, Genetic cloning, and Space exploration", "Air pollution, Water pollution, Noise pollution, and Thermal pollution"],
     "The 'Evil Quartet' (or HIPPO: Habitat loss, Invasive species, Pollution, Population, Overharvesting) encapsulates the 4 primary extinction drivers."),
    ("stmt", "Habitat Loss and Fragmentation Impact",
     "Habitat loss is recognized as the single most devastating cause driving animals and plants to extinction.",
     "When large habitats are broken into small, isolated fragments due to roads, railways, and agriculture, mammals and birds requiring large territories and migratory species are severely affected.", 1,
     "Both Statement I and Statement II are correct. Fragmentation increases detrimental 'edge effects' and isolates breeding populations, precipitating inbreeding and local extirpation."),
    ("ar", "Amazon Rain Forest Deforestation",
     "The Amazon rain forest, once covering 14% of the Earth's land surface, is being cleared and fragmented at an alarming pace.",
     "Vast tracts of the Amazon basin are systematically deforested for cultivating soyabeans or converted into grass pastures for raising beef cattle.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Agricultural conversion for commercial soyabean farming and cattle ranching is the primary economic driver of Amazon destruction."),
    ("match", "Extinct Species and Their Native Regions",
     "Match the famously extinct species in List I with its historical geographic homeland in List II:",
     [("A", "Dodo (Raphus cucullatus)"),
      ("B", "Quagga"),
      ("C", "Thylacine (Tasmanian Wolf)"),
      ("D", "Steller's Sea Cow")],
     [("I", "Mauritius"),
      ("II", "Africa"),
      ("III", "Australia / Tasmania"),
      ("IV", "Russia / Bering Sea")],
     "A-I, B-II, C-III, D-IV",
     "The flightless Dodo was native to Mauritius, the zebra-like Quagga to Africa, the Thylacine to Australia/Tasmania, and Steller's Sea Cow to the icy Bering Sea."),
    ("mcq", "Over-Exploitation and Extinction",
     "Which of the following species was driven to complete extinction within the past two centuries solely due to excessive human commercial over-exploitation?",
     "Passenger Pigeon (Ectopistes migratorius)",
     ["Bengal Tiger", "Asian Elephant", "Saltwater Crocodile"],
     "The Passenger Pigeon, once numbering billions in North America, was driven to complete extinction by 1914 due to commercial hunting and forest clearing."),
    ("mcq", "Terror of Bengal Invasive Weed",
     "Eichhornia crassipes, a floating aquatic macrophyte introduced to India for its beautiful purple flowers and leaf shape, became an ecological menace known as the 'Terror of Bengal' because it:",
     "Propagates vegetatively with astonishing speed, choking water bodies, blocking sunlight, and drastically depleting dissolved oxygen, killing fish",
     ["Excretes toxic mercury directly into the municipal drinking supply", "Parasitizes the root systems of terrestrial mango trees along river banks", "Emits flammable methane gas causing spontaneous forest fires"],
     "Water hyacinth (Eichhornia crassipes) forms thick mats that block light and strip water of dissolved oxygen, devastating freshwater aquatic ecosystems."),
    ("stmt", "Alien Invasive Plants in India",
     "Parthenium hysterophorus (Carrot grass / Congress grass) was accidentally imported into India as a contaminant with American wheat under the PL-480 program.",
     "Lantana camara, introduced as an ornamental hedging shrub from South America, has vigorously invaded understories of Indian deciduous forests, suppressing native herb regeneration.", 1,
     "Both Statement I and Statement II are correct. Both Parthenium and Lantana are devastating invasive weeds in India, displacing native flora and causing severe allergies."),
    ("seq", "Process of Invasive Alien Species Ecological Impact",
     "Arrange the sequential stages through which an introduced exotic species becomes an invasive pest:",
     ["Transport and introduction of non-native exotic species across natural biogeographical barriers", "Establishment of a localized founder breeding population in the new recipient ecosystem", "Rapid population expansion driven by lack of co-evolved natural predators, pathogens, and competitors", "Aggressive competitive displacement and extinction of native indigenous flora and fauna"],
     "I -> II -> III -> IV",
     "Biological invasion proceeds from introduction to establishment, enemy-free population explosion, and competitive displacement of native biodiversity."),
    ("mcq", "African Catfish Threat to Indian Rivers",
     "The illegal introduction of the predatory African catfish for aquaculture poses an acute existential threat to native Indian freshwater catfishes. What is its scientific name?",
     "Clarias gariepinus",
     ["Catla catla", "Labeo rohita", "Cirrhinus mrigala"],
     "The exotic African sharptooth catfish (Clarias gariepinus), illegally bred in aquaculture, escaped into rivers, aggressively devouring native indigenous catfishes."),
    ("ar", "Co-Extinction Vulnerability",
     "When a host fish species becomes extinct, its unique assemblage of monogenean ectoparasites invariably meets immediate extinction.",
     "In obligate symbiotic and mutualistic relationships, the extinction of one partner species automatically leads to the co-extinction of the dependent partner.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Obligate relationships (such as co-evolved plant-pollinator pairs or host-parasite pairs) guarantee co-extinction."),
    ("mcq", "Lake Victoria Cichlid Fish Collapse",
     "The introduction of the predatory Nile perch into Lake Victoria in East Africa famously caused:",
     "The ecological extinction of an entire assemblage of over 200 native endemic species of cichlid fish",
     ["A 500% increase in local aquatic plant diversity", "The complete desiccation and drying up of Lake Victoria", "The immediate evolution of flight in indigenous wetland birds"],
     "Introducing the giant Nile perch into Lake Victoria led to one of the most catastrophic vertebrate extinctions, annihilating >200 unique endemic cichlid species."),
    ("mcq", "IUCN Headquarters and Establishment",
     "The International Union for Conservation of Nature (IUCN), the global authority on the status of the natural world and measures needed to safeguard it, was established in 1948 and is headquartered in:",
     "Gland, Switzerland",
     ["Nairobi, Kenya", "New York, USA", "Vienna, Austria"],
     "The IUCN was founded in 1948 in Fontainebleau, France, and is currently headquartered in Gland, Switzerland."),
    ("match", "IUCN Red List Categories and Status",
     "Match the IUCN Red List conservation status category in List I with its official criterion in List II:",
     [("A", "Extinct (EX)"),
      ("B", "Extinct in the Wild (EW)"),
      ("C", "Critically Endangered (CR)"),
      ("D", "Vulnerable (VU)")],
     [("I", "There is no reasonable doubt that the last individual of the taxon has died"),
      ("II", "Survives only in cultivation, captivity, or as a naturalized population outside past range"),
      ("III", "Facing an extremely high risk of extinction in the wild in the immediate future"),
      ("IV", "Facing a high risk of extinction in the medium-term future")],
     "A-I, B-II, C-III, D-IV",
     "EX means last individual is dead, EW exists only in captivity, CR faces immediate extreme extinction risk, and VU faces high medium-term risk."),
    ("mcq", "The Sixth Mass Extinction Anthropocene",
     "How does the ongoing 'Sixth Mass Extinction' (the Anthropocene extinction event) differ fundamentally from the five previous prehistoric mass extinctions recorded in fossil history?",
     "It is occurring at a rate estimated to be 100 to 1,000 times faster than background rates, and is driven entirely by anthropogenic human activities",
     ["It is caused exclusively by a massive asteroid collision in the Pacific Ocean", "It affects only microscopic marine plankton while terrestrial vertebrates flourish", "It is resulting in an instantaneous drop of global average temperatures by 20 degrees Celsius"],
     "Unlike prehistoric extinctions caused by volcanic traps or bolide impacts, the sixth extinction is extraordinarily rapid and driven entirely by human exploitation and habitat destruction."),
    ("mcq", "IUCN Red Data Book Function",
     "What is the primary function of the 'Red Data Book' published by the IUCN?",
     "To maintain an authoritative, scientifically verifiable global inventory of the conservation status of threatened biological species",
     ["To record international carbon-credit transactions between nations", "To register intellectual property patents for genetically modified crops", "To record global meteorological temperature anomalies in the Arctic"],
     "The IUCN Red List of Threatened Species (Red Data Book) provides taxonomic, conservation status, and distribution data on species facing extinction risk."),
    ("stmt", "Great Indian Bustard Conservation Emergency",
     "The Great Indian Bustard (Ardeotis nigriceps) is classified as 'Critically Endangered' on the IUCN Red List.",
     "The primary contemporary threat causing high adult mortality in the Thar Desert of Rajasthan is collisions with high-voltage overhead power transmission cables.", 1,
     "Both Statement I and Statement II are correct. With fewer than 150 individuals remaining in the wild, overhead powerlines across their flight paths pose an existential collision threat."),
    ("mcq", "Vulture Crisis in India and Diclofenac",
     "The catastrophic 99% decline of Oriental white-backed vultures (Gyps bengalensis) across the Indian subcontinent during the 1990s was discovered to be caused by:",
     "Renal failure and visceral gout induced by consuming livestock carcasses treated with the veterinary drug Diclofenac",
     ["A contagious fungal skin disease spreading across nesting cliffs", "Overhunting by commercial fur traders for feather export", "Atmospheric radiation emitted from commercial telecommunication towers"],
     "Vultures died in millions across South Asia from acute kidney failure after feeding on cattle treated with the anti-inflammatory NSAID Diclofenac (banned for veterinary use in 2006)."),
    ("seq", "Sequential Severity Hierarchy of IUCN Threat Categories",
     "Arrange the IUCN Red List threat categories in increasing order of extinction risk (from lowest threat to highest risk of extinction):",
     ["Least Concern (LC)", "Near Threatened (NT)", "Vulnerable (VU)", "Endangered (EN)", "Critically Endangered (CR)"],
     "I -> II -> III -> IV -> V",
     "The progressive threat hierarchy moves from Least Concern to Near Threatened, Vulnerable, Endangered, and Critically Endangered."),
    ("mcq", "Ballast Water and Marine Bio-Invasion",
     "How do ocean-going commercial cargo vessels inadvertently trigger destructive alien species invasions in marine coastal ports worldwide?",
     "By taking up coastal seawater with plankton and larvae as ballast in one port, and discharging it untreated into distant recipient harbors",
     ["By burning low-sulfur marine bunker fuel in international shipping lanes", "By using sonar navigation frequencies that communicate with pelagic dolphins", "By painting ship hulls with non-toxic zinc galvanic anodes"],
     "Ships pump in ballast water for trim and stability, inadvertently transporting thousands of marine species across oceans and releasing them in new ecosystems."),
    ("mcq", "Deforestation Edge Effect",
     "In conservation biology, the 'Edge Effect' in fragmented forest patches refers to:",
     "Alterations in microclimatic conditions (increased wind, solar desiccating heat, and predator vulnerability) along the boundary zone of a habitat fragment",
     ["The physical edge where continental plates collide to create fold mountains", "The boundary line where agricultural irrigation canals meet freshwater lakes", "The biological limit where photosynthetic chlorophyll ceases to function at high altitudes"],
     "Edge effects drastically alter temperature, humidity, and predation near forest edges, degrading habitat quality for deep-forest interior species.")
]

# ==============================================================================
# Slot 10: Biodiversity Conservation Strategies (In-situ, Ex-situ, Protected Areas)
# ==============================================================================
s10_raw = [
    ("mcq", "In-situ vs Ex-situ Conservation Distinction",
     "The conservation of genetic resources and endangered species within their natural ecosystem and wild habitats is known as:",
     "In-situ conservation (On-site conservation)",
     ["Ex-situ conservation (Off-site conservation)", "In-vitro conservation", "Cryogenic preservation"],
     "In-situ conservation protects species in their natural surroundings (National Parks, Sanctuaries), while Ex-situ protects them outside (Zoos, Gene banks)."),
    ("stmt", "National Parks vs Wildlife Sanctuaries in India",
     "In a National Park, all human activities, livestock grazing, and private resource extraction are strictly prohibited under the Wildlife Protection Act 1972.",
     "In a Wildlife Sanctuary, certain limited human rights such as regulated cattle grazing or collection of non-timber minor forest produce may be permitted by the Chief Wildlife Warden.", 1,
     "Both Statement I and Statement II are correct. National Parks enjoy higher statutory protection with zero grazing, whereas sanctuaries allow limited regulated human access."),
    ("ar", "Biosphere Reserves MAB Zonation",
     "A typical Biosphere Reserve under UNESCO's Man and the Biosphere (MAB) program is partitioned into Core, Buffer, and Transition zones.",
     "The Core zone is strictly legally protected from all human interference to serve as an undisturbed natural baseline for monitoring.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Biosphere reserves combine strict core preservation with buffer research and sustainable human transition zones."),
    ("match", "Biosphere Reserve Zones and Allowed Activities",
     "Match the Biosphere Reserve zone in List I with its designated human activity in List II:",
     [("A", "Core Zone"),
      ("B", "Buffer Zone"),
      ("C", "Transition / Manipulation Zone"),
      ("D", "Corridor Zone")],
     [("I", "Legally protected undisturbed wilderness reserved exclusively for scientific monitoring and non-destructive research"),
      ("II", "Surrounds the core; permits non-destructive research, environmental education, and low-impact ecotourism"),
      ("III", "Outermost zone where local communities, forest departments, and stakeholders practice sustainable agriculture, settlements, and forestry"),
      ("IV", "Contiguous natural strip facilitating wildlife movement and genetic gene-flow between disjointed forest patches")],
     "A-I, B-II, C-III, D-IV",
     "Core is inviolate, buffer permits controlled research/education, transition contains sustainable human settlements, and corridors connect fragmented habitats."),
    ("mcq", "First National Park of India",
     "Established in 1936 in Uttarakhand to protect the endangered Bengal tiger (originally named Hailey National Park), India's first national park is today known as:",
     "Jim Corbett National Park",
     ["Kaziranga National Park", "Kanha National Park", "Ranthambore National Park"],
     "Jim Corbett National Park (established in 1936 as Hailey National Park) is India's oldest national park, situated in the Nainital and Pauri Garhwal districts."),
    ("mcq", "First Biosphere Reserve of India",
     "Designated in 1986 under UNESCO's MAB framework, what was India's very first Biosphere Reserve, encompassing tropical forests across Tamil Nadu, Kerala, and Karnataka?",
     "Nilgiri Biosphere Reserve",
     ["Nanda Devi Biosphere Reserve", "Sundarbans Biosphere Reserve", "Gulf of Mannar Biosphere Reserve"],
     "The Nilgiri Biosphere Reserve (designated in 1986) was India's first biosphere reserve, conserving the Nilgiri Tahr and Lion-tailed Macaque."),
    ("stmt", "Ex-situ Conservation Techniques",
     "Cryopreservation involves freezing viable gametes, embryos, and tissue cultures at -196 degrees Celsius in liquid nitrogen for indefinite preservation.",
     "Botanical gardens and seed banks allow the conservation of endangered plant species and their wild crop relatives outside vulnerable wild habitats.", 1,
     "Both Statement I and Statement II are correct. Ex-situ approaches (seed banks, botanical gardens, cryobanks) protect germplasm against extinction in the wild."),
    ("seq", "Hierarchy of Protected Area Categorization in India",
     "Arrange the Indian protected area categories in order of increasing level of permitted community participation and human activity:",
     ["National Park (completely inviolate with zero private rights or livestock grazing)", "Wildlife Sanctuary (limited traditional livestock grazing and rights granted by District Collector)", "Conservation Reserve / Community Reserve (collaborative management with local panchayats and landowners)", "Biosphere Reserve Transition Zone (extensive sustainable agriculture, towns, and economic enterprises)"],
     "I -> II -> III -> IV",
     "Statutory protection ranges from strict inviolate National Parks to Sanctuaries, community-managed reserves, and populated transition zones."),
    ("mcq", "Cryopreservation Temperature and Medium",
     "In genetic cryopreservation of endangered flora and fauna germplasm, what chemical medium and temperature are universally utilized?",
     "Liquid Nitrogen at -196 degrees Celsius (-320 degrees Fahrenheit)",
     ["Dry Ice at -78 degrees Celsius", "Solid Argon at -189 degrees Celsius", "Liquid Helium at -269 degrees Celsius"],
     "Cryopreservation universally stores biological germplasm in liquid nitrogen at its boiling point of -196 degrees Celsius (-320 F)."),
    ("ar", "Sacred Groves as Conservation Refugia",
     "Sacred groves in the Western Ghats and Khasi Hills have preserved several plant species that are now completely extinct in the surrounding landscape.",
     "Traditional socio-cultural taboos against tree-felling, hunting, and grazing kept the sacred forest patches ecologically undisturbed for centuries.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Cultural and spiritual protection shielded sacred groves from logging, preserving rare climax species."),
    ("mcq", "World Heritage Natural Sites in India",
     "Which of the following Indian national parks is recognized as a UNESCO World Heritage Site famous for holding the world's largest population of the Great Indian One-Horned Rhinoceros?",
     "Kaziranga National Park (Assam)",
     ["Keoladeo National Park (Rajasthan)", "Gir National Park (Gujarat)", "Bandipur National Park (Karnataka)"],
     "Kaziranga National Park in Assam holds over two-thirds of the world's One-Horned Rhinoceroses (Rhinoceros unicornis) and is a UNESCO World Heritage site."),
    ("mcq", "Floating National Park of the World",
     "Keibul Lamjao National Park, the only floating national park in the world, is situated on Loktak Lake in Manipur to protect which critically endangered mammal?",
     "Sangai (Brow-antlered deer / Cervus eldi eldi) living on floating biomass phumdis",
     ["Snow Leopard", "Kashmir Stag (Hangul)", "Golden Langur"],
     "Keibul Lamjao National Park in Manipur is famous for its floating vegetative mats called 'phumdis', supporting the endangered Sangai dancing deer."),
    ("match", "Protected Area Types and Specific Indian Examples",
     "Match the conservation area category in List I with its famous Indian example in List II:",
     [("A", "National Park"),
      ("B", "Wildlife Sanctuary"),
      ("C", "Biosphere Reserve"),
      ("D", "Ex-situ Conservation Facility")],
     [("I", "Jim Corbett / Kaziranga"),
      ("II", "Periyar / Bharatpur (Keoladeo)"),
      ("III", "Nilgiri / Nanda Devi / Gulf of Mannar"),
      ("IV", "National Gene Bank at NBPGR, New Delhi")],
     "A-I, B-II, C-III, D-IV",
     "Jim Corbett is a National Park; Periyar is a Sanctuary; Nilgiri is a Biosphere Reserve; and the National Bureau of Plant Genetic Resources (NBPGR) houses the National Gene Bank."),
    ("mcq", "National Bureau of Plant Genetic Resources (NBPGR)",
     "India's premier ex-situ institution responsible for the collection, quarantine, and long-term seed-bank conservation of agricultural genetic resources is:",
     "National Bureau of Plant Genetic Resources (NBPGR), New Delhi",
     ["Forest Research Institute (FRI), Dehradun", "Botanical Survey of India (BSI), Kolkata", "Wildlife Institute of India (WII), Dehradun"],
     "The National Bureau of Plant Genetic Resources (NBPGR) in New Delhi maintains one of the largest national seed vaults and gene banks in the world."),
    ("mcq", "Svalbard Global Seed Vault",
     "Built deep inside a permafrost mountain on a remote Norwegian archipelago in the Arctic to safeguard the world's food crop diversity against global catastrophes, it is known as the:",
     "Svalbard Global Seed Vault ('Doomsday Vault')",
     ["Arctic Botanical Sanctuary", "Greenland Cryobank", "Nordic Marine Refugium"],
     "The Svalbard Global Seed Vault in Norway stores duplicate back-up seed samples of global food crops at -18 degrees Celsius deep inside permafrost."),
    ("stmt", "Wildlife Corridors Function",
     "Wildlife corridors are linear strips of natural habitat that connect isolated protected areas across human-dominated landscapes.",
     "Corridors prevent inbreeding depression, facilitate seasonal migration, and allow demographic rescue of localized small animal populations.", 1,
     "Both Statement I and Statement II are correct. Elephant and tiger corridors allow animal movement between fragmented reserves, preventing genetic stagnation."),
    ("mcq", "National Park where Asiatic Lions are Conserved",
     "Which protected area in Gujarat is celebrated as the last surviving natural wild refuge of the Asiatic Lion (Panthera leo persica)?",
     "Gir National Park and Wildlife Sanctuary",
     ["Dachigam National Park", "Ranthambore National Park", "Sundarbans National Park"],
     "Gir National Park and Wildlife Sanctuary in Saurashtra, Gujarat, is the sole remaining natural sanctuary in the world for the wild Asiatic Lion."),
    ("seq", "Process of Establishing an Ex-situ Seed Bank Accession",
     "Arrange the procedural steps followed by agricultural scientists to conserve wild plant germplasm in a long-term seed bank:",
     ["Collection of mature, viable seeds from diverse wild crop populations across environmental gradients", "Thorough cleaning, genetic inspection, and screening to remove pathogens and non-viable seeds", "Controlled moisture desiccation to reduce seed moisture content to optimal levels (3–7%)", "Hermetic sealing in moisture-proof foil envelopes and storage in sub-zero freezers (-18 to -20 degrees Celsius)"],
     "I -> II -> III -> IV",
     "Seed banking follows a standardized protocol: collecting wild germplasm, screening/cleaning, precise drying to 3–7% moisture, and sub-zero hermetic storage."),
    ("mcq", "Sacred Groves Across Indian States",
     "What are Sacred Groves traditionally known as in the state of Rajasthan?",
     "Orans",
     ["Deorais", "Kavu", "Law Kyntang"],
     "Sacred groves are called Orans in Rajasthan, Deorais in Maharashtra, Kavu in Kerala, and Law Kyntang in Meghalaya."),
    ("mcq", "Project Tiger Launch Date and Objective",
     "Launched on April 1, 1973 at Corbett National Park by the Government of India, Project Tiger aimed primarily to:",
     "Ensure a viable population of Bengal tigers in their natural habitats and preserve areas of biological importance as national heritage",
     ["Domesticate wild tigers for agricultural plowing and circus entertainment", "Export tiger pelts and bones to international pharmaceutical markets", "Confine all wild tigers permanently within zoological gardens in capital cities"],
     "Project Tiger was launched in 1973 to save the Bengal tiger from extinction by setting up dedicated Tiger Reserves managed by the National Tiger Conservation Authority (NTCA).")
]
'''

with open('scripts/subject_generators/append_evs_s7_10.py', 'w') as f:
    f.write(s7_to_10)

print("append_evs_s7_10.py written.")
