#!/usr/bin/env python3
"""
create_mmc_s21_30.py
Builds mmc_s21_30.py containing all 10 slots (Slots 21 to 30) for Mass Media & Mass Communication (Code 318).
"""

import sys, os

out_path = "scripts/subject_generators/mmc_s21_30.py"

# Open file and write header
f = open(out_path, "w", encoding="utf-8")
f.write('''# Mass Media & Mass Communication (Code 318) - Slots 21 to 30 (200 Questions)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from slot_helpers import mcq, stmt, ar, match, seq

SLOTS_21_30 = {}
''')

# We import make_mmc_s21_30's s21, s22, s23, and then append the rest
import make_mmc_s21_30 as base
for s_block in base.slots_code:
    f.write(s_block + "\n")

# Now let's write SLOT 24 and 25
slot24_25 = '''
# ==============================================================================
# SLOT 24: Television News Gathering & Production (ENG, DSNG, OB Vans, PTC)
# ==============================================================================
SLOTS_21_30[24] = [
    mcq("TV News Production", "ENG Definition",
        "In television journalism, what does the acronym 'ENG' stand for, and what technological shift did it represent?",
        "Electronic News Gathering; the historic shift from bulky 16mm celluloid film cameras to portable video cameras and electronic tape/solid-state storage",
        ["Emergency National Government; an order to shut down private broadcasts",
         "Electronic Network Grid; an electrical wire connecting studio lightbulbs",
         "Editorial News Graphics; an artistic software tool for title screens"],
        "ENG enabled field reporters to shoot lightweight video, view it instantly without chemical laboratory developing, and transmit it rapidly.",
        "Defines Electronic News Gathering (ENG)."),
    mcq("TV News Production", "Piece to Camera (PTC)",
        "What is a 'Piece to Camera' (PTC), also known as a stand-up, in a television news report?",
        "The moment in a news package where the field reporter faces the camera directly and delivers a portion of the narration or analysis",
        ["A technician cleaning the camera lens with a microfiber cloth",
         "A physical piece of metal that breaks inside the camera tripod",
         "A photograph of the camera printed in a magazine"],
        "A PTC establishes reporter presence at the scene, delivers crucial transitions, and enhances credibility by showing on-the-ground reporting.",
        "Defines a Piece to Camera (PTC) / Stand-up."),
    stmt("TV News Production", "DSNG vs OB Van",
        "A Digital Satellite News Gathering (DSNG) van is equipped with a satellite uplink dish to transmit live audio-video feeds directly to the newsroom from remote locations.",
        "An Outdoor Broadcast (OB) Van is a complete mobile multi-camera production control room on wheels used for covering massive live events like cricket matches or national parades.",
        "both_true",
        "Both statements are true. DSNG focuses on mobile satellite uplink transmission, while large OB vans house multi-camera production control facilities.",
        "Distinguishes DSNG satellite vans from comprehensive multi-camera OB vans."),
    ar("TV News Production", "Teleprompter Utility",
        "Television news anchors read scripts off a 'Teleprompter' mounted directly in front of the studio camera lens.",
        "A teleprompter displays scrolling text on a one-way mirrored glass, allowing the anchor to read the script while maintaining continuous direct eye contact with the camera.",
        "both_correct_explain",
        "Because the mirrored glass reflects text without obscuring the lens, anchors read smoothly while appearing to look directly at the audience.",
        "Explains the optical design and utility of a studio teleprompter."),
    match("TV News Production", "News Production Elements",
        "Match the television news production term in List-I with its description in List-II:",
        ["Sound Bite / Byte", "B-Roll / Cutaway", "Voice-Over (VO)", "Lower Third / Aston / Super"],
        ["A short, recorded statement from an interviewee or newsmaker", "Supplemental, contextual video footage cut into a story to illustrate what is being spoken about", "The news anchor or reporter reading copy over video footage being displayed on screen", "Text graphics placed in the lower portion of the screen showing speaker name and title"],
        "A-I, B-II, C-III, D-IV",
        "Byte = interview statement; B-roll = illustrative footage; VO = anchor voice over video; Lower third = name/title graphic banner.",
        "Matches television news production components to definitions."),
    mcq("TV News Production", "Sound on Tape (SOT)",
        "In television news scripting, what does the designation 'SOT' stand for?",
        "Sound on Tape (indicating recorded audio from an interview bite or event actuality)",
        ["Signal Over Transmission", "Silence On Timeline", "Screen Output Termination"],
        "SOT marks the transition in an AV script where the recorded audio/video bite of a newsmaker plays with its own synchronized sound.",
        "Identifies Sound on Tape (SOT) in television scripting."),
    stmt("TV News Production", "Package (PKG) Format",
        "A television news 'Package' (PKG) is a complete, self-contained, pre-edited story containing anchor intro, reporter voiceover, B-roll visuals, sound bites, and a PTC.",
        "A television news package should run for at least four continuous hours without any commercial interruptions.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because news packages are tightly edited, typically running between 90 seconds and 3 minutes.",
        "Defines a television news package (PKG) and its running time."),
    ar("TV News Production", "Cellular Backpacks (LiveU)",
        "Bonded cellular backpack systems (such as LiveU or Dejero) have largely replaced bulky DSNG satellite trucks for breaking live news coverage.",
        "Cellular backpacks bond multiple 4G/5G mobile SIM cards together, transmitting high-definition live video wirelessly from anywhere with cellular coverage at a fraction of satellite cost.",
        "both_correct_explain",
        "Bonded cellular backpacks offer portable, affordable, and instant transmission over cellular data networks, eclipsing expensive satellite trucks.",
        "Analyzes the technological disruption of bonded cellular backpacks over DSNG."),
    seq("TV News Production", "Field Television Reporting Workflow",
        "Arrange the stages of producing a field news package for an evening broadcast in operational sequence:",
        ["Reporter and camera operator arrive at breaking news location and survey scene", "Filming relevant B-roll visual footage, cutaways, and ambient natural sound (NatSound)", "Conducting on-camera interviews with eyewitnesses and filming closing PTC", "Writing two-column AV script and recording reporter voiceover track", "Editing video footage with voiceover, bytes, and graphics into final broadcast package"],
        "I -> II -> III -> IV -> V",
        "Field reporting workflow: Arrival/survey -> B-roll filming -> Interviews/PTC -> Script/Voiceover -> Non-linear video editing.",
        "Sequences the production workflow of a television news field package."),
    mcq("TV News Production", "Natural Sound (NatSound)",
        "In video editing, what is 'NatSound' (Natural Sound, also called Wild Track or Ambient Sound)?",
        "The ambient background environmental audio (such as cheering crowds, rain, or traffic) recorded on location that lends realism to a report",
        ["An opera singer performing in the studio",
         "The artificial beeping sound of a computer mouse",
         "The sound of the television director shouting instructions"],
        "Natural sound captures the acoustic environment of the event, immersing the viewer in the authentic atmosphere of the story.",
        "Defines Natural Sound (NatSound) in television news."),
    stmt("TV News Production", "Talking Head Critique",
        "A 'Talking Head' refers to a static, visually uninteresting shot of an anchor or expert speaking uninterrupted for long periods without cutaways or visual action.",
        "Good television journalism minimizes boring talking heads by intercutting dynamic, illustrative B-roll footage showing the events being described.",
        "both_true",
        "Both statements correctly critique static 'talking head' presentation and advocate for visually dynamic video storytelling.",
        "Evaluates the 'talking head' flaw and B-roll visual storytelling."),
    ar("TV News Production", "Cutaway Function in Editing",
        "In video editing, 'Cutaways' are inserted between two continuous shots of an interview subject.",
        "Cutaways prevent jarring 'Jump Cuts' and conceal edits when shortening an interviewee's lengthy monologue.",
        "both_correct_explain",
        "Inserting a cutaway (e.g. reporter nodding or hands gesticulating) bridges spliced video sections smoothly, masking jump cuts.",
        "Explains how cutaway shots eliminate jump cuts in video editing."),
    match("TV News Production", "PTC Varieties",
        "Match the Piece to Camera (PTC) type in List-I with its structural placement and goal in List-II:",
        ["Opening PTC", "Bridge PTC", "Closing / Sign-off PTC", "Demonstration PTC"],
        ["Hooking audience interest and setting up the core dilemma at the start", "Connecting two disparate sections of a story or transitioning between perspectives", "Summarizing the takeaway, providing future outlook, and delivering reporter sign-off", "Reporter actively participating in or physically demonstrating an activity while explaining"],
        "A-I, B-II, C-III, D-IV",
        "Opening = hook/setup; Bridge = transition between sections; Closing = summary/sign-off; Demo = active physical demonstration.",
        "Matches Piece to Camera (PTC) types to narrative functions."),
    mcq("TV News Production", "Reporter Sign-off",
        "Which of the following phrases exemplifies a standard television news field 'Sign-off'?",
        "'With cameraperson Rajesh Sharma, this is Priya Sen reporting for City News, Lucknow.'",
        ["'Please buy commercial insurance from our sponsors immediately.'",
         "'The weather tomorrow will be sixty degrees warmer.'",
         "'I refuse to answer any questions from the studio anchor.'"],
        "A sign-off identifies the cameraperson, reporter byline, news channel name, and reporting location, signaling the conclusion of the package.",
        "Recognizes a standard television news field sign-off."),
    stmt("TV News Production", "Live Phono / Phonocall",
        "A 'Phono' (phonocall) occurs when a field reporter provides breaking audio commentary live over a telephone line while the studio displays a still photo or map.",
        "Phonos are strictly illegal under all telecommunication laws.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because live phonos are a universal, routine emergency method for covering breaking news when video links are unavailable.",
        "Defines a live phone-in (phono) in television news."),
    ar("TV News Production", "Rule of Thirds in Camera Framing",
        "Television camera operators align an interview subject's eyes along the upper horizontal third line of the frame.",
        "The Rule of Thirds divides the frame with two horizontal and two vertical lines, placing key visual elements along grid intersections to create aesthetic balance.",
        "both_correct_explain",
        "Adhering to the rule of thirds prevents awkward dead space and places the subject's expressive facial features at naturally engaging visual focal points.",
        "Explains the Rule of Thirds in television camera composition."),
    mcq("TV News Production", "Lead-in in TV News",
        "In a television news bulletin, what is the 'Anchor Lead-in'?",
        "The introductory script read live by the studio anchor that establishes the context and introduces the reporter's pre-edited package",
        ["The heavy electrical cable connecting the cameras to the wall",
         "The commercial break played at the start of the morning",
         "The brand of makeup applied to the presenter's forehead"],
        "The anchor lead-in introduces the story, sets up the stakes, and tosses the broadcast to the field reporter's package or live feed.",
        "Identifies the anchor lead-in in television broadcasting."),
    match("TV News Production", "Technical Script Cues",
        "Match the television script instruction in List-I with its operational directive in List-II:",
        ["ANCHOR (ON CAM)", "VO (VOICE OVER)", "SOT (SOUND ON TAPE)", "OC / PTC (ON CAMERA / PIECE TO CAMERA)"],
        ["Anchor speaks directly to camera, visible on screen", "Anchor or reporter reads script while B-roll video plays on screen", "Recorded interview bite plays with its original video and synchronized audio", "Field reporter appears on screen speaking on location"],
        "A-I, B-II, C-III, D-IV",
        "Anchor on cam = studio anchor visible; VO = voice over video; SOT = synchronized sound on tape; PTC = field reporter on camera.",
        "Matches television news scripting cues to production directions."),
    seq("TV News Production", "Live Breaking News Protocol",
        "Arrange the stages of executing a breaking live news broadcast from an unexpected disaster site:",
        ["Assignment desk receives news flash and alerts nearest field reporter and camera crew", "Crew deploys cellular transmission unit and establishes live video link with PCR", "Producer cuts into live programming and anchor introduces breaking situation", "Anchor tosses to field reporter on location for live situation report", "Studio integrates incoming live visual feeds, eyewitness bytes, and official emergency updates"],
        "I -> II -> III -> IV -> V",
        "Breaking news flow: Flash alert -> Deployment/link setup -> Studio cut-in -> Live toss to field -> Ongoing multi-source integration.",
        "Sequences live breaking news operational protocol."),
    mcq("TV News Production", "Vox Pop Framing in TV",
        "When filming television 'Vox Pops' (street reactions), how should the camera operator frame the diverse respondents?",
        "Using medium close-up shots, alternating head directions (left-facing and right-facing) between speakers to avoid repetitive visual monotony",
        ["Filming all respondents exclusively from a distance of two kilometers away",
         "Filming only the respondents' shoes and socks",
         "Having all twenty respondents speak simultaneously into one microphone"],
        "Alternating screen direction and using expressive medium close-ups maintains visual rhythm and editorial dynamism across rapid street interviews.",
        "Explains camera framing best practices for television vox pops.")
]

# ==============================================================================
# SLOT 25: Television Studio Operations & Control Rooms (PCR, MCR, Lighting)
# ==============================================================================
SLOTS_21_30[25] = [
    mcq("Studio Operations", "PCR vs MCR",
        "What is the operational distinction between the Production Control Room (PCR) and the Master Control Room (MCR) in a television station?",
        "The PCR directs and mixes the live studio cameras, microphones, and graphics for a specific show; the MCR oversees the final transmission stream, commercials, and broadcast playout to the transmitter/satellite",
        ["The PCR is where employees eat lunch; the MCR is where janitors store brooms",
         "The PCR is located on the satellite in outer space; the MCR is underground",
         "The PCR handles radio; the MCR handles print newspapers"],
        "PCR controls show production in the studio; MCR manages continuous 24/7 channel transmission playout, automated schedules, and master broadcast feeds.",
        "Distinguishes the Production Control Room from the Master Control Room."),
    mcq("Studio Operations", "Vision Mixer / Video Switcher",
        "What is the role of the 'Vision Mixer' (both the console hardware and the operator) in the Production Control Room?",
        "Switching seamlessly between multiple camera angles, video servers, digital graphics, and remote satellite feeds during a live broadcast",
        ["Painting the studio walls with oil colors before morning news",
         "Adjusting the prescription lenses of the news anchor's eyeglasses",
         "Turning the studio ceiling air conditioning units on and off"],
        "The vision mixer selects and cuts, dissolves, or wipes between camera inputs and graphic feeds upon instructions from the director.",
        "Identifies the role and operation of the vision mixer/video switcher."),
    stmt("Studio Operations", "Three-Point Lighting System",
        "The classic 'Three-Point Lighting' system consists of the Key Light, the Fill Light, and the Back Light (Hair/Rim light).",
        "The Fill Light is placed opposite the Key Light to soften and eliminate harsh, dark shadows created by the Key Light.",
        "both_true",
        "Both statements are foundational truths of photographic and television lighting design.",
        "Validates the components and functions of three-point lighting."),
    ar("Studio Operations", "Back Light Function",
        "In television studio lighting, the 'Back Light' is positioned behind and above the presenter, shining down onto the head and shoulders.",
        "The back light creates a luminous outline that visually separates the presenter from the background, preventing them from blending flatly into the set.",
        "both_correct_explain",
        "The rim of light created by the back light separates the foreground subject from the background wall, imparting three-dimensional visual depth.",
        "Explains the function of the back light in separating subjects from background."),
    match("Studio Operations", "Three-Point Lighting Roles",
        "Match the lighting fixture in List-I with its primary illumination duty in List-II:",
        ["Key Light", "Fill Light", "Back Light / Rim Light", "Background / Set Light"],
        ["Primary, strongest light illuminating the subject and establishing basic exposure", "Secondary softer light placed opposite key light to soften shadows", "Shines from behind onto hair and shoulders to create three-dimensional depth", "Illuminates set walls, props, and backdrops to create environmental atmosphere"],
        "A-I, B-II, C-III, D-IV",
        "Key = main illumination; Fill = shadow softening; Back = rim/depth separation; Background = set atmosphere.",
        "Matches three-point lighting components to illumination duties."),
    mcq("Studio Operations", "Chroma Key / Green Screen",
        "What is the principle of 'Chroma Keying' (frequently using a green or blue cyclorama screen) in television studio production?",
        "An electronic compositing process that replaces a solid uniform color background (green) with a virtual digital set, graphic map, or video footage",
        ["A chemical paint that turns actors invisible to human eyes",
         "A lighting technique that permanently damages television cameras",
         "A method of printing color photographs on silk fabric"],
        "Chroma keying isolates and drops out a specific color hue (green/blue), seamlessly substituting it with digital graphics or virtual sets.",
        "Explains the technology of chroma keying/green screen compositing."),
    stmt("Studio Operations", "Why Green for Chroma Key?",
        "Green is the most common color used for chroma key backgrounds because human skin tones contain virtually no green pigment, preventing accidental transparency.",
        "Presenters on a green-screen set are strongly encouraged to wear bright green neckties and green suits.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because wearing green clothing on a green-screen set causes that clothing to become transparent and disappear.",
        "Explains why green is chosen for chroma key and wardrobe restrictions."),
    ar("Studio Operations", "Floor Manager's Role",
        "The 'Floor Manager' (Floor Director) is the Director's eyes, ears, and voice inside the physical studio space.",
        "Presenters cannot hear the Director speaking in the control room during a live broadcast, relying on the Floor Manager's standardized non-verbal hand cues.",
        "both_correct_explain",
        "Because open loudspeakers cannot be used in a live studio, the Floor Manager conveys director instructions through visual hand signals.",
        "Analyzes the role and communication methods of the television Floor Manager."),
    seq("Studio Operations", "Live Studio Show Countdown Sequence",
        "Arrange the final countdown commands delivered from the PCR before a live broadcast goes on air:",
        ["Director checks ready status of audio, cameras, teleprompter, and graphics", "Floor Manager calls for quiet in the studio ('Quiet on floor, going live')", "PCR Assistant Director counts down aloud: 'Ten, nine, eight... five, four, three, two...'", "Director commands: 'Cue anchor, take Camera One'", "Floor Manager points decisively at news anchor as tally light turns red"],
        "I -> II -> III -> IV -> V",
        "Studio countdown: Technical check -> Call for quiet -> Final verbal countdown -> Director's cue -> Floor manager cue/Red tally.",
        "Sequences live television studio launch countdown."),
    mcq("Studio Operations", "Camera Tally Light",
        "What is the meaning of the small red 'Tally Light' illuminating atop a studio television camera?",
        "It signals to the presenter and crew that this specific camera is currently 'hot' (live on air transmitting to viewers)",
        ["It warns that the camera battery has caught fire",
         "It indicates that the camera operator must immediately stop filming",
         "It signals that the television station has been purchased by a bank"],
        "The red tally light alerts the presenter exactly which camera lens to address during multi-camera switching.",
        "Identifies the meaning of the red camera tally light."),
    stmt("Studio Operations", "Cyclorama (Cyc)",
        "A 'Cyclorama' (Cyc) is a seamless curved backdrop wall in a television studio designed to eliminate sharp corners and create the illusion of infinite space.",
        "A cyclorama must always be constructed out of heavy corrugated sheet metal with sharp jagged edges.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because a cyc has smooth, curved (coved) corners to prevent shadows and visual seams.",
        "Defines a studio cyclorama (cyc)."),
    ar("Studio Operations", "Color Temperature (Kelvin)",
        "Studio lighting technicians must match the color temperature of all light fixtures, avoiding mixing 3200K tungsten fixtures with 5600K daylight fixtures without gel filters.",
        "Cameras white-balance to a single color temperature; uncorrected mixed lighting causes subjects to appear simultaneously orange and blue on screen.",
        "both_correct_explain",
        "Mismatched color temperatures produce uncorrectable color casts on video sensors, necessitating uniform color balancing.",
        "Analyzes color temperature balance in television lighting."),
    match("Studio Operations", "Floor Manager Hand Signals",
        "Match the standard television hand signal in List-I with its operational meaning in List-II:",
        ["Pointing index finger directly at presenter", "Rotating index finger in a circular motion", "Drawing index finger horizontally across throat", "Stretching both hands apart as if pulling toffee"],
        ["You are on the air, start speaking immediately (Cue)", "Wind it up, hurry up, speed up delivery", "Cut immediately, stop speaking, kill audio", "Stretch it out, slow down, we have surplus time to fill"],
        "A-I, B-II, C-III, D-IV",
        "Point finger = Cue; Circular finger = Speed up; Finger across throat = Cut immediately; Stretching hands = Stretch/slow down.",
        "Matches Floor Manager hand signals to operational instructions."),
    mcq("Studio Operations", "Intercom / Talkback System",
        "What is the 'Intercom' (Talkback / Matrix) system in a broadcast facility?",
        "An internal, multi-channel closed audio communication network allowing the director, producer, camera operators, sound engineer, and floor manager to converse continuously",
        ["A telephone service for viewers to order takeout food",
         "A public megaphone mounted on the station roof",
         "A radio transmitter broadcasting directly to police cars"],
        "The intercom connects all technical personnel across the control room, studio, and engineering bays during production.",
        "Identifies the function of the television talkback/intercom system."),
    stmt("Studio Operations", "Audio Console in PCR",
        "The audio engineer in the PCR controls the audio mixing console, balancing wireless lapel microphones, anchor desk mics, video playback sound, and musical stingers.",
        "Television audio mixing consoles are completely silent and do not require VU meters or faders.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because consoles use faders and VU/peak meters to monitor and balance sound levels.",
        "Evaluates the role of the studio audio engineer and mixing console."),
    ar("Studio Operations", "IFB (Interruptible Foldback)",
        "Television news anchors wear a discreet in-ear earpiece called an 'IFB' (Interruptible Foldback / Feedback).",
        "The IFB delivers the continuous program audio while allowing the news director or producer in the PCR to interrupt and speak breaking instructions directly into the anchor's ear.",
        "both_correct_explain",
        "The IFB allows live director-to-anchor cues without interrupting the broadcast audio heard by the viewing public.",
        "Explains the function and utility of an IFB earpiece."),
    mcq("Studio Operations", "Camera Pedestal",
        "In a professional broadcast studio, what is a 'Studio Pedestal'?",
        "A heavy, counterbalanced, pneumatic hydraulic mounting base with wheels that allows smooth height adjustments, panning, and crabbing across the smooth studio floor",
        ["A wooden stool where the director sits to rest",
         "A trophy awarded to the highest-rated sports reporter",
         "A decorative marble pillar placed in the studio entrance lobby"],
        "Pneumatic pedestals enable effortless vertical elevation changes and silky camera dollies across studio floors.",
        "Defines a broadcast camera pedestal."),
    match("Studio Operations", "PCR Roles",
        "Match the control room specialist in List-I with their operational responsibility in List-II:",
        ["Director", "Technical Director / Vision Mixer", "Audio Engineer", "Graphics Operator / CG Operator"],
        ["Calls camera cuts, guides show pacing, and leads all technical execution", "Physically pushes switcher buttons to execute cuts, dissolves, and keys", "Rides faders to ensure clean vocal levels and smooth audio transitions", "Triggers lower thirds, name supers, scoreboards, and full-frame graphic slides"],
        "A-I, B-II, C-III, D-IV",
        "Director = calls cuts/leads execution; Technical Director = pushes switcher buttons; Audio = levels/faders; Graphics = triggers lower thirds/slides.",
        "Matches PCR personnel to production duties."),
    seq("Studio Operations", "Pre-Broadcast Camera Check Procedure",
        "Arrange the stages of preparing a studio multi-camera setup before production:",
        ["Powering on cameras and checking electronic tally lamps and intercom lines", "Adjusting pedestal pneumatic pressure and leveling tripod heads", "Framing studio calibration chart to set electronic White Balance across all cameras", "Matching camera color matrices and iris apertures on Camera Control Units (CCU)", "Locking off establishing and wide-shot camera positions for the show opening"],
        "I -> II -> III -> IV -> V",
        "Camera check: Power/intercom -> Pedestal leveling -> White balance -> CCU alignment/iris -> Initial framing.",
        "Sequences multi-camera alignment and calibration procedure."),
    mcq("Studio Operations", "Camera Control Unit (CCU)",
        "What is the function of the 'Camera Control Unit' (CCU) operated by the video engineer in engineering control?",
        "To remotely adjust each studio camera's electronic iris (exposure), black levels, color balance, and gain to ensure all cameras look visually identical on air",
        ["To physically push the camera around the studio floor",
         "To clean the teleprompter glass with liquid detergent",
         "To translate the news script into computer binary numbers"],
        "The CCU allows remote engineering matching of optical and color parameters across all active studio cameras.",
        "Explains the role of the Camera Control Unit (CCU).")
]
'''
f.write(slot24_25 + "\n")

f.close()
print("Base slots 21 to 25 written.")
