import sys, os

out_path = "scripts/subject_generators/cs_s31_40.py"

content = '''import sys, os
sys.path.insert(0, os.getcwd())
from scripts.subject_generators.slot_helpers import mcq, stmt, ar, match, seq

def build_slot(ch, items):
    res = []
    for itm in items:
        qtype = itm[0]
        if qtype == "mcq":
            _, top, stem, corr, wrongs, expl = itm
            res.append(mcq(ch, top, stem, corr, wrongs, expl))
        elif qtype == "stmt":
            _, top, s1, s2, rel, expl = itm
            res.append(stmt(ch, top, s1, s2, rel, expl))
        elif qtype == "ar":
            _, top, a, r, rel, expl = itm
            res.append(ar(ch, top, a, r, rel, expl))
        elif qtype == "match":
            _, top, stem, l1, l2, pair, expl = itm
            res.append(match(ch, top, stem, l1, l2, pair, expl))
        elif qtype == "seq":
            _, top, stem, items_list, order_str, expl = itm
            res.append(seq(ch, top, stem, items_list, order_str, expl))
    assert len(res) == 20, f"Slot has {len(res)} items instead of 20"
    return res

CH_DF_II = "Data Handling using Pandas - II (DataFrames, Operations and Analysis)"
CH_PYPLOT = "Data Visualization using Pyplot"
CH_SQL_II = "Database Concepts, SQL Functions and Queries"
CH_SOCIETY = "Societal Impacts, Cyber Ethics and Data Protection"

# ==============================================================================
# Slot 31: DataFrame Attributes & Dimensions
# ==============================================================================
s31_raw = [
    ("mcq", "DataFrame Shape Attribute",
     "What does df.shape return for a DataFrame containing 5 rows and 3 columns?",
     "(5, 3) as a tuple representing (number of rows, number of columns)",
     ["(3, 5) as a tuple", "15 as an integer", "[5, 3] as a list"],
     "df.shape returns a 2-tuple representing the dimensionality of the DataFrame: (rows, columns)."),
    ("stmt", "DataFrame Size and Ndim Properties",
     "df.size returns the total count of elements in the DataFrame, equal to rows multiplied by columns.",
     "df.ndim is always equal to 2 for any standard Pandas DataFrame representing a two-dimensional structure.", 1,
     "Both Statement I and Statement II are correct. df.size gives total cell count and df.ndim is always 2 for DataFrames."),
    ("ar", "DataFrame Transposition Properties",
     "df.T transposes the DataFrame, interchanging its rows into columns and columns into rows.",
     "Upon transposing with df.T, the index labels and column labels of the DataFrame are swapped.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Transposing flips the coordinate axes, swapping row index and column index."),
    ("match", "DataFrame Fundamental Attributes",
     "Match the DataFrame attribute in List I with its description in List II:",
     [("A", "df.index"),
      ("B", "df.columns"),
      ("C", "df.dtypes"),
      ("D", "df.empty")],
     [("I", "Returns the row index / labels of the DataFrame"),
      ("II", "Returns the column labels of the DataFrame"),
      ("III", "Returns a Series containing the data types of each column"),
      ("IV", "Returns a boolean indicating True if DataFrame has zero elements")],
     "A-I, B-II, C-III, D-IV",
     "df.index provides row descriptors, df.columns provides column descriptors, df.dtypes gives per-column data types, and df.empty checks for zero elements."),
    ("seq", "Attribute Numerical Values in Ascending Order",
     "For a DataFrame df with 4 rows and 3 columns, arrange the following attributes in ascending numerical order of their evaluated values:",
     [("A", "df.ndim"),
      ("B", "df.shape[1]"),
      ("C", "df.shape[0]"),
      ("D", "df.size")],
     "A, B, C, D",
     "df.ndim = 2, df.shape[1] (columns) = 3, df.shape[0] (rows) = 4, and df.size (4*3) = 12. Sorted order: A (2), B (3), C (4), D (12).")
]

s31_extras = [
    ("DataFrame Values Attribute", "What does the df.values attribute return for a Pandas DataFrame?",
     "A two-dimensional NumPy ndarray containing the raw values of the DataFrame",
     ["A Python dictionary of column names", "A single string containing all numbers", "A tuple of row labels"],
     "df.values extracts the internal data representation as a 2D NumPy ndarray."),
    ("DataFrame Axes Property", "What is returned by accessing df.axes on a DataFrame?",
     "A list of length 2 containing [row_index, column_index]",
     ["A scalar integer indicating 2", "A dictionary of data types", "A list of numerical values"],
     "df.axes returns a list containing the two axis objects: the row Index and the column Index."),
    ("Row Count via len()", "What does len(df) evaluate to for a DataFrame with 8 rows and 4 columns?",
     "8 (the number of rows in the DataFrame)",
     ["4 (the number of columns)", "32 (the total elements)", "2 (the dimensions)"],
     "len(df) returns the number of rows (the length of the index axis)."),
    ("DataFrame Total Cell Count", "If a DataFrame has shape (10, 4), what is the value returned by df.size?",
     "40",
     ["14", "10", "4"],
     "df.size is the product of row count and column count: 10 * 4 = 40."),
    ("Return Type of df.dtypes", "What is the return type of df.dtypes in Pandas?",
     "A Series indexed by column names with their respective data types",
     ["A single string indicating the dominant dtype", "A Python tuple of data types", "A 1D NumPy array of strings"],
     "df.dtypes returns a Pandas Series where index labels are column names and values are data types."),
    ("Transposed Shape Computation", "If df has shape (6, 2), what will be the shape of df.T?",
     "(2, 6)",
     ["(6, 2)", "(12, 1)", "(2, 2)"],
     "Transposition swaps rows and columns; hence shape (6, 2) becomes (2, 6)."),
    ("DataFrame Memory Usage", "Which method returns a Series showing the memory footprint in bytes consumed by each column?",
     "df.memory_usage()",
     ["df.bytes()", "df.ram_size()", "df.storage()"],
     "df.memory_usage() computes the memory consumption of each column and index in bytes."),
    ("Empty DataFrame Verification", "Which attribute provides a direct boolean check whether a DataFrame contains no data elements?",
     "df.empty",
     ["df.is_null", "df.blank", "df.zero"],
     "df.empty returns True if the DataFrame has 0 rows or 0 columns."),
    ("Heterogeneous Column Dtypes", "Can individual columns in a single Pandas DataFrame have different data types (e.g., int, float, string)?",
     "Yes, DataFrames are 2D heterogeneous tabular structures where each column can hold a distinct dtype",
     ["No, all columns must strictly share identical dtypes", "Only if the DataFrame has fewer than 10 rows", "No, Pandas only supports floating-point data"],
     "DataFrames are designed specifically to support heterogeneous tabular data with distinct dtypes per column."),
    ("DataFrame Dimensionality Property", "Which attribute explicitly returns the number of axes / dimensions (always 2 for DataFrame)?",
     "df.ndim",
     ["df.dims", "df.dimension", "df.axes_count"],
     "df.ndim indicates the number of dimensions, which is 2 for DataFrames and 1 for Series."),
    ("Accessing Row Count from Shape", "How can the number of rows in DataFrame df be extracted from its shape attribute?",
     "df.shape[0]",
     ["df.shape[1]", "df.shape.rows", "df.shape[-2:-1]"],
     "df.shape is a tuple (rows, cols); hence index 0 corresponds to row count."),
    ("Column Names as List", "How can you obtain a standard Python list containing all column label strings of DataFrame df?",
     "list(df.columns)",
     ["df.columns.to_list_py()", "str(df.columns)", "df.get_column_list()"],
     "list(df.columns) or df.columns.tolist() converts the Index of column labels into a native Python list."),
    ("Non-null Value Count per Column", "What does df.count() compute by default on a DataFrame?",
     "The number of non-null (valid) observations along each column (axis=0)",
     ["The total number of missing NaN entries", "The average value of each column", "The total number of rows regardless of nulls"],
     "df.count() computes the count of valid, non-null values for each column."),
    ("Default Row Index Type", "When a DataFrame is created without supplying custom index labels, what type of Index is assigned?",
     "RangeIndex(start=0, stop=n, step=1)",
     ["CategoricalIndex", "MultiIndex", "StringIndex"],
     "By default, Pandas assigns a RangeIndex starting at 0 up to n-1."),
    ("DataFrame True Column Count", "How can you programmatically get the total number of columns in DataFrame df?",
     "len(df.columns) or df.shape[1]",
     ["df.count_cols()", "len(df)", "df.size // 2"],
     "The number of columns is given by df.shape[1] or the length of the column index len(df.columns).")
]

# ==============================================================================
# Slot 32: DataFrame Selection (loc, iloc, boolean masking)
# ==============================================================================
s32_raw = [
    ("mcq", "Label-based vs Integer-based Indexing",
     "What is the definitive operational difference between df.loc[] and df.iloc[] in Pandas?",
     "df.loc[] is label-based (inclusive of endpoint), while df.iloc[] is 0-based integer positional (exclusive of endpoint)",
     ["df.loc[] works only on columns and df.iloc[] on rows", "df.loc[] uses integers and df.iloc[] uses string labels", "df.loc[] is deprecated in favor of df.iloc[]"],
     "df.loc[] indexes by label and includes both start and stop labels; df.iloc[] indexes by integer positions and excludes stop position."),
    ("stmt", "Slice Inclusion in loc and iloc",
     "In df.loc['RowA':'RowC'], the row labeled 'RowC' is included in the sliced result.",
     "In df.iloc[0:2], the row at integer index position 2 is excluded from the sliced result.", 1,
     "Both Statement I and Statement II are correct. Label slicing with loc includes endpoints; integer slicing with iloc excludes endpoints."),
    ("ar", "Boolean Masking in Pandas",
     "The relational expression df['Marks'] >= 75 generates a boolean Series with the same index as df.",
     "Comparison operators applied to a Pandas Series execute element-wise vector evaluations returning True or False for each entry.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Series comparisons evaluate element-by-element, creating a boolean mask."),
    ("match", "DataFrame Selection Syntaxes",
     "Match the selection syntax in List I with its description in List II:",
     [("A", "df['Score']"),
      ("B", "df[['Score']]"),
      ("C", "df.loc['R1':'R3', 'A':'B']"),
      ("D", "df.iloc[0:3, 1:3]")],
     [("I", "Extracts a single column as a 1D Series"),
      ("II", "Extracts a single column as a 2D DataFrame"),
      ("III", "Selects rows R1..R3 and columns A..B using labels (inclusive)"),
      ("IV", "Selects rows 0..2 and columns 1..2 using integer positions (exclusive)")],
     "A-I, B-II, C-III, D-IV",
     "Single bracket yields a Series; double brackets yield a DataFrame; loc slices labels inclusively; iloc slices positions exclusively."),
    ("seq", "Hierarchical Data Extraction Narrowing",
     "Arrange the following indexing expressions in decreasing order of extracted data dimensionality / granularity:",
     [("A", "df (Full DataFrame)"),
      ("B", "df[df['Age'] > 18] (Filtered subset of rows)"),
      ("C", "df[df['Age'] > 18][['Name', 'Score']] (Subset of rows with two selected columns)"),
      ("D", "df[df['Age'] > 18]['Score'].iloc[0] (A single scalar value)")],
     "A, B, C, D",
     "Expressions progress from full DataFrame (A) to row-filtered DataFrame (B) to 2-column DataFrame (C) to scalar float/int value (D).")
]

s32_extras = [
    ("Single Cell Scalar Access by Label", "Which accessor provides fastest scalar value access using row and column labels?",
     "df.at['RowLabel', 'ColLabel']",
     ["df.value('RowLabel', 'ColLabel')", "df.get_scalar('RowLabel', 'ColLabel')", "df.scalar['RowLabel', 'ColLabel']"],
     "df.at is optimized for high-performance single scalar lookup by label."),
    ("Positional Column Extraction", "What does df.iloc[:, 0] return for any non-empty DataFrame?",
     "The first column of the DataFrame across all rows as a Pandas Series",
     ["The first row of the DataFrame across all columns", "The top-left single scalar cell", "A DataFrame containing only column 0"],
     "The slice : selects all rows, and 0 selects the first column, returning a Series."),
    ("Compound Boolean Filtering", "How do you filter rows in DataFrame df where 'City' is 'Delhi' AND 'Age' is greater than 20?",
     "df[(df['City'] == 'Delhi') & (df['Age'] > 20)]",
     ["df[df['City'] == 'Delhi' and df['Age'] > 20]", "df[(df['City'] == 'Delhi') && (df['Age'] > 20)]", "df[City == 'Delhi' & Age > 20]"],
     "Pandas requires bitwise & for element-wise logical AND, and each sub-condition must be enclosed in parentheses."),
    ("Python Logical 'and' Error", "Why does df[(df['A'] > 5) and (df['B'] < 10)] fail with a ValueError in Pandas?",
     "Python's logical 'and' evaluates the truth value of the entire array at once, which is ambiguous for multiple booleans",
     ["Because column names cannot be capital letters", "Because Python does not support comparisons in brackets", "Because 'and' is a reserved SQL keyword"],
     "Python's built-in boolean operators 'and'/'or' require a single scalar truth value; vectorized Pandas requires '&'/'|'."),
    ("Extracting the Last Row", "Which statement extracts the very last row of DataFrame df as a Series?",
     "df.iloc[-1]",
     ["df.loc[-1]", "df.last()", "df.tail(-1)"],
     "df.iloc[-1] uses negative integer positional indexing to access the final row."),
    ("Positional Row Slicing", "What rows are selected by df.iloc[2:5]?",
     "Rows at integer positions 2, 3, and 4 (3 rows total)",
     ["Rows at integer positions 2, 3, 4, and 5 (4 rows total)", "Rows 1, 2, 3", "Only row 2 and row 5"],
     "Integer slicing in iloc follows standard Python slice rules: start is included, stop is excluded (indices 2, 3, 4)."),
    ("Label Column Slicing", "What does df.loc[:, 'Math':'Science'] return?",
     "All rows, and all columns from 'Math' up to and including 'Science'",
     ["Only the 'Math' and 'Science' columns, skipping columns in between", "Only the first row for Math and Science", "An error because columns cannot be sliced by label"],
     "df.loc[:, 'Math':'Science'] slices all consecutive columns between 'Math' and 'Science', inclusive of both endpoints."),
    ("Fast Positional Scalar Lookup", "Which accessor is optimized for fastest single scalar lookup by integer position?",
     "df.iat[row_idx, col_idx]",
     ["df.get_pos(row_idx, col_idx)", "df.cell(row_idx, col_idx)", "df.scalar(row_idx, col_idx)"],
     "df.iat provides extremely fast scalar access using integer coordinates."),
    ("df.head() Default Behavior", "How many rows are returned by default when df.head() is called without parameters?",
     "5 rows",
     ["10 rows", "1 row", "All rows"],
     "df.head() returns the first 5 rows of the DataFrame by default."),
    ("df.tail(3) Behavior", "What does df.tail(3) return?",
     "The last 3 rows of the DataFrame",
     ["The first 3 rows of the DataFrame", "3 random rows from the DataFrame", "All rows except the last 3"],
     "df.tail(n) displays the final n rows of the DataFrame."),
    ("Value Membership Filtering", "Which method filters rows where the 'Subject' column matches any element in ['Physics', 'Chemistry']?",
     "df[df['Subject'].isin(['Physics', 'Chemistry'])]",
     ["df[df['Subject'].contains(['Physics', 'Chemistry'])]", "df[df['Subject'].in_list(['Physics', 'Chemistry'])]", "df[df['Subject'] == ['Physics', 'Chemistry']]"],
     "Series.isin(values) returns a boolean mask indicating whether each element matches any value in the provided collection."),
    ("Single vs Double Bracket Return Type", "What is the return type of df[['Age']] versus df['Age']?",
     "df[['Age']] returns a DataFrame; df['Age'] returns a Series",
     ["df[['Age']] returns a Series; df['Age'] returns a DataFrame", "Both return a Series", "Both return a DataFrame"],
     "Passing a list of column names [['col']] returns a 2D DataFrame; passing a single string ['col'] returns a 1D Series."),
    ("String Prefix Filtering", "How do you select rows where string column 'Student' begins with 'A'?",
     "df[df['Student'].str.startswith('A')]",
     ["df[df['Student'].startswith('A')]", "df[df['Student'][0] == 'A']", "df[df['Student'].like('A%')]"],
     "Vectorized string operations in Pandas are accessed via the .str accessor: df['Col'].str.startswith('A')."),
    ("iloc Row and Column Subset Sizing", "In df.iloc[1:4, :2], how many rows and columns are contained in the result?",
     "3 rows and 2 columns",
     ["4 rows and 2 columns", "3 rows and 3 columns", "1 row and 2 columns"],
     "Rows selected: positions 1, 2, 3 (3 rows). Columns selected: positions 0, 1 (2 columns). Result is 3 rows by 2 columns."),
    ("Filtering with Negation Operator", "How can you invert a boolean condition mask in Pandas (e.g. select all rows where 'Pass' is NOT True)?",
     "df[~df['Pass']]",
     ["df[!df['Pass']]", "df[not df['Pass']]", "df[-df['Pass']]"],
     "The tilde operator (~) acts as the bitwise NOT operator for inverting boolean Series in Pandas.")
]

# ==============================================================================
# Slot 33: DataFrame Manipulation (Add/Drop/Rename)
# ==============================================================================
s33_raw = [
    ("mcq", "Adding New Column with Scalar Broadcasting",
     "How do you add a new column named 'Score' with all values initialized to 100 in an existing DataFrame df?",
     "df['Score'] = 100",
     ["df.add_column('Score', 100)", "df.insert_col('Score', 100)", "df.new('Score') = 100"],
     "Assigning a scalar to a new column name df['new_col'] = value automatically broadcasts the value to all rows."),
    ("stmt", "DataFrame drop() Axis and Inplace Parameters",
     "df.drop('ColA', axis=1) removes 'ColA' from the returned DataFrame without modifying the original df unless inplace=True is set.",
     "In df.drop(), axis=0 specifies dropping rows by label, which is the default axis behavior.", 1,
     "Both Statement I and Statement II are correct. drop() defaults to axis=0 (rows), requires axis=1 for columns, and is non-destructive unless inplace=True."),
    ("ar", "Inplace Renaming Mechanics",
     "df.rename(columns={'old_name': 'new_name'}, inplace=True) modifies the column header in the existing DataFrame without reassignment.",
     "The parameter inplace=True instructs Pandas methods to mutate the underlying object directly rather than returning a modified copy.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). inplace=True modifies the caller object in place."),
    ("match", "DataFrame Modification Operations",
     "Match the modification syntax in List I with its operation in List II:",
     [("A", "df.drop(columns=['C1', 'C2'])"),
      ("B", "df.drop(index=['R1', 'R2'])"),
      ("C", "df.rename(index={'r1': 'Row1'})"),
      ("D", "del df['OldCol']")],
     [("I", "Drops specified columns by name"),
      ("II", "Drops specified rows by index label"),
      ("III", "Renames row index labels"),
      ("IV", "Permanently deletes a column in place using Python keyword")],
     "A-I, B-II, C-III, D-IV",
     "drop(columns=...) removes columns, drop(index=...) removes rows, rename(index=...) updates row labels, and del permanently deletes a column."),
    ("seq", "Pipeline of DataFrame Column Transformation",
     "Arrange the sequential steps in calculating a derived total column and cleaning raw features:",
     [("A", "Instantiate DataFrame with raw columns 'Theory' and 'Practical'"),
      ("B", "Calculate derived total: df['Total'] = df['Theory'] + df['Practical']"),
      ("C", "Drop raw feature columns: df.drop(columns=['Theory', 'Practical'], inplace=True)"),
      ("D", "Rename 'Total' to 'Final_Score': df.rename(columns={'Total': 'Final_Score'}, inplace=True)")],
     "A, B, C, D",
     "Sequence: create raw DataFrame (A) -> compute derived column (B) -> drop raw columns (C) -> rename final column (D).")
]

s33_extras = [
    ("Permanent Column Deletion via del", "Which statement permanently removes the column 'Salary' from DataFrame df using Python's del keyword?",
     "del df['Salary']",
     ["del df.loc['Salary']", "del(df.columns['Salary'])", "delete df['Salary']"],
     "del df['column_name'] is a built-in Python statement that mutates the DataFrame in place by removing the specified column."),
    ("Default Axis in df.drop()", "What happens if you execute df.drop('ColA') without specifying the axis parameter?",
     "Pandas searches for a row with index label 'ColA' (axis=0) and raises a KeyError if no such row label exists",
     ["It automatically drops the column 'ColA'", "It drops both row and column 'ColA'", "It deletes the entire DataFrame"],
     "The default parameter in df.drop() is axis=0 (rows); to drop a column, axis=1 or columns='ColA' must be specified."),
    ("Adding New Row using loc", "How can a new row with index label 'R5' be appended to DataFrame df with values [10, 20, 30]?",
     "df.loc['R5'] = [10, 20, 30]",
     ["df.append_row('R5', [10, 20, 30])", "df['R5'] = [10, 20, 30]", "df.add_row('R5', [10, 20, 30])"],
     "Assigning a sequence or dict to a new row label via df.loc['new_label'] appends or updates that row in place."),
    ("Excluding Row Index on CSV Export", "Which argument in df.to_csv('out.csv') prevents writing the row index column to the file?",
     "index=False",
     ["no_index=True", "header=False", "drop_index=True"],
     "index=False suppresses writing the row labels as the first column in the exported CSV file."),
    ("df.pop() Column Method", "What does df.pop('ColA') do?",
     "Deletes 'ColA' from df in place and returns 'ColA' as a Series",
     ["Deletes 'ColA' only if it is empty", "Returns 'ColA' without modifying df", "Renames 'ColA' to 'pop'"],
     "df.pop() removes the specified column from the DataFrame and returns it as a Series object."),
    ("Resetting Row Index", "Which method resets the DataFrame row index back to standard sequential integers 0, 1, 2...?",
     "df.reset_index(drop=True)",
     ["df.reindex_default()", "df.clean_index()", "df.zero_index()"],
     "df.reset_index(drop=True) replaces the existing index with RangeIndex(0, n) and drops the old index."),
    ("Setting Index to Existing Column", "How do you set an existing column 'RollNo' as the new row index of DataFrame df?",
     "df.set_index('RollNo', inplace=True)",
     ["df.index = 'RollNo'", "df.make_index('RollNo')", "df.assign_index('RollNo')"],
     "df.set_index('ColName', inplace=True) sets the designated column as the new index."),
    ("Removing Duplicate Rows", "Which method eliminates duplicate rows from a DataFrame, retaining the first occurrence by default?",
     "df.drop_duplicates()",
     ["df.unique()", "df.distinct()", "df.remove_repeats()"],
     "df.drop_duplicates() identifies and drops identical rows across all or specified columns."),
    ("Reindexing DataFrame Rows", "Which method reindexes the rows of df according to a new specified sequence of labels?",
     "df.reindex(['r1', 'r2', 'r3'])",
     ["df.set_labels(['r1', 'r2', 'r3'])", "df.sort_index(['r1', 'r2', 'r3'])", "df.remap(['r1', 'r2', 'r3'])"],
     "df.reindex() conforms the DataFrame to a new index, inserting NaN for any newly introduced labels."),
    ("Index Alignment in Column Assignment", "When assigning a Series s with index [0, 1] to df['NewCol'] where df has index [0, 1, 2], what value appears in row 2?",
     "NaN (missing value) due to index label alignment",
     ["0", "Error is raised", "The value from row 1 is duplicated"],
     "Pandas strictly aligns Series assignments by index labels; unaligned rows receive NaN."),
    ("Simultaneous Row and Column Renaming", "How can you rename both rows and columns in a single call to df.rename()?",
     "df.rename(index={'r1': 'Row1'}, columns={'c1': 'Col1'})",
     ["df.rename(['r1', 'Row1'], ['c1', 'Col1'])", "df.rename_both({'r1': 'Row1'}, {'c1': 'Col1'})", "df.alter(row={'r1': 'Row1'}, col={'c1': 'Col1'})"],
     "df.rename() accepts separate dictionaries for index and columns parameters simultaneously."),
    ("Ignoring Errors in df.drop()", "What parameter in df.drop() prevents raising an exception if a specified column label does not exist?",
     "errors='ignore'",
     ["suppress=True", "silent=True", "check=False"],
     "Setting errors='ignore' suppresses KeyError when attempting to drop non-existent labels."),
    ("Sorting DataFrame by Column Values", "How do you sort DataFrame df by the values in column 'Marks' in descending order?",
     "df.sort_values(by='Marks', ascending=False)",
     ["df.sort('Marks', reverse=True)", "df.order_by('Marks', desc=True)", "df.sort_column('Marks', False)"],
     "df.sort_values(by='Marks', ascending=False) sorts the table in descending order of column 'Marks'."),
    ("Sorting DataFrame by Row Index", "How do you sort DataFrame df by its row index labels in ascending order?",
     "df.sort_index(ascending=True)",
     ["df.sort_rows()", "df.order_index()", "df.arrange_index()"],
     "df.sort_index() sorts the DataFrame along the index axis."),
    ("Vectorized Column Multiplication", "What is the result of executing df['Gross'] = df['Basic'] * 1.2?",
     "Adds or updates column 'Gross' where each element is 1.2 times the corresponding element in 'Basic'",
     ["Multiplies the entire DataFrame by 1.2", "Converts 'Gross' to a string", "Raises an error because scalar multiplication on columns is prohibited"],
     "Arithmetic operations between a column and a scalar operate element-wise in a vectorized manner.")
]

# ==============================================================================
# Slot 34: DataFrame Missing Data (isna, dropna, fillna)
# ==============================================================================
s34_raw = [
    ("mcq", "Standard Missing Value Representation",
     "In Pandas, what standard floating-point object is used to denote missing, unrecorded, or undefined values?",
     "NaN (Not a Number) / np.nan",
     ["NULL", "NoneType only", "BLANK"],
     "Pandas represents missing numerical data using IEEE 754 floating-point NaN (np.nan)."),
    ("stmt", "isna() and notna() Behavior",
     "df.isna() and df.isnull() are exact functional aliases in Pandas returning identical boolean masks.",
     "df.notna() returns True for valid observations and False for NaN or missing entries.", 1,
     "Both Statement I and Statement II are correct. isna() and isnull() are identical aliases, and notna() is the logical inverse."),
    ("ar", "dropna how='all' vs how='any'",
     "Executing df.dropna(how='all') only drops rows where every single column entry is NaN.",
     "The default setting in dropna() is how='any', which eliminates a row if even one column contains NaN.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). how='all' requires 100% null entries along the axis, whereas how='any' requires only one null entry."),
    ("match", "Missing Data Cleaning Functions",
     "Match the missing data function in List I with its action in List II:",
     [("A", "df.isna().sum()"),
      ("B", "df.fillna(0)"),
      ("C", "df.dropna(axis=1)"),
      ("D", "df.fillna(method='ffill')")],
     [("I", "Counts total missing values in each column"),
      ("II", "Replaces all NaN values with 0 across the DataFrame"),
      ("III", "Drops all columns containing any NaN value"),
      ("IV", "Forward-fills missing entries using previous valid values")],
     "A-I, B-II, C-III, D-IV",
     "isna().sum() tallies nulls, fillna(0) imputes zeros, dropna(axis=1) removes incomplete columns, and ffill propagates prior valid entries."),
    ("seq", "Missing Data Treatment Workflow",
     "Arrange the professional data cleaning steps for handling missing values in order:",
     [("A", "Detect and count missing values using df.isna().sum()"),
      ("B", "Evaluate missingness patterns and decide whether to impute or drop"),
      ("C", "Impute missing numeric values using df['Col'].fillna(df['Col'].mean(), inplace=True)"),
      ("D", "Verify data completeness using assert df.isna().sum().sum() == 0")],
     "A, B, C, D",
     "Sequence: detect nulls (A) -> assess strategy (B) -> impute missing values (C) -> verify zero remaining nulls (D).")
]

s34_extras = [
    ("Arithmetic Involving NaN", "What is the result of standard arithmetic addition between an integer and NaN (e.g., 10 + np.nan)?",
     "NaN (Not a Number)",
     ["10", "0", "TypeError exception"],
     "Standard arithmetic operations involving NaN propagate NaN as the output."),
    ("Default skipna Behavior in Aggregations", "Does df['Score'].sum() include or skip NaN values by default in Pandas?",
     "It skips NaN values by default (skipna=True) and computes the sum of valid numbers",
     ["It evaluates to NaN if any NaN is present", "It raises a ValueError", "It converts NaNs to 1"],
     "Pandas aggregation functions skip missing values by default (skipna=True)."),
    ("Default Axis in df.dropna()", "What does df.dropna() do by default when called without arguments?",
     "Drops all rows (axis=0) that contain at least one NaN value (how='any')",
     ["Drops all columns containing NaN", "Replaces NaNs with zeros", "Drops only rows where all columns are NaN"],
     "By default, df.dropna() drops rows (axis=0) having any missing values (how='any')."),
    ("Backward Fill Parameter", "Which method or parameter fills missing values using the next immediate valid observation?",
     "df.fillna(method='bfill') or df.bfill()",
     ["df.fillna(method='next')", "df.fillna(direction='back')", "df.backwards()"],
     "bfill (backward fill) propagates the next valid observation backwards to fill gaps."),
    ("Column-Specific fillna via Dict", "How can you impute NaN values with 0 in column 'Age' and 'Unknown' in column 'City' simultaneously?",
     "df.fillna({'Age': 0, 'City': 'Unknown'})",
     ["df.fillna(['Age': 0, 'City': 'Unknown'])", "df.replace_null('Age'=0, 'City'='Unknown')", "df.fill({'Age': 0}, {'City': 'Unknown'})"],
     "Passing a dictionary of {column_name: fill_value} to df.fillna() allows column-specific imputation."),
    ("Checking Presence of Any Nulls", "What does df.isna().any() return for a DataFrame?",
     "A Series of booleans indicating whether each column contains at least one NaN",
     ["A single boolean True if entire DataFrame has nulls", "A list of row indices containing nulls", "The count of null values"],
     "df.isna().any() evaluates column-wise (axis=0), returning True for columns with >=1 NaN."),
    ("IEEE 754 NaN Equality Paradox", "In Python/NumPy, what does the expression np.nan == np.nan evaluate to?",
     "False (by IEEE 754 floating-point standard, NaN is not equal to anything, including itself)",
     ["True", "None", "Raises an error"],
     "By IEEE 754 definition, NaN != NaN is True, and NaN == NaN is False. To test for NaN, np.isnan() or pd.isna() must be used."),
    ("dropna Subset Parameter", "Which syntax drops rows only if NaN appears specifically in column 'Age' or 'Salary'?",
     "df.dropna(subset=['Age', 'Salary'])",
     ["df.dropna(cols=['Age', 'Salary'])", "df.dropna(only=['Age', 'Salary'])", "df[['Age', 'Salary']].dropna()"],
     "The subset parameter in dropna restricts null inspection to the designated list of columns."),
    ("dropna Thresh Parameter", "What does df.dropna(thresh=3) do for a DataFrame?",
     "Retains only rows that have at least 3 non-null (valid) observations",
     ["Drops rows that have 3 or more null values", "Drops the first 3 rows", "Drops rows with exactly 3 non-null values"],
     "The thresh=n argument requires that a row/column must contain at least n non-null values to be kept."),
    ("Integer Dtype Upcasting to Float", "In standard Pandas, why does an integer column convert to float64 when a NaN value is introduced?",
     "Standard NumPy integer dtypes cannot represent NaN; hence Pandas upcasts to float64 to accommodate NaN",
     ["Because floats consume less memory", "Because Python rounds integers during assignments", "Because integer dtypes are deprecated in Pandas"],
     "Standard numpy int64 cannot represent missing values, forcing conversion to float64 to support NaN."),
    ("Replacing Sentinel Values with NaN", "How do you replace invalid sentinel values of -999 with NaN across DataFrame df?",
     "df.replace(-999, np.nan, inplace=True)",
     ["df.fillna(-999 = np.nan)", "df.substitute(-999, np.nan)", "df.nullify(-999)"],
     "df.replace(old_value, new_value) replaces occurrences of specific sentinel values with np.nan."),
    ("Grand Total of Missing Values", "Which expression computes the grand total number of missing cells across an entire DataFrame df?",
     "df.isna().sum().sum()",
     ["df.isna().count()", "df.total_missing()", "len(df.isna())"],
     "df.isna().sum() yields column-wise null sums; calling .sum() again computes the grand total scalar count."),
    ("Partial Missing Row Evaluation", "If a row has values [10, np.nan, 30, np.nan], does df.dropna(how='any') drop this row?",
     "Yes, because at least one cell contains NaN",
     ["No, because more than half the values are valid", "No, because how='any' requires all values to be NaN", "Only if axis=1 is specified"],
     "how='any' drops the entry if any null value is encountered."),
    ("Non-null Counting in describe()", "Does df.describe() count NaN entries in its summary calculations?",
     "No, the count row in describe() reflects only valid non-null entries, and statistics exclude NaNs",
     ["Yes, NaNs are counted as 0", "Yes, NaNs are counted as 1", "describe() raises an error if NaNs exist"],
     "Summary statistics generated by describe() explicitly exclude missing observations."),
    ("Linear Value Interpolation", "Which Pandas method fills missing numerical values along a linear gradient between surrounding valid observations?",
     "df.interpolate(method='linear')",
     ["df.gradient_fill()", "df.smooth()", "df.linear_fill()"],
     "df.interpolate() fills NaN values using various mathematical interpolation techniques, defaulting to linear.")
]

# ==============================================================================
# Slot 35: Descriptive Statistics & Aggregations
# ==============================================================================
s35_raw = [
    ("mcq", "Default Axis for Descriptive Aggregations",
     "What is the default axis for statistical functions like df.mean(), df.sum(), and df.max() in Pandas?",
     "axis=0 (or 'index'), computing statistics down each column across rows",
     ["axis=1 (or 'columns'), computing across columns for each row", "axis=None, computing across the whole table into a single scalar", "No default axis; an error is raised if omitted"],
     "By default, aggregation methods in Pandas operate along axis=0 (index), yielding column-wise summary values."),
    ("stmt", "Row-wise Aggregations and describe() Output",
     "df.mean(axis=1) computes the arithmetic average across columns for each individual row.",
     "df.describe() computes summary statistics including count, mean, std, min, 25%, 50%, 75%, and max for numerical columns.", 1,
     "Both Statement I and Statement II are correct. axis=1 executes row-wise reductions, and describe() outputs the standard 8-statistic summary."),
    ("ar", "Mode Series Return Type",
     "Executing df['Score'].mode() returns a Pandas Series rather than a single scalar value.",
     "A distribution can be multimodal (possessing two or more distinct values occurring with equal maximum frequency).", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Because multiple modes can exist, mode() must return a Series."),
    ("match", "Statistical Functions and Mathematical Definitions",
     "Match the statistical method in List I with its definition in List II:",
     [("A", "df.median()"),
      ("B", "df.mean()"),
      ("C", "df.std()"),
      ("D", "df.var()")],
     [("I", "The 50th percentile / middle value separating lower and upper halves"),
      ("II", "The arithmetic mean (sum of valid elements divided by count)"),
      ("III", "Sample standard deviation (square root of sample variance, ddof=1)"),
      ("IV", "Sample variance (mean squared deviation from the mean)")],
     "A-I, B-II, C-III, D-IV",
     "median() is 50th percentile, mean() is arithmetic average, std() is sample standard deviation, and var() is sample variance."),
    ("seq", "Quartile and Extremity Metrics Ordering",
     "Arrange the statistical metrics produced by df['Marks'].describe() in strictly non-decreasing mathematical order:",
     [("A", "min (0th percentile minimum observation)"),
      ("B", "25% (First quartile Q1)"),
      ("C", "50% (Second quartile Q2 / Median)"),
      ("D", "75% (Third quartile Q3)")],
     "A, B, C, D",
     "By mathematical definition of percentiles: min <= 25% (Q1) <= 50% (Median) <= 75% (Q3). Order: A, B, C, D.")
]

s35_extras = [
    ("Min and Max Computations", "Which methods calculate the smallest and largest values in column 'Price' of DataFrame df?",
     "df['Price'].min() and df['Price'].max()",
     ["df['Price'].lowest() and df['Price'].highest()", "df['Price'].bottom() and df['Price'].top()", "df['Price'].small() and df['Price'].large()"],
     "min() and max() calculate the minimum and maximum non-null values in a Series or DataFrame."),
    ("Disabling skipna in Aggregations", "What occurs when df.sum(skipna=False) is invoked on a column containing one or more NaN entries?",
     "The calculation evaluates to NaN because missing values are not skipped",
     ["Missing values are treated as 0", "An exception is raised", "Missing values are replaced by the mean"],
     "Setting skipna=False forces arithmetic propagation of NaNs, causing the overall result to be NaN."),
    ("count() vs len() Distinction", "How does df['Age'].count() differ fundamentally from len(df['Age'])?",
     "df['Age'].count() counts only non-null values, whereas len(df['Age']) counts all rows including NaNs",
     ["df['Age'].count() counts unique values only", "len() counts only positive numbers", "They are exact duplicates with identical behavior"],
     "count() tallies non-null observations; len() returns the total length of the index axis."),
    ("Arbitrary Quantile Computation", "Which method computes the 75th percentile (third quartile) of column 'Age'?",
     "df['Age'].quantile(0.75)",
     ["df['Age'].percentile(75)", "df['Age'].quartile(3)", "df['Age'].q(0.75)"],
     "Series.quantile(q) computes the q-th quantile, where 0 <= q <= 1."),
    ("Describing Categorical Features", "How can you instruct df.describe() to generate summary metrics (unique, top, freq) for non-numeric columns?",
     "df.describe(include='all') or df.describe(include=['O'])",
     ["df.describe(categorical=True)", "df.describe(strings=True)", "df.describe_all()"],
     "include='all' instructs describe() to include categorical columns, computing count, unique, top, and freq."),
    ("Degrees of Freedom in Pandas std()", "What is the default value of ddof (delta degrees of freedom) used by Pandas in df.std()?",
     "ddof=1 (sample standard deviation, dividing by N-1)",
     ["ddof=0 (population standard deviation, dividing by N)", "ddof=2", "ddof=N"],
     "Unlike NumPy (which defaults to ddof=0), Pandas defaults to ddof=1 to compute unbiased sample standard deviation."),
    ("Frequency Table via value_counts", "What does df['Grade'].value_counts() return?",
     "A Series containing counts of unique values sorted in descending order of frequency",
     ["A single integer indicating total distinct grades", "A histogram plot of grades", "A list of unique grade names without counts"],
     "value_counts() produces a frequency distribution Series indexed by unique values."),
    ("Cumulative Sum Computation", "Which method computes the running cumulative sum down each column in DataFrame df?",
     "df.cumsum()",
     ["df.running_sum()", "df.accumulate()", "df.cum_total()"],
     "cumsum() returns cumulative sums over the requested axis (default axis=0)."),
    ("Row-wise Sum Computation", "What is produced by executing df.sum(axis=1) on a DataFrame with 4 rows and 3 columns?",
     "A Series of length 4 containing the horizontal sum of elements for each row",
     ["A Series of length 3 containing column sums", "A single scalar representing the grand total", "A 4x3 DataFrame of normalized sums"],
     "axis=1 computes sums across columns for each row, returning a Series whose index matches df.index."),
    ("Index Label of Maximum Value", "Which method returns the row index label where the maximum value in column 'Score' occurs?",
     "df['Score'].idxmax()",
     ["df['Score'].argmax()", "df['Score'].max_index()", "df['Score'].find_max()"],
     "idxmax() returns the index label of the first occurrence of the maximum value."),
    ("Index Label of Minimum Value", "Which method returns the row index label where the minimum value in column 'Score' occurs?",
     "df['Score'].idxmin()",
     ["df['Score'].argmin()", "df['Score'].min_index()", "df['Score'].find_min()"],
     "idxmin() returns the index label of the first occurrence of the minimum value."),
    ("Interquartile Range Calculation", "How is the Interquartile Range (IQR) calculated from Pandas quantile evaluations?",
     "df['Col'].quantile(0.75) - df['Col'].quantile(0.25)",
     ["df['Col'].quantile(0.50) - df['Col'].quantile(0.25)", "df['Col'].max() - df['Col'].min()", "df['Col'].std() / 2"],
     "IQR is defined mathematically as Q3 - Q1 (75th percentile minus 25th percentile)."),
    ("Correlation Matrix Method", "Which method computes pairwise Pearson correlation coefficients between all numerical columns in DataFrame df?",
     "df.corr()",
     ["df.correlate()", "df.pearson()", "df.covariance_matrix()"],
     "df.corr() calculates the pairwise correlation matrix for numerical columns."),
    ("Single Mode Evaluation Trace", "For a Series containing [2, 4, 4, 4, 6], what does series.mode()[0] return?",
     "4",
     ["3", "2", "6"],
     "4 occurs three times (most frequent); hence 4 is the mode."),
    ("Column Product Calculation", "Which function computes the cumulative product of all non-null values in column 'Factors'?",
     "df['Factors'].prod()",
     ["df['Factors'].multiply()", "df['Factors'].product_all()", "df['Factors'].total_product()"],
     "prod() or product() calculates the product of values along the specified axis.")
]

# ==============================================================================
# Slot 36: Data Visualization using Pyplot (Line Plots)
# ==============================================================================
s36_raw = [
    ("mcq", "Foundational Line Plot Function",
     "Which function in matplotlib.pyplot is standardly used to construct a two-dimensional line plot?",
     "plt.plot(x, y)",
     ["plt.line(x, y)", "plt.draw_line(x, y)", "plt.graph(x, y)"],
     "matplotlib.pyplot.plot() is the primary function for rendering 2D line plots."),
    ("stmt", "Axis Labeling and Plot Titles",
     "plt.xlabel('Time (s)') configures the text label displayed along the horizontal X-axis.",
     "plt.title('Velocity vs Time') specifies the heading title displayed prominently above the plot area.", 1,
     "Both Statement I and Statement II are correct. xlabel() annotates the X-axis, and title() renders the chart header."),
    ("ar", "Line Plot Styling Arguments",
     "Invoking plt.plot(x, y, color='red', linestyle='--', marker='o') renders a red dashed line with circular marker points.",
     "Pyplot provides explicit keyword arguments including color, linestyle, and marker to customize visual rendering of line graphs.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Keyword arguments color, linestyle, and marker customize line aesthetics."),
    ("match", "Line Plot Styling Parameters",
     "Match the styling parameter in List I with its rendering effect in List II:",
     [("A", "linestyle=':'"),
      ("B", "linestyle='--'"),
      ("C", "marker='^'"),
      ("D", "linewidth=3")],
     [("I", "Renders a dotted line style"),
      ("II", "Renders a dashed line style"),
      ("III", "Renders triangle-up markers at data points"),
      ("IV", "Sets the thickness of the line to 3 points")],
     "A-I, B-II, C-III, D-IV",
     "':' is dotted, '--' is dashed, '^' is triangle-up marker, and linewidth sets line thickness in points."),
    ("seq", "Constructing and Displaying a Line Plot",
     "Arrange the correct sequence of Pyplot instructions to produce a complete annotated line chart:",
     [("A", "Import module: import matplotlib.pyplot as plt"),
      ("B", "Plot data series: plt.plot(x, y, label='Temperature')"),
      ("C", "Add annotations: plt.xlabel('Hours'); plt.ylabel('Celsius'); plt.title('Day Trends'); plt.grid(True)"),
      ("D", "Render visual canvas: plt.show()")],
     "A, B, C, D",
     "Sequence: import library (A) -> call plot() (B) -> set labels/title/grid (C) -> invoke show() (D).")
]

s36_extras = [
    ("Enabling Canvas Grid Lines", "Which Pyplot command displays background grid lines across both X and Y axes?",
     "plt.grid(True)",
     ["plt.show_grid()", "plt.background_grid()", "plt.enable_mesh()"],
     "plt.grid(True) overlays grid lines on the active plot axes."),
    ("Shorthand Formatting String", "In plt.plot(x, y, 'r*--'), what line styling is generated by the format string 'r*--'?",
     "Red color, star marker, and dashed line style",
     ["Red color, round marker, solid line", "Green color, triangle marker, dotted line", "Blue color, square marker, dash-dot line"],
     "In Pyplot format strings: 'r' = red, '*' = star marker, and '--' = dashed line style."),
    ("Displaying Plot Legend", "Which command displays the legend identifying plotted series that have label parameters defined?",
     "plt.legend()",
     ["plt.show_labels()", "plt.draw_legend()", "plt.key()"],
     "plt.legend() places a legend box on the plot associating labels with their visual styles."),
    ("Marker Size Parameter", "Which keyword parameter adjusts the physical size of markers in plt.plot()?",
     "markersize (or ms)",
     ["markerwidth", "point_size", "radius"],
     "markersize (shorthand ms) specifies marker size in points."),
    ("Marker Face Color Parameter", "Which keyword parameter controls the fill color inside data point markers in plt.plot()?",
     "markerfacecolor (or mfc)",
     ["markerfill", "fill_color", "pointcolor"],
     "markerfacecolor (shorthand mfc) specifies the interior color of markers."),
    ("Marker Edge Color Parameter", "Which keyword parameter controls the border outline color of data point markers in plt.plot()?",
     "markeredgecolor (or mec)",
     ["marker_border", "edge_color", "outline_color"],
     "markeredgecolor (shorthand mec) specifies the boundary color of markers."),
    ("Restricting X-axis Range", "How do you explicitly constrain the visible range of the horizontal X-axis between 0 and 50?",
     "plt.xlim(0, 50)",
     ["plt.xrange(0, 50)", "plt.set_x(0, 50)", "plt.axis_x(0, 50)"],
     "plt.xlim(min, max) configures the minimum and maximum display limits of the X-axis."),
    ("Restricting Y-axis Range", "How do you explicitly constrain the visible range of the vertical Y-axis between 100 and 1000?",
     "plt.ylim(100, 1000)",
     ["plt.yrange(100, 1000)", "plt.set_y(100, 1000)", "plt.axis_y(100, 1000)"],
     "plt.ylim(min, max) configures the display limits of the Y-axis."),
    ("plt.show() Functional Role", "What is the primary function of plt.show() in a Python visualization script?",
     "Renders the active figure window on screen and blocks execution until closed",
     ["Saves the figure as a PNG file to the working directory", "Clears all plotted data from memory", "Exports data coordinates to a CSV file"],
     "plt.show() displays all active figure windows and starts the GUI event loop."),
    ("Multiple Lines on Single Axes", "How are multiple independent lines plotted on the same coordinate axes in Pyplot?",
     "By invoking plt.plot() multiple times before calling plt.show()",
     ["By passing a 3D tensor to a single plt.plot()", "Multiple lines cannot be plotted on the same chart", "By importing multiple pyplot modules"],
     "Successive calls to plt.plot() add additional line plots to the currently active axes."),
    ("Line Transparency Parameter", "Which parameter adjusts the opacity/transparency of plotted lines (ranging from 0.0 to 1.0)?",
     "alpha",
     ["opacity", "transparency", "tint"],
     "alpha accepts a float between 0.0 (completely transparent) and 1.0 (completely opaque)."),
    ("Continuous Solid Line Style", "What string denotes a standard continuous solid line style in plt.plot()?",
     "'-' or 'solid'",
     ["'--'", "':'", "'-.'"],
     "The hyphen '-' represents a continuous solid line in Matplotlib."),
    ("Clearing Active Figure", "Which Pyplot function clears the current figure without closing the window canvas?",
     "plt.clf()",
     ["plt.clear_all()", "plt.reset()", "plt.erase()"],
     "plt.clf() clears the current figure (Clear Figure)."),
    ("Clearing Active Axes", "Which Pyplot function clears the current axes while preserving the figure container?",
     "plt.cla()",
     ["plt.wipe()", "plt.clean()", "plt.blank()"],
     "plt.cla() clears the current active axes (Clear Axes)."),
    ("Customizing Axis Tick Labels", "Which function configures the exact numeric positions and custom string labels along the X-axis?",
     "plt.xticks(ticks, labels)",
     ["plt.xmarks(ticks, labels)", "plt.axis_ticks_x(ticks, labels)", "plt.set_ticks(ticks, labels)"],
     "plt.xticks() sets the location ticks and string labels of the X-axis.")
]

# ==============================================================================
# Slot 37: Data Visualization using Pyplot (Bar Charts)
# ==============================================================================
s37_raw = [
    ("mcq", "Vertical vs Horizontal Bar Charts",
     "What is the operational distinction between plt.bar() and plt.barh() in Matplotlib Pyplot?",
     "plt.bar() renders vertical column charts, whereas plt.barh() renders horizontal bar charts",
     ["plt.bar() is for numeric data and plt.barh() is for string data", "plt.bar() plots histograms while plt.barh() plots bar charts", "plt.barh() is deprecated"],
     "plt.bar() renders vertical bars (categories along X-axis); plt.barh() renders horizontal bars (categories along Y-axis)."),
    ("stmt", "Grouped Bars and Width Adjustments",
     "To plot multiple comparative bars side-by-side on categorical axes, the x-coordinates of series must be offset by the bar width.",
     "The width parameter in plt.bar() controls the horizontal thickness of individual vertical bars.", 1,
     "Both Statement I and Statement II are correct. Shifting x coordinates by bar width prevents overlap, and width specifies bar thickness."),
    ("ar", "Per-bar Color Customization",
     "Supplying a list of colors color=['gold', 'silver', 'brown'] in plt.bar() assigns distinct colors to consecutive bars.",
     "The color parameter in Pyplot bar functions accepts an iterable sequence of color names or hex codes corresponding to each bar.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Passing a list of colors applies them cyclically/sequentially across bars."),
    ("match", "Bar Chart Parameters and Roles",
     "Match the bar chart parameter in List I with its functionality in List II:",
     [("A", "width=0.4"),
      ("B", "height=0.5"),
      ("C", "edgecolor='black'"),
      ("D", "bottom=series1")],
     [("I", "Sets horizontal bar thickness in vertical bar charts plt.bar()"),
      ("II", "Sets vertical bar thickness in horizontal bar charts plt.barh()"),
      ("III", "Configures the outline border color surrounding each bar"),
      ("IV", "Sets vertical offset baseline to create stacked vertical bar charts")],
     "A-I, B-II, C-III, D-IV",
     "width sets vertical bar width, height sets horizontal bar thickness, edgecolor sets border stroke, and bottom stacks bars vertically."),
    ("seq", "Constructing Side-by-Side Comparative Bar Charts",
     "Arrange the sequential steps to produce a side-by-side grouped comparative bar chart for two datasets:",
     [("A", "Calculate numerical x-coordinates using np.arange(len(categories)) and define bar width w"),
      ("B", "Plot first dataset at offset coordinates: plt.bar(x - w/2, data1, width=w, label='2023')"),
      ("C", "Plot second dataset at offset coordinates: plt.bar(x + w/2, data2, width=w, label='2024')"),
      ("D", "Assign category labels using plt.xticks(x, categories) and display legend via plt.legend()")],
     "A, B, C, D",
     "Sequence: setup x-coords and width (A) -> plot shifted series 1 (B) -> plot shifted series 2 (C) -> set xticks and legend (D).")
]

s37_extras = [
    ("Default Vertical Bar Width", "What is the standard default width of vertical bars in plt.bar() if unspecified?",
     "0.8",
     ["1.0", "0.5", "0.2"],
     "The default width for bars in matplotlib.pyplot.bar is 0.8."),
    ("Horizontal Bar Thickness Parameter", "In plt.barh(), which parameter specifies the bar thickness along the vertical axis?",
     "height",
     ["width", "thickness", "bar_size"],
     "In horizontal bar charts (plt.barh), the bar thickness is specified using the height parameter."),
    ("Creating Stacked Vertical Bar Charts", "How is a stacked bar chart constructed where series2 rests on top of series1?",
     "plt.bar(x, series2, bottom=series1)",
     ["plt.bar(x, series2, stack=series1)", "plt.bar(x, series2, top_of=series1)", "plt.bar(x, series2 + series1)"],
     "The bottom parameter provides the baseline y-coordinates, stacking series2 directly on top of series1."),
    ("Legend Placement Parameter", "Which parameter in plt.legend() explicitly defines the anchor position of the legend box?",
     "loc='upper right' (or other cardinal position strings)",
     ["position='top'", "anchor='upper right'", "align='right'"],
     "The loc parameter controls legend placement (e.g., 'upper right', 'lower left', 'center')."),
    ("Bar Alignment Parameter", "What is the default alignment of bars relative to their categorical coordinate ticks in plt.bar()?",
     "align='center'",
     ["align='edge'", "align='left'", "align='right'"],
     "Bars are centered on the tick coordinates by default (align='center')."),
    ("Y-axis Ticks for Horizontal Bars", "Which function formats categorical string labels along the vertical axis for horizontal bar charts?",
     "plt.yticks(positions, labels)",
     ["plt.xticks(positions, labels)", "plt.y_labels(labels)", "plt.set_y_categories(labels)"],
     "plt.yticks() sets the locations and labels of tick marks on the vertical Y-axis."),
    ("Overlapping Bars Without Offsets", "What visual outcome occurs if two calls to plt.bar() use identical x-coordinates without shifting or stacking?",
     "The second series of bars is drawn directly over the first series, obscuring the underlying bars",
     ["Matplotlib automatically creates a 3D side-by-side plot", "An OverlapException is thrown", "The bars automatically average together"],
     "Without adjusting x-coordinates or setting bottom, bars render directly on top of each other, hiding the earlier series."),
    ("Pandas Built-in Bar Plotting", "Which method directly generates a bar plot from a Pandas DataFrame df?",
     "df.plot(kind='bar') or df.plot.bar()",
     ["df.to_bar()", "df.bar_chart()", "df.render_bar()"],
     "Pandas provides built-in plotting accessors df.plot(kind='bar') wrapping Matplotlib."),
    ("Horizontal Reference Line", "Which Pyplot function draws an unbroken horizontal reference line across the plotting area at y=50?",
     "plt.axhline(y=50, color='gray', linestyle='--')",
     ["plt.hline(50)", "plt.draw_horizontal(50)", "plt.ref_y(50)"],
     "plt.axhline() adds a horizontal line across the entire axes."),
    ("Vertical Reference Line", "Which Pyplot function draws an unbroken vertical reference line across the plotting area at x=10?",
     "plt.axvline(x=10, color='red')",
     ["plt.vline(10)", "plt.draw_vertical(10)", "plt.ref_x(10)"],
     "plt.axvline() adds a vertical line across the entire axes."),
    ("Error Bar Parameter on Bars", "Which parameter in plt.bar() renders vertical error bars representing measurement uncertainty?",
     "yerr=errors",
     ["error_bars=errors", "err=errors", "uncertainty=errors"],
     "yerr draws error bars representing deviation or confidence bounds on vertical bars."),
    ("Color Shorthand 'k'", "In Matplotlib color specifications, which color is designated by the single character 'k'?",
     "Black",
     ["Khaki", "Krypton Blue", "Kelly Green"],
     "In Matplotlib, 'k' stands for Black ('b' is used for Blue)."),
    ("Color Shorthand 'c'", "In Matplotlib color specifications, which color is designated by the single character 'c'?",
     "Cyan",
     ["Crimson", "Charcoal", "Cream"],
     "'c' represents Cyan in Matplotlib color abbreviations."),
    ("Color Shorthand 'm'", "In Matplotlib color specifications, which color is designated by the single character 'm'?",
     "Magenta",
     ["Maroon", "Mustard", "Mauve"],
     "'m' represents Magenta in Matplotlib color abbreviations."),
    ("Bar Hatching Patterns", "Which parameter adds crosshatching, slashes, or dots inside bars in plt.bar()?",
     "hatch='//'",
     ["pattern='//'", "texture='//'", "fill_pattern='//'"],
     "The hatch parameter applies patterns such as '/', '\', '|', '-', '+', 'x', 'o', 'O', '.', '*' inside bars.")
]

# ==============================================================================
# Slot 38: Pyplot Histograms & Plot Export (hist, savefig)
# ==============================================================================
s38_raw = [
    ("mcq", "Continuous Frequency Distribution Visualization",
     "Which Matplotlib Pyplot function groups continuous numerical data into contiguous intervals to display frequency distribution?",
     "plt.hist(data)",
     ["plt.bar(data)", "plt.freq(data)", "plt.distribution(data)"],
     "plt.hist() automatically groups continuous values into discrete interval bins to display distribution frequencies."),
    ("stmt", "Histogram Bins and rwidth Parameters",
     "In plt.hist(data, bins=10), the bins argument partitions the data range into 10 equal-width class intervals.",
     "The rwidth parameter specifies the relative width of the histogram bars as a fraction of the bin width (e.g. 0.8 leaves gaps).", 1,
     "Both Statement I and Statement II are correct. bins defines partition count, and rwidth controls bar width relative to bin space."),
    ("ar", "Plot Saving Order Execution",
     "Calling plt.savefig('chart.png') must be executed before plt.show() when exporting plots in standard Python scripts.",
     "plt.show() displays the canvas and may reset or clear the current figure in memory, causing subsequent savefig() calls to save a blank image.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Calling show() can flush the active figure buffer, leaving savefig() blank if called afterwards."),
    ("match", "Histogram Customization Parameters",
     "Match the histogram parameter in List I with its description in List II:",
     [("A", "cumulative=True"),
      ("B", "orientation='horizontal'"),
      ("C", "edgecolor='black'"),
      ("D", "density=True")],
     [("I", "Plots cumulative frequencies where each bin aggregates counts of prior bins"),
      ("II", "Generates horizontal histogram bins extending along the X-axis"),
      ("III", "Draws crisp borders around each bin bar for visual clarity"),
      ("IV", "Normalizes counts so the total area under the histogram integrates to 1")],
     "A-I, B-II, C-III, D-IV",
     "cumulative creates cumulative distributions, orientation flips axes, edgecolor outlines bars, and density computes probability density."),
    ("seq", "Histogram Construction and Disk Export",
     "Arrange the sequence of steps to generate a binned frequency histogram and export it to disk:",
     [("A", "Collect continuous numerical observations dataset"),
      ("B", "Specify custom bin intervals: bins = [0, 35, 50, 75, 100]"),
      ("C", "Generate histogram: plt.hist(dataset, bins=bins, edgecolor='black', rwidth=0.9)"),
      ("D", "Export to image file: plt.savefig('distribution.png', dpi=300); plt.show()")],
     "A, B, C, D",
     "Sequence: collect data (A) -> specify bin boundaries (B) -> plot histogram (C) -> export with savefig and call show (D).")
]

s38_extras = [
    ("Default Histogram Bin Count", "What is the default number of equal-width bins created by plt.hist() when bins is not specified?",
     "10 bins",
     ["5 bins", "20 bins", "50 bins"],
     "By default, plt.hist() divides the range of data into 10 equal-width bins."),
    ("Explicit Non-equal Bin Edges", "Can bins in plt.hist() be passed as an explicit list of edge boundaries such as [0, 20, 50, 100]?",
     "Yes, passing a list defines exact bin edge thresholds allowing variable-width intervals",
     ["No, all bins in Matplotlib must strictly be equal in width", "No, bins only accepts a single integer", "Only if density=False"],
     "Passing a sequence of numbers to bins specifies the exact left and right boundaries for each bin."),
    ("High Resolution Image Export", "Which parameter in plt.savefig() specifies the image resolution in dots per inch?",
     "dpi=300 (or other numeric value)",
     ["resolution=300", "pixels=300", "quality=300"],
     "dpi (Dots Per Inch) controls the output raster image resolution in savefig()."),
    ("Tight Bounding Box on Export", "Which parameter in plt.savefig() eliminates unnecessary white space padding around the exported figure?",
     "bbox_inches='tight'",
     ["crop=True", "pad=0", "autotrim=True"],
     "bbox_inches='tight' trims excess margin whitespace when saving figures."),
    ("plt.hist() Return Values", "What three objects are returned by the function call n, bins, patches = plt.hist(data)?",
     "n (array of bin counts), bins (array of bin edge points), patches (list of graphical BarContainer objects)",
     ["x, y, and z coordinates", "mean, median, and mode", "figure, axes, and canvas"],
     "plt.hist() returns the frequency counts (n), the bin boundary values (bins), and the graphical container patches."),
    ("Bar Chart vs Histogram Difference", "What is the conceptual difference between a bar chart and a histogram?",
     "Bar charts represent discrete categorical data with separated bars; histograms represent continuous numerical distributions partitioned into intervals",
     ["Bar charts are horizontal and histograms are vertical", "Bar charts use color while histograms are black and white", "Histograms are for time series only"],
     "Bar charts visualize discrete categories; histograms visualize the continuous distribution of numerical variables."),
    ("Unfilled Outline Histogram", "Which parameter setting renders an unfilled outline-only polygon histogram without filled color bars?",
     "histtype='step'",
     ["histtype='outline'", "outline=True", "fill=False"],
     "histtype='step' generates a line plot that is empty inside, useful for comparing multiple distributions."),
    ("Step-filled Histogram Style", "Which parameter generates a stepped line plot that is filled with solid color underneath?",
     "histtype='stepfilled'",
     ["histtype='fill_step'", "step_fill=True", "polygon=True"],
     "histtype='stepfilled' renders a stepped baseline that is filled."),
    ("Standard Supported Export Formats", "Which collection of image formats is universally supported by plt.savefig()?",
     "PNG, PDF, SVG, EPS, and JPG",
     ["EXE, DLL, and BAT", "DOCX, PPTX, and XLSX", "MP4, AVI, and MKV"],
     "Matplotlib exports to standard raster (PNG, JPG) and vector (PDF, SVG, EPS) graphic formats."),
    ("Transparent Figure Export", "Which parameter in plt.savefig() produces an image with a transparent canvas background?",
     "transparent=True",
     ["alpha=0", "no_bg=True", "clear_canvas=True"],
     "Setting transparent=True saves the figure with an alpha transparent background."),
    ("Overlapping Histograms Visibility", "How do you ensure that two overlapping histograms plotted on the same axes are mutually visible?",
     "Set alpha=0.5 (transparency) on both plt.hist() calls",
     ["Set color='clear'", "Use two different screens", "Set transparent=False"],
     "Using semi-transparency (alpha between 0.3 and 0.6) allows overlapping histogram distributions to remain clearly legible."),
    ("Range Outlier Exclusion", "Which parameter in plt.hist() restricts binning to values between a minimum and maximum threshold, ignoring outliers?",
     "range=(min_val, max_val)",
     ["limits=(min_val, max_val)", "clip=(min_val, max_val)", "bounds=(min_val, max_val)"],
     "The range parameter defines the lower and upper binning boundaries; values outside are omitted."),
    ("Figure Size Initialization", "Which command initializes a figure canvas with explicit width and height dimensions of 10 and 6 inches?",
     "plt.figure(figsize=(10, 6))",
     ["plt.set_size(10, 6)", "plt.canvas(10, 6)", "plt.dimensions(10, 6)"],
     "plt.figure(figsize=(width, height)) initializes figure canvas dimensions in inches."),
    ("Horizontal Histogram Orientation", "Which parameter in plt.hist() causes the histogram bins to extend horizontally along the X-axis?",
     "orientation='horizontal'",
     ["direction='horizontal'", "axis='x'", "horizontal=True"],
     "orientation='horizontal' generates horizontal histogram bins where frequencies lie on the X-axis."),
    ("Canvas Dots Per Inch Setup", "Which parameter in plt.figure() sets the rendering DPI resolution for on-screen display?",
     "dpi=100",
     ["resolution=100", "ppi=100", "screen_res=100"],
     "plt.figure(dpi=val) controls display canvas resolution.")
]

# ==============================================================================
# Slot 39: Database Concepts, SQL Functions and Queries
# ==============================================================================
s39_raw = [
    ("mcq", "MySQL MOD() Remainder Function",
     "What is the evaluated output of the SQL query: SELECT MOD(17, 5);?",
     "2",
     ["3", "3.4", "1"],
     "MOD(N, M) returns the remainder of N divided by M: 17 = 5 * 3 + 2, remainder is 2."),
    ("stmt", "SQL Math Functions: POWER and ROUND",
     "In MySQL, POWER(2, 3) and POW(2, 3) evaluate to 8.",
     "ROUND(15.768, 2) rounds the numerical argument to two decimal places, returning 15.77.", 1,
     "Both Statement I and Statement II are correct. POWER/POW computes exponents, and ROUND rounds to specified decimal places."),
    ("ar", "SQL String Length Evaluation",
     "The SQL query SELECT LENGTH('CUET Exam'); returns 9.",
     "The LENGTH() function in MySQL calculates the length of a string in bytes/characters, counting spaces as characters.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). 'CUET' (4) + ' ' (1) + 'Exam' (4) = 9 characters."),
    ("match", "SQL String Functions and Outputs",
     "Match the SQL string function on 'Computer' in List I with its evaluated output in List II:",
     [("A", "SUBSTR('Computer', 1, 4)"),
      ("B", "UPPER('Computer')"),
      ("C", "INSTR('Computer', 'put')"),
      ("D", "RIGHT('Computer', 3)")],
     [("I", "'Comp'"),
      ("II", "'COMPUTER'"),
      ("III", "4 (1-based index position)"),
      ("IV", "'ter'")],
     "A-I, B-II, C-III, D-IV",
     "SUBSTR extracts substring from pos 1 for len 4 ('Comp'), UPPER converts to uppercase, INSTR finds 1-based position (4), and RIGHT extracts last 3 chars ('ter')."),
    ("seq", "Ascending Evaluation of SQL Function Results",
     "Arrange the evaluated scalar outputs of these SQL queries in increasing numerical order:",
     [("A", "SELECT MOD(11, 4); (Result: 3)"),
      ("B", "SELECT ROUND(3.64, 0); (Result: 4)"),
      ("C", "SELECT POWER(2, 3); (Result: 8)"),
      ("D", "SELECT LENGTH('Informatics'); (Result: 11)")],
     "A, B, C, D",
     "Evaluations: MOD(11, 4) = 3; ROUND(3.64, 0) = 4; POWER(2, 3) = 8; LENGTH('Informatics') = 11. Ascending order: A (3), B (4), C (8), D (11).")
]

s39_extras = [
    ("Negative Precision in ROUND()", "What is the evaluated output of the MySQL query: SELECT ROUND(128.456, -1);?",
     "130",
     ["120", "128.5", "128"],
     "Negative decimal places in ROUND() round to powers of 10: -1 rounds to nearest tens, so 128 becomes 130."),
    ("SQL TRIM() Function", "What does SELECT TRIM('   Data Science   '); return in MySQL?",
     "'Data Science' (leading and trailing whitespace removed)",
     ["'DataScience' (all spaces removed)", "'   Data Science'", "'Data Science   '"],
     "TRIM() removes both leading and trailing whitespace while preserving inner whitespace between words."),
    ("SQL LTRIM() Function", "What does SELECT LTRIM('   Python'); return?",
     "'Python' (leading spaces removed)",
     ["'   Python'", "'Python   '", "''"],
     "LTRIM() removes leading whitespace characters from the beginning of a string."),
    ("SQL RTRIM() Function", "What does SELECT RTRIM('Database   '); return?",
     "'Database' (trailing spaces removed)",
     ["'   Database'", "'Database   '", "NULL"],
     "RTRIM() removes trailing whitespace characters from the end of a string."),
    ("String Concatenation in MySQL", "What is the result of SELECT CONCAT('Class', ' ', '12'); in MySQL?",
     "'Class 12'",
     ["'Class12'", "NULL", "Error"],
     "CONCAT() joins two or more string arguments together into a single combined string."),
    ("SQL MID() Function", "What is the output of SELECT MID('Informatics', 3, 4); in MySQL?",
     "'form'",
     ["'Info'", "'nfor'", "'rmat'"],
     "MID(str, pos, len) is a synonym for SUBSTR; starting at 1-based index 3 ('f') for length 4 extracts 'form'."),
    ("MySQL NOW() Function", "What does the MySQL function NOW() return?",
     "The current date and time in 'YYYY-MM-DD HH:MM:SS' format",
     ["Only the current time", "Only the current date", "Current year only"],
     "NOW() returns the current date and time as a timestamp value in 'YYYY-MM-DD HH:MM:SS' format."),
    ("MySQL CURDATE() Function", "What does SELECT CURDATE(); return?",
     "The current system date in 'YYYY-MM-DD' format",
     ["Current date and time", "Current time only", "Day of the week"],
     "CURDATE() (or CURRENT_DATE()) returns the current system date without the time component."),
    ("SQL YEAR() Extraction", "What is the evaluated output of SELECT YEAR('2026-06-15');?",
     "2026",
     ["6", "15", "20"],
     "YEAR() extracts the 4-digit year component from a valid date or datetime expression."),
    ("SQL MONTHNAME() Function", "What does SELECT MONTHNAME('2026-05-18'); return in MySQL?",
     "'May'",
     ["5", "'05'", "'Spring'"],
     "MONTHNAME() returns the full English name of the month for the given date argument."),
    ("SQL DAYNAME() Function", "What does the SQL function DAYNAME(date) return?",
     "The full English weekday name corresponding to the date (e.g., 'Monday', 'Sunday')",
     ["The day number (1-31)", "The day of the year (1-365)", "The month name"],
     "DAYNAME() returns the weekday name corresponding to the specified date."),
    ("SQL DAYOFMONTH() Function", "What is the evaluated result of SELECT DAYOFMONTH('2026-08-25');?",
     "25",
     ["8", "2026", "2"],
     "DAYOFMONTH() returns the day of the month as an integer between 1 and 31."),
    ("CONCAT with NULL Behavior", "What is the result of SELECT CONCAT('Hello', NULL, 'World'); in MySQL?",
     "NULL (concatenating any string with NULL yields NULL in standard MySQL)",
     ["'HelloWorld'", "'HelloNULLWorld'", "''"],
     "In MySQL, CONCAT() returns NULL if any argument is NULL (unlike CONCAT_WS)."),
    ("SQL UCASE and LCASE", "Which functions in MySQL serve as synonyms for UPPER() and LOWER() respectively?",
     "UCASE() and LCASE()",
     ["UP() and DOWN()", "TO_UPPER() and TO_LOWER()", "CAPITAL() and SMALL()"],
     "UCASE() is an exact synonym for UPPER(), and LCASE() is an exact synonym for LOWER()."),
    ("SQL INSTR() Search Function", "What is returned by SELECT INSTR('Informatics', 'mat');?",
     "6 (1-based character position where substring begins)",
     ["5", "3", "True"],
     "INSTR(str, substr) returns the 1-based index position of the first occurrence of substr in str ('I'-1, 'n'-2, 'f'-3, 'o'-4, 'r'-5, 'm'-6).")
]

# ==============================================================================
# Slot 40: Societal Impacts, Cyber Ethics, Data Protection & E-waste
# ==============================================================================
s40_raw = [
    ("mcq", "Active vs Passive Digital Footprints",
     "What is the fundamental distinction between an Active Digital Footprint and a Passive Digital Footprint?",
     "Active footprints are deliberately created by users (e.g., social media posts), whereas passive footprints are collected covertly without explicit active sharing (e.g., IP server logs, browsing cookies)",
     ["Active footprints are always legal while passive footprints are always criminal", "Active footprints are stored on phones and passive footprints on desktop computers", "Active footprints disappear after 24 hours while passive footprints endure forever"],
     "Active digital footprints result from deliberate user actions; passive footprints are recorded invisibly by web servers and trackers."),
    ("stmt", "Digital Divide and Netiquette Concepts",
     "The Digital Divide refers to socioeconomic and geographic inequality in access to information and communications technology.",
     "Netiquette refers to informal codes of ethical, polite, and respectful communication conduct in online digital interactions.", 1,
     "Both Statement I and Statement II are correct. Digital divide describes ICT access disparity, and netiquette encompasses online behavioral norms."),
    ("ar", "E-waste Environmental Hazards",
     "Improper disposal of electronic waste (e-waste) in unlined municipal landfills causes severe environmental contamination.",
     "Discarded electronic components contain hazardous toxic heavy metals such as lead, mercury, cadmium, and brominated flame retardants that leach into groundwater.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Toxic heavy metals in e-waste infiltrate water tables and soil if discarded unscientifically."),
    ("match", "Cyber Crimes and Unethical Digital Behaviors",
     "Match the cyber offense in List I with its description in List II:",
     [("A", "Phishing"),
      ("B", "Cyberbullying"),
      ("C", "Identity Theft"),
      ("D", "Plagiarism")],
     [("I", "Fraudulent communications masquerading as trustworthy institutions to steal credentials"),
      ("II", "Harassing, humiliating, or intimidating individuals using digital communication channels"),
      ("III", "Unauthorized acquisition and misuse of someone's personal identity data for fraud"),
      ("IV", "Presenting someone else's work, creative ideas, or code as one's own without attribution")],
     "A-I, B-II, C-III, D-IV",
     "Phishing steals credentials via spoofing, cyberbullying is online harassment, identity theft is credential impersonation, and plagiarism is unattributed copying."),
    ("seq", "Protocol for Institutional Electronic Hardware Disposal",
     "Arrange the correct sequence of steps to retire and safely dispose of computing hardware:",
     [("A", "Back up critical institutional data to verified secure secondary storage"),
      ("B", "Perform cryptographic wiping / sanitization of internal storage drives"),
      ("C", "Dismantle hardware to separate hazardous components from recyclable plastics and metals"),
      ("D", "Transfer hazardous residues to government-certified, authorized e-waste recycling facilities")],
     "A, B, C, D",
     "Sequence: data backup (A) -> secure sanitization (B) -> hardware dismantling (C) -> authorized e-waste transfer (D).")
]

s40_extras = [
    ("Indian IT Act 2000", "Which landmark Indian legislation provides legal recognition for electronic transactions, digital signatures, and penalizes cyber offenses?",
     "Information Technology Act, 2000 (IT Act 2000)",
     ["Cyber Safety Act 1995", "Indian Penal Code 1860 only", "Electronic Commerce Regulation Act 2010"],
     "The Information Technology Act, 2000 is India's primary legislation governing cyber crimes and electronic commerce."),
    ("Hacking Penalties under IT Act", "Which section of the Indian IT Act 2000 specifically penalizes computer system hacking, unauthorized access, and tampering?",
     "Section 66 (along with Section 43)",
     ["Section 10", "Section 100", "Section 2"],
     "Section 66 of the IT Act 2000 covers hacking and fraudulent computing offenses with imprisonment and fines."),
    ("Cyberstalking Definition", "What is Cyberstalking?",
     "Repeated, persistent use of the internet or electronic communications to obsessively track, harass, or threaten an individual",
     ["Downloading open source software", "Sending a single transactional email", "Creating a personal blog"],
     "Cyberstalking involves sustained, unwanted surveillance and harassment conducted across digital channels."),
    ("Ransomware Mechanism", "What is Ransomware?",
     "Malware that encrypts the victim's files or locks their operating system, demanding financial payment for the decryption key",
     ["Hardware that speeds up processing", "Antivirus program that deletes junk files", "A network routing protocol"],
     "Ransomware renders files inaccessible via strong cryptography and demands ransom for decryption."),
    ("Spyware Characteristics", "What is Spyware?",
     "Covert software installed on a device without user consent to track activity, monitor keystrokes, and extract private data",
     ["A tool used to clean dust from keyboards", "Software that optimizes internet bandwidth", "A compiler optimization flag"],
     "Spyware operates surreptitiously in the background, exfiltrating credentials and private activities."),
    ("Online Trolling", "What is 'Trolling' in online communities?",
     "Deliberately posting provocative, offensive, or irrelevant messages in online forums to provoke anger or disruption",
     ["Searching for academic research papers", "Playing competitive multiplayer games", "Setting up firewall filters"],
     "Trolling involves intentional online disruption aimed at inciting emotional discord and arguments."),
    ("Environmental Standards: EPEAT and ENERGY STAR", "What do EPEAT and ENERGY STAR certifications indicate on computer hardware?",
     "Compliance with rigorous energy efficiency, material recyclability, and environmental sustainability standards",
     ["Proof that the computer cannot be hacked", "Indication of maximum computing speed", "Compliance with gaming graphics benchmarks"],
     "ENERGY STAR and EPEAT signify high energy efficiency and environmentally sustainable hardware manufacturing."),
    ("Precious Metal Recovery from E-waste", "What valuable resources can be reclaimed through scientific e-waste recycling?",
     "Precious metals including gold, silver, copper, and platinum from circuit boards and contacts",
     ["Petroleum fuel", "Organic fertilizers", "Fresh drinking water"],
     "Printed circuit boards contain significant concentrations of precious metals (gold, silver, palladium, copper)."),
    ("Digital Signature Role", "What is the primary function of a Digital Signature?",
     "Authenticates the identity of the sender and guarantees the integrity and non-repudiation of the electronic message",
     ["Scans the document for spelling errors", "Compresses file size for faster email attachment", "Converts plain text into handwritten cursive font"],
     "Digital signatures provide cryptographic authentication, message integrity, and non-repudiation using public key cryptography."),
    ("Copyright Infringement", "What constitutes Copyright Infringement in software and digital content?",
     "Unauthorized copying, modification, distribution, or commercial piracy of protected creative works without the copyright owner's consent",
     ["Purchasing a legitimate single-user license", "Writing original code that performs a common mathematical operation", "Reading public documentation"],
     "Copyright infringement violates the exclusive statutory rights granted to the creator of an intellectual property."),
    ("Creative Commons Licensing", "What is the purpose of Creative Commons (CC) licenses?",
     "Provides standardized legal permissions enabling creators to grant the public permission to share and reuse their work under flexible conditions",
     ["Requires users to pay monthly royalties to governments", "Enforces secret proprietary copyright protection", "Prohibits all educational use of media"],
     "Creative Commons offers standardized public licenses (e.g. CC-BY, CC-SA) that grant flexible sharing permissions."),
    ("Data Privacy Rights", "What does the concept of 'Data Privacy' encompass in the information age?",
     "The right of individuals to exercise control over how their personal identifiable information is gathered, stored, and shared",
     ["The government's ownership of all citizen hard drives", "The prohibition of all cloud databases", "The requirement that all websites be password-free"],
     "Data privacy concerns the lawful, fair, and transparent handling of personal identifiable data (PII)."),
    ("HTTP Browser Cookies", "What is a browser cookie?",
     "A small text file sent by a web server and stored on the user's computer to retain session state, authentication, and browsing preferences",
     ["A piece of malicious firmware in the hard drive", "An executable virus file", "A hardware processor cache"],
     "Cookies are text files used by web applications to identify user sessions and personalize state across HTTP requests."),
    ("Spam Definition", "What is defined as 'Spam' in electronic communication?",
     "Unsolicited, bulk electronic messages sent indiscriminately to large recipient lists, often advertising products or phishing scams",
     ["Encrypted personal messages between friends", "Automated system update notifications", "Operating system error logs"],
     "Spam is unsolicited bulk messaging distributed without recipient consent."),
    ("Computer Ergonomics", "Why is ergonomics vital for regular computer users?",
     "Promotes proper posture, screen distance, and workstation setup to prevent repetitive strain injuries (RSI) and eye fatigue",
     ["Increases internet download speed", "Reduces CPU operating temperatures", "Prevents malware infections"],
     "Ergonomics adapts equipment and work environments to human biomechanics to prevent musculoskeletal injuries.")
]

# ==============================================================================
# Slots Compilation
# ==============================================================================
SLOT31 = build_slot(CH_DF_II, list(s31_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s31_extras])
SLOT32 = build_slot(CH_DF_II, list(s32_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s32_extras])
SLOT33 = build_slot(CH_DF_II, list(s33_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s33_extras])
SLOT34 = build_slot(CH_DF_II, list(s34_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s34_extras])
SLOT35 = build_slot(CH_DF_II, list(s35_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s35_extras])

SLOT36 = build_slot(CH_PYPLOT, list(s36_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s36_extras])
SLOT37 = build_slot(CH_PYPLOT, list(s37_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s37_extras])
SLOT38 = build_slot(CH_PYPLOT, list(s38_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s38_extras])

SLOT39 = build_slot(CH_SQL_II, list(s39_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s39_extras])
SLOT40 = build_slot(CH_SOCIETY, list(s40_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s40_extras])

SLOTS_31_40 = {
    31: SLOT31,
    32: SLOT32,
    33: SLOT33,
    34: SLOT34,
    35: SLOT35,
    36: SLOT36,
    37: SLOT37,
    38: SLOT38,
    39: SLOT39,
    40: SLOT40
}

print("CS Slots 31 to 40 compiled successfully.")
'''

with open(out_path, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Generated {out_path} ({len(content)} bytes)")
