import sys, os
sys.path.insert(0, os.getcwd())
from scripts.subject_generators.slot_helpers import mcq, stmt, ar, match, seq

CH_INST = "Social Institutions: Continuity and Change"
CH_MARKET = "The Market as a Social Institution"
CH_INEQ = "Patterns of Social Inequality and Exclusion"

slots = {}

# Slot 11: Adivasi Dispossession, Forest Acts & PESA (20 items)
s11 = [
    mcq(CH_INST, "Forest Rights Act 2006 Historical Redress",
        "The Forest Rights Act (FRA) 2006 was officially enacted to redress which historical injustice?",
        "The colonial and post-colonial non-recognition of customary land and forest rights of forest-dwelling communities",
        ["The loss of royal pension stipends to pre-colonial princely rulers",
         "The destruction of British naval docks in metropolitan coastal cities",
         "The lack of foreign private airline ownership among urban industrialists"],
        "The FRA 2006 explicitly recognizes pre-existing customary tenure rights of forest-dwelling STs and OTFDs."),
    stmt(CH_INST, "PESA 1996 Gram Sabha Powers",
        "Under the PESA Act 1996, the Gram Sabha in Scheduled Areas has the mandatory right to be consulted before land acquisition.",
        "Under PESA, state governments can dissolve Gram Sabhas and transfer tribal lands directly to mining corporations without local notice.", 3,
        "Statement I is correct as PESA mandates Gram Sabha consultation; Statement II is incorrect as Gram Sabha decisions cannot be bypassed."),
    ar(CH_INST, "Disproportionate Tribal Displacement",
        "Adivasis have borne a disproportionately high burden of displacement caused by dams, mines, and industrial projects in independent India.",
        "Over 40 percent of all persons displaced by post-independence development projects were tribal people, despite tribes constituting only 8 percent of the national population.", 1,
        "Both (A) and (R) are true, and (R) correctly explains (A). Natural resource geography placed projects overwhelmingly on tribal lands."),
    match(CH_INST, "Tribal Legislation and Year",
        "Match the tribal protective legislations in List I with their enactment years in List II:",
        [("A", "PESA Act"), ("B", "Forest Rights Act (FRA)"), ("C", "British Indian Forest Act"), ("D", "Fifth Schedule Enactment")],
        [("I", "1996"), ("II", "2006"), ("III", "1927"), ("IV", "1950")],
        "A-I, B-II, C-III, D-IV",
        "PESA was enacted in 1996, FRA in 2006, Indian Forest Act in 1927, and Fifth Schedule in the 1950 Constitution."),
    seq(CH_INST, "Chronology of Tribal Forest Encroachment Laws",
        "Arrange the historical milestones in Indian forest tenure legislation in chronological order:",
        [("A", "British colonial Forest Act classifying Reserved and Protected forests"),
         ("B", "Creation of the Fifth and Sixth Schedules in the Indian Constitution"),
         ("C", "Panchayats (Extension to Scheduled Areas) Act (PESA)"),
         ("D", "Scheduled Tribes and Other Traditional Forest Dwellers (FRA) Act")],
        "A, B, C, D",
        "Legislation progressed from 1927 colonial Forest Act to 1950 Constitution, 1996 PESA, and 2006 Forest Rights Act.")
]

s11_extras = [
    ("Minor Forest Produce Gathering Rights", "Which statutory right over Minor Forest Produce (MFP) did FRA 2006 confer on tribal communities?",
     "Right of ownership, access to collect, use, and dispose of minor forest produce customarily gathered within village boundaries",
     ["Obligation to surrender all forest herbs to private corporate pharmaceutical cartels without compensation", "Complete ban on entering forest lands during monsoon months", "Mandatory export of all collected tendu leaves to foreign governments exclusively"],
     "FRA 2006 vested ownership and marketing rights of minor forest produce directly in forest-dwelling communities."),
    ("Critical Wildlife Habitats vs Tribal Rights", "Under FRA 2006, relocation of forest dwellers from 'Critical Wildlife Habitats' (such as tiger reserves) can occur only after:",
     "The free, prior, and informed consent of the affected Gram Sabhas is obtained and a complete resettlement package is implemented",
     ["A unilateral midnight executive order issued by commercial timber logging firms", "A sudden police eviction carried out without any prior notification or compensation", "A decision voted on by tourists visiting foreign holiday destinations"],
     "FRA mandates that relocation from core habitats requires prior informed consent and verified resettlement."),
    ("Land Alienation via Moneylending", "In central Indian tribal districts, the primary socio-economic mechanism of land alienation was:",
     "Usurious debt traps where illiterate tribal peasants mortgaged ancestral land to non-tribal moneylenders and lost title",
     ["Compulsory state taxation on owning traditional hunting bows and arrows", "Universal free distribution of commercial tractors by international charities", "Voluntary donation of all arable farms to urban university research laboratories"],
     "Exorbitant interest rates (often exceeding 50-100%) trapped tribal peasants, transferring land to diku moneylenders."),
    ("Niyamgiri Dongria Kondh Landmark", "The historic 2013 Niyamgiri Gram Sabha referendums in Odisha were significant because:",
     "All twelve tribal village Gram Sabhas unanimously rejected bauxite mining on their sacred Niyam Dongar hill, which the Supreme Court upheld",
     ["The Gram Sabhas voted to sell their sacred hill to international corporate mining conglomerates", "The Gram Sabhas demanded the immediate construction of a commercial airport on their mountain", "The Gram Sabhas refused to accept any food grains from government ration shops"],
     "Niyamgiri established a global precedent: the Supreme Court upheld the Dongria Kondh Gram Sabhas' democratic veto over corporate mining."),
    ("Chota Nagpur Tenancy Act 1908", "What historical tribal rebellion directly forced the British colonial government to pass the Chota Nagpur Tenancy (CNT) Act in 1908?",
     "The Birsa Munda Ulgulan (Revolt) of 1899-1900", ["The Santhal Hool of 1855", "The Kol Rebellion of 1831", "The Sepoy Mutiny of 1857"],
     "The CNT Act 1908 prohibiting tribal land transfer to non-tribals was a direct outcome of Birsa Munda's great rebellion."),
    ("Santhal Parganas Tenancy Act 1876", "The Santhal Parganas Tenancy Act protecting tribal land tenure in eastern India was enacted following:",
     "The heroic Santhal Hool (Rebellion) of 1855 led by Sidhu and Kanhu Murmu", ["The First Anglo-Maratha War", "The Battle of Plassey", "The Non-Cooperation Movement of 1920"],
     "The 1855 Santhal Hool against moneylenders and British revenue collectors led to the creation of Santhal Parganas and protective tenancy laws."),
    ("Tribal Sub-Plan (TSP) Strategy", "What was the administrative purpose of introducing the 'Tribal Sub-Plan' (TSP) in the Fifth Five-Year Plan (1974-79)?",
     "To ensure that budgetary outlays for tribal development were earmarked in direct proportion to the tribal population in states",
     ["To force all tribal youth to join the merchant navy", "To ban all indigenous tribal agricultural festivals across peninsular India", "To privatize all rural schools in tribal districts to foreign commercial companies"],
     "The TSP strategy mandated state and central ministries to earmark development funds in proportion to tribal demographics."),
    ("Development-Induced Displacement", "Sociologists study 'Development-Induced Displacement' in tribal belts primarily as a crisis of:",
     "Involuntary physical uprooting, loss of customary livelihoods, cultural alienation, and social disarticulation",
     ["A celebration of voluntary urban consumerism and metropolitan real estate wealth", "An automated process managed smoothly by artificial intelligence without any human hardship", "A temporary weekend camping trip organized by state tourism corporations"],
     "Displacement destroys social networks, livelihood bases, and sacred cultural ties, plunging communities into chronic poverty."),
    ("Mining in Fifth Schedule Areas", "In the landmark *Samatha v. State of Andhra Pradesh* (1997) judgment, the Supreme Court ruled that:",
     "Mining leases granted to private non-tribal companies in Fifth Schedule Areas are null and void, as tribal land cannot be leased to non-tribals",
     ["Private multinational mining firms hold absolute sovereign rights over all tribal territories", "The Fifth Schedule of the Constitution was unconstitutional and invalid", "All tribal residents must be forcibly evicted to construct deep underground coal pits"],
     "The Samatha judgment upheld that tribal land in Scheduled Areas cannot be leased to private non-tribal corporations."),
    ("Community Forest Resource (CFR) Rights", "Under Section 3(1)(i) of FRA 2006, 'Community Forest Resource' (CFR) rights grant Gram Sabhas the power to:",
     "Protect, regenerate, conserve, and manage customary community forest resources for sustainable use",
     ["Clear-fell all ancestral forests and sell raw timber to overseas commercial paper mills", "Construct commercial concrete parking lots inside tiger reserves", "Hand over customary village water springs to private beverage conglomerates"],
     "CFR rights empower communities to govern and conserve ancestral forests through their traditional ecological knowledge."),
    ("Forest Villages vs Revenue Villages", "Historically, 'Forest Villages' set up by colonial and post-colonial forest departments were characterized by:",
     "Inhabitants lacking permanent land tenure and being subjected to compulsory bonded labour for forestry operations",
     ["Every family possessing freehold legal title and complete municipal civic amenities", "Residents receiving free private foreign holidays funded by the United Nations", "Zero government jurisdiction or state presence of any kind"],
     "Forest villages functioned as labour reserves for forest departments without formal land titles or standard panchayat development funds."),
    ("Conversion of Forest Villages to Revenue Villages", "A key statutory directive of the Forest Rights Act 2006 regarding 'Forest Villages' is to:",
     "Convert all forest villages, unrecorded settlements, and old habitations into formal Revenue Villages with full development entitlements",
     ["Demolish all homes in forest villages and deport residents to foreign countries", "Forbid forest village residents from voting in national democratic elections", "Surrender all forest villages to private multinational real estate firms"],
     "FRA mandates converting forest settlements into full revenue villages to extend roads, schools, electricity, and civic rights."),
    ("Ecology and Adivasi Worldview", "In sociological studies of indigenous belief systems, the Adivasi relationship with nature is characterized by:",
     "Sacred groves, animistic reverence for rivers and hills, and sustainable harvest taboos rather than predatory extraction",
     ["A desire to completely pave over all forests with concrete highways", "Total indifference toward wildlife, clean water, and fertile soils", "A belief that nature exists solely to be destroyed for immediate cash profit"],
     "Adivasi worldviews embed humans within nature: sacred groves (Sarnas) and clan totems enforce ecological conservation."),
    ("Adivasi Women and Land Rights", "In patriarchal tribal customary inheritance systems (such as among Santhals and Mundas), women historically:",
     "Had only usufructuary maintenance rights while ancestral land was inherited strictly through male lineage agnates",
     ["Held absolute legal power to sell all clan land to foreign buyers at will", "Inherited ninety percent of all ancestral land over male siblings", "Were appointed as supreme hereditary village monarchs"],
     "Customary tribal tenure often restricted land inheritance to patrilineal agnates, leaving widows and unmarried daughters vulnerable."),
    ("Tribal Intellectual Property and Biopiracy", "Why is the protection of tribal traditional ecological knowledge (TEK) vital in modern international intellectual property debates?",
     "To prevent commercial pharmaceutical corporations from patenting tribal medicinal plant preparations without benefit-sharing (biopiracy)",
     ["To force all tribal healers to abandon traditional medicine and buy imported antibiotics exclusively", "To ban all scientific research in universities across developing countries", "To make traditional herbal teas illegal in rural villages"],
     "Protecting TEK ensures indigenous groups retain sovereignty and fair benefit-sharing against predatory corporate biopiracy.")
]
for top, stem, corr, wrongs, sol in s11_extras:
    s11.append(mcq(CH_INST, top, stem, corr, wrongs, sol))
assert len(s11) == 20
slots[11] = s11

# Slot 12: Family Systems - Joint vs Nuclear Adaptations (20 items)
s12 = [
    mcq(CH_INST, "Joint Family Definition",
        "In Indian sociology, how is a traditional 'Joint Family' fundamentally defined?",
        "A multi-generational household sharing a common hearth (kitchen), common property, common worship, and reciprocal family obligations",
        ["A group of unrelated college students sharing a rented apartment in a metropolitan city",
         "A corporate board of company directors meeting annually in a private hotel",
         "A temporary military barracks where soldiers reside during wartime campaigns"],
        "Sociologically, a joint family is defined by co-residence, common kitchen (chulha), joint property, and joint worship."),
    stmt(CH_INST, "Nuclearization vs Extended Functional Ties",
        "Modern urban migration and housing shortages have led to a physical increase in nuclear residential family units in Indian cities.",
        "Physical nuclearization has completely severed all emotional, ritual, financial, and kinship obligations between urban households and rural kin.", 3,
        "Statement I is correct as urban nuclear households have expanded; Statement II is incorrect as functional jointness persists strongly."),
    ar(CH_INST, "Functional Adaptations of Indian Family",
        "Sociologists describe the contemporary Indian family as exhibiting 'structural adaptation' rather than total breakdown.",
        "Urban nuclear households frequently rely on extended family networks for child care, marriage alliances, elderly care, and financial crisis support.", 1,
        "Both (A) and (R) are true, and (R) correctly explains (A). The Indian family adapts functionally while maintaining extended solidarity."),
    match(CH_INST, "Family Typologies and Characteristics",
        "Match the family typologies in List I with their descriptions in List II:",
        [("A", "Nuclear Family"), ("B", "Joint Family"), ("C", "Patriarchal Family"), ("D", "Matriarchal Family")],
        [("I", "Authority, descent, and inheritance are concentrated in the senior male lineage head"),
         ("II", "Composed strictly of a married couple and their dependent biological or adopted children"),
         ("III", "Multi-generational household with common property, common kitchen, and extended relations"),
         ("IV", "Theoretical or observed system where maternal women hold primary lineage and societal authority")],
        "A-II, B-III, C-I, D-IV",
        "Nuclear family is parents and children; Joint is multi-generational; Patriarchal is male-dominated; Matriarchal is female-led."),
    seq(CH_INST, "Developmental Cycle of the Indian Household",
        "Arrange the phases of the 'Developmental Cycle of the Domestic Group' (formulated by Fortes/Shah) in typical logical sequence:",
        [("A", "Establishment of a nuclear family through marriage of a couple"),
         ("B", "Expansion of the family through the birth of dependent children"),
         ("C", "Fission or partial separation as adult sons marry and set up adjacent hearths"),
         ("D", "Re-establishment of independent nuclear units restarting the domestic cycle")],
        "A, B, C, D",
        "The domestic cycle progresses from marriage to expansion, dispersal/fission upon children marrying, and eventual replacement.")
]

s12_extras = [
    ("A.M. Shah on Household Dimensions", "Sociologist A.M. Shah made a vital theoretical distinction between which two concepts in family studies?",
     "The 'Household' (a residential, commensal unit) and the 'Family' (a broader conceptual and kinship institution)",
     ["The 'Apartment' and the 'Skyscraper'", "The 'Bank Account' and the 'Stock Market'", "The 'Factory' and the 'Trade Union'"],
     "A.M. Shah demonstrated that while households may nuclearize residentially, family kinship networks persist functionally."),
    ("Iravati Karve's Joint Family Definition", "Anthropologist Iravati Karve famously defined the traditional Indian joint family as:",
     "A group of people who generally live under one roof, eat food cooked at one hearth, hold property in common, participate in common family worship, and are related to one another as some particular type of kindred",
     ["A random collection of unrelated international travellers residing in an airport lounge", "A group of corporate executives sharing a company automobile", "An informal gathering of village farmers at a tea stall"],
     "Iravati Karve's classic definition in *Kinship Organization in India* emphasizes co-residence, common commensality, property, and worship."),
    ("Elderly Care in Changing Families", "How has the rise of dual-earner nuclear urban households impacted the care of elderly parents in modern India?",
     "It has created care-giving dilemmas, increasing reliance on paid domestic attendants, assisted living facilities, and informal family negotiations",
     ["It has eliminated all aging, with all citizens remaining permanently thirty years old", "It has resulted in the government banning all citizens aged over sixty from living in cities", "It has forced all grandparents to work in deep underground coal mines"],
     "Longer life expectancies combined with nuclear urban housing have created new challenges for elder care and filial support."),
    ("Dayabhaga vs Mitakshara Systems", "In classical Hindu family jurisprudence, how does the 'Dayabhaga' system (Bengal/Assam) differ from the 'Mitakshara' system (rest of India)?",
     "Under Mitakshara, a son acquires a coparcenary birthright in ancestral property at birth, whereas under Dayabhaga, sons acquire rights only upon the father's death",
     ["Mitakshara applies exclusively to foreign European merchants, while Dayabhaga applies to agricultural tenants", "Under Dayabhaga, property is inherited only by pet animals", "Mitakshara forbids all inheritance and mandates that all wealth be burned"],
     "Mitakshara recognizes birthright in ancestral coparcenary property, whereas Dayabhaga recognizes inheritance only upon the ancestor's death."),
    ("Hindu Succession Act 2005 Amendment", "What historic egalitarian reform did the Hindu Succession (Amendment) Act, 2005 introduce for daughters?",
     "It conferred equal coparcenary birthrights on daughters in ancestral property, identical to sons",
     ["It completely abolished private property ownership across all Indian states", "It barred daughters from receiving any education or formal employment", "It required all daughters to surrender their bank accounts to their husbands"],
     "The 2005 amendment granted daughters equal coparcenary rights by birth in Hindu joint family ancestral property."),
    ("Dual-Career Families in Urban India", "In modern urban sociology, 'Dual-Career' families are characterized by:",
     "Both husband and wife pursuing demanding professional careers, often negotiating gendered divisions of household domestic labour and childcare",
     ["Families where husband and wife work on completely different continents and never speak", "Families where both spouses are professional sports champions in the Olympic Games", "Households where neither partner has any source of income or formal employment"],
     "Dual-career families navigate modern career aspirations while often struggling with the gendered 'second shift' of domestic chores."),
    ("Second Shift Concept in Family Sociology", "Sociologist Arlie Hochschild's concept of the 'Second Shift' refers to:",
     "The unpaid domestic housework and childcare that employed women perform at home after returning from their paid formal jobs",
     ["A night shift worked by factory labourers in heavy manufacturing plants", "An extra academic semester undertaken by university students", "A secondary employment contract taken by bank managers on weekends"],
     "The 'second shift' highlights the persistent gender inequality where working women still perform the bulk of domestic chores."),
    ("Impact of Technology on Kinship Ties", "How have modern digital communication technologies (smartphones, video calls, messaging groups) altered extended family networks?",
     "They have enabled 'virtual jointness', allowing dispersed family members across continents to maintain daily contact, celebrate rituals, and coordinate decisions",
     ["They have completely destroyed all human speech and eliminated family relationships", "They have made it illegal for relatives to speak to each other across state borders", "They have forced all families to live in offline radio-free bunkers"],
     "Digital platforms sustain transnational and trans-local kinship solidarity, maintaining close emotional ties despite physical distance."),
    ("Single-Parent Households in India", "Sociological studies indicate that single-parent households in urban India:",
     "Are gradually increasing due to divorce, widowhood, or choice, frequently facing gendered economic challenges and social stigma",
     ["Are strictly prohibited by constitutional criminal statutes and subject to life imprisonment", "Receive free multi-million dollar state subsidies with zero personal taxation", "Exist exclusively among foreign tourists residing in luxury beach resorts"],
     "Single-parent households (predominantly female-headed) navigate economic burdens and patriarchal social disapproval."),
    ("Patrifocal vs Matrifocal Dynamics", "A family system is described as 'Patrifocal' when:",
     "The family life, cultural values, domestic authority, and decision-making center around male figures and paternal lineage interests",
     ["All property is owned exclusively by infants under two years old", "Family decisions are determined by random weekly newspaper lottery drawings", "The household is managed exclusively by foreign municipal civil servants"],
     "Patrifocal families center authority, lineage continuity, and decision-making around senior male patriarchal figures."),
    ("Remittances and Rural Joint Ties", "How does remittances sent by urban migrant workers maintain the economic viability of rural joint families?",
     "Remittances provide crucial cash income to purchase agricultural inputs, repay debts, educate younger siblings, and support aging parents in the village",
     ["Remittances are used exclusively to purchase private golden statues of foreign monarchs", "Remittances are immediately confiscated by metropolitan municipal corporations", "Remittances force rural farmers to stop cultivating food crops"],
     "Urban remittances bridge urban and rural households, sustaining the agrarian base and extended family reproduction."),
    ("Childhood Socialization in Joint Families", "Sociologists note that in traditional joint families, childhood socialization is characterized by:",
     "Multiple adult caretakers (grandparents, aunts, uncles), fostering diffuse emotional security and collective group orientation rather than narrow individualism",
     ["Strict isolation of the child in solitary confinement until age eighteen", "Care provided exclusively by foreign paid professional nanny staff", "Zero interaction between the child and any biological relatives"],
     "Joint families expose children to multi-generational socialization, diffusing emotional attachments beyond the biological parents."),
    ("Neolocal Residence Trends", "When newly married couples in modern metropolitan cities establish an independent household separate from both partners' parents, they practice:",
     "Neolocal residence", ["Patrilocal residence", "Matrilocal residence", "Avunculocal residence"],
     "Neolocal residence refers to establishing an autonomous household independent of both the husband's and wife's natal families."),
    ("Dowry Escalation and Commercialisation", "Modern sociological analysis demonstrates that rather than disappearing with education, the practice of dowry has:",
     "Expanded and commercialized, becoming a vehicle for competitive consumer display, black money absorption, and grooming price inflation",
     ["Completely ceased to exist in all Indian states since the passing of the Dowry Prohibition Act in 1961", "Been transformed into an equal cash payment from the groom's parents to the bride", "Been declared a mandatory religious sacrament by the Supreme Court of India"],
     "Dowry has commercialized into consumer displays (cars, appliances, cash), fueled by consumerism and marriage market prestige."),
    ("Domestic Violence within Family Structures", "Sociologists analyze domestic violence against women in patriarchal family structures as:",
     "An enforcement mechanism of male dominance, unequal power relations, and control over women's sexuality, labour, and choices",
     ["A purely accidental medical occurrence with zero connection to gender or family norms", "A legally encouraged custom rewarded with cash bonuses by state municipal governments", "An issue that affects only foreign nations and never occurs within Indian households"],
     "Domestic violence operates structurally to police gender roles and enforce patriarchal subordination within the domestic sphere.")
]
for top, stem, corr, wrongs, sol in s12_extras:
    s12.append(mcq(CH_INST, top, stem, corr, wrongs, sol))
assert len(s12) == 20
slots[12] = s12

# Save slots 11 and 12 into intermediate dictionary
print("Slots 11 and 12 completed.")
