import sys, os
sys.path.insert(0, os.getcwd())
from scripts.subject_generators.slot_helpers import mcq, stmt, ar, match, seq

CH_DEMO = "The Demographic Structure of the Indian Society"
CH_INST = "Social Institutions: Continuity and Change"

slots = {}

# Import Slots 1 to 4 from slots_1_10
import scripts.generators.soc.slots_1_10 as s10
for k in range(1, 5):
    slots[k] = s10.SLOTS[k]

# Import Slot 5 from build_slots_5_20
import scripts.generators.soc.build_slots_5_20 as s5
slots[5] = s5.slots[5]

# Import Slot 6 from build_slots_6_10
import scripts.subject_generators.build_slots_6_10 as s6
slots[6] = s6.slots[6]

# Slot 7: Sanskritisation, Reference Groups & Critiques (20 items)
s7 = [
    mcq(CH_INST, "Sanskritisation Definition",
        "How did M.N. Srinivas define the social process of 'Sanskritisation'?",
        "A process by which a low or middle Hindu caste, or tribal group, changes its customs, ritual, ideology, and way of life in the direction of a high, twice-born caste",
        ["A state mandate requiring all citizens to speak ancient Sanskrit in parliamentary debates",
         "The complete rejection of all religious ceremonies in favour of Western European atheism",
         "A government subsidy program for building private Sanskrit grammar schools in urban cities"],
        "M.N. Srinivas coined Sanskritisation to describe positional upward mobility through cultural emulation."),
    stmt(CH_INST, "Positional vs Structural Change in Sanskritisation",
        "Sanskritisation leads only to positional changes for particular castes within the caste system, not to a structural change of the system itself.",
        "Sanskritisation results in the complete overthrow and destruction of the Brahminical hierarchy.", 3,
        "Statement I is correct as Sanskritisation alters positional rank without modifying the structural hierarchy; Statement II is incorrect."),
    ar(CH_INST, "Reference Group in Sanskritisation",
        "Lower castes did not always emulate Brahmins; they also emulated Kshatriya or locally dominant peasant castes.",
        "The reference group for Sanskritisation was determined by local prestige, political power, and dominant caste influence in the region.", 1,
        "Both (A) and (R) are true, and (R) correctly explains (A). Srinivas noted Kshatriya and dominant caste models alongside Brahminical models."),
    match(CH_INST, "Sanskritisation Concepts and Theorists",
        "Match the sociological concepts in List I with their descriptions in List II:",
        [("A", "Sanskritisation"), ("B", "Reference Group"), ("C", "De-Sanskritisation"), ("D", "Dominant Caste")],
        [("I", "A social group whose lifestyle, values, and norms are emulated by others seeking upward status"),
         ("II", "Emulating twice-born ritual practices, vegetarianism, and customs for social mobility"),
         ("III", "Rejecting upper-caste cultural emulation to assert autonomous Dalit/Bahujan cultural identity"),
         ("IV", "Caste group holding intermediate land, decisive numbers, and political dominance in a village")],
        "A-II, B-I, C-III, D-IV",
        "Sanskritisation is cultural emulation; Reference Group is the model; De-Sanskritisation asserts Dalit pride; Dominant caste holds land and power."),
    seq(CH_INST, "Stages of Sanskritisation Process",
        "Arrange the stages of Sanskritisation for an upwardly mobile caste in logical sequence:",
        [("A", "Accumulation of secular economic wealth or land ownership"),
         ("B", "Adoption of dvija ritual symbols like sacred thread, vegetarianism, and teetotalism"),
         ("C", "Claiming higher Varna status (e.g. Kshatriya lineage) before local councils or censuses"),
         ("D", "Gradual social acceptance of the revised status by adjacent castes over generations")],
        "A, B, C, D",
        "Sanskritisation typically begins with economic wealth, followed by ritual emulation, mythical genealogy claims, and eventual generational acceptance.")
]

s7_extras = [
    ("Kumud Pawde's Sanskrit Experience", "In her autobiographical essay *The Story of My Sanskrit*, Dalit scholar Kumud Pawde highlights:",
     "The intense resistance and social hostility she encountered from upper-caste scholars for studying sacred Sanskrit as a Dalit woman",
     ["The universal encouragement and free scholarships she received from conservative orthodox priests", "Her decision to abandon Indian literature to study European navigation", "A complete absence of caste consciousness in modern Indian universities"],
     "Kumud Pawde documented how studying Sanskrit was seen as a threat to upper-caste monopoly over sacred knowledge."),
    ("Dalit Critique: Hegemony Acceptance", "A central Dalit critique of Sanskritisation formulated by modern scholars is that it:",
     "Legitimizes the ideology of purity and pollution and accepts the supremacy of upper-caste Brahminical culture",
     ["Compels high-caste priests to clean village sewers", "Was invented by British colonial officers who had never visited an Indian village", "Bans lower-caste students from enrolling in technical engineering colleges"],
     "Critiques emphasize that Sanskritisation accepts the lower status of manual labour and reinforces Brahminical hierarchy."),
    ("Gender Impact of Sanskritisation", "How does Sanskritisation typically impact the status and autonomy of women in emulating castes?",
     "It introduces patriarchal restrictions like female seclusion (purdah), dowry, and bans on widow remarriage to emulate high-caste norms",
     ["It grants women complete financial independence and eliminates all marriage customs", "It requires women to serve as commanding generals in regional armies", "It eliminates all domestic household chores and mandates female political leadership"],
     "Sanskritisation often reduces female autonomy by adopting orthodox patriarchal practices (purdah, dowry, widow remarriage bans)."),
    ("Model of Sanskritisation: Kshatriya", "When a newly wealthy peasant caste emulates warrior martial traditions and meat-eating rituals, it adopts the:",
     "Kshatriya model of Sanskritisation", ["Brahminical model of Sanskritisation", "Vaishya commercial model", "Renouncer ascetic model"],
     "The Kshatriya model emulates martial prowess, royal genealogy, and ruling authority rather than strict Brahminical vegetarianism."),
    ("Mythical Genealogies and Caste Sabhas", "How did caste associations (Jati Sabhas) historically reinforce Sanskritisation claims?",
     "By hiring traditional genealogists (Bhats/Charans) to construct mythical descent from ancient Vedic solar or lunar dynasties",
     ["By purchasing international television broadcasting channels", "By legally dissolving their caste identity and joining European trading companies", "By requiring all caste members to migrate permanently to South America"],
     "Caste sabhas commissioned mythical genealogies linking their communities to ancient Kshatriya or solar/lunar lines."),
    ("De-Sanskritisation Phenomenon", "In modern social movements, 'De-Sanskritisation' refers to:",
     "The conscious assertion of non-Brahmin, Dalit, or tribal pride and rejection of upper-caste rituals and values",
     ["The compulsory translation of modern physics textbooks into classical Latin", "The nationalization of all rural agricultural cooperatives", "A legal mandate banning the practice of astrology across Asia"],
     "De-Sanskritisation reclaims indigenous Dalit-Bahujan cultural identity and rejects upper-caste hegemony."),
    ("Yogendra Singh on Sanskritisation Scope", "According to sociologist Yogendra Singh, Sanskritisation operates primarily as a:",
     "Cultural form of social mobility that leaves the structural distribution of power largely intact",
     ["Complete violent economic revolution that abolishes private property", "Biological evolution that alters human physical genetics", "Foreign diplomatic treaty that redrafts international borders"],
     "Yogendra Singh categorized Sanskritisation as cultural mobility without structural economic revolution."),
    ("Sanskritisation and Colonial Census", "Why did Sanskritisation claims accelerate dramatically around the 1901 Census?",
     "Sir Herbert Risley's attempt to rank castes by social precedence prompted hundreds of castes to petition for higher status",
     ["The colonial government promised to abolish all income taxes for castes ranked as Brahmins", "The British army required all soldiers to prove descent from European royalty", "The Census was conducted exclusively in the Sanskrit language"],
     "The 1901 Census ranking provoked castes to mobilize, organize associations, and assert Sanskritised identities."),
    ("Commensal Rigidity in Sanskritisation", "When a caste undergoes Sanskritisation, its commensal behavior towards lower service castes typically becomes:",
     "More exclusionary and rigid, refusing to accept cooked food or water from castes ranked below them",
     ["Completely egalitarian, hosting universal community dining for all village residents", "Indifferent, ignoring all traditional rules regarding food and water sharing", "Focused exclusively on importing Western packaged fast foods"],
     "Sanskritising castes often enforce harsher commensal taboos against lower castes to prove their newly claimed ritual purity."),
    ("Brahminical vs Westernised Mobility", "M.N. Srinivas observed that while lower castes were often 'Sanskritising' their lifestyle, upper castes were increasingly:",
     "Westernising their lifestyle through English education, secular professions, and modern consumption",
     ["Emigrating to rural agricultural villages to perform manual labour", "Abandoning all urban properties to live as forest ascetics", "Forming armed rebellions to restore ancient monarchies"],
     "Srinivas identified a dual movement: lower castes adopting traditional Sanskrit symbols while upper castes adopted secular Westernisation."),
    ("Sanskritisation Without Economic Mobility", "What happens when a caste attempts Sanskritisation without possessing the secular economic or political power to back its claims?",
     "It faces violent sanctions, ridicule, and economic boycotts from locally dominant higher castes",
     ["It is automatically granted parliamentary seats by presidential decree", "It receives free private bank accounts from the national government", "It is awarded royal titles by international judicial courts"],
     "Without economic power, claims to higher status provoke violent backlash and humiliation from dominant castes."),
    ("Twice-Born (Dvija) Concept", "In classical Varna theory, which castes are designated as 'Dvija' (twice-born) entitled to the sacred thread (Upanayana)?",
     "Brahmins, Kshatriyas, and Vaishyas", ["Shudras and Dalits only", "Nomadic hunter-gatherers and pastoralists exclusively", "Foreign colonial merchants only"],
     "The first three Varnas (Brahmin, Kshatriya, Vaishya) are scripturally classified as Dvija (twice-born)."),
    ("Anti-Sanskritisation Literature", "Dalit literature in Maharashtra and Karnataka fundamentally subverted Sanskritisation by:",
     "Celebrating Dalit cultural expressions, dialect, labour dignity, and protest against Brahminical oppression",
     ["Writing classical epics glorifying ancient royal coronations in Sanskrit", "Demanding the re-institution of royal court poetry", "Encouraging Dalits to adopt orthodox Vedic sacrifices"],
     "Dalit literature challenged Sanskritisation by validating Dalit lived experiences, rebel poetry, and human dignity."),
    ("Sanskritisation in Tribal Contexts", "How did Sanskritisation historically affect certain central Indian tribal chieftains (e.g. Gonds and Bhils)?",
     "Tribal chiefs claimed Rajput (Kshatriya) ancestry, hired Brahmin priests, and adopted Hindu royal court rituals",
     ["Tribal chiefs declared themselves emperors of Great Britain", "Tribal chiefs abolished all traditional clan councils and moved to London", "Tribal chiefs banned all agricultural farming across their territories"],
     "Tribal ruling elites often claimed Rajput status (Rajputisation) to legitimize their territorial statehood."),
    ("Subversion of Sanskrit Monopolies", "In modern constitutional India, the state subverted historical Sanskrit monopolies by:",
     "Establishing secular state universities where Sanskrit and sacred texts are open to all citizens regardless of caste or gender",
     ["Banning the printing and reading of all classical texts nationwide", "Restricting university admission strictly to hereditary priests", "Requiring all university professors to be foreign nationals"],
     "Constitutional democracy democratized access to higher education, literature, and classical languages for all citizens.")
]
for top, stem, corr, wrongs, sol in s7_extras:
    s7.append(mcq(CH_INST, top, stem, corr, wrongs, sol))
assert len(s7) == 20
slots[7] = s7

# Slot 8: Dominant Castes & Agrarian Land Reforms (20 items)
s8 = [
    mcq(CH_INST, "Dominant Caste Definition",
        "According to M.N. Srinivas, which combination of factors defines a 'Dominant Caste' in rural India?",
        "Decisive numerical strength, intermediate landownership, and regional political power",
        ["Highest ritual Brahminical status with zero landholding or local political presence",
         "Ownership of international airline companies and urban commercial banks exclusively",
         "Hereditary recognition by the United Nations as sovereign indigenous rulers"],
        "Srinivas formulated dominant caste based on numerical preponderance, economic landholdings, and local political muscle."),
    stmt(CH_INST, "Dominant Caste and Land Reforms",
        "Post-independence land reforms (Zamindari abolition) transferred land rights from absentee landlords to intermediate cultivating peasant castes.",
        "These intermediate peasant castes successfully mobilized their numerical strength under universal adult franchise to dominate state politics.", 1,
        "Both statements are correct: Land reforms granted land to cultivating peasants (Jats, Yadavs, Vokkaligas) who leveraged numbers in electoral politics."),
    ar(CH_INST, "Dominant Caste vs Ritual Status Disparity",
        "A dominant caste does not necessarily hold the highest rank in the ritual Varna hierarchy.",
        "Decisive numerical strength and agrarian landownership give intermediate peasant castes decisive economic and political power over ritually superior Brahmins.", 1,
        "Both (A) and (R) are true, and (R) correctly explains (A). Dominant castes like Jats, Marathas, and Kammas wield secular power despite ritual ranking."),
    match(CH_INST, "Regional Dominant Castes and States",
        "Match the prominent dominant caste groups in List I with their primary Indian states in List II:",
        [("A", "Jats"), ("B", "Vokkaligas and Lingayats"), ("C", "Yadavs"), ("D", "Kammas and Reddys")],
        [("I", "Karnataka"), ("II", "Haryana, Punjab, and Western Uttar Pradesh"), ("III", "Andhra Pradesh and Telangana"), ("IV", "Bihar and Uttar Pradesh")],
        "A-II, B-I, C-IV, D-III",
        "Jats dominate Northwestern India; Vokkaligas/Lingayats dominate Karnataka; Yadavs dominate UP/Bihar; Kammas/Reddys dominate Andhra/Telangana."),
    seq(CH_INST, "Rise of Dominant Castes to Regional Power",
        "Arrange the stages in the post-independence empowerment of intermediate peasant dominant castes in chronological order:",
        [("A", "Abolition of Zamindari intermediaries and conferral of land ownership on cultivating tenants"),
         ("B", "Adoption of Green Revolution technologies (HYV seeds, tube-wells) boosting agrarian surpluses"),
         ("C", "Formation of regional peasant political parties and powerful agrarian vote banks"),
         ("D", "Direct capture of regional legislative assemblies and state chief ministerships")],
        "A, B, C, D",
        "The sequence progressed from land ownership (1950s) to Green Revolution wealth (1960s-70s), political party mobilization, and state power capture.")
]

s8_extras = [
    ("Dominant Caste Concept Origin", "M.N. Srinivas first formulated the concept of 'Dominant Caste' based on his intensive ethnographic fieldwork in which village?",
     "Rampura in Mysore (Karnataka)", ["Sripuram in Tanjore", "Mohana in Uttar Pradesh", "Kishan Garhi in Aligarh"],
     "Srinivas developed the dominant caste concept during his study of Rampura village in Mysore."),
    ("Dominant Caste Atrocities", "In contemporary rural sociology, why do dominant castes frequently come into conflict with Dalits?",
     "Dalits increasingly assert their constitutional rights, demand statutory minimum wages, and resist traditional subservience, challenging dominant caste hegemony",
     ["Dalits attempt to nationalize all agricultural land and transfer it to foreign corporations", "Dominant castes refuse to participate in parliamentary elections", "Dalits demand that all village residents convert to Western Christianity"],
     "Caste atrocities often arise when assertive Dalits refuse traditional unpaid labour and demand dignity, provoking dominant caste violence."),
    ("Western Education in Dominant Caste Power", "In addition to land and numbers, M.N. Srinivas noted which fourth element that consolidates a caste's dominance?",
     "Access to modern English education and positions in the government administrative civil service",
     ["Hereditary ownership of traditional sailing warships", "Control over diamond mining operations in Africa", "Monopoly over international textile patents"],
     "Modern education and representation in government bureaucracy reinforce the rural dominance of peasant castes."),
    ("Dominant Castes as Vote Banks", "Sociologist Rajni Kothari argued that the political mobilization of caste in India:",
     "Transformed caste into a competitive political instrument, democratizing power and enabling lower and intermediate castes to organize effective vote banks",
     ["Completely destroyed Indian democracy and restored British colonial administration", "Forced all citizens to vote exclusively based on horoscope readings", "Eliminated all political parties and replaced them with hereditary monarchs"],
     "Rajni Kothari showed that politics politicized caste, turning it into a secular tool for democratic negotiation and representation."),
    ("Marathas in Maharashtra", "In Maharashtra, which agrarian caste constitutes the classic example of a dominant caste controlling cooperatives, sugar mills, and state politics?",
     "The Marathas", ["The Chitpavan Brahmins", "The Mahars", "The Parsis"],
     "Marathas constitute over 30% of Maharashtra's population, controlling the rural sugar cooperative network and state politics."),
    ("Land Ceiling Acts Subversion", "How did dominant landowning peasant castes largely subvert post-independence Land Ceiling legislation?",
     "Through 'benami' transfers (registering land in the names of distant relatives, servants, or fictitious identities) and colluding with local revenue officials",
     ["By donating all their excess land to international charitable organizations", "By voluntarily abandoning agriculture to become full-time university professors", "By burning all their land records and returning to hunting-gathering"],
     "Landowners circumvented ceiling limits through fraudulent benami transfers and exploiting bureaucratic loopholes."),
    ("Green Revolution Beneficiaries", "Which social class in rural India benefited most decisively from the state-subsidized Green Revolution inputs in the 1960s and 1970s?",
     "Middle and large landowners belonging to intermediate dominant castes with access to irrigation and credit",
     ["Landless agricultural labourers and marginal tenants", "Traditional village leather artisans and scavengers", "Nomadic tribal hunter-gatherers"],
     "The Green Revolution disproportionately enriched prosperous landed farmers who had the capital to invest in tube-wells, fertilizers, and tractors."),
    ("Agrarian Shift to Capitalist Farming", "The transformation of dominant peasant castes into capitalist farmers was marked by:",
     "Hiring wage labour, maximizing market profit, investing in commercial cash crops, and re-investing surplus in agro-processing businesses",
     ["Returning to non-monetary barter exchange of agricultural grains", "Forbidding the use of tractors and modern electricity", "Refusing to sell crops in urban markets"],
     "Dominant castes transitioned from subsistence farming to profit-oriented capitalist agribusiness, sugar mills, and transport."),
    ("Dominant Caste Resistance to Reservations", "In recent decades, why have traditional dominant agrarian castes (such as Jats, Patidars, and Marathas) demanded OBC reservations?",
     "Agrarian fragmentation, rising input costs, and stagnation in farming have made youth desperate for secure government employment",
     ["They wish to abandon Indian citizenship and live as refugees abroad", "They have lost all their agricultural land to foreign space agencies", "They have been declared illegal immigrants by the Supreme Court"],
     "Agrarian crises, land subdivision, and formal job scarcity prompted dominant farming castes to mobilize for quota benefits."),
    ("Inter-Caste Dominance vs Intra-Caste Inequality", "Sociological studies demonstrate that while a caste may be 'dominant' in regional politics:",
     "Intense internal economic stratification exists between a tiny elite of rich farmers and the mass of small, indebted peasants within the same caste",
     ["Every single member of the caste possesses identical monetary wealth and identical acres of land", "All members of the caste are employed as high court judges", "There is zero poverty or landlessness among any members of the caste"],
     "Dominant castes are internally stratified: affluent leaders hold power while marginal peasant caste-brethren face poverty."),
    ("Dominant Caste Control of Panchayati Raj", "Historically, prior to reservations for Dalits and women, traditional village panchayats were dominated by:",
     "Elders and wealthy landowners of the dominant caste who dispensed justice to maintain the traditional social order",
     ["Young female agricultural labourers elected by computer lottery", "British colonial military judges permanently posted in villages", "Elected representatives from international trade unions"],
     "Dominant castes monopolized traditional informal village councils (caste panchayats), settling disputes in their own favor."),
    ("Patidars of Gujarat", "In Gujarat, the Patidar (Kanbi) community established economic and political dominance primarily through:",
     "Commercial cash crop agriculture (tobacco/cotton), dairy cooperatives (Amul), overseas migration, and small-scale industries",
     ["Hereditary monopolization of Hindu temple priesthoods", "Traditional nomadic fishing along international oceanic borders", "Exclusively serving as military cavalry for the Mughal Empire"],
     "Patidars converted agrarian surpluses into commercial agribusiness, dairy networks, and industrial entrepreneurship."),
    ("Dominant Caste and Cultural Hegemony", "In village life, the dominant caste's culture often becomes:",
     "The local reference model for language, dress, rituals, and dispute settlement, exercising cultural hegemony over subordinate groups",
     ["Strictly forbidden from being displayed in any public streets", "Identical to Western European corporate etiquette", "Subject to censorship by foreign embassies"],
     "The dominant caste establishes cultural hegemony: local dialects, wedding rituals, and dispute norms reflect its preferences."),
    ("Dominant Caste Political Coalitions", "In democratic electoral politics, dominant peasant castes frequently forge coalitions with:",
     "Other intermediate agrarian castes and minority groups to secure legislative majorities in state assemblies",
     ["Foreign colonial powers to overthrow the Constitution", "Space exploration agencies to establish lunar colonies", "Ancient hereditary royal dynasties exclusively"],
     "Dominant castes build multi-caste electoral alliances (e.g. AJGAR, KHAM) to consolidate political power in state politics."),
    ("Decline of Brahmin Dominance in South India", "The rise of non-Brahmin dominant peasant castes in South India in the early 20th century was accelerated by:",
     "The Non-Brahmin Movement (Justice Party, Self-Respect Movement) that challenged Brahminical monopoly over government jobs and education",
     ["A royal decree issued by the King of England banning Brahmins from India", "The complete collapse of all agriculture in southern India", "The total replacement of regional languages by classical Sanskrit"],
     "Non-Brahmin political movements dismantled Brahminical hegemony in administration and education across the south.")
]
for top, stem, corr, wrongs, sol in s8_extras:
    s8.append(mcq(CH_INST, top, stem, corr, wrongs, sol))
assert len(s8) == 20
slots[8] = s8

# Slot 9: Tribal Communities - Classification & Traits (20 items)
s9 = [
    mcq(CH_INST, "Tribal Classification Criteria",
        "In Indian sociology and anthropology, tribal communities are classified based on which two broad sets of traits?",
        "'Permanent traits' (ecological habitat, language, physical characteristics) and 'Acquired traits' (livelihood, degree of assimilation)",
        ["Monthly bank balance and ownership of private commercial airlines",
         "The number of foreign languages spoken fluently by tribal council leaders",
         "The brand of tractor utilized in commercial agriculture"],
        "Tribes are classified by permanent traits (region, language, physical type) and acquired traits (livelihood, assimilation)."),
    stmt(CH_INST, "Permanent vs Acquired Traits",
        "Permanent traits of tribes include their classification into language families such as Austro-Asiatic, Tibeto-Burman, Dravidian, and Indo-Aryan.",
        "Acquired traits refer to their physical anatomical phenotypes such as Negrito and Proto-Australoid features.", 3,
        "Statement I is correct; Statement II is incorrect because physical phenotypes are permanent biological traits, not acquired ones."),
    ar(CH_INST, "Geographic Concentration of Indian Tribes",
        "Over 85 percent of the tribal population in India is concentrated in 'Middle India' (stretching from Gujarat to West Bengal).",
        "Middle India contains rich mineral, forest, and water resources where tribal communities have resided for millennia.", 1,
        "Both (A) and (R) are true, and (R) correctly explains (A). The central tribal belt encompasses MP, Jharkhand, Odisha, Chhattisgarh, and adjacent states."),
    match(CH_INST, "Tribal Language Families and Examples",
        "Match the tribal language families in List I with the prominent tribes speaking them in List II:",
        [("A", "Austro-Asiatic (Munda group)"), ("B", "Tibeto-Burman"), ("C", "Dravidian"), ("D", "Indo-Aryan")],
        [("I", "Gonds and Oraons"), ("II", "Santhals, Hos, and Mundas"), ("III", "Bhils and Warli"), ("IV", "Bodos, Nagas, and Khasis")],
        "A-II, B-IV, C-I, D-III",
        "Santhals/Mundas speak Austro-Asiatic; Khasis/Nagas speak Tibeto-Burman; Gonds/Oraons speak Dravidian; Bhils speak Indo-Aryan."),
    seq(CH_INST, "Size Classification of Indian Tribes",
        "Arrange the following tribal groups from the largest population size in India to smaller groups:",
        [("A", "Large tribal groups exceeding several millions (Bhils and Gonds)"),
         ("B", "Intermediate tribal groups like Santhals and Oraons"),
         ("C", "Regional tribal communities like Khasis and Garos"),
         ("D", "Small, vulnerable island populations under one thousand (Great Andamanese and Sentinelese)")],
        "A, B, C, D",
        "Tribes range from multi-million populations (Bhils, Gonds) down to endangered island populations under one hundred individuals.")
]

s9_extras = [
    ("Concept of Adivasi", "The term 'Adivasi' coined in the 1930s literally translates to:",
     "'Original inhabitants' or 'first settlers' of the land", ["'Royal rulers'", "'Modern factory workers'", "'Foreign merchants'"],
     "'Adivasi' literally means original inhabitants, expressing indigenous identity and territorial priority."),
    ("Particularly Vulnerable Tribal Groups (PVTGs)", "Which criteria are utilized by the Government of India to identify Particularly Vulnerable Tribal Groups (PVTGs)?",
     "Pre-agricultural level of technology, declining or stagnant population, extremely low literacy, and subsistence economic status",
     ["Ownership of commercial jet aircraft and private golf courses", "Over 90 percent enrollment in foreign university doctoral programs", "Monopolization of national heavy engineering industries"],
     "PVTGs are identified by stagnant/declining population, pre-agricultural technology, low literacy, and extreme economic vulnerability."),
    ("Number of PVTGs in India", "How many tribal groups have been officially designated as Particularly Vulnerable Tribal Groups (PVTGs) across India?",
     "75 tribal groups", ["12 tribal groups", "350 tribal groups", "500 tribal groups"],
     "The Government of India has recognized 75 tribal communities as PVTGs across 18 states and one Union Territory."),
    ("Northeastern Tribal Profile", "How does the tribal demographic profile in Northeastern states (e.g. Mizoram, Nagaland, Meghalaya) contrast with Middle India?",
     "Tribes constitute over 80-90% of the state population in several Northeastern states, but represent only a small fraction of the total national tribal population",
     ["Northeastern tribes have zero literacy and zero political representation in state assemblies", "Northeastern tribes have completely abandoned their native languages for classical Latin", "Northeastern tribes live exclusively in underground salt mines"],
     "In the Northeast, tribes form the overwhelming majority locally, although 85% of India's total tribal population resides in Middle India."),
    ("Dormitory System: Ghotul", "In Indian anthropology, the 'Ghotul' studied extensively by Verrier Elwin was:",
     "A traditional youth dormitory and socialization institution among the Muria Gonds of Bastar",
     ["A commercial bank granting microloans to village traders", "A military fortress constructed by colonial engineers", "A religious temple where lower castes were forbidden from entering"],
     "The Ghotul is the traditional co-educational youth dormitory of the Muria Gonds, fostering community solidarity and cultural values."),
    ("Nomadic and De-Notified Tribes", "The 'Criminal Tribes Act' of 1871 enacted by the British colonial regime was historic because it:",
     "Falsely classified entire hereditary nomadic and wandering communities as 'born criminals' subject to surveillance and confinement",
     ["Abolished all police forces and courts across British India", "Granted sovereign territorial independence to pastoral nomadic groups", "Made nomadism mandatory for all citizens living in urban cities"],
     "The colonial Criminal Tribes Act 1871 stigmatized hundreds of nomadic communities as genetically and hereditarily criminal."),
    ("De-Notification in 1952", "Following independence, the Government of India passed the Habitual Offenders Act in 1952 to:",
     "'De-notify' the communities previously classified under the British Criminal Tribes Act, ending their statutory criminal status",
     ["Re-arrest all nomadic pastoralists and confine them permanently in penal colonies", "Abolish the Indian Constitution and restore British law", "Declare all nomadic languages extinct"],
     "In 1952, the communities were 'de-notified', though socio-economic stigma and police harassment often persisted."),
    ("Tribe-Caste Continuum Concept", "Anthropologist Surajit Sinha proposed the concept of the 'Tribe-Caste Continuum' to explain:",
     "The gradual, historical process through which egalitarian, lineage-based tribal groups were assimilated into hierarchical, stratified Hindu caste society",
     ["The complete genetic separation of human populations into biological species", "A computer algorithm for calculating railway freight tariffs", "A statutory formula for distributing foreign aid grants"],
     "The Tribe-Caste continuum models the historical transformation of tribes into castes via peasantization and Sanskritisation."),
    ("Tribal Mode of Livelihood: Jhum", "Traditional 'Jhum' or shifting cultivation practiced by many tribal groups in hilly terrains is ecologically characterized by:",
     "Slashing and burning vegetation, cultivating the plot for a few seasons, and leaving it fallow for natural forest regeneration",
     ["Using heavy diesel tractors to plough soil five meters deep with chemical fertilizers", "Diverting large continental rivers into concrete industrial pipelines", "Planting only genetically modified monoculture cash crops for export"],
     "Jhum (shifting/slash-and-burn cultivation) relies on cyclical fallow periods to restore natural soil fertility in hilly forest ecosystems."),
    ("Colonial Ban on Shifting Cultivation", "Why did British colonial forest administrators aggressively prohibit tribal shifting (Jhum) cultivation?",
     "They viewed it as wasteful of valuable commercial timber (teak and sal) and difficult to monitor for state land revenue collection",
     ["They wished to convert all tribal hills into wild tiger sanctuaries", "They believed shifting cultivation caused global ice ages", "They wanted tribal farmers to emigrate to work in European gold mines"],
     "Colonial foresters opposed Jhum because it burned valuable commercial timber and evaded fixed territorial land revenue taxation."),
    ("Constitutional Schedules: Fifth and Sixth", "The Indian Constitution protects tribal autonomy through which two landmark administrative schedules?",
     "The Fifth Schedule (for Scheduled Areas in peninsular India) and the Sixth Schedule (for autonomous district councils in Assam, Meghalaya, Tripura, Mizoram)",
     ["The First and Second Schedules", "The Ninth and Tenth Schedules", "The Eleventh and Twelfth Schedules"],
     "The Fifth and Sixth Schedules provide specialized constitutional governance and protective district councils for tribal areas."),
    ("Sixth Schedule Autonomous District Councils", "Under the Sixth Schedule of the Indian Constitution, Autonomous District Councils (ADCs) in the Northeast possess:",
     "Legislative, judicial, and executive powers to manage customary laws, land transfer, forests, and local village courts",
     ["Power to declare international war against neighboring foreign nations", "Complete control over national foreign exchange reserves", "Zero legal powers to make any local decisions whatsoever"],
     "Sixth Schedule ADCs exercise substantial autonomy to protect indigenous customary law, land alienation, and local governance."),
    ("Scheduled Tribes Category Origin", "The administrative category 'Scheduled Tribes' was directly derived from which historical colonial document?",
     "The Government of India Act, 1935, which categorized vulnerable indigenous groups as 'backward tribes'",
     ["The Magna Carta of 1215", "The Charter Act of 1813", "The Indian Councils Act of 1909"],
     "The GoI Act 1935 defined 'backward tribes', which became the basis for the Constitution's Scheduled Tribes list."),
    ("Totemism in Tribal Sociology", "In anthropological studies of tribal religion, 'Totemism' refers to:",
     "A belief system where a clan traces sacred kinship or spiritual association with a specific animal, plant, or natural object, observing taboos against harming it",
     ["The scientific worship of industrial steam locomotives and factories", "The mandatory requirement that all village residents wear silver wristwatches", "A commercial lottery for distributing agricultural land"],
     "Totemism links clan lineage to a sacred animal or plant emblem, symbolizing group solidarity and enforcing ecological taboos."),
    ("Tribal Assimilation into Peasant Society", "When tribal communities lost their forests and were absorbed into Hindu agrarian society, they were historically integrated at:",
     "The bottom of the caste hierarchy as landless agricultural labourers, menial service castes, or bonded servants",
     ["The apex of society as supreme high-caste priests", "The status of wealthy urban corporate industrialists", "The rank of sovereign provincial royal governors"],
     "Tribal absorption into the caste system overwhelmingly relegated communities to the lowest rungs of landless agrarian labour.")
]
for top, stem, corr, wrongs, sol in s9_extras:
    s9.append(mcq(CH_INST, top, stem, corr, wrongs, sol))
assert len(s9) == 20
slots[9] = s9

# Slot 10: Tribal Debates - Isolation vs Integration (20 items)
s10_qs = [
    mcq(CH_INST, "Isolation vs Integration Tribal Debate",
        "The famous debate in Indian sociology between Verrier Elwin and G.S. Ghurye centered on:",
        "Whether tribal communities should be isolated in protective enclaves or assimilated into mainstream Hindu society",
        ["Whether India should build nuclear submarines or diesel trains",
         "Whether university degrees should be awarded in English or Latin exclusively",
         "Whether tea plantations in Assam should be owned by French or German merchants"],
        "The Elwin-Ghurye debate contrasted Elwin's protectionist enclave approach with Ghurye's assimilationist stance."),
    stmt(CH_INST, "Elwin's National Park Proposal",
        "Verrier Elwin initially proposed establishing 'National Parks' or protected reserves for tribes like the Baigas to shield them from rapacious exploiters.",
        "Elwin was accused by nationalist critics of wanting to keep tribal people as 'museum specimens' for anthropological curiosity.", 1,
        "Both statements are correct: Elwin proposed isolation to prevent cultural ruin, but nationalists criticized it as keeping tribes in a zoo."),
    ar(CH_INST, "Ghurye's Backward Hindus Thesis",
        "G.S. Ghurye characterized Indian tribes as 'backward Hindus' rather than distinct indigenous peoples.",
        "He argued that tribal communities had undergone centuries of imperfect cultural and religious assimilation into Hindu society.", 1,
        "Both (A) and (R) are true, and (R) correctly explains (A). In *The Aborigines-'So-Called'-and Their Future*, Ghurye argued for assimilation."),
    match(CH_INST, "Tribal Debaters and Perspectives",
        "Match the scholars and leaders in List I with their tribal development philosophy in List II:",
        [("A", "Verrier Elwin"), ("B", "G.S. Ghurye"), ("C", "Jawaharlal Nehru"), ("D", "Jaipal Singh Munda")],
        [("I", "Viewed tribes as 'backward Hindus' needing integration into mainstream Hindu society"),
         ("II", "Advocated protective isolation in reserves to shield tribes from moneylenders and cultural destruction"),
         ("III", "Formulated the 'Tribal Panchsheel' balancing modern development with preservation of tribal genius"),
         ("IV", "Adavasi political leader who championed Adivasi rights in the Constituent Assembly and demanded Jharkhand")],
        "A-II, B-I, C-III, D-IV",
        "Elwin advocated protection/isolation; Ghurye advocated assimilation; Nehru framed Tribal Panchsheel; Jaipal Singh led Adivasi politics."),
    seq(CH_INST, "Evolution of Indian Tribal Policy",
        "Arrange the phases of official tribal policy in modern Indian history in chronological order:",
        [("A", "British colonial policy of non-interference and 'excluded/partially excluded areas'"),
         ("B", "Intense nationalist debate between Elwin's isolationism and Ghurye's assimilationism"),
         ("C", "Adoption of Nehru's 'Tribal Panchsheel' balancing integration with cultural autonomy"),
         ("D", "Enactment of the landmark PESA Act (1996) and Forest Rights Act (2006)")],
        "A, B, C, D",
        "Policy evolved from colonial excluded areas to the Elwin-Ghurye debate, Nehru's Panchsheel, and modern rights-based legislation (PESA/FRA).")
]

s10_extras = [
    ("Nehru's First Principle of Panchsheel", "What is the very first principle of Jawaharlal Nehru's five-point 'Tribal Panchsheel'?",
     "People should develop along the lines of their own genius and we should avoid imposing anything on them",
     ["All tribal languages should be immediately outlawed in primary schools", "Tribal lands should be auctioned to private multinational mining conglomerates", "All tribal youth should be conscripted into the merchant navy"],
     "Nehru's first principle demanded that tribal people develop according to their own genius without external cultural imposition."),
    ("Nehru on Tribal Land Rights", "Regarding tribal rights in land and forests, Nehru's Tribal Panchsheel explicitly stipulated that:",
     "Tribal rights in land and forests should be respected and safeguarded by the state",
     ["All tribal forests should be cleared immediately for urban real estate", "Tribal lands should be converted into military artillery firing ranges", "Tribal communities should be taxed at double the rate of urban businesses"],
     "Nehru insisted that customary rights in land and forests must be protected and never alienated to outsiders."),
    ("Nehru on Administration Quality", "According to Nehru's Tribal Panchsheel, tribal areas should be administered by:",
     "Training and building up a team of tribal people themselves for administration and development work",
     ["Importing thousands of untrained foreign corporate executives to manage all villages", "Deploying permanent military martial law battalions in all settlements", "Abolishing all administrative departments in tribal districts"],
     "Nehru emphasized building indigenous tribal administrative capacity rather than flooding tribal lands with non-tribal bureaucrats."),
    ("Nehru on Evaluating Tribal Progress", "How did Nehru define the true index of success for tribal development in his Panchsheel?",
     "Not by statistics of money spent or how many buildings erected, but by the quality of human character that is evolved",
     ["By the total metric tons of coal extracted from tribal lands per annum", "By how many European neckties tribal farmers wear on weekends", "By the total profits generated for private international logging firms"],
     "Nehru warned against judging success by money spent, emphasizing the preservation of human dignity and character."),
    ("Jaipal Singh Munda in Constituent Assembly", "In his famous 1946 speech to the Constituent Assembly, Olympic gold medalist and Adivasi leader Jaipal Singh stated:",
     "That as an Adivasi, he welcomed the new democracy, but reminded the nation that his people had been exploited and pushed aside for thousands of years",
     ["That all tribal communities wished to leave the Indian Union and join European empires", "That tribal people refused to participate in modern democratic governance", "That all industrial steel factories should be dismantled immediately"],
     "Jaipal Singh articulated the historical dispossession of Adivasis while embracing democratic nation-building on terms of dignity."),
    ("Impact of Large Dams on Adivasis", "Sociological studies of post-independence 'Nehruvian development' reveal that mega-dams (e.g. Sardar Sarovar, Hirakud) resulted in:",
     "Disproportionate displacement of Adivasis, who constituted over 40-50% of all displaced persons despite being only 8% of the population",
     ["Free luxury urban apartments and permanent corporate executive jobs for all displaced tribal families", "The complete elimination of poverty across all central Indian tribal districts", "Zero physical displacement of any human beings across central India"],
     "Adivasis bore the heaviest burden of national development, suffering massive land submergence without adequate rehabilitation."),
    ("A.R. Desai's Critique of Tribal Policy", "Marxist sociologist A.R. Desai argued that government tribal welfare policies failed because:",
     "They operated within a capitalist framework that inevitably allowed private contractors, mining corporations, and moneylenders to exploit tribal resources",
     ["They spent too much state revenue building free modern universities in tribal villages", "They enforced compulsory vegetarianism across all tribal communities", "They were managed exclusively by foreign anthropological scholars"],
     "A.R. Desai critiqued the state for facilitating capitalist resource extraction that dispossessed Adivasis."),
    ("Land Alienation Mechanisms", "How did non-tribal moneylenders and traders historically alienate land from illiterate tribal farmers?",
     "By trapping them in debt cycles with exorbitant interest rates, forcing mortgage of land, and using forged legal documents",
     ["By paying them three times the international market price in pure gold coins", "By constructing free modern irrigation canals on their farms", "By transferring urban metropolitan penthouses into their legal ownership"],
     "Usurious interest, debt traps, liquor inducement, and legal manipulation resulted in widespread tribal land alienation."),
    ("PESA Act 1996 Core Mandate", "What revolutionary power does the Panchayats (Extension to Scheduled Areas) Act, 1996 (PESA) grant to the village Gram Sabha?",
     "Mandatory consultation prior to land acquisition, ownership of minor forest produce, and power to prevent tribal land alienation",
     ["Power to mint regional paper currency independent of the Reserve Bank of India", "Authority to command naval battleships on international waters", "Zero power to object to private corporate mining leases"],
     "PESA empowers the traditional Gram Sabha with statutory authority over land acquisition, minor forest produce, and dispute settlement."),
    ("Minor Forest Produce (MFP) Significance", "Why is statutory ownership of 'Minor Forest Produce' (MFP) under PESA and FRA vital for tribal livelihoods?",
     "Gathering items like tendu leaves, mahua flowers, lac, and honey provides critical cash income and subsistence during agricultural lean seasons",
     ["MFP consists exclusively of radioactive uranium ores used for space rockets", "MFP items can only be sold to royal monarchies in Europe", "MFP gathering is strictly forbidden by the United Nations"],
     "Minor forest produce is the economic lifeline of forest-dwelling communities, supporting survival during lean agricultural months."),
    ("Forest Rights Act (FRA) 2006 Landmark", "The Scheduled Tribes and Other Traditional Forest Dwellers (Recognition of Forest Rights) Act, 2006 was enacted to:",
     "Correct the 'historical injustice' committed against forest dwellers by legally recognizing individual and community forest rights",
     ["Evict all human populations from forests and convert all land into private luxury golf resorts", "Hand over all Indian national parks to foreign commercial logging conglomerates", "Criminalize the collection of fallen dry firewood by tribal women"],
     "FRA 2006 recognized pre-existing customary tenure rights, seeking to redress historical colonial and post-colonial injustices."),
    ("Displacement vs Rehabilitation Gap", "Walter Fernandes and other sociologists describe the post-independence rehabilitation of displaced Adivasis as:",
     "A systemic failure characterized by inadequate cash compensation, cultural dislocation, and pauperization into informal migrant labour",
     ["An unprecedented triumph where every displaced farmer became a millionaire industrialist", "A completely non-existent issue because no development projects displaced any tribal villages", "Fully supervised by international space agencies with zero complaints"],
     "Fernandes documented that fewer than a third of displaced Adivasis were resettled, turning self-reliant cultivators into vulnerable casual wage laborers."),
    ("Sub-Nationalism and Tribal Statehood", "The creation of Jharkhand and Chhattisgarh as separate states in November 2000 was the culmination of:",
     "Decades of protracted tribal struggles demanding political autonomy, protection of natural resources, and freedom from internal colonialism",
     ["A sudden decision by the British Crown to redraw South Asian borders in 2000", "A linguistic dispute regarding the grammar of classical Sanskrit", "A military conflict between neighboring foreign kingdoms"],
     "Jharkhand and Chhattisgarh emerged from decades of tribal social movements resisting resource exploitation and demanding autonomy."),
    ("Internal Colonialism Concept in Jharkhand", "In the Jharkhand movement, social theorists used the concept of 'Internal Colonialism' to describe how:",
     "The mineral and forest wealth of the region was extracted to enrich metropolitan industrial centers while local Adivasis suffered extreme poverty",
     ["Foreign colonial powers had returned to establish military forts across Ranchi", "The entire population of Jharkhand had emigrated to North America", "Jharkhand was importing all its food grain from Western Europe"],
     "'Internal colonialism' conceptualized the extractive drainage of Jharkhand's minerals without regional benefit to indigenous inhabitants."),
    ("Cultural Imperialism vs Autonomy", "In modern anthropological consensus, the most sustainable approach to tribal communities is:",
     "Respecting constitutional self-governance, land tenure security, and cultural autonomy while providing quality public health and education on their own terms",
     ["Forced cultural assimilation that erases all indigenous languages and rituals", "Enclosing all tribal communities inside high electric barbed-wire fences without medical care", "Transferring all tribal children to foreign boarding schools to forget their ancestral heritage"],
     "Contemporary sociology champions rights-based self-determination, forest tenure, and culturally respectful human development.")
]
for top, stem, corr, wrongs, sol in s10_extras:
    s10_qs.append(mcq(CH_INST, top, stem, corr, wrongs, sol))
assert len(s10_qs) == 20
slots[10] = s10_qs

# Save slots 1 to 10 into soc_s1_10.py
out_path = "scripts/subject_generators/soc_s1_10.py"
with open(out_path, "w", encoding="utf-8") as f:
    f.write("# Sociology Slots 1 to 10 (200 questions)\n\nSLOTS_1_10 = " + repr(slots) + "\n")

print(f"SUCCESS: Slots 1 to 10 saved in {out_path}! Total slots: {len(slots)}")
for k in range(1, 11):
    assert len(slots[k]) == 20, f"Slot {k} has {len(slots[k])} items"
    print(f"  Slot {k}: 20 items")
