# Slots 31 to 35 Generator
s31_to_35 = '''
CH_ECONOMICS = "Environmental and Natural Resource Economics"

# ==============================================================================
# Slot 31: Natural Resources Classification & Common Property Resources
# ==============================================================================
s31_raw = [
    ("mcq", "Resource Classification Taxonomy",
     "In natural resource economics, resources whose quantity is not diminished by human consumption and which are continuously replenished by cosmic or planetary cycles (such as solar radiation, wind, and tidal energy) are classified as:",
     "Perpetual resources",
     ["Non-renewable stock resources", "Exhaustible biotic resources", "Fossil hydrocarbons"],
     "Perpetual resources (solar, wind, tides) are virtually inexhaustible on human timescales, unlike finite non-renewable stock resources (coal, petroleum)."),
    ("stmt", "Renewable vs Non-Renewable Resources",
     "Renewable resources (such as groundwater, fisheries, and forests) can regenerate biologically or biogeochemically, provided harvesting does not exceed their maximum sustainable yield.",
     "Non-renewable resources (such as crude oil, coal, and metallic ores) exist in finite fixed geological stocks and cannot be replenished on human generational timescales.", 1,
     "Both Statement I and Statement II are correct. Renewable resources regenerate dynamically, while non-renewable resources are depleted permanently upon extraction."),
    ("ar", "Tragedy of the Commons Garrett Hardin Thesis",
     "In his classic 1968 essay 'The Tragedy of the Commons', Garrett Hardin argued that shared, open-access resources inevitably suffer degradation and depletion.",
     "When access is unrestricted, each rational economic individual maximizes private gain by extracting resources, while the environmental degradation cost is diffused across the entire collective society.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Private individual benefit (+1) outweighs the private fraction of collective environmental loss (-1/n), driving systemic overexploitation."),
    ("match", "Resource Concepts and Institutional Frameworks",
     "Match the resource concept in List I with its pioneer or economic definition in List II:",
     [("A", "The Tragedy of the Commons (1968)"),
      ("B", "Governing the Commons (Nobel Prize 2009)"),
      ("C", "Hubbert Peak Oil Theory (1956)"),
      ("D", "Maximum Sustainable Yield (MSY)")],
     [("I", "Garrett Hardin: open-access commons face inevitable ruin without private property or state coercion"),
      ("II", "Elinor Ostrom: user communities can sustainably govern common pool resources through self-organized rules without state intervention"),
      ("III", "M. King Hubbert: crude oil extraction follows a bell-shaped curve, peaking before irreversible terminal decline"),
      ("IV", "The maximum harvest rate that can be extracted indefinitely from a renewable resource without depleting the base stock")],
     "A-I, B-II, C-III, D-IV",
     "Hardin warned of tragedy of commons, Ostrom proved community CPR governance, Hubbert modeled peak oil, and MSY defines sustainable harvest yields."),
    ("mcq", "Elinor Ostrom Nobel Memorial Prize Contribution",
     "Political scientist Elinor Ostrom became the first woman to win the Nobel Memorial Prize in Economic Sciences (2009) by disproving Hardin's thesis, demonstrating empirically that:",
     "Local communities can successfully manage Common Property Resources (CPRs like alpine pastures, irrigation canals, and community forests) through self-devised institutional rules, monitoring, and graduated sanctions",
     ["Private corporate monopolies are the only entities capable of conserving water", "All human beings are biologically programmed to destroy every ecosystem they encounter", "The state military must police every village well in the world"],
     "Elinor Ostrom documented hundreds of long-enduring, community-managed common pool resources (CPRs), proving cooperative user governance avoids the tragedy of the commons."),
    ("mcq", "Common Pool Resources (CPR) Economic Attributes",
     "In public economics, a 'Common Pool Resource' (CPR) is defined by which combination of economic characteristics?",
     "High rivalness in consumption (one user's extraction diminishes availability to others) and high excludability difficulty (costly to exclude potential beneficiaries)",
     ["Low rivalness and high excludability (Toll / Club goods)", "Low rivalness and low excludability (Pure Public goods like clean air)", "High rivalness and easy excludability (Pure Private goods like a sandwich)"],
     "CPRs (pastures, fisheries, groundwater) are rivalrous (subtractable) yet non-excludable, making them vulnerable to free-riding unless governed by local institutional rules."),
    ("stmt", "Potential vs Actual Resources",
     "Potential resources are resources identified in a geographic region whose total quantity may not be known and which are not currently utilized due to technological or financial constraints.",
     "Actual / Developed resources are those whose quantity and quality have been surveyed, determined, and are currently being extracted and consumed using available technology.", 1,
     "Both Statement I and Statement II are correct. Potential resources (e.g. uranium in Ladakh, geothermal energy in Puga) await technology, whereas actual resources are currently mined."),
    ("seq", "Life Cycle of an Exhaustible Non-Renewable Resource (Hubbert Curve)",
     "Arrange the stages of non-renewable fossil fuel exploitation according to the Hubbert bell-shaped production curve:",
     ["Initial discovery and early extraction: rapid exponential growth as easily accessible, shallow reserves are tapped", "Peak Production (Hubbert Peak): maximum extraction rate is reached when approximately half of all recoverable reserves are exhausted", "Post-Peak Deceleration: production begins irreversible terminal decline as remaining reserves become deeper and costlier to extract", "Economic depletion / Abandonment: energy return on investment (EROI) collapses near 1:1, rendering remaining reserves economically unviable"],
     "I -> II -> III -> IV",
     "Hubbert curve progression: discovery boom, peak production, post-peak contraction, and economic exhaustion when EROI collapses."),
    ("mcq", "Energy Return on Investment (EROI)",
     "In energy economics and resource sustainability, 'Energy Return on Investment' (EROI) is the crucial ratio of:",
     "The amount of usable energy delivered from an energy source to the amount of energy expended to discover, extract, and refine that energy",
     ["The monetary price of crude oil divided by gold prices", "The speed of electric electrons flowing through aluminum wires", "The total number of coal miners employed divided by national population"],
     "EROI = Energy Delivered / Energy Invested. Early oil wells yielded EROI > 100:1, whereas unconventional shale and tar sands deliver lower EROI (~5:1 to 10:1)."),
    ("ar", "Maximum Sustainable Yield (MSY) Overharvesting Risk",
     "Managing marine fisheries strictly at the theoretical Maximum Sustainable Yield (MSY) frequently leads to catastrophic population collapse.",
     "MSY models assume static environmental carrying capacity and ignore recruitment fluctuations, climatic shocks (El Niño), and multi-species ecological trophic interactions.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Real ecosystems fluctuate; setting quotas at deterministic MSY leaves zero safety buffer against natural mortality spikes."),
    ("mcq", "Critical Mineral Security in Clean Energy Transition",
     "The global transition to electric vehicles (EVs) and renewable solar-wind grids has escalated international strategic competition for which suite of 'Critical Minerals'?",
     "Lithium, Cobalt, Nickel, Graphite, and Rare Earth Elements (such as Neodymium and Dysprosium)",
     ["Common table salt, granite gravel, and river sand", "Pulverized fly ash, sulfur dioxide, and nitrogen gas", "Animal bone meal and agricultural urea pellets"],
     "Clean energy technologies require vast quantities of critical minerals: lithium and cobalt for batteries, neodymium for wind turbine permanent magnets, and polysilicon for solar PV."),
    ("mcq", "Monazite Sands of Kerala and Thorium Reserves",
     "The coastal beach placer sands of Kerala and Odisha contain vast global reserves of which radioactive mineral that forms the bedrock of India's three-stage nuclear power program?",
     "Monazite (rich in Thorium-232)",
     ["Bauxite (rich in Aluminum)", "Hematite (rich in Iron)", "Cinnabar (rich in Mercury)"],
     "Kerala's monazite beach sands hold nearly 25% of the world's known reserves of Thorium, earmarked for Stage 3 Advanced Heavy Water Reactors (AHWR)."),
    ("match", "Mineral Resources and Major Indian Mining States",
     "Match the mineral resource in List I with its leading producing state in List II:",
     [("A", "Bauxite (Aluminum ore)"),
      ("B", "Iron Ore (Hematite)"),
      ("C", "Copper Ore"),
      ("D", "Mica (Sheet mica)")],
     [("I", "Odisha (Panchpatmali plateau, Koraput)"),
      ("II", "Odisha / Chhattisgarh (Bailadila)"),
      ("III", "Madhya Pradesh (Malanjkhand) / Rajasthan (Khetri)"),
      ("IV", "Andhra Pradesh (Nellore) / Jharkhand (Koderma)")],
     "A-I, B-II, C-III, D-IV",
     "Odisha leads in Bauxite and Iron Ore; MP/Rajasthan lead in Copper; and Andhra/Jharkhand lead in Mica reserves."),
    ("mcq", "Deep Sea Mining Ecological Threat (Clarion-Clipperton Zone)",
     "Environmental oceanographers warn that commercial deep-sea mining of Polymetallic Nodules on the abyssal plains of the Clarion-Clipperton Zone would cause irreversible damage by:",
     "Destroying unique, slow-growing benthic benthic ecosystems, creating massive underwater sediment plumes, and disrupting ocean carbon sequestration",
     ["Heating the ocean water until all marine fish instantly vaporize", "Causing the Moon to crash into the Pacific Ocean", "Freezing all ocean surface waters into solid ice sheets"],
     "Abyssal nodule extraction destroys fragile hydrothermal vent and nodule-dependent benthic fauna, releasing choking sediment plumes across thousands of kilometers."),
    ("mcq", "Overdraft of Groundwater in Northwestern India",
     "In Punjab, Haryana, and Western Rajasthan, dynamic groundwater assessment by the Central Ground Water Board (CGWB) categorizes majority of assessment blocks as:",
     "'Over-Exploited' (where annual groundwater extraction exceeds annual recharge, resulting in long-term water table decline)",
     ["'Safe' with 100% surplus recharge", "'Semi-Critical' with rising water tables", "'Submerged' beneath permanent freshwater lakes"],
     "Over 75% of assessment units in Punjab and Haryana are 'Over-Exploited', extracting more groundwater than natural monsoon recharge can replenish."),
    ("stmt", "Ostrom Eight Design Principles for CPRs",
     "Elinor Ostrom identified eight core design principles for stably managing Common Pool Resources.",
     "These principles include clearly defined boundaries, congruence between appropriation rules and local conditions, collective-choice arrangements, active monitoring, and graduated sanctions.", 1,
     "Both Statement I and Statement II are correct. Ostrom proved that communities prevent CPR collapse when users design, monitor, and enforce their own rules with graduated penalties."),
    ("mcq", "Jevons Paradox in Resource Consumption",
     "In natural resource economics, the 'Jevons Paradox' (rebound effect) observed by William Stanley Jevons demonstrates that:",
     "Technological efficiency gains that reduce the amount of a resource needed for a specific task often lead to an overall increase in total consumption of that resource",
     ["Technological efficiency always eliminates 100% of resource use permanently", "Resource consumption decreases linearly as human population expands", "All energy efficiency technologies cause instantaneous economic collapse"],
     "Jevons observed that Watt's efficient steam engine lowered coal costs, increasing profitability and driving a massive surge in total coal consumption (the rebound effect)."),
    ("seq", "Stages of Community Forest Resource Management under Ostrom Principles",
     "Arrange the institutional steps a village community takes to govern a common forest sustainably:",
     ["Delineating clear physical boundary lines of the community forest and defining authorized community members", "Holding collective assembly meetings to formulate shared rules specifying harvesting seasons, gear, and quotas", "Electing internal community forest monitors to enforce rules and detect unauthorized timber felling", "Applying low-cost, graduated sanctions (warnings, small fines, social censure) against first-time violators"],
     "I -> II -> III -> IV",
     "Ostrom CPR governance: boundary definition, participatory rule-making, community monitoring, and graduated peer sanctions."),
    ("mcq", "Virtual Water Export in Indian Agriculture",
     "Why do environmental hydrologists criticize India's status as the world's largest commercial exporter of Basmati rice and refined sugar?",
     "Because exporting millions of tons of water-guzzling rice and sugarcane effectively amounts to an enormous virtual net export of billions of cubic meters of scarce, depleted groundwater",
     ["Because exporting rice causes all Indian citizens to starve completely", "Because rice exports produce toxic radioactive fly ash in ports", "Because sugarcane exports cause all trains in India to stop running"],
     "Cultivating 1 kg of rice requires ~3,000–5,000 liters of water; exporting rice and sugar from water-stressed regions amounts to exporting precious fossil groundwater reserves."),
    ("mcq", "Recycling Aluminum Energy Savings",
     "Recycling post-consumer scrap aluminum cans saves approximately what percentage of the energy required to produce primary virgin aluminum metal from raw bauxite ore?",
     "Approximately 95% of the energy",
     ["Less than 5% of the energy", "Exactly 0%, recycling consumes more energy", "50% of the energy, but emits pure lead vapors"],
     "Secondary aluminum recycling saves ~95% of the energy required for primary electrolytic smelting (Hall-Héroult process) from bauxite ore.")
]

# ==============================================================================
# Slot 32: Environmental Economics & Externalities (Valuation, Green GDP, Taxes)
# ==============================================================================
s32_raw = [
    ("mcq", "Negative Production Externality Definition",
     "In environmental economics, a 'negative production externality' occurs when:",
     "An industrial manufacturing activity imposes uncompensated environmental or health damage costs on third parties or society, which are not reflected in the market price",
     ["A consumer purchases an organic apple and gives it to a family member", "A beekeeper places beehives near an orchard, increasing fruit pollination for the farmer", "A company earns record profits by reducing its chemical emissions to zero"],
     "Negative externalities (e.g. factory sulfur emissions, chemical river discharge) represent unpriced social costs borne by neighboring communities rather than the producing firm."),
    ("stmt", "Positive Externalities and Under-Provision",
     "A positive externality occurs when an economic activity generates uncompensated beneficial side-effects for third parties (e.g. an orchard owner benefiting from a neighbor's beehives).",
     "In an unregulated free market, goods generating positive externalities are typically under-produced and under-provided relative to the socially optimal level.", 1,
     "Both Statement I and Statement II are correct. Without public subsidies or incentives, private markets fail to supply sufficient quantities of positive-externality goods."),
    ("ar", "Pigouvian Tax Mechanism",
     "A Pigouvian tax is an environmental tax levied on an economic activity that generates negative externalities.",
     "Setting the tax rate exactly equal to the marginal external damage (marginal external cost) forces the polluting firm to internalize the full social cost of production.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Arthur Pigou showed that taxing emissions shifts the private marginal cost curve upward to match social marginal cost."),
    ("match", "Environmental Valuation Methods and Techniques",
     "Match the non-market environmental valuation technique in List I with its operational methodology in List II:",
     [("A", "Contingent Valuation Method (CVM)"),
      ("B", "Hedonic Pricing Method"),
      ("C", "Travel Cost Method (TCM)"),
      ("D", "Replacement Cost Method")],
     [("I", "Survey-based stated preference technique directly asking citizens their Willingness to Pay (WTP) to conserve an ecosystem"),
      ("II", "Revealed preference technique inferring environmental value from property price differentials reflecting air quality or noise"),
      ("III", "Revealed preference method estimating recreational site value based on travel expenses and time spent by visitors"),
      ("IV", "Estimating ecosystem service value based on the engineering cost of constructing artificial infrastructure to replace the service")],
     "A-I, B-II, C-III, D-IV",
     "CVM uses WTP surveys, Hedonic pricing analyzes property prices, Travel Cost assesses tourism expenditure, and Replacement cost prices engineering substitutes."),
    ("mcq", "Coase Theorem and Property Rights",
     "Formulated by Nobel laureate Ronald Coase (1960), the 'Coase Theorem' states that if property rights are clearly defined and transaction costs are negligible:",
     "Private bargaining between the polluter and affected parties will lead to an economically efficient allocation of resources, regardless of who initially holds the property rights",
     ["The government must nationalize all private factories and operate them as public utilities", "Pollution will always increase exponentially until all parties go bankrupt", "The judicial courts must mandate uniform 100% fines on all economic activities"],
     "Coase demonstrated that with zero transaction costs and clear property rights, voluntary bargaining internalizes externalities efficiently without direct regulatory taxation."),
    ("mcq", "Green GDP / Environmental Accounting",
     "How does 'Green Gross Domestic Product' (Green GDP) adjust traditional GDP accounting to reflect ecological reality?",
     "It deducts the economic costs of environmental degradation, resource depletion, and biodiversity loss from traditional GDP",
     ["It adds the total monetary value of all green-colored automobiles manufactured in the country", "It multiplies national GDP by the total square kilometers of forest land", "It excludes all industrial and manufacturing sectors completely"],
     "Green GDP = Traditional GDP - Environmental Degradation Costs - Natural Resource Depletion, measuring true sustainable wealth generation."),
    ("stmt", "Willingness to Pay (WTP) vs Willingness to Accept (WTA)",
     "In non-market environmental valuation, Willingness to Pay (WTP) measures the maximum amount an individual would pay to secure an environmental improvement.",
     "Willingness to Accept (WTA) measures the minimum financial compensation an individual would require to endure a specific environmental deterioration.", 1,
     "Both Statement I and Statement II are correct. Behavioral economics shows WTA consistently exceeds WTP due to loss aversion and endowment effects."),
    ("seq", "Step-by-Step Execution of an Environmental Cost-Benefit Analysis (CBA)",
     "Arrange the sequential analytical steps in conducting a formal Environmental Cost-Benefit Analysis for a proposed infrastructure project:",
     ["Identification of all direct financial costs and social/environmental externalities over the project lifespan", "Monetary valuation of non-market environmental impacts using techniques like CVM, Hedonic pricing, and Travel Cost", "Discounting future flows of costs and environmental benefits to their Present Value using an appropriate social discount rate", "Calculating the Net Present Value (NPV = Present Value of Benefits - Present Value of Costs) and Benefit-Cost Ratio (BCR)"],
     "I -> II -> III -> IV",
     "CBA sequence: impact identification, non-market valuation, discounting to present value, and net present value calculation."),
    ("mcq", "Social Discount Rate Dilemma in Climate Economics",
     "In climate change economics, why did the 'Stern Review on the Economics of Climate Change' (2006) use an exceptionally low social discount rate (approx. 1.4%)?",
     "Because a high discount rate heavily discounts catastrophic future damages (50–100 years away) to near-zero present value, morally violating intergenerational equity",
     ["Because banks in the UK had zero interest rates in 2006", "Because low discount rates make all coal power plants appear 100% pollution-free", "Because discount rates can never mathematically exceed 1.5%"],
     "Nicholas Stern argued for an ethical, low discount rate (~1.4%) so that catastrophic future impacts on future generations carry substantial moral and economic weight today."),
    ("ar", "Payment for Ecosystem Services (PES) Incentive",
     "Payment for Ecosystem Services (PES) programs create market incentives for environmental conservation.",
     "Upstream forest stewards and watershed landowners are financially compensated by downstream water users (cities, hydroelectric plants) for maintaining forest cover that filters water.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). PES (e.g. Costa Rica's Pagos por Servicios Ambientales) compensates resource managers for positive conservation externalities."),
    ("mcq", "Carbon Tax vs Cap-and-Trade Systems",
     "In climate policy, what is the fundamental functional distinction between a 'Carbon Tax' and an 'Emissions Trading Scheme' (Cap-and-Trade)?",
     "A Carbon Tax fixes the price of carbon emissions while leaving the quantity of emissions reductions uncertain; Cap-and-Trade fixes the maximum quantity cap of emissions while leaving the carbon allowance price to market trading",
     ["A Carbon Tax is paid exclusively in physical coal lumps, while Cap-and-Trade is paid in gold", "A Carbon Tax applies only to agricultural tractors, while Cap-and-Trade applies only to bicycles", "There is zero difference; both terms represent identical corporate income taxes"],
     "Carbon tax = price certainty, quantity uncertainty; Cap-and-Trade = quantity certainty (fixed emissions cap), price determined by supply and demand."),
    ("mcq", "Use Value vs Non-Use Value in Total Economic Value (TEV)",
     "In the Total Economic Value (TEV) framework of environmental assets, which of the following is categorized as a 'Non-Use Value'?",
     "Existence Value (the utility derived simply from knowing that species like the Blue Whale or Snow Leopard exist, without ever intending to see or use them)",
     ["Direct consumptive harvesting of timber for furniture", "Recreational ecotourism boating on a mountain lake", "Direct medicinal collection of herbal bark for pharmaceuticals"],
     "Non-use values include Existence value (satisfaction that nature exists) and Bequest value (preserving nature for future generations), distinct from direct/indirect use values."),
    ("match", "Ecosystem Services Categories (Millennium Ecosystem Assessment)",
     "Match the Millennium Ecosystem Assessment (MEA 2005) service category in List I with its ecological example in List II:",
     [("A", "Provisioning Services"),
      ("B", "Regulating Services"),
      ("C", "Cultural Services"),
      ("D", "Supporting Services")],
     [("I", "Freshwater, food crops, timber, medicinal plants, and genetic resources"),
      ("II", "Climate regulation, carbon sequestration, flood control, water purification, and pollination"),
      ("III", "Spiritual inspiration, aesthetic enjoyment, cognitive development, and ecotourism"),
      ("IV", "Soil formation, primary biomass production, and biogeochemical nutrient cycling")],
     "A-I, B-II, C-III, D-IV",
     "Provisioning yields tangible goods; Regulating maintains environmental balances; Cultural provides spiritual/aesthetic benefits; and Supporting sustains fundamental life-support cycles."),
    ("mcq", "Opportunity Cost in Forest Conservation",
     "When a government designates a virgin forest tract as an inviolate National Park, the 'Opportunity Cost' of that conservation decision represents:",
     "The forgone economic benefits that could have been generated if the land had been converted into commercial open-cast mining, timber logging, or agricultural estates",
     ["The monetary salary paid to national park forest guards", "The cost of building high-voltage electric perimeter fences", "The total tourist entry ticket revenue collected annually"],
     "Opportunity cost is the value of the best alternative forgone: by choosing conservation, society sacrifices the commercial revenue from mining or logging."),
    ("mcq", "Robert Costanza Global Ecosystem Services Valuation",
     "In their landmark 1997 Nature paper, ecological economist Robert Costanza and colleagues shocked conventional economists by estimating the average annual global economic value of all planetary ecosystem services at:",
     "$33 trillion per year (nearly double the entire global Gross National Product of $18 trillion at the time)",
     ["$50 million per year", "$100 billion per year", "$100 trillion every single day"],
     "Costanza's team calculated global ecosystem services at ~$33 trillion/year (updated in 2014 to $125–145 trillion/year), proving nature's economic contribution dwarfs conventional GDP."),
    ("stmt", "Pollution Havens Hypothesis",
     "The 'Pollution Haven Hypothesis' posits that multinational corporations in highly polluting industries tend to relocate manufacturing facilities from developed countries to developing nations.",
     "Developing nations with lower income levels often maintain weaker environmental standards and lax regulatory enforcement to attract foreign direct investment.", 1,
     "Both Statement I and Statement II are correct. The hypothesis warns of a 'race to the bottom' where developing economies accept heavy industrial pollution in exchange for industrial employment."),
    ("mcq", "Border Carbon Adjustment (BCA / CBAM)",
     "The European Union's 'Carbon Border Adjustment Mechanism' (CBAM) imposes an environmental tariff on carbon-intensive imports (steel, cement, aluminum, fertilizers) entering the EU to:",
     "Prevent 'carbon leakage' by ensuring imported goods pay a carbon price equivalent to domestic EU manufacturers under the EU Emissions Trading System",
     ["Fund the construction of space telescopes in South America", "Ban all international maritime cargo vessels from entering European waters", "Subsidize the extraction of coal inside European national parks"],
     "CBAM levels the playing field: non-EU manufacturers with high carbon footprints must pay carbon border taxes, incentivizing global decarbonization."),
    ("seq", "Contingent Valuation Method (CVM) Survey Protocol",
     "Arrange the methodological steps followed by environmental economists conducting a CVM study to value a threatened wetland:",
     ["Drafting a detailed hypothetical policy scenario describing the wetland and the specific ecosystem improvements proposed", "Selecting a statistically representative random sample of households within the beneficiary population", "Administering survey interviews eliciting individual maximum Willingness to Pay (WTP) using dichotomous-choice referendum bidding", "Statistical econometric analysis aggregating individual WTP across all households to derive the total economic value of the wetland"],
     "I -> II -> III -> IV",
     "CVM workflow: scenario design, representative sampling, WTP survey elicitation (bid format), and econometric aggregation of total social value."),
    ("mcq", "Ecological Economics vs Environmental Economics",
     "How does 'Ecological Economics' (Herman Daly, Robert Costanza) differ fundamentally from neoclassical 'Environmental Economics'?",
     "Ecological economics views the human macro-economy as an open subsystem embedded entirely within a finite, physically constrained global ecosystem, rather than viewing the environment merely as an external factor of production",
     ["Ecological economics advocates maximizing coal burning to accelerate industrial growth", "Ecological economics rejects all scientific biology and focuses only on paper currencies", "There is zero difference; both terms are identical neoclassical branches"],
     "Environmental economics applies neoclassical market tools to pollution; Ecological economics recognizes thermodynamic limits, viewing the economy as an embedded subsystem of the biosphere."),
    ("mcq", "Bequest Value Definition",
     "In the economic valuation of biodiversity, 'Bequest Value' is formally defined as the economic value derived from:",
     "The satisfaction of preserving pristine natural ecosystems and endangered species so that future generations will inherit and experience them",
     ["The monetary profit earned from harvesting timber tomorrow morning", "The insurance payout received after a forest fire burns a national park", "The price paid for purchasing commercial mineral extraction licenses"],
     "Bequest value reflects intergenerational altruism: the willingness of present citizens to pay to pass on intact natural heritage to unborn generations.")
]

# ==============================================================================
# Slot 33: Non-Renewable Energy Resources (Coal, Petroleum, Natural Gas)
# ==============================================================================
s33_raw = [
    ("mcq", "Ranks of Coal by Carbon Content and Calorific Value",
     "Arrange the geological ranks of coal in descending order of their carbon content, geological age, and calorific heat value (from highest quality to lowest):",
     "Anthracite -> Bituminous -> Lignite -> Peat",
     ["Peat -> Lignite -> Bituminous -> Anthracite", "Lignite -> Anthracite -> Peat -> Bituminous", "Bituminous -> Lignite -> Anthracite -> Peat"],
     "Anthracite has highest carbon (>90%), Bituminous (75–85%), Lignite brown coal (60–70%), and Peat is initial uncompressed organic precursor (<60%)."),
    ("stmt", "Gondwana vs Tertiary Coal Reserves in India",
     "Over 98% of India's commercial coal production originates from ancient Permian Gondwana coalfields situated in river valleys (Damodar, Mahanadi, Son, Godavari).",
     "Tertiary coal deposits (approximately 55 million years old) are found in Northeastern states (Assam, Meghalaya, Arunachal Pradesh) and are characterized by high sulfur content.", 1,
     "Both Statement I and Statement II are correct. Gondwana coal (Jharkhand, Odisha, WB) is low-sulfur bituminous; Tertiary coal (NE India) has high sulfur, producing acidic fumes."),
    ("ar", "Jharia Coalfield Underground Mine Fires",
     "The Jharia coalfield in Dhanbad district, Jharkhand, has been burning continuously with subterranean underground mine fires for over a century.",
     "Unregulated historical opencast and bord-and-pillar mining left abandoned underground voids where exposed coal seams undergo spontaneous combustion upon contact with atmospheric oxygen.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Spontaneous coal oxidation in unsealed underground galleries has fueled continuous subterranean fires since 1916, causing subsidence and toxic fumes."),
    ("match", "Fossil Fuels and Chemical Compositions",
     "Match the fossil fuel in List I with its primary hydrocarbon chemical component in List II:",
     [("A", "Natural Gas"),
      ("B", "Liquefied Petroleum Gas (LPG)"),
      ("C", "Compressed Natural Gas (CNG)"),
      ("D", "Biogas")],
     [("I", "Methane (CH4, approx. 70–90%)"),
      ("II", "Propane (C3H8) and Butane (C4H10) compressed under moderate pressure"),
      ("III", "Methane (CH4) compressed to 200–250 bar pressure for vehicular transport"),
      ("IV", "Methane (55–70%) mixed with Carbon Dioxide (30–45%) from anaerobic digestion")],
     "A-I, B-II, C-III, D-IV",
     "Natural gas and CNG are predominantly methane (CH4); LPG is propane/butane; and biogas is biologically generated methane and CO2."),
    ("mcq", "Acid Mine Drainage (AMD) Chemistry",
     "Acid Mine Drainage (AMD) from abandoned coal and metal mines severely contaminates surrounding river basins with orange-red acidic runoff (pH < 3.0) because:",
     "Pyrite (Iron Disulfide, FeS2) minerals exposed to air and water during mining oxidize into sulfuric acid (H2SO4) and soluble heavy metals, catalyzed by Acidithiobacillus ferrooxidans bacteria",
     ["Underground coal workers pour thousands of gallons of battery acid into mine shafts", "Coal burns underground turning all water into liquid hydrochloric acid", "Granite bedrock dissolves spontaneously into pure nitric acid"],
     "Oxidation of pyrite: 2FeS2 + 7O2 + 2H2O -> 2Fe(2+) + 4SO4(2-) + 4H+. This generates sulfuric acid that leaches toxic heavy metals into streams, coating rocks in orange 'yellow boy'."),
    ("mcq", "Petroleum Refining Fractional Distillation",
     "In crude oil refining, fractional distillation separates complex petroleum mixtures into distinct commercial products based on differences in their:",
     "Boiling point temperatures and hydrocarbon molecular chain lengths",
     ["Magnetic susceptibility and electrical conductance", "Visual color and opacity under ultraviolet light", "Radioactive half-life decay rates"],
     "Fractional distillation heats crude oil: light vapors with low boiling points (LPG, petrol) rise to the top of the tower, while heavier fractions (diesel, asphalt) condense lower down."),
    ("stmt", "Hydraulic Fracturing (Fracking) for Shale Gas",
     "Shale gas is unconventional natural gas trapped within deep, low-permeability organic shale rock formations.",
     "Extracting shale gas requires hydraulic fracturing ('fracking') and horizontal drilling, which consumes millions of liters of water and chemical additives, risking groundwater contamination and induced earthquakes.", 1,
     "Both Statement I and Statement II are correct. Fracking injects pressurized water, sand, and chemicals to fracture shale, carrying risks of methane migration and wastewater disposal."),
    ("seq", "Fractional Distillation Column Product Separation from Top to Bottom",
     "Arrange the petroleum refining fractions in order of increasing boiling point (from the top of the distillation column to the bottom residue):",
     ["Petroleum gases (LPG: Propane, Butane; boiling below 40 degrees Celsius)", "Petrol / Gasoline (C5–C10; boiling between 40 and 175 degrees Celsius)", "Kerosene and Aviation Turbine Fuel (C10–C16; boiling between 175 and 275 degrees Celsius)", "Diesel oil and Fuel oils (C16–C20; boiling between 250 and 350 degrees Celsius)", "Bitumen and Asphalt residue (C20+; non-volatile bottoms above 350 degrees Celsius)"],
     "I -> II -> III -> IV -> V",
     "Distillation column top-to-bottom: light petroleum gases, gasoline, kerosene, diesel/fuel oil, and residual asphalt/bitumen."),
    ("mcq", "Deepwater Horizon Gulf of Mexico Oil Spill (2010)",
     "The 2010 Deepwater Horizon disaster in the Gulf of Mexico (the largest marine oil spill in petroleum history) released over 4 million barrels of crude oil due to:",
     "A high-pressure methane gas blowout that exploded the offshore drilling rig, rupturing the deep-sea wellhead at 1,500 meters water depth",
     ["A direct collision between two massive commercial oil tankers", "An intentional terrorist bombing of a coastal refinery", "A magnitude 9.0 tsunami crashing onto the Florida coastline"],
     "The BP Deepwater Horizon blowout killed 11 workers and gushed crude for 87 days at the seafloor, devastating coastal marshes, pelagic fisheries, and marine wildlife."),
    ("ar", "Exxon Valdez Oil Spill and Double-Hull Tanker Mandate",
     "The 1989 Exxon Valdez oil spill in Prince William Sound, Alaska, catalyzed an international regulatory overhaul of maritime oil transport.",
     "The US Oil Pollution Act of 1990 and IMO regulations mandated the phased elimination of single-hull oil tankers in favor of double-hull tanker construction.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Double hulls provide an outer buffer space that prevents cargo tank breach during low-energy grounding or collision."),
    ("mcq", "Coalbed Methane (CBM) in India",
     "Coalbed Methane (CBM) is an unconventional natural gas resource stored within coal seams, held in place by:",
     "Adsorption onto the solid matrix of coal under subterranean hydrostatic water pressure",
     ["Liquid synthetic plastics poured into mine tunnels", "Deep underground frozen permafrost ice blocks", "Magmatic chambers beneath active volcanic islands"],
     "CBM is absorbed onto the internal micropore surfaces of coal under water pressure; de-watering the coal seam releases clean methane gas."),
    ("mcq", "Lignite Mining and Neyveli Complex",
     "India's largest reserves and opencast mining operations of brown coal ('Lignite') are situated at Neyveli in which southern state?",
     "Tamil Nadu",
     ["Kerala", "Karnataka", "Andhra Pradesh"],
     "Neyveli in Cuddalore district, Tamil Nadu, holds India's largest lignite deposits, operated by NLC India Limited for pithead thermal power generation."),
    ("match", "Fossil Fuel Emissions and Specific Environmental Damages",
     "Match the fossil fuel combustion byproduct in List I with its primary damage mechanism in List II:",
     [("A", "Sulfur Dioxide (SO2) from coal"),
      ("B", "Nitrogen Oxides (NOx) from diesel"),
      ("C", "Carbon Dioxide (CO2) from all fossil fuels"),
      ("D", "Black Carbon Soot Particulates")],
     [("I", "Acid rain formation (H2SO4) and corrosion of historical architecture"),
      ("II", "Ground-level photochemical smog, tropospheric ozone, and PAN formation"),
      ("III", "Enhanced greenhouse effect, global warming, and ocean acidification"),
      ("IV", "Direct inhalation toxicity, atmospheric warming, and accelerated glacier melting when deposited on snow")],
     "A-I, B-II, C-III, D-IV",
     "SO2 causes acid rain; NOx forms smog/ozone; CO2 drives global climate change; and black carbon accelerates Himalayan glacier melting by reducing albedo."),
    ("mcq", "Tar Sands (Oil Sands) Environmental Footprint",
     "The commercial extraction of synthetic crude oil from the Athabasca 'Tar Sands' in Alberta, Canada, is considered one of the most carbon-intensive and ecologically destructive energy operations because:",
     "It requires open-pit strip mining of pristine boreal forests and consumes enormous volumes of natural gas and water to thermally separate viscous bitumen from sand",
     ["It involves zero human labor and produces zero greenhouse emissions", "It releases pure oxygen that cools the Arctic polar ice sheet", "It transforms sand into solid titanium metal without energy"],
     "Tar sands extraction strips ancient boreal forests, produces toxic tailings ponds, and generates up to 3 times more lifecycle greenhouse emissions than conventional light crude."),
    ("mcq", "Natural Gas Methane Leaks (Fugitive Emissions)",
     "Why do atmospheric scientists emphasize that 'Fugitive Methane Emissions' leaking from natural gas pipelines, compressors, and wellheads can negate the climate benefit of switching from coal to gas?",
     "Because Methane (CH4) is an exceptionally potent greenhouse gas with a Global Warming Potential (GWP) nearly 84 times greater than CO2 over a 20-year timescale",
     ["Because methane transforms into solid ice in the atmosphere", "Because methane destroys all electrical power generation equipment", "Because methane attracts swarms of desert locusts to cities"],
     "If more than ~2.5–3% of natural gas escapes as unburnt fugitive methane along the supply chain, its high GWP (84x over 20 years) cancels out the carbon benefit of replacing coal."),
    ("stmt", "Strategic Petroleum Reserves (SPR) of India",
     "India established underground Strategic Petroleum Reserves (SPR) to protect against global crude oil supply disruptions and geopolitical shocks.",
     "The Indian Strategic Petroleum Reserves Limited (ISPRL) maintains subterranean unlined underground rock caverns at Visakhapatnam (AP), Mangaluru (Karnataka), and Padur (Karnataka).", 1,
     "Both Statement I and Statement II are correct. Strategic underground rock caverns store ~5.33 million metric tons of crude, providing ~9.5 days of national consumption buffer."),
    ("mcq", "Rat-Hole Mining in Meghalaya Hazards",
     "The primitive and hazardous coal mining practice of 'Rat-Hole Mining' in Meghalaya (banned by the National Green Tribunal in 2014) involves:",
     "Digging narrow vertical pits (3 to 4 feet wide) into hillsides through which miners, often children, crawl horizontally to extract thin coal seams, risking cave-ins and flooding",
     ["Using advanced automated laser robotics to excavate mountain tunnels", "Employing trained laboratory rats to carry coal nuggets out of mines", "Drilling deep-sea offshore oil platforms in the Brahmaputra river"],
     "Rat-hole mining violates human safety and environmental laws, polluting rivers with acid mine drainage and causing fatal entrapments during sudden monsoon cave-ins."),
    ("seq", "Geological Genesis of Coal from Ancient Swamp Flora",
     "Arrange the stages of geological coalification over hundreds of millions of years under heat and pressure:",
     ["Dense ancient swamp forests and giant lycophyte ferns die, accumulating in stagnant, oxygen-poor water basins", "Partial microbial decomposition in anaerobic mire forms spongy, high-moisture 'Peat'", "Burial beneath thousands of meters of sedimentary rock compresses peat into brown, soft 'Lignite'", "Intense tectonic thermal maturation and overburden pressure convert lignite into hard 'Bituminous' and finally metamorphic 'Anthracite' coal"],
     "I -> II -> III -> IV",
     "Coal formation: swamp accumulation, anaerobic peat formation, sedimentary compression into lignite, and thermal maturation into bituminous/anthracite."),
    ("mcq", "Coal Gasification and Fischer-Tropsch Synthesis",
     "The chemical conversion process of 'Coal Gasification' followed by 'Fischer-Tropsch synthesis' transforms solid coal into clean synthetic fuels by:",
     "Reacting pulverized coal with oxygen and steam at high temperatures to produce synthesis gas (Syngas: CO + H2), which is catalytically converted into synthetic diesel or methanol",
     ["Dissolving coal in water with table salt and drinking it directly", "Freezing coal with dry ice to make diamonds at room temperature", "Exposing coal to acoustic music to induce chemical fission"],
     "Coal gasification generates Syngas (CO + H2); catalytic Fischer-Tropsch synthesis condenses Syngas into liquid transportation fuels (coal-to-liquids CTL)."),
    ("mcq", "Coal Ash Pond Failure and Heavy Metal Spills",
     "When earthen dikes of wet 'Coal Ash Ponds' breach or overflow during torrential rains at thermal power stations, what is the primary environmental catastrophe?",
     "Catastrophic slurry floods smother adjacent farmland and rivers with toxic heavy metals (including Arsenic, Lead, Mercury, Selenium, and Cadmium) that poison aquatic life and drinking water",
     ["The ash pond immediately cools down the surrounding country by 50 degrees", "The fly ash transforms into fertile organic compost that triples crop yields overnight", "The ash pond begins emitting pure helium gas that floats into the clouds"],
     "Wet ash dyke breaches (such as the Fly Ash disaster at Singrauli or NTPC plants) release millions of tons of heavy metal sludge, burying farmland and contaminating drinking rivers.")
]

# ==============================================================================
# Slot 34: Renewable Energy Technologies (Solar, Wind, Hydro, Biogas, Geothermal)
# ==============================================================================
s34_raw = [
    ("mcq", "Photovoltaic (PV) Effect Principle",
     "In a solar photovoltaic (PV) cell, direct conversion of sunlight into electricity occurs via the 'Photovoltaic Effect', wherein:",
     "Incident photons with energy greater than the bandgap of a semiconductor (like silicon) excite electrons across the p-n junction, generating an electric direct current (DC)",
     ["Sunlight boils water inside micro-tubes to turn miniature steam turbines", "Solar heat causes chemical combustion of hydrogen gas stored in glass panels", "Ultraviolet rays split silicon atoms through controlled nuclear fission"],
     "Solar PV cells absorb solar photons, freeing electron-hole pairs across a semiconductor p-n junction to generate direct current (DC) electricity."),
    ("stmt", "International Solar Alliance (ISA) Headquarters and Mandate",
     "The International Solar Alliance (ISA) was jointly launched by India and France in November 2015 at COP21 in Paris.",
     "The ISA is headquartered at the National Institute of Solar Energy (NISE) in Gurugram, Haryana, representing the first intergovernmental treaty-based organization headquartered in India.", 1,
     "Both Statement I and Statement II are correct. ISA unites sunshine countries ('Suryaputras') between the Tropics of Cancer and Capricorn to scale up solar energy globally."),
    ("ar", "Wind Power Density Cubic Velocity Relationship",
     "The electrical power output generated by a modern wind turbine increases dramatically with wind speed, obeying a cubic velocity relationship ($P \\propto v^3$).",
     "The kinetic energy flux passing through the swept area of turbine blades per second is proportional to the mass flow rate multiplied by the square of velocity, yielding a cubic function of wind velocity ($P = \\frac{1}{2} \\rho A v^3$).", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Doubling wind speed increases theoretical wind power output eight-fold (2^3 = 8), making high-wind sites exceptionally productive."),
    ("match", "Renewable Energy Sources and Operating Physics",
     "Match the renewable energy technology in List I with its operational energy conversion principle in List II:",
     [("A", "Solar Photovoltaic (PV)"),
      ("B", "Solar Thermal / CSP"),
      ("C", "Wind Turbine Generator"),
      ("D", "Ocean Thermal Energy Conversion (OTEC)")],
     [("I", "Direct solid-state conversion of photons to direct current electricity via semiconductor p-n junction"),
      ("II", "Mirrors (heliostats / parabolic troughs) concentrate sunlight to heat thermal fluid, generating steam to drive a turbine"),
      ("III", "Aerodynamic lift forces rotate air-foil blades, driving a gearbox and synchronous magnetic generator"),
      ("IV", "Exploiting temperature difference (minimum 20 degrees Celsius) between warm surface seawater and cold deep ocean water to vaporize low-boiling fluid")],
     "A-I, B-II, C-III, D-IV",
     "PV converts light to DC; CSP concentrates solar heat for steam turbines; Wind uses aerodynamic lift; and OTEC exploits vertical ocean thermal gradients."),
    ("mcq", "Muppandal Wind Farm Significance",
     "The Muppandal Wind Farm, one of the largest onshore operational wind power complexes in the world with over 1,500 MW capacity, is located in which Indian district?",
     "Kanyakumari district, Tamil Nadu",
     ["Jaisalmer district, Rajasthan", "Kutch district, Gujarat", "Satara district, Maharashtra"],
     "Muppandal in Kanyakumari, Tamil Nadu, exploits powerful seasonal monsoon winds channeled through the mountain gap of the Western Ghats."),
    ("mcq", "PM-KUSUM Scheme for Farmers",
     "The Government of India's flagship 'PM-KUSUM' scheme (Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan) promotes agricultural energy independence by:",
     "Providing financial subsidies to install standalone off-grid solar irrigation pumps and solarize existing grid-connected agriculture pumps, allowing farmers to sell surplus power",
     ["Mandating that farmers burn diesel generators 24 hours a day", "Confiscating agricultural farmland to build commercial thermal coal plants", "Replacing all crops with solar glass roofs"],
     "PM-KUSUM de-dieselizes agriculture: it funds standalone solar pumps, solarizes grid pumps, and allows farmers to generate solar electricity on barren lands to feed into the grid."),
    ("stmt", "Small Hydro vs Large Hydro Environmental Impacts",
     "Large hydroelectric projects (>25 MW) often cause severe ecological impacts, including submergence of forests, displacement of tribal populations, and seismic hazards.",
     "Small Hydro Power (SHP, up to 25 MW), particularly run-of-the-river designs, involves minimal water storage, causing significantly lower social and environmental disruption.", 1,
     "Both Statement I and Statement II are correct. Run-of-the-river small hydro diverts stream flow through a penstock without massive reservoir inundation."),
    ("seq", "Process Flow of Anaerobic Biogas Digestion (SATAT Initiative)",
     "Arrange the four biochemical stages of anaerobic microbial digestion converting cattle dung into Compressed Bio-Gas (CBG):",
     ["Hydrolysis: hydrolytic enzymes break complex insoluble biopolymers (cellulose, lipids) into simple soluble monomers (sugars, amino acids)", "Acidogenesis: acid-forming bacteria ferment simple monomers into volatile fatty acids (VFAs), alcohols, and lactic acid", "Acetogenesis: acetogenic bacteria convert volatile fatty acids into acetic acid, hydrogen gas, and carbon dioxide", "Methanogenesis: strictly anaerobic methanogenic archaea (Methanobacterium) convert acetic acid and H2/CO2 into clean Methane gas (CH4)"],
     "I -> II -> III -> IV",
     "Biogas digestion follows 4 biochemical phases: Hydrolysis -> Acidogenesis -> Acetogenesis -> Methanogenesis, producing methane fuel."),
    ("mcq", "Geothermal Energy Potential in India (Puga Valley)",
     "Where is India's most promising geothermal energy field located, where ONGC is executing India's first commercial geothermal power generation project tapping subterranean volcanic steam?",
     "Puga Valley, Eastern Ladakh",
     ["Thar Desert, Rajasthan", "Sundarbans delta, West Bengal", "Rann of Kutch, Gujarat"],
     "Puga Valley in Ladakh sits along the collision suture of the Indian and Asian tectonic plates, venting boiling geothermal springs and steam (>160 C) at 4,400 meters altitude."),
    ("ar", "Intermittency and Battery Energy Storage Systems (BESS)",
     "Massive integration of solar and wind energy into national electrical grids requires grid-scale Battery Energy Storage Systems (BESS) or Pumped Hydro Storage.",
     "Solar and wind power generation are inherently intermittent and variable, fluctuating with day-night cycles, cloud cover, and seasonal wind patterns.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Grid stability requires storage to balance the mismatch between peak solar generation (noon) and peak consumer demand (evening)."),
    ("mcq", "Betz Limit in Wind Turbine Aerodynamics",
     "In wind energy engineering, what is the theoretical maximum aerodynamic efficiency (the 'Betz Limit') that any wind turbine can extract from the kinetic energy of the wind?",
     "59.3% (or 16/27 of total wind kinetic energy)",
     ["100% of all wind energy", "Exactly 25%", "90.5%"],
     "Formulated by German physicist Albert Betz in 1919, the Betz limit dictates that no wind turbine can capture more than 59.3% of the wind's kinetic energy without stopping airflow."),
    ("mcq", "Compressed Bio-Gas (CBG) under SATAT Scheme",
     "Under the Ministry of Petroleum's 'SATAT' (Sustainable Alternative Towards Affordable Transportation) initiative, Compressed Bio-Gas (CBG) is produced for vehicular transport by:",
     "Purifying raw biogas to remove CO2 and H2S (achieving > 90% methane purity) and compressing it to 200–250 bar, chemically identical to fossil CNG",
     ["Burning raw cattle dung directly inside automobile fuel tanks", "Converting sugarcane molasses into radioactive atomic isotopes", "Mixing raw sewage directly with commercial aviation fuel"],
     "SATAT establishes commercial CBG plants: raw biogas is scrubbed of CO2 and sulfur to reach >90% methane, compressed to 250 bar, and sold through retail fuel pumps as green CNG."),
    ("match", "Solar Technologies and Components",
     "Match the solar technology in List I with its characteristic technical feature in List II:",
     [("A", "Monocrystalline Silicon PV"),
      ("B", "Polycrystalline Silicon PV"),
      ("C", "Perovskite Solar Cells"),
      ("D", "Parabolic Trough CSP")],
     [("I", "Highest commercial efficiency (20–24%), uniform black appearance, cut from single continuous crystal ingots"),
      ("II", "Moderate efficiency (15–18%), speckled blue appearance, manufactured from melted multi-grain silicon fragments"),
      ("III", "Emerging crystalline material with ABX3 crystal structure offering high lab efficiency and low-cost roll-to-roll manufacturing"),
      ("IV", "U-shaped curved parabolic mirrors focusing sunlight onto a receiver tube filled with synthetic thermal oil")],
     "A-I, B-II, C-III, D-IV",
     "Mono-Si is efficient black single crystal; Poly-Si is blue multi-crystal; Perovskites offer next-gen efficiency; and Parabolic troughs are solar thermal concentrators."),
    ("mcq", "Bhadla Solar Park Record",
     "Covering over 14,000 acres in Jodhpur district, Rajasthan, which mega-installation is celebrated as one of the largest single operational solar parks in the world with over 2,245 MW capacity?",
     "Bhadla Solar Park",
     ["Pavagada Solar Park", "Kurnool Solar Park", "Rewa Solar Park"],
     "Bhadla Solar Park in Rajasthan operates across scorching desert lands with exceptionally high solar insolation, generating over 2,245 MW of clean electricity."),
    ("mcq", "Pumped Storage Hydropower (PSH) Mechanism",
     "How does a 'Pumped Storage Hydropower' (PSH) facility function as an enormous, rechargeable 'water battery' on electrical grids?",
     "Surplus cheap electricity during off-peak hours pumps water from a lower reservoir to an upper reservoir; during peak demand, water is released down through turbines to generate power",
     ["It uses chemical sulfuric acid to melt mountain rock into electrical current", "It freezes water into ice cubes during peak hours and boils them at night", "It uses radioactive uranium to evaporate water into clouds"],
     "PSH stores potential energy: surplus off-peak solar/wind pumps water uphill, and gravity-fed hydro turbines discharge during peak evening demand with ~75–80% round-trip efficiency."),
    ("stmt", "Ocean Thermal Energy Conversion (OTEC) Closed-Cycle",
     "Closed-cycle Ocean Thermal Energy Conversion (OTEC) utilizes a working fluid with a low boiling point, such as liquid ammonia.",
     "Warm surface seawater (25 degrees Celsius) evaporates the liquid ammonia into high-pressure vapor to drive a turbine, while cold deep ocean water (5 degrees Celsius) condensed it back to liquid.", 1,
     "Both Statement I and Statement II are correct. OTEC exploits vertical temperature gradients (minimum 20 C) in tropical oceans to operate continuous baseload thermal power cycles."),
    ("mcq", "Floating Solar Photovoltaic (FSPV) Advantages",
     "Installing 'Floating Solar PV' panels on reservoirs and irrigation canals (such as the 100 MW floating solar project at Ramagundam, Telangana) provides which dual environmental benefits?",
     "Conserves valuable terrestrial land, reduces water evaporative losses from the reservoir, while the natural water cooling effect increases solar panel electrical efficiency",
     ["Eliminates all fish from the reservoir and turns freshwater into saltwater", "Increases water evaporation by 500% to create local rainstorms", "Absorbs all gravitational forces above the reservoir"],
     "Floating solar saves agricultural land, shades water surfaces to suppress reservoir evaporation, and natural evaporative cooling lowers panel temperatures, boosting solar cell efficiency."),
    ("seq", "Process of Offshore Wind Energy Generation and Transmission",
     "Arrange the sequential operational stages of an offshore marine wind energy system:",
     ["Deep-sea anchored floating foundations or seabed monopile foundations secure giant 15 MW wind turbines in open ocean wind corridors", "Oceanic winds rotate aerodynamic carbon-fiber blades, driving permanent magnet synchronous generators", "Generated alternating current (AC) is stepped up by an offshore collector substation and converted into High-Voltage Direct Current (HVDC)", "Subsea armored submarine power cables transmit high-voltage clean electricity to onshore grid interconnect substations"],
     "I -> II -> III -> IV",
     "Offshore wind workflow: marine foundation anchoring, turbine aerodynamic rotation, offshore HVDC transformation, and subsea cable transmission to shore."),
    ("mcq", "National Green Hydrogen Mission Targets",
     "Approved by the Union Cabinet in 2023 with an outlay of Rs. 19,744 crore, India's 'National Green Hydrogen Mission' aims to produce at least how much green hydrogen per annum by 2030?",
     "5 Million Metric Tonnes (MMT) per annum, supported by 125 GW of dedicated renewable energy capacity",
     ["100 kilograms per year", "500 billion tons every month", "Zero hydrogen, as hydrogen is banned"],
     "The Green Hydrogen Mission aims for 5 MMT/year by 2030, decarbonizing hard-to-abate sectors (steel, fertilizers, refineries) via renewable water electrolysis."),
    ("mcq", "Pelamis and Oscillating Water Column (Wave Energy)",
     "In marine wave energy conversion, an 'Oscillating Water Column' (OWC) device (such as the pilot plant at Vizhinjam, Kerala) generates electricity by:",
     "Rising and falling ocean waves act like a piston inside an enclosed submerged chamber, forcing air back and forth through a bidirectional Wells air turbine",
     ["Collecting wave foam and burning it in diesel engines", "Freezing wave crests into solid ice blocks that float ashore", "Using magnets attached to wild dolphins to turn underwater dynamos"],
     "OWC wave energy captures water level oscillations in a hollow chamber; moving air drives a specialized Wells turbine that rotates in the same direction regardless of airflow direction.")
]

# ==============================================================================
# Slot 35: Nuclear Energy & Radiation Hazards (Fission, Three-Stage, Accidents)
# ==============================================================================
s35_raw = [
    ("mcq", "Nuclear Fission Energy Mechanism",
     "In a commercial nuclear fission power reactor, electricity is generated through the splitting of heavy atomic nuclei (such as Uranium-235) induced by the capture of:",
     "Thermal (slow) neutrons, releasing enormous thermal kinetic energy, fission fragments, and 2 to 3 secondary neutrons",
     ["High-energy microwave radiation pulses", "High-pressure sonic sound waves", "Liquid chemical kerosene sparks"],
     "U-235 captures a thermal neutron, undergoing fission into barium, krypton, 2-3 neutrons, and ~200 MeV of thermal energy, which boils water to turn steam turbines."),
    ("stmt", "Homi Bhabha Three-Stage Nuclear Power Program",
     "Dr. Homi Jehangir Bhabha formulated India's Three-Stage Nuclear Power Program to strategically utilize India's modest uranium reserves and vast thorium wealth.",
     "Stage 1 utilizes Pressurized Heavy Water Reactors (PHWRs) fueled by natural uranium, producing electricity and Plutonium-239 byproduct.", 1,
     "Both Statement I and Statement II are correct. Bhabha's three stages sequentially transition from PHWR (natural uranium) to FBR (plutonium) to thorium-based AHWR."),
    ("ar", "Fast Breeder Reactor (FBR) Stage 2 Breeding Ratio",
     "In Stage 2 of India's nuclear program, Fast Breeder Reactors (FBRs) are engineered to produce more fissile material than they consume.",
     "In an FBR, fast unmoderated neutrons convert fertile Thorium-232 or Uranium-238 blankets into fissile Uranium-233 or Plutonium-239 at a breeding ratio greater than 1.0.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). FBRs breed excess fissile fuel (breeding ratio > 1), multiplying usable nuclear fuel reserves for Stage 3."),
    ("match", "Catastrophic Nuclear Disaster Milestones",
     "Match the historic nuclear accident in List I with its location, year, and primary cause in List II:",
     [("A", "Three Mile Island"),
      ("B", "Chernobyl Disaster"),
      ("C", "Fukushima Daiichi Disaster"),
      ("D", "Kyshtym Disaster (Mayak)")],
     [("I", "Pennsylvania, USA (1979): Partial reactor core meltdown triggered by mechanical coolant valve failure and operator errors"),
      ("II", "Ukraine, USSR (1986): Catastrophic steam explosion and graphite fire at RBMK reactor following unauthorized safety test"),
      ("III", "Japan (2011): Magnitude 9.0 earthquake and 15-meter tsunami disabling emergency diesel generators, causing triple core meltdown"),
      ("IV", "Chelyabinsk, USSR (1957): Explosion of high-level radioactive waste storage tank releasing massive strontium-90 cloud")],
     "A-I, B-II, C-III, D-IV",
     "Three Mile Island occurred in 1979 (USA); Chernobyl in 1986 (Soviet Union); Fukushima in 2011 (Japan); and Kyshtym in 1957 (Urals)."),
    ("mcq", "Chernobyl Radioisotopes and Health Impacts",
     "The 1986 Chernobyl nuclear disaster released massive atmospheric plumes of volatile radioisotopes across Europe, leading to severe spikes in pediatric thyroid cancer primarily caused by:",
     "Iodine-131 (absorbed rapidly by the thyroid gland via contaminated cow milk)",
     ["Non-toxic carbon dioxide gas", "Solid gold isotopes deposited on soil", "Liquid helium rain"],
     "Volatile Iodine-131 (half-life 8 days) concentrated in pasture grass and dairy milk, bioaccumulating in human thyroid glands and inducing thousands of pediatric thyroid carcinomas."),
    ("mcq", "Half-Life Concept in Radioactive Decay",
     "The 'Half-Life' (t_1/2) of a radioactive isotope (e.g. Cesium-137 with t_1/2 = 30 years, or Plutonium-239 with t_1/2 = 24,100 years) is defined as the time required for:",
     "Exactly half of the radioactive parent nuclei in a sample to undergo decay into daughter products",
     ["The complete elimination of 100% of all radioactivity from the universe", "The atomic nucleus to double its physical weight", "The temperature of the isotope to drop to absolute zero"],
     "Half-life is the characteristic time required for 50% of radioactive atoms to disintegrate. Long-lived isotopes (Pu-239, t1/2 = 24,100 yrs) require geological isolation for millennia."),
    ("stmt", "Heavy Water as Moderator in PHWRs",
     "In India's commercial Pressurized Heavy Water Reactors (PHWRs), 'Heavy Water' (Deuterium Oxide, D2O) is used as both moderator and coolant.",
     "Heavy water has a very low neutron absorption cross-section, allowing the reactor to maintain a sustained chain reaction using unenriched natural uranium fuel.", 1,
     "Both Statement I and Statement II are correct. D2O slows down fast fission neutrons without absorbing them, eliminating the need for expensive uranium enrichment."),
    ("seq", "Sequence of Long-Term High-Level Nuclear Waste Management",
     "Arrange the sequential operational steps for managing and isolating high-level radioactive waste (HLW) from spent reactor fuel:",
     ["Underwater cooling: spent fuel assemblies are stored in deep wet pools for 5–10 years to dissipate intense decay heat", "Chemical reprocessing: recovering unburnt uranium and plutonium while separating liquid high-level fission product wastes", "Vitrification: immobilizing liquid high-level radioactive waste by incorporating it into durable borosilicate glass matrices inside stainless steel canisters", "Deep Geological Repository (DGR): permanent disposal in stable, impermeable crystalline bedrock hundreds of meters beneath the Earth's surface"],
     "I -> II -> III -> IV",
     "Nuclear waste management lifecycle: wet pool cooling, chemical reprocessing, vitrification in borosilicate glass, and deep geological repository isolation."),
    ("mcq", "Ionizing vs Non-Ionizing Radiation",
     "Why is 'Ionizing Radiation' (such as Alpha particles, Beta particles, Gamma rays, and X-rays) biologically hazardous to living organisms, unlike non-ionizing radio waves?",
     "It carries sufficient quantum energy to strip orbital electrons from atoms, creating free radicals that break covalent chemical bonds and induce double-strand DNA breaks",
     ["It freezes human cells into solid ice crystals", "It transforms human blood into pure diesel fuel", "It causes all sound waves to disappear from the room"],
     "Ionizing radiation breaks chemical bonds, damages purine/pyrimidine DNA bases, and causes chromosome aberrations, leading to radiation sickness, sterility, and cancers."),
    ("ar", "Alpha Particle Biological Hazard Inhalation",
     "Alpha particles (Helium nuclei, 4He2+) cannot penetrate a simple sheet of paper or human skin, yet they pose an extreme lethal health hazard if inhaled or ingested.",
     "Alpha particles have a high Linear Energy Transfer (LET) and heavy mass; once deposited inside internal lung or bone tissue, they cause dense, localized ionizing ionization damage to adjacent cell DNA.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). External alpha is stopped by dead skin epidermis; internal alpha emitter inhalation (e.g. Radon, Plutonium) induces high-density cancer-causing double-strand DNA breaks."),
    ("mcq", "Kudankulam Nuclear Power Plant Technology",
     "The Kudankulam Nuclear Power Plant (KKNPP) in Tamil Nadu, India's largest operational nuclear power station, utilizes advanced Russian-designed reactors of which type?",
     "VVER-1000 Pressurized Water Reactors (PWRs) equipped with passive safety systems",
     ["Graphite-moderated RBMK reactors identical to Chernobyl", "Open-pool swimming pool research reactors", "Coal-fired gasification boilers"],
     "Kudankulam operates VVER-1000 pressurized water reactors using low-enriched uranium fuel and light water moderator, featuring passive core-cooling safety mechanisms."),
    ("mcq", "Stage 3 of Indian Nuclear Program Fissile Fuel",
     "In Stage 3 of Dr. Bhabha's nuclear blueprint, Advanced Heavy Water Reactors (AHWRs) will breed and utilize which man-made fissile isotope derived from abundant native Thorium-232?",
     "Uranium-233 (U-233)",
     ["Uranium-235 (U-235)", "Plutonium-238 (Pu-238)", "Cobalt-60 (Co-60)"],
     "In Stage 3, fertile Thorium-232 captures neutrons to transmute into fissile Uranium-233: 232Th + n -> 233Th -> 233Pa -> 233U, unlocking India's vast monazite reserves."),
    ("match", "Radioactive Isotopes and Half-Lives / Uses",
     "Match the radioisotope in List I with its signature property/half-life in List II:",
     [("A", "Iodine-131"),
      ("B", "Cesium-137"),
      ("C", "Carbon-14"),
      ("D", "Plutonium-239")],
     [("I", "Half-life of 8 days; concentrates in thyroid gland; used in medical radiotherapy"),
      ("II", "Half-life of 30 years; major persistent gamma-emitting fission product contaminating soils"),
      ("III", "Half-life of 5,730 years; cosmogenically formed isotope used for radiocarbon dating archaeological organic remains"),
      ("IV", "Half-life of 24,100 years; fissile transuranic actinide used in nuclear weapons and breeder reactors")],
     "A-I, B-II, C-III, D-IV",
     "I-131 has 8-day half-life; Cs-137 has 30-year half-life; C-14 has 5,730-year half-life; and Pu-239 has 24,100-year half-life."),
    ("mcq", "Vitrification Process for High-Level Waste",
     "In nuclear fuel reprocessing at Bhabha Atomic Research Centre (BARC, Trombay), what does the process of 'Vitrification' achieve?",
     "It mixes liquid high-level radioactive fission waste with borosilicate glass-forming chemicals at 1,000 degrees Celsius, converting it into an insoluble, chemically durable solid glass block",
     ["It dissolves spent uranium fuel in milk to feed to farm animals", "It burns radioactive rods in open coal furnaces", "It launches nuclear waste canisters into orbit around Mars"],
     "Vitrification chemically binds radioactive waste inside molten borosilicate glass matrices, preventing leaching by groundwater over geological time scales."),
    ("mcq", "Radon Gas Indoor Inhalation Hazard",
     "Radon-222 (an odorless, colorless, radioactive noble gas produced by the radioactive decay of Radium-226 in subterranean granite and soils) poses a major health hazard in poorly ventilated basements because:",
     "Its inhaled short-lived alpha-emitting decay daughters (Polonium-218 and Polonium-214) deposit in lung bronchial epithelium, acting as the second leading cause of lung cancer",
     ["It explodes immediately upon contact with indoor fluorescent lighting", "It corrodes structural steel rebar inside concrete foundations within 2 hours", "It turns oxygen into poisonous hydrogen cyanide gas"],
     "Radon is a radioactive noble gas; inhaling its alpha-emitting solid progeny (Po-218, Po-214) causes chronic pulmonary irradiation, ranking second only to tobacco smoking in causing lung cancer."),
    ("stmt", "Sievert and Gray Radiation Dose Units",
     "The Gray (Gy) is the SI unit measuring absorbed radiation dose, representing the absorption of one joule of radiation energy per kilogram of matter.",
     "The Sievert (Sv) measures biological effective dose, multiplying absorbed dose in Grays by radiation biological weighting factors (Q) to account for tissue-specific biological damage.", 1,
     "Both Statement I and Statement II are correct. Gray measures physical absorbed energy (J/kg); Sievert measures biological cancer/damage risk in human tissue."),
    ("mcq", "Fukushima Daiichi Hydrogen Explosions",
     "During the 2011 Fukushima disaster, the catastrophic explosions that blew off the outer secondary containment roofs of Reactor Units 1, 3, and 4 were caused by:",
     "Overheating zirconium fuel cladding reacting with steam to produce massive hydrogen gas (Zr + 2H2O -> ZrO2 + 2H2), which leaked into the service floor and detonated upon mixing with air",
     ["A direct nuclear thermonuclear explosion equivalent to a 20-megaton hydrogen bomb", "Undersea torpedo attacks from hostile naval submarines", "The spontaneous detonation of the nuclear uranium core fuel pellets"],
     "Water loss caused fuel rods to exceed 1,200 C; zirconium alloy reacted with steam producing hydrogen gas, which accumulated in reactor buildings and exploded upon contact with oxygen."),
    ("seq", "Biochemical Progression of Acute Radiation Syndrome (ARS)",
     "Arrange the clinical phases in an individual exposed to an acute, whole-body ionizing radiation dose (>4–6 Sieverts):",
     ["Prodromal phase: rapid onset of nausea, severe vomiting, fatigue, and diarrhea within hours of exposure", "Latent phase: temporary apparent clinical improvement where symptoms subside for several days to weeks", "Manifest illness phase: massive collapse of hematopoietic bone marrow, extensive internal hemorrhaging, immune depletion, and intestinal lining sloughing", "Death from opportunistic infections and septic shock unless rescued by bone marrow transplant"],
     "I -> II -> III -> IV",
     "Acute Radiation Syndrome progresses from prodromal nausea to latent calm, manifest hematopoietic/gastrointestinal collapse, and fatal septicemia."),
    ("mcq", "Atomic Energy Act 1962 in India",
     "Under the Atomic Energy Act, 1962, which statutory authority holds the exclusive monopoly over all atomic energy research, uranium mining, nuclear power generation, and fissile materials in India?",
     "The Central Government through the Department of Atomic Energy (DAE)",
     ["Private foreign multinational energy corporations", "State Electricity Boards of individual states", "Municipal corporations of capital cities"],
     "The Atomic Energy Act 1962 centralizes all atomic energy, nuclear minerals (uranium, thorium), and reactor operations under the Department of Atomic Energy (DAE) reporting directly to the Prime Minister."),
    ("mcq", "Atomic Energy Regulatory Board (AERB) Safety Role",
     "The statutory regulatory body established in 1983 to frame nuclear safety rules, conduct safety audits, and license nuclear and radiological installations in India is the:",
     "Atomic Energy Regulatory Board (AERB)",
     ["Nuclear Power Corporation of India Limited (NPCIL)", "Bhabha Atomic Research Centre (BARC)", "Uranium Corporation of India Limited (UCIL)"],
     "The AERB is India's independent safety watchdog, enforcing radiological protection standards and issuing operating licenses for nuclear reactors and medical radiotherapy units.")
]
'''

with open('scripts/subject_generators/make_evs_s31_35.py', 'w') as f:
    f.write(s31_to_35)

print("make_evs_s31_35.py written.")
