# Slots 18 to 20 Generator
s18_to_20 = '''
# ==============================================================================
# Slot 18: River Conservation & Indian Water Management (GAP, Namami Gange, CPCB)
# ==============================================================================
s18_raw = [
    ("mcq", "Ganga Action Plan Phase I Launch",
     "The Ganga Action Plan (GAP) Phase I was launched in 1985 by Prime Minister Rajiv Gandhi with the primary objective of:",
     "Interception, diversion, and treatment of domestic sewage entering the river to improve water quality to bathing standards",
     ["Building high-speed nuclear submarine channels down the Ganga", "Constructing unbroken concrete embankments along all 2,525 km of the river", "Eliminating all wild aquatic organisms from the river system"],
     "GAP was launched in June 1985 at Varanasi to intercept, divert, and treat municipal sewage from 25 class-I riparian cities along the Ganga."),
    ("stmt", "National River Conservation Plan (NRCP) Scope",
     "The National River Conservation Plan (NRCP) was formulated to extend river pollution abatement works to all major polluted river stretches across India.",
     "Under NRCP, financial expenditure for sewage infrastructure is shared between the Central and State Governments on a cooperative basis.", 1,
     "Both Statement I and Statement II are correct. NRCP covers major inter-state rivers (Yamuna, Narmada, Krishna, Cauvery, Godavari) across dozens of states."),
    ("ar", "Aviral Dhara and Nirmal Dhara Goals",
     "The Namami Gange Mission established the twin interconnected goals of 'Nirmal Dhara' (clean flow) and 'Aviral Dhara' (uninterrupted continuous ecological flow).",
     "Achieving a clean river is ecologically impossible without maintaining sufficient minimum environmental baseflows (E-flows) to dilute effluents and sustain riverine biodiversity.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Nirmal Dhara (zero untreated discharge) requires Aviral Dhara (continuous ecological flow) for aquatic self-purification."),
    ("match", "Key River Action Programs and Milestones",
     "Match the river conservation milestone in List I with its year or administrative agency in List II:",
     [("A", "Ganga Action Plan Phase I"),
      ("B", "National Ganga River Basin Authority (NGRBA)"),
      ("C", "Namami Gange Integrated Conservation Mission"),
      ("D", "Statutory Implementation Agency for Namami Gange")],
     [("I", "1985"),
      ("II", "2009 (Chaired by the Prime Minister)"),
      ("III", "2014 (Approved with Rs. 20,000 crore budget)"),
      ("IV", "National Mission for Clean Ganga (NMCG)")],
     "A-I, B-II, C-III, D-IV",
     "GAP-I launched in 1985, NGRBA created in 2009, Namami Gange approved in 2014, and NMCG acts as the registered society implementation wing."),
    ("mcq", "Primary River Basin Pollution Source in India",
     "According to official Central Pollution Control Board (CPCB) river monitoring reports, what accounts for over 70% of the total pollution load entering major Indian rivers?",
     "Untreated municipal domestic sewage from cities and towns along river banks",
     ["Thermal radioactive cooling discharges from nuclear stations", "Direct acid rain falling on river surfaces", "Agricultural soil erosion from mountain meadows"],
     "CPCB data confirms that domestic municipal sewage is by far the largest contributor (>70%) to organic pollution loads in Indian rivers, far outstripping industrial effluent volume."),
    ("mcq", "Ecological Flow (E-Flow) Mandate on River Ganga",
     "In October 2018, the Central Government took the historic statutory step under the Environment (Protection) Act 1986 of notifying mandatory 'Environmental Flows' (E-Flows) for:",
     "The River Ganga from its origins down to Unnao, mandating minimum cubic meter per second discharge from all barrages and hydroelectric dams across all seasons",
     ["Only small seasonal monsoon gullies in Rajasthan", "Private municipal swimming pools in metropolitan centers", "Underground groundwater extraction borewells"],
     "The 2018 E-Flow notification legally mandated continuous minimum discharge rates (varying across dry, lean, and monsoon seasons) from all dams along the upper Ganga basin."),
    ("stmt", "Central Ground Water Authority (CGWA) Mandate",
     "The Central Ground Water Authority (CGWA) was constituted under Section 3(3) of the Environment (Protection) Act, 1986, following Supreme Court directives.",
     "CGWA has statutory powers to regulate and control indiscriminate groundwater extraction, issue No Objection Certificates (NOCs), and declare 'Over-exploited' assessment units.", 1,
     "Both Statement I and Statement II are correct. CGWA regulates indiscriminate industrial and infrastructure extraction of groundwater to prevent aquifer exhaustion."),
    ("seq", "Sequence of Treatment in an Urban Sewage Treatment Plant (STP)",
     "Arrange the sequential treatment units in a modern Activated Sludge Process Sewage Treatment Plant:",
     ["Bar screens and Grit chambers: physical removal of large floating debris, plastics, and coarse heavy sand", "Primary Clarifier (Sedimentation tank): settling of settleable organic suspended solids as primary raw sludge", "Aeration Basin: aerobic microorganisms digest dissolved organic matter (reducing BOD) in presence of diffused compressed air", "Secondary Clarifier and Chlorination / UV disinfection: settling of activated biomass sludge and disinfection of treated effluent before river discharge"],
     "I -> II -> III -> IV",
     "STP sequence: screening/grit removal, primary settling, biological aeration basin, and secondary settling with disinfection."),
    ("mcq", "Common Effluent Treatment Plants (CETPs)",
     "In dense industrial clusters dominated by Small and Medium Enterprises (SMEs), how does a 'Common Effluent Treatment Plant' (CETP) solve industrial water pollution?",
     "It aggregates wastewater from dozens of small industrial units into a single central facility, making sophisticated multi-stage effluent treatment technically and financially viable",
     ["It dumps all chemical effluents directly into open city storm drains at midnight", "It evaporates wastewater using diesel burners funded by public subsidies", "It converts heavy chemical metals into drinking bottled mineral water"],
     "CETPs pool wastewater from small enterprises that lack individual capital to install expensive effluent treatment systems, ensuring collective compliance with pollution standards."),
    ("ar", "Zero Liquid Discharge (ZLD) in Polluting Industries",
     "The Central Pollution Control Board mandates 'Zero Liquid Discharge' (ZLD) for heavily polluting industrial sectors like distilleries, pulp and paper, and tanneries.",
     "Under ZLD, all wastewater is recycled, purified, and reused within the facility through membrane filtration and evaporators, completely eliminating any discharge into rivers.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). ZLD enforces a closed-loop system where water is recovered and dissolved salts are crystallized for disposal, eliminating river pollution."),
    ("mcq", "CPCB River Monitoring Network (NWMP)",
     "Under the National Water Quality Monitoring Programme (NWMP) operated by CPCB, water samples across Indian rivers are monitored to classify stretches into how many Priority Classes based on BOD?",
     "Five Priority Classes (Priority I: BOD > 30 mg/L to Priority V: BOD 3 to 6 mg/L)",
     ["Two classes: Clean and Dirty", "Ten classes numbered from Alpha to Omega", "Zero classes, as monitoring is unclassified"],
     "CPCB categorizes polluted river stretches into 5 Priority Classes: Priority I (BOD > 30 mg/L, critically polluted) down to Priority V (BOD 3-6 mg/L)."),
    ("mcq", "Constructed Wetlands for Wastewater Treatment",
     "How do 'Constructed Wetlands' (Phytoremediation root-zone systems) treat sewage sustainably in peri-urban and rural areas without chemical additions?",
     "By channeling wastewater through engineered gravel beds planted with wetland reeds (Typha, Phragmites), where root biofilms filter, oxygenate, and degrade pollutants",
     ["By using subterranean volcanic steam vents to boil sewage into sterile vapor", "By spraying radioactive cesium isotopes to neutralize all living organisms", "By burying wastewater in plastic containers 1,000 meters deep underground"],
     "Constructed wetlands use natural physical filtration, plant nutrient uptake, and rhizosphere microbial biofilms to remove BOD, nitrogen, and pathogens cheaply and naturally."),
    ("match", "River Basins and Major Environmental Issues",
     "Match the Indian river in List I with its signature pollution/management challenge in List II:",
     [("A", "Yamuna (Delhi stretch)"),
      ("B", "Ganga (Kanpur stretch)"),
      ("C", "Damodar (Jharkhand / WB)"),
      ("D", "Narmada River")],
     [("I", "Zero dissolved oxygen throughout non-monsoon months due to unsewered municipal drains entering downstream of Wazirabad barrage"),
      ("II", "High organic sewage and chromium chemical effluent from historical leather tanning complexes in Jajmau"),
      ("III", "Historically known as 'Sorrow of Bengal', heavily polluted by coal washery slurries, fly ash, and thermal stations"),
      ("IV", "Controversies over massive hydroelectric dam construction (Sardar Sarovar Dam) and submergence of tribal lands")],
     "A-I, B-II, C-III, D-IV",
     "Delhi Yamuna suffers total anoxia, Kanpur Ganga receives tannery effluents, Damodar suffers coal washery silt, and Narmada witnessed Sardar Sarovar struggles."),
    ("mcq", "Mandatory Rainwater Harvesting in Tamil Nadu",
     "In 2001, which Indian state became the pioneer in the country to make rooftop rainwater harvesting compulsory for every building, resulting in a dramatic turnaround of urban groundwater tables?",
     "Tamil Nadu",
     ["Rajasthan", "Uttar Pradesh", "Bihar"],
     "Tamil Nadu enacted a historic law in 2001 mandating rooftop rainwater harvesting across all buildings in Chennai and state-wide, reviving depleted aquifers within five years."),
    ("mcq", "Kalyani Canal East Kolkata Wetlands Nature Solution",
     "The East Kolkata Wetlands (a Ramsar Site) perform a globally unique, cost-free ecological service for the metropolis of Kolkata by:",
     "Treating over 750 million liters of municipal sewage daily through a natural cascade of shallow fish-rearing ponds (bheries) and vegetable farms",
     ["Dumping all city sewage directly into the open Bay of Bengal via high-pressure pipelines", "Storing all industrial toxic radioactive chemicals in deep salt caverns", "Serving as an offshore coal bunkering port for international ships"],
     "The East Kolkata Wetlands use natural solar radiation, algae, and benthic bacteria to purify city wastewater while producing thousands of tons of fish and vegetables daily."),
    ("stmt", "National Water Quality Criteria for Outdoor Bathing",
     "According to CPCB's Designated Best Use classification, Class 'B' water is earmarked for 'Outdoor Bathing'.",
     "Class 'B' water mandates that Dissolved Oxygen must be 5.0 mg/L or higher, Biochemical Oxygen Demand (BOD5) must be 3.0 mg/L or less, and Fecal Coliforms must be below 500 MPN/100 mL (desirable).", 1,
     "Both Statement I and Statement II are correct. Class B criteria (DO >= 5 mg/L, BOD <= 3 mg/L, pH 6.5-8.5) define acceptable parameters for safe river bathing."),
    ("mcq", "CPCB Real-Time Water Quality Monitoring System",
     "Under Namami Gange, automated real-time water quality monitoring stations installed along the river transmit continuous sensor data to CPCB on which parameters?",
     "pH, Dissolved Oxygen (DO), Biochemical Oxygen Demand (BOD), Chemical Oxygen Demand (COD), Conductivity, and Turbidity",
     ["Only atmospheric wind direction and barometric pressure", "Total monetary tax revenue collected from riverside temples", "Percentage of pure gold dissolved in river sand"],
     "Real-time water quality sensors provide uninterrupted telemetry on pH, DO, BOD, COD, temperature, and turbidity directly to the national dashboard."),
    ("seq", "Procedure of Implementing a River Catchment Restoration Plan",
     "Arrange the progressive operational steps involved in cleaning a polluted river basin:",
     ["Comprehensive basin-wide mapping of all domestic sewage outfalls and industrial effluent discharge points", "Construction of interception and diversion (I&D) trunk sewers to stop direct untreated outfalls into the river", "Erection of state-of-the-art Sewage Treatment Plants (STPs) and Common Effluent Treatment Plants (CETPs)", "Mandatory enforcement of minimum environmental ecological flows (E-Flows) and continuous online monitoring"],
     "I -> II -> III -> IV",
     "Basin restoration proceeds from outfall inventory to sewer interception/diversion, treatment plant construction, and continuous E-flow enforcement."),
    ("mcq", "Bacterial Bioremediation of Oil Spills (Oilzapper)",
     "The microbial consortium 'Oilzapper', developed by TERI (The Energy and Resources Institute) in India, bioremediates hazardous oil spills and petroleum sludge by:",
     "Utilizing a cocktail of specialized hydrocarbon-degrading bacterial strains that feed on crude oil, breaking it down into CO2, water, and harmless biomass",
     ["Burning the oil slick with thermite flares on the water surface", "Precipitating the crude oil to the ocean bed using pulverized lead powder", "Converting petroleum into solid plastic blocks that float on the surface"],
     "TERI's 'Oilzapper' consists of 5 bacterial strains that rapidly digest complex petroleum hydrocarbons, successfully cleaning thousands of tons of oily sludge in situ."),
    ("mcq", "River Interlinking Project (ILR) Environmental Concerns",
     "The ambitious National River Interlinking Project in India faces major ecological criticism from environmental scientists primarily because it:",
     "Submerges vast tracts of pristine tiger and elephant forests, disrupts riverine hydrological regimes, and alters natural deltaic sedimentation",
     ["Will cause all Himalayan mountains to sink into tectonic trenches", "Will permanently stop the Earth from rotating on its axis", "Will convert all freshwater into pure alcohol"],
     "Ecologists warn that interlinking rivers (e.g. Ken-Betwa link submerging Panna Tiger Reserve) alters monsoon dynamics, floods forests, and destroys deltaic estuarine fisheries.")
]

# ==============================================================================
# Slot 19: Soil Pollution, Degradation & Desertification
# ==============================================================================
s19_raw = [
    ("mcq", "Soil Salinization in Canal-Irrigated Arid Lands",
     "In arid and semi-arid tracts of Punjab, Haryana, and Rajasthan, excessive flood irrigation from canals without adequate underground drainage leads to:",
     "Waterlogging followed by severe soil salinization (Reh / Kallar) as capillary action pulls dissolved mineral salts to the surface where water evaporates",
     ["Instantaneous transformation of the soil into rich tropical volcanic peat", "Rapid cooling of the subsoil causing permanent permafrost formation", "The complete elimination of all soil microbes within 5 minutes"],
     "Over-irrigation in poorly drained soils raises water tables; capillary action draws saline water upward, depositing white encrustations of sodium salts (salinization)."),
    ("stmt", "Types of Water-Induced Soil Erosion",
     "Sheet erosion refers to the uniform, gradual removal of a thin layer of topsoil across a wide slope caused by sheet runoff, often remaining unnoticed.",
     "Gully erosion occurs when runoff concentrates into fast-flowing channels, carving deep ravines that fragment agricultural lands into uncultivable badlands.", 1,
     "Both Statement I and Statement II are correct. Water erosion progresses through splash, sheet, rill, and gully erosion (as seen in the Chambal ravines)."),
    ("ar", "Chambal Ravines and Gully Erosion",
     "The Chambal river basin in Madhya Pradesh, Rajasthan, and Uttar Pradesh is characterized by extensive, barren badlands known as the Chambal Ravines.",
     "Uncontrolled gully erosion, deforestation, and friable alluvial soils have dissected thousands of hectares of fertile farmland into deep, uncultivable chasms.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Severe gully erosion has turned over 4,000 km2 along the Chambal into badland topography."),
    ("match", "Soil Degradation Processes and Mitigating Conservation Practices",
     "Match the soil degradation hazard in List I with its standard conservation technique in List II:",
     [("A", "Slope runoff and water erosion"),
      ("B", "Wind erosion in arid deserts"),
      ("C", "Soil salinization and alkalinization"),
      ("D", "Industrial heavy metal contamination")],
     [("I", "Contour bunding and bench terracing"),
      ("II", "Shelterbelts / Windbreaks of deep-rooted trees"),
      ("III", "Application of agricultural gypsum (CaSO4.2H2O) and sub-surface leaching drainage"),
      ("IV", "Phytoremediation using hyperaccumulator plants (e.g., Brassica juncea)")],
     "A-I, B-II, C-III, D-IV",
     "Contour terracing curbs water runoff, shelterbelts stop wind erosion, gypsum rectifies sodic soils, and phytoremediation cleans heavy metals."),
    ("mcq", "Phytoremediation Biological Mechanism",
     "Phytoremediation is an environmentally friendly green technology that utilizes selected plants and associated microbes to:",
     "Extract, sequester, degrade, or immobilize toxic heavy metals and organic contaminants from polluted soils and groundwater",
     ["Incinerate topsoil using high-temperature thermal blowtorches", "Pave contaminated farmland with multi-layer asphalt to seal in toxins", "Inject liquid mercury into crop root nodules to stimulate nitrogen fixation"],
     "Phytoremediation uses plants (e.g. mustard, sunflowers) to phytoextract, phytostabilize, or rhizofilter heavy metals like lead, cadmium, and arsenic from soil."),
    ("mcq", "Indian Mustard (Brassica juncea) in Phytoremediation",
     "Why is Indian Mustard (Brassica juncea) celebrated globally in environmental biotechnology as a model 'hyperaccumulator' plant?",
     "It possesses extraordinary physiological capacity to absorb and translocate heavy metals (such as Lead, Cadmium, and Nickel) from soil into its harvestable above-ground shoots",
     ["It produces synthetic petroleum gasoline directly inside its seed pods", "It converts soil radioisotopes into harmless nitrogen gas in the dark", "It freezes all soil water to halt chemical reactions"],
     "Brassica juncea is a renowned metal hyperaccumulator capable of extracting up to 400 times more lead and cadmium than ordinary crops without succumbing to phytotoxicity."),
    ("stmt", "United Nations Convention to Combat Desertification (UNCCD)",
     "The UNCCD was established in 1994 as the sole legally binding international agreement linking environment and development to sustainable land management.",
     "The convention focuses specifically on the Arid, Semi-Arid, and Dry Sub-Humid areas, known as the drylands, where some of the most vulnerable ecosystems exist.", 1,
     "Both Statement I and Statement II are correct. UNCCD addresses land degradation, desertification, and drought in drylands."),
    ("seq", "Progressive Stages of Water-Induced Soil Erosion",
     "Arrange the evolutionary stages of soil erosion by water in order of increasing visual prominence and structural devastation:",
     ["Raindrop / Splash erosion: kinetic impact of falling raindrops dislodges and shatters soil aggregates", "Sheet erosion: uniform superficial peeling of a thin topsoil layer by unchanneled overland runoff", "Rill erosion: runoff concentrates into numerous miniature, centimeter-deep finger-like rivulets", "Gully erosion: rills coalesce into deep, steep-sided channels that cannot be smoothed over by ordinary plowing"],
     "I -> II -> III -> IV",
     "Erosion progresses systematically from raindrop splash to sheet erosion, shallow rills, and finally destructive deep gullies."),
    ("mcq", "Land Degradation Neutrality (LDN) Goal",
     "Under UNCCD and Sustainable Development Goal 15.3, 'Land Degradation Neutrality' (LDN) is defined as a state whereby:",
     "The amount and quality of land resources necessary to support ecosystem functions and food security remains stable or increases within specified scales",
     ["All agricultural activities are permanently banned worldwide", "All terrestrial land is converted into urban industrial housing projects", "Zero water is permitted to be consumed for crop cultivation"],
     "LDN is a target where degradation is balanced by restoration, ensuring no net loss of healthy productive land by 2030."),
    ("ar", "Excess Chemical Nitrogen Fertilizer and Soil Acidification",
     "Continuous, excessive application of synthetic nitrogenous fertilizers (such as Urea and Ammonium Sulfate) over decades leads to severe soil acidification.",
     "Microbial nitrification of ammonium ions (NH4+) in soil releases free hydrogen ions (H+), steadily exhausting the soil's natural buffering base cations (Ca2+, Mg2+).", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Oxidation of ammonia fertilizers acidifies soil, leaching out calcium and magnesium nutrients and stunting crops."),
    ("mcq", "Bonn Challenge Forest Landscape Restoration",
     "The 'Bonn Challenge', launched in 2011 by Germany and IUCN, is a global effort to:",
     "Restore 150 million hectares of the world's deforested and degraded land by 2020, and 350 million hectares by 2030",
     ["Construct a continuous concrete highway spanning all continents", "Eliminate all national parks across developing countries", "Export all topsoil from Africa to industrial greenhouses in Europe"],
     "The Bonn Challenge is the premier global commitment to bring 350 million hectares of degraded and deforested landscapes into restoration by 2030 (India committed to 26M ha)."),
    ("mcq", "Gypsum Application in Sodic (Alkali) Soils",
     "Why is agricultural Gypsum (hydrated calcium sulfate, CaSO4.2H2O) applied to reclaim sodic (alkali) soils characterized by high exchangeable sodium?",
     "Calcium ions (Ca2+) from gypsum displace harmful exchangeable sodium ions (Na+) from the soil clay complex, allowing sodium to be leached downward as soluble sodium sulfate",
     ["Gypsum burns the soil with high heat, sterilizing all fungal spores", "Gypsum changes the color of soil from black to green to reflect sunlight", "Gypsum acts as a synthetic nuclear isotope absorbing all groundwater"],
     "Gypsum provides soluble Ca2+ that replaces Na+ on clay colloids: Clay-2Na + CaSO4 -> Clay-Ca + Na2SO4, restoring soil permeability and structure."),
    ("match", "Soil Problem and Diagnostic Chemical Parameter",
     "Match the degraded soil condition in List I with its chemical diagnostic indicator in List II:",
     [("A", "Saline Soil (White Alkali)"),
      ("B", "Sodic / Alkaline Soil (Black Alkali)"),
      ("C", "Acid Soil"),
      ("D", "Healthy Agricultural Loam")],
     [("I", "Electrical Conductivity (EC) > 4 dS/m, ESP < 15%, pH < 8.5"),
      ("II", "Exchangeable Sodium Percentage (ESP) > 15%, high pH (often > 8.5 to 10)"),
      ("III", "Soil pH < 5.5, high soluble aluminum (Al3+) and manganese toxicity"),
      ("IV", "Balanced pH 6.5 to 7.5, optimal organic carbon (> 0.75%), good crumb structure")],
     "A-I, B-II, C-III, D-IV",
     "Saline soil has high EC (>4 dS/m), sodic soil has high ESP (>15%), acid soil has pH < 5.5, and healthy loam maintains pH 6.5–7.5."),
    ("mcq", "Terrace Farming in Mountain Agriculture",
     "How does the construction of stepped 'Bench Terraces' on steep mountain slopes (such as in Uttarakhand and Himachal) prevent catastrophic soil erosion?",
     "By transforming steep continuous runoff slopes into a series of leveled horizontal steps, drastically reducing surface runoff velocity and promoting water infiltration",
     ["By heating the mountain soil to accelerate chemical weathering of bedrock", "By preventing cloud formation over mountain valleys", "By funneling all torrential rain directly into deep ravine cracks"],
     "Bench terracing breaks steep hillsides into stepped horizontal platforms, eliminating high runoff velocity and holding fertile topsoil in place."),
    ("mcq", "Shelterbelts and Wind Erosion in Arid Zones",
     "In the arid desert zones of Rajasthan and Gujarat, farmers plant 'Shelterbelts' (multiple rows of trees and shrubs perpendicular to prevailing winds) to:",
     "Reduce ground-level wind velocity, preventing wind shear from lifting and blowing away fertile topsoil and stabilizing sand dunes",
     ["Block all sunlight from reaching neighboring weed fields", "Trap migratory marine fish in desert depressions", "Generate commercial timber for ship construction within months"],
     "Shelterbelts (e.g. Prosopis cineraria, Acacia nilotica) act as windbreaks, lifting wind currents and protecting delicate topsoil from aeolian deflation."),
    ("stmt", "Humus and Soil Ecological Health",
     "Humus is the dark, amorphous, highly decomposed organic fraction of soil formed by microbial decay of plant and animal residues.",
     "Humus has an extraordinarily high Cation Exchange Capacity (CEC), improves soil moisture retention, enhances aeration, and provides slow-release plant nutrients.", 1,
     "Both Statement I and Statement II are correct. Humus provides high cation exchange capacity, aggregates soil particles, and sustains rich microbial biodiversity."),
    ("mcq", "Soil Health Card Scheme in India",
     "The Government of India's 'Soil Health Card Scheme' (launched in 2015 with the motto 'Swasth Dhara, Khet Hara') provides farmers with customized crop-wise recommendations based on testing:",
     "12 soil fertility parameters (including primary N, P, K; secondary S; micronutrients Zn, Fe, Cu, Mn, B; and physical traits pH, EC, OC)",
     ["Only the depth of the underground water table", "The speed of passing cloud formations over the field", "The percentage of radioactive uranium in the topsoil"],
     "Soil Health Cards evaluate 12 essential soil parameters, rationalizing fertilizer usage and preventing soil degradation from over-application of urea."),
    ("seq", "Process of Desertification in Fragile Drylands",
     "Arrange the sequential environmental steps of anthropogenic desertification in arid rangelands:",
     ["Overgrazing, intensive firewood collection, and cultivation on marginal sloping lands remove protective vegetative cover", "Bare topsoil is exposed to direct solar baking, wind deflation, and raindrop compaction, forming an impermeable crust", "Rainwater fails to infiltrate, rushing off as flash runoff while wind sweeps away fertile organic dust", "Productivity collapses, indigenous vegetation fails to regenerate, and the land is permanently transformed into barren desert"],
     "I -> II -> III -> IV",
     "Desertification sequence: vegetation stripping, crusting and erosion, loss of hydrological retention, and final biological collapse into desert."),
    ("mcq", "Mulching and Moisture Conservation",
     "In organic farming and soil conservation, the agronomic practice of 'Mulching' involves:",
     "Spreading a protective layer of organic materials (crop straw, dry leaves, compost) over the bare soil surface to suppress weed growth, buffer temperature, and conserve moisture",
     ["Flooding the field with 1 meter of standing water throughout the year", "Burning all crop stalks on the field with kerosene every week", "Plowing the field 10 times a day during peak summer heat"],
     "Mulching covers bare soil, slashing evaporative water loss, buffering root temperatures, stopping erosion, and enriching humus as the organic mulch decomposes."),
    ("mcq", "Zero-Tillage (No-Till) Farming Benefits",
     "Why do conservation agriculture specialists advocate 'Zero-Tillage' (No-Till) farming over conventional deep plowing in agricultural fields?",
     "It leaves crop residues on the surface, preserves natural soil crumb structure, prevents topsoil erosion, and enhances carbon sequestration in the soil profile",
     ["It completely eliminates the need for any rainwater or irrigation", "It allows farmers to harvest crops without planting any seeds", "It causes all agricultural pests to turn into beneficial earthworms"],
     "Zero-tillage drills seeds directly into previous crop stubble without plowing, preventing erosion, preserving soil fungal mycorrhizae, and cutting fuel emissions.")
]

# ==============================================================================
# Slot 20: Noise Pollution & Ambient Acoustic Norms
# ==============================================================================
s20_raw = [
    ("mcq", "Noise Pollution Statutory Definition in India",
     "Under Indian environmental law, 'Noise' was officially recognized and incorporated as an 'Air Pollutant' under which statutory amendment?",
     "The Air (Prevention and Control of Pollution) Amendment Act, 1987",
     ["The Wildlife Protection Act, 1972", "The Indian Forest Act, 1927", "The Motor Vehicles Act, 1939"],
     "The 1987 amendment to the Air Act 1981 formally amended Section 2(a) to include 'noise' within the legal definition of an air pollutant."),
    ("stmt", "Decibel Logarithmic Scale",
     "Sound pressure level is measured in 'decibels' (dB), which operates on a logarithmic rather than a linear scale.",
     "Because the decibel scale is logarithmic, an increase of 10 dB represents a ten-fold increase in sound intensity, and an increase of 20 dB represents a hundred-fold increase.", 1,
     "Both Statement I and Statement II are correct. Decibels: L = 10 log10(I/I0). A 10 dB jump multiplies intensity by 10; a 20 dB jump multiplies intensity by 100."),
    ("ar", "Permanent Hearing Damage Sound Threshold",
     "Exposure to an instantaneous sound level of 150 decibels (dB) or higher can cause immediate and permanent damage to human hearing.",
     "A sound intensity of 150 dB (such as a jet aircraft takeoff at close range or a rocket launch) physically ruptures the delicate tympanic eardrum and destroys cochlear sensory hair cells.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Sounds >= 150 dB cause mechanical acoustic trauma, permanently destroying non-regenerative auditory hair cells."),
    ("match", "Ambient Noise Standards under Noise Rules 2000",
     "Match the zone category in List I with its statutory daytime (6:00 AM to 10:00 PM) permissible noise limit in List II under the Noise Pollution Rules, 2000:",
     [("A", "Industrial Area"),
      ("B", "Commercial Area"),
      ("C", "Residential Area"),
      ("D", "Silence Zone")],
     [("I", "75 dB(A)"),
      ("II", "65 dB(A)"),
      ("III", "55 dB(A)"),
      ("IV", "50 dB(A)")],
     "A-I, B-II, C-III, D-IV",
     "Daytime limits under Noise Rules 2000: Industrial 75 dB, Commercial 65 dB, Residential 55 dB, and Silence Zone 50 dB."),
    ("mcq", "Nighttime Noise Standards under Noise Rules 2000",
     "What are the statutory nighttime (10:00 PM to 6:00 AM) permissible ambient noise limits in decibels dB(A) for Residential and Silence Zones respectively in India?",
     "Residential: 45 dB(A); Silence Zone: 40 dB(A)",
     ["Residential: 75 dB(A); Silence Zone: 65 dB(A)", "Residential: 60 dB(A); Silence Zone: 55 dB(A)", "Residential: 20 dB(A); Silence Zone: 10 dB(A)"],
     "Nighttime limits: Industrial 70 dB, Commercial 55 dB, Residential 45 dB, and Silence Zone 40 dB."),
    ("mcq", "Silence Zone Distance Criterion",
     "Under the Noise Pollution (Regulation and Control) Rules, 2000, a 'Silence Zone' is formally defined as an area comprising an area not less than:",
     "100 meters around hospitals, educational institutions, courts, and religious places declared by the State Government",
     ["5 kilometers around all corporate business parks", "500 meters around all highway toll plazas", "10 meters around public bus terminals"],
     "Noise Rules define a Silence Zone as an area comprising not less than 100 meters around hospitals, educational institutions, and courts."),
    ("stmt", "Nighttime Loudspeaker Restrictions",
     "Under Rule 5 of the Noise Pollution Rules 2000, the operation of loudspeakers or public address systems in open public places is prohibited between 10:00 PM and 6:00 AM.",
     "State Governments have discretionary power to relax this nighttime restriction for specified cultural or religious occasions for a maximum of 15 days in a calendar year.", 1,
     "Both Statement I and Statement II are correct. Loudspeakers are banned between 10 PM and 6 AM, with up to 15 days annual festival relaxation permitted until midnight."),
    ("seq", "Sequence of Physiological Stress Responses to Chronic Noise",
     "Arrange the progressive physiological and systemic health consequences in a human being subjected to chronic noise pollution (>85 dB) over months:",
     ["Auditory acoustic perception triggers acute autonomic sympathetic nervous system stimulation", "Secretion of stress hormones (adrenaline, noradrenaline, and cortisol) surges into the bloodstream", "Peripheral vasoconstriction causes sustained elevation of systemic blood pressure (hypertension)", "Chronic cardiovascular strain leads to heart disease, sleep architecture fragmentation, and cognitive impairment"],
     "I -> II -> III -> IV",
     "Noise stress progression: sympathetic activation, stress hormone release, vasoconstriction/hypertension, and long-term cardiovascular/cognitive damage."),
    ("mcq", "Green Muffler Technique for Noise Reduction",
     "The 'Green Muffler' environmental pollution abatement technique involves:",
     "Planting 4 to 6 continuous rows of dense, leafy trees (such as Ashok and Neem) along highways and near industrial areas to attenuate and absorb sound waves",
     ["Wrapping industrial exhaust pipes with green plastic sheets", "Painting airport runways with sound-absorbing green paint", "Wearing green cotton earplugs in urban traffic"],
     "Green Muffler is the greenbelt planting of dense trees (e.g. Polyalthia longifolia / Ashok, Neem) along roadsides to scatter and absorb noise (reducing levels by 10-15 dB)."),
    ("ar", "Frequency Weighting dB(A) Scale",
     "Environmental noise regulations universally specify sound limits in 'A-weighted decibels' [dB(A)] rather than unweighted physical sound pressure.",
     "The A-weighting acoustic filter adjusts physical sound measurements to correspond to the non-linear frequency sensitivity of the human ear, which is most sensitive between 1 kHz and 5 kHz.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Human hearing does not perceive all frequencies equally; dB(A) adjusts measurements to human ear responsiveness."),
    ("mcq", "Presbycusis vs Noise-Induced Hearing Loss (NIHL)",
     "While presbycusis is age-related hearing decline, 'Noise-Induced Hearing Loss' (NIHL) is clinically characterized by a distinctive diagnostic 'notch' on an audiogram at which frequency?",
     "4,000 Hertz (4 kHz)",
     ["50 Hertz", "20,000 Hertz", "100 Hertz"],
     "NIHL characteristically produces a sensorineural bilateral hearing loss notch centered at 4,000 Hz (4 kHz) on an audiogram, resulting from acoustic cochlear damage."),
    ("mcq", "Firecrackers Noise Standards in India",
     "According to the Environment (Protection) Rules and Supreme Court orders, the manufacture, sale, and use of firecrackers generating a noise level exceeding what limit at a distance of 4 meters are prohibited?",
     "125 dB(AI) or 145 dB(C)peak",
     ["75 dB(A)", "90 dB(A)", "160 dB(A)"],
     "The statutory noise limit for sound-emitting firecrackers is 125 dB(AI) or 145 dB(C)peak at 4 meters distance from the point of bursting."),
    ("match", "Common Everyday Sounds and Typical Decibel Levels",
     "Match the sound source in List I with its typical approximate decibel level in List II:",
     [("A", "Quiet rustling leaves / Gentle breathing"),
      ("B", "Normal human conversation at 1 meter"),
      ("C", "Heavy city traffic / Food blender"),
      ("D", "Jet aircraft takeoff at 50 meters distance")],
     [("I", "20 to 30 dB(A)"),
      ("II", "60 dB(A)"),
      ("III", "85 to 90 dB(A)"),
      ("IV", "140 to 150 dB(A)")],
     "A-I, B-II, C-III, D-IV",
     "Whisper/leaves ~20–30 dB, conversation ~60 dB, heavy traffic ~85–90 dB, and jet takeoff ~140–150 dB."),
    ("mcq", "Occupational Noise Safety Threshold (OSHA / Factories Act)",
     "Under the Model Factories Rules and international occupational health standards (OSHA), what is the maximum permissible continuous noise exposure for an 8-hour workday without mandatory ear protection?",
     "85 to 90 dB(A)",
     ["60 dB(A)", "110 dB(A)", "130 dB(A)"],
     "The standard occupational safety limit is 85–90 dB(A) for an 8-hour shift; for every 3–5 dB increase, permissible exposure duration is halved."),
    ("mcq", "Tinnitus Pathology and Noise Exposure",
     "Chronic exposure to excessive noise often causes a persistent, phantom acoustic ringing, buzzing, or hissing sound in the ears known clinically as:",
     "Tinnitus",
     ["Glaucoma", "Myopia", "Strabismus"],
     "Tinnitus is the perception of sound (ringing/buzzing) in the absence of an external auditory stimulus, triggered by damage to cochlear auditory neurons."),
    ("stmt", "Vehicular Horn Regulations under Central Motor Vehicle Rules",
     "Under Rule 119 of the Central Motor Vehicles Rules 1989, no motor vehicle shall be fitted with multi-toned horns giving a succession of different notes or any other shrill-sounding horn.",
     "The use of pressure horns, musical horns, and unauthorized sirens is strictly illegal across all non-emergency civilian vehicles in India.", 1,
     "Both Statement I and Statement II are correct. Pressure horns and musical multi-tone horns are legally banned under Motor Vehicle Rules to prevent acute urban noise."),
    ("mcq", "Acoustic Insulation Materials in Architecture",
     "In green architecture and sustainable building design, which materials are installed inside walls and ceilings to absorb acoustic energy and prevent sound transmission?",
     "Dense mineral rockwool, fiberglass batts, acoustic foam panels, and double-glazed insulated windows",
     ["Single-pane thin plate glass and hollow tin sheets", "Solid lead sheets painted with water-based acrylics", "Open steel mesh wire fencing"],
     "Acoustic insulation uses porous, fibrous absorbers (rockwool, fiberglass) that convert sound wave kinetic energy into heat, coupled with double-glazed window air gaps."),
    ("seq", "Enforcement Protocol for Noise Rule Violations",
     "Arrange the statutory procedural steps taken by designated law enforcement authorities upon receiving a complaint of illegal nighttime loudspeaker use:",
     ["Police receiving complaint dispatch an authorized officer equipped with a calibrated Type-1 Sound Level Meter", "On-site sound level measurement recorded at the boundary of the complainant's property establishing exceedance of standards", "Immediate seizure of unauthorized public address amplifiers, loudspeakers, and power generator equipment", "Filing of formal charges and prosecution under Section 15 of the Environment (Protection) Act 1986"],
     "I -> II -> III -> IV",
     "Enforcement follows: complaint receipt, calibrated decibel measurement, physical seizure of equipment, and prosecution under EPA 1986."),
    ("mcq", "Infrasound vs Ultrasound Frequencies",
     "Infrasound, generated by large wind turbines, earthquakes, and volcanic eruptions that can induce nausea and dizziness in humans, consists of sound frequencies:",
     "Below 20 Hertz (below the normal lower threshold of human hearing)",
     ["Between 20 Hz and 20,000 Hz", "Above 20,000 Hertz", "Exactly at 1,000,000 Hertz"],
     "Infrasound is low-frequency sound below 20 Hz (inaudible to human ears but felt as vibrations); Ultrasound is high-frequency sound above 20,000 Hz (20 kHz)."),
    ("mcq", "Wildlife Behavioral Disruption by Noise Pollution",
     "How does chronic anthropogenic noise pollution (from highways, shipping, and mining) severely disrupt wildlife ecological survival?",
     "It masks animal acoustic communication signals, preventing birds from singing to attract mates, impairing parental alarm calls, and interfering with bat and cetacean echolocation foraging",
     ["It accelerates biological mutation rates, turning birds into quadrupeds", "It increases photosynthetic efficiency of trees along the highway", "It causes all aquatic fish to lose their swimming bladders within hours"],
     "Acoustic masking drowns out mating songs, predator warning calls, and echolocation clicks in marine mammals and terrestrial birds, devastating survival and reproductive success.")
]
'''

with open('scripts/subject_generators/make_evs_s18_20.py', 'w') as f:
    f.write(s18_to_20)

print("make_evs_s18_20.py written.")
