import sys, os

out_path = "scripts/subject_generators/cs_s11_20.py"

content = '''import sys, os
sys.path.insert(0, os.getcwd())
from scripts.subject_generators.slot_helpers import mcq, stmt, ar, match, seq

def build_slot(ch, items):
    res = []
    for itm in items:
        qtype = itm[0]
        if qtype == "mcq":
            _, top, stem, corr, wrongs, expl = itm
            res.append(mcq(ch, top, stem, corr, wrongs, expl))
        elif qtype == "stmt":
            _, top, s1, s2, rel, expl = itm
            res.append(stmt(ch, top, s1, s2, rel, expl))
        elif qtype == "ar":
            _, top, a, r, rel, expl = itm
            res.append(ar(ch, top, a, r, rel, expl))
        elif qtype == "match":
            _, top, stem, l1, l2, pair, expl = itm
            res.append(match(ch, top, stem, l1, l2, pair, expl))
        elif qtype == "seq":
            _, top, stem, items_list, order_str, expl = itm
            res.append(seq(ch, top, stem, items_list, order_str, expl))
    assert len(res) == 20, f"Slot has {len(res)} items instead of 20"
    return res

CH_DS = "Data Structures: Stacks"
CH_ALGO = "Search and Sorting Algorithms"
CH_PYSQL = "Database Management and Python-SQL Connectivity"

# Slot 11: Linear Data Structures: Stack Implementation in Python
s11_raw = [
    ("mcq", "Stack Fundamental Operating Principle",
     "What foundational access principle defines a 'Stack' data structure?",
     "LIFO (Last-In, First-Out): the most recently inserted element is the first element to be removed",
     ["FIFO (First-In, First-Out)", "Random Access", "Hierarchical Tree Traversal"],
     "A stack is a linear data structure operating under the LIFO (Last-In, First-Out) principle where insertion and deletion occur at the top."),
    ("stmt", "Stack Push and Pop Implementation via List",
     "In Python, a stack can be implemented using a list where append() performs the Push operation and pop() performs the Pop operation at O(1) amortized time.",
     "Executing stack.pop() on an empty list raises a built-in IndexError representing a 'Stack Underflow' condition.", 1,
     "Both Statement I and Statement II are correct. List append and pop at the tail operate in O(1) time, and popping an empty list raises IndexError (underflow)."),
    ("ar", "Stack Overflow in Fixed-Size Implementations",
     "In fixed-capacity array implementations of a stack, attempting to push an element when the stack top equals maximum capacity triggers a 'Stack Overflow'.",
     "Stack Overflow occurs because physical memory allocated for the fixed-size stack has been completely exhausted.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Stack overflow is the error condition where insertion is attempted on a full stack structure."),
    ("match", "Stack Operations and Operational Semantics",
     "Match the stack primitive operation in List I with its operational definition in List II:",
     [("A", "Push(item)"),
      ("B", "Pop()"),
      ("C", "Peek() / Top()"),
      ("D", "IsEmpty()")],
     [("I", "Inserts a new element at the top of the stack"),
      ("II", "Removes and returns the topmost element from the stack"),
      ("III", "Returns the topmost element without removing it from the stack"),
      ("IV", "Evaluates whether the stack currently contains zero elements")],
     "A-I, B-II, C-III, D-IV",
     "Push adds to top; Pop removes and returns top; Peek inspects top without removal; IsEmpty checks for zero elements."),
    ("seq", "Stack Push-Pop State Tracing Sequence",
     "Trace the state of an initially empty stack S following these consecutive operations: Push(10), Push(20), Pop(), Push(30), Push(40), Pop():",
     [("A", "After Push(10), Push(20): Stack contents are [10, 20] with top pointing to 20"),
      ("B", "After Pop(): 20 is removed; Stack contents are [10] with top pointing to 10"),
      ("C", "After Push(30), Push(40): Stack contents are [10, 30, 40] with top pointing to 40"),
      ("D", "After final Pop(): 40 is removed; Stack final state is [10, 30] with top pointing to 30")],
     "A, B, C, D",
     "Following LIFO rules: [10, 20] -> pop removes 20 -> [10] -> pushes 30, 40 -> [10, 30, 40] -> pop removes 40 -> [10, 30].")
]

s11_extras = [
    ("Stack Underflow Definition", "What error condition occurs when a program attempts to perform a Pop or Peek operation on an empty stack?",
     "Stack Underflow",
     ["Stack Overflow", "Memory Leak", "Buffer Saturation"],
     "Stack Underflow is the error condition where deletion or inspection is attempted on a stack containing zero elements."),
    ("Peek Operation Return Value", "Given a Python stack implemented as a list S = [5, 15, 25, 35], what is returned by the Peek() function: S[-1]?",
     "35 (the topmost element, without modifying the list)",
     ["5", "25", "None"],
     "Peek/Top accesses the last inserted element (S[-1]) without removing it from the data structure."),
    ("Why Avoid insert(0, item) for Stacks", "Why is implementing a stack using list.insert(0, item) and list.pop(0) considered inefficient?",
     "Inserting and deleting at index 0 requires shifting all existing n elements, resulting in slow O(n) linear time complexity per operation",
     ["It causes a syntax error in Python 3", "It converts integers into strings", "It deletes all elements simultaneously"],
     "Modifying the front of a dynamic list forces O(n) element shifts, whereas append() and pop() at the tail operate in O(1) amortized time."),
    ("Function Call Stack in Operating Systems", "How does an operating system or runtime environment utilize a stack during function execution?",
     "To manage activation records (stack frames) storing local variables, parameters, and return addresses across nested function calls",
     ["To store permanent files on the hard disk", "To display graphics on the computer monitor", "To connect to the internet"],
     "The runtime Call Stack manages active subroutine frames, pushing records on invocation and popping upon return."),
    ("Reversing a String Using a Stack", "Why is a stack the ideal data structure to reverse an input string (e.g., 'PYTHON' to 'NOHTYP')?",
     "Pushing each character sequentially and then popping all characters naturally reverses the sequence due to LIFO behavior",
     ["Stacks sort characters in alphabetical order automatically", "Stacks double the length of strings", "Stacks delete all vowels"],
     "Pushing characters 'P','Y','T','H','O','N' and popping them off yields 'N','O','H','T','Y','P' directly."),
    ("Deque as Optimized Stack Container", "Which Python collection module provides collections.deque with guaranteed O(1) append and pop performance from both ends?",
     "collections.deque",
     ["heapq", "queue.PriorityQueue", "array.array"],
     "collections.deque (double-ended queue) provides memory-efficient, fast O(1) appends and pops from both ends."),
    ("Top Pointer Value in Empty Stack", "In an array implementation of a stack where top stores the index of the highest item, what is top initialized to for an empty stack?",
     "-1",
     ["0", "1", "None"],
     "In 0-indexed arrays, top = -1 indicates an empty stack; top = 0 indicates one item present."),
    ("Checking Empty Stack in Python", "Which expression idiomatically evaluates to True if a Python list stack S is completely empty?",
     "len(S) == 0 or not S",
     ["S is None", "S == -1", "S.empty() == 0"],
     "In Python, an empty list evaluates to False in boolean context (not S) or can be checked via len(S) == 0."),
    ("Undo Mechanism in Text Editors", "Which data structure powers the 'Undo' and 'Redo' operations in modern text editors and software applications?",
     "Stack (pushing edits on action, popping on undo)",
     ["Queue", "Binary Search Tree", "Hash Table"],
     "Undo/Redo uses twin LIFO stacks: edits are pushed onto an undo stack and popped onto a redo stack."),
    ("Web Browser Back Button Data Structure", "What data structure manages the visited URLs when a user clicks the 'Back' button in a web browser?",
     "A Stack",
     ["A Queue", "A Directed Graph", "A Min-Heap"],
     "Web browsers maintain visited URLs in a stack; clicking Back pops the current page and navigates to the previous page."),
    ("Stack Overflow Exception in Python", "In Python, what exception is raised when unbounded recursive calls consume all available stack frames?",
     "RecursionError",
     ["StackUnderflowError", "MemoryLeakError", "ArithmeticError"],
     "Excessive recursion exhausts Python\'s call stack limit, raising RecursionError: maximum recursion depth exceeded."),
    ("Size of Stack in Python", "How is the current number of elements in a Python list-based stack S determined?",
     "len(S)",
     ["S.size()", "S.count()", "size(S)"],
     "The built-in len() function returns the total number of items stored in the stack list."),
    ("Displaying Stack Elements from Top to Bottom", "Given stack S = [10, 20, 30], how can elements be printed from Top to Bottom without modifying S?",
     "for i in range(len(S) - 1, -1, -1): print(S[i])",
     ["for x in S: print(x)", "print(S[0])", "for i in range(len(S)): print(S[i])"],
     "Iterating in reverse index order (from len-1 down to 0) accesses elements from the topmost to the bottom-most."),
    ("Stack Space Complexity", "What is the auxiliary space complexity of a stack storing n elements?",
     "O(n) linear space",
     ["O(1) constant space", "O(n^2) quadratic space", "O(log n) logarithmic space"],
     "A stack storing n items requires memory directly proportional to the number of stored elements, O(n)."),
    ("Stack Definition in NCERT CS", "In NCERT Class 12 Computer Science, a stack is officially classified as what type of data structure?",
     "A Linear, Dynamic Data Structure",
     ["A Non-Linear Hierarchical Structure", "A Relational Tabular Structure", "A Static Matrix Structure"],
     "A stack is a linear data structure whose elements form a sequential order governed by LIFO discipline.")
]

# Slot 12: Stack Applications & Expression Evaluation
s12_raw = [
    ("mcq", "Infix to Postfix Notation Conversion",
     "What is the equivalent Postfix (Reverse Polish Notation) expression for the Infix expression: (A + B) * C?",
     "A B + C *",
     ["A B C + *", "+ A B * C", "A B * C +"],
     "Parenthesized (A + B) evaluates first to AB+; multiplying by C yields AB+C*."),
    ("stmt", "Postfix Expression Evaluation Rules",
     "When evaluating a Postfix expression using a stack, encountering an operand causes it to be pushed onto the stack.",
     "When an operator is encountered, two operands are popped: the first popped operand is the left operand and the second popped operand is the right operand.", 3,
     "Statement I is correct: operands are pushed. Statement II is incorrect: the FIRST popped operand is the RIGHT operand (op2), and the SECOND popped operand is the LEFT operand (op1), computing: op1 <operator> op2."),
    ("ar", "Parentheses Elimination in Postfix Notation",
     "Postfix expressions do not require parentheses to dictate operator evaluation precedence.",
     "The order of operators and operands in Postfix notation inherently specifies unambiguous evaluation order strictly from left to right.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Postfix notation is unambiguous and eliminates parentheses and precedence rules."),
    ("match", "Expression Notations and Formats",
     "Match the mathematical expression format in List I with its symbolic syntax in List II for adding A and B:",
     [("A", "Infix Notation"),
      ("B", "Postfix Notation (Reverse Polish)"),
      ("C", "Prefix Notation (Polish)"),
      ("D", "Evaluation Data Structure")],
     [("I", "A + B (operator placed between operands)"),
      ("II", "A B + (operator placed after operands)"),
      ("III", "+ A B (operator placed before operands)"),
      ("IV", "LIFO Stack")],
     "A-I, B-II, C-III, D-IV",
     "Infix places operator between; Postfix places operator after; Prefix places operator before; Stack evaluates postfix/prefix."),
    ("seq", "Evaluating Postfix Expression Step-by-Step",
     "Trace the sequential stack evaluation steps for the postfix expression: '6 3 2 + * 5 -':",
     [("A", "Push 6, push 3, push 2 onto stack -> Stack: [6, 3, 2]"),
      ("B", "Encounter '+': Pop 2 and 3, compute 3 + 2 = 5, push 5 -> Stack: [6, 5]"),
      ("C", "Encounter '*': Pop 5 and 6, compute 6 * 5 = 30, push 30 -> Stack: [30]"),
      ("D", "Push 5, encounter '-': Pop 5 and 30, compute 30 - 5 = 25, push 25 -> Final Result: 25")],
     "A, B, C, D",
     "Postfix evaluation: push 6,3,2 -> 3+2=5 -> push 5 -> 6*5=30 -> push 30 -> push 5 -> 30-5=25.")
]

s12_extras = [
    ("Evaluating 8 2 / 3 +", "What is the evaluated numerical result of the postfix expression: '8 2 / 3 +'?",
     "7 (8 / 2 = 4, followed by 4 + 3 = 7)",
     ["1", "10", "4"],
     "8 and 2 pushed; '/' computes 8 / 2 = 4; push 4; push 3; '+' computes 4 + 3 = 7."),
    ("Evaluating 10 5 - 2 *", "What is the evaluated result of the postfix expression: '10 5 - 2 *'?",
     "10 (10 - 5 = 5, followed by 5 * 2 = 10)",
     ["0", "20", "25"],
     "10 and 5 pushed; '-' pops 5 and 10, computing 10 - 5 = 5; 2 pushed; '*' computes 5 * 2 = 10."),
    ("Evaluating 7 3 * 4 2 / -", "Evaluate the postfix expression: '7 3 * 4 2 / -':",
     "19 (7 * 3 = 21, 4 / 2 = 2, 21 - 2 = 19)",
     ["23", "10", "14"],
     "7 * 3 = 21; 4 / 2 = 2; subtraction computes 21 - 2 = 19."),
    ("Balanced Parentheses Checking Algorithm", "How does a compiler use a stack to check whether parentheses in an expression are balanced (e.g., '{[()]}')?",
     "Push opening brackets onto stack; when encountering a closing bracket, pop top and verify matching bracket type; check if stack is empty at end",
     ["Count total characters and check if even", "Convert brackets into numbers and sum them", "Sort brackets alphabetically"],
     "Opening brackets are pushed; closing brackets pop the top element to verify matched pairing; empty stack at end confirms balance."),
    ("Infix to Postfix Operator Precedence", "During infix to postfix conversion, what happens when the current scanned operator has LOWER precedence than the operator on top of the stack?",
     "Operators of higher or equal precedence are repeatedly popped from the stack and appended to output before pushing the current operator",
     ["The current operator is immediately discarded", "The program crashes with a SyntaxError", "The stack is completely emptied and deleted"],
     "An operator cannot sit on top of an operator with equal or higher precedence; higher precedence operators must be popped first."),
    ("Handling Left Parenthesis in Infix to Postfix", "When scanning an Infix expression, what is done when an open parenthesis '(' is encountered?",
     "It is pushed directly onto the operator stack without checking precedence",
     ["It is appended directly to the postfix output string", "It pops all operators currently in the stack", "It raises an exception"],
     "Open parentheses '(' are pushed onto the operator stack to demarcate a new local evaluation sub-scope."),
    ("Handling Right Parenthesis in Infix to Postfix", "What action is triggered when a closing parenthesis ')' is encountered during infix to postfix conversion?",
     "All operators on the stack are popped and appended to output until a matching '(' is popped and discarded",
     ["The entire expression is evaluated to a single number", "The closing parenthesis is pushed onto the stack", "The program halts immediately"],
     "Closing parenthesis ')' triggers popping of all enclosed operators to output until the matching '(' is removed."),
    ("Infix A + B * C Postfix", "What is the postfix representation of the unparenthesized infix expression: A + B * C?",
     "A B C * + (multiplication has higher precedence than addition)",
     ["A B + C *", "+ A * B C", "A B C + *"],
     "Due to operator precedence (* before +), B * C forms BC*, which is added to A, producing ABC*+."),
    ("Infix A * B + C Postfix", "What is the postfix representation of: A * B + C?",
     "A B * C +",
     ["A B C * +", "+ * A B C", "A B C + *"],
     "A * B evaluates first to AB*, which is then added to C, yielding AB*C+."),
    ("Evaluating 5 4 + 2 * 3 /", "Evaluate the postfix expression: '5 4 + 2 * 3 /':",
     "6 (5 + 4 = 9, 9 * 2 = 18, 18 / 3 = 6)",
     ["3", "9", "12"],
     "5+4 = 9; 9*2 = 18; 18/3 = 6."),
    ("Exponentiation Operator Associativity", "How does the exponentiation operator (^) differ in associativity from addition and multiplication during infix conversion?",
     "Exponentiation is right-to-left associative (e.g., 2 ^ 3 ^ 2 = 2 ^ 9 = 512)",
     ["Exponentiation has zero precedence", "Exponentiation is left-to-right associative", "Exponentiation cannot be converted to postfix"],
     "Exponentiation (**) evaluates right-to-left; an incoming '^' does not pop an existing '^' of equal precedence."),
    ("Postfix Evaluation Operand Order Hazard", "For non-commutative operators like '-' and '/', why is preserving the exact pop order critical in postfix evaluation?",
     "Because popping top as b and next as a computes a - b or a / b; reversing them yields incorrect arithmetic results",
     ["Because computers cannot divide numbers backwards", "Because the stack will overflow", "Because negative numbers are illegal"],
     "First popped is the right operand (op2); second popped is the left operand (op1). Computing op1 - op2 is mandatory."),
    ("Prefix to Infix Scanning Direction", "When evaluating a Prefix expression (+ A B) using a stack, in which direction is the expression scanned?",
     "From right to left (from end to beginning)",
     ["From left to right", "From the center outwards", "In random order"],
     "Prefix expressions are scanned from right to left; operands are pushed, and operators pop the required operands."),
    ("Evaluating 20 4 / 2 3 * +", "Evaluate the postfix expression: '20 4 / 2 3 * +':",
     "11 (20 / 4 = 5, 2 * 3 = 6, 5 + 6 = 11)",
     ["15", "10", "26"],
     "20 / 4 = 5; 2 * 3 = 6; 5 + 6 = 11."),
    ("Compiler Syntax Parsing Role", "Why do programming language compilers convert human-written infix code into postfix/abstract syntax trees?",
     "Postfix notation can be directly evaluated in linear O(n) time by hardware execution stacks without backtracking or precedence parsing",
     ["To make the code look secret from hackers", "To make source files larger", "To prevent code from running on other computers"],
     "Postfix represents linear, unambiguous machine instruction order directly executable on hardware operand stacks.")
]

# Slot 13: Linear Search & Binary Search Algorithms
s13_raw = [
    ("mcq", "Binary Search Mandatory Precondition",
     "What strict structural precondition must be satisfied by a list before the Binary Search algorithm can be applied?",
     "The elements of the list must be arranged in sorted order (ascending or descending)",
     ["The list must contain only positive prime numbers", "The list length must be an exact power of 2", "The list must be implemented as a linked chain"],
     "Binary search operates by halving the search space based on relative magnitude, strictly requiring sorted elements."),
    ("stmt", "Linear vs Binary Search Time Complexities",
     "Linear Search has a worst-case time complexity of O(n) and operates effectively on both unsorted and sorted lists.",
     "Binary Search has a worst-case time complexity of O(log n) because it halves the remaining search space with each comparison.", 1,
     "Both Statement I and Statement II are correct. Linear search is O(n) on arbitrary lists; Binary search is O(log n) on sorted lists."),
    ("ar", "Binary Search Midpoint Calculation Formula",
     "In binary search implementations, calculating the midpoint index using mid = low + (high - low) // 2 is preferred over mid = (low + high) // 2.",
     "The formula mid = low + (high - low) // 2 avoids potential integer arithmetic overflow when low and high are extremely large integers in languages like C/Java.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). While Python handles arbitrary integers, the overflow-safe formula is standard algorithmic best practice."),
    ("match", "Search Algorithms and Operational Characteristics",
     "Match the search concept in List I with its algorithmic property in List II:",
     [("A", "Linear Search Best Case"),
      ("B", "Linear Search Worst Case"),
      ("C", "Binary Search Best Case"),
      ("D", "Binary Search Worst Case")],
     [("I", "O(1) (target element found at the very first index position 0)"),
      ("II", "O(n) (target element at the last index or absent entirely)"),
      ("III", "O(1) (target element located at the exact initial midpoint)"),
      ("IV", "O(log n) (search space repeatedly halved until low > high)")],
     "A-I, B-II, C-III, D-IV",
     "Linear best is O(1) at index 0, worst O(n); Binary best is O(1) at mid, worst O(log n)."),
    ("seq", "Binary Search Algorithm Execution Steps",
     "Arrange the sequential execution steps of Binary Search searching for target 'key' in sorted list L with bounds low and high:",
     [("A", "Initialize low = 0 and high = len(L) - 1"),
      ("B", "While low <= high, compute midpoint index mid = (low + high) // 2"),
      ("C", "If L[mid] == key, return mid (successful search termination)"),
      ("D", "If L[mid] < key set low = mid + 1; else set high = mid - 1; if loop ends return -1")],
     "A, B, C, D",
     "Binary search: set bounds -> compute mid -> test equality -> adjust bounds based on magnitude -> return -1 if exhausted.")
]

s13_extras = [
    ("Binary Search Maximum Comparisons for N=1000", "What is the maximum number of comparisons required by Binary Search to search a sorted list of 1,000 elements?",
     "10 comparisons (since 2^10 = 1024 >= 1000)",
     ["500 comparisons", "1,000 comparisons", "100 comparisons"],
     "Maximum comparisons in binary search = ceil(log2(n)). For n=1000, 2^10 = 1024, so maximum 10 comparisons are needed."),
    ("Linear Search Comparisons on Absent Key", "In an unsorted list of 500 items, how many comparisons does Linear Search perform to confirm an element is absent?",
     "500 comparisons (it must inspect every single element)",
     ["1 comparison", "250 comparisons", "9 comparisons"],
     "In an unsorted list, confirming absence requires an exhaustive search of all n elements (500 comparisons)."),
    ("Midpoint Calculation in Binary Search", "For a sorted list of length 15 (indices 0 to 14), what is the first midpoint index examined by mid = (low + high) // 2?",
     "Index 7 ((0 + 14) // 2 = 7)",
     ["Index 8", "Index 0", "Index 14"],
     "Mid = (0 + 14) // 2 = 7; the element at index 7 is examined first."),
    ("Binary Search Trace Next Interval", "Searching for key=45 in sorted list [10, 20, 30, 40, 50, 60, 70] (low=0, high=6, mid=3 with L[3]=40). What are the next low and high values?",
     "low = 4, high = 6 (since key 45 > 40, search moves to the right subarray)",
     ["low = 0, high = 2", "low = 3, high = 6", "low = 4, high = 4"],
     "Because target 45 > L[mid] (40), the target must reside in the right half; low is updated to mid + 1 = 4."),
    ("Search on Unsorted Data Trade-off", "When searching an unsorted list of 1,000 elements only once, why is Linear Search preferred over sorting followed by Binary Search?",
     "Linear search takes O(n) ~ 1000 ops, whereas sorting first takes O(n log n) ~ 10,000 ops, making sorting for a single search wasteful",
     ["Binary search cannot run on modern computers", "Linear search is always faster than binary search in all situations", "Sorting deletes all elements"],
     "Sorting overhead (O(n log n)) is justified only if multiple amortized searches will be performed on the same dataset."),
    ("Binary Search on Descending List", "If a sorted list is in descending order, how is the comparison branch modified in binary search?",
     "If key > L[mid], search moves left (high = mid - 1); if key < L[mid], search moves right (low = mid + 1)",
     ["The list must be deleted and rewritten", "No modification is needed; code works identically", "Binary search is impossible on descending lists"],
     "In descending arrays, larger values reside at lower indices, reversing the sub-array traversal directions."),
    ("Recursive Binary Search Base Case", "In a recursive binary search function def bsearch(L, low, high, key):, what base condition indicates failure (not found)?",
     "if low > high: return -1",
     ["if len(L) == 0: return -1", "if low == high: return -1", "if key < 0: return -1"],
     "When the search interval collapses such that low exceeds high, the search space is exhausted and the key is absent."),
    ("Number of Comparisons for N=1 Million", "Approximately how many comparisons are needed in the worst case to search 1,000,000 sorted records using Binary Search?",
     "Approximately 20 comparisons (2^20 = 1,048,576)",
     ["500,000 comparisons", "1,000,000 comparisons", "10,000 comparisons"],
     "Log2(1,000,000) is approximately 19.93, requiring at most 20 comparisons."),
    ("Space Complexity of Iterative Binary Search", "What is the auxiliary space complexity of iterative Binary Search?",
     "O(1) constant space (only pointers low, high, and mid are maintained)",
     ["O(n) linear space", "O(log n) space", "O(n^2) space"],
     "Iterative binary search uses constant auxiliary memory (O(1)) since it updates pointer indices in-place without call stack recursion."),
    ("Linear Search Implementation in Python", "Which built-in Python operator implements a linear search under the hood across a list?",
     "The 'in' operator (e.g., if item in my_list:)",
     ["The 'is' operator", "The '+' operator", "The '==' operator"],
     "The 'item in list' statement performs a sequential linear scan across elements from index 0 to len-1."),
    ("Index Method of Python List", "What happens when list.index(x) is called and x is NOT present in the list?",
     "It raises a ValueError: x is not in list",
     ["It returns -1", "It returns None", "It appends x to the list"],
     "Unlike find() on strings, list.index() raises ValueError if the target element is absent."),
    ("Binary Search Failure Condition in Loop", "In the standard loop while low <= high:, what terminates the loop if the target is not in the array?",
     "low becomes greater than high (low > high)",
     ["high becomes negative only", "low becomes equal to high", "mid becomes zero"],
     "When sub-array bounds cross (low > high), the search interval becomes invalid, exiting the loop."),
    ("Sentinel Linear Search Concept", "What is a 'Sentinel Linear Search'?",
     "Placing the target key at the end of the array to eliminate the index boundary check (i < n) in the inner loop",
     ["Searching using two pointers simultaneously", "Searching only even numbers", "Searching a database on satellite networks"],
     "A sentinel search appends the key as a sentinel at the tail, removing the loop bound condition and reducing inner loop instructions."),
    ("Ternary Search Comparison", "How does Ternary Search divide the search space, and how many comparisons does it perform per step?",
     "It divides the sorted range into 3 equal parts using two midpoints, performing up to 2 comparisons per step",
     ["It divides into 10 parts", "It searches 3 lists simultaneously", "It operates only on prime numbers"],
     "Ternary search splits the search interval into three segments with two midpoints (m1, m2), eliminating 2/3 of the space per step."),
    ("Linear Search on Dictionaries", "When checking if a key exists in a Python dictionary using 'key in dict', is the search linear or constant time?",
     "O(1) average constant time because Python dictionaries use hash tables, not linear search",
     ["O(n) linear time", "O(log n) logarithmic time", "O(n^2) quadratic time"],
     "Dictionary key lookups use hash indexing, yielding O(1) average time compared to O(n) linear list scans.")
]

# Slot 14: Bubble Sort Algorithm
s14_raw = [
    ("mcq", "Bubble Sort Core Mechanism",
     "What is the fundamental mechanical operation executed during each pass of the Bubble Sort algorithm?",
     "Repeatedly comparing adjacent elements and swapping them if they are in the wrong order, causing the largest unsorted element to 'bubble up' to its correct position",
     ["Finding the minimum element and placing it at the front", "Inserting each element into an already sorted subarray", "Dividing the array into two halves recursively"],
     "Bubble sort steps through the list, comparing adjacent pairs and swapping out-of-order items so the largest item settles at the end each pass."),
    ("stmt", "Bubble Sort Passes and Total Comparisons",
     "To sort an array of n elements using standard Bubble Sort, exactly n - 1 passes are required in the worst case.",
     "The total number of comparisons in an unoptimized Bubble Sort of n elements is n × (n - 1) / 2, yielding O(n²) time complexity.", 1,
     "Both Statement I and Statement II are correct. n elements require n-1 passes; total comparisons = (n-1) + (n-2) + ... + 1 = n(n-1)/2 = O(n²)."),
    ("ar", "Optimized Bubble Sort Early Termination",
     "Bubble Sort can be optimized to achieve O(n) linear time complexity when the input array is already sorted.",
     "By utilizing a boolean flag ('swapped = False') that tracks whether any swap occurred during a pass, the algorithm terminates immediately if a pass completes with zero swaps.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). If no swaps occur in a pass, the list is already sorted, allowing immediate early exit in O(n) time."),
    ("match", "Bubble Sort Complexities and Metrics",
     "Match the Bubble Sort complexity scenario in List I with its metric in List II for an array of n elements:",
     [("A", "Worst-case Time Complexity"),
      ("B", "Best-case Time Complexity (Optimized)"),
      ("C", "Average-case Time Complexity"),
      ("D", "Auxiliary Space Complexity")],
     [("I", "O(n²) (reverse sorted array requiring n(n-1)/2 swaps)"),
      ("II", "O(n) (already sorted array terminating after 1 pass)"),
      ("III", "O(n²)"),
      ("IV", "O(1) (in-place sorting requiring no extra memory)")],
     "A-I, B-II, C-III, D-IV",
     "Worst is O(n²); Optimized best is O(n); Average is O(n²); Auxiliary space is O(1) in-place."),
    ("seq", "Bubble Sort Pass 1 Execution Trace",
     "Trace the step-by-step swaps during Pass 1 of Bubble Sort on the array: [50, 20, 40, 10, 30]:",
     [("A", "Compare 50 and 20: 50 > 20 -> Swap -> Array: [20, 50, 40, 10, 30]"),
      ("B", "Compare 50 and 40: 50 > 40 -> Swap -> Array: [20, 40, 50, 10, 30]"),
      ("C", "Compare 50 and 10: 50 > 10 -> Swap -> Array: [20, 40, 10, 50, 30]"),
      ("D", "Compare 50 and 30: 50 > 30 -> Swap -> Array: [20, 40, 10, 30, 50] (50 is now in its final sorted position)")],
     "A, B, C, D",
     "Pass 1 pushes largest element (50) to the end: [50,20] swap -> [50,40] swap -> [50,10] swap -> [50,30] swap -> 50 fixed at end.")
]

s14_extras = [
    ("Comparisons in Pass k of Bubble Sort", "In pass i (where i ranges from 0 to n-2) of Bubble Sort on an array of length n, how many adjacent comparisons are performed?",
     "n - 1 - i comparisons",
     ["n comparisons", "i comparisons", "n / 2 comparisons"],
     "Because each pass i permanently fixes the largest remaining element at the end, the inner loop only needs n - 1 - i comparisons."),
    ("Stability of Bubble Sort", "Is Bubble Sort a 'Stable' sorting algorithm, and why?",
     "Yes, it is stable because equal elements are never swapped (comparison uses strict inequality >), preserving their relative initial order",
     ["No, bubble sort shuffles equal elements randomly", "Stability depends on the computer brand", "No sorting algorithm is ever stable"],
     "Bubble sort preserves relative order of duplicate keys because adjacent swaps occur only when left > right."),
    ("Bubble Sort on Already Sorted Array", "How many comparisons and swaps are performed by optimized Bubble Sort on [1, 2, 3, 4, 5]?",
     "4 comparisons and 0 swaps (terminates after Pass 1 due to swapped flag)",
     ["10 comparisons and 10 swaps", "0 comparisons and 0 swaps", "20 comparisons and 4 swaps"],
     "For n=5 already sorted, Pass 1 checks 4 adjacent pairs, performs 0 swaps, detects swapped==False, and terminates."),
    ("Bubble Sort on Reverse Sorted Array", "For an array of 5 elements sorted in reverse order [5, 4, 3, 2, 1], how many total swaps occur during Bubble Sort?",
     "10 swaps (5 × 4 / 2 = 10)",
     ["4 swaps", "5 swaps", "20 swaps"],
     "In reverse order, every single comparison triggers a swap: 4 + 3 + 2 + 1 = 10 total swaps."),
    ("In-Place Sorting Definition", "What does it mean that Bubble Sort is an 'In-Place' sorting algorithm?",
     "It sorts the elements within the original array without requiring significant additional auxiliary memory (auxiliary space O(1))",
     ["It can only sort numbers that are smaller than 10", "It creates five temporary copies of the array in RAM", "It can only run in the cloud"],
     "In-place sorting modifies the input array directly using a constant amount O(1) of extra memory."),
    ("Outer Loop Range in Python Bubble Sort", "What is the standard range for the outer loop variable i in Python Bubble Sort for list L of length n?",
     "for i in range(n - 1):",
     ["for i in range(n * n):", "for i in range(1):", "for i in range(n + 1):"],
     "An array of n elements requires at most n - 1 passes, standardly indexed as range(n - 1)."),
    ("Inner Loop Range in Python Bubble Sort", "What is the standard range for the inner loop variable j in pass i of Bubble Sort?",
     "for j in range(n - 1 - i):",
     ["for j in range(n):", "for j in range(i):", "for j in range(n + i):"],
     "The inner loop runs from index 0 up to n - 1 - i, avoiding already sorted elements at the tail."),
    ("Adjacent Swap Code in Python", "What is the idiomatic Python statement to swap adjacent elements L[j] and L[j+1] without a temporary variable?",
     "L[j], L[j+1] = L[j+1], L[j]",
     ["swap(L[j], L[j+1])", "L[j] == L[j+1]", "L[j] = L[j+1]"],
     "Python supports simultaneous tuple assignment: L[j], L[j+1] = L[j+1], L[j]."),
    ("Descending Bubble Sort Comparison", "To sort an array in descending order using Bubble Sort, what condition triggers a swap between L[j] and L[j+1]?",
     "if L[j] < L[j+1]:",
     ["if L[j] > L[j+1]:", "if L[j] == L[j+1]:", "if L[j] != L[j+1]:"],
     "To sort descending (largest to smallest), swap when the left element is smaller than the right element (L[j] < L[j+1])."),
    ("Why Bubble Sort is Inefficient for Large Data", "Why is Bubble Sort considered impractical for enterprise production systems sorting millions of records?",
     "Its quadratic O(n²) time complexity requires trillions of operations for large n, whereas O(n log n) algorithms like Merge Sort run in seconds",
     ["Bubble sort is strictly illegal under international software patents", "Bubble sort can only run on 8-bit computers", "Bubble sort cannot sort floating point numbers"],
     "For n = 1,000,000, n² is 10^12 operations, making O(n²) algorithms prohibitively slow compared to O(n log n)."),
    ("Number of Elements Fixed Per Pass", "In standard Bubble Sort, exactly how many elements are guaranteed to reach their final sorted position after k passes?",
     "At least k elements",
     ["All n elements", "0 elements", "n / k elements"],
     "Each pass bubbles the largest remaining element to its terminal position; hence k passes guarantee at least k elements are fixed."),
    ("Total Passes for Array of 10 Elements", "What is the maximum number of passes executed by Bubble Sort on an array of 10 elements?",
     "9 passes (n - 1 = 10 - 1 = 9)",
     ["10 passes", "100 passes", "5 passes"],
     "An array of size n requires at most n - 1 passes, because when n - 1 elements are placed, the remaining element is automatically in place."),
    ("Bidirectional Bubble Sort (Cocktail Sort)", "What variation of Bubble Sort traverses alternatively in both directions (left-to-right, then right-to-left)?",
     "Cocktail Shaker Sort (Bidirectional Bubble Sort)",
     ["Insertion Sort", "Quick Sort", "Radix Sort"],
     "Cocktail shaker sort traverses forward to bubble the maximum, then backward to bubble the minimum, addressing 'turtle' small elements."),
    ("Number of Swaps on Equal Elements", "If an array contains identical duplicate values [7, 7, 7, 7], how many swaps are executed by Bubble Sort?",
     "0 swaps (since 7 > 7 is False, no swaps occur)",
     ["16 swaps", "6 swaps", "1 swap"],
     "The comparison if L[j] > L[j+1] evaluates to False for duplicate values, resulting in zero swaps."),
    ("Bubble Sort Analogy Origin", "Why is the algorithm named 'Bubble Sort'?",
     "Because smaller/larger elements gradually 'bubble' up to the top or bottom of the list during successive passes like air bubbles in water",
     ["Because it was invented by a soap bubble manufacturing company", "Because the computer screen displays bubbles while sorting", "Because it operates inside a circular memory bubble"],
     "The name derives from the visual metaphor of elements bubbling to their appropriate positions across passes.")
]

# Slot 15: Insertion Sort Algorithm
s15_raw = [
    ("mcq", "Insertion Sort Conceptual Metaphor",
     "Which real-world analogy best describes the working principle of the Insertion Sort algorithm?",
     "Sorting a hand of playing cards: picking cards one by one and inserting each into its correct relative position among the already sorted cards",
     ["Pouring water through a sieve", "Arranging books by color", "Rolling dice until matching numbers appear"],
     "Insertion sort mimics card sorting: the array is conceptually split into a sorted and an unsorted subarray; items are inserted into the sorted portion."),
    ("stmt", "Insertion Sort Subarray Dynamics",
     "Insertion Sort maintains two virtual subarrays: a sorted subarray on the left and an unsorted subarray on the right.",
     "In each pass, the first element of the unsorted subarray (the 'key') is picked and shifted into its correct sorted position by shifting larger elements one position to the right.", 1,
     "Both Statement I and Statement II are correct. Insertion sort picks the key from the unsorted segment, shifts larger sorted elements rightward, and places the key."),
    ("ar", "Insertion Sort Best-Case Efficiency",
     "Insertion Sort achieves an optimal best-case time complexity of O(n) when applied to an already sorted array.",
     "When the array is already sorted, the while loop condition (L[j] > key) fails immediately on the first check for every element, performing exactly n - 1 comparisons and 0 shifts.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). On presorted data, each key is compared once against its immediate left neighbor and immediately placed."),
    ("match", "Insertion Sort Operational Metrics",
     "Match the Insertion Sort complexity scenario in List I with its metric in List II for an array of n elements:",
     [("A", "Worst-case Time Complexity"),
      ("B", "Best-case Time Complexity"),
      ("C", "Number of Passes (Outer Loop)"),
      ("D", "Auxiliary Space Complexity")],
     [("I", "O(n²) (reverse sorted array requiring maximum element shifts)"),
      ("II", "O(n) (already sorted array requiring 1 comparison per item)"),
      ("III", "n - 1 passes (outer loop runs from index 1 to n - 1)"),
      ("IV", "O(1) (in-place sorting requiring no extra array allocation)")],
     "A-I, B-II, C-III, D-IV",
     "Worst is O(n²); Best is O(n); Passes is n-1; Auxiliary space is O(1) in-place."),
    ("seq", "Insertion Sort Execution Trace on [40, 30, 20, 10]",
     "Trace the state of the array [40, 30, 20, 10] after each insertion pass from index 1 to index 3:",
     [("A", "Initial state: [40] is sorted; unsorted segment is [30, 20, 10]"),
      ("B", "Pass 1 (key=30): Shift 40 right, insert 30 -> Array: [30, 40, 20, 10]"),
      ("C", "Pass 2 (key=20): Shift 40 and 30 right, insert 20 -> Array: [20, 30, 40, 10]"),
      ("D", "Pass 3 (key=10): Shift 40, 30, and 20 right, insert 10 -> Array: [10, 20, 30, 40]")],
     "A, B, C, D",
     "Insertion sort passes: start [40] -> insert 30 yields [30,40] -> insert 20 yields [20,30,40] -> insert 10 yields [10,20,30,40].")
]

s15_extras = [
    ("Starting Index of Outer Loop", "In Python Insertion Sort, why does the outer loop start at index 1 (for i in range(1, len(L))) rather than index 0?",
     "A single element at index 0 is inherently sorted by definition, so the first unsorted element to insert is at index 1",
     ["Index 0 cannot be accessed in Python", "Index 0 is reserved for hardware memory addresses", "Because Python lists cannot hold numbers at index 0"],
     "An array of length 1 is trivially sorted; the algorithm begins by inserting the element at index 1 into the sub-list L[0]."),
    ("While Loop Shift Condition in Insertion Sort", "What dual conditions govern the inner while loop during Insertion Sort: while j >= 0 and L[j] > key:?",
     "Ensures index j does not go out of bounds on the left (j >= 0) and continues shifting elements right as long as they are greater than the key",
     ["Ensures j is an even number", "Checks if the computer has enough battery", "Verifies the list has no duplicate strings"],
     "The inner loop decrements j while checking j >= 0 to prevent index errors and L[j] > key to shift elements greater than key."),
    ("Final Placement Statement", "After the inner while loop terminates in Insertion Sort, what statement places the key in its correct position?",
     "L[j + 1] = key",
     ["L[j] = key", "L[i] = key", "L[0] = key"],
     "When the loop exits, j points to the element smaller than key (or -1); the key belongs immediately to the right at index j + 1."),
    ("Stability of Insertion Sort", "Is Insertion Sort a 'Stable' sorting algorithm?",
     "Yes, it is stable because elements with equal keys are not shifted past one another (shift occurs strictly when L[j] > key)",
     ["No, insertion sort always reverses equal keys", "Only when sorting floating point numbers", "No, stability applies only to binary search"],
     "The strict inequality L[j] > key halts shifting when an identical element is reached, preserving original relative order."),
    ("Insertion Sort for Nearly-Sorted Data", "Why is Insertion Sort widely used in hybrid algorithms (like Timsort in Python) for small or nearly-sorted data?",
     "It operates in near O(n) linear time with ultra-low overhead on small arrays (typically n < 32) and datasets with few inversions",
     ["It uses zero computer memory whatsoever", "It is the only algorithm allowed in Python", "It can sort data without reading it"],
     "Low constant factor overhead and O(n) performance on presorted data make insertion sort ideal for small partitions in hybrid algorithms."),
    ("Reverse Sorted Array Worst-Case Shifts", "For an array of n elements sorted in reverse order, how many element shifts are performed by Insertion Sort?",
     "n × (n - 1) / 2 shifts",
     ["n shifts", "n - 1 shifts", "2 × n shifts"],
     "In reverse order, element i must shift past all i preceding elements: 1 + 2 + ... + (n-1) = n(n-1)/2 shifts."),
    ("Number of Comparisons for [10, 20, 30, 40]", "How many comparisons does Insertion Sort perform on the already sorted list [10, 20, 30, 40]?",
     "3 comparisons (exactly 1 comparison per pass for 3 passes)",
     ["12 comparisons", "6 comparisons", "0 comparisons"],
     "For n=4 sorted items, passes i=1, 2, 3 each execute exactly one comparison (L[j] > key is false) and terminate."),
    ("Insertion Sort In-Place Property", "What is the auxiliary memory required by Insertion Sort during execution?",
     "O(1) constant auxiliary space (only the scalar variable 'key' and loop indices are stored)",
     ["O(n) linear space", "O(n^2) space", "O(log n) space"],
     "Insertion sort is an in-place algorithm requiring only a handful of temporary index and scalar storage variables, O(1)."),
    ("Online Sorting Capability", "Why is Insertion Sort classified as an 'Online Algorithm'?",
     "It can process and sort a stream of data elements piece-by-piece as they arrive in real-time, without having the entire dataset upfront",
     ["It requires an active internet connection to function", "It uploads all sorted data to online websites", "It works only on web browsers"],
     "An online algorithm can incorporate new incoming elements one-by-one into an already sorted list without re-running from scratch."),
    ("Number of Outer Loop Iterations for N=50", "How many times does the outer for loop execute when sorting an array of 50 elements using Insertion Sort?",
     "49 times (from index 1 to index 49)",
     ["50 times", "25 times", "2500 times"],
     "The outer loop iterates across indices 1 through n-1, executing exactly n - 1 = 49 times."),
    ("Tracing Insertion Sort on [9, 5, 1, 4, 3]", "In sorting [9, 5, 1, 4, 3], what is the state of the array after Pass 1 (inserting 5)?",
     "[5, 9, 1, 4, 3]",
     ["[1, 5, 9, 4, 3]", "[9, 5, 1, 3, 4]", "[5, 1, 4, 3, 9]"],
     "Pass 1: key=5; 9 is shifted right; 5 is placed at index 0 -> [5, 9, 1, 4, 3]."),
    ("Difference Between Shifting and Swapping", "How does Insertion Sort's element displacement mechanism differ from Bubble Sort?",
     "Insertion Sort shifts elements one position right using assignments (L[j+1] = L[j]), whereas Bubble Sort executes full 3-step swaps",
     ["Bubble sort deletes elements while insertion sort adds elements", "Insertion sort requires double memory", "There is zero difference between them"],
     "A single assignment shift uses fewer memory bus writes than a 3-statement swap, making insertion sort practically faster than bubble sort."),
    ("Descending Insertion Sort Condition", "To sort a list in descending order using Insertion Sort, how is the while loop condition modified?",
     "while j >= 0 and L[j] < key:",
     ["while j >= 0 and L[j] > key:", "while j > 0 and L[j] == key:", "while j < len(L):"],
     "For descending order, elements smaller than the key are shifted right: while j >= 0 and L[j] < key:."),
    ("Worst-Case Array Configuration", "Which initial configuration represents the worst-case input for Insertion Sort?",
     "An array arranged in strictly reverse sorted order",
     ["An already sorted array", "An array with all identical elements", "An array containing random floating-point numbers"],
     "In reverse sorted order, every element must shift across the entire sorted prefix, producing maximal quadratic O(n²) operations."),
    ("Comparison Count on Uniform Duplicate Array", "How many comparisons does Insertion Sort perform on an array of identical elements [5, 5, 5, 5, 5]?",
     "4 comparisons (1 comparison per pass, since 5 > 5 is False)",
     ["25 comparisons", "10 comparisons", "0 comparisons"],
     "Because L[j] > key is immediately False when comparing equal values, the inner loop terminates after 1 check per pass (4 total).")
]

# Slot 16: Python-SQL Connectivity: Database Connection & Cursor
s16_raw = [
    ("mcq", "Database Connection Module in Python",
     "Which standard database connector module is utilized in Python to establish communication with a MySQL relational database server?",
     "mysql.connector",
     ["sql.database", "python.sql", "mysql.interface"],
     "The mysql.connector module provides the standard API to connect, execute SQL statements, and retrieve datasets from MySQL."),
    ("stmt", "connect() Parameters and Credentials",
     "The mysql.connector.connect() function requires parameter arguments including host, user, password, and optionally database.",
     "The is_connected() method of a MySQLConnection object returns a boolean indicating whether the database socket connection remains active.", 1,
     "Both Statement I and Statement II are correct. connect() establishes the authenticated session; is_connected() verifies socket health."),
    ("ar", "Cursor Object Role in Database Interface",
     "In Python database programming, SQL queries are executed through a 'Cursor' object rather than directly on the connection object.",
     "The Cursor acts as a database control structure that maintains the query execution context and traverses the returned result-set rows.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The cursor encapsulates SQL query transmission and result-set buffer navigation."),
    ("match", "Python-SQL Connectivity Entities and Roles",
     "Match the database interface entity in List I with its operational function in List II:",
     [("A", "mysql.connector.connect()"),
      ("B", "connection.cursor()"),
      ("C", "connection.close()"),
      ("D", "cursor.close()")],
     [("I", "Establishes an authenticated communication session with the MySQL database server"),
      ("II", "Instantiates a cursor object used to execute SQL statements and fetch results"),
      ("III", "Terminates the network socket session and releases database server connections"),
      ("IV", "Closes the query execution context and frees server-side memory buffers")],
     "A-I, B-II, C-III, D-IV",
     "connect opens session; cursor creates query interface; connection.close shuts session; cursor.close frees cursor buffers."),
    ("seq", "Python-MySQL Connection Initialization Sequence",
     "Arrange the correct sequence of steps for establishing an authenticated database session in Python:",
     [("A", "Import the connector module using 'import mysql.connector'"),
      ("B", "Invoke mysql.connector.connect(host='localhost', user='root', password='mypassword')"),
      ("C", "Verify connection integrity by testing 'if conn.is_connected():'"),
      ("D", "Instantiate the query cursor using 'cur = conn.cursor()'")],
     "A, B, C, D",
     "Connection initialization: import module -> connect with credentials -> verify with is_connected() -> create cursor.")
]

s16_extras = [
    ("Default Host Parameter", "What hostname string is standardly used when connecting to a MySQL server running on the local machine?",
     "'localhost' or '127.0.0.1'",
     ["'www.mysql.com'", "'remote_server'", "'0.0.0.0'"],
     "'localhost' or the loopback IP '127.0.0.1' points to the local host machine running the MySQL server daemon."),
    ("Default MySQL Port", "What is the standard default TCP network port utilized by MySQL database servers?",
     "Port 3306",
     ["Port 80", "Port 21", "Port 8080"],
     "MySQL listens by default on TCP port 3306 for incoming client connections."),
    ("Handling Connection Failure", "Which exception class from mysql.connector catches failed connection attempts (e.g., incorrect password or offline server)?",
     "mysql.connector.Error",
     ["ConnectionTimeoutError", "DatabaseAbsentError", "SQLSyntaxError"],
     "mysql.connector.Error is the base exception class catching authentication, connection, and query execution failures."),
    ("Selecting Database After Connection", "If the 'database' argument is omitted in connect(), how can a database be selected later in Python?",
     "By executing cur.execute('USE school_db;') or setting conn.database = 'school_db'",
     ["By restarting the operating system", "By renaming the Python script file", "A database cannot be selected after connection"],
     "A database can be selected dynamically by executing 'USE db_name' via cursor or setting connection.database."),
    ("Dictionary Cursor Option", "How can a MySQL cursor be configured to return fetched rows as dictionaries ({col_name: value}) instead of tuples?",
     "cur = conn.cursor(dictionary=True)",
     ["cur = conn.dict_cursor()", "cur = conn.cursor(type='dict')", "cur = conn.cursor(json=True)"],
     "Passing dictionary=True to conn.cursor() formats fetched records as Python dictionaries mapping column names to row values."),
    ("Buffered Cursor Purpose", "Why is a 'buffered cursor' (cursor = conn.cursor(buffered=True)) useful in Python-MySQL connectivity?",
     "It fetches the entire result set immediately from the server into local memory, preventing 'Unread result found' errors when executing subsequent queries",
     ["It encrypts all database passwords", "It speeds up the computer's CPU", "It deletes duplicate rows automatically"],
     "Buffered cursors pull all results into memory at query time, freeing the connection socket for subsequent query executions."),
    ("Closing Resources Protocol", "In what order should database resources be closed upon completing operations?",
     "Close the cursor first (cur.close()), followed by the connection (conn.close())",
     ["Close the connection first, then the cursor", "Only close the operating system", "Never close cursors"],
     "Best practice closes child resources first: close the cursor to release query handles, then close the parent database connection."),
    ("Checking Connection Object Type", "What type of object does mysql.connector.connect() return upon successful authentication?",
     "mysql.connector.connection_cext.CMySQLConnection (or MySQLConnection)",
     ["A text file object", "A boolean True", "A string containing the SQL version"],
     "connect() returns a MySQLConnection instance representing the active client-server session."),
    ("Multiple Cursors on Single Connection", "Can a single active MySQL database connection have multiple distinct cursor objects open simultaneously?",
     "Yes, multiple cursors can be instantiated on a single connection to manage separate query streams",
     ["No, only one cursor is permitted per database server worldwide", "Only if the database is in read-only mode", "Only on Sundays"],
     "A single database connection can spawn multiple cursors, though managing concurrent unbuffered queries requires care."),
    ("Executing Multi-Statement Scripts", "By default, does cursor.execute() allow executing multiple semicolon-separated SQL statements in a single call?",
     "No, multi-statement execution is disabled by default for security, but can be enabled via multi=True in execute()",
     ["Yes, execute() always runs unlimited statements", "No, multi-statements are strictly illegal in all databases", "Only on Linux systems"],
     "To prevent SQL injection multi-query attacks, multi-statements require explicit activation via cursor.execute(query, multi=True)."),
    ("Testing is_connected() Output", "What data type is returned by connection.is_connected()?",
     "bool (True if connected, False if disconnected)",
     ["str ('connected' or 'disconnected')", "int (1 or 0)", "None"],
     "is_connected() performs a heartbeat check and returns True if the connection socket remains open, else False."),
    ("Connection Pooling Concept", "What is 'Connection Pooling' in enterprise Python database applications?",
     "Maintaining a cache of pre-established reusable database connections to avoid the expensive overhead of creating new connections per request",
     ["Submerging server hardware in cooling water", "Combining five databases into one single table", "Running queries on swimming pool sensors"],
     "Connection pools maintain warm, authenticated database sockets, eliminating TCP handshake overhead on high-frequency queries."),
    ("Importing Error Submodule", "What is the standard syntax to import the error handler submodule in mysql.connector?",
     "from mysql.connector import Error",
     ["import Error from mysql", "from mysql import exceptions", "import mysql_error"],
     "Programmers standardly write 'from mysql.connector import Error' to catch and inspect MySQL errno and msg attributes."),
    ("Autocommit Property in Connection", "What does setting connection.autocommit = True accomplish in Python?",
     "It automatically commits every data modification statement (INSERT, UPDATE, DELETE) immediately without requiring manual conn.commit()",
     ["It automatically deletes the database every night", "It types SQL code automatically", "It prevents any writing to the database"],
     "Enabling autocommit automatically sends COMMIT after every DML statement, making modifications permanent immediately."),
    ("MySQL Connector Installation Tool", "Which command-line package manager is used to install the official MySQL connector for Python?",
     "pip install mysql-connector-python",
     ["apt install python-sql", "npm install mysql", "python install database"],
     "The official Oracle MySQL connector package is installed into Python environments using 'pip install mysql-connector-python'.")
]

# Slot 17: Python-SQL Connectivity: Executing Queries & Data Retrieval
s17_raw = [
    ("mcq", "fetchone() vs fetchall() Return Types",
     "What are the respective return types and values of cursor.fetchone() and cursor.fetchall() after executing a SELECT query in Python?",
     "fetchone() returns a single tuple representing the next row (or None if no more rows); fetchall() returns a list of tuples representing all remaining rows",
     ["fetchone() returns an integer; fetchall() returns a string", "fetchone() returns a list; fetchall() returns a single dictionary", "Both return identical strings"],
     "fetchone() retrieves one row as a tuple (or None at end); fetchall() returns all remaining rows as a list of tuples (or empty list [])."),
    ("stmt", "cursor.rowcount and fetchmany(n)",
     "cursor.fetchmany(size=5) retrieves the next 5 rows from the query result set as a list of tuples.",
     "cursor.rowcount returns the number of rows affected by a DML statement or retrieved so far by the cursor.", 1,
     "Both Statement I and Statement II are correct. fetchmany(n) fetches up to n records; rowcount logs affected or fetched row numbers."),
    ("ar", "Handling Empty Result Sets in fetchone()",
     "When fetchone() is called after all records from a query have been exhausted, it returns the Python object None without raising an IndexError.",
     "None is returned as a sentinel value to allow simple while loop iteration: while row is not None: ... row = cur.fetchone().", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Returning None allows clean while loop traversal until the result stream terminates."),
    ("match", "Cursor Fetch Methods and Empty Output Behavior",
     "Match the cursor fetch method in List I with its return value when executed on an empty result set in List II:",
     [("A", "cursor.fetchone()"),
      ("B", "cursor.fetchall()"),
      ("C", "cursor.fetchmany(3)"),
      ("D", "cursor.rowcount on INSERT")],
     [("I", "None"),
      ("II", "Empty list: []"),
      ("III", "Empty list: []"),
      ("IV", "Positive integer representing the count of rows successfully inserted")],
     "A-I, B-II, C-III, D-IV",
     "fetchone on empty returns None; fetchall returns []; fetchmany returns []; rowcount on INSERT returns affected row count."),
    ("seq", "Record Extraction and Display Sequence via Python Cursor",
     "Arrange the correct sequence of steps for querying and displaying employee records using fetchall():",
     [("A", "Execute the query using cur.execute('SELECT EmpId, Name, Salary FROM Employee WHERE DeptId = 10;')"),
      ("B", "Extract all matching records into memory using records = cur.fetchall()"),
      ("C", "Iterate through the returned list of tuples using a for loop: 'for row in records:'"),
      ("D", "Access individual attributes using tuple indexing (e.g., row[0], row[1]) or tuple unpacking and display")],
     "A, B, C, D",
     "Query processing workflow: execute query -> fetchall into list -> loop over rows -> unpack and display tuple values.")
]

s17_extras = [
    ("Unpacking Tuples in Cursor Iteration", "Given a cursor yielding (roll, name, marks), what is the cleanest Python syntax to iterate through all rows?",
     "for roll, name, marks in cur.fetchall(): print(roll, name, marks)",
     ["for i in range(len(cur)): print(cur[i])", "while cur.read(): print(row)", "for x in cur.execute(): print(x)"],
     "Python supports tuple unpacking directly in loop headers, binding individual columns to descriptive variables."),
    ("Iterating Directly Over Cursor", "Can a Python programmer iterate directly over a cursor object using: for row in cur:?",
     "Yes, the cursor object is an iterable that yields rows one-by-one using internal fetchone() streaming",
     ["No, direct iteration raises a TypeError", "Only if the database contains fewer than 10 rows", "Only in text files"],
     "Cursor objects implement the Python iterator protocol, enabling clean line-by-line streaming via 'for row in cur:'."),
    ("Memory Hazard of fetchall() on Massive Tables", "Why is calling cur.fetchall() on a table containing 50 million records dangerous?",
     "It attempts to load all 50 million row tuples into computer RAM simultaneously, risking out-of-memory crashes",
     ["It deletes the records from the server", "It locks the database permanently", "It turns all numbers into zero"],
     "fetchall() materializes the entire result-set in memory; massive datasets should be processed using fetchone() or fetchmany() streaming."),
    ("Result of fetchall() When No Rows Match", "If SELECT * FROM Student WHERE Marks > 100; matches zero rows, what does cur.fetchall() return?",
     "An empty list []",
     ["None", "False", "Raises a RecordNotFoundError"],
     "fetchall() returns an empty list [] when a query produces zero matching records."),
    ("Result of fetchone() When No Rows Match", "If a query matches zero rows, what does cur.fetchone() return immediately?",
     "None",
     ["An empty tuple ()", "An empty list []", "Raises an IndexError"],
     "When no rows match the query criteria, fetchone() returns None immediately."),
    ("Extracting Column Headers from Cursor", "How can the column names of a queried table be extracted dynamically from an executed cursor cur?",
     "[desc[0] for desc in cur.description]",
     ["cur.columns", "cur.get_fieldnames()", "cur.header"],
     "cur.description contains metadata tuples for each column, where the first element desc[0] is the column name."),
    ("cursor.rowcount Value Before Fetch", "In MySQL Connector, what does cur.rowcount return immediately after cur.execute('SELECT ...') on an unbuffered cursor?",
     "-1 (rowcount is not known until rows are actively fetched from the unbuffered socket)",
     ["The total rows in the table", "0", "None"],
     "On unbuffered cursors, rowcount returns -1 until all rows have been streamed and read into the client."),
    ("fetchmany() When Remaining Rows < n", "If 2 rows remain in the result buffer and cur.fetchmany(10) is executed, how many rows are returned?",
     "Exactly 2 rows as a list of 2 tuples (it returns whatever rows remain without error)",
     ["It raises an EOFError", "It pads with 8 None objects", "It returns an empty list"],
     "fetchmany(n) fetches up to n rows; if fewer than n rows remain, it returns all remaining available rows."),
    ("Re-executing Query on Same Cursor", "What happens if cur.execute('SELECT ...') is called on a cursor that still has unread results from a previous query?",
     "It raises an 'InternalError: Unread result found' unless buffered=True was used",
     ["The previous results are automatically printed to the screen", "The database deletes both tables", "The server restarts"],
     "Unread results on an unbuffered socket block subsequent queries on the same connection, raising 'Unread result found'."),
    ("Accessing First Column of Single Row", "What is the cleanest code to fetch the scalar count from cur.execute('SELECT COUNT(*) FROM Emp;')?",
     "cur.fetchone()[0]",
     ["cur.fetchall()", "cur.fetchone()", "cur.count"],
     "fetchone() returns a 1-element tuple (count,); indexing [0] extracts the scalar integer count directly."),
    ("Iterating With While Loop and fetchone", "Complete the while loop to process all records: row = cur.fetchone(); while ____: print(row); row = cur.fetchone()",
     "row is not None",
     ["row != []", "len(row) > 0", "row == True"],
     "Because fetchone() returns None at the end of the result stream, the sentinel check is 'while row is not None:'."),
    ("Parameterized SELECT Query Execution", "How should a query searching for a specific roll number roll_no be safely executed using execute()?",
     "cur.execute('SELECT * FROM Student WHERE Roll = %s;', (roll_no,))",
     ["cur.execute('SELECT * FROM Student WHERE Roll = ' + str(roll_no))", "cur.execute(f'SELECT * FROM Student WHERE Roll = {roll_no}')", "cur.execute('SELECT * FROM Student WHERE Roll = roll_no')"],
     "Parameters must be passed as a second tuple argument: cur.execute(sql, (param,)), allowing the driver to escape parameters safely."),
    ("Rowcount After UPDATE Statement", "If cur.execute('UPDATE Student SET Marks = Marks + 5 WHERE Marks < 40;') updates 8 students, what does cur.rowcount return?",
     "8",
     ["0", "-1", "40"],
     "For DML statements (INSERT, UPDATE, DELETE), cur.rowcount returns the exact number of rows affected by the statement."),
    ("Data Types Conversion in Python Cursor", "When a MySQL DATE column is retrieved via cursor.fetchone(), how does the connector present it in Python?",
     "As a Python datetime.date object",
     ["As a raw integer timestamp", "As an encrypted byte string", "As a floating-point number"],
     "The MySQL connector automatically converts SQL DATE, TIME, and DATETIME types into Python native datetime objects."),
    ("Resetting Cursor Result Pointer", "Can an unbuffered cursor seek backward to re-read rows that were already fetched?",
     "No, standard result cursors are forward-only streams; re-reading requires re-executing the query or buffering records in memory",
     ["Yes, using cur.seek(0)", "Yes, using cur.rewind()", "Yes, by calling cur.back()"],
     "Standard database socket cursors are forward-only; to revisit records, developers store them in Python lists or re-query.")
]

# Slot 18: Python-SQL Connectivity: Parameterized Queries & Commit
s18_raw = [
    ("mcq", "Preventing SQL Injection via Parameterization",
     "Why is executing queries using parameterized placeholders (e.g., cur.execute(query, (val,))) strictly required over string concatenation?",
     "Parameterized queries separate SQL logic from untrusted user data, preventing malicious SQL Injection attacks",
     ["String concatenation is not supported in Python", "Parameterized queries make the computer screen brighter", "Parameterized queries convert text into binary images"],
     "Parameterization sends code and data separately, ensuring user input cannot break out of data literals to alter SQL syntax (SQL Injection defense)."),
    ("stmt", "connection.commit() for DML Transactions",
     "In Python database programming, changes made by DML statements (INSERT, UPDATE, DELETE) are not permanently saved to disk until connection.commit() is invoked.",
     "The rollback() method of a connection object undoes all uncommitted transactions executed during the current transaction block.", 1,
     "Both Statement I and Statement II are correct. Transaction ACID durability requires commit() to finalize changes; rollback() aborts pending uncommitted mutations."),
    ("ar", "Difference Between Cursor and Connection Commit",
     "Invoking cur.commit() will result in an AttributeError in Python.",
     "The commit() and rollback() methods belong to the database Connection object, not to individual Cursor objects.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Transactions span entire database connections, so commit() is a method of the connection."),
    ("match", "Transaction Management Methods and Placeholders",
     "Match the database transaction entity in List I with its operational function in List II:",
     [("A", "conn.commit()"),
      ("B", "conn.rollback()"),
      ("C", "%s placeholder"),
      ("D", "cursor.executemany()")],
     [("I", "Permanently commits all pending transactional modifications to the database"),
      ("II", "Reverts all uncommitted changes back to the previous stable savepoint state"),
      ("III", "Standard format placeholder for passing parameterized variables in MySQL Connector"),
      ("IV", "Executes an SQL template against a list of multiple parameter tuples efficiently in batch")],
     "A-I, B-II, C-III, D-IV",
     "commit finalizes; rollback undoes; %s is parameter placeholder; executemany runs batch insertions."),
    ("seq", "Secure Multi-Record Insertion Sequence with Commit",
     "Arrange the sequential operational steps for executing batch record insertions with error handling and transaction commit:",
     [("A", "Define the SQL template with placeholders: 'INSERT INTO Emp VALUES (%s, %s, %s);'"),
      ("B", "Prepare a list of data tuples containing the records to be inserted"),
      ("C", "Execute batch insertion using cur.executemany(sql, records) within a try block"),
      ("D", "Call conn.commit() to finalize the transaction, or conn.rollback() inside the except block on error")],
     "A, B, C, D",
     "Batch transaction sequence: define SQL template -> prepare data tuples -> executemany -> commit on success or rollback on exception.")
]

s18_extras = [
    ("SQL Injection Attack Mechanism", "What is an 'SQL Injection' attack?",
     "A cyber attack where an adversary injects malicious SQL fragments into input fields to manipulate database queries and gain unauthorized data access",
     ["Physically injecting liquid into a hard drive", "Flooding a server with email spam", "Stealing computer monitors from an office"],
     "SQL injection exploits unsanitized input concatenated into query strings, allowing attackers to bypass authentication or extract sensitive data."),
    ("Placeholder Syntax in MySQL Connector", "What placeholder symbol is standardly used by mysql.connector for parameterized queries across all data types?",
     "%s (even for integers, floats, and dates)",
     ["?", ":val", "$1"],
     "MySQL Connector standardly uses the '%s' format specifier as its parameter marker, regardless of whether the column is string or integer."),
    ("Tuple Requirement in Single Parameter", "When passing a single variable to cur.execute(sql, (val,)), why is the trailing comma mandatory?",
     "In Python, a single element enclosed in parentheses without a comma is evaluated as a scalar, not as a tuple",
     ["The trailing comma tells MySQL to shut down", "The comma is an encryption key", "The comma speeds up the internet connection"],
     "Parentheses alone do not create a 1-tuple in Python; (val,) with a trailing comma is required to create a singleton tuple."),
    ("executemany() Performance Advantage", "Why is cur.executemany(sql, list_of_tuples) superior to running cur.execute() in a Python for loop?",
     "executemany() batches multiple inserts into optimized compound network payloads, dramatically reducing round-trip database latency",
     ["executemany() uses zero electricity", "executemany() converts SQL into Python functions", "executemany() runs without a database server"],
     "Batching via executemany() reduces client-server network roundtrips from n roundtrips down to a single optimized batch packet."),
    ("Dangers of Forgetting commit()", "What happens to newly inserted rows if a Python script executes cur.execute('INSERT ...') but exits without calling conn.commit()?",
     "The changes are discarded (rolled back), and the newly inserted records will not appear in the database table",
     ["The table is corrupted and deleted", "The computer hard drive crashes", "The rows are inserted twice"],
     "Without commit(), transactional DDL/DML sessions discard uncommitted mutations upon session disconnect (implicit rollback)."),
    ("ACID Properties: Durability", "Which ACID property guarantees that once a transaction is finalized with connection.commit(), changes survive power failures?",
     "Durability",
     ["Atomicity", "Consistency", "Isolation"],
     "Durability guarantees that committed transactions are written to non-volatile storage and persist across system crashes."),
    ("ACID Properties: Atomicity", "Which ACID property ensures that an entire batch of multiple SQL operations either completely succeeds or completely fails as an indivisible unit?",
     "Atomicity ('All or Nothing')",
     ["Consistency", "Isolation", "Durability"],
     "Atomicity ensures that all statements within a transaction boundary complete successfully, or all are rolled back if any step fails."),
    ("Try-Except-Rollback Pattern", "In professional banking software, why is conn.rollback() placed inside the 'except Exception:' block?",
     "To ensure that if an error occurs halfway through a multi-step transfer, the database reverts to its original balanced state without partial updates",
     ["To delete the customer\'s bank account", "To transfer all money to the bank manager", "To print error logs to paper"],
     "Rolling back on exception prevents half-completed transactional states (e.g., money debited from account A but not credited to account B)."),
    ("Preventing SQL Injection Example", "Which code example demonstrates SECURE parameterized coding that is impervious to SQL injection?",
     "cur.execute('SELECT * FROM Users WHERE user=%s AND pass=%s;', (uname, pword))",
     ["cur.execute('SELECT * FROM Users WHERE user=\"' + uname + '\" AND pass=\"' + pword + '\"')", "cur.execute(f'SELECT * FROM Users WHERE user=\"{uname}\"')", "cur.execute('SELECT * FROM Users WHERE user=' + uname)"],
     "Passing inputs as parameter tuples to execute() prevents SQL injection by treating input strictly as literal values."),
    ("Commit Not Required for SELECT", "Why is calling connection.commit() NOT necessary after executing a SELECT query?",
     "SELECT is a read-only Data Query Language (DQL) operation that does not modify persistent database state",
     ["SELECT queries cannot connect to databases", "SELECT automatically commits before running", "SELECT runs only on temporary RAM tables"],
     "Read-only queries do not mutate data or alter storage pages, rendering commit() redundant."),
    ("Autocommit Disabled Default", "In standard Python DB-API 2.0 compliant drivers, is autocommit enabled or disabled by default?",
     "Disabled by default (transactions must be explicitly committed)",
     ["Enabled by default", "It changes randomly on every run", "Enabled only on weekends"],
     "DB-API 2.0 specifies that autocommit is disabled by default, requiring explicit commit() calls to preserve transactional boundaries."),
    ("Handling IntegrityError in Inserts", "What specific exception is raised if an INSERT statement violates a PRIMARY KEY constraint by attempting a duplicate key?",
     "mysql.connector.errors.IntegrityError",
     ["mysql.connector.errors.DataError", "mysql.connector.errors.ProgrammingError", "mysql.connector.errors.InterfaceError"],
     "Constraint violations (duplicate primary keys, foreign key violations, not-null breaches) raise IntegrityError."),
    ("Checking Last Insert ID", "How can an auto-incremented ID generated by an INSERT statement be retrieved from a cursor in Python?",
     "cursor.lastrowid",
     ["cursor.id", "cursor.get_insert_id()", "cursor.auto_id"],
     "cursor.lastrowid returns the integer generated for an AUTO_INCREMENT column by the most recent INSERT statement."),
    ("Closing Connection Aborts Uncommitted Data", "If conn.close() is called while a transaction has uncommitted INSERTs, what default action does MySQL take?",
     "It automatically executes a rollback, discarding all uncommitted changes",
     ["It automatically commits the changes to disk", "It freezes the database server", "It sends an email alert to the admin"],
     "Closing an active connection socket with pending uncommitted transactions triggers an automatic rollback by the RDBMS engine."),
    ("Savepoint Concept in Transactions", "What is a 'SAVEPOINT' in relational database transactions?",
     "A designated marker within a transaction allowing partial rollback to that specific point without discarding earlier successful operations",
     ["A USB flash drive plugged into the server", "A screenshot of the database table", "The password used to log in"],
     "SAVEPOINT creates an intermediate bookmark inside a transaction, permitting granular rollbacks (ROLLBACK TO savepoint_name).")
]

# Slot 19: Relational Algebra & SQL Table JOINs
s19_raw = [
    ("mcq", "Cartesian Product vs Equi-Join Distinction",
     "What is the fundamental difference between a 'Cartesian Product' (CROSS JOIN) and an 'Equi-Join' between two tables?",
     "A Cartesian Product pairs every row of the first table with every row of the second table unconditionally; an Equi-Join matches rows based on an equality condition between common columns",
     ["A Cartesian Product deletes all rows, while Equi-Join adds new rows", "A Cartesian Product works only on numbers, while Equi-Join works only on text", "There is zero difference between them"],
     "Cartesian product combines every tuple of R with every tuple of S (Card = c1*c2); Equi-join filters Cartesian product tuples using equality on matching keys."),
    ("stmt", "Natural Join vs Equi-Join Column Duplication",
     "An Equi-Join retains all columns from both tables in the output result-set, including duplicate join columns.",
     "A Natural Join (NATURAL JOIN) automatically eliminates duplicate join columns, retaining only a single copy of the common attributes.", 1,
     "Both Statement I and Statement II are correct. Equi-join keeps duplicate columns unless projected; Natural join joins on common column names and eliminates duplicate columns."),
    ("ar", "Cartesian Product Degree Calculation",
     "If Table Student has 5 columns and Table Marks has 4 columns, the Cartesian Product of Student and Marks will possess exactly 9 columns.",
     "The Degree of a Cartesian Product of two relations is the sum of the degrees of the individual relations (Degree = d1 + d2).", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Cartesian product degree is additive: Degree(A x B) = Degree(A) + Degree(B) = 5 + 4 = 9."),
    ("match", "Relational Join Types and Output Behaviors",
     "Match the SQL JOIN type in List I with its operational output rule in List II:",
     [("A", "INNER JOIN"),
      ("B", "LEFT OUTER JOIN"),
      ("C", "RIGHT OUTER JOIN"),
      ("D", "CROSS JOIN")],
     [("I", "Returns only matching tuples where the join condition evaluates to True in both tables"),
      ("II", "Returns all tuples from the left table, with matched values from the right table or NULL if unmatched"),
      ("III", "Returns all tuples from the right table, with matched values from the left table or NULL if unmatched"),
      ("IV", "Returns the unrestricted Cartesian product pairing every tuple of both tables")],
     "A-I, B-II, C-III, D-IV",
     "INNER JOIN returns matched only; LEFT JOIN preserves all left rows; RIGHT JOIN preserves all right rows; CROSS JOIN returns full product."),
    ("seq", "Two-Table Equi-Join Query Formulation Sequence",
     "Arrange the correct sequence of clauses for formulating a two-table Equi-Join query with table aliases in SQL:",
     [("A", "SELECT clause: Specify desired attributes prefixed by table aliases (e.g., SELECT E.Name, D.DeptName)"),
      ("B", "FROM clause: Declare primary table with alias (e.g., FROM Employee E)"),
      ("C", "JOIN clause: Specify secondary table and join predicate (e.g., JOIN Department D ON E.DeptId = D.DeptId)"),
      ("D", "WHERE & ORDER BY clauses: Apply additional filter criteria and sort the combined output records")],
     "A, B, C, D",
     "Join query formulation: SELECT projections -> FROM table 1 -> JOIN table 2 ON key equality -> optional WHERE/ORDER BY.")
]

s19_extras = [
    ("Cartesian Product Cardinality Calculation", "If Table R has 20 rows and Table S has 15 rows, what is the Cardinality of their Cartesian Product R × S?",
     "300 rows (20 × 15 = 300)",
     ["35 rows", "5 rows", "200 rows"],
     "The Cardinality of a Cartesian Product is the product of individual cardinalities: 20 × 15 = 300 rows."),
    ("Table Aliases in SQL Joins", "Why are short table aliases (e.g., FROM Employee E JOIN Dept D) widely used in multi-table queries?",
     "They provide concise prefixes to disambiguate identical column names (e.g., E.DeptId vs D.DeptId) and enhance readability",
     ["They make the query run 10 times faster", "Table aliases are required by hardware routers", "They encrypt the table names"],
     "Aliases resolve column ambiguity across joined relations and reduce typing in complex expressions."),
    ("Explicit vs Implicit Join Syntax", "How does the implicit join SELECT * FROM A, B WHERE A.id = B.id compare to SELECT * FROM A JOIN B ON A.id = B.id?",
     "Both produce identical result sets, but the explicit JOIN ON syntax is standard SQL-92 and separates join logic from row filtering",
     ["Implicit join deletes all data in Table B", "Explicit join can only join tables with 1 column", "Implicit join is not supported in MySQL"],
     "Implicit comma joins and explicit INNER JOIN ON produce identical execution plans; explicit JOIN ON is modern standard practice."),
    ("Natural Join Prerequisite", "What prerequisite must be met for NATURAL JOIN to correctly link two tables automatically?",
     "The tables must have at least one attribute with the identical column name and compatible data type",
     ["Both tables must have exactly the same number of rows", "Both tables must be stored on different hard drives", "Both tables must have zero NULL values"],
     "NATURAL JOIN automatically matches columns sharing identical attribute names across both relations."),
    ("Accidental Column Matching in Natural Join", "What danger arises when using NATURAL JOIN if both tables happen to share an unexpected common column name (e.g., 'Status')?",
     "Natural Join will match on BOTH columns (e.g., id AND Status), unexpectedly eliminating valid records that differ in Status",
     ["The computer shuts down immediately", "The database drops Table A", "Status is converted into a primary key"],
     "Natural Join joins across ALL columns sharing the same name; unexpected name overlaps severely restrict join results."),
    ("Self-Join Concept", "What is a 'Self-Join' in relational database management?",
     "Joining a table to itself by creating two distinct aliases of the same table (e.g., finding an employee's manager in the same Emp table)",
     ["Joining a table to an Excel spreadsheet", "A query that runs without any tables", "A join that deletes duplicate columns"],
     "A self-join pairs rows of a table with other rows in the same table, commonly used for hierarchical relationships like employee-manager."),
    ("Full Outer Join Emulation in MySQL", "Since MySQL does not natively support the FULL OUTER JOIN keyword, how is it standardly emulated?",
     "By taking the UNION of a LEFT JOIN query and a RIGHT JOIN query",
     ["By using a CROSS JOIN", "By restarting the MySQL server with a flag", "MySQL cannot perform outer joins of any kind"],
     "A FULL OUTER JOIN is emulated in MySQL by uniting a LEFT JOIN with a RIGHT JOIN: SELECT ... LEFT JOIN ... UNION SELECT ... RIGHT JOIN ...;."),
    ("Join Condition Omission Consequence", "What happens if a programmer writes SELECT * FROM Emp, Dept; forgetting the WHERE E.DeptId = D.DeptId join condition?",
     "It produces a Cartesian Product pairing every employee with every department",
     ["It produces a syntax error and halts", "It returns an empty result set", "It prints only the first employee"],
     "Omitting the join condition causes an unrestricted Cartesian product, generating all combinatorial row pairings."),
    ("Multi-Table Join with 3 Tables", "How many join conditions are required at minimum to join 3 tables together without producing a Cartesian product?",
     "At least 2 join conditions (N tables require N - 1 join conditions)",
     ["3 join conditions", "1 join condition", "5 join conditions"],
     "To connect N relations into a cohesive join graph without Cartesian product, at least N - 1 join conditions are required."),
    ("Non-Equi Join Definition", "What is a 'Non-Equi Join' in SQL?",
     "A join where the join condition utilizes comparison operators other than equality (such as <, >, <=, >=, or BETWEEN)",
     ["A join between tables stored in different databases", "A join that does not return any rows", "A join using foreign languages"],
     "Non-equi joins match tuples using inequality predicates (e.g., salary BETWEEN grade.low AND grade.high)."),
    ("Ambiguous Column Name Error", "What causes the SQL error 'Column DeptId in field list is ambiguous' in a joined query?",
     "Referencing DeptId in the SELECT list without qualifying which table it belongs to (e.g., E.DeptId vs D.DeptId) when both tables have that column",
     ["Typing DeptId in lowercase letters", "DeptId being an empty column", "DeptId containing too many numbers"],
     "When joined relations share a column name, unqualified references create ambiguity, requiring table prefixes (table.column)."),
    ("Left Outer Join Output on Unmatched Left Rows", "In a LEFT OUTER JOIN between Customer and Orders, what values appear in the Order columns for a Customer with zero orders?",
     "NULL values in all columns originating from the Orders table",
     ["Zeros in all columns", "The row is omitted completely", "The string 'NO ORDER'"],
     "LEFT JOIN preserves all left-side tuples; unmatched right-side attributes are populated with NULL."),
    ("Relational Algebra Join Symbol", "What mathematical symbol represents the Natural Join operation in relational algebra notation?",
     "The bowtie symbol (⨝)",
     ["The multiplication sign (×)", "The sigma sign (σ)", "The pi sign (π)"],
     "In relational algebra, the bowtie symbol (⨝) denotes the Natural Join operation between two relations."),
    ("Relational Algebra Cartesian Product Symbol", "What symbol represents the Cartesian Product in relational algebra?",
     "The multiplication cross symbol (×)",
     ["The divide sign (/)", "The plus sign (+)", "The minus sign (-)"],
     "Cartesian product is denoted in relational algebra by the cross multiplication operator (R × S)."),
    ("Cross Join with Empty Table", "What is the Cardinality of the Cartesian Product R × S if Table R has 100 rows and Table S has 0 rows?",
     "0 rows (100 × 0 = 0)",
     ["100 rows", "1 row", "None"],
     "Any number multiplied by zero is zero; pairing with an empty table yields an empty Cartesian product.")
]

# Slot 20: SQL Table Constraints & Integrity Rules
s20_raw = [
    ("mcq", "Primary Key vs Unique Constraint Distinction",
     "What is the fundamental functional difference between a PRIMARY KEY constraint and a UNIQUE constraint in an SQL table?",
     "A table can have only ONE Primary Key which cannot accept NULLs, whereas a table can have MULTIPLE Unique constraints which can accept NULL values",
     ["A Primary Key only works on text, while Unique works on numbers", "A Unique constraint deletes duplicate rows automatically", "There is zero difference between them"],
     "A relation permits exactly one Primary Key (strictly NOT NULL); a relation permits multiple UNIQUE constraints, which allow NULLs under SQL standards."),
    ("stmt", "Foreign Key and Referential Constraints",
     "A FOREIGN KEY constraint establishes a relational link between a column in a child table and a PRIMARY KEY or UNIQUE column in a parent table.",
     "Inserting a child row with a foreign key value that does not exist in the parent table will raise an IntegrityError constraint violation.", 1,
     "Both Statement I and Statement II are correct. Foreign keys link child to parent unique keys; inserting unreferenced child values violates referential integrity."),
    ("ar", "CHECK Constraint and Domain Integrity",
     "A CHECK constraint enforces Domain Integrity by ensuring all values in a column satisfy a specific boolean logical condition.",
     "If an INSERT or UPDATE statement attempts to store a value that evaluates the CHECK condition to FALSE (e.g., CHECK (Age >= 18)), the DBMS rejects the operation.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). CHECK constraints validate data values against business rules before permitting writes."),
    ("match", "SQL Table Constraints and Rules",
     "Match the table constraint in List I with its operational validation rule in List II:",
     [("A", "NOT NULL"),
      ("B", "DEFAULT"),
      ("C", "UNIQUE"),
      ("D", "CHECK")],
     [("I", "Guarantees that a column cannot be left empty or assigned a NULL value"),
      ("II", "Supplies a predefined fallback value when no explicit value is provided during insertion"),
      ("III", "Ensures all non-null values stored in the column are distinct and unique"),
      ("IV", "Validates that attribute values satisfy a specified boolean mathematical predicate")],
     "A-I, B-II, C-III, D-IV",
     "NOT NULL forbids empty values; DEFAULT assigns fallback; UNIQUE enforces distinctness; CHECK enforces boolean condition."),
    ("seq", "Table Creation with Full Constraints Sequence",
     "Arrange the correct sequence of clauses in a CREATE TABLE SQL statement defining an Employee table with primary and foreign keys:",
     [("A", "CREATE TABLE Employee (EmpId INT PRIMARY KEY, EmpName VARCHAR(50) NOT NULL,"),
      ("B", "Salary DECIMAL(10, 2) CHECK (Salary > 0), City VARCHAR(30) DEFAULT 'Delhi',"),
      ("C", "DeptId INT,"),
      ("D", "FOREIGN KEY (DeptId) REFERENCES Department(DeptId) ON DELETE SET NULL);")],
     "A, B, C, D",
     "Schema definition: primary key/not null -> check/default columns -> foreign key column -> foreign key references clause.")
]

s20_extras = [
    ("DEFAULT Constraint Behavior", "What happens when an INSERT statement omits a column that has a DEFAULT 'Active' constraint defined?",
     "The column is automatically populated with the value 'Active'",
     ["The insertion fails with an error", "The column is populated with NULL", "The entire table is locked"],
     "DEFAULT specifies the default literal value automatically assigned when an INSERT statement does not provide a value for that column."),
    ("Foreign Key Syntax", "What is the correct SQL syntax to declare a Foreign Key on DeptId in the Employee table referencing the Department table?",
     "FOREIGN KEY (DeptId) REFERENCES Department(DeptId)",
     ["FOREIGN KEY DeptId POINTS Department(DeptId)", "LINK DeptId TO Department(DeptId)", "DeptId FOREIGN KEY = Department.DeptId"],
     "The standard SQL syntax is: FOREIGN KEY (child_col) REFERENCES parent_table(parent_col)."),
    ("ON DELETE SET NULL Effect", "In a foreign key defined with 'ON DELETE SET NULL', what occurs when a referenced parent record is deleted?",
     "The foreign key attribute in all referencing child records is automatically updated to NULL",
     ["All referencing child records are deleted permanently", "The parent deletion is aborted", "The child records turn into primary keys"],
     "ON DELETE SET NULL sets the child foreign key column to NULL when the referenced parent tuple is deleted."),
    ("ON DELETE RESTRICT Default", "What is the effect of the default 'ON DELETE RESTRICT' (or NO ACTION) on a parent table row?",
     "It prevents the parent record from being deleted as long as referencing records exist in the child table",
     ["It deletes all child records instantly", "It converts the parent record to text", "It shuts down the database"],
     "RESTRICT rejects the deletion of a parent record if any child records currently reference that parent key."),
    ("Column-Level vs Table-Level Constraints", "How does a Column-Level constraint definition differ from a Table-Level constraint definition in CREATE TABLE?",
     "Column-level constraints are defined on the same line as the attribute; table-level constraints are defined separately at the end and can span multiple composite columns",
     ["Column-level constraints apply only to numbers", "Table-level constraints are deleted after 24 hours", "There is zero difference between them"],
     "Column-level constraints apply to single columns; table-level constraints appear as distinct declarations and can bind composite keys."),
    ("Multiple Columns in UNIQUE Constraint", "Can a UNIQUE constraint be applied across multiple columns together (e.g., UNIQUE(PassportNo, CountryCode))?",
     "Yes, as a composite table-level constraint ensuring the combination of values is unique across rows",
     ["No, UNIQUE can only apply to single columns", "Only if the columns contain numbers", "Only in proprietary Oracle databases"],
     "A composite UNIQUE constraint ensures the combined tuple values of all specified attributes remain unique."),
    ("CHECK Constraint Involving Multiple Columns", "Can a CHECK constraint evaluate relationships between two distinct columns (e.g., CHECK (EndDate >= StartDate))?",
     "Yes, table-level CHECK constraints can compare multiple columns within the same row",
     ["No, CHECK constraints can only check a single column against a constant", "Only if both columns are integers", "Only on Saturdays"],
     "Table-level CHECK constraints can reference multiple columns of the same row to validate relational integrity rules."),
    ("Adding Primary Key to Existing Table", "What SQL command adds a Primary Key constraint to an existing table 'Student' on column 'Roll'?",
     "ALTER TABLE Student ADD PRIMARY KEY (Roll);",
     ["UPDATE Student SET PRIMARY KEY = Roll;", "ALTER TABLE Student MODIFY Roll = PRIMARY KEY;", "ADD PRIMARY KEY (Roll) TO Student;"],
     "ALTER TABLE table_name ADD PRIMARY KEY (col_name); adds a primary key to an existing relation."),
    ("Dropping Primary Key Constraint", "Which command removes the primary key constraint from the 'Student' table in MySQL?",
     "ALTER TABLE Student DROP PRIMARY KEY;",
     ["DELETE PRIMARY KEY FROM Student;", "ALTER TABLE Student REMOVE PRIMARY KEY;", "DROP PRIMARY KEY FROM Student;"],
     "In MySQL, ALTER TABLE table_name DROP PRIMARY KEY; removes the primary key constraint."),
    ("Constraint Naming Convention", "Why do database architects explicitly name constraints using the CONSTRAINT keyword (e.g., CONSTRAINT chk_sal CHECK (Salary > 0))?",
     "Naming constraints allows them to be specifically identified, queried in system catalogs, and dropped cleanly via ALTER TABLE",
     ["Constraints cannot work unless given a human name", "Named constraints take up zero hard disk space", "Unnamed constraints delete themselves"],
     "Explicit constraint names facilitate maintenance, clear error diagnostic reporting, and targeted dropping via ALTER TABLE."),
    ("NOT NULL Constraint Modification", "Why must a NOT NULL constraint on an existing column be added via MODIFY rather than ADD CONSTRAINT in MySQL?",
     "NOT NULL is a column attribute specification, applied via ALTER TABLE table_name MODIFY col_name datatype NOT NULL;",
     ["NOT NULL is not supported in MySQL", "NOT NULL can only be set during computer startup", "MySQL does not allow modifying columns"],
     "In MySQL, adding NOT NULL requires modifying the column definition: ALTER TABLE tbl MODIFY col type NOT NULL;."),
    ("Foreign Key Data Type Matching Rule", "What strict requirement applies to the data types of a Foreign Key column and its referenced Primary Key column?",
     "They must have matching or strictly compatible data types and sizes (e.g., both INT, or both VARCHAR(20))",
     ["The child column must be integer and parent must be text", "Data types do not matter in foreign keys", "Parent must be float and child must be date"],
     "Foreign key references require matching types and dimensions so binary keys compare accurately across relations."),
    ("Integrity Violation on Child Row Insertion", "What error is triggered if an INSERT into Employee specifies DeptId = 99, but Department table has no DeptId 99?",
     "Cannot add or update a child row: a foreign key constraint fails (IntegrityError)",
     ["The department 99 is created automatically", "The salary is set to zero", "The row is saved in a secret temporary file"],
     "Referential integrity blocks the insertion of orphan child rows whose foreign keys lack matching parent keys."),
    ("Self-Referencing Foreign Key Example", "Which real-world scenario utilizes a Self-Referencing Foreign Key (where a table references its own primary key)?",
     "An Employee table where ManagerId is a foreign key referencing EmpId within the same Employee table",
     ["A table storing numbers from 1 to 10", "A table storing student grades", "A table storing book titles"],
     "Hierarchical self-references (e.g., an employee\'s manager being another employee in the same table) use self-referential foreign keys."),
    ("Database Metadata Catalog for Constraints", "In MySQL, which system database and table store metadata about all defined table constraints?",
     "INFORMATION_SCHEMA.TABLE_CONSTRAINTS",
     ["MYSQL.PASSWORDS", "SYS.HARDWARE", "CONFIG.RULES"],
     "The ANSI-standard INFORMATION_SCHEMA.TABLE_CONSTRAINTS view catalogs all active constraints across tables.")
]

SLOT11 = build_slot(CH_DS, list(s11_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s11_extras])
SLOT12 = build_slot(CH_DS, list(s12_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s12_extras])

SLOT13 = build_slot(CH_ALGO, list(s13_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s13_extras])
SLOT14 = build_slot(CH_ALGO, list(s14_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s14_extras])
SLOT15 = build_slot(CH_ALGO, list(s15_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s15_extras])

SLOT16 = build_slot(CH_PYSQL, list(s16_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s16_extras])
SLOT17 = build_slot(CH_PYSQL, list(s17_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s17_extras])
SLOT18 = build_slot(CH_PYSQL, list(s18_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s18_extras])
SLOT19 = build_slot(CH_PYSQL, list(s19_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s19_extras])
SLOT20 = build_slot(CH_PYSQL, list(s20_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s20_extras])

SLOTS_11_20 = {
    11: SLOT11,
    12: SLOT12,
    13: SLOT13,
    14: SLOT14,
    15: SLOT15,
    16: SLOT16,
    17: SLOT17,
    18: SLOT18,
    19: SLOT19,
    20: SLOT20
}

print("CS Slots 11 to 20 compiled successfully.")
'''

with open(out_path, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Generated {out_path} ({len(content)} bytes)")
