# Slots 11 to 15 Generator
s11_to_15 = '''
CH_POLLUTION = "Monitoring the Environment and Pollution"

# ==============================================================================
# Slot 11: Wildlife Conservation Programs & Species Recovery in India
# ==============================================================================
s11_raw = [
    ("mcq", "Project Elephant Launch and Mandate",
     "Launched in 1992 by the Ministry of Environment and Forests, 'Project Elephant' was established primarily to provide financial and technical support to:",
     "Protect wild Asian elephants, safeguard their natural migratory corridors, and address human-elephant conflict",
     ["Promote the commercial ivory export trade from domestic captive herds", "Confine all wild elephants strictly to urban zoological facilities", "Train wild elephants exclusively for military transport in mountain terrains"],
     "Project Elephant was launched in February 1992 to protect wild Asian elephants (Elephas maximus), secure elephant corridors, and mitigate human-elephant conflict."),
    ("stmt", "Project Tiger and NTCA Statutory Status",
     "Project Tiger was originally initiated as a centrally sponsored scheme in 1973 under Prime Minister Indira Gandhi.",
     "The National Tiger Conservation Authority (NTCA) was granted statutory status via the 2006 amendment to the Wildlife (Protection) Act, 1972.", 1,
     "Both Statement I and Statement II are correct. NTCA was established on statutory footing in 2006 to oversee tiger reserve management, tiger census, and anti-poaching forces."),
    ("ar", "Indian Rhino Vision 2020 Translocation Success",
     "Indian Rhino Vision 2020 (IRV 2020) successfully translocated Greater One-Horned Rhinoceroses from Kaziranga to Manas National Park.",
     "Distributing the rhino population across multiple protected reserves cushions the species against catastrophic disease epidemics or extreme flood mortality in Kaziranga.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). IRV 2020 aimed to establish a wild population of 3,000 rhinos spread across 7 protected areas in Assam to avoid single-site catastrophic risks."),
    ("match", "Wildlife Conservation Projects and Launch Years",
     "Match the flagship Indian wildlife recovery program in List I with its official launch year in List II:",
     [("A", "Project Tiger"),
      ("B", "Crocodile Conservation Project"),
      ("C", "Project Elephant"),
      ("D", "Project Snow Leopard")],
     [("I", "1973"),
      ("II", "1975"),
      ("III", "1992"),
      ("IV", "2009")],
     "A-I, B-II, C-III, D-IV",
     "Project Tiger was launched in 1973, the Crocodile Project in 1975 (with UNDP/FAO), Project Elephant in 1992, and Project Snow Leopard in 2009."),
    ("mcq", "Crocodile Species in Indian Project",
     "The Government of India's Crocodile Conservation Project (launched in 1975 with FAO/UNDP) focused on the captive rearing and release of which three native crocodilian species?",
     "Gharial (Gavialis gangeticus), Mugger (Crocodylus palustris), and Saltwater crocodile (Crocodylus porosus)",
     ["Nile crocodile, American alligator, and Caiman", "Komodo dragon, Monitor lizard, and Chameleon", "Spectacled caiman, Black caiman, and Dwarf crocodile"],
     "India's 1975 crocodile project saved all three native species: the freshwater Mugger, the estuarine Saltwater crocodile, and the fish-eating Gharial."),
    ("mcq", "Project Cheetah Reintroduction at Kuno",
     "In September 2022, wild African cheetahs (Acinonyx jubatus) were reintroduced into Kuno National Park in Madhya Pradesh, reversing the historical extinction of cheetahs in India declared in:",
     "1952",
     ["1972", "1986", "2000"],
     "The Asiatic cheetah was officially declared extinct in India in 1952. In 2022, African cheetahs were brought from Namibia and South Africa to Kuno National Park."),
    ("stmt", "Gharial Specialization and Habitat",
     "The Gharial (Gavialis gangeticus) is characterized by a long, narrow snout adapted specifically for piscivorous (fish-eating) diet.",
     "The National Chambal Sanctuary spanning Rajasthan, MP, and UP is the most critical remaining wild stronghold for the breeding population of Gharials.", 1,
     "Both Statement I and Statement II are correct. Chambal river is the cleanest major river system in North India providing deep pools and sandbanks for nesting Gharials."),
    ("seq", "Milestones in Indian Tiger Conservation Policy",
     "Arrange the historical milestones of tiger conservation in India in chronological order:",
     ["Passage of the Wildlife (Protection) Act creating legal schedules against hunting", "Official launch of Project Tiger across an initial network of 9 Tiger Reserves", "Creation of the National Tiger Conservation Authority (NTCA) as a statutory body", "Global 'Tx2' commitment at St. Petersburg Tiger Summit to double wild tiger numbers"],
     "I -> II -> III -> IV",
     "The sequence begins with the WPA in 1972, Project Tiger in 1973, NTCA creation in 2006, and the St. Petersburg Global Tiger Summit in 2010."),
    ("mcq", "Project Hangul Conservation Sanctuary",
     "Project Hangul (launched in 1970 with IUCN/WWF support) was dedicated to saving the critically endangered Kashmir Stag (Cervus elaphus hangul), found predominantly in which national park?",
     "Dachigam National Park (Jammu and Kashmir)",
     ["Hemis National Park (Ladakh)", "Great Himalayan National Park (Himachal Pradesh)", "Valley of Flowers National Park (Uttarakhand)"],
     "The Hangul or Kashmir Stag is endemic to the temperate riverine forests of Dachigam National Park near Srinagar."),
    ("ar", "Elephant Corridors and Habitat Fragmentation",
     "Securing recognized linear 'Elephant Corridors' is critical to reducing fatal human-elephant conflicts in India.",
     "Elephants are mega-herbivores requiring vast home ranges (up to 500-1,000 km2); severed migratory corridors force herds into human villages and crop fields.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Fragmenting traditional migration paths forces elephants into agricultural fields, causing crop depredation and retaliatory killings."),
    ("mcq", "MIKE Program in Elephant Conservation",
     "Under the CITES framework, what does the international monitoring program 'MIKE' associated with elephant reserves stand for?",
     "Monitoring the Illegal Killing of Elephants",
     ["Management of Indigenous Karnataka Elephants", "Mitigation of Infrastructure Killing Elephants", "Movement Index for Keystone Elephants"],
     "MIKE (Monitoring the Illegal Killing of Elephants) is a CITES program tracking trends in the illegal poaching of African and Asian elephants."),
    ("mcq", "Gahirmatha Marine Sanctuary Turtle Mass Nesting",
     "Gahirmatha Marine Sanctuary in Odisha is celebrated globally as the world's most important rookery for the mass nesting ('Arribada') of which endangered marine reptile?",
     "Olive Ridley Sea Turtle (Lepidochelys olivacea)",
     ["Green Sea Turtle (Chelonia mydas)", "Leatherback Sea Turtle (Dermochelys coriacea)", "Hawksbill Sea Turtle (Eretmochelys imbricata)"],
     "Gahirmatha beach and the mouth of the Rushikulya river in Odisha witness the mass synchronous nesting (Arribada) of hundreds of thousands of Olive Ridley turtles annually."),
    ("match", "Flagship Species and Key Conservation Reserves",
     "Match the endangered wildlife species in List I with its primary Indian sanctuary/national park in List II:",
     [("A", "One-Horned Rhinoceros"),
      ("B", "Asiatic Lion"),
      ("C", "Snow Leopard"),
      ("D", "Great Indian Bustard")],
     [("I", "Kaziranga National Park (Assam)"),
      ("II", "Gir National Park (Gujarat)"),
      ("III", "Hemis National Park (Ladakh)"),
      ("IV", "Desert National Park (Rajasthan)")],
     "A-I, B-II, C-III, D-IV",
     "Kaziranga harbors the One-Horned Rhino, Gir protects the Asiatic Lion, Hemis is renowned for Snow Leopards, and Desert National Park for the Great Indian Bustard."),
    ("mcq", "Project Snow Leopard High Altitude Strategy",
     "Project Snow Leopard, launched in 2009, covers the high-altitude landscapes of the Indian Himalayas across which elevation zone?",
     "High-altitude areas above 3,000 meters above mean sea level",
     ["Sub-tropical terai foothills below 500 meters", "Coastal mangrove mudflats at sea level", "Deccan plateau thorn scrub woodlands"],
     "Project Snow Leopard operates across the trans-Himalayan high-altitude ecosystem (>3,000m) in Ladakh, J&K, HP, Uttarakhand, Sikkim, and Arunachal Pradesh."),
    ("mcq", "Vulture Conservation Breeding Centers (VCBC)",
     "India's first specialized Vulture Conservation Breeding Centre (Jatayu Conservation Breeding Centre) was established in 2001 at Pinjore in which state?",
     "Haryana",
     ["Rajasthan", "Gujarat", "Madhya Pradesh"],
     "The Jatayu Conservation Breeding Centre was established in 2001 at Bir Shikargah Wildlife Sanctuary in Pinjore, Haryana, by BNHS and the Haryana Forest Department."),
    ("stmt", "Sea Turtle TED Mandate",
     "A Turtle Excluder Device (TED) is a specialized escape hatch built into commercial mechanized trawl nets.",
     "The installation of TEDs in coastal Odisha trawl nets allows caught sea turtles to escape unharmed while retaining fish and shrimp catches.", 1,
     "Both Statement I and Statement II are correct. TEDs prevent drowning of endangered Olive Ridley turtles accidentally caught in bottom trawl fishing gear."),
    ("mcq", "Project Dolphin Statutory Declaration",
     "The Gangetic River Dolphin (Platanista gangetica), an apex predator serving as an indicator of riverine health, was declared India's National Aquatic Animal in:",
     "2009",
     ["1972", "1986", "2019"],
     "Prime Minister Manmohan Singh declared the blind Gangetic Dolphin as India's National Aquatic Animal in October 2009 during the first National Ganga River Basin Authority meeting."),
    ("seq", "Execution Steps of Wildlife Species Reintroduction",
     "Arrange the standard IUCN conservation protocol steps for a wild species reintroduction (e.g. Cheetah project):",
     ["Comprehensive habitat suitability assessment, prey-base enumeration, and fence security audit", "Veterinary health screening, genetic profiling, and international quarantine holding of donor animals", "Air transport and release into soft-release pre-adaptation hunting bomas at the reintroduction site", "Hard release into the open wild landscape accompanied by satellite radio-collar tracking and anti-poaching monitoring"],
     "I -> II -> III -> IV",
     "Reintroductions proceed methodically from ecological site audits to quarantine holding, soft-release boma acclimatization, and finally free-ranging wild release with satellite telemetry."),
    ("mcq", "Vikramshila Gangetic Dolphin Sanctuary",
     "The only protected riverine sanctuary in India established exclusively for the conservation of the Gangetic Dolphin is Vikramshila Sanctuary, located in:",
     "Bhagalpur district, Bihar",
     ["Varanasi, Uttar Pradesh", "Haridwar, Uttarakhand", "Diamond Harbour, West Bengal"],
     "Vikramshila Gangetic Dolphin Sanctuary covers approximately 60 km of the Ganga river from Sultanganj to Kahalgaon in Bhagalpur district, Bihar."),
    ("mcq", "CA|TS Global Tiger Accreditation",
     "In tiger conservation, what does the internationally benchmarked site management accreditation standard 'CA|TS' stand for?",
     "Conservation Assured | Tiger Standards",
     ["Central Authority for Tiger Sanctuaries", "Corridor Assessment and Tracking Scheme", "Captive Animal Translocation Standard"],
     "CA|TS (Conservation Assured Tiger Standards) is a global accreditation tool setting minimum criteria for effective tiger reserve management.")
]

# ==============================================================================
# Slot 12: Indian Wildlife & Biodiversity Legislation (WPA 1972, BDA 2002)
# ==============================================================================
s12_raw = [
    ("mcq", "Wildlife Protection Act 1972 Enactment Context",
     "The Wildlife (Protection) Act, 1972 was enacted by the Indian Parliament under which constitutional power to establish a uniform national framework for wildlife conservation?",
     "Enacted under Article 252 after resolutions passed by state legislatures, prior to the 42nd Constitutional Amendment",
     ["Enacted exclusively as a municipal municipal council ordinance", "Enacted under the emergency powers of the Reserve Bank of India", "Enacted by presidential proclamation with zero parliamentary vote"],
     "The WPA 1972 was enacted under Article 252 at the request of 11 states, providing India's first unified national legal framework for protecting wild animals, birds, and plants."),
    ("stmt", "Original Schedules of WPA 1972",
     "Under the original 1972 Act, Schedule I and Part II of Schedule II provided absolute statutory protection with the highest penalties for hunting.",
     "Schedule V of the original Act listed 'Vermin' animals (such as common crows, fruit bats, mice, and rats) that could be hunted without a permit.", 1,
     "Both Statement I and Statement II are correct. Schedule I species (Tigers, Lions, Rhinos) carried maximum penalties, while Schedule V listed unprotected vermin."),
    ("ar", "Wildlife Protection Amendment Act 2022 Rationalization",
     "The Wildlife (Protection) Amendment Act, 2022 reduced the total number of schedules from six to four.",
     "The amendment rationalized schedules to streamline enforcement and incorporated a dedicated new Schedule IV to implement India's obligations under the CITES convention.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The 2022 amendment collapsed schedules to four: Schedule I (highest protection), Schedule II (lesser protection), Schedule III (protected plants), and Schedule IV (CITES listed specimens)."),
    ("match", "Biodiversity Act 2002 Three-Tier Governance",
     "Match the statutory institution created under the Biological Diversity Act, 2002 in List I with its jurisdiction level in List II:",
     [("A", "National Biodiversity Authority (NBA)"),
      ("B", "State Biodiversity Board (SBB)"),
      ("C", "Biodiversity Management Committee (BMC)"),
      ("D", "Headquarters of NBA")],
     [("I", "National statutory regulatory body established in 2003"),
      ("II", "State-level authority regulating commercial utilization by Indian citizens"),
      ("III", "Local level body established within every local self-government (Panchayat / Municipality)"),
      ("IV", "Chennai, Tamil Nadu")],
     "A-I, B-II, C-III, D-IV",
     "The BDA 2002 operates a 3-tier structure: NBA at the national level (HQ in Chennai), SBBs at the state level, and BMCs at the local Panchayat/Municipal level."),
    ("mcq", "People Biodiversity Register (PBR)",
     "Under the Biological Diversity Act 2002, what is the statutory role of a 'People's Biodiversity Register' (PBR) prepared by local Biodiversity Management Committees?",
     "To comprehensively document local biological resources, traditional ecological knowledge, medicinal uses, and breeding practices of local communities",
     ["To register private patents on wild forest herbs for multinational pharmaceutical corporations", "To record land deed transfers for highway infrastructure development", "To catalog imported exotic ornamental plants in botanical nurseries"],
     "A PBR is a legal decentralized register documenting local flora, fauna, traditional medicinal wisdom, and biodiversity resources in consultation with local villagers."),
    ("mcq", "Access and Benefit Sharing (ABS) Mechanism",
     "The 'Access and Benefit Sharing' (ABS) mandate codified under the Biological Diversity Act 2002 and the Nagoya Protocol ensures that:",
     "Commercial users of biological resources and traditional knowledge share fair and equitable financial/non-financial benefits with local indigenous knowledge-holders",
     ["All biological genetic resources of developing countries are transferred freely to foreign biotechnology firms without compensation", "Local communities are legally barred from entering their native forests for any purpose", "Government retains 100% of all revenues without giving any portion to local communities"],
     "ABS operationalizes the Nagoya Protocol: commercial companies utilizing traditional medicinal plants must share profits/royalties with the native custodian communities."),
    ("stmt", "CITES Appendices and International Wildlife Trade",
     "CITES (Convention on International Trade in Endangered Species of Wild Fauna and Flora) is an international agreement regulating cross-border trade in wildlife specimens.",
     "Appendix I of CITES includes species threatened with extinction for which international commercial trade is completely banned.", 1,
     "Both Statement I and Statement II are correct. CITES was drafted in 1973 in Washington DC; Appendix I gives absolute commercial trade bans (e.g., tiger skins, elephant ivory)."),
    ("seq", "Statutory Process for Commercial Use Approval under BDA 2002",
     "Arrange the legal steps an international corporate entity must follow to access Indian biological resources for commercial research:",
     ["Submission of formal Form I application to the National Biodiversity Authority (NBA) in Chennai", "Consultation by the NBA with the concerned State Biodiversity Board and local Biodiversity Management Committee", "Negotiation and execution of a legally binding Access and Benefit Sharing (ABS) agreement specifying royalty sharing", "Issuance of formal statutory approval allowing sample collection under agreed terms"],
     "I -> II -> III -> IV",
     "Foreign entities must apply to NBA, which consults local BMCs/SBBs, negotiates an ABS agreement, and grants access with clear benefit-sharing terms."),
    ("mcq", "Schedule I Plants under WPA 1972",
     "Which of the following rare, endemic medicinal insectivorous plants is protected under Schedule VI (now Schedule III) of the Wildlife Protection Act, forbidding its collection from the wild?",
     "Nepenthes khasiana (Pitcher plant of Meghalaya)",
     ["Eichhornia crassipes (Water hyacinth)", "Parthenium hysterophorus (Carrot grass)", "Lantana camara (Wild sage)"],
     "The endemic Khasi pitcher plant (Nepenthes khasiana), Beddome's cycad, Red vanda, and Blue vanda are strictly protected under the plant schedules of the WPA."),
    ("ar", "WPA Amendment 2022 and Vermin Declaration",
     "The 2022 Amendment completely deleted the standalone 'Schedule V (Vermin)' from the Wildlife (Protection) Act, 1972.",
     "Under the amended framework, the Central Government can now directly notify any species (other than Schedule I) as vermin for a specified area and period.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Deleting Schedule V allows flexible, localized notifications of vermin (e.g. wild boars damaging crops in specific districts)."),
    ("mcq", "National Board for Wildlife (NBWL) Chairmanship",
     "Under Section 5A of the Wildlife (Protection) Act 1972, who serves as the ex-officio Chairperson of the apex National Board for Wildlife (NBWL)?",
     "The Prime Minister of India",
     ["The Union Minister of Environment, Forest and Climate Change", "The Chief Justice of India", "The Director General of Forests"],
     "The National Board for Wildlife (NBWL) is chaired by the Prime Minister of India, with the Union Environment Minister serving as Vice-Chairperson."),
    ("mcq", "State Board for Wildlife (SBWL) Chairmanship",
     "At the state level, who serves as the statutory Chairperson of the State Board for Wildlife (SBWL)?",
     "The Chief Minister of the State",
     ["The Governor of the State", "The Principal Chief Conservator of Forests (PCCF)", "The Chief Secretary to the State Government"],
     "The State Board for Wildlife is chaired ex-officio by the Chief Minister of the respective state (or Administrator in Union Territories)."),
    ("match", "Wildlife Statutes and Key Provisions",
     "Match the statutory provision in List I with its legal section or entity in List II:",
     [("A", "Hunting prohibition of Schedule I animals"),
      ("B", "Declaration of National Parks"),
      ("C", "Central Zoo Authority (CZA)"),
      ("D", "National Tiger Conservation Authority (NTCA)")],
     [("I", "Section 9 of WPA 1972"),
      ("II", "Section 35 of WPA 1972"),
      ("III", "Chapter IVA added by 1991 amendment"),
      ("IV", "Chapter IVB added by 2006 amendment")],
     "A-I, B-II, C-III, D-IV",
     "Hunting is barred under Section 9, National Parks declared under Section 35, Central Zoo Authority created in 1991, and NTCA constituted under Chapter IVB in 2006."),
    ("mcq", "Central Zoo Authority (CZA) Role",
     "The Central Zoo Authority (CZA), established under the 1991 amendment to the Wildlife Protection Act, performs which regulatory function?",
     "Enforces minimum standards and animal welfare norms for housing, veterinary healthcare, and breeding across all recognized Indian zoos",
     ["Exports wild tigers to private commercial entertainment circuses abroad", "Licenses open commercial trophy hunting across designated national parks", "Operates commercial timber sawmills inside municipal zoological gardens"],
     "The CZA oversees all Indian zoos, regulates captive breeding exchanges, ensures enclosure enrichment, and de-recognizes sub-standard facilities."),
    ("mcq", "Wildlife Crime Control Bureau (WCCB)",
     "The statutory multi-disciplinary agency established under the Ministry of Environment to combat organized wildlife crime and illegal poaching syndicates in India is the:",
     "Wildlife Crime Control Bureau (WCCB)",
     ["Central Vigilance Commission (CVC)", "Serious Fraud Investigation Office (SFIO)", "Narcotics Control Bureau (NCB)"],
     "The Wildlife Crime Control Bureau (WCCB), established in 2007 under Section 38Y of WPA, gathers intelligence and coordinates inter-state wildlife enforcement."),
    ("stmt", "Biodiversity Heritage Sites (BHS)",
     "Under Section 37 of the Biological Diversity Act 2002, State Governments can notify areas of significant biodiversity outside protected areas as 'Biodiversity Heritage Sites' (BHS).",
     "Nallur Tamarind Grove in Bengaluru and Ameenpur Lake in Telangana are recognized Biodiversity Heritage Sites in India.", 1,
     "Both Statement I and Statement II are correct. BHS status safeguards unique cultural or wild biodiversity patches outside traditional national parks."),
    ("mcq", "Invasive Species Regulation in WPA 2022",
     "The Wildlife (Protection) Amendment Act, 2022 introduced a groundbreaking new provision empowering the Central Government to:",
     "Regulate or prohibit the import, trade, possession, and proliferation of invasive alien species that threaten native biodiversity",
     ["Permit private individuals to keep wild cheetahs as domestic house pets without permits", "Abolish all wildlife sanctuaries located near coastal shipping ports", "Ban all scientific field research on wild birds"],
     "The 2022 amendment explicitly inserted provisions empowering the Centre to regulate or prohibit invasive alien animal and plant species to protect native fauna."),
    ("seq", "Process of Notifying a National Park under WPA 1972",
     "Arrange the statutory procedural steps required to formally establish a National Park in India:",
     ["Issuance of preliminary notification declaring the state's intention to constitute an area as a National Park", "Appointment of a Settlement Officer to inquire into, determine, and settle all pre-existing private rights and land claims", "Complete extinguishment, acquisition, or relocation of all private land rights within the proposed sanctuary boundary", "Issuance of final notification under Section 35 formally establishing the inviolate National Park"],
     "I -> II -> III -> IV",
     "National park notification requires: preliminary intent, rights settlement by Collector/Settlement Officer, acquisition of rights, and final Section 35 notification."),
    ("mcq", "Section 8 Biodiversity Act Exemption",
     "The Biological Diversity Act 2002 explicitly exempts which of the following from the requirement of prior NBA/SBB permission?",
     "Local people and indigenous Vaids and Hakims practicing traditional healing systems, and normally traded commodities",
     ["Foreign pharmaceutical conglomerates conducting commercial gene-patenting research", "Multinational agricultural agrochemical seed monopolies", "Commercial foreign biotechnology joint ventures"],
     "Local communities, indigenous healers (Vaids, Hakims), and registered normally traded commodities (e.g., kitchen spices) are exempt from commercial ABS clearances."),
    ("mcq", "Nagoya Protocol on ABS Adoption",
     "The Nagoya Protocol on Access to Genetic Resources and the Fair and Equitable Sharing of Benefits Arising from their Utilization was adopted in 2010 under the aegis of which treaty?",
     "Convention on Biological Diversity (CBD)",
     ["UN Framework Convention on Climate Change (UNFCCC)", "Ramsar Convention on Wetlands", "Basel Convention on Hazardous Wastes"],
     "The Nagoya Protocol was adopted at COP-10 of the Convention on Biological Diversity (CBD) in Nagoya, Japan, to create a legally binding global ABS architecture.")
]

# ==============================================================================
# Slot 13: Air Pollution Fundamentals (Primary/Secondary, Smog, Acid Rain)
# ==============================================================================
s13_raw = [
    ("mcq", "Primary vs Secondary Air Pollutants",
     "A 'secondary air pollutant' is defined as a harmful substance that is not emitted directly from a source, but forms in the atmosphere when primary pollutants interact with sunlight or other atmospheric chemicals. Which of the following is a classic secondary pollutant?",
     "Peroxyacetyl Nitrate (PAN) and Tropospheric Ozone (O3)",
     ["Carbon Monoxide (CO)", "Sulfur Dioxide (SO2)", "Nitric Oxide (NO)"],
     "PAN and ozone are secondary pollutants formed by photochemical reactions involving primary emissions (NOx and VOCs) in the presence of sunlight."),
    ("stmt", "Classical Smog vs Photochemical Smog",
     "Classical smog (London smog) occurs in cool, humid climates and is a reducing mixture of sulfur dioxide, smoke, and particulate matter.",
     "Photochemical smog (Los Angeles smog) occurs in warm, sunny, dry climates and is an oxidizing mixture characterized by high concentrations of ozone, NOx, and PAN.", 1,
     "Both Statement I and Statement II are correct. London smog is reducing (SO2 + soot in cold fog); Los Angeles smog is oxidizing (NOx + hydrocarbons in hot sun)."),
    ("ar", "Acid Rain pH Threshold",
     "Precipitation is formally classified as 'Acid Rain' when its pH value drops below 5.6.",
     "Unpolluted natural rainwater is naturally slightly acidic (pH ~5.6) due to the dissolution of atmospheric carbon dioxide forming weak carbonic acid (H2CO3).", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Natural CO2 yields pH ~5.6; inputs of SO2 and NOx form strong H2SO4 and HNO3, driving pH down to 4.0 or lower."),
    ("match", "Air Pollutants and Primary Health/Environmental Impacts",
     "Match the air pollutant in List I with its specific environmental/health hazard in List II:",
     [("A", "Carbon Monoxide (CO)"),
      ("B", "Sulfur Dioxide (SO2)"),
      ("C", "Tropospheric Ozone (O3)"),
      ("D", "Lead (Pb) Particulates")],
     [("I", "Binds irreversibly to hemoglobin forming carboxyhemoglobin, causing severe tissue hypoxia"),
      ("II", "Induces chlorosis in plant foliage and reacts with moisture to form sulfuric acid rain"),
      ("III", "Causes intense respiratory irritation, premature crop senescence, and cracked tire rubber"),
      ("IV", "Accumulates in body tissues causing neurotoxic cognitive damage and low IQ in children")],
     "A-I, B-II, C-III, D-IV",
     "CO causes hypoxia, SO2 damages lungs/leaves and forms acid rain, O3 attacks tissues and rubber, and lead causes neurotoxic developmental impairment."),
    ("mcq", "Taj Mahal Stone Leprosy",
     "The yellowing and surface pitting of the white marble (CaCO3) of the Taj Mahal in Agra, known as 'Marble Cancer' or 'Stone Leprosy', is primarily caused by:",
     "Atmospheric sulfur dioxide emissions from the Mathura refinery reacting with moisture to form sulfuric acid, converting marble into gypsum",
     ["Uranium mining dust transported across the Thar desert by dust storms", "High concentrations of dissolved sodium chloride from the Yamuna river", "Direct thermal radiation from local brick kilns baking the stone"],
     "SO2 from Mathura refinery and local coal industries reacts with marble: CaCO3 + H2SO4 -> CaSO4.2H2O (gypsum), causing marble flaking and discolouration."),
    ("mcq", "Temperature Inversion and Winter Smog",
     "During Delhi winters, severe particulate smog is exacerbated by a meteorological condition known as 'Temperature Inversion', in which:",
     "A layer of warm air settles over a colder surface air layer, trapping pollutants close to the ground like an impermeable atmospheric lid",
     ["Surface winds accelerate to hurricane speeds, blowing all topsoil into the stratosphere", "Cold polar air masses trigger instantaneous condensation of all ozone into liquid droplets", "Solar ultraviolet radiation drops to absolute zero, halting all chemical bonding"],
     "Under thermal inversion, cool surface air is trapped beneath a warmer layer aloft; vertical atmospheric mixing halts, causing hazardous smoke and PM2.5 accumulation."),
    ("stmt", "PM2.5 vs PM10 Health Severity",
     "Particulate matter with an aerodynamic diameter of 2.5 micrometers or less (PM2.5) poses a far greater human health hazard than larger PM10 particles.",
     "Because of their minute size, PM2.5 particles bypass upper respiratory nasal cilia, penetrate deep into pulmonary alveoli, and enter the systemic blood circulation.", 1,
     "Both Statement I and Statement II are correct. PM2.5 penetrates deep alveolar tissue and enters capillaries, causing chronic heart disease, strokes, and lung cancer."),
    ("seq", "Chemical Steps in the Genesis of Photochemical Smog",
     "Arrange the sequential chemical reactions involved in the formation of daytime photochemical smog:",
     ["Vehicular engines burn gasoline at high temperatures, emitting Nitric Oxide (NO) and unburnt Volatile Organic Compounds (VOCs)", "Nitric oxide oxidizes in ambient air to form brown Nitrogen Dioxide (NO2)", "Solar ultraviolet radiation photolyzes NO2 into NO and highly reactive nascent atomic oxygen (O)", "Atomic oxygen combines with molecular oxygen (O2) to form secondary Tropospheric Ozone (O3), which further reacts with VOCs to generate PAN"],
     "I -> II -> III -> IV",
     "Photochemical smog begins with primary NOx/VOC emissions, oxidation to NO2, UV photolysis yielding atomic oxygen, and secondary ozone/PAN generation."),
    ("mcq", "Lichens as Bioindicators of Air Pollution",
     "Lichens (symbiotic associations of fungi and algae) are exceptionally sensitive bioindicators that completely disappear from urban areas polluted by:",
     "Sulfur dioxide (SO2)",
     ["Carbon dioxide (CO2)", "Argon gas (Ar)", "Methane gas (CH4)"],
     "Lichens absorb atmospheric water directly without cuticles; high SO2 destroys chlorophyll and kills lichens, creating 'lichen deserts' around polluted industrial zones."),
    ("ar", "Catalytic Converter Unleaded Petrol Prerequisite",
     "Motor vehicles fitted with catalytic converters must run exclusively on unleaded petrol.",
     "Tetraethyl lead in leaded petrol acts as a catalytic poison that coats the platinum-palladium-rhodium catalysts, permanently deactivating the converter.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Lead poisons noble metal catalysts in catalytic converters, rendering emissions control completely ineffective."),
    ("mcq", "Fly Ash Composition and Utilization",
     "Fly ash, a finely divided mineral byproduct captured from the flue gases of pulverized coal-fired thermal power stations, is mandated by the MoEFCC to be utilized in:",
     "Cement manufacturing, fly-ash brick production, road embankment stabilization, and mine backfilling",
     ["Cosmetic skin creams and pharmaceutical digestive antacids", "Direct human food fortification as a replacement for wheat flour", "Open ocean dumping to fertilize marine coral reefs"],
     "MoEFCC mandates 100% fly ash utilization in cement, brick-making, road construction, and concrete, preventing ash pond contamination and soil pollution."),
    ("mcq", "Major Constituents of Acid Rain",
     "Which two strong mineral acids contribute approximately 60–70% and 30–40% respectively to the total acidity of anthropogenic acid rain?",
     "Sulfuric acid (H2SO4) and Nitric acid (HNO3)",
     ["Hydrochloric acid (HCl) and Hydrofluoric acid (HF)", "Acetic acid (CH3COOH) and Citric acid", "Phosphoric acid (H3PO4) and Boric acid (H3BO3)"],
     "Acid rain is caused predominantly by emissions of SO2 (forming H2SO4, ~60–70%) and NOx (forming HNO3, ~30–40%)."),
    ("match", "Air Pollutants and Standard Units of Measurement",
     "Match the air pollution parameter in List I with its standard monitoring metric in List II:",
     [("A", "PM2.5 / PM10"),
      ("B", "Carbon Monoxide (CO)"),
      ("C", "Air Quality Index (AQI)"),
      ("D", "Noise Level")],
     [("I", "Micrograms per cubic meter (ug/m3)"),
      ("II", "Milligrams per cubic meter (mg/m3) or parts per million (ppm)"),
      ("III", "Unitless dimensionless composite index (0 to 500)"),
      ("IV", "A-weighted decibels dB(A)")],
     "A-I, B-II, C-III, D-IV",
     "PM is measured in ug/m3, CO in mg/m3, AQI is a unitless 0–500 score, and noise is measured in decibels dB(A)."),
    ("mcq", "Indoor Air Pollution in Rural India",
     "In rural households lacking clean cooking gas, the incomplete combustion of solid biomass fuels (wood, cattle dung, crop residues) in unvented chulhas releases massive levels of:",
     "Carbon monoxide, polycyclic aromatic hydrocarbons (PAHs), and fine respirable particulates (PM2.5)",
     ["Pure helium and molecular nitrogen gas", "Stratospheric chlorofluorocarbons", "Liquid mercury droplets"],
     "Biomass combustion in traditional stoves causes severe indoor air pollution, leading to acute respiratory infections, chronic obstructive pulmonary disease (COPD), and cataracts in rural women."),
    ("mcq", "Pradhan Mantri Ujjwala Yojana Environmental Goal",
     "The primary environmental and public health objective of the Government of India's 'Pradhan Mantri Ujjwala Yojana' (PMUY) is to:",
     "Provide subsidized Liquefied Petroleum Gas (LPG) connections to rural BPL women, eliminating hazardous indoor biomass smoke",
     ["Construct coal gasification plants in municipal primary schools", "Mandate that all rural transport run exclusively on diesel engines", "Distribute free kerosene wick lamps across all electrified villages"],
     "PMUY replaces biomass chulhas with clean burning LPG, drastically reducing indoor air pollution and lowering rural women's exposure to carcinogenic smoke."),
    ("stmt", "Stubble Burning (Parali) and Delhi Smog",
     "Paddy straw stubble burning in Punjab and Haryana during October-November coincides with post-monsoon meteorological wind transitions, blanketing the Indo-Gangetic Plains in toxic smog.",
     "The widespread adoption of mechanized Combine Harvesters leaves 10-15 cm standing stalks in fields, which farmers burn to rapidly clear seedbeds for winter wheat sowing.", 1,
     "Both Statement I and Statement II are correct. Combine harvesters leave standing stubble; short turnaround times between rice harvest and wheat sowing incentivize burning."),
    ("mcq", "Bio-Decomposer Capsule Technology",
     "The 'Pusa Bio-Decomposer' microbial consortium developed by ICAR-IARI decomposes standing paddy straw in agricultural fields by:",
     "Enzymatically digesting lignin and cellulose into nutrient-rich organic compost within 20-25 days without burning",
     ["Incinerating stubble via controlled microbial thermal exothermic combustion", "Transforming crop stalks into toxic synthetic plastics that repel insects", "Freezing the soil surface to sub-zero temperatures to halt weed germination"],
     "Pusa Bio-Decomposer uses fungal enzymes to rapidly digest cellulose and lignin in crop residues, converting stubble into soil-enriching humus in situ."),
    ("seq", "Sequence of Lake Acidification Ecological Collapse",
     "Arrange the sequential biological impacts that occur as a freshwater lake undergoes progressive acidification (pH dropping from 6.5 to below 4.5):",
     ["Lake buffering capacity is exhausted as limestone cations are depleted by sulfuric acid inputs", "Sensitive aquatic insects, freshwater snails, and zooplankton crustaceans die off", "Aluminum ions (Al3+) are leached from surrounding catchment soils into the water column, precipitating on fish gills", "Fish fail to reproduce, adults suffer mucus asphyxiation, and the lake becomes an oligotrophic 'dead lake' with crystalline clear, lifeless water"],
     "I -> II -> III -> IV",
     "Acidification progresses from buffer depletion to invertebrate dieback, toxic aluminum leaching, fish reproductive failure, and total aquatic dead-lake collapse."),
    ("mcq", "Ozone Layer Depletion vs Tropospheric Ozone",
     "Which statement correctly differentiates 'Stratospheric Ozone' from 'Tropospheric Ozone'?",
     "Stratospheric ozone is 'good ozone' that shields Earth from lethal solar UV-B rays, whereas Tropospheric ozone is 'bad ozone' acting as a toxic ground-level air pollutant and greenhouse gas",
     ["Stratospheric ozone causes respiratory asthma in city pedestrians, while tropospheric ozone protects against skin cancer", "Both forms of ozone are toxic pollutants that must be completely scrubbed from the atmosphere", "Both forms of ozone are synthetic man-made chemicals absent from nature"],
     "'Ozone in stratosphere = Good' (absorbs harmful UV); 'Ozone in troposphere = Bad' (respiratory irritant, oxidant damaging lungs and crops)."),
    ("mcq", "Bhopal Gas Tragedy Toxic Chemical",
     "On the night of December 2-3, 1984, the catastrophic Bhopal Gas Tragedy at the Union Carbide pesticide plant was caused by the accidental release of over 40 tons of which highly lethal gas?",
     "Methyl Isocyanate (MIC)",
     ["Sulfur Dioxide (SO2)", "Phosgene (COCl2)", "Carbon Monoxide (CO)"],
     "The Bhopal disaster, the world's worst industrial catastrophe, was caused by the runaway exothermic reaction and leak of highly toxic Methyl Isocyanate (MIC, CH3NCO).")
]

# ==============================================================================
# Slot 14: Air Quality Standards & Pollution Control Technologies
# ==============================================================================
s14_raw = [
    ("mcq", "Electrostatic Precipitator (ESP) Removal Efficiency",
     "In thermal power plants and cement factories, Electrostatic Precipitators (ESPs) are installed in flue gas stacks because they can remove what percentage of particulate matter?",
     "Over 99% of particulate matter from the exhaust stream",
     ["Less than 25% of particulate matter", "Exactly 50% of gaseous sulfur dioxide", "Only radioactive radon gas"],
     "NCERT highlights that an Electrostatic Precipitator can remove over 99% of particulate matter present in the exhaust from a thermal power plant."),
    ("stmt", "Working Principle of Electrostatic Precipitator",
     "An ESP features electrode wires maintained at several thousand volts that produce a corona that releases electrons.",
     "The released electrons attach to airborne dust particles, giving them a net negative charge, causing them to be attracted and held by grounded collecting plates.", 1,
     "Both Statement I and Statement II are correct. High-voltage corona wires charge dust particles negatively, which are then collected on positively grounded metal plates."),
    ("ar", "Flue Gas Velocity in Electrostatic Precipitator",
     "The velocity of flue gas passing between the collecting plates of an electrostatic precipitator must be maintained at a very low speed.",
     "Low gas velocity allows sufficient residence time for charged dust particles to migrate under electrostatic forces and settle onto collecting plates without being re-entrained.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). High gas velocity would blow dust particles off the plates back into the exhaust stream."),
    ("match", "Air Pollution Control Equipment and Mechanism",
     "Match the air pollution control device in List I with its primary removal mechanism in List II:",
     [("A", "Electrostatic Precipitator (ESP)"),
      ("B", "Wet Scrubber"),
      ("C", "Baghouse / Fabric Filter"),
      ("D", "Catalytic Converter")],
     [("I", "High-voltage corona charges particles, collecting them on oppositely charged grounded plates"),
      ("II", "Spray of lime slurry (Ca(OH)2) or water absorbs and neutralizes acidic gases like SO2"),
      ("III", "Woven fabric cloth bags physically filter out fine airborne dust and particulate matter"),
      ("IV", "Platinum-palladium-rhodium catalysts oxidize CO/hydrocarbons and reduce NOx into harmless gases")],
     "A-I, B-II, C-III, D-IV",
     "ESPs use electrostatic charge, scrubbers wash gases with liquid spray, fabric filters sieve particulates, and catalytic converters convert toxic vehicle gases."),
    ("mcq", "Scrubber Chemical Reagent for Sulfur Dioxide",
     "In a wet scrubber installed on a coal-fired power station, exhaust gas passes through a continuous spray of water mixed with which alkaline chemical to scrub sulfur dioxide?",
     "Limestone / Lime slurry (Calcium Carbonate / Calcium Hydroxide)",
     ["Concentrated Hydrochloric Acid", "Liquid Benzene", "Solid Sodium Cyanide"],
     "Wet scrubbers spray a slurry of lime (CaO/Ca(OH)2) or limestone (CaCO3) to react with SO2, converting it into calcium sulfite and gypsum (CaSO4.2H2O)."),
    ("mcq", "Catalytic Converter Chemical Reactions",
     "In an automobile's catalytic converter, the platinum-rhodium catalyst facilitates which of the following simultaneous chemical transformations?",
     "Oxidizes unburnt hydrocarbons into CO2 and H2O, oxidizes CO into CO2, and reduces Nitrogen Oxides (NOx) into harmless Nitrogen gas (N2)",
     ["Converts all oxygen into toxic ozone to disinfect the exhaust pipe", "Reduces all carbon dioxide into solid graphite flakes deposited inside the engine", "Transforms nitrogen gas into liquid ammonia fertilizer stored in the chassis"],
     "Catalytic converters use precious metals (Pt, Pd, Rh) to simultaneously oxidize hydrocarbons/CO and reduce NOx to harmless N2, CO2, and water vapor."),
    ("stmt", "Air Prevention and Control of Pollution Act 1981",
     "The Air (Prevention and Control of Pollution) Act was enacted by the Indian Parliament in 1981 to implement the decisions of the 1972 Stockholm Conference.",
     "By a landmark amendment in 1987, 'Noise' was officially included within the statutory definition of an air pollutant under the Air Act.", 1,
     "Both Statement I and Statement II are correct. The Air Act 1981 was amended in 1987 to bring noise pollution under the regulatory ambit of Pollution Control Boards."),
    ("seq", "Working Cycle of a Pulse-Jet Baghouse Filter",
     "Arrange the operational stages of a pulse-jet fabric baghouse filter in an industrial cement plant:",
     ["Dust-laden flue gas enters the baghouse hopper and flows upward around cylindrical fabric filter bags", "Particulate matter is physically intercepted on the exterior fabric surface, forming a filtering dust cake", "Clean filtered gas passes through the interior of the bags and exhausts through the stack", "Periodic high-pressure pulses of compressed air are blasted downward into the bags, dislodging the dust cake into the collection hopper"],
     "I -> II -> III -> IV",
     "Baghouse filtration proceeds from gas entry to surface dust cake interception, clean gas exhaust, and automated pulse-jet cleaning cycles."),
    ("mcq", "National Ambient Air Quality Standards (NAAQS) Pollutants",
     "The Central Pollution Control Board (CPCB) notifies National Ambient Air Quality Standards (NAAQS) for how many criteria air pollutants in India?",
     "12 pollutants (including PM10, PM2.5, SO2, NO2, CO, NH3, O3, Pb, Benzene, Benzo(a)pyrene, Arsenic, and Nickel)",
     ["Only 2 pollutants (Carbon Monoxide and Carbon Dioxide)", "Exactly 50 radioactive isotopes", "Only industrial mercury vapor"],
     "NAAQS covers 12 criteria pollutants: PM10, PM2.5, SO2, NO2, CO, NH3, O3, Pb, Benzene, Benzo(a)pyrene, Arsenic, and Nickel."),
    ("ar", "CNG Transition in Public Transport",
     "In 2002, the entire public bus fleet in Delhi was converted from diesel to Compressed Natural Gas (CNG) following Supreme Court directives.",
     "CNG burns almost completely and leaves very little unburnt residue, cannot be siphoned or easily adulterated, and emits far lower particulate matter than diesel.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). CNG (primarily methane) burns much cleaner than diesel, significantly reducing respirable black carbon emissions."),
    ("mcq", "National Air Quality Index (AQI) Categories",
     "India's National Air Quality Index (AQI), launched under the Swachh Bharat Abhiyan in 2014, classifies ambient air quality into how many color-coded categories?",
     "Six categories: Good (0-50), Satisfactory (51-100), Moderate (101-200), Poor (201-300), Very Poor (301-400), and Severe (401-500)",
     ["Three categories: Clean, Polluted, and Toxic", "Ten numerical deciles without color coding", "Two binary categories: Safe and Unsafe"],
     "India's AQI uses 6 categories: Good (Green), Satisfactory (Light Green), Moderate (Yellow), Poor (Orange), Very Poor (Red), and Severe (Dark Red)."),
    ("mcq", "Bharat Stage (BS) Emission Norms Leapfrog",
     "In April 2020, the Government of India made a historic leap in vehicular emission standards by skipping BS-V entirely and transitioning directly from:",
     "BS-IV to BS-VI (Euro 6 equivalent)",
     ["BS-I to BS-IV", "BS-II to BS-V", "BS-III to BS-IV"],
     "To combat vehicular air pollution, India leapfrogged directly from BS-IV to BS-VI norms on April 1, 2020, slashing fuel sulfur limits from 50 ppm to 10 ppm."),
    ("match", "AQI Numerical Ranges and Health Advisories",
     "Match the AQI score range in List I with its official category in List II:",
     [("A", "0 to 50"),
      ("B", "101 to 200"),
      ("C", "201 to 300"),
      ("D", "401 to 500")],
     [("I", "Good (Minimal health impact)"),
      ("II", "Moderate (Breathing discomfort to people with asthma and heart diseases)"),
      ("III", "Poor (Breathing discomfort to most people on prolonged exposure)"),
      ("IV", "Severe (Affects healthy people and seriously impacts those with existing diseases)")],
     "A-I, B-II, C-III, D-IV",
     "0-50 is Good, 101-200 is Moderate, 201-300 is Poor, and 401-500 is Severe."),
    ("mcq", "Graded Response Action Plan (GRAP)",
     "In the National Capital Region (NCR) of Delhi, the 'Graded Response Action Plan' (GRAP) overseen by the Commission for Air Quality Management (CAQM) is:",
     "An emergency institutional framework that triggers increasingly stringent anti-pollution curbs (construction bans, truck restrictions, school closures) as AQI worsens",
     ["A long-term project to pave all forest soils with asphalt", "A plan to export Delhi's industrial manufacturing entirely to coastal islands", "A tax rebate scheme for diesel luxury SUVs"],
     "GRAP triggers emergency stage-wise restrictions (Stage I to IV) based on AQI levels to prevent atmospheric particulate collapse during winter."),
    ("mcq", "Cyclone Separator Mechanism",
     "How does a mechanical 'Cyclone Collector' separate coarse industrial dust particles from incoming exhaust gas streams without filters?",
     "By imparting high-speed centrifugal swirling forces that fling heavier dust particles outward against the cyclone walls to slide down into a hopper",
     ["By using radioactive gamma beams to disintegrate matter into energy", "By freezing exhaust gases into liquid nitrogen ice blocks", "By spraying liquid mercury mist through the ductwork"],
     "Cyclone separators use centrifugal vortex forces to separate coarse particulate matter (>10 micrometers) from gas streams purely by inertial mass."),
    ("stmt", "National Clean Air Programme (NCAP) Targets",
     "The Ministry of Environment launched the National Clean Air Programme (NCAP) in 2019 to reduce particulate matter (PM10 and PM2.5) concentrations across non-attainment cities.",
     "The revised target under NCAP aims for up to a 40% reduction in PM concentrations or achieving national standards by 2026.", 1,
     "Both Statement I and Statement II are correct. NCAP targets over 130 non-attainment cities, mandating city-specific clean air action plans."),
    ("mcq", "Diesel Particulate Filter (DPF) in BS-VI Vehicles",
     "Under BS-VI vehicular standards, modern diesel vehicles are equipped with a Diesel Particulate Filter (DPF) and Selective Catalytic Reduction (SCR) that utilizes which additive to reduce NOx?",
     "Aqueous urea solution (Diesel Exhaust Fluid / AdBlue)",
     ["Ethanol distilled from sugarcane molasses", "Concentrated sulfuric acid", "Liquid petroleum gas"],
     "BS-VI diesel vehicles use AdBlue (aqueous urea solution) in SCR systems to break down toxic NOx into harmless nitrogen and water vapor."),
    ("seq", "Sequence of Emissions Reductions in BS-VI Transition",
     "Arrange the vehicular fuel and engineering upgrades that enabled India's transition to BS-VI standards:",
     ["Desulfurization of refinery fuels reducing sulfur content from 50 ppm to ultra-low 10 ppm", "Integration of on-board diagnostics (OBD-II) to monitor real-time tailpipe emissions", "Fitting of wall-flow Diesel Particulate Filters (DPF) capturing fine black carbon soot", "Installation of Selective Catalytic Reduction (SCR) injecting urea to eliminate nitrogen oxides"],
     "I -> II -> III -> IV",
     "BS-VI compliance requires ultra-low sulfur fuel (10 ppm), OBD-II diagnostics, particulate filters, and urea SCR systems."),
    ("mcq", "Vapour Recovery Systems at Fuel Stations",
     "Why does the Central Pollution Control Board mandate the installation of Stage I and Stage II 'Vapour Recovery Systems' (VRS) at retail petrol pumps in major cities?",
     "To capture and condense toxic Volatile Organic Compound (VOC) vapors (like carcinogenic Benzene) displaced during tanker unloading and vehicle fueling",
     ["To prevent water from entering the underground petrol storage tanks", "To prevent diesel fuel from freezing into solid wax during winters", "To cool the car radiator while pumping gasoline"],
     "VRS systems capture volatile hydrocarbon vapors (especially benzene) displaced during fuel transfers, preventing smog formation and protecting attendant health."),
    ("mcq", "Continuous Ambient Air Quality Monitoring Stations (CAAQMS)",
     "What is the operational advantage of automated Continuous Ambient Air Quality Monitoring Stations (CAAQMS) deployed by the CPCB over manual monitoring stations?",
     "They generate real-time, uninterrupted 24x7 sensor data on criteria pollutants transmitted instantly to public online AQI portals",
     ["They physically absorb all air pollutants from an entire 50-kilometer city radius", "They eliminate the need for any national air quality standards", "They run exclusively by burning coal inside the monitoring kiosk"],
     "CAAQMS stations provide real-time continuous pollutant measurements, enabling automated instant computation of the National Air Quality Index.")
]

# ==============================================================================
# Slot 15: Water Pollution Fundamentals (Sources, DO, BOD, COD, Thermal)
# ==============================================================================
s15_raw = [
    ("mcq", "Point vs Non-Point Sources of Water Pollution",
     "Which of the following is a classic example of a 'point source' of water pollution?",
     "A concrete industrial discharge pipe pouring untreated chemical effluent directly from a factory into a river",
     ["Agricultural fertilizer and pesticide runoff washing off thousands of scattered farm fields during rains", "Acidic atmospheric deposition falling uniformly across a mountain lake watershed", "Diffuse urban stormwater runoff washing oil and pet waste off city streets"],
     "Point sources discharge pollutants from distinct, identifiable conveyances (e.g. factory pipes), while non-point sources are diffuse (e.g. farm runoff)."),
    ("stmt", "Dissolved Oxygen (DO) and Aquatic Health",
     "A healthy, unpolluted freshwater ecosystem typically maintains a Dissolved Oxygen (DO) concentration of 8.0 mg/L or higher at 20 degrees Celsius.",
     "When DO levels fall below 4.0 mg/L, the water is classified as heavily polluted and becomes lethal to most fish species, triggering mass fish kills.", 1,
     "Both Statement I and Statement II are correct. High DO indicates clean water; organic decomposition consumes oxygen, and levels below 4 mg/L cause widespread fish mortality."),
    ("ar", "Biochemical Oxygen Demand (BOD) and Pollution",
     "A high Biochemical Oxygen Demand (BOD) value indicates heavy organic water pollution.",
     "BOD measures the amount of dissolved oxygen required by aerobic microorganisms to biologically decompose the biodegradable organic matter present in a unit volume of water.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). More organic waste stimulates aerobic bacterial blooms, which consume oxygen and yield a high BOD."),
    ("match", "Water Quality Parameters and Standard Testing Conditions",
     "Match the water quality parameter in List I with its scientific definition in List II:",
     [("A", "Dissolved Oxygen (DO)"),
      ("B", "Biochemical Oxygen Demand (BOD)"),
      ("C", "Chemical Oxygen Demand (COD)"),
      ("D", "Fecal Coliform Count")],
     [("I", "Concentration of free, non-compound O2 molecules dissolved in water available to aquatic organisms"),
      ("II", "Amount of oxygen consumed by aerobic bacteria decomposing organic matter over 5 days at 20 degrees Celsius"),
      ("III", "Amount of oxygen required to chemically oxidize both biodegradable and non-biodegradable organic compounds using potassium dichromate"),
      ("IV", "Microbiological indicator measuring the abundance of Escherichia coli bacteria originating from human/animal sewage")],
     "A-I, B-II, C-III, D-IV",
     "DO measures available oxygen, BOD measures biological oxygen demand, COD measures total chemical oxidation, and Fecal Coliform indicates sewage contamination."),
    ("mcq", "COD vs BOD Relationship",
     "Why is the Chemical Oxygen Demand (COD) value of a wastewater sample virtually always higher than its Biochemical Oxygen Demand (BOD) value?",
     "Because strong chemical oxidants (like acidified potassium dichromate) oxidize both biodegradable and non-biodegradable organic substances, whereas bacteria only decompose biodegradable matter",
     ["Because bacteria consume inorganic heavy metals that chemical oxidants cannot touch", "Because BOD testing is conducted at absolute zero temperature", "Because COD testing only measures dissolved oxygen gas bubbles"],
     "COD measures total oxidizable organic matter (biodegradable + refractory non-biodegradable compounds), so COD is always greater than or equal to BOD."),
    ("mcq", "Thermal Pollution Ecological Mechanism",
     "When industrial facilities and thermal power stations withdraw river water for cooling and discharge superheated effluent back into the water body, the primary ecological damage results because:",
     "Warm water holds substantially less dissolved oxygen (decreasing gas solubility) and drastically increases the metabolic oxygen demand of aquatic ectotherms",
     ["Warm water immediately turns into solid ice crystals", "Warm water causes all fish to mutate into terrestrial reptiles within hours", "Warm water completely eliminates all solar radiation penetration"],
     "Solubility of gases decreases as temperature rises; thermal discharges reduce DO while accelerating fish metabolic rates, inducing acute respiratory suffocation."),
    ("stmt", "Water Prevention and Control of Pollution Act 1974",
     "The Water (Prevention and Control of Pollution) Act was enacted in 1974 as India's first comprehensive environmental legislation.",
     "The Act established the Central Pollution Control Board (CPCB) and State Pollution Control Boards (SPCBs) to enforce effluent standards.", 1,
     "Both Statement I and Statement II are correct. The Water Act 1974 created the institutional machinery (CPCB/SPCBs) for nationwide water monitoring."),
    ("seq", "Oxygen Sag Curve Dynamics Downstream of Sewage Discharge",
     "Arrange the sequential zones along a river as it recovers downstream from a massive point-source sewage discharge (Streeter-Phelps Oxygen Sag):",
     ["Clean Zone: high dissolved oxygen (DO > 8 mg/L) and low biological oxygen demand", "Zone of Degradation: sewage influx triggers explosive bacterial bloom, DO plummets rapidly, BOD surges", "Zone of Active Decomposition: DO reaches lowest critical minimum (septic conditions), sludge worms and anaerobic bacteria dominate", "Zone of Recovery followed by Clean Zone: natural re-aeration replenishes DO, organic load is fully assimilated, game fish return"],
     "I -> II -> III -> IV",
     "Downstream of sewage discharge, the river passes through degradation, septic decomposition (sag minimum), re-aeration recovery, and restored clean water."),
    ("mcq", "Suspended Solids and Turbidity",
     "Excessive Total Suspended Solids (TSS) and turbidity in freshwater bodies harm aquatic primary productivity primarily by:",
     "Scattering and blocking sunlight penetration through the photic zone, thereby inhibiting submerged macrophyte and phytoplankton photosynthesis",
     ["Increasing water boiling temperature above 200 degrees Celsius", "Absorbing all atmospheric nitrogen gas", "Converting freshwater into pure seawater"],
     "High turbidity blocks light penetration, curtailing photosynthesis in submerged plants while clogging benthic gravels and fish gill filaments."),
    ("ar", "Organic Sewage and Pathogen Transmission",
     "Untreated municipal sewage discharge into drinking water sources poses a grave risk of epidemic waterborne diseases.",
     "Municipal sewage carries high loads of enteric pathogens, including bacteria (Vibrio cholerae, Salmonella typhi), viruses (Hepatitis A, Poliovirus), and protozoans (Entamoeba histolytica).", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Raw human sewage contains high titers of excreted fecal pathogens that contaminate downstream drinking intakes."),
    ("mcq", "Standard Drinking Water Quality for Fecal Coliform",
     "According to the Bureau of Indian Standards (BIS 10500:2012) and WHO drinking water guidelines, what is the mandatory permissible limit for E. coli or fecal coliforms in 100 mL of treated drinking water?",
     "Zero / Shall not be detectable in any 100 mL sample",
     ["Less than 50 coliforms per 100 mL", "Exactly 500 coliforms per 100 mL", "Up to 1,000 coliforms per 100 mL"],
     "Treated drinking water must contain ZERO detectable fecal coliforms or E. coli per 100 mL sample to be safe for human consumption."),
    ("mcq", "Total Dissolved Solids (TDS) Upper Desirable Limit",
     "Under BIS 10500 standards for drinking water, what is the desirable acceptable limit for Total Dissolved Solids (TDS) in drinking water?",
     "500 mg/L (with permissible limit extending to 2,000 mg/L in absence of alternate sources)",
     ["50 mg/L", "10,000 mg/L", "35,000 mg/L (equivalent to seawater)"],
     "Acceptable limit for TDS in drinking water is 500 mg/L; beyond this, palatability decreases and scaling occurs."),
    ("match", "Water Pollution Terms and Technical Indicators",
     "Match the water quality concept in List I with its environmental indicator in List II:",
     [("A", "Oligotrophic Lake"),
      ("B", "Eutrophic Lake"),
      ("C", "Septic Zone"),
      ("D", "Leachate")],
     [("I", "Deep, clear, nutrient-poor lake with low productivity and high dissolved oxygen"),
      ("II", "Shallow, nutrient-rich water body covered in dense algal scums with severe oxygen depletion"),
      ("III", "Anaerobic stretch of a river where dissolved oxygen is completely exhausted"),
      ("IV", "Toxic liquid that has percolated through solid landfill waste, picking up dissolved pollutants")],
     "A-I, B-II, C-III, D-IV",
     "Oligotrophic is clean and nutrient-poor, eutrophic is nutrient-rich with algal blooms, septic is anoxic, and leachate is contaminated landfill runoff."),
    ("mcq", "Thermal Stratification and Epilimnion/Hypolimnion",
     "In deep temperate lakes during summer, thermal stratification separates the water column into a warm, sunlit surface layer and a cold, dense bottom layer called respectively:",
     "Epilimnion (warm surface) and Hypolimnion (cold bottom), separated by the Thermocline",
     ["Mesosphere and Troposphere", "Photic zone and Core zone", "Transition zone and Buffer zone"],
     "Thermal stratification creates three layers: upper warm Epilimnion, steep gradient Thermocline (Metalimnion), and lower cold Hypolimnion."),
    ("mcq", "Salinity Unit in Estuarine Ecology",
     "Salinity of natural waters is standardly reported in parts per thousand (ppt). What are the characteristic average salinity values for freshwater, brackish water, and oceans respectively?",
     "Freshwater: < 0.5 ppt; Brackish water: 0.5 to 30 ppt; Ocean seawater: 30 to 35 ppt",
     ["Freshwater: 35 ppt; Ocean: 0.5 ppt; Hypersaline: 5 ppt", "Freshwater: 100 ppt; Brackish water: 50 ppt; Ocean: 10 ppt", "All waters have exactly 50 ppt salinity"],
     "Freshwater has salinity < 0.5 ppt, brackish water ranges from 0.5 to 30 ppt, and typical marine seawater averages 35 ppt."),
    ("stmt", "Water Pollution Cess Act 1977",
     "The Water (Prevention and Control of Pollution) Cess Act was passed in 1977 to generate financial resources for Central and State Pollution Control Boards.",
     "The cess was levied on local authorities and specified industries based on the volume of water consumed for industrial and domestic purposes.", 1,
     "Both Statement I and Statement II are correct. The Water Cess Act 1977 levied consumption taxes on industrial water users to fund pollution board operations."),
    ("mcq", "Oxygen Depletion by Synthetic Detergents",
     "Traditional commercial synthetic laundry detergents worsened river eutrophication and oxygen depletion because they contained high concentrations of:",
     "Sodium tripolyphosphate (STPP) builder additives that release excess bioavailable phosphorus into waterways",
     ["Radioactive cobalt isotopes", "Liquid chlorine bleach that evaporates into helium", "Pure elemental carbon that forms diamonds on river beds"],
     "Phosphates in detergents (STPP) act as major limiting nutrient inputs that stimulate massive cyanobacterial blooms in freshwater bodies."),
    ("seq", "Laboratory Measurement of Biochemical Oxygen Demand (BOD5)",
     "Arrange the laboratory protocol steps for determining the 5-day BOD (BOD5 at 20 degrees Celsius) of a wastewater sample:",
     ["Aliquots of wastewater are diluted with aerated, nutrient-enriched dilution water and filled into airtight BOD glass bottles", "Initial Dissolved Oxygen (DO_initial) is measured immediately in one bottle using the Winkler iodometric titration or DO probe", "The remaining sealed incubation bottles are placed in a dark incubator maintained at 20 degrees Celsius for precisely 5 days", "Final Dissolved Oxygen (DO_final) is measured on Day 5; BOD is calculated as (DO_initial - DO_final) multiplied by the dilution factor"],
     "I -> II -> III -> IV",
     "Standard 5-day BOD protocol: prepare dilution, measure Day-0 DO, incubate in the dark at 20 C for 5 days, measure Day-5 DO, and compute depletion x dilution factor."),
    ("mcq", "Primary vs Secondary Wastewater Treatment",
     "In a modern Sewage Treatment Plant (STP), what is the fundamental functional difference between 'Primary Treatment' and 'Secondary Treatment'?",
     "Primary treatment is a physical process removing settleable and floating solids via screening and sedimentation; Secondary treatment is a biological process using aerobic microbes to digest dissolved organic matter",
     ["Primary treatment kills all viruses with radiation, while secondary treatment adds chemical fertilizers", "Primary treatment occurs in open rivers, while secondary treatment occurs in household kitchens", "Both stages are identical physical filtration steps through sand beds"],
     "Primary treatment is physical (screening and settling tanks), whereas secondary treatment is biological (activated sludge or trickling filters reducing BOD)."),
    ("mcq", "Advanced Tertiary Wastewater Treatment",
     "Tertiary wastewater treatment is designed to remove which stubborn contaminants that survive conventional biological secondary treatment?",
     "Dissolved nutrients (phosphorus and nitrogen), recalcitrant heavy metals, and pathogenic microbes via disinfection (chlorination or UV irradiation)",
     ["Only large floating tree branches and plastic bottles", "Coarse sand and grit particles settling in bar screens", "Elemental oxygen bubbles dissolved in the aeration basin"],
     "Tertiary treatment provides polishing: nutrient removal (nitrification-denitrification, chemical phosphorus precipitation) and pathogen disinfection (UV/chlorine).")
]
'''

with open('scripts/subject_generators/make_evs_s11_15.py', 'w') as f:
    f.write(s11_to_15)

print("make_evs_s11_15.py written.")
