# Slots 26 to 30 Generator
s26_to_30 = '''
# ==============================================================================
# Slot 26: Green Revolution Impacts & Agricultural Sustainability
# ==============================================================================
s26_raw = [
    ("mcq", "Pioneers of Green Revolution",
     "The global Green Revolution was catalyzed by Nobel Peace Prize laureate Norman Borlaug through developing semi-dwarf wheat varieties, while in India it was spearheaded by renowned geneticist:",
     "Dr. M.S. Swaminathan",
     ["Dr. Verghese Kurien", "Dr. Homi Bhabha", "Dr. Salim Ali"],
     "Dr. M.S. Swaminathan led India's Green Revolution in the 1960s, introducing semi-dwarf high-yielding Mexican wheat lines (Lerma Rojo, Sonora 64) with Norman Borlaug."),
    ("stmt", "High-Yielding Varieties (HYVs) Requirements",
     "The high-yielding dwarf varieties (HYVs) of wheat and rice introduced during the Green Revolution were highly responsive to synthetic chemical fertilizers.",
     "To achieve their genetic yield potential, HYVs required an input-intensive package of chemical NPK fertilizers, heavy canal/tube-well irrigation, and chemical pesticides.", 1,
     "Both Statement I and Statement II are correct. HYVs were non-lodging, fertilizer-responsive varieties requiring assured irrigation and chemical agrochemical inputs."),
    ("ar", "Pesticide Treadmill and Pest Resurgence",
     "Continuous, intensive application of synthetic chemical insecticides often leads to severe 'pest resurgence' and secondary pest outbreaks.",
     "Broad-spectrum chemical insecticides destroy natural co-evolved predators and parasitoids (spiders, ladybird beetles) that previously kept pest populations in check, while target pests evolve resistance.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The 'pesticide treadmill' occurs when killing natural predators and selecting resistant survivors forces farmers to spray higher doses of costlier chemicals."),
    ("match", "Green Revolution Crops and Landmark Cultivars",
     "Match the landmark Green Revolution crop variety in List I with its agricultural crop in List II:",
     [("A", "Sonalika and Kalyan Sona"),
      ("B", "IR8 ('Miracle Rice')"),
      ("C", "Jaya and Padma"),
      ("D", "Sharbati Sonora")],
     [("I", "Semi-dwarf high-yielding wheat selections developed in India"),
      ("II", "Semi-dwarf miracle rice developed by the International Rice Research Institute (IRRI)"),
      ("III", "High-yielding semi-dwarf rice varieties developed by Indian scientists"),
      ("IV", "Amber-grained mutant wheat variety developed at IARI via gamma irradiation")],
     "A-I, B-II, C-III, D-IV",
     "Sonalika/Kalyan Sona are dwarf wheats; IR8 is IRRI miracle rice; Jaya/Padma are Indian dwarf rices; and Sharbati Sonora is a gamma-irradiated mutant wheat developed by M.S. Swaminathan."),
    ("mcq", "Groundwater Depletion in Green Revolution Heartlands",
     "The relentless cultivation of water-intensive paddy-wheat crop rotations in Punjab and Haryana has caused catastrophic environmental decline, characterized by:",
     "Severe depletion of deep groundwater aquifers (falling by 0.5 to 1.0 meters per year) due to free electricity and motorized tube-well extraction",
     ["Permanent flooding turning Punjab into an open saltwater ocean", "The complete cessation of all summer solar radiation", "Instant transformation of Punjab soil into Arctic permafrost"],
     "Paddy cultivation in semi-arid Punjab consumes ~3,000–5,000 liters of water per kg of rice, depleting fossil groundwater tables to alarming depths (>30 meters)."),
    ("mcq", "Erosion of Indigenous Genetic Agro-Biodiversity",
     "One of the gravest long-term ecological casualties of the Green Revolution in India was the widespread displacement and loss of:",
     "Thousands of diverse, climate-resilient traditional indigenous landraces of rice, millets, and pulses adapted to local microclimates and pests",
     ["All synthetic chemical fertilizer manufacturing factories", "All electric railway tracks connecting rural towns", "All domestic cattle breeds throughout South Asia"],
     "Monocultures of a few dwarf HYV varieties replaced over 30,000 diverse indigenous rice landraces (such as deep-water, saline-tolerant, and drought-hardy varieties)."),
    ("stmt", "NPK Imbalance in Indian Soils",
     "The scientifically recommended balanced ratio for Nitrogen, Phosphorus, and Potassium (N:P:K) fertilizer application for cereal crops is generally 4:2:1.",
     "Disproportionate government subsidies on Urea led to distorted application ratios exceeding 30:8:1 in states like Punjab, causing micronutrient exhaustion and nitrate pollution.", 1,
     "Both Statement I and Statement II are correct. Heavily subsidized urea led to massive over-application of nitrogen, degrading soil physical crumb structure and polluting aquifers."),
    ("seq", "Ecological Feedback Loop of the Chemical Pesticide Treadmill",
     "Arrange the stages illustrating the agricultural 'pesticide treadmill':",
     ["Routine prophylactic application of broad-spectrum synthetic chemical insecticide on a monoculture crop", "Non-target mortality: beneficial predatory spiders, parasitic wasps, and pollinators are decimated", "Target pest population rebounds explosively (pest resurgence) as surviving resistant mutants multiply without natural predator control", "Farmers escalate spray frequency and switch to higher dosages of more toxic, expensive chemical cocktails"],
     "I -> II -> III -> IV",
     "Pesticide treadmill: broad-spectrum spraying, predator wipeout, target resistance resurgence, and escalated chemical dependency."),
    ("mcq", "Secondary Pest Outbreak Definition",
     "In agro-ecology, a 'Secondary Pest Outbreak' occurs when:",
     "An insect species that was previously minor and non-damaging explodes into a devastating major pest because chemical sprays eradicated its natural predators",
     ["Cattle enter an agricultural field and eat standing wheat", "Migratory birds fly over farm fields without feeding", "Earthworms burrow into garden compost beds"],
     "Secondary pest outbreaks (e.g. whiteflies or spider mites surging in cotton) happen when insecticides eliminate the natural predators that previously suppressed minor pests."),
    ("ar", "Evergreen Revolution Paradigm",
     "Dr. M.S. Swaminathan advocated transitioning from the original Green Revolution to an 'Evergreen Revolution'.",
     "An Evergreen Revolution aims to achieve productivity enhancement in perpetuity without associated ecological harm, by integrating organic principles, soil conservation, and biotechnology.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Swaminathan warned that an exploitative green revolution turns fertile lands into deserts; the evergreen revolution balances yield with ecological sustainability."),
    ("mcq", "Endosulfan Tragedy in Kasargod, Kerala",
     "The aerial spraying of the organochlorine pesticide 'Endosulfan' over government cashew plantations in Kasargod, Kerala (1976–2000), triggered a public health catastrophe causing:",
     "Severe neurobehavioral disorders, congenital physical deformities in children, hydrocephalus, and cancers, leading to a Supreme Court ban",
     ["Immediate transformation of all cashew trees into golden sandalwood", "Zero health impacts on any human or animal populations", "The complete elimination of malaria without any side effects"],
     "Aerial spraying of Endosulfan poisoned the Kasargod biosphere, causing tragic congenital birth defects, mental retardation, and endocrine cancers, prompting a national ban in 2011."),
    ("mcq", "Crop Diversity and Food Security",
     "Why do agro-ecologists strongly advocate reviving 'Millets' (Shree Anna: Ragi, Jowar, Bajra) in Indian agriculture?",
     "Because millets are hardy C4 crops with low water requirements, highly drought-resilient, rich in micronutrients and fiber, and thrive in poor soils without heavy chemical inputs",
     ["Because millets require 10 times more water than lowland flooded paddy", "Because millets can only be grown inside heated greenhouse laboratories", "Because millets contain zero carbohydrates or calories"],
     "Millets are climate-smart C4 crops requiring ~70% less water than rice, resisting heat waves, and providing rich iron, calcium, and dietary fiber."),
    ("match", "Agrochemical Categories and Environmental Hazards",
     "Match the agrochemical class in List I with its signature ecological threat in List II:",
     [("A", "Synthetic Nitrogenous Fertilizers (Urea)"),
      ("B", "Organochlorine Insecticides (DDT, Endosulfan)"),
      ("C", "Organophosphate Insecticides (Malathion, Chlorpyrifos)"),
      ("D", "Chemical Herbicides (Glyphosate / 2,4-D)")],
     [("I", "Groundwater nitrate contamination, soil acidification, and lake eutrophication"),
      ("II", "Extreme environmental persistence, lipophilic bioaccumulation, and biomagnification"),
      ("III", "Potent acetylcholinesterase inhibition causing acute neurotoxicity in farm labor"),
      ("IV", "Non-target herbicide drift killing beneficial wildflowers, soil fungi, and pollinators")],
     "A-I, B-II, C-III, D-IV",
     "Urea drives nitrate leaching/eutrophication; organochlorines biomagnify; organophosphates inhibit cholinesterase; and herbicides destroy non-target flora and soil microbes."),
    ("mcq", "Pest Resistance Genetics",
     "How do target insect populations genetically evolve resistance to chemical pesticides over generations of continuous exposure?",
     "Pesticides act as an intense selective pressure: the rare individuals possessing pre-existing genetic mutations (e.g. enhanced detoxifying enzymes) survive and pass the resistance alleles to their offspring",
     ["Insects consciously decide to modify their internal organs to consume the poison as food", "The chemical pesticide causes all insects to mutate into non-reproductive drones", "Insects absorb the pesticide and use it to fly faster than airplanes"],
     "Pesticide resistance is Darwinian natural selection: insecticides wipe out susceptible individuals, leaving resistant variants to reproduce and dominate future generations."),
    ("mcq", "Pesticide Residue Limits (MRL)",
     "In food safety and environmental health, what does 'Maximum Residue Limit' (MRL) represent?",
     "The highest legally tolerated concentration of a pesticide residue in food or animal feed, based on good agricultural practice and toxicological safety",
     ["The maximum number of pesticide bottles a retail farmer can purchase in one month", "The lowest price at which a chemical dealer can sell an insecticide", "The maximum weight of a grain sack exported abroad"],
     "MRL is the maximum legal concentration of pesticide residue allowed on food commodities, regulated in India by FSSAI and internationally by Codex Alimentarius."),
    ("stmt", "Food Corporation of India (FCI) Storage and Food Waste",
     "The Green Revolution succeeded in making India self-sufficient in cereal production, accumulating massive buffer stocks in Food Corporation of India (FCI) godowns.",
     "However, inadequate covered scientific warehousing leads to substantial post-harvest storage losses from fungal spoilage, rodent infestation, and moisture damage.", 1,
     "Both Statement I and Statement II are correct. Production success must be matched by cold-chain and airtight hermetic silo storage to prevent post-harvest food waste."),
    ("mcq", "Saline Water Ingress in Coastal Agriculture",
     "Over-pumping of coastal freshwater aquifers to irrigate intensive commercial crops in coastal Gujarat and Tamil Nadu has caused which severe hydro-geological problem?",
     "Seawater intrusion / Saline water ingress, contaminating freshwater wells with saltwater and permanently salinizing agricultural soils",
     ["Volcanic magma seeping upward into domestic drinking taps", "Complete disappearance of the ocean shoreline over hundreds of miles", "Transformation of all seawater into pure distilled spring water"],
     "Excessive drawdown of coastal aquifers reverses the natural hydraulic gradient, causing denser seawater to migrate inland and salinize coastal freshwater wells."),
    ("seq", "Sequence of Groundwater Contamination by Over-Fertilization",
     "Arrange the environmental steps leading to groundwater nitrate contamination from intensive agricultural fields:",
     ["Excess synthetic urea fertilizer is broadcast onto agricultural fields beyond crop assimilation capacity", "Soil nitrifying bacteria convert excess ammonium (NH4+) into highly soluble, negatively charged nitrate ions (NO3-)", "Overhead flood irrigation dissolves the unabsorbed nitrate ions and carries them down through the soil profile", "Nitrates percolate past the crop root zone into shallow water tables, elevating drinking-water nitrate levels above 45 mg/L"],
     "I -> II -> III -> IV",
     "Nitrate pollution sequence: over-application of urea, microbial nitrification, leaching with irrigation water, and deep aquifer contamination."),
    ("mcq", "Loss of Honeybees and Pollination Crisis",
     "The widespread application of systemic neonicotinoid pesticides (such as Imidacloprid) in intensive agriculture is implicated globally in 'Colony Collapse Disorder' (CCD) because they:",
     "Impair honeybee navigation, memory, foraging behavior, and immune resistance at sub-lethal concentrations, threatening global crop pollination",
     ["Physically blind honeybees by turning their compound eyes into solid wax", "Attract millions of hornets to build nests inside bee hives", "Increase bee flying speed to 500 kilometers per hour"],
     "Neonicotinoids are systemic neurotoxins that translocate into nectar and pollen, disorienting honeybee navigation dances and devastating pollinators."),
    ("mcq", "Kharif vs Rabi Agricultural Seasons in India",
     "Which of the following pairings correctly matches an Indian cropping season with its characteristic duration and primary cereal crops?",
     "Kharif: Monsoon sowing (June-July) and autumn harvesting (Sept-Oct), featuring Rice, Maize, Jowar, and Cotton",
     ["Rabi: Monsoon sowing (July) and summer harvesting (May), featuring flooded Paddy and Jute", "Zaid: Winter sowing (December) and rainy harvesting (August), featuring Wheat and Mustard", "Kharif: Winter season from November to April, featuring Barley and Chickpea"],
     "Kharif crops coincide with the southwest monsoon (Rice, Maize, Cotton); Rabi crops are winter-sown (Wheat, Barley, Mustard, Gram); Zaid crops grow in summer (melons, cucumber).")
]

# ==============================================================================
# Slot 27: Sustainable Agriculture & Organic Farming Practices
# ==============================================================================
s27_raw = [
    ("mcq", "Four Principles of Organic Agriculture (IFOAM)",
     "According to the International Federation of Organic Agriculture Movements (IFOAM), organic agriculture is guided by which four foundational ethical principles?",
     "The Principles of Health, Ecology, Fairness, and Care",
     ["The Principles of Profit, Exploitation, Expansion, and Monopoly", "The Principles of Chemicalization, Mechanization, Hybridization, and Acceleration", "The Principles of Monoculture, Deforestation, Irrigation, and Taxation"],
     "IFOAM establishes that organic farming must sustain the health of soils, ecosystems, and people; be based on living ecological systems; ensure fairness; and be managed with care."),
    ("stmt", "Sikkim as World's First 100% Organic State",
     "In 2016, Sikkim was officially declared as India's and the world's first '100% Organic State'.",
     "In 2018, Sikkim won the prestigious UN Food and Agriculture Organization (FAO) Future Policy Gold Award (the 'Oscar for best policies') for its comprehensive transition.", 1,
     "Both Statement I and Statement II are correct. Sikkim phased out chemical fertilizers and pesticides completely, transforming over 75,000 hectares into certified organic agriculture."),
    ("ar", "Zero Budget Natural Farming (ZBNF) Philosophy",
     "Zero Budget Natural Farming (ZBNF), formulated by agricultural scientist Subhash Palekar, aims to eliminate farmers' dependency on purchased market inputs.",
     "ZBNF utilizes on-farm biological formulations prepared from native indigenous cow dung, urine, jaggery, and pulse flour, slashing cultivation production costs to nearly zero.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). ZBNF replaces costly commercial inputs with locally brewed microbial cultures, liberating smallholders from the debt cycle."),
    ("match", "Four Pillars of ZBNF (Subhash Palekar Natural Farming)",
     "Match the ZBNF core pillar in List I with its preparation/biological role in List II:",
     [("A", "Bijamrita"),
      ("B", "Jiwamrita"),
      ("C", "Acchadana"),
      ("D", "Whapasa")],
     [("I", "Natural seed treatment formulation of cow dung, urine, lime, and virgin soil protecting seeds from fungal diseases"),
      ("II", "Fermented microbial inoculum of fresh cow dung, urine, jaggery, pulse flour, and soil that stimulates soil microflora"),
      ("III", "Mulching using crop residues (straw, dried biomass) to conserve moisture and suppress weeds"),
      ("IV", "Soil condition where both air molecules and water molecules coexist in the root zone, avoiding saturation")],
     "A-I, B-II, C-III, D-IV",
     "Bijamrita is seed treatment, Jiwamrita is microbial soil inoculant, Acchadana is mulching, and Whapasa is optimal soil aeration/moisture balance."),
    ("mcq", "Jaivik Bharat Logo Signification",
     "The 'Jaivik Bharat' certification logo introduced by FSSAI on organic food packaging in India signifies that the product:",
     "Complies strictly with certified organic food standards under the National Programme for Organic Production (NPOP) or Participatory Guarantee System (PGS-India)",
     ["Contains genetically modified organisms approved for animal feed", "Was processed using high-dose ionizing gamma irradiation", "Was manufactured using synthetic chemical preservatives"],
     "The Jaivik Bharat green leaf and tick logo certifies that food products meet NPOP (third-party) or PGS-India (peer-group) organic standards."),
    ("mcq", "Participatory Guarantee System (PGS-India)",
     "Under the Ministry of Agriculture's 'Paramparagat Krishi Vikas Yojana' (PKVY), the 'Participatory Guarantee System' (PGS-India) differs from third-party organic certification because:",
     "It is a decentralized, peer-review certification process operated by localized farmer groups, making organic certification affordable for smallholders",
     ["It requires expensive multi-thousand-dollar annual audits by private foreign European agencies", "It allows farmers to spray synthetic DDT once every month", "It applies exclusively to nuclear laboratory-grown meat products"],
     "PGS-India is a participatory, community-based certification where neighboring farmers inspect each other's organic compliance, eliminating costly third-party certification fees."),
    ("stmt", "Permaculture Design Principles (Bill Mollison)",
     "Permaculture (permanent agriculture / permanent culture) was developed in the 1970s by Australian ecologists Bill Mollison and David Holmgren.",
     "Permaculture designs human habitats and agricultural systems by mimicking the diversity, resilience, and patterns observed in natural climax ecosystems.", 1,
     "Both Statement I and Statement II are correct. Permaculture integrates architecture, agroforestry, rainwater harvesting, and companion planting into closed-loop systems."),
    ("seq", "Process of Preparing Farm-Brewed Jiwamrita Inoculant",
     "Arrange the traditional steps for preparing 200 liters of liquid Jiwamrita (enough for one acre of natural farming):",
     ["Mix 10 kg of fresh Desi cow dung with 10 liters of Desi cow urine in a 200-liter plastic drum", "Add 2 kg of organic jaggery (or sugarcane juice) and 2 kg of pulse flour (besan) along with a handful of virgin forest soil", "Fill the barrel with 200 liters of chemical-free water and stir vigorously clockwise with a wooden stick", "Keep the drum in shade covered with a moist gunny bag, stirring twice daily for 48 to 72 hours until microbial fermentation peaks"],
     "I -> II -> III -> IV",
     "Jiwamrita preparation: blend dung/urine, add jaggery/besan/virgin soil, dilute with 200L water, and ferment in shade for 2–3 days."),
    ("mcq", "Crop Rotation and Pest Disruption",
     "Why is systematic 'Crop Rotation' (e.g., alternating cereal crops with leguminous pulses) considered a cornerstone of sustainable agriculture?",
     "It breaks host-specific pest and disease reproductive cycles, balances soil nutrient extraction, and enriches soil nitrogen via leguminous biological fixation",
     ["It guarantees that crops grow without requiring any sunlight", "It eliminates the need for harvesting crops forever", "It prevents weeds from ever germinating in the soil profile"],
     "Alternating crop families denies pests continuous host tissue, balances nutrient drawdown, and replenishes nitrogen naturally through legumes."),
    ("ar", "Green Manuring Benefits",
     "Ploughing in green manure crops (such as Dhaincha / Sesbania aculeata or Sunn hemp / Crotalaria juncea) dramatically improves soil fertility.",
     "Green manures fix atmospheric nitrogen in root nodules and incorporate massive amounts of soft organic biomass, stimulating soil earthworms and microbial activity.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Green manuring provides ~60–80 kg of organic nitrogen per hectare and enhances soil humus and moisture retention."),
    ("mcq", "Companion Planting and Push-Pull Technology",
     "In sustainable farming, the celebrated 'Push-Pull' pest management technology developed in Africa utilizes companion planting where:",
     "A repellent intercrop (like Desmodium) 'pushes' stemborer moths away from the main maize crop, while a border trap crop (like Napier grass) 'pulls' and attracts them to lay eggs on an infertile plant",
     ["Tractors push all weeds into neighboring farms and pull down all trees", "Chemical insecticides are sprayed with high-pressure push pumps", "Farmers pull up all crops every night to protect them from insects"],
     "Push-pull uses companion plants: Desmodium emits volatiles that repel stemborers (push), while border Napier grass attracts them (pull) and traps larvae in sticky sap."),
    ("mcq", "Polyculture vs Monoculture Resilience",
     "Why are agricultural 'Polycultures' (growing multiple compatible crop species together on the same land) far more resilient than monocultures?",
     "Varied canopy heights, complementary root depths, and diverse ecological niches maximize sunlight and nutrient capture while preventing single-pathogen crop devastation",
     ["Polycultures require 10 times more chemical fertilizers than monocultures", "All polyculture crops mature simultaneously within 2 hours", "Polycultures eliminate all biological life except a single crop"],
     "Polycultures optimize niche differentiation, resist pest epidemics, and maintain soil coverage, mimicking natural polytypic ecosystem stability."),
    ("match", "Sustainable Agricultural Concepts and Definitions",
     "Match the sustainable farming technique in List I with its practical method in List II:",
     [("A", "Alley Cropping"),
      ("B", "Cover Cropping"),
      ("C", "Strip Cropping"),
      ("D", "Dryland Mulching")],
     [("I", "Cultivating food crops in corridors between rows of nitrogen-fixing trees or pruned shrubs"),
      ("II", "Planting low-growing legumes specifically to prevent soil erosion and weed growth between cash crops"),
      ("III", "Growing erosion-prone crops and erosion-resistant cover crops in alternating narrow contour strips"),
      ("IV", "Covering soil with dry straw or leaf litter to suppress evaporation and maintain root moisture")],
     "A-I, B-II, C-III, D-IV",
     "Alley cropping grows crops between tree hedgerows, cover cropping shields bare soil, strip cropping alternates contours, and mulching conserves moisture."),
    ("mcq", "Paramparagat Krishi Vikas Yojana (PKVY)",
     "The primary objective of the Ministry of Agriculture's flagship scheme 'Paramparagat Krishi Vikas Yojana' (PKVY) launched in 2015 is to:",
     "Promote organic farming among smallholders through cluster-based mobilization, capacity building, and PGS-India certification support",
     ["Distribute free chemical pesticide tankers to all farming households", "Convert all organic farms into commercial chemical fertilizer manufacturing plants", "Mandate that all crops be cultivated without soil using plastic hydroponics"],
     "PKVY supports traditional organic farming in 50-acre farmer clusters, providing financial assistance for organic inputs, PGS certification, and marketing."),
    ("mcq", "Bio-Dynamic Agriculture Steiner Concept",
     "Initiated by Austrian philosopher Rudolf Steiner in 1924, 'Biodynamic Agriculture' is an organic farming system characterized by:",
     "Viewing the farm as a self-contained living organism and utilizing specialized herbal and mineral compost preparations (e.g. Horn Manure 500) aligned with celestial rhythms",
     ["Using nuclear fission energy to heat greenhouse seedling trays", "Eliminating all animals from farm ecosystems to prevent grazing", "Spraying liquid copper sulfate every morning on bare soil"],
     "Biodynamic farming (Demeter certification) treats the farm as a holistic organism, using specialized preparations (500-508) and lunar planting calendars."),
    ("stmt", "National Programme for Organic Production (NPOP)",
     "The National Programme for Organic Production (NPOP) was launched by the Ministry of Commerce and Industry in 2001.",
     "NPOP provides third-party certification standards for organic agricultural exports, accredited by APEDA and recognized by the European Union and USDA.", 1,
     "Both Statement I and Statement II are correct. NPOP is India's formal institutional framework for third-party organic certification, essential for export markets."),
    ("mcq", "System of Rice Intensification (SRI) Principles",
     "The 'System of Rice Intensification' (SRI) enables farmers to increase paddy yields while reducing water consumption by 30–50% by adopting which practices?",
     "Transplanting young single seedlings (8–12 days old) at wide square spacing (25x25 cm), keeping soil moist rather than flooded, and using mechanical weeders",
     ["Flooding the paddy field with 1 meter of continuous standing water", "Planting 50 old seedlings per hill tightly packed together", "Spraying heavy chemical insecticides every 3 days"],
     "SRI (developed by Fr. Henri de Laulanie in Madagascar) uses single young seedlings, wide spacing, alternate wetting and drying (AWD), and mechanical cono-weeding."),
    ("seq", "Conversion Stages from Chemical to Certified Organic Farm",
     "Arrange the mandatory progressive stages for a conventional chemical farm to attain formal NPOP 'Certified Organic' status:",
     ["Submission of application, farm history dossier, and inspection contract to an accredited certification body", "Conversion Year 1: complete cessation of all prohibited synthetic agrochemicals and establishment of boundary buffer zones", "Conversion Year 2 and 3: ongoing third-party audits, soil testing, and documentation of organic management practices", "Issuance of Scope Certificate formally granting 'Certified Organic' status after completing the 3-year transition period"],
     "I -> II -> III -> IV",
     "Organic conversion: application, Year-1 agrochemical cessation, Year-2/3 transitional audits, and final Certified Organic scope certification after 3 years."),
    ("mcq", "Desi vs Exotic Cattle Dung in Natural Farming",
     "Why does Subhash Palekar's natural farming framework specifically advocate the dung and urine of indigenous Indian zebu cattle (Bos indicus) over exotic European breeds (Bos taurus)?",
     "Indigenous zebu cattle possess a hump and dewlap, producing dung and urine with far higher counts of beneficial probiotic microflora and humic precursors",
     ["Exotic European cattle dung contains toxic heavy metals like uranium", "Indigenous cattle dung does not contain any water or organic carbon", "Exotic cattle cannot produce any manure"],
     "Palekar argues that Bos indicus (Desi humped cattle with surya ketu nadi) harbors over 300 crore beneficial microorganisms per gram of dung, ideal for Jiwamrita fermentation."),
    ("mcq", "Conservation Agriculture Three Core Principles",
     "According to the Food and Agriculture Organization (FAO), 'Conservation Agriculture' is universally defined by the simultaneous application of which three agronomic principles?",
     "Minimum mechanical soil disturbance (zero tillage), permanent organic soil cover (mulch/cover crops), and diversified crop species rotations",
     ["Deep intensive tractor plowing, chemical pesticide drenching, and continuous wheat monoculture", "Open stubble burning, high-pressure sprinkler irrigation, and zero weeding", "Complete deforestation of all field boundaries, chemical seed coating, and night harvesting"],
     "Conservation Agriculture (CA) rests on three pillars: zero or minimum tillage, permanent soil cover with crop residues, and diversified crop rotations.")
]

# ==============================================================================
# Slot 28: Integrated Pest Management (IPM) & Biological Pest Controls
# ==============================================================================
s28_raw = [
    ("mcq", "Integrated Pest Management (IPM) Foundational Concept",
     "Integrated Pest Management (IPM) is defined by the FAO and agricultural ecologists as an ecosystem-based strategy that focuses on:",
     "Long-term prevention of pest damage through a combination of cultural, biological, and mechanical controls, using chemical pesticides only as an emergency last resort",
     ["The complete, total eradication of 100% of all insect species from agricultural landscapes", "Continuous calendar-based prophylactic spraying of synthetic chemical insecticides every week", "Replacing all biological crops with artificial plastic replicas"],
     "IPM does not aim for total pest eradication, but suppresses pest populations below the Economic Injury Level using multi-tactic biological and cultural methods."),
    ("stmt", "Economic Injury Level (EIL) vs Economic Threshold (ET)",
     "Economic Injury Level (EIL) is the lowest population density of a pest that will cause economic damage exceeding the cost of pest control.",
     "Economic Threshold (ET), also known as the Action Threshold, is the pest density at which control measures must be initiated to prevent the population from reaching the EIL.", 1,
     "Both Statement I and Statement II are correct. ET is the operational decision trigger, set lower than EIL, giving time for controls to work before economic losses occur."),
    ("ar", "Biocontrol Agents Host Specificity",
     "Effective biological pest control agents must possess high degree of host specificity toward the target pest.",
     "A biocontrol agent lacking host specificity may attack non-target beneficial insects, native caterpillars, and harmless native biodiversity.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Host specificity prevents ecological disasters (such as the Cane Toad introduction in Australia which devastated native fauna)."),
    ("match", "Biocontrol Agents and Target Agricultural Pests",
     "Match the beneficial biocontrol organism in List I with its target pest in List II:",
     [("A", "Trichogramma chilonis (Egg Parasitoid Wasp)"),
      ("B", "Coccinella septempunctata (Ladybird Beetle)"),
      ("C", "Chrysoperla carnea (Green Lacewing)"),
      ("D", "Beauveria bassiana (Entomopathogenic Fungus)")],
     [("I", "Lepidopteran borers and bollworms (Helicoverpa, Chilo)"),
      ("II", "Soft-bodied sap-sucking Aphids and Scale insects"),
      ("III", "Whiteflies, Jassids, and Thrips"),
      ("IV", "Soil white grubs, Caterpillars, and Termites")],
     "A-I, B-II, C-III, D-IV",
     "Trichogramma parasitizes moth eggs, Ladybird beetles prey on aphids, Lacewings devour whiteflies, and Beauveria infects insect cuticles as a fungal pathogen."),
    ("mcq", "Trichogramma Egg Parasitoid Cards (Tricho-Cards)",
     "How are 'Tricho-Cards' (containing eggs of the angoumois grain moth parasitized by Trichogramma wasps) deployed by farmers in sugarcane and cotton fields?",
     "Cards are stapled to the underside of crop leaves; adult micro-wasps emerge, search out and parasitize the eggs of destructive pest moths before caterpillars hatch",
     ["Cards are boiled in water and sprayed through tractor nozzles", "Cards are burned at field corners to generate chemical smoke", "Cards are buried 2 meters underground to repel earthworms"],
     "Tricho-cards release thousands of microscopic Trichogramma wasps that seek out Helicoverpa or Chilo moth eggs, laying their own eggs inside and killing the pest embryo."),
    ("mcq", "Bacillus thuringiensis (Bt) Mechanism of Action",
     "The entomopathogenic soil bacterium Bacillus thuringiensis (Bt) produces crystalline proteinaceous endotoxins (Cry proteins) that kill insect larvae by:",
     "Dissolving in the alkaline gut of susceptible caterpillars, binding to epithelial receptors, and creating pores that cause cell lysis and starvation",
     ["Freezing the insect's blood into solid ice within seconds", "Attacking the root system of host crops to starve insects", "Emitting radioactive gamma rays that disintegrate the insect shell"],
     "Bt Cry endotoxins are activated by the alkaline pH of the insect midgut, binding to cell membranes and creating lytic pores that cause fatal septicemia."),
    ("stmt", "Neem Formulations (Azadirachtin) Multiple Modes of Action",
     "Azadirachtin, the primary limonoid compound extracted from neem (Azadirachta indica) seeds, acts primarily as an antifeedant, repellent, and insect growth regulator (IGR).",
     "Unlike broad-spectrum neurotoxins, neem formulations do not knock down insects instantly, but disrupt ecdysone hormonal titers, preventing larvae from molting into adults.", 1,
     "Both Statement I and Statement II are correct. Azadirachtin deters feeding, disrupts larval molting hormones (ecdysone), and has low toxicity to beneficial pollinators."),
    ("seq", "Decision-Making Sequence in an IPM Scouting Program",
     "Arrange the sequential operational steps followed by an IPM scout in an agricultural field:",
     ["Regular systematic field scouting and sweep-net sampling to enumerate pest and natural enemy densities", "Plotting pest population density against established Economic Threshold (ET) benchmarks", "Pest density crosses Action Threshold: first deploying mechanical and biological tools (pheromone traps, biopesticides)", "If pest resurgence threatens to exceed EIL, targeted application of selective, low-persistence botanical or green-labeled pesticide"],
     "I -> II -> III -> IV",
     "IPM workflow: field monitoring/scouting, threshold evaluation, biological/cultural intervention, and emergency targeted chemical application only when necessary."),
    ("mcq", "Pheromone Traps and Mating Disruption",
     "In cotton and fruit orchards, synthetic female sex pheromone lures (such as Gossyplure for Pink Bollworm) are utilized in pest management to:",
     "Attract and trap male moths inside traps for population monitoring, and flood orchards with pheromones to confuse males, preventing successful mating",
     ["Directly poison crop roots so caterpillars cannot chew foliage", "Repel beneficial honeybees from entering the agricultural field", "Convert male insects into non-flying female drones"],
     "Sex pheromone traps serve dual roles: monitoring pest population surges and mating disruption (saturating air with pheromone so males cannot locate females)."),
    ("ar", "Cultural Pest Control and Trap Cropping",
     "Planting rows of yellow African Marigolds (Tagetes erecta) around a commercial tomato field is a classic IPM 'Trap Cropping' technique.",
     "Tomato fruit borers (Helicoverpa armigera) exhibit a strong egg-laying ovipositional preference for marigold flowers over tomato foliage, concentrating the pest on sacrificial plants.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Marigold trap crops lure Helicoverpa away from tomatoes; pests on marigolds can be collected or treated without spraying the cash crop."),
    ("mcq", "Nuclear Polyhedrosis Virus (NPV) Specificity",
     "Why are Baculoviruses, specifically Nucleopolyhedrovirus (NPV, e.g. HaNPV against Helicoverpa armigera), prized as ideal biological insecticides?",
     "They are exceptionally species-specific pathogens with zero negative impacts on plants, mammals, birds, fish, or non-target beneficial insects",
     ["They infect and kill all animal species in the ecosystem within 1 hour", "They can be used as nuclear atomic fuel in power plants", "They eliminate all bacterial and fungal life from soil"],
     "NCERT highlights that Baculoviruses (NPV) are narrow-spectrum biocontrol agents that attack only specific insect pests, leaving beneficial insects and vertebrates unhurt."),
    ("mcq", "Yellow and Blue Sticky Traps Function",
     "In greenhouse horticulture and integrated vegetable farming, bright yellow and bright blue sticky card traps are installed primarily to monitor and capture:",
     "Yellow traps capture Whiteflies, Aphids, and Leafminers; Blue traps specifically attract and capture Thrips",
     ["Yellow traps capture wild birds; Blue traps capture rodents and snakes", "Yellow traps catch falling autumn leaves; Blue traps catch rainfall", "Both traps catch only stray domestic cattle"],
     "Insects exhibit positive phototaxis to specific wavelengths: yellow attracts aphids and whiteflies, while blue attracts flower thrips, trapping them on sticky glue."),
    ("match", "Non-Chemical Pest Control Tactics and Examples",
     "Match the non-chemical pest management method in List I with its operational example in List II:",
     [("A", "Cultural Control"),
      ("B", "Mechanical / Physical Control"),
      ("C", "Biological Control"),
      ("D", "Behavioral / Semiochemical Control")],
     [("I", "Crop rotation, adjusting sowing dates to escape pest peaks, and deep summer plowing to expose pupae"),
      ("II", "Hand-picking large caterpillars, installing bird perches, and bagging fruit clusters with paper"),
      ("III", "Conserving predatory ladybird beetles, lacewings, and releasing Trichogramma wasps"),
      ("IV", "Installing synthetic sex pheromone delta traps and light traps in fields")],
     "A-I, B-II, C-III, D-IV",
     "Cultural control alters agronomic practices, mechanical uses physical removal, biological uses natural enemies, and semiochemical uses pheromone lures."),
    ("mcq", "Deep Summer Plowing as Cultural Pest Control",
     "Why do agricultural scientists recommend 'Deep Summer Plowing' of empty fields during peak summer months (May–June) before the monsoon?",
     "It inverts the soil, exposing dormant subterranean insect pupae, nematode cysts, and soil-borne fungal spores to the scorching sun and predatory birds",
     ["It freezes soil water to prevent weed seeds from absorbing moisture", "It creates underground tunnels for subterranean mining exploration", "It adds chemical synthetic pesticides directly into the subsoil"],
     "Deep summer plowing brings soil-dwelling pupae (e.g. bollworms, white grubs) and fungal sclerotia to the surface where desiccating heat and birds destroy them."),
    ("mcq", "T-Shaped Bird Perches in Paddy Fields",
     "Installing simple wooden T-shaped 'Bird Perches' (approx. 15-20 per acre) across paddy and pulse fields is an effective eco-friendly pest control measure because:",
     "They provide resting platforms for insectivorous predatory birds (like Black Drongos, Egrets, and Mynas) to perch and actively hunt insect caterpillars",
     ["They scare all birds completely away from the agricultural field", "They generate electric shocks that kill flying insect pests on contact", "They broadcast sonic frequencies that repel fungal spores"],
     "Bird perches invite predatory insectivorous birds (Black Drongos, Blue Jays, King Crows) to rest and hunt stemborers and caterpillars without chemicals."),
    ("stmt", "Cactoblastis cactorum Classic Biocontrol Success",
     "In the early 20th century, millions of hectares of Australian rangeland were rendered useless by the rampant invasion of the exotic Prickly Pear Cactus (Opuntia).",
     "The cactus was brought under complete biological control by introducing a natural cactus-feeding moth (Cactoblastis cactorum) from its native South American range.", 1,
     "Both Statement I and Statement II are correct. NCERT highlights Cactoblastis cactorum as a classic historical example of successful biological weed control."),
    ("mcq", "Refugia in Bt Transgenic Crop Cultivation",
     "Why do agricultural regulatory guidelines mandate that farmers planting genetically modified Bt Cotton must plant a non-Bt cotton border 'Refugia' around their fields?",
     "To provide a breeding refuge for Bt-susceptible insects, ensuring they mate with rare resistant mutants to dilute and delay the evolution of resistance alleles",
     ["To attract locust swarms to eat the border crops instead of Bt cotton", "To prevent cows and goats from entering the cotton field", "To export non-Bt cotton at triple the market price"],
     "Refugia rows produce millions of homozygous susceptible (SS) moths that mate with rare resistant (RR) moths, producing heterozygous (RS) offspring killed by Bt toxins."),
    ("seq", "Mode of Infection of Entomopathogenic Fungus Beauveria bassiana",
     "Arrange the sequential stages of insect death caused by the biocontrol fungus Beauveria bassiana:",
     ["Fungal conidiospores adhere to the hydrophobic waxy insect cuticle", "Spore germinates, producing an appressorium and cuticle-degrading enzymes (chitinases, proteases) that penetrate the body wall", "Fungal mycelium proliferates inside the insect hemolymph, consuming nutrients and releasing toxic beauvericin", "Insect dies of fungal septicemia; white fungal hyphae emerge through the cuticle, producing a fuzzy 'white muscardine' corpse that sheds spores"],
     "I -> II -> III -> IV",
     "Fungal biocontrol infection: spore adhesion, cuticle enzymatic penetration, hemolymph proliferation, and white muscardine sporulation."),
    ("mcq", "Entomopathogenic Nematodes (EPNs) as Biopesticides",
     "Entomopathogenic nematodes (such as Steinernema carpocapsae and Heterorhabditis) parasitize and kill destructive subterranean soil pests (like White Grubs) by:",
     "Entering the pest through natural body openings (spiracles, mouth) and releasing symbiotic bacteria (Xenorhabdus) that cause rapid lethal septicemia within 48 hours",
     ["Stinging the insect with neurotoxic venoms similar to cobra venom", "Strangling the insect by wrapping around its legs and wings", "Consuming the entire crop root system to starve the insect"],
     "EPNs enter soil grubs and release mutualistic Xenorhabdus/Photorhabdus bacteria, which multiply and convert host tissue into food, killing the pest in 24–48 hours."),
    ("mcq", "Resistance Breakdown in Indian Bt Cotton (Pink Bollworm)",
     "In recent years across Gujarat and Maharashtra, field populations of the Pink Bollworm (Pectinophora gossypiella) evolved widespread resistance to Bollgard-II Bt cotton primarily because:",
     "Farmers neglected planting mandatory non-Bt refugia borders, exposing billions of consecutive pest generations to continuous, single-toxin selective pressure",
     ["The Pink Bollworm mutated into a carnivorous bird", "Rainfall in India ceased entirely for a decade", "Farmers sprayed pure sugar water over all cotton fields"],
     "Failure to maintain non-Bt refugia allowed rare homozygous resistant Pink Bollworms to interbreed, leading to resistance breakdown against Cry1Ac and Cry2Ab toxins.")
]

# ==============================================================================
# Slot 29: Biofertilizers & Soil Health Management
# ==============================================================================
s29_raw = [
    ("mcq", "Biofertilizer Scientific Definition",
     "A 'Biofertilizer' is scientifically defined as a substance that contains:",
     "Living or latent microorganisms that, when applied to seeds, plant surfaces, or soil, colonize the rhizosphere or plant interior and promote growth by increasing nutrient availability",
     ["A mixture of synthetic chemical urea and diammonium phosphate salts", "Crushed rock phosphate pulverized with sulfuric acid in an industrial kiln", "Sterile distilled water devoid of all biological organisms"],
     "Biofertilizers are microbial inoculants (bacteria, fungi, cyanobacteria) that fix atmospheric nitrogen, solubilize phosphorus, or mobilize micronutrients naturally."),
    ("stmt", "Symbiotic vs Free-Living Nitrogen Fixers",
     "Rhizobium is a classic symbiotic nitrogen-fixing bacterium that forms specialized root nodules exclusively on leguminous host plants.",
     "Azotobacter is a free-living, aerobic nitrogen-fixing bacterium that enriches soil fertility in non-leguminous cereal and vegetable crops.", 1,
     "Both Statement I and Statement II are correct. Rhizobium requires leguminous root nodules, whereas Azotobacter fixes nitrogen independently in aerobic soils."),
    ("ar", "Leghemoglobin Role in Root Nodules",
     "Leguminous root nodules containing active nitrogen-fixing Rhizobium exhibit a characteristic pink or reddish internal color.",
     "The enzyme nitrogenase is extremely sensitive to molecular oxygen; pink 'Leghemoglobin' functions as an oxygen scavenger, maintaining an anaerobic micro-environment inside the nodule.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Nitrogenase is irreversibly poisoned by O2; leghemoglobin binds O2 with high affinity to protect nitrogenase while fueling bacteroid respiration."),
    ("match", "Biofertilizers and Biological Categories",
     "Match the biofertilizer organism in List I with its biological classification in List II:",
     [("A", "Rhizobium leguminosarum"),
      ("B", "Azospirillum brasilense"),
      ("C", "Anabaena azollae"),
      ("D", "Glomus intraradices")],
     [("I", "Symbiotic nitrogen-fixing bacterium of leguminous root nodules"),
      ("II", "Associative symbiotic nitrogen-fixing bacterium colonizing cereal root surfaces"),
      ("III", "Symbiotic cyanobacterium inhabiting the leaf cavities of the aquatic water fern Azolla"),
      ("IV", "Vesicular-Arbuscular Mycorrhizal (VAM) endomycorrhizal fungus mobilizing soil phosphorus")],
     "A-I, B-II, C-III, D-IV",
     "Rhizobium is symbiotic in legumes, Azospirillum is associative in grasses, Anabaena azollae lives inside Azolla ferns, and Glomus is a VAM phosphorus fungus."),
    ("mcq", "Azolla-Anabaena Symbiosis in Lowland Paddy",
     "The tiny aquatic water fern Azolla is widely cultivated as a dual-purpose green manure and biofertilizer in flooded rice paddies because:",
     "Its dorsal leaf cavities harbor the nitrogen-fixing cyanobacterium Anabaena azollae, contributing 40 to 60 kg of biological nitrogen per hectare per season",
     ["It releases toxic heavy metals that kill all weeds in the field", "It freezes the standing paddy water to prevent insect breeding", "It absorbs all atmospheric carbon dioxide, creating a vacuum"],
     "Azolla floats on paddy water; its symbiotic cyanobacterium fixes massive nitrogen; incorporating Azolla biomass boosts soil nitrogen and yields."),
    ("mcq", "Phosphate Solubilizing Bacteria (PSB) Mechanism",
     "A vast proportion of soil phosphorus exists in insoluble fixed forms (calcium, iron, or aluminum phosphates) unavailable to plant roots. How do Phosphate Solubilizing Bacteria (PSB like Pseudomonas striata and Bacillus megaterium) make it bioavailable?",
     "By secreting low-molecular-weight organic acids (such as citric, oxalic, and gluconic acids) that chelate mineral cations and lower rhizosphere pH, releasing soluble orthophosphate",
     ["By using nuclear transmutation to transform silicon atoms into phosphorus atoms", "By heating the soil to 500 degrees Celsius to melt rock phosphate", "By physically chewing rock phosphate minerals into microscopic dust"],
     "PSBs excrete organic acids that dissolve insoluble rock phosphates and chelate Fe/Al/Ca cations, liberating plant-absorbable H2PO4- and HPO4(2-) ions."),
    ("stmt", "Vesicular-Arbuscular Mycorrhizae (VAM) Benefits",
     "Mycorrhizae represent a symbiotic mutualism between specialized fungi (e.g., genus Glomus) and the root systems of higher plants.",
     "The extensive fungal hyphal network dramatically increases root absorption surface area, primarily absorbing phosphorus and water, while enhancing resistance to root pathogens.", 1,
     "Both Statement I and Statement II are correct. VAM fungi extend fungal hyphae meters past the root zone, channeling immobile phosphorus and water to the host plant."),
    ("seq", "Steps in Legume Root Nodule Formation by Rhizobium",
     "Arrange the sequential biological steps in the establishment of a Rhizobium-legume root nodule:",
     ["Legume roots secrete flavonoid chemical attractants into the rhizosphere, inducing Rhizobium to produce Nod factors", "Rhizobia attach to root hair tips, causing characteristic root hair curling ('shepherd's crook')", "An intracellular infection thread forms, guiding proliferating bacteria through the root cortex", "Cortical and pericycle cells divide, forming a mature nodule where bacteria differentiate into bacteroids and synthesize leghemoglobin"],
     "I -> II -> III -> IV",
     "Nodulation sequence: flavonoid signaling, root hair curling, infection thread invasion, and cortical cell division yielding pink bacteroid nodules."),
    ("mcq", "Free-Living Cyanobacteria Biofertilizers",
     "Which group of free-living, autotrophic Blue-Green Algae (Cyanobacteria) possessing specialized thick-walled cells called 'Heterocysts' fix nitrogen in Indian paddy soils?",
     "Nostoc, Anabaena, and Aulosira",
     ["Spirogyra, Chlamydomonas, and Volvox", "Agaricus, Penicillium, and Rhizopus", "E. coli, Streptococcus, and Staphylococcus"],
     "Heterocystous cyanobacteria (Aulosira, Nostoc, Anabaena, Tolypothrix) fix atmospheric nitrogen inside oxygen-impermeable heterocysts in waterlogged paddy."),
    ("ar", "Carrier-Based Inoculants Storage Vulnerability",
     "Peat- or lignite-based biofertilizer packets have a limited shelf life (typically 6 months) and lose efficacy rapidly if exposed to direct sunlight or temperatures above 30 degrees Celsius.",
     "Biofertilizers contain live, active microbial cells that rapidly perish under heat desiccation and ultraviolet exposure.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Biofertilizers rely on viable cell counts (minimum 10^7–10^8 CFU/g); heat and sunlight destroy live bacteria."),
    ("mcq", "Liquid Biofertilizers Technological Advantage",
     "Modern 'Liquid Biofertilizer' formulations developed by agricultural research institutes offer which major operational advantages over traditional solid carrier peat packets?",
     "Longer shelf life (up to 12 to 24 months), tolerance to higher temperatures (up to 45 degrees Celsius), zero carrier contamination, and compatibility with drip irrigation fertigation",
     ["They can be ignited as high-octane diesel fuel", "They allow crops to grow without any water or seeds", "They eliminate the need for agricultural harvesting"],
     "Liquid biofertilizers contain cell protectants (trehalose, glycerol) that extend viability to 1-2 years, withstand heat, and allow easy application via drip systems."),
    ("mcq", "Rhizosphere Competence Definition",
     "In soil microbiology, the term 'Rhizosphere Competence' refers to the ability of an inoculated biofertilizer microbial strain to:",
     "Survive, colonize, proliferate, and successfully compete against indigenous native soil microbes along the root surface of the growing host plant",
     ["Mutate into a parasitic insect within the plant stem", "Fly through the air to pollinate neighboring agricultural fields", "Dissolve all rock bedrock into volcanic magma"],
     "Rhizosphere competence is the competitive survival ability of an introduced biofertilizer strain to colonize root hairs despite intense competition from native soil microbes."),
    ("match", "Microbial Inoculants and Primary Target Crops",
     "Match the biofertilizer inoculant in List I with its recommended host crop in List II:",
     [("A", "Rhizobium japonicum"),
      ("B", "Azotobacter chroococcum"),
      ("C", "Azospirillum lipoferum"),
      ("D", "Acetobacter diazotrophicus")],
     [("I", "Soybean (Glycine max)"),
      ("II", "Wheat, Mustard, Vegetables, and Cotton"),
      ("III", "Maize, Sorghum, Pearl Millet, and Grasses"),
      ("IV", "Sugarcane (endophytic nitrogen fixation inside vascular tissue)")],
     "A-I, B-II, C-III, D-IV",
     "R. japonicum targets soybean, Azotobacter targets cereals/cotton, Azospirillum targets millets, and Acetobacter colonizes sugarcane stalks as an endophyte."),
    ("mcq", "Potassium Mobilizing Microorganisms (KMB)",
     "Potassium Mobilizing Bacteria (KMB, such as Frateuria aurantia) enhance agricultural soil fertility by:",
     "Dissolving insoluble potassium minerals (such as mica, illite, and feldspar) through organic acid secretion, converting them into plant-available soluble K+ ions",
     ["Transforming nitrogen gas directly into pure potassium metal", "Preventing rainwater from entering the crop root system", "Absorbing all potassium from crops and locking it into rock forever"],
     "KMB bacteria (Frateuria aurantia) secrete organic acids that solubilize mineral-bound potassium from soil silicates, boosting crop potassium nutrition naturally."),
    ("mcq", "Endomycorrhizae vs Ectomycorrhizae Distinction",
     "While Ectomycorrhizae (found in temperate forest trees like Pinus and Quercus) form a dense fungal mantle around root tips and penetrate intercellularly (Hartig net), 'Endomycorrhizae' (VAM):",
     "Penetrate directly into root cortical cells, forming specialized branched structures called 'Arbuscules' and storage structures called 'Vesicles'",
     ["Destroy the entire root system, causing immediate plant death", "Float exclusively on the surface of water without touching roots", "Live inside the green leaves of the plant canopy"],
     "Endomycorrhizae (VAM/AMF) penetrate root cortical cell walls (without breaking the plasma membrane), forming branched arbuscules for nutrient exchange and lipid vesicles for storage."),
    ("stmt", "Zinc Solubilizing Biofertilizers (ZSB)",
     "Zinc deficiency is the most widespread micronutrient disorder in Indian soils, severely limiting rice, wheat, and maize productivity.",
     "Zinc Solubilizing Bacteria (ZSB, such as Bacillus sp.) solubilize insoluble zinc oxide (ZnO) and zinc carbonate into plant-absorbable zinc ions (Zn2+).", 1,
     "Both Statement I and Statement II are correct. ZSB inoculants overcome zinc deficiency naturally, mobilizing soil zinc reserves without heavy synthetic zinc sulfate additions."),
    ("mcq", "Seed Priming and Biofertilizer Inoculation",
     "When treating agricultural seeds with biofertilizer slurry (e.g. Rhizobium culture) prior to sowing, why is jaggery (gur) or gum arabic solution used as an adhesive?",
     "To provide a sticky sticking agent that adheres bacterial cells evenly to the seed coat while providing initial carbon nourishment during germination",
     ["To poison all surrounding birds so they do not eat seeds", "To color the seeds pink so they look attractive in markets", "To make seeds waterproof so they never absorb moisture"],
     "Jaggery solution acts as a natural sticking agent and energy source, ensuring high bacterial cell titers adhere to the seed coat until root germination begins."),
    ("seq", "Biofertilizer Quality Control Evaluation Protocol",
     "Arrange the laboratory quality control steps used to evaluate a commercial biofertilizer packet under the Fertilizer Control Order (FCO 1985):",
     ["Sampling of commercial packet from storage and recording temperature and expiry date", "Serial dilution of 1 gram carrier in sterile water blanks (from 10^-1 down to 10^-8)", "Pour plating on selective solid agar media (e.g., Yeast Extract Mannitol Agar / YEMA for Rhizobium)", "Incubation at 28 degrees Celsius, counting Colony Forming Units (CFU), and confirming minimum cell count (> 10^8 cells/g) with zero contamination"],
     "I -> II -> III -> IV",
     "Quality control under FCO: sampling, serial dilution, selective agar plating, and CFU colony counting to verify standard microbial density."),
    ("mcq", "Endophytic Nitrogen Fixation in Sugarcane",
     "Gluconacetobacter diazotrophicus is a unique nitrogen-fixing bacterium celebrated in sugarcane cultivation because it lives as an 'endophyte', meaning:",
     "It colonizes the interior intercellular vascular tissues and cavities of roots, stems, and leaves without causing any disease symptoms",
     ["It lives exclusively in desert sand dunes 10 miles away from the farm", "It lives inside the digestive tracts of predatory farm owls", "It grows exclusively on the plastic irrigation pipelines"],
     "Gluconacetobacter diazotrophicus thrives endophytically inside sugarcane vascular bundles, fixing significant nitrogen directly in sucrose-rich internal tissues."),
    ("mcq", "Soil Organic Carbon (SOC) Crisis in Indian Agriculture",
     "Decades of intensive chemical farming and burning of crop residues have caused Soil Organic Carbon (SOC) in many Indian soils to decline dangerously from 1.0% to below:",
     "0.3 to 0.5%",
     ["0.0001%", "5.0%", "10.0%"],
     "Continuous synthetic fertilizer use without organic recycling has halved SOC across vast arable belts, impairing soil water retention and microbial biofertilizer efficacy.")
]

# ==============================================================================
# Slot 30: Forestry Management, JFM & Social Forestry (FRA 2006, JFM 1990)
# ==============================================================================
s30_raw = [
    ("mcq", "National Forest Policy 1988 Forest Cover Target",
     "The National Forest Policy (NFP), 1988, stipulates that to achieve ecological stability, India must maintain what percentage of its total geographical area under forest and tree cover?",
     "A minimum of 33% nationally, with 67% in mountainous and hilly regions to prevent soil erosion and landslips",
     ["Exactly 10% nationally and 10% in hills", "100% of all land area, eliminating all cities", "50% in cities and 5% in forests"],
     "The 1988 National Forest Policy sets the national target of 33% total forest cover, with a higher goal of 67% in fragile mountainous regions."),
    ("stmt", "Forest Conservation Act 1980 Prior Approval Mandate",
     "The Forest (Conservation) Act, 1980 was enacted to check rampant indiscriminate deforestation across Indian states.",
     "Under Section 2 of the Act, no State Government can de-reserve any reserved forest or divert forest land for any non-forest purpose without prior approval of the Central Government.", 1,
     "Both Statement I and Statement II are correct. The FCA 1980 centralized forest clearance powers with MoEFCC, drastically reducing state-level forest diversion."),
    ("ar", "Joint Forest Management (JFM) Paradigm Shift",
     "The Joint Forest Management (JFM) resolution of June 1990 marked a historic paradigm shift in Indian forestry from colonial policing to participatory partnership.",
     "Under JFM, village communities (Forest Protection Committees) actively protect degraded forests in exchange for usufruct rights over non-timber forest produce (NTFP) and a share in timber revenue.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). JFM replaced adversarial state-community conflict with co-management, granting villagers usufruct benefits in return for forest regeneration."),
    ("match", "Historic Community Forestry Movements and Milestones",
     "Match the community forestry milestone in List I with its historical pioneer or location in List II:",
     [("A", "Arabari Experiment (1971)"),
      ("B", "Chipko Movement (1973)"),
      ("C", "Appiko Movement (1983)"),
      ("D", "Bishnoi Khejarli Sacrifice (1730)")],
     [("I", "Dr. A.K. Banerjee and local villagers reviving 1,272 hectares of degraded Sal forest in Midnapore, West Bengal"),
      ("II", "Gaura Devi, Sundarlal Bahuguna, and Chandi Prasad Bhatt hugging trees in Chamoli, Uttarakhand"),
      ("III", "Pandurang Hegde and villagers hugging trees against commercial logging in Western Ghats, Karnataka"),
      ("IV", "Amrita Devi Bishnoi and 363 martyrs sacrificing their lives for Khejri trees in Rajasthan")],
     "A-I, B-II, C-III, D-IV",
     "Arabari pioneered JFM, Chipko fought logging in Garhwal, Appiko mirrored Chipko in Karnataka's Western Ghats, and Bishnois gave history's ultimate sacrifice in 1730."),
    ("mcq", "Forest Rights Act 2006 (FRA) Historic Justice",
     "The Scheduled Tribes and Other Traditional Forest Dwellers (Recognition of Forest Rights) Act, 2006 (FRA) was enacted to undo the 'historical injustice' committed against forest dwellers by:",
     "Recognizing Individual Forest Rights (IFR) to cultivate forest lands, Community Forest Rights (CFR), and empowering the Gram Sabha to protect and manage community forest resources",
     ["Evicting all tribal communities from all forest areas in India within 30 days", "Transferring all forest lands to private multinational timber conglomerates", "Abolishing all Gram Panchayats across rural forested districts"],
     "FRA 2006 legally recognizes pre-existing rights of forest-dwelling Scheduled Tribes and traditional forest dwellers, making the Gram Sabha the supreme statutory authority over forest protection."),
    ("mcq", "Social Forestry Classification",
     "The National Commission on Agriculture (1976) classified 'Social Forestry' into which three distinct operational components?",
     "Farm Forestry, Community Forestry, and Extension (Strip) Forestry",
     ["Industrial Forestry, Military Forestry, and Space Forestry", "Urban Lawn Mowing, Golf Course Designing, and Indoor Bonsai Cultivation", "Commercial Timber Export, Paper Pulp Refining, and Sawmill Management"],
     "Social forestry brings trees outside traditional forests: Farm forestry (on individual farms), Community forestry (on village panchayat lands), and Extension forestry (along roads, canals, railways)."),
    ("stmt", "Agroforestry Systems Classification",
     "Agri-silviculture is an agroforestry system combining agricultural food crops with forestry trees on the same land management unit.",
     "Silvo-pastoral systems combine forestry trees with pasture grasses and livestock grazing.", 1,
     "Both Statement I and Statement II are correct. Agroforestry systems integrate woody perennials with crops (Agri-silviculture), animals (Silvo-pastoral), or both (Agri-silvo-pastoral)."),
    ("seq", "Process of Forest Rights Recognition under FRA 2006",
     "Arrange the statutory procedural steps for recognizing community forest rights under the Forest Rights Act, 2006:",
     ["The Gram Sabha convenes and elects the village Forest Rights Committee (FRC) to receive and verify claims", "The FRC conducts physical ground verification of traditional boundaries, prepares maps, and submits findings to the Gram Sabha", "The Gram Sabha deliberates, passes a formal resolution approving the rights, and forwards it to the Sub-Divisional Level Committee (SDLC)", "The District Level Committee (DLC) gives final statutory approval and issues formal land title deeds (patta) signed by the District Collector"],
     "I -> II -> III -> IV",
     "FRA process: Gram Sabha elects FRC, FRC maps claims, Gram Sabha passes resolution, and District Level Committee (DLC) issues final titles."),
    ("mcq", "Arabari Forest Experiment Significance",
     "Why is the 1971 Arabari experiment in West Bengal considered a legendary turning point in modern global forestry?",
     "Divisional Forest Officer Dr. A.K. Banerjee demonstrated that by promising villagers 25% share of Sal timber revenue and free fuelwood collection, severely degraded Sal forests regenerated into valuable timber worth crores within 10 years",
     ["It was the first site where commercial plastic trees were planted as a substitute for wood", "It demonstrated that clear-felling all forests increases regional rainfall by 1,000%", "It was a military test site for chemical defoliants"],
     "The Arabari model proved that community involvement backed by economic benefit-sharing revives degraded forests, serving as the blueprint for India's 1990 national JFM policy."),
    ("mcq", "Taungya System of Agroforestry History",
     "Originating in 19th-century colonial Burma under Dietrich Brandis, the 'Taungya system' is an agroforestry practice where:",
     "Agricultural food crops are cultivated simultaneously in the spaces between rows of planted commercial timber saplings (such as Teak) during the early establishment years",
     ["All forest trees are completely removed to cultivate floating hydroponic tomatoes", "Forest lands are paved with concrete tiles to collect clean rainwater", "Cattle are locked in underground caves to produce white milk"],
     "Under the Taungya system, shifting cultivators planted food crops between rows of young teak saplings; once the forest canopy closed, farmers moved to a new coupe."),
    ("ar", "Eucalyptus Monoculture Ecological Controversy",
     "The widespread planting of exotic Eucalyptus trees under early Social Forestry programs in India faced severe opposition from environmentalists.",
     "Eucalyptus has high transpiration rates that draw down shallow groundwater tables, provides zero edible fodder for village livestock, and produces leaf litter with allelopathic properties inhibiting ground vegetation.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). While fast-growing for pulpwood, Eucalyptus monocultures dried up local wells and suppressed native floral regeneration."),
    ("mcq", "CAMPA and Compensatory Afforestation Fund Act 2016",
     "What is the statutory purpose of the 'Compensatory Afforestation Fund Management and Planning Authority' (CAMPA) established under the 2016 Act?",
     "To manage and disburse thousands of crores of compensation funds deposited by infrastructure agencies diverting forest land, mandating afforestation on equivalent non-forest land",
     ["To privatize all reserved forests and sell them to real estate builders", "To deforest all national parks across Himalayan states", "To fund nuclear energy research projects in cities"],
     "CAMPA manages funds paid by developers when forest land is diverted, ensuring afforestation on non-forest land and funding wildlife conservation works."),
    ("match", "Forestry Terminology and Descriptions",
     "Match the forestry concept in List I with its description in List II:",
     [("A", "Silviculture"),
      ("B", "Coppicing"),
      ("C", "Afforestation"),
      ("D", "Reforestation")],
     [("I", "The art, science, and practice of establishing, cultivating, and managing forest stands sustainably"),
      ("II", "Woodland management method of repeatedly felling tree stems near ground level to stimulate multi-stem regrowth from stumps"),
      ("III", "Establishment of a forest by planting trees on land that historically has not contained forests"),
      ("IV", "Re-establishment of forest cover either naturally or artificially on land that was previously forested but cleared")],
     "A-I, B-II, C-III, D-IV",
     "Silviculture manages forest growth, coppicing regenerates trees from stumps, afforestation creates forests on new lands, and reforestation restores cleared forests."),
    ("mcq", "Minor Forest Produce (MFP) Economic Role",
     "Non-Timber Forest Produce (NTFP) / Minor Forest Produce (such as Tendu leaves, Mahua flowers, Sal seeds, Honey, and Lac) is crucial to tribal livelihoods because:",
     "It provides up to 50–70% of seasonal household income and nutrition for millions of indigenous tribal forest dwellers across Central India",
     ["It is processed exclusively into nuclear rocket propellants", "It eliminates the need for human beings to drink water", "It is traded only between foreign international governments"],
     "Minor Forest Produce represents the financial backbone of tribal economies; under FRA 2006, ownership of MFP is granted directly to forest-dwelling communities."),
    ("mcq", "Sacred Groves vs State Protected Areas",
     "A distinctive institutional feature of 'Sacred Groves' compared to Government National Parks is that:",
     "Sacred groves are protected through community-enforced traditional spiritual beliefs, rituals, and local taboos without any formal state forest department policing",
     ["Sacred groves are owned by private foreign multinational banks", "Sacred groves allow open clear-felling of all timber trees every month", "Sacred groves are artificial indoor greenhouse museums in cities"],
     "Sacred groves are self-governed by community faith and cultural taboos, serving as undisturbed biocultural heritage without state enforcement."),
    ("stmt", "India State of Forest Report (ISFR)",
     "The India State of Forest Report (ISFR) is published biennially (every two years) by the Forest Survey of India (FSI), Dehradun.",
     "The report uses satellite remote sensing (IRS LISS-III) to evaluate and map forest canopy density across Very Dense Forest (>70%), Moderately Dense Forest (40–70%), and Open Forest (10–40%).", 1,
     "Both Statement I and Statement II are correct. FSI's biennial report provides the official assessment of India's forest cover, mangrove cover, and growing stock."),
    ("mcq", "Miyawaki Method of Urban Afforestation",
     "Pioneered by Japanese botanist Akira Miyawaki, the 'Miyawaki Method' of urban forestry creates dense, multi-layered native mini-forests in cities by:",
     "Planting dozens of native tree species exceptionally densely (3–5 saplings per m2) in rich, aerated soil, accelerating forest succession 10 times faster than conventional plantations",
     ["Planting a single cloned hybrid poplar tree in a 50-acre concrete parking lot", "Using chemical hormones to make trees grow to 100 meters height in 2 days", "Importing plastic artificial trees and spraying them with pine scent"],
     "The Miyawaki method plants multi-tiered native species in close proximity, fostering rapid canopy closure and self-sustaining urban biodiversity micro-forests within 2–3 years."),
    ("seq", "Sequence of Operations in Forest Working Plan Preparation",
     "Arrange the formal procedural stages followed by a Forest Working Plan Officer to manage a forest division sustainably for a 10-year period:",
     ["Rigorous field enumeration, stock-mapping, and boundary verification of all forest compartments", "Calculating annual sustainable yield, increment growth rates, and prescribing annual harvesting coupes", "Formulating dedicated working circles (e.g. Protection circle, Selection working circle, Eco-restoration circle)", "Securing formal statutory approval from the Ministry of Environment, Forest and Climate Change before implementation"],
     "I -> II -> III -> IV",
     "Working plan preparation: compartment stock-mapping, sustainable yield calculation, working circle zoning, and MoEFCC statutory clearance."),
    ("mcq", "TRIFED and Van Dhan Vikas Yojana",
     "The Tribal Cooperative Marketing Development Federation of India (TRIFED) operationalizes the 'Van Dhan Vikas Yojana' to empower tribal forest gatherers by:",
     "Establishing tribal self-help group enterprises for on-site value addition, processing, packaging, and marketing of Minor Forest Produce, eliminating middlemen exploitation",
     ["Confining all tribal families permanently inside export processing factories", "Banning the collection of all forest leaves, honey, and seeds by villagers", "Selling forest lands to corporate timber brokers"],
     "Van Dhan scheme sets up tribal SHG clusters to process MFPs (e.g., bottling wild honey, processing Mahua jam, making Tendu leaf bundles), capturing retail profits for tribals."),
    ("mcq", "Ecological Succession: Primary vs Secondary Succession",
     "In forest ecology, how does 'Secondary Succession' (e.g. an abandoned farm field or burnt forest regenerating) differ fundamentally from 'Primary Succession'?",
     "Secondary succession occurs on sites where pre-existing soil and biological seed banks already exist, progressing much faster toward a climax community than primary succession on bare rock",
     ["Secondary succession requires 5 million years, while primary succession takes 2 days", "Secondary succession occurs only in outer space", "Secondary succession results in zero vegetation ever growing"],
     "Primary succession starts on bare sterile substrate without soil (lava, glaciated rock); secondary succession begins with intact soil sponges, proceeding rapidly to climax.")
]
'''

with open('scripts/subject_generators/make_evs_s26_30.py', 'w') as f:
    f.write(s26_to_30)

print("make_evs_s26_30.py written.")
