#!/usr/bin/env python3
"""
make_mmc_s36_40.py
Generates Slots 36 to 40 for Mass Media & Mass Communication (Code 318).
"""

import sys, os

content = '''# Mass Media & Mass Communication (Code 318) - Slots 36 to 40 (100 Questions)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from slot_helpers import mcq, stmt, ar, match, seq

SLOTS_36_40 = {}

# ==============================================================================
# SLOT 36: Public Relations Principles, Tools & Crisis Management
# ==============================================================================
SLOTS_36_40[36] = [
    mcq("Public Relations", "PR vs Advertising Distinction",
        "What is the fundamental distinction between Public Relations (PR) and Commercial Advertising?",
        "Advertising is paid promotional space with total message control by the sponsor; PR earns credibility through unpaid media coverage, editorial goodwill, and two-way relationship building",
        ["Advertising is always free of cost; PR costs millions of rupees per second",
         "Advertising is conducted solely by government police; PR is run by military generals",
         "Advertising uses only printed paper; PR uses only spoken telephone calls"],
        "PR focuses on earning organic editorial credibility and mutually beneficial stakeholder relationships, whereas advertising is paid media with controlled placement.",
        "Distinguishes Public Relations from Commercial Advertising."),
    mcq("Public Relations", "PR vs Propaganda",
        "How is ethical modern Public Relations distinguished from political 'Propaganda'?",
        "PR is grounded in verified factual truth, transparency, and two-way symmetrical communication; Propaganda relies on half-truths, manipulation, coercion, and concealment to enforce an agenda",
        ["PR is only practiced in winter; Propaganda is practiced in summer",
         "PR can only be communicated in German; Propaganda is in French",
         "PR requires painting billboards green; Propaganda uses blue ink"],
        "Propaganda manipulates and coerces using one-way deception; ethical PR relies on factual truth and two-way symmetrical dialogue.",
        "Differentiates ethical Public Relations from Propaganda."),
    stmt("Public Relations", "Press Release Anatomy",
        "A standard professional 'Press Release' is written in the Inverted Pyramid news style, complete with headline, dateline, attribution, and contact details for the media desk.",
        "A press release must always conceal the organization's name and telephone number so reporters cannot verify the information.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because press releases must prominently display media contact information to facilitate verification.",
        "Evaluates the structural components and professional standards of a press release."),
    ar("Public Relations", "Press Conference Rationale",
        "Organizations should call a formal 'Press Conference' only when announcing monumental, breaking news that justifies gathering busy journalists.",
        "Calling press conferences for trivial routine announcements damages institutional credibility and alienates beat journalists.",
        "both_correct_explain",
        "Journalists operate under tight deadlines; wasting their time on trivial announcements burns professional goodwill, explaining why conferences should be reserved for major news.",
        "Analyzes the strategic decision to convene a press conference."),
    match("Public Relations", "PR Tools",
        "Match the Public Relations tool in List-I with its primary operational purpose in List-II:",
        ["Press Release", "Press Kit / Media Kit", "House Journal / Internal Newsletter", "Crisis Communication Plan"],
        ["Written official factual announcement dispatched to news media editors", "Comprehensive information packet containing fact sheets, bios, and high-res photos for journalists", "Regular company periodical strengthening internal communication, employee morale, and culture", "Pre-established protocol and designated spokesperson team to navigate organizational emergencies"],
        "A-I, B-II, C-III, D-IV",
        "Press release = factual announcement; Media kit = background info packet; House journal = internal employee magazine; Crisis plan = emergency protocols.",
        "Matches PR communication tools to operational purposes."),
    mcq("Public Relations", "Ivy Lee & Declaration of Principles",
        "Which pioneer, regarded as the father of modern Public Relations alongside Edward Bernays, issued the famous 1906 'Declaration of Principles' pledging transparency and truth to the press?",
        "Ivy Ledbetter Lee",
        ["Rosser Reeves", "Claude Hopkins", "John Wanamaker"],
        "Ivy Lee pioneered ethical public relations, advising corporations to abandon secrecy and operate with open, factual transparency toward the press.",
        "Identifies Ivy Lee and his 1906 Declaration of Principles."),
    stmt("Public Relations", "Edward Bernays & Engineering of Consent",
        "Edward Bernays, nephew of Sigmund Freud, applied psychoanalytic and social psychological principles to pioneer the field of public relations.",
        "Bernays authored influential foundational texts including 'Crystallizing Public Opinion' (1923) and 'The Engineering of Consent'.",
        "both_true",
        "Both statements accurately describe Edward Bernays's psychological approach and landmark publications in public relations.",
        "Validates Edward Bernays's foundational role in public relations."),
    ar("Public Relations", "Golden Hour in Crisis Communication",
        "In organizational crisis management, the first hour ('The Golden Hour') following a disaster or scandal is critical.",
        "Failing to communicate quickly during the initial crisis window creates an information vacuum that is rapidly filled by destructive rumors, speculation, and panic.",
        "both_correct_explain",
        "Communicating transparently within the golden hour establishes command of narrative facts and prevents rumor mongering.",
        "Explains the strategic importance of the 'Golden Hour' in crisis communication."),
    seq("Public Relations", "Crisis Communication Workflow",
        "Arrange the stages of managing an organizational crisis through professional PR protocols:",
        ["Crisis breaks: convening emergency crisis response team and verifying ground facts", "Designating a single authorized spokesperson and halting conflicting internal statements", "Issuing rapid initial holding statement acknowledging the event and expressing human empathy", "Conducting regular media briefings with verified corrective measures and relief data", "Post-crisis evaluation, brand recovery audit, and policy rectifications"],
        "I -> II -> III -> IV -> V",
        "Crisis protocol: Convene team -> Designate spokesperson -> Holding statement -> Regular briefings -> Post-crisis evaluation.",
        "Sequences professional crisis communication protocol."),
    mcq("Public Relations", "Corporate Social Responsibility (CSR)",
        "Under Section 135 of the Indian Companies Act 2013, qualifying profitable corporations are legally mandated to spend at least what percentage of their average net profit on CSR activities?",
        "2%",
        ["10%", "25%", "0.1%"],
        "Section 135 of the Companies Act 2013 mandates that eligible companies spend at least 2% of their average net profits over the past three years on CSR.",
        "Recalls the statutory 2% CSR expenditure requirement under Indian law."),
    stmt("Public Relations", "Publicity vs Public Relations",
        "'Publicity' is the simple act of getting media attention, headlines, or mentions for a person or product, which can be positive or negative.",
        "'Public Relations' is the sustained, strategic management of all communication and relationships between an organization and its diverse publics.",
        "both_true",
        "Both statements correctly differentiate short-term transactional publicity from long-term strategic public relations.",
        "Distinguishes publicity from public relations."),
    ar("Public Relations", "Single Spokesperson Rule in Crisis",
        "During a corporate crisis, organizations must strictly route all public statements through a single designated spokesperson.",
        "Multiple, uncoordinated internal voices issuing contradictory statements destroy organizational credibility and inflame public panic.",
        "both_correct_explain",
        "Conflicting statements from different managers compound crisis confusion, necessitating a disciplined single point of authoritative communication.",
        "Analyzes the necessity of a single designated spokesperson in crisis management."),
    match("Public Relations", "PR Communication Models (Grunig & Hunt)",
        "Match James Grunig and Todd Hunt's PR model in List-I with its structural characteristic in List-II:",
        ["Press Agentry / Publicity Model", "Public Information Model", "Two-Way Asymmetrical Model", "Two-Way Symmetrical Model"],
        ["One-way communication seeking attention at all costs; truth is not essential (P.T. Barnum style)", "One-way dissemination of factual, truthful information (Ivy Lee government PR style)", "Two-way communication using feedback/research primarily to persuade audiences to change attitudes", "Two-way communication fostering mutual understanding, negotiation, and reciprocal adjustment"],
        "A-I, B-II, C-III, D-IV",
        "Press Agentry = attention/truth not essential; Public Info = one-way truthful facts; Two-Way Asymmetrical = research used to persuade; Two-Way Symmetrical = mutual understanding.",
        "Matches Grunig and Hunt's four models of Public Relations."),
    mcq("Public Relations", "Media Kit Contents",
        "Which of the following items is traditionally included inside a comprehensive 'Media Kit' distributed at a press conference?",
        "Main press release, company backgrounder, executive biographies, high-resolution photographs, and product fact sheet",
        ["A box of expired chocolates and used train tickets",
         "A blank sheet of paper and a mechanical wristwatch",
         "Personal credit cards belonging to company directors"],
        "A media kit packages essential background assets: press release, corporate profile, executive bios, and high-res imagery.",
        "Identifies standard contents of a media kit."),
    stmt("Public Relations", "Internal vs External Publics",
        "An organization's 'Internal Publics' include employees, managers, trade unions, and board members.",
        "An organization's 'External Publics' include consumers, media journalists, government regulators, suppliers, investors, and local community neighbors.",
        "both_true",
        "Both statements are true. Identifying and communicating with both internal and external publics is fundamental to PR stakeholder mapping.",
        "Differentiates internal from external organizational publics."),
    ar("Public Relations", "Johnson & Johnson Tylenol Crisis (1982)",
        "Johnson & Johnson's handling of the 1982 Chicago Tylenol cyanide poisoning crisis is universally cited as the gold standard of crisis communication.",
        "Johnson & Johnson prioritized public safety over short-term profits by immediately issuing a nationwide recall of 31 million bottles and introducing tamper-evident packaging.",
        "both_correct_explain",
        "Decisive, transparent action putting consumer safety first salvaged corporate trust, making the Tylenol response the benchmark of ethical crisis PR.",
        "Analyzes the benchmark Johnson & Johnson Tylenol crisis response."),
    mcq("Public Relations", "PR Lobbying Definition",
        "In public affairs and government relations, what is 'Lobbying'?",
        "The specialized practice of educating, informing, and persuading legislators, policymakers, and government regulators on behalf of a specific industry or civic cause",
        ["Bribing politicians with physical bags of cash at midnight",
         "Standing silently inside a hotel lobby for forty days",
         "Writing anonymous insulting letters to judges"],
        "Lobbying is the professional representation of client or public interest perspectives to government officials to influence legislative policy.",
        "Defines lobbying in government public affairs."),
    match("Public Relations", "Stakeholder Communication Channels",
        "Match the stakeholder group in List-I with its primary PR communication vehicle in List-II:",
        ["Shareholders / Financial Community", "Employees / Internal Staff", "News Media Journalists", "Local Community Neighbors"],
        ["Annual General Meeting (AGM) reports, balance sheet filings, and investor calls", "Intranet portal, employee town halls, and internal house journals", "Press releases, press conferences, and media backgrounders", "Open-house community visits, local civic sponsorships, and CSR camps"],
        "A-I, B-II, C-III, D-IV",
        "Shareholders = AGM/investor calls; Employees = intranet/town halls; Media = releases/conferences; Community = CSR/open house.",
        "Matches stakeholder groups to specialized PR channels."),
    seq("Public Relations", "Executing a Press Conference",
        "Arrange the operational timeline of organizing a successful corporate press conference:",
        ["Drafting press release and assembling comprehensive media kits", "Sending personalized press invitations with clear RSVP details to beat journalists", "Setting up briefing venue with branded stage backdrop, multi-mic podium, and audio mult-box", "Executive spokesperson delivers 10-minute briefing followed by open Q&A session", "Distributing press kits and following up with journalists for coverage tracking"],
        "I -> II -> III -> IV -> V",
        "Press conference sequence: Materials preparation -> Invitations -> Technical staging -> Briefing/Q&A -> Distribution/Tracking.",
        "Sequences the operational stages of organizing a press conference."),
    mcq("Public Relations", "Astroturfing in PR",
        "Why is 'Astroturfing' condemned by international public relations professional ethics associations (like PRSA and IPRA)?",
        "Because it deceives the public by manufacturing synthetic, fake citizen groups funded by covert corporate interests while pretending to be an authentic grassroots movement",
        ["Because it uses too much synthetic green paint on outdoor fences",
         "Because it forces all employees to play outdoor sports every Sunday",
         "Because it was outlawed by the International Postal Union in 1890"],
        "Astroturfing is deceptive stealth lobbying that fabricates false grassroots legitimacy, violating core principles of transparency and honesty.",
        "Condemns astroturfing in ethical public relations.")
]

# ==============================================================================
# SLOT 37: Characteristics of New Media & Digital Platforms
# ==============================================================================
SLOTS_36_40[37] = [
    mcq("New Media", "Digital Convergence",
        "What is 'Digital Convergence' in contemporary mass communication, popularized by scholars like Henry Jenkins?",
        "The blending, merging, and integration of previously distinct media technologies (print, audio, video, telecommunications) onto a single digital platform or device",
        ["The melting of computer cables when overheated",
         "The legal merger of two identical newspaper printing presses in one room",
         "The requirement that all movies must be printed on physical paper"],
        "Digital convergence breaks traditional medium boundaries, allowing smartphones and internet protocols to deliver text, audio, television, and gaming simultaneously.",
        "Defines digital convergence in media theory."),
    mcq("New Media", "Hypertextuality",
        "What defines the unique characteristic of 'Hypertextuality' in digital new media (pioneered by Ted Nelson and Tim Berners-Lee)?",
        "Non-linear information navigation where embedded clickable links (hyperlinks) allow users to jump instantly across diverse documents, websites, and databases",
        ["Reading printed books with magnifying glasses",
         "Typing messages using only uppercase capital letters",
         "Writing secret messages in invisible lemon juice ink"],
        "Hypertextuality replaces linear narrative reading with dynamic, multi-directional associative paths connected by clickable web hyperlinks.",
        "Defines hypertextuality in digital communication."),
    stmt("New Media", "Interactivity in New Media",
        "In traditional legacy media (print, radio, television), the communication flow is predominantly one-way transmission with delayed feedback.",
        "In digital new media, 'Interactivity' empowers users to actively respond, modify, curate, comment, and co-create content in real-time.",
        "both_true",
        "Both statements correctly contrast legacy one-way broadcasting with the multidirectional interactivity of new media.",
        "Contrasts legacy media one-way flow with new media interactivity."),
    ar("New Media", "Prosumer Phenomenon",
        "Futurist Alvin Toffler coined the term 'Prosumer' to describe the blurred boundary between media producers and media consumers.",
        "On Web 2.0 and social media platforms, ordinary internet users simultaneously consume media while generating and uploading their own content.",
        "both_correct_explain",
        "Because digital users actively produce content (blogs, videos, memes) while consuming peer content, they function simultaneously as producer-consumers (prosumers).",
        "Explains Alvin Toffler's concept of the 'Prosumer' in digital culture."),
    match("New Media", "New Media Characteristics (Lievrouw & Livingstone)",
        "Match the digital media attribute in List-I with its technological hallmark in List-II:",
        ["Interactivity", "Multimediality", "Hypertextuality", "Asynchronicity"],
        ["Two-way responsive dialogue between user and digital interface", "Seamless integration of text, photography, sound, animation, and video", "Networked non-linear nodes of information connected by hyperlinks", "Content accessed, shared, and consumed at times chosen by user rather than live schedule"],
        "A-I, B-II, C-III, D-IV",
        "Interactivity = responsive user dialogue; Multimediality = integrated sensory media; Hypertextuality = hyperlinked nodes; Asynchronicity = time-shifted on-demand access.",
        "Matches defining characteristics of digital new media to technological hallmarks."),
    mcq("New Media", "Web 1.0 vs Web 2.0",
        "How is the architectural shift from 'Web 1.0' to 'Web 2.0' (coined by Tim O'Reilly) fundamentally characterized?",
        "Web 1.0 was a 'read-only' static web of published brochure pages; Web 2.0 is a 'read-write' participatory web driven by user-generated content and social networks",
        ["Web 1.0 used fiber-optic lasers; Web 2.0 uses copper telegraph wires",
         "Web 1.0 was operated exclusively on smartphones; Web 2.0 is on mechanical typewriters",
         "Web 1.0 was owned entirely by Google; Web 2.0 is owned by Wikipedia"],
        "Web 2.0 revolutionized the internet by transforming passive readers into active creators through blogs, social networks, and collaborative wikis.",
        "Contrasts the architecture of Web 1.0 with Web 2.0."),
    stmt("New Media", "The Long Tail (Chris Anderson)",
        "Chris Anderson's 'The Long Tail' theory demonstrates that internet platforms make significant collective profits by selling small volumes of hard-to-find niche items.",
        "Physical retail stores easily beat internet platforms because physical shelf space inside malls is completely infinite and costs zero rupees.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because physical shelf space is expensive and finite, whereas digital storage allows infinite niche inventory.",
        "Evaluates Chris Anderson's Long Tail economic theory of digital media."),
    ar("New Media", "Echo Chambers & Filter Bubbles",
        "Algorithmic personalization on social media platforms can trap users inside 'Echo Chambers' and 'Filter Bubbles' (Eli Pariser).",
        "Recommendation algorithms prioritize content that confirms a user's pre-existing political prejudices to maximize user engagement and ad clicks.",
        "both_correct_explain",
        "Optimizing for engagement leads algorithms to feed ideologically agreeable content, isolating users from dissenting perspectives inside filter bubbles.",
        "Analyzes the formation of algorithmic filter bubbles and echo chambers."),
    seq("New Media", "Digital Social Media Evolution",
        "Arrange the emergence of major digital social platforms in historical order:",
        ["SixDegrees.com launches as first modern social networking site (1997)", "Friendster and MySpace pioneer social networking booms (2002-2003)", "Facebook launches across university campuses (2004)", "YouTube revolutionizes user-generated video sharing (2005)", "TikTok pioneers short-form algorithmic vertical video feeds (late 2010s)"],
        "I -> II -> III -> IV -> V",
        "Social media evolution: SixDegrees (1997) -> Friendster/MySpace -> Facebook (2004) -> YouTube (2005) -> TikTok (late 2010s).",
        "Sequences the historical rise of digital social media platforms."),
    mcq("New Media", "Citizen Journalism via Social Media",
        "How has social media fundamentally disrupted traditional newsroom gatekeeping during breaking emergencies (like the 2008 Mumbai attacks or Arab Spring)?",
        "By enabling eyewitness citizens on the ground to broadcast live video, tweets, and photos instantly to a global audience hours before legacy TV crews arrive",
        ["By forcing all television cameras to be permanently dismantled",
         "By requiring every citizen to pass a physical marathon race",
         "By shutting down all electrical internet servers during wars"],
        "Social media democratizes news distribution, empowering citizen witnesses to bypass institutional newsrooms during breaking crises.",
        "Analyzes social media disruption of newsroom gatekeeping during crises."),
    stmt("New Media", "Digital Divide",
        "The 'Digital Divide' refers to the socioeconomic inequalities in access to digital information technologies, high-speed broadband, and digital literacy.",
        "In India, the digital divide reflects disparities across urban vs rural geographies, gender lines, and economic income classes.",
        "both_true",
        "Both statements correctly describe the structural and demographic manifestations of the digital divide in India.",
        "Validates the multifaceted nature of the digital divide in India."),
    ar("New Media", "Virality and Memetics",
        "Internet 'Memes' replicate and diffuse across digital social networks with astonishing speed.",
        "Memes are culturally malleable, humorous, and modular, allowing online communities to continuously remix, personalize, and recirculate them.",
        "both_correct_explain",
        "The modular, participatory nature of memes enables rapid peer-to-peer reinterpretation and exponential algorithmic virality.",
        "Explains the communicative mechanics of internet memes and virality."),
    match("New Media", "Digital Theories & Scholars",
        "Match the digital media theorist in List-I with their signature conceptual framework in List-II:",
        ["Henry Jenkins", "Eli Pariser", "Chris Anderson", "Tim O'Reilly"],
        ["Convergence Culture and Participatory Culture", "The Filter Bubble and algorithmic personalization isolation", "The Long Tail: Why the Future of Business is Selling Less of More", "Web 2.0: Harnessing collective intelligence and open architecture"],
        "A-I, B-II, C-III, D-IV",
        "Jenkins = Convergence/Participatory culture; Pariser = Filter Bubble; Anderson = Long Tail; O'Reilly = Web 2.0.",
        "Matches digital media scholars to their signature conceptual frameworks."),
    mcq("New Media", "Net Neutrality Principle",
        "What is the foundational principle of 'Net Neutrality' in telecommunications and internet regulation?",
        "Internet Service Providers (ISPs) must treat all internet data traffic equally, without blocking, throttling, or creating discriminatory paid fast lanes for favored websites",
        ["A law mandating that all computer screens must be painted neutral gray",
         "The requirement that internet users must never express political opinions",
         "A rule forcing all websites to charge identical prices"],
        "Net neutrality protects an open, egalitarian internet by forbidding ISPs from discriminating, slowing down, or speeding up traffic based on commercial deals.",
        "Defines the principle of Net Neutrality."),
    stmt("New Media", "TRAI on Net Neutrality (2016)",
        "In February 2016, the Telecom Regulatory Authority of India (TRAI) issued landmark regulations prohibiting discriminatory tariffs for data services based on content.",
        "This TRAI ruling effectively prohibited Facebook's 'Free Basics' and Airtel Zero in India, upholding net neutrality.",
        "both_true",
        "Both statements are true. TRAI's 2016 decision barred zero-rating and discriminatory pricing, championing net neutrality in India.",
        "Highlights TRAI's landmark 2016 Net Neutrality ruling."),
    ar("New Media", "Surveillance Capitalism",
        "Shoshana Zuboff coined the term 'Surveillance Capitalism' to critique the business models of modern digital tech monopolies (like Google and Meta).",
        "Digital platforms harvest human behavioral data exhaust, transforming personal experiences into proprietary behavioral prediction products sold to advertisers.",
        "both_correct_explain",
        "Harvesting user behavior to manufacture and monetize predictive behavioral models forms the core engine of surveillance capitalism.",
        "Analyzes Shoshana Zuboff's concept of Surveillance Capitalism."),
    mcq("New Media", "Gamification in Digital Apps",
        "In digital media and user interface design, what is 'Gamification'?",
        "The application of game-design mechanics (points, badges, leaderboards, streaks) to non-game environments (news apps, fitness, education) to boost user engagement",
        ["Playing arcade video games during working office hours",
         "A computer virus that deletes chess applications",
         "The manufacturing of plastic dice for children"],
        "Gamification leverages intrinsic psychological drives (competition, achievement, streaks) to maximize engagement and daily retention on digital platforms.",
        "Defines gamification in digital platforms."),
    match("New Media", "Emerging Tech Concepts",
        "Match the emerging digital technology in List-I with its communication utility in List-II:",
        ["Virtual Reality (VR)", "Augmented Reality (AR)", "Artificial Intelligence (AI) Chatbots", "Podcast RSS"],
        ["Immersive 360-degree simulated visual and sensory environment shutting out physical world", "Overlays digital computer graphics, text, and 3D assets onto the live physical camera view", "Natural language processing models conducting dynamic conversational dialogues with users", "Open XML syndication protocol automating audio episode delivery to subscriber apps"],
        "A-I, B-II, C-III, D-IV",
        "VR = 360 immersive simulation; AR = digital graphics overlay on real world; AI chatbots = conversational NLP; RSS = automated audio syndication.",
        "Matches emerging digital media technologies to functional traits."),
    seq("New Media", "Digital Information Literacy Verification Flow",
        "Arrange the critical steps an educated digital citizen should take before sharing a viral sensational online post:",
        ["Pause upon encountering an emotionally provocative, shocking digital headline", "Inspect author byline, URL domain integrity, and publication date", "Perform reverse image search to verify if accompanying photograph is recycled or misattributed", "Cross-check facts on independent professional fact-checking portals (e.g. AltNews, BoomLive)", "Decide whether to debunk, ignore, or share only verified factual context"],
        "I -> II -> III -> IV -> V",
        "Digital verification steps: Pause/Emotional awareness -> Source/Date check -> Reverse image trace -> Fact-checker cross-check -> Responsible sharing.",
        "Sequences digital media literacy fact-checking steps."),
    mcq("New Media", "Information Overload / Infobesity",
        "What psychological state does the concept of 'Information Overload' (or Infobesity) describe in the 24/7 digital smartphone era?",
        "Cognitive fatigue, anxiety, and decision paralysis caused by being inundated with vastly more data, notifications, and breaking alerts than the human mind can process",
        ["A physical illness caused by eating computer circuit boards",
         "The financial cost of buying multiple internet modems",
         "The weight of physical encyclopedias in a library"],
        "Information overload occurs when sensory input from relentless digital streams exceeds human cognitive processing capacity, causing fatigue and anxiety.",
        "Defines information overload in the digital age.")
]

# ==============================================================================
# SLOT 38: Constitutional Foundations & Media Freedom (Article 19(1)(a) & 19(2))
# ==============================================================================
SLOTS_36_40[38] = [
    mcq("Media Law", "Article 19(1)(a) Constitutional Guarantee",
        "Under the Constitution of India, freedom of the press is not explicitly enumerated as a separate fundamental right, but is legally derived from:",
        "Article 19(1)(a) — Freedom of Speech and Expression",
        ["Article 21 — Right to Life and Personal Liberty",
         "Article 14 — Right to Equality before Law",
         "Article 32 — Right to Constitutional Remedies"],
        "The Supreme Court of India (Romesh Thappar case, Indian Express case) established that press freedom is an inherent part of Article 19(1)(a).",
        "Recalls Article 19(1)(a) as the constitutional home of press freedom in India."),
    mcq("Media Law", "Article 19(2) Reasonable Restrictions",
        "Article 19(2) of the Indian Constitution empowers the state to enact 'reasonable restrictions' on freedom of speech on how many enumerated constitutional grounds?",
        "Eight specific grounds (Sovereignty & integrity of India, Security of the State, Friendly relations with foreign States, Public order, Decency or morality, Contempt of court, Defamation, Incitement to an offence)",
        ["Two grounds (Weather conditions and Highway traffic)",
         "Zero grounds (Freedom of speech in India is completely absolute without any limits)",
         "Fifty grounds decided daily by municipal police chiefs"],
        "Article 19(2) contains an exhaustive list of eight specific grounds under which the legislature may enact reasonable speech restrictions.",
        "Identifies the eight grounds of reasonable restrictions under Article 19(2)."),
    stmt("Media Law", "First Constitutional Amendment (1951)",
        "The First Amendment to the Constitution of India (1951) amended Article 19(2) to introduce the grounds of 'Public Order', 'Friendly relations with foreign States', and 'Incitement to an offence'.",
        "The First Amendment also inserted the word 'reasonable' before 'restrictions', making government speech curbs subject to judicial review by the courts.",
        "both_true",
        "Both statements are true. The 1951 amendment added three grounds and the word 'reasonable', empowering the judiciary to test proportionality.",
        "Evaluates the historic First Constitutional Amendment 1951 on Article 19(2)."),
    ar("Media Law", "Romesh Thappar v. State of Madras (1950)",
        "In Romesh Thappar v. State of Madras (1950), the Supreme Court struck down the Madras government's ban on the circulation of the weekly journal 'Cross Roads'.",
        "The Supreme Court held that freedom of speech and expression includes the freedom of circulation, as publication without circulation is of no value.",
        "both_correct_explain",
        "Justice Patanjali Sastri established that circulation is an inseparable organ of speech freedom, striking down the ban as unconstitutional.",
        "Analyzes the landmark Romesh Thappar ruling establishing freedom of circulation."),
    match("Media Law", "Landmark Supreme Court Cases",
        "Match the landmark constitutional speech case in List-I with its foundational legal ruling in List-II:",
        ["Romesh Thappar v. State of Madras (1950)", "Brij Bhushan v. State of Delhi (1950)", "Sakal Papers v. Union of India (1962)", "Bennett Coleman v. Union of India (1973)"],
        ["Struck down entry ban on journal; established freedom of circulation as part of 19(1)(a)", "Struck down pre-censorship on 'Organiser'; held pre-censorship of a newspaper violates 19(1)(a)", "Struck down Daily Newspapers (Price and Page) Order; government cannot restrict newspaper pages to curb competition", "Struck down newsprint quota policy capping page limits at 10 pages; held newsprint rationing cannot control editorial size"],
        "A-I, B-II, C-III, D-IV",
        "Romesh Thappar = circulation; Brij Bhushan = pre-censorship unconstitutional; Sakal Papers = price-page struck down; Bennett Coleman = newsprint quota page cap struck down.",
        "Matches landmark Indian press freedom rulings to their legal precedents."),
    mcq("Media Law", "Pre-Censorship on the Press",
        "In Brij Bhushan v. State of Delhi (1950), what did the Supreme Court rule regarding government pre-censorship of newspapers during peacetime?",
        "Pre-censorship on a newspaper is an unconstitutional violation of Article 19(1)(a) unless justified strictly under valid emergency or public order grounds",
        ["Pre-censorship is mandatory for every morning newspaper",
         "The government must write all news headlines personally",
         "Newspapers can only publish articles approved by foreign embassies"],
        "The Supreme Court ruled that imposing pre-censorship on a newspaper is an abhorrent restraint striking at the heart of free speech under Article 19(1)(a).",
        "Understands the constitutional ban on peacetime pre-censorship in India."),
    stmt("Media Law", "Absolute vs Qualified Right",
        "Freedom of speech and expression in India under Article 19(1)(a) is an absolute, unconditional right that cannot be restricted under any circumstances.",
        "In the United States, the First Amendment states that 'Congress shall make no law... abridging the freedom of speech, or of the press'.",
        "s1_true_s2_false",
        "Statement 1 is false because Indian speech rights are qualified by reasonable restrictions in Article 19(2). Statement 2 is true regarding the US First Amendment.",
        "Contrasts Indian qualified free speech with the US First Amendment text."),
    ar("Media Law", "Sakal Papers Ruling on Economic Regulations",
        "In Sakal Papers (1962), the Supreme Court ruled that the state cannot curb the volume of circulation or pages of a newspaper under the guise of regulating commercial business.",
        "Freedom of speech cannot be restricted for a purpose not permitted under Article 19(2), such as protecting small newspapers from economic competition.",
        "both_correct_explain",
        "Because economic fairness is not an enumerated ground in Article 19(2), the state cannot suppress newspaper pages to curb price competition.",
        "Explains why economic regulation cannot bypass Article 19(2) restrictions."),
    seq("Media Law", "Constitutional Speech Precedents",
        "Arrange these landmark Supreme Court press freedom decisions in chronological sequence:",
        ["Romesh Thappar v. State of Madras (freedom of circulation, 1950)", "Sakal Papers v. Union of India (price-page schedule, 1962)", "Bennett Coleman v. Union of India (newsprint quota policy, 1973)", "Indian Express Newspapers v. Union of India (import duty on newsprint, 1985)", "Shreya Singhal v. Union of India (striking down Section 66A IT Act, 2015)"],
        "I -> II -> III -> IV -> V",
        "Chronology: Romesh Thappar (1950) -> Sakal Papers (1962) -> Bennett Coleman (1973) -> Indian Express (1985) -> Shreya Singhal (2015).",
        "Sequences landmark constitutional press freedom cases in India."),
    mcq("Media Law", "Shreya Singhal v. Union of India (2015)",
        "Why did the Supreme Court strike down Section 66A of the Information Technology Act in the landmark Shreya Singhal (2015) case?",
        "Because Section 66A was unconstitutionally vague, overbroad, and created a chilling effect on online speech by criminalizing 'annoying' or 'offensive' digital messages",
        ["Because the internet was declared illegal across India",
         "Because Section 66A forced citizens to buy expensive laptops",
         "Because police officers refused to read computer screens"],
        "The Supreme Court invalidated Section 66A because vague terms like 'annoying' or 'grossly offensive' violated Article 19(1)(a) and failed the test of 19(2).",
        "Recalls the constitutional invalidation of Section 66A IT Act in Shreya Singhal."),
    stmt("Media Law", "Test of Proportionality",
        "To qualify as a 'reasonable restriction' under Article 19(2), a law must satisfy the judicial 'Test of Proportionality'.",
        "The test requires that the restriction must pursue a legitimate state aim, be rationally connected to that aim, use the least intrusive means, and maintain balance between public interest and fundamental rights.",
        "both_true",
        "Both statements correctly articulate the modern constitutional doctrine of proportionality governing fundamental rights.",
        "Explains the constitutional test of proportionality on speech restrictions."),
    ar("Media Law", "Chilling Effect Doctrine",
        "Vague, overbroad penal laws restricting speech are routinely struck down by constitutional courts under the 'Chilling Effect' doctrine.",
        "When laws are ambiguous, citizens self-censor legitimate, lawful expression out of fear of arbitrary arrest and harassment by police authorities.",
        "both_correct_explain",
        "Vague statutory language deters lawful dissent, chilling free public discourse and rendering the law unconstitutional.",
        "Analyzes the Chilling Effect doctrine in constitutional jurisprudence."),
    match("Media Law", "Article 19(2) Grounds and Scenarios",
        "Match the Article 19(2) ground in List-I with its legal scenario in List-II:",
        ["Public Order", "Defamation", "Contempt of Court", "Decency or Morality"],
        ["Suppressing incendiary communal hate speech inciting riots between religious groups", "Civil damages suit filed against an editor for publishing fabricated accusations of embezzlement", "Punishing a media network for launching a malicious campaign attacking the personal integrity of a judge", "Banning sexually explicit pornographic literature displayed openly on streets"],
        "A-I, B-II, C-III, D-IV",
        "Public order = riots/communal hate; Defamation = false embezzlement claim; Contempt = attacks on judge integrity; Decency = explicit pornography.",
        "Matches Article 19(2) restriction grounds to realistic legal situations."),
    mcq("Media Law", "Right to Information as Fundamental Right",
        "In which landmark cases (such as State of UP v. Raj Narain, 1975) did the Supreme Court establish that the 'Right to Information' is an integral part of Article 19(1)(a)?",
        "State of Uttar Pradesh v. Raj Narain (1975) and S. P. Gupta v. Union of India (1981)",
        ["A. K. Gopalan v. State of Madras (1950)",
         "Champakam Dorairajan v. State of Madras (1951)",
         "Berubari Union Case (1960)"],
        "Justice K. K. Mathew famously held that in a democracy where citizens are masters, they have a right to know every public act done by public servants under Article 19(1)(a).",
        "Identifies Raj Narain (1975) as establishing Right to Information as a fundamental right."),
    stmt("Media Law", "Commercial Speech Protection",
        "In Tata Press Ltd v. MTNL (1995), the Supreme Court ruled that commercial speech (advertising) is protected under Article 19(1)(a).",
        "The Supreme Court held that consumers have a fundamental right to receive economic information regarding product availability and prices in a free economy.",
        "both_true",
        "Both statements are historically accurate: the Tata Press ruling extended Article 19(1)(a) protection to commercial advertising.",
        "Evaluates the constitutional status of commercial speech under Tata Press (1995)."),
    ar("Media Law", "Prior Restraint on Publication (Injunctions)",
        "Indian courts follow the classic common law 'Bonnard v. Perryman' rule regarding gag orders and prior restraint against the press in defamation claims.",
        "Courts refuse to grant pre-publication ex-parte gag orders if the defendant journalist asserts they have evidence to prove justification and truth at trial.",
        "both_correct_explain",
        "Prior restraint is heavily disfavored; courts allow publication if the reporter pleads truth, resolving damages post-publication rather than gagging the press.",
        "Analyzes judicial restraint regarding pre-publication injunctions."),
    mcq("Media Law", "Seditions Law (Section 124A IPC) Scrutiny",
        "In Kedar Nath Singh v. State of Bihar (1962), how did the Supreme Court narrow the interpretation of the colonial sedition law (Section 124A IPC) to save it from unconstitutionality?",
        "It held that severe criticism of the government does not constitute sedition unless it actively incites violence or creates public disorder",
        ["It made sedition punishable exclusively with a one-rupee postal stamp",
         "It allowed police officers to arrest any journalist who misspelled the word 'democracy'",
         "It declared that all journalists must sign an oath of loyalty to the ruling political party"],
        "Kedar Nath Singh restricted sedition strictly to acts involving intention or tendency to create disorder or incite violence, protecting non-violent criticism.",
        "Recalls the constitutional narrowing of sedition in Kedar Nath Singh (1962)."),
    match("Media Law", "Speech Concepts",
        "Match the legal speech concept in List-I with its constitutional definition in List-II:",
        ["Commercial Speech", "Chilling Effect", "Clear and Present Danger / Spark in Powder Keg", "Prior Restraint"],
        ["Communication made on behalf of business or commerce; protected under Tata Press", "The inhibition or discouragement of legitimate speech caused by fear of severe legal penalties", "The legal test requiring an immediate, proximate, direct link between speech and imminent violence", "Government censorship prohibiting speech or publication before it actually occurs"],
        "A-I, B-II, C-III, D-IV",
        "Commercial speech = business communication; Chilling effect = fear of penalty stopping speech; Clear and present danger = proximate violence link; Prior restraint = pre-publication censorship.",
        "Matches core freedom of speech concepts to definitions."),
    seq("Media Law", "Proportionality Analysis Steps",
        "Arrange the four analytical stages of the constitutional 'Test of Proportionality' (Modern Dental College / Puttaswamy):",
        ["Legitimate State Goal: Is the measure designed to achieve a legitimate public purpose?", "Suitability / Rational Connection: Is there a rational connection between the restriction and the goal?", "Necessity / Least Restrictive Means: Is there a less intrusive alternative available to achieve the same result?", "Balancing / Strict Proportionality: Does the public benefit outweigh the impact on fundamental rights?"],
        "I -> II -> III -> IV",
        "Proportionality stages: Legitimate goal -> Rational connection -> Necessity/Least restrictive -> Balancing/Proportionality stricto sensu.",
        "Sequences the four-pronged test of constitutional proportionality."),
    mcq("Media Law", "Media Immunity during Emergency",
        "During the National Emergency (1975-1977) in India, what happened to the fundamental rights under Article 19 and freedom of the press?",
        "Article 19 was suspended under Presidential order, and stringent statutory pre-censorship was imposed on all newspapers, leading to blank editorial columns in protest",
        ["Newspapers were ordered to double their printing size to one hundred pages",
         "Television broadcasts were transmitted exclusively in color for the first time",
         "All foreign journalists were granted automatic citizenship"],
        "During the Emergency, Article 19 was suspended, and Chief Censors vetted every daily news dispatch, prompting iconic blank edit spaces in papers like The Indian Express.",
        "Recalls the suspension of press freedom and pre-censorship during the 1975-77 Emergency.")
]

# ==============================================================================
# SLOT 39: Key Media Statutes & Regulations (Defamation, Contempt, Official Secrets, RTI, Copyright, IT Act)
# ==============================================================================
SLOTS_36_40[39] = [
    mcq("Media Statutes", "Civil vs Criminal Defamation",
        "In Indian jurisprudence, what is the fundamental difference between Civil Defamation and Criminal Defamation?",
        "Civil defamation is an uncodified tort adjudicated in civil courts seeking monetary damages; Criminal defamation is codified under Sections 499 & 500 IPC punishing offenders with up to 2 years imprisonment",
        ["Civil defamation is punished by hanging; Criminal defamation requires a five-rupee fine",
         "Civil defamation is tried exclusively by municipal police; Criminal defamation is tried by doctors",
         "Civil defamation applies only to books; Criminal defamation applies only to radio"],
        "Civil defamation seeks financial compensation for loss of reputation under tort law; criminal defamation under IPC 499/500 imposes fine and/or imprisonment.",
        "Differentiates civil defamation from criminal defamation under Indian law."),
    mcq("Media Statutes", "Defamation Exceptions under IPC 499",
        "Under Section 499 of the Indian Penal Code, which of the following is the First Exception protecting journalists against defamation charges?",
        "Truth imputed for the public good (imputation of truth which public good requires to be made)",
        ["The excuse that the journalist was feeling tired when writing",
         "The claim that the printing ink was of low commercial quality",
         "The assertion that the editor is younger than twenty years of age"],
        "The First Exception to Section 499 protects any truthful statement, provided its publication was made or intended for the public good.",
        "Identifies the Truth for Public Good exception under Section 499 IPC."),
    stmt("Media Statutes", "Contempt of Courts Act 1971",
        "Civil Contempt involves willful disobedience to any judgment, decree, direction, or order of a court.",
        "Criminal Contempt involves publishing any matter that scandalizes the court, prejudices judicial proceedings, or interferes with the administration of justice.",
        "both_true",
        "Both statements accurately define Civil Contempt and Criminal Contempt under Section 2 of the Contempt of Courts Act, 1971.",
        "Distinguishes civil contempt from criminal contempt under the 1971 Act."),
    ar("Media Statutes", "Truth as Defence in Contempt (2006 Amendment)",
        "The Contempt of Courts (Amendment) Act 2006 introduced 'Truth' as a valid statutory defense in contempt proceedings.",
        "The court must be satisfied that the defense of truth was raised in the public interest and the request for invoking the defense was bona fide.",
        "both_correct_explain",
        "The 2006 amendment allowed journalists to plead truth as a defense against contempt, provided it serves bona fide public interest.",
        "Analyzes truth as a defense under the Contempt of Courts (Amendment) Act 2006."),
    match("Media Statutes", "Key Indian Media Acts",
        "Match the media statute in List-I with its primary legal realm in List-II:",
        ["Official Secrets Act, 1923", "Copyright Act, 1957", "Right to Information (RTI) Act, 2005", "Information Technology Act, 2000"],
        ["Espionage, state secrecy, and penalizing unauthorized access to classified defense zones", "Protecting literary, dramatic, musical, artistic, and cinematographic intellectual property", "Mandating transparent government disclosures and citizen access to public administrative records", "Cybercrimes, electronic contracts, digital signatures, and intermediary liabilities"],
        "A-I, B-II, C-III, D-IV",
        "Official Secrets = defense espionage/secrecy; Copyright = intellectual property; RTI = access to government records; IT Act = cyber regulations.",
        "Matches landmark Indian media statutes to their functional domains."),
    mcq("Media Statutes", "Right to Information (RTI) Timeline",
        "Under Section 7(1) of the Right to Information Act 2005, within how many days must a Public Information Officer (PIO) normally provide requested information to a citizen?",
        "Within 30 days (reduced to 48 hours if the information concerns the life or liberty of a person)",
        ["Within 365 days", "Within 10 years", "Immediately within five minutes"],
        "The standard statutory timeline is 30 days, expedited to 48 hours when life or liberty is at stake.",
        "Recalls the statutory timelines for information delivery under the RTI Act 2005."),
    stmt("Media Statutes", "Section 8 Exemptions under RTI",
        "Section 8 of the RTI Act 2005 outlines specific exemptions where public authorities are not obligated to disclose information (e.g. national security, cabinet papers, trade secrets).",
        "Under Section 8(2), information can still be disclosed if public interest in disclosure outweighs the harm to protected interests.",
        "both_true",
        "Both statements are true. Section 8 lists exemptions, but Section 8(2) introduces the paramount Public Interest override.",
        "Evaluates Section 8 exemptions and public interest overrides under the RTI Act."),
    ar("Media Statutes", "Copyright Fair Dealing (Section 52)",
        "Under Section 52 of the Indian Copyright Act 1957, journalists may reproduce excerpts of copyrighted works for reporting current events without infringing copyright.",
        "The legal doctrine of 'Fair Dealing' protects the legitimate use of copyrighted excerpts for news reporting, review, criticism, and academic scholarship.",
        "both_correct_explain",
        "Fair dealing provides statutory immunity for news reporting and criticism, preventing copyright from obstructing public information.",
        "Explains the Fair Dealing doctrine under Section 52 of the Copyright Act 1957."),
    seq("Media Statutes", "RTI Appeal Redressal Hierarchy",
        "Arrange the stages of appealing a denied RTI application in statutory sequence:",
        ["Citizen files formal RTI application with Public Information Officer (PIO)", "PIO rejects request or fails to respond within 30-day statutory deadline", "Citizen files First Appeal before the designated First Appellate Authority (FAA) within the public authority", "FAA upholds rejection or fails to decide within 30-45 days", "Citizen files Second Appeal before the independent Central/State Information Commission (CIC/SIC)"],
        "I -> II -> III -> IV -> V",
        "RTI appeals ladder: PIO application -> PIO rejection -> First Appeal (FAA) -> FAA failure -> Second Appeal (CIC/SIC).",
        "Sequences the appellate hierarchy under the RTI Act 2005."),
    mcq("Media Statutes", "Copyright Duration in India",
        "What is the statutory duration of copyright protection for literary, dramatic, and musical works under the Indian Copyright Act 1957?",
        "The lifetime of the author plus 60 years following the calendar year of the author's death",
        ["Exactly 5 years from publication",
         "1,000 years from creation",
         "Until the author reaches 50 years of age"],
        "Indian copyright law grants protection for the author's life plus 60 years post-mortem, after which the work enters the public domain.",
        "Recalls the statutory duration of copyright for literary works in India."),
    stmt("Media Statutes", "Intermediary Liability (Section 79 IT Act)",
        "Section 79 of the Information Technology Act 2000 provides 'Safe Harbor' protection to online intermediaries (like social media platforms and ISPs).",
        "An intermediary loses its safe harbor protection if it fails to exercise due diligence or fails to remove unlawful content upon receiving a court order or government takedown notice.",
        "both_true",
        "Both statements correctly reflect the conditional safe harbor mechanism established under Section 79 of the IT Act.",
        "Validates Section 79 Safe Harbor provisions under the IT Act 2000."),
    ar("Media Statutes", "Whistleblower Protection Challenges",
        "Investigative journalists often face immense legal pressure under the Official Secrets Act (OSA) 1923 when reporting on administrative corruption.",
        "The colonial-era OSA 1923 contains sweeping, broad definitions of 'secret documents' and lacks an explicit public interest whistleblower defense clause.",
        "both_correct_explain",
        "Because the 1923 OSA criminalizes possession of any unclassified official paper without a public interest defense, it can be weaponized against whistleblowers.",
        "Analyzes the chilling effect of the Official Secrets Act 1923 on investigative journalism."),
    match("Media Statutes", "Statutory Sections",
        "Match the legal provision in List-I with its statutory enactment in List-II:",
        ["Section 499 & 500", "Section 124A", "Section 66A (struck down)", "Section 8(1)"],
        ["Indian Penal Code (Defamation definition and punishment)", "Indian Penal Code (Sedition definition and punishment)", "Information Technology Act (Online offensive messages)", "Right to Information Act (Exemptions from disclosure)"],
        "A-I, B-II, C-III, D-IV",
        "499/500 = Defamation; 124A = Sedition; 66A = IT Act online speech (void); 8(1) = RTI exemptions.",
        "Matches statutory section numbers to their legal subject matter."),
    mcq("Media Statutes", "Central Information Commission (CIC)",
        "What is the Central Information Commission (CIC), constituted under the Right to Information Act 2005?",
        "The high-level autonomous statutory body that acts as the final appellate authority for RTI disputes involving central government ministries and public authorities",
        ["A police department that intercepts citizen emails",
         "A court that sentences citizens to life imprisonment",
         "A commercial company that sells advertising software"],
        "The CIC is the independent quasi-judicial watchdog enforcing transparency and hearing second appeals regarding central public bodies under RTI.",
        "Identifies the role and nature of the Central Information Commission."),
    stmt("Media Statutes", "Sub-Judice Rule",
        "The 'Sub-Judice' rule prohibits public discussion, editorial pronouncements, or media coverage that could prejudice an ongoing, unresolved trial before a court of law.",
        "Journalists are legally permitted to bribe presiding judges to obtain advance written copies of court verdicts.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because bribing judicial officers is a grave criminal offense.",
        "Defines the sub-judice rule in media law."),
    ar("Media Statutes", "Plagiarism vs Copyright Infringement",
        "Plagiarism is fundamentally an ethical violation of academic and journalistic integrity, whereas copyright infringement is a statutory violation of legal property rights.",
        "Copying a public domain Shakespeare text word-for-word without attribution is plagiarism, but does not constitute copyright infringement.",
        "both_correct_explain",
        "Because public domain works have no active copyright, copying them without credit violates academic ethics (plagiarism) without violating copyright statutes.",
        "Differentiates ethical plagiarism from statutory copyright infringement."),
    mcq("Media Statutes", "Idea-Expression Dichotomy",
        "In copyright law, what is the foundational 'Idea-Expression Dichotomy'?",
        "Copyright protects only the specific original tangible expression of an idea, but does NOT protect the underlying raw idea, historical fact, or concept itself",
        ["Copyright protects thoughts inside a person's brain before they are spoken",
         "Copyright protects all English dictionary words",
         "Copyright only protects physical sculptures made of bronze"],
        "Raw ideas, scientific concepts, and historical facts are free for all to explore; copyright protects only the original literary or artistic expression.",
        "Explains the Idea-Expression Dichotomy in intellectual property law."),
    match("Media Statutes", "Legal Punishments & Redress",
        "Match the legal violation in List-I with its standard judicial remedy in List-II:",
        ["Civil Defamation", "Criminal Defamation (IPC 500)", "Criminal Contempt of Court", "Copyright Infringement"],
        ["Court-ordered compensatory monetary damages and public apology", "Simple imprisonment up to two years, or fine, or both", "Simple imprisonment up to six months, or fine up to Rs. 2,000, or both", "Injunction restraining circulation, seizure of infringing copies, and damages"],
        "A-I, B-II, C-III, D-IV",
        "Civil defamation = damages/apology; Criminal defamation = up to 2 yrs prison/fine; Contempt = up to 6 months prison/Rs 2000 fine; Copyright = injunction/seizure/damages.",
        "Matches media law violations to their statutory remedies."),
    seq("Media Statutes", "Filing and Pursuing an RTI Application",
        "Arrange the stages of securing public documents under the RTI Act 2005:",
        ["Drafting clear, specific queries requesting public records or certified copies", "Paying the statutory application fee of Rs. 10 and submitting to designated PIO", "Receiving written response and inspecting requested records within 30 days", "Paying prescribed photocopying inspection fees for copies of certified records", "Receiving certified copies stamped and signed by public authority"],
        "I -> II -> III -> IV -> V",
        "RTI workflow: Drafting queries -> Application submission/Fee -> PIO response -> Photocopy fee payment -> Certified document receipt.",
        "Sequences practical workflow of an RTI application."),
    mcq("Media Statutes", "Digital Personal Data Protection Act 2023 (DPDP)",
        "The Digital Personal Data Protection Act 2023 (DPDP Act) governs the processing of digital personal data in India, establishing which regulatory authority?",
        "The Data Protection Board of India (DPBI)",
        ["The National Media Censor Directorate",
         "The Central Telegraph Inspection Guild",
         "The All India Radio Administrative Council"],
        "The DPDP Act 2023 established the Data Protection Board of India (DPBI) to enforce data privacy compliance and adjudicate violations.",
        "Identifies the Data Protection Board of India under the DPDP Act 2023.")
]

# ==============================================================================
# SLOT 40: Media Ethics & Professional Standards (Trial by Media, Paid News, Code of Conduct)
# ==============================================================================
SLOTS_36_40[40] = [
    mcq("Media Ethics", "Four Core Ethical Principles (SPJ Code)",
        "The Society of Professional Journalists (SPJ) Code of Ethics is structured around which four foundational pillars?",
        "Seek Truth and Report It; Minimize Harm; Act Independently; Be Accountable and Transparent",
        ["Maximize Corporate Profits; Eliminate Competition; Obey Government Orders; Conceal Sources",
         "Print Dramatic Sensations; Exaggerate Crises; Protect Advertisers; Attack Rivals",
         "Charge Money for Interviews; Ignore Fact-Checking; Support Political Parties; Avoid Criticism"],
        "The SPJ Code universalizes four ethical benchmarks: Seek Truth, Minimize Harm, Act Independently, and Be Accountable.",
        "Recalls the four foundational pillars of the SPJ Code of Ethics."),
    mcq("Media Ethics", "Trial by Media Harm",
        "Why is 'Trial by Media' condemned as a severe ethical violation in journalism?",
        "It pronounces an accused individual guilty in the court of public opinion before a judicial verdict, destroying their reputation and prejudicing fair trial rights",
        ["It costs too much money to purchase television studio microphones",
         "It prevents lawyers from wearing black coats in courtrooms",
         "It requires newspapers to be printed on glossy paper"],
        "Trial by media usurps the judicial function, conducting sensational kangaroo courts that obliterate the presumption of innocence.",
        "Analyzes the ethical and democratic hazards of Trial by Media."),
    stmt("Media Ethics", "Protection of Confidential Sources",
        "Journalistic ethics dictates that a reporter must protect the identity of a confidential source who provided information on the condition of anonymity.",
        "The Press Council of India code emphasizes that revealing a confidential source breaches professional trust and discourages future whistleblowers.",
        "both_true",
        "Both statements reflect the sacred journalistic principle of source confidentiality.",
        "Validates the ethical imperative of protecting confidential sources."),
    ar("Media Ethics", "Conflict of Interest in Journalism",
        "Financial and corporate journalists must disclose personal stock holdings or recuse themselves from reporting on companies whose shares they own.",
        "Failing to disclose financial holdings creates a severe conflict of interest, tempting reporters to publish favorable spin to artificially inflate their personal wealth.",
        "both_correct_explain",
        "Personal economic interests compromise journalistic objectivity, necessitating strict disclosure and recusal rules to preserve integrity.",
        "Analyzes conflict of interest rules in financial journalism."),
    match("Media Ethics", "Ethical Dilemmas in Journalism",
        "Match the ethical violation in List-I with its journalistic manifestation in List-II:",
        ["Paid News", "Plagiarism", "Checkbook Journalism", "Sensationalism / Clickbait"],
        ["Publishing favorable candidate coverage in exchange for financial kickbacks during elections", "Stealing another reporter's original reporting, sentences, or paragraphs without attribution", "Paying large cash sums to criminal suspects or celebrities to purchase exclusive interviews", "Distorting, exaggerating, and sexualizing ordinary news to artificially manufacture public hysteria"],
        "A-I, B-II, C-III, D-IV",
        "Paid news = cash for favorable coverage; Plagiarism = stealing text; Checkbook = cash for interviews; Sensationalism = distorting news for hysteria.",
        "Matches journalistic ethical violations to concrete manifestations."),
    mcq("Media Ethics", "Minimizing Harm Principle",
        "Which journalistic practice directly embodies the ethical duty to 'Minimize Harm'?",
        "Concealing the identity and photographs of juvenile victims of crime, rape survivors, and shielding grieving relatives from aggressive intrusions",
        ["Publishing the private residential home addresses of children in daily newspapers",
         "Live-broadcasting the uncovered faces of sexual assault survivors on evening television",
         "Interviewing traumatized children inside intensive care units without parental consent"],
        "Minimizing harm demands compassionate restraint, protecting vulnerable individuals, minors, and crime victims from gratuitous media trauma.",
        "Applies the 'Minimize Harm' ethical principle to vulnerable crime victims."),
    stmt("Media Ethics", "Sensationalism during Disasters",
        "During live disaster and hostage situations (such as the 2008 Mumbai 26/11 attacks), media channels should refrain from broadcasting live security troop movements.",
        "Live coverage of tactical commandos during an ongoing hostage crisis gives terrorists and their handlers real-time tactical intelligence, endangering lives.",
        "both_true",
        "Both statements are tragic historical lessons from 26/11, leading to strict regulatory bans on live operational coverage during anti-terror actions.",
        "Evaluates media ethics and tactical restraint during live terror and disaster coverage."),
    ar("Media Ethics", "Right to Privacy vs Public Interest",
        "Journalists may ethically report on an individual's private life only when there is an overriding, legitimate 'Public Interest'.",
        "Public figures have a right to reasonable personal privacy, which can only be superseded when private conduct reveals corruption, public hypocrisy, or illegality.",
        "both_correct_explain",
        "Mere prurient public curiosity is not synonymous with 'public interest'; privacy may be breached only when public accountability demands disclosure.",
        "Differentiates public interest from morbid public curiosity in privacy issues."),
    seq("Media Ethics", "Ethical Editorial Decision-Making Flow",
        "Arrange the stages of resolving an ethical dilemma in a newsroom (e.g. deciding whether to publish leaked private emails):",
        ["Identify the ethical conflict between public's right to know and individual privacy", "Verify authenticity of documents and evaluate motives of source", "Analyze consequences: who will be harmed and what public benefit will be served?", "Explore ethical alternatives and seek independent legal and editorial counsel", "Make transparent, justifiable editorial decision and stand accountable for published story"],
        "I -> II -> III -> IV -> V",
        "Ethical decision flow: Identify dilemma -> Verify authenticity -> Consequence analysis -> Explore alternatives -> Justifiable accountable action.",
        "Sequences newsroom ethical decision-making framework."),
    mcq("Media Ethics", "Private Treaties Controversy",
        "What was the controversial media practice of 'Private Treaties' pioneered by certain Indian media conglomerates in the 2000s?",
        "Media companies acquired equity stakes/shares in corporate firms in exchange for guaranteed advertising space and favorable editorial coverage",
        ["Newspapers signing peace treaties between warring foreign nations",
         "Reporters selling personal diaries to public libraries",
         "Editors purchasing private residential plots in hill stations"],
        "Private treaties compromised editorial independence by giving media conglomerates direct financial equity in the very companies they reported on.",
        "Critiques the controversial practice of 'Private Treaties' in Indian media."),
    stmt("Media Ethics", "Suicide Reporting Guidelines (WHO / PCI)",
        "The World Health Organization (WHO) and Press Council of India prohibit publishing sensational front-page headlines or detailed operational methods of suicide.",
        "Sensationalized, detailed reporting of suicide can trigger 'Copycat Suicides' (the Werther Effect) among vulnerable individuals.",
        "both_true",
        "Both statements are scientifically verified and represent mandatory ethical reporting guidelines to prevent suicide contagion.",
        "Validates ethical suicide reporting guidelines and the Werther Effect."),
    ar("Media Ethics", "Checkbook Journalism Hazards",
        "Ethical news organizations universally condemn 'Checkbook Journalism' (paying sources for interviews).",
        "Paying cash incentives tempts interviewees to exaggerate, invent sensational fabrications, and tailor stories to maximize their financial payout.",
        "both_correct_explain",
        "Financial compensation corrupts source veracity, destroying the credibility and objectivity of the reported information.",
        "Explains why Checkbook Journalism destroys factual credibility."),
    match("Media Ethics", "Ethical Norms and Codes",
        "Match the ethical journalism standard in List-I with its practical guideline in List-II:",
        ["Right of Reply", "Correction and Clarification", "Identification of Victims", "Surreptitious Recording"],
        ["Giving an accused person fair, prompt, and adequate space to respond to allegations", "Prominently publishing corrections when factual errors are identified in past reports", "Never publishing names, photographs, or identifying details of rape or POCSO survivors", "Using hidden spy cameras only as an exceptional last resort on matters of grave public crime"],
        "A-I, B-II, C-III, D-IV",
        "Right of reply = fair response; Correction = publishing corrections; Victim ID = concealing rape/minor identities; Surreptitious recording = last resort only.",
        "Matches core journalistic ethical norms to practical newsroom guidelines."),
    mcq("Media Ethics", "Ombudsman / Internal Self-Correction",
        "Why is an institutional 'Ombudsman' (Readers' Representative) considered a gold standard of newsroom ethical accountability?",
        "Because they operate independently inside the newsroom to investigate reader grievances, challenge editors, and publish transparent corrections in the paper's own columns",
        ["Because they are appointed by the city police to inspect employee attendance",
         "Because they write humorous horoscope predictions for the weekend edition",
         "Because they decide the annual subscription price of the paper"],
        "An ombudsman gives readers an impartial internal advocate, cementing credibility through transparent public self-correction.",
        "Explains the value of a news ombudsman in ethical self-regulation."),
    stmt("Media Ethics", "Fabrication & Jayson Blair Scandal",
        "In 2003, reporter Jayson Blair resigned in disgrace from The New York Times after being caught fabricating quotes, scenes, and plagiarizing dozens of national stories.",
        "The New York Times celebrated Jayson Blair by awarding him an automatic promotion to Editor-in-Chief.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because the discovery of his systematic fabrications led to his firing and the resignation of top editors.",
        "Recalls the landmark Jayson Blair journalistic fabrication scandal."),
    ar("Media Ethics", "Grief and Trauma Sensitivity",
        "Journalists covering horrific plane crashes or disasters must never shove microphones into the faces of shock-stricken grieving relatives demanding 'How do you feel?'.",
        "Intrusive, aggressive interviewing of individuals in acute psychological shock inflicts re-traumatization and violates fundamental human dignity.",
        "both_correct_explain",
        "Exploiting personal agony for emotional broadcast spectacle violates basic compassion and dignity, requiring journalistic sensitivity.",
        "Condemns insensitive media intrusion during bereavement and trauma."),
    mcq("Media Ethics", "Native Advertising / Sponsored Content",
        "What ethical hazard does 'Native Advertising' (sponsored content) pose to readers when not clearly labeled?",
        "It deceives readers by mimicking the visual layout, typography, and editorial tone of legitimate objective news stories, disguising commercial PR as journalism",
        ["It causes computer screens to short-circuit and catch fire",
         "It increases the physical weight of printed broadsheet newspapers by 100 kilograms",
         "It forces readers to read the paper backwards"],
        "Native advertising tricks readers into trusting commercial advertising as objective editorial content unless boldly and transparently labeled.",
        "Analyzes the deception inherent in unlabeled native advertising."),
    match("Media Ethics", "Global Ethical Bodies",
        "Match the ethical or self-regulatory organization in List-I with its institutional mandate in List-II:",
        ["PCI (Press Council of India)", "SPJ (Society of Professional Journalists)", "NBDA / NBSA (News Broadcasters & Digital Association)", "ICFJ (International Center for Journalists)"],
        ["Quasi-judicial statutory watchdog preserving print press freedom and ethics in India", "Pioneered the globally celebrated four-pillar Code of Ethics in the United States", "Self-regulatory complaints authority for private Indian television news channels", "Global organization promoting professional standards, digital tools, and investigative training"],
        "A-I, B-II, C-III, D-IV",
        "PCI = Indian print ethics; SPJ = US four-pillar code; NBDA/NBSA = Indian private TV news ethics; ICFJ = global training and standards.",
        "Matches major domestic and international journalistic ethics bodies."),
    seq("Media Ethics", "Handling a Major Factual Error in Print",
        "Arrange the ethical steps a newspaper must execute upon realizing it printed a major defamatory factual error:",
        ["Immediate internal editorial investigation confirming the error and false allegations", "Drafting a clear, prominent, unhedged correction and unconditional apology", "Publishing the correction and apology on the same page and prominence as the original error", "Delivering a personal written letter of apology to the aggrieved individual", "Reviewing newsroom copy-editing protocols to prevent recurrence of similar lapses"],
        "I -> II -> III -> IV -> V",
        "Correction workflow: Confirm error -> Draft unhedged apology -> Prominent publication -> Personal apology letter -> Review desk protocols.",
        "Sequences professional protocol for correcting major errors in print journalism."),
    mcq("Media Ethics", "Public Good as Supreme Compass",
        "In the final analysis, what is the ultimate ethical north star that justifies the special privileges, protections, and constitutional freedoms enjoyed by the press?",
        "Uncompromising service to the public interest, democratic accountability, civic enlightenment, and truth",
        ["Maximizing quarterly advertising revenues for corporate media barons",
         "Providing free entertainment gossip for celebrity fans",
         "Serving as a mouthpiece for whichever political party is in power"],
        "Freedom of the press is not a personal license for proprietors, but a sacred democratic trust held on behalf of the public interest.",
        "Summarizes the ethical rationale of press freedom as service to the public interest.")
]

print("Mass Media Slots 36 to 40 compiled successfully: 5 slots (100 questions).")
'''

with open("scripts/subject_generators/mmc_s36_40.py", "w", encoding="utf-8") as f:
    f.write(content)

print(f"Generated scripts/subject_generators/mmc_s36_40.py ({len(content)} bytes)")
