#!/usr/bin/env python3
"""
make_mmc_s21_30.py
Generates mmc_s21_30.py containing Slots 21 to 30 for Mass Media & Mass Communication (Code 318).
"""

import sys, os

out_path = "scripts/subject_generators/mmc_s21_30.py"

header = '''# Mass Media & Mass Communication (Code 318) - Slots 21 to 30 (200 Questions)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from slot_helpers import mcq, stmt, ar, match, seq

SLOTS_21_30 = {}
'''

# We will build slots 21 to 30 into a list of slot strings
slots_code = []

# ==============================================================================
# SLOT 21: Podcasting & Digital Audio
# ==============================================================================
s21 = '''
# ==============================================================================
# SLOT 21: Podcasting & Digital Audio
# ==============================================================================
SLOTS_21_30[21] = [
    mcq("Podcasting", "Podcast Origin & Technology",
        "The term 'Podcast' was originally coined in 2004 by journalist Ben Hammersley as a portmanteau blending which two words?",
        "iPod (Apple's portable MP3 player) and Broadcast",
        ["Pocket and Castaway", "Post and Document", "Polytechnic and Cassette"],
        "Ben Hammersley coined 'podcast' in The Guardian (2004), combining Apple's iPod and broadcast.",
        "Recalls the etymology of podcasting."),
    mcq("Podcasting", "RSS Feed Role",
        "What fundamental digital architecture enables automated syndication and delivery of podcast audio files to subscriber feeds?",
        "RSS (Really Simple Syndication) feed with enclosure tags linking to audio media files",
        ["Analog telegraph cables running along railway lines",
         "Shortwave radio transmitters operating on medium voltage",
         "Printed postcards delivered weekly by postal couriers"],
        "RSS feeds containing media enclosure tags allow podcast aggregator apps to automatically pull new episodes upon publication.",
        "Identifies RSS as the core technical delivery architecture of podcasts."),
    stmt("Podcasting", "Linear Radio vs Asynchronous Podcasting",
        "Linear radio broadcasting requires listeners to tune in at a specific scheduled time of day to catch a program.",
        "Podcasting is an asynchronous, on-demand audio medium where listeners download or stream content at their own personal convenience.",
        "both_true",
        "Both statements correctly distinguish linear time-bound radio broadcasting from on-demand asynchronous podcasting.",
        "Contrasts linear radio with on-demand podcasting."),
    ar("Podcasting", "Niche Demographics in Podcasting",
        "Podcasts thrive on serving hyper-specific, micro-niche audiences (such as indie board-game designers or Sanskrit etymology).",
        "Unlike broadcast radio, podcasting is not constrained by finite broadcast spectrum or the necessity of maximizing mass regional ratings.",
        "both_correct_explain",
        "The absence of spectrum limits and mass demographic imperatives allows podcasts to cater economically to specialized niche communities.",
        "Analyzes how podcasting enables long-tail niche programming."),
    match("Podcasting", "Podcast Formats",
        "Match the podcast format in List-I with its structural style in List-II:",
        ["Solo Commentary / Monologue", "Interview / Q&A", "Co-hosted Banter / Dialogue", "Narrative Non-Fiction / Audio Doc"],
        ["Single presenter sharing personal insights, expertise, or storytelling", "Host questioning a new guest expert each episode", "Two or more hosts exploring topics with natural conversational chemistry", "Heavily produced audio documentary with field sound, multiple voices, and scoring"],
        "A-I, B-II, C-III, D-IV",
        "Solo = monologue; Interview = guest Q&A; Co-hosted = multi-host banter; Narrative doc = produced documentary.",
        "Matches podcast formats to production styles."),
    mcq("Podcasting", "Serial (2014) Milestone",
        "Which landmark investigative true-crime podcast, hosted by Sarah Koenig and spun off from This American Life, ignited the global modern podcasting boom in 2014?",
        "Serial",
        ["The Daily", "Radiolab", "Hardcore History"],
        "Serial became a cultural phenomenon, achieving record-breaking global downloads and ushering podcasting into the mainstream media consciousness.",
        "Identifies Serial as the breakthrough podcast milestone."),
    stmt("Podcasting", "Podcatcher Apps",
        "Software applications that subscribe to, download, and organize podcast RSS feeds are commonly termed 'Podcatchers' (e.g. Apple Podcasts, Spotify).",
        "Podcatchers can only play audio files if the user is connected to a live satellite television dish.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because podcatchers stream or download MP3/AAC audio files via standard internet protocols.",
        "Defines podcatcher applications."),
    ar("Podcasting", "Intimacy in Earphone Listening",
        "Podcasts foster exceptionally high levels of perceived listener intimacy and personal host attachment.",
        "Podcasts are predominantly consumed through personal headphones, delivering the human voice directly inside the listener's head without ambient distraction.",
        "both_correct_explain",
        "Headphone delivery and conversational voice design create an intensely private, intimate acoustic relationship with the host.",
        "Explains the psychological intimacy of earphone-delivered podcasts."),
    seq("Podcasting", "Podcast Production Pipeline",
        "Arrange the stages of launching a weekly narrative podcast series in sequential order:",
        ["Conceptualizing series premise, episode outlines, and target demographic", "Recording voice interviews and narration tracks using broadcast microphones", "Editing audio, balancing levels, and layering music and ambient SFX in DAW", "Exporting audio master (MP3) and uploading to podcast media host", "Generating RSS feed and distributing across major podcast directory platforms"],
        "I -> II -> III -> IV -> V",
        "Podcast pipeline: Concept -> Recording -> DAW editing -> Media host upload -> RSS directory distribution.",
        "Sequences podcast production and distribution stages."),
    mcq("Podcasting", "Host-Read Ads",
        "Why do 'Host-Read Advertisements' in podcasts command higher commercial sponsor rates than automated programmatic audio ads?",
        "Because listeners trust the host personally, making the endorsement feel like an authentic recommendation from a trusted friend",
        ["Because host-read ads must be spoken in five foreign languages simultaneously",
         "Because radio legislation forces all podcast hosts to buy the sponsor's factory",
         "Because host-read ads can only be heard by university professors"],
        "Host-read ads leverage parasocial trust, resulting in significantly higher brand recall and listener conversion rates.",
        "Explains the effectiveness of host-read podcast advertising."),
    stmt("Podcasting", "Podcast Monetization Models",
        "Podcasts can be monetized through brand sponsorships, subscription paywalls, crowdfunding (e.g. Patreon), and live tour events.",
        "Podcasting is legally forbidden from generating any financial revenue anywhere in the world.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because podcasting is a thriving commercial industry with diverse revenue streams.",
        "Identifies diverse podcast monetization channels."),
    ar("Podcasting", "Binge Listening Behavior",
        "Narrative serialized podcasts frequently stimulate 'Binge Listening' behavior among audiences.",
        "Compelling cliffhangers, continuous storylines, and instantaneous digital access empower listeners to consume entire multi-episode seasons consecutively.",
        "both_correct_explain",
        "Serialization coupled with friction-free on-demand access naturally drives immersive consecutive binge listening.",
        "Analyzes the psychology of binge listening in serialized podcasts."),
    match("Podcasting", "Audio Analytics Metrics",
        "Match the podcast analytics metric in List-I with its measurement focus in List-II:",
        ["Unique Downloads", "Completion Rate", "Churn Rate", "Subscriber Count"],
        ["Total number of distinct IP addresses that downloaded an episode file", "Percentage of an episode duration actually listened to before stopping", "Rate at which recurring listeners unsubscribe from the feed", "Estimated size of ongoing core audience following the feed"],
        "A-I, B-II, C-III, D-IV",
        "Downloads = distinct IP requests; Completion = percentage heard; Churn = unsubscription rate; Subscribers = core follower base.",
        "Matches podcast metrics to analytical definitions."),
    mcq("Podcasting", "ID3 Tags in MP3",
        "In digital audio podcasting, what is the role of an 'ID3 Tag' embedded within an MP3 file?",
        "It stores metadata such as episode title, artist/host name, album/podcast title, year, episode number, and cover artwork",
        ["It speeds up the computer's CPU processing fans",
         "It scrambles the audio to prevent humans from hearing it",
         "It changes the color of the listener's computer keyboard"],
        "ID3 metadata containers embed track title, artist, podcast series name, and cover artwork directly inside MP3 files.",
        "Identifies the role of ID3 metadata tags in MP3 files."),
    stmt("Podcasting", "Vodcast / Video Podcast",
        "A 'Vodcast' (or Video Podcast) includes video footage of hosts and guests in studio alongside the audio track, widely popular on YouTube.",
        "Vodcasts are strictly prohibited from being played on mobile smartphones.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because video podcasts are extensively consumed on smartphones via streaming apps.",
        "Defines video podcasts (vodcasts)."),
    ar("Podcasting", "Independent Creator Economy",
        "Podcasting has empowered independent journalists and creators to build self-sustaining media enterprises outside legacy corporate newsrooms.",
        "Affordable home recording hardware and free open distribution protocols have lowered the barriers to audio publishing to near zero.",
        "both_correct_explain",
        "Democratized production tools and open RSS syndication remove gatekeeping bottlenecks, fostering an independent creator economy.",
        "Explains how podcasting fuels the creator economy."),
    mcq("Podcasting", "Dynamic Ad Insertion (DAI)",
        "What is 'Dynamic Ad Insertion' (DAI) in modern digital audio podcast distribution?",
        "Technology that automatically inserts targeted, up-to-date advertisements into podcast episodes at the moment of download based on listener location",
        ["A physical robot that places CD discs into household mailboxes",
         "A sound effect that simulates car horn honking during podcasts",
         "An audio glitch that erases commercial sponsors"],
        "DAI swaps out old ads for fresh, geo-targeted commercials whenever any back-catalog episode is downloaded.",
        "Defines Dynamic Ad Insertion in digital audio."),
    match("Podcasting", "Audio Platforms",
        "Match the audio platform in List-I with its operational profile in List-II:",
        ["Spotify", "Apple Podcasts", "Audible", "SoundCloud"],
        ["Streaming platform leading proprietary podcast acquisitions and music integration", "Pioneering directory setting the open RSS indexing standard for podcasts", "Subscription audio service specializing in professionally narrated audiobooks and originals", "Open audio sharing platform originally celebrated for indie musicians and creators"],
        "A-I, B-II, C-III, D-IV",
        "Spotify = streaming/acquisitions; Apple = open RSS pioneer; Audible = audiobooks; SoundCloud = indie creator sharing.",
        "Matches digital audio platforms to operational profiles."),
    seq("Podcasting", "Audio Show Launch Checklist",
        "Arrange the pre-launch checklist steps for publishing a new podcast series:",
        ["Designing official podcast cover art matching directory resolution standards (3000x3000px)", "Recording and editing a compelling 2-minute series trailer episode", "Drafting clear show description, genre category tags, and host bio", "Setting up hosting account and validating RSS feed syntax", "Submitting validated RSS feed to major podcast distribution directories"],
        "I -> II -> III -> IV -> V",
        "Pre-launch checklist: Artwork -> Trailer -> Metadata/Category -> RSS validation -> Directory submission.",
        "Sequences podcast pre-launch setup steps."),
    mcq("Podcasting", "Open vs Walled Garden Ecosystem",
        "Why do digital media scholars praise the traditional RSS podcast ecosystem as an 'Open Web' standard?",
        "Because anyone can host audio on any server and any podcast app can read the open RSS feed without being locked into a single proprietary platform",
        ["Because podcast files can only be opened using physical keys",
         "Because all podcasts are required to be completely free of speech",
         "Because podcasting is owned entirely by the United Nations postal agency"],
        "Open RSS allows decentralized hosting and consumption across competing apps, resisting closed proprietary walled gardens.",
        "Explains the open-web architecture of RSS podcasting.")
]
'''
slots_code.append(s21)

# ==============================================================================
# SLOT 22: History of Television in India
# ==============================================================================
s22 = '''
# ==============================================================================
# SLOT 22: History of Television in India
# ==============================================================================
SLOTS_21_30[22] = [
    mcq("Television History", "First Television Broadcast in India",
        "When and where did television broadcasting make its experimental debut in India, assisted by a UNESCO educational grant?",
        "September 15, 1959, in New Delhi",
        ["January 26, 1950, in Bombay", "August 15, 1947, in Calcutta", "October 2, 1970, in Madras"],
        "Experimental television began in Delhi on September 15, 1959, with a small UNESCO-backed transmitter broadcasting educational programs twice weekly.",
        "Recalls the launch date and location of television in India."),
    mcq("Television History", "Krishi Darshan Launch",
        "Launched on January 26, 1967, to broadcast agricultural innovations to farmers in 80 villages, which is the longest-running television program in India?",
        "Krishi Darshan",
        ["Gram Sevak", "Kisan Bulletin", "Mandi Samachar"],
        "Krishi Darshan debuted on Republic Day 1967 under Dr. Vikram Sarabhai's initiative, making it India's longest continuously running TV program.",
        "Identifies Krishi Darshan as India's longest-running television show."),
    stmt("Television History", "SITE Experiment (1975-1976)",
        "The Satellite Instructional Television Experiment (SITE) utilized NASA's ATS-6 satellite to broadcast educational programming directly to 2,400 backward villages.",
        "SITE was hailed internationally as the largest techno-social mass communication experiment in the developing world.",
        "both_true",
        "Both statements are historically true. SITE (1975-76), spearheaded by ISRO and NASA, proved the power of satellite TV for rural development.",
        "Evaluates the historic SITE experiment."),
    ar("Television History", "Separation of Doordarshan from AIR",
        "In April 1976, television was officially separated from All India Radio and given its own independent department named 'Doordarshan'.",
        "Rapid television expansion demanded specialized visual production techniques, studio infrastructure, and distinct administrative management.",
        "both_correct_explain",
        "Because visual TV production diverges fundamentally from audio radio broadcasting, Doordarshan was separated as a distinct directorate in 1976.",
        "Explains why Doordarshan was separated from AIR in 1976."),
    match("Television History", "Key Milestones",
        "Match the historic milestone in Indian television with its momentous year in List-II:",
        ["Experimental UNESCO pilot in Delhi", "Launch of Krishi Darshan", "SITE Satellite Experiment", "Separation of Doordarshan from AIR"],
        ["1959", "1967", "1975-1976", "1976"],
        "A-I, B-II, C-III, D-IV",
        "Pilot = 1959; Krishi Darshan = 1967; SITE = 1975-76; DD separation = 1976.",
        "Matches landmark television milestones to their respective years."),
    mcq("Television History", "1982 Color TV & Asian Games",
        "Which major international sporting event hosted in New Delhi served as the catalyst for the nationwide introduction of Color Television and national networking in India?",
        "The 1982 Asian Games (Asiad)",
        ["The 1975 Cricket World Cup", "The 1996 Olympic Games", "The 2010 Commonwealth Games"],
        "The IX Asian Games in New Delhi (1982) drove the dramatic modernization of Indian TV, launching color broadcasting and INSAT-1A networking.",
        "Identifies the 1982 Asian Games as the driver of color television."),
    stmt("Television History", "INSAT and National Networking",
        "The commissioning of the INSAT-1A and INSAT-1B satellites allowed Doordarshan to network all regional transmitters for simultaneous national broadcasts.",
        "Before INSAT, television programs had to be physically transported on heavy magnetic tape reels by train or plane between cities.",
        "both_true",
        "Both statements are true. Satellite transponders replaced the cumbersome physical transport of tape reels with instantaneous networking.",
        "Explains the revolutionary impact of INSAT on television networking."),
    ar("Television History", "Hum Log Milestone",
        "In 1984, Doordarshan broadcast 'Hum Log', celebrated as India's first indigenous television soap opera.",
        "Hum Log was conceived as an entertainment-education (pro-social) melodrama addressing family planning, gender equality, and alcoholism.",
        "both_correct_explain",
        "Inspired by Mexican telenovela pioneer Miguel Sabido, Hum Log combined popular drama with socially progressive developmental messaging.",
        "Analyzes Hum Log as India's first pro-social soap opera."),
    seq("Television History", "Evolution of Indian Television",
        "Arrange the historical milestones of Indian television in chronological sequence:",
        ["Experimental broadcast begins at Delhi Kendra (1959)", "Dr. Vikram Sarabhai leads SITE rural satellite broadcast (1975-76)", "Separation from AIR to create independent Doordarshan (1976)", "Color television and national networking for Asian Games (1982)", "First private satellite channels enter Indian homes during Gulf War (1991-92)"],
        "I -> II -> III -> IV -> V",
        "Timeline: 1959 (Pilot) -> 1975 (SITE) -> 1976 (DD creation) -> 1982 (Color/Asiad) -> 1991 (Private satellite TV).",
        "Sequences the chronological trajectory of Indian television."),
    mcq("Television History", "The Mega-Epics of the 1980s",
        "In the late 1980s, which two mythological television serials brought the entire nation to a standstill on Sunday mornings, commanding unprecedented 90%+ viewership?",
        "Ramanand Sagar's Ramayan (1987) and B. R. Chopra's Mahabharat (1988)",
        ["Shaktimaan and Captain Vyom",
         "Kyunki Saas Bhi Kabhi Bahu Thi and Kahaani Ghar Ghar Kii",
         "Buniyaad and Khandaan"],
        "Ramayan and Mahabharat became unprecedented cultural phenomena, emptying streets across India during Sunday morning broadcasts.",
        "Identifies Ramayan and Mahabharat as cultural mega-epics."),
    stmt("Television History", "1991 Cable TV Revolution",
        "The 1991 Gulf War, broadcast live by CNN, catalyzed the rapid spread of private satellite dishes and neighborhood cable television across urban India.",
        "In 1992, Zee TV was launched as the first private Hindi-language satellite entertainment channel in India.",
        "both_true",
        "Both statements are historical facts marking the deregulation and explosion of private satellite TV in India.",
        "Evaluates the 1991-1992 private cable and satellite TV boom."),
    ar("Television History", "Demise of State Monopoly",
        "The advent of private satellite television in the early 1990s permanently dismantled Doordarshan's monopoly over the Indian television landscape.",
        "Viewers gained access to dozens of 24-hour entertainment, music (MTV/Channel V), and private news channels via local cable operators.",
        "both_correct_explain",
        "Cross-border satellite broadcasts bypassed state terrestrial transmitters, providing viewers diverse alternatives to Doordarshan.",
        "Explains how satellite television ended the state broadcasting monopoly."),
    match("Television History", "Pioneering Indian TV Shows",
        "Match the iconic television series in List-I with its distinctive cultural milestone in List-II:",
        ["Hum Log (1984)", "Buniyaad (1986)", "Ramayan (1987)", "Tara (1993)"],
        ["India's first entertainment-education soap opera", "Masterful family drama depicting the trauma of Partition, directed by Ramesh Sippy", "First mythological epic television series, directed by Ramanand Sagar", "Pioneering progressive private satellite drama depicting contemporary urban women on Zee TV"],
        "A-I, B-II, C-III, D-IV",
        "Hum Log = first soap opera; Buniyaad = Partition drama; Ramayan = mythological epic; Tara = urban women on Zee TV.",
        "Matches iconic Indian television serials to their historical significance."),
    mcq("Television History", "DD Metro / Entertainment Channel",
        "In 1993, Doordarshan launched which secondary channel targeting young, urban viewers with popular entertainment to compete with private cable TV?",
        "DD Metro (DD-2)",
        ["DD Bharati", "DD Sports", "DD Urdu"],
        "DD Metro was launched in 1993 to offer lighter entertainment and compete directly with satellite channels like Zee and Star.",
        "Recalls the role of DD Metro in the 1990s TV rivalry."),
    stmt("Television History", "Kheda Communications Project",
        "The Kheda Communications Project (1975-1990) in Gujarat utilized a local low-power transmitter to broadcast participatory development programs in local Charotari dialect.",
        "The Kheda project won the prestigious UNESCO Prize for Rural Communication in 1984.",
        "both_true",
        "Both statements are true, honoring the Kheda Project as a world-renowned participatory development experiment.",
        "Highlights the achievements of the Kheda Communications Project."),
    ar("Television History", "Commercialization of Doordarshan",
        "Beginning in the late 1970s and 1980s, Doordarshan shifted from being purely state-funded to accepting commercial advertisements and sponsored programs.",
        "Commercial advertising revenue enabled Doordarshan to finance rapid network expansion across India and incentivize private television serial producers.",
        "both_correct_explain",
        "Commercial sponsorship provided the capital needed to commission blockbuster serials and expand transmitter infrastructure.",
        "Analyzes the commercialization of Doordarshan in the 1980s."),
    mcq("Television History", "Doordarshan's Signature Logo",
        "Doordarshan's famous eye-shaped symbol logo, paired with a haunting signature tune composed by Pandit Ravi Shankar and Ustad Ali Ahmed Hussain Khan, was designed by:",
        "National Institute of Design (NID), Ahmedabad (conceptualized by Devashis Nayak)",
        ["The Royal College of Art, London",
         "The Film and Television Institute of India (FTII)",
         "The Indian Space Research Organisation (ISRO)"],
        "The iconic eye-symbol of Doordarshan was designed at NID Ahmedabad in 1976, accompanied by an iconic classical score.",
        "Recalls the design origin of Doordarshan's iconic logo and music."),
    match("Television History", "Institutional Pioneers",
        "Match the visionary leader in List-I with their transformative impact on Indian television in List-II:",
        ["Dr. Vikram Sarabhai", "Prof. Yash Pal", "Manohar Shyam Joshi", "Ramesh Sippy"],
        ["Father of Indian space program who conceived SITE and social uses of TV", "Renowned scientist who directed Space Applications Centre during SITE and hosted 'Turning Point'", "Literary giant who scripted landmark serials 'Hum Log' and 'Buniyaad'", "Acclaimed filmmaker who directed the partition epic television series 'Buniyaad'"],
        "A-I, B-II, C-III, D-IV",
        "Sarabhai = conceived SITE; Yash Pal = SITE/Turning Point host; Joshi = writer Hum Log/Buniyaad; Sippy = director Buniyaad.",
        "Matches pioneers of Indian television to their accomplishments."),
    seq("Television History", "Satellite TV Emergence in India",
        "Arrange the appearance of private satellite television networks in India in chronological order:",
        ["CNN broadcasts live footage of 1991 Gulf War via satellite dishes", "Subhash Chandra launches Zee TV as first Hindi private satellite channel (1992)", "Rupert Murdoch's News Corporation acquires Star TV network", "Sony Entertainment Television (SET) enters the Indian market (1995)", "Launch of dedicated 24x7 private news channels (late 1990s)"],
        "I -> II -> III -> IV -> V",
        "Chronology: CNN Gulf War (1991) -> Zee TV launch (1992) -> Star TV acquisition -> Sony entry (1995) -> 24/7 news channels.",
        "Sequences the entry and consolidation of private satellite television."),
    mcq("Television History", "Low Power Transmitters (LPTs)",
        "During the 1980s expansion under Prime Minister Indira Gandhi, what technological initiative allowed Doordarshan to install 'a transmitter a day' across smaller Indian towns?",
        "Installation of Low Power Transmitters (LPTs) and Very Low Power Transmitters (VLPTs) relaying satellite signals from Delhi",
        ["Underground optical fiber lines laid to every village home",
         "Submarine cables running along all rivers",
         "Hot-air balloons broadcasting television signals from the sky"],
        "LPTs and VLPTs receiving feeds from INSAT enabled rapid, cost-effective physical expansion of terrestrial TV coverage across India.",
        "Explains the LPT expansion program of Doordarshan in the 1980s.")
]
'''
slots_code.append(s22)

# ==============================================================================
# SLOT 23: Public vs Private Television & Audience Measurement
# ==============================================================================
s23 = '''
# ==============================================================================
# SLOT 23: Public vs Private Television & Audience Measurement
# ==============================================================================
SLOTS_21_30[23] = [
    mcq("Public vs Private TV", "Public Service Mandate",
        "What defines the core philosophical mandate of a 'Public Service Broadcaster' (like Doordarshan) compared to a commercial private channel?",
        "To inform, educate, and entertain all citizens universally without commercial bias, serving minority interests, national culture, and civic literacy",
        ["To maximize quarterly corporate shareholder profits by broadcasting only reality gossip",
         "To broadcast advertisements for twenty-four hours continuously",
         "To charge viewers one thousand rupees per minute of viewing"],
        "Public service broadcasting prioritizes universal access, citizenship, cultural diversity, and education over commercial rating metrics.",
        "Defines the core philosophy of public service broadcasting."),
    mcq("Public vs Private TV", "TRP Definition",
        "In television broadcasting, what does the acronym 'TRP' stand for?",
        "Television Rating Point",
        ["Total Radio Performance", "Technical Relay Protocol", "Transponder Radiation Power"],
        "TRP stands for Television Rating Point, measuring the percentage of a target audience tuned into a specific program at a specific time.",
        "Recalls the full form of TRP."),
    stmt("Public vs Private TV", "Commercial Channel Revenue Model",
        "Commercial private television channels depend overwhelmingly on advertising revenue, which is directly linked to TRP ratings.",
        "High TRP ratings allow commercial television channels to command higher advertising rates per 10-second commercial spot.",
        "both_true",
        "Both statements are true. Advertising rates are directly proportional to audience ratings (TRP).",
        "Explains the relationship between TRP ratings and commercial ad rates."),
    ar("Public vs Private TV", "Sensationalism Driven by TRP",
        "The intense competition for TRPs has pushed many 24-hour commercial news channels toward sensationalism, shouting debates, and melodrama.",
        "Sensationalist content, dramatic visual graphics, and emotional controversy are more effective at capturing fleeting channel-surfing viewers than calm analytical reporting.",
        "both_correct_explain",
        "Commercial reliance on instantaneous ratings incentivizes high-decibel spectacle to grab attention and boost TRPs.",
        "Analyzes the causal link between commercial TRP chasing and media sensationalism."),
    match("Public vs Private TV", "Audience Measurement Concepts",
        "Match the television audience measurement term in List-I with its definition in List-II:",
        ["BARC", "Peoplemeter", "TVR (Television Rating)", "Reach"],
        ["Broadcast Audience Research Council, the joint industry body measuring TV viewership in India", "An electronic monitoring device installed in sampled sample households to record viewing", "Percentage of target population watching a program averaged across its duration", "The total number of unique individuals who watched a channel for at least a minimum threshold time"],
        "A-I, B-II, C-III, D-IV",
        "BARC = industry measurement body; Peoplemeter = electronic monitoring box; TVR = average viewing percentage; Reach = unique viewers.",
        "Matches audience measurement entities and metrics to definitions."),
    mcq("Public vs Private TV", "BARC Composition",
        "Which key industry stakeholders jointly founded and govern the Broadcast Audience Research Council (BARC) India?",
        "Broadcasters (IBDF), Advertisers (ISA), and Advertising Agencies (AAAI)",
        ["The Supreme Court, the Police, and the Defense Ministry",
         "Foreign film production studios and Hollywood actors",
         "Undergraduate college students and primary school teachers"],
        "BARC is a joint industry body uniting the Indian Broadcasting and Digital Foundation (IBDF), Indian Society of Advertisers (ISA), and AAAI.",
        "Identifies the tri-partite industry composition of BARC India."),
    stmt("Public vs Private TV", "DTH vs Cable Distribution",
        "Direct-to-Home (DTH) satellite systems (like Tata Play, Dish TV, DD Free Dish) beam television signals directly from satellites into home dish antennas.",
        "Traditional analog cable TV required local cable operators to lay physical coaxial cables on overhead electricity poles to connect neighborhood homes.",
        "both_true",
        "Both statements accurately explain the technological distinction between satellite DTH systems and terrestrial cable networks.",
        "Distinguishes DTH satellite technology from terrestrial cable networks."),
    ar("Public vs Private TV", "DD Free Dish Phenomenon",
        "Doordarshan's 'DD Free Dish' has grown into the largest Free-to-Air (FTA) satellite television platform in the world.",
        "DD Free Dish requires no monthly recurring subscription fee from viewers, requiring only a one-time purchase of a dish and digital set-top box.",
        "both_correct_explain",
        "Because DD Free Dish is completely free of monthly recurring subscription charges, it has attained massive adoption across rural and semi-urban India.",
        "Explains the explosive growth of DD Free Dish."),
    seq("Public vs Private TV", "TRP Measurement Process (BARC)",
        "Arrange the stages of measuring television audience ratings in methodological sequence:",
        ["Baseline Establishment Survey determining national demographic sample frame", "Installation of electronic Peoplemeters in statistically sampled households", "Household members register personal viewing using remote-control user buttons", "Automated cellular transmission of viewing watermarks and audio data to central servers", "Statistical processing and publication of weekly TRP ratings to broadcasters and advertisers"],
        "I -> II -> III -> IV -> V",
        "BARC process: Baseline survey -> Meter installation -> Member registration -> Data transmission -> Weekly rating publication.",
        "Sequences BARC television audience rating methodology."),
    mcq("Public vs Private TV", "Audio Watermarking in BARC",
        "What modern technological system does BARC utilize to accurately identify the channel being watched on a television set?",
        "Inserting an inaudible acoustic watermark code into the television audio broadcast, detected by the Peoplemeter",
        ["Taking continuous photographic snapshots of the family living room",
         "Measuring the electric current consumed by the television power cord",
         "Having postal inspectors visit homes daily to interview viewers"],
        "BARC uses inaudible watermarking embedded in channel audio streams, which Peoplemeter hardware decodes to record viewing.",
        "Identifies audio watermarking technology used in BARC Peoplemeters."),
    stmt("Public vs Private TV", "Conditional Access System (CAS) & Digitization",
        "The Digital Addressable System (DAS) mandated set-top boxes (STBs) to ensure encryption, transparent channel billing, and addressability.",
        "Before digitization, analog cable operators frequently underreported their actual subscriber numbers to evade paying royalties to broadcasters.",
        "both_true",
        "Both statements are true. Mandatory cable digitization eliminated rampant subscriber under-reporting by analog operators.",
        "Evaluates the impact of mandatory digital cable addressability (DAS)."),
    ar("Public vs Private TV", "Niche vs General Entertainment Channels",
        "General Entertainment Channels (GECs) command significantly higher advertising revenue than niche channels (such as history or lifestyle channels).",
        "GECs cater to broad mass family audiences, achieving significantly higher cumulative reach and Gross Rating Points (GRPs).",
        "both_correct_explain",
        "Because GECs reach vast multi-generational demographics, their mass rating volume attracts the bulk of corporate advertising spend.",
        "Analyzes why GECs dominate television advertising revenue."),
    match("Public vs Private TV", "Distribution Technologies",
        "Match the television delivery technology in List-I with its operational medium in List-II:",
        ["Terrestrial Television", "Cable Television (CATV)", "Direct-to-Home (DTH)", "Internet Protocol TV (IPTV) / OTT"],
        ["Ground-based transmission towers transmitting VHF/UHF waves to rooftop antennas", "Physical coaxial and fiber-optic cables routed by localized multi-system operators", "High-power Ku-band satellite transponders beaming directly to personal dish antennas", "Broadband internet packet-switched networks streaming data to connected screens"],
        "A-I, B-II, C-III, D-IV",
        "Terrestrial = broadcast towers; Cable = physical coaxial/fiber; DTH = satellite to dish; IPTV/OTT = packet-switched internet streaming.",
        "Matches television distribution technologies to transmission media."),
    mcq("Public vs Private TV", "Gross Rating Point (GRP)",
        "In media planning, how is 'Gross Rating Point' (GRP) calculated?",
        "Reach (percentage of target audience exposed) multiplied by Average Frequency of exposure (Reach x Frequency)",
        ["Total number of television sets sold in shopping malls",
         "The electric voltage of the satellite uplink dish",
         "The monthly salary of the television news anchor"],
        "GRP equals Reach percentage multiplied by Average Frequency, representing the total advertising weight of a media schedule.",
        "Defines Gross Rating Point (GRP) in media planning."),
    stmt("Public vs Private TV", "Public Broadcasting Funding Models",
        "Public service broadcasters globally are funded through diverse models such as license fees (BBC in UK), state grants, and commercial ads (Doordarshan).",
        "The BBC in the UK carries thirty minutes of commercial diaper advertisements every hour to fund its investigative journalism.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because the BBC domestic UK public service is funded by a license fee and carries no commercial advertising.",
        "Contrasts public service broadcaster funding models internationally."),
    ar("Public vs Private TV", "Rating Manipulation Vulnerability",
        "Television rating systems based on a small sample of panel households are vulnerable to corrupt manipulation and tampering.",
        "If unscrupulous broadcasters identify and bribe a few dozen sampled panel households to keep their channel switched on, ratings can be artificially inflated.",
        "both_correct_explain",
        "Because sample panel sizes are tiny relative to national populations, bribing a small cluster of panel homes severely distorts ratings.",
        "Analyzes systemic vulnerabilities to TRP tampering and manipulation."),
    mcq("Public vs Private TV", "TRAI's Regulatory Role",
        "Which statutory body regulates broadcasting and cable TV distribution tariffs, channel packaging regulations, and interconnection agreements in India?",
        "Telecom Regulatory Authority of India (TRAI)",
        ["Press Council of India (PCI)",
         "National Disaster Management Authority (NDMA)",
         "Reserve Bank of India (RBI)"],
        "In 2004, the Government of India entrusted the regulation of broadcasting and cable services to TRAI.",
        "Identifies TRAI as the economic regulator of broadcasting and cable distribution."),
    match("Public vs Private TV", "Channel Typologies",
        "Match the channel type in List-I with its primary programming genre in List-II:",
        ["GEC (General Entertainment Channel)", "24x7 News Channel", "Specialty / Niche Channel", "Infotainment Channel"],
        ["Family dramas, reality game shows, comedy, and prime-time soap operas", "Continuous breaking news, live debates, prime-time panel shows, and bulletins", "Dedicated single genres such as sports, music, or cooking/food", "Documentaries blending factual science, nature, and history with entertainment (e.g. Discovery, NatGeo)"],
        "A-I, B-II, C-III, D-IV",
        "GEC = soap operas/reality; News = 24/7 debates/bulletins; Specialty = single genre (sports/music); Infotainment = science/nature docs.",
        "Matches channel categories with core programming styles."),
    seq("Public vs Private TV", "Evolution of TV Audience Measurement in India",
        "Arrange the milestones of television audience measurement in India chronologically:",
        ["Paper diary method administered by Doordarshan audience research unit", "Introduction of electronic Peoplemeters by TAM (Television Audience Measurement) India", "Industry debates regarding sample size and ownership transparency", "Establishment of unified multi-stakeholder body BARC India", "BARC rolls out audio-watermarking technology across thousands of metered households"],
        "I -> II -> III -> IV -> V",
        "Measurement evolution: DD paper diaries -> TAM electronic meters -> Industry debates -> BARC establishment -> Watermarking rollout.",
        "Sequences the evolution of television audience measurement in India."),
    mcq("Public vs Private TV", "Cord-Cutting Phenomenon",
        "What does the contemporary term 'Cord-Cutting' describe in the television ecosystem?",
        "The trend where viewers cancel traditional cable or DTH television subscriptions in favor of internet-based on-demand streaming (OTT) platforms",
        ["Accidentally slicing a television power cord with scissors",
         "The government cutting electrical cables during a thunderstorm",
         "The physical manufacturing of braided wire cables in factories"],
        "Cord-cutting describes consumers abandoning legacy pay-TV (cable/DTH) to consume video content exclusively via broadband OTT services.",
        "Defines cord-cutting in modern television consumption.")
]
'''
slots_code.append(s23)

# Add slots 24 and 25 (already written above)
# We will read them directly from the previous make script or inject clean definitions.
# Let's import the previous s24 and s25 strings!
EOF_MARKER = "END_OF_MAKE"
'''
