# Slots 16 to 20 Generator
s16_to_20 = '''
# ==============================================================================
# Slot 16: Eutrophication & Lake Ecology (Cultural, Algal Blooms, Limnology)
# ==============================================================================
s16_raw = [
    ("mcq", "Cultural Eutrophication Definition",
     "While natural eutrophication is the slow, centuries-long ecological aging of a lake, 'Cultural Eutrophication' refers to:",
     "The drastically accelerated nutrient enrichment and aging of a water body caused by anthropogenic runoff containing fertilizers and domestic sewage",
     ["The introduction of classical cultural art sculptures onto lake shores", "The drying up of a lake caused purely by tectonic earthquake uplift", "The acidification of a lake caused exclusively by volcanic sulfur fumes"],
     "Cultural eutrophication is man-made nutrient pollution (effluents, fertilizers) that turns clear lakes into choked, green swamps within decades."),
    ("stmt", "Limiting Nutrients in Freshwater vs Marine Systems",
     "Phosphorus (orthophosphate) is typically the primary limiting nutrient controlling algal primary productivity in freshwater lakes.",
     "Nitrogen (nitrate/ammonium) is generally the primary limiting nutrient controlling algal blooms in marine and estuarine coastal environments.", 1,
     "Both Statement I and Statement II are correct. Freshwater productivity is usually constrained by phosphorus, while marine ecosystems are primarily nitrogen-limited."),
    ("ar", "Algal Bloom and Nighttime Fish Suffocation",
     "Dense algal blooms frequently cause catastrophic mass fish kills during early morning pre-dawn hours.",
     "At night, in the absence of sunlight, photosynthesis ceases entirely while both massive algal biomass and aquatic bacteria consume dissolved oxygen via cellular respiration.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Pre-dawn DO drops to near-zero levels because algal and microbial respiration consumes oxygen throughout the dark night."),
    ("match", "Trophic Status Classification of Lakes",
     "Match the lake trophic state in List I with its ecological characteristic in List II:",
     [("A", "Oligotrophic"),
      ("B", "Mesotrophic"),
      ("C", "Eutrophic"),
      ("D", "Dystrophic")],
     [("I", "Deep, crystal-clear water, low nutrient levels, low algal biomass, and abundant dissolved oxygen in deep hypolimnion"),
      ("II", "Intermediate nutrient levels, moderate biological productivity, and balanced aquatic communities"),
      ("III", "Shallow water, excessive nutrients, recurrent dense cyanobacterial blooms, and severe benthic oxygen depletion"),
      ("IV", "Brown, tea-colored water rich in humic organic acids with low pH and low primary productivity")],
     "A-I, B-II, C-III, D-IV",
     "Oligotrophic is low nutrient/high DO; mesotrophic is intermediate; eutrophic is high nutrient/bloom-prone; and dystrophic is humic/acidic peat bog lakes."),
    ("mcq", "Cyanobacterial Blooms and Toxins",
     "Common bloom-forming freshwater cyanobacteria like Microcystis aeruginosa and Anabaena release potent hepatotoxins and neurotoxins known as:",
     "Microcystins and Anatoxins",
     ["Aflatoxins and Ochratoxins", "Penicillin and Streptomycin", "DDT and Malathion"],
     "Harmful algal blooms (HABs) of cyanobacteria produce dangerous hepatotoxins (microcystins) and neurotoxins that poison drinking water, livestock, and pets."),
    ("mcq", "Biomanipulation Lake Restoration Strategy",
     "In ecological lake restoration, the top-down 'Biomanipulation' approach to control excessive phytoplankton blooms involves:",
     "Stocking piscivorous game fish (like pike) to reduce zooplanktivorous forage fish, thereby allowing herbivorous zooplankton (Daphnia) to proliferate and graze down algae",
     ["Dumping tons of synthetic chemical herbicides directly into the lake every week", "Pumping the entire lake dry and paving the sediment with concrete", "Eliminating all zooplankton to let algae grow unchecked"],
     "Shapiro's biomanipulation uses food web cascades: piscivores control small fish, releasing large Daphnia grazers that filter clear water by consuming phytoplankton."),
    ("stmt", "Hypoxia and Marine Dead Zones",
     "A marine 'Dead Zone' is an area of an ocean or coastal sea where dissolved oxygen drops below 2.0 mg/L (hypoxia), forcing mobile marine life to flee and killing sessile benthos.",
     "The massive annual dead zone in the northern Gulf of Mexico is driven primarily by agricultural fertilizer runoff carried down the Mississippi River basin.", 1,
     "Both Statement I and Statement II are correct. Hypoxic dead zones occur globally in coastal waters where massive agricultural nutrient runoff fuels blooms and subsequent oxygen crashes."),
    ("seq", "Sequence of Cultural Eutrophication in a Freshwater Lake",
     "Arrange the sequential ecological phases of cultural eutrophication from initial nutrient influx to complete ecosystem degradation:",
     ["Excess agricultural fertilizer runoff and untreated domestic sewage discharge into an oligotrophic lake", "Massive population explosion of surface phytoplankton and cyanobacteria, forming thick algal scums (algal bloom)", "Algal scums block solar irradiance, causing submerged deep-water plants to die from lack of photosynthesis", "Massive dead algal biomass sinks to the benthic zone, where aerobic bacterial decomposition strips the hypolimnion of dissolved oxygen, suffocating fish"],
     "I -> II -> III -> IV",
     "Eutrophication sequence: nutrient influx, algal bloom, sunlight interception and macrophyte death, followed by bacterial decomposition and complete anoxic fish kill."),
    ("mcq", "Loktak Lake Phumdis Ecology",
     "The unique floating islands known as 'Phumdis' in Loktak Lake, Manipur, are composed of:",
     "Heterogeneous masses of dense floating vegetation, organic debris, and soil in varying stages of decomposition supporting wildlife",
     ["Artificial plastic pontoons installed by the tourism department", "Solid volcanic basalt rock fragments floating due to gas pockets", "Compacted municipal solid plastic waste floating on the surface"],
     "Phumdis are thick, floating mats of organic matter, soil, and vegetation unique to Loktak Lake, supporting Keibul Lamjao National Park and Sangai deer."),
    ("ar", "Secchi Disk Transparency and Trophic State",
     "A Secchi disk measures the visual transparency and depth of light penetration in a lake water column.",
     "In highly eutrophic lakes, high concentrations of suspended phytoplankton cells scatter and absorb incoming light, drastically reducing Secchi depth to less than 1 meter.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Secchi disk depth is inversely correlated with algal biomass and trophic state index (TSI)."),
    ("mcq", "Aeration and Destratification Restoration",
     "Why do lake management engineers install mechanical bottom-diffused aeration systems in eutrophic reservoirs during summer?",
     "To inject dissolved oxygen into the hypolimnion, preventing anoxia and halting the chemical release of phosphorus bound in benthic sediments",
     ["To boil the bottom water to kill all fish parasites", "To generate electricity to power municipal street lighting", "To blow floating plastic garbage toward the lakeshore"],
     "Aerating the anoxic bottom sediment prevents ferric iron (Fe3+) reduction to ferrous iron (Fe2+), keeping phosphate locked in sediments and suppressing blooms."),
    ("mcq", "Red Tide Phenomenon in Coastal Waters",
     "Marine 'Red Tides' that discolor coastal waters and produce paralytic shellfish poisoning (PSP) are caused by explosive blooms of which micro-organisms?",
     "Dinoflagellates (e.g., Karenia brevis, Alexandrium)",
     ["Freshwater chlorophyte green algae", "Brown kelp seaweeds", "Symbiotic coral zooxanthellae"],
     "Red tides are toxic blooms of marine dinoflagellates producing potent neurotoxins (brevetoxins, saxitoxins) that accumulate in filter-feeding shellfish."),
    ("match", "Lake Ecological Zones and Characteristics",
     "Match the lake zone in List I with its limnological description in List II:",
     [("A", "Littoral Zone"),
      ("B", "Limnetic Zone"),
      ("C", "Profundal Zone"),
      ("D", "Benthic Zone")],
     [("I", "Shallow, sunlit near-shore region colonized by rooted emergent and submerged aquatic macrophytes"),
      ("II", "Open water surface region away from shore where light penetrates, dominated by phytoplankton and zooplankton"),
      ("III", "Deep, cold, unlit water region below the compensation depth where respiration exceeds photosynthesis"),
      ("IV", "The bottom lake sediment substrate inhabited by decomposers and burrowing benthic invertebrates")],
     "A-I, B-II, C-III, D-IV",
     "Littoral is shallow rooted zone, limnetic is open sunlit water, profundal is deep dark zone, and benthic is bottom sediment."),
    ("mcq", "Weed Infestation in Dal Lake",
     "Dal Lake in Srinagar, Jammu & Kashmir, faces acute ecological degradation and water shrinkage primarily due to cultural eutrophication that fuels the rampant proliferation of:",
     "Azolla, Salvinia natans, and excessive submerged aquatic weed weeds choking the navigation channels",
     ["Marine giant kelp forests", "Terrestrial cactus plants growing in deep water", "Submerged mangrove stilt roots"],
     "Untreated hotel sewage and Dal dweller settlements release nutrients, fueling massive blooms of invasive weeds (Azolla, Salvinia, Ceratophyllum) requiring mechanical harvesting."),
    ("mcq", "Internal Nutrient Loading in Shallow Lakes",
     "Even after completely cutting off external agricultural and sewage inputs to a eutrophic lake, water quality may fail to improve for years due to:",
     "Internal phosphorus loading released from legacy-enriched benthic bottom sediments under anoxic conditions",
     ["Spontaneous thermonuclear fusion occurring within water molecules", "Excessive migration of migratory ducks consuming all lake oxygen", "Atmospheric condensation of pure industrial fertilizer vapor"],
     "Internal nutrient loading occurs when decades of accumulated sedimentary phosphorus recycle back into the water column under summer anoxic conditions."),
    ("stmt", "Oligotrophication Phenomenon",
     "Oligotrophication is the reverse ecological process wherein a nutrient-rich lake transitions back toward a nutrient-poor, clear-water oligotrophic state.",
     "Diversion of sewage discharges, ban on phosphate detergents, and chemical precipitation with aluminum salts (alum) can induce oligotrophication.", 1,
     "Both Statement I and Statement II are correct. Reducing external nutrient inputs and locking sediment phosphorus with alum restores lake clarity."),
    ("mcq", "Compensation Depth in Limnology",
     "In limnology, the 'Compensation Depth' is the specific water depth at which:",
     "The rate of photosynthetic oxygen production by phytoplankton exactly equals the rate of their respiratory oxygen consumption",
     ["The water temperature reaches absolute zero", "The lake floor meets oceanic crust", "Water pressure is high enough to crush submarine hulls"],
     "At the compensation depth (base of the photic zone), net primary production is zero because gross photosynthesis matches respiratory loss."),
    ("seq", "Ecological Succession from Open Lake to Terrestrial Climax",
     "Arrange the stages of hydrosere (hydrarch) ecological succession converting an open freshwater lake into a mature forest:",
     ["Phytoplankton pioneer stage: unicellular algae and diatoms colonize open water", "Submerged and Floating plant stage: rooted macrophytes (Hydrilla, Potamogeton, Nymphaea) trap sediment and shallow the basin", "Reed-swamp and Marsh-meadow stage: amphibious grasses (Typha, Phragmites) build dense peat and organic soil", "Woodland stage progressing to mature mesic Forest Climax community"],
     "I -> II -> III -> IV",
     "Hydrosere succession begins with phytoplankton, moves through submerged/floating plants, reed swamps, marsh meadows, and ends in a climax forest."),
    ("mcq", "Macrophyte Role in Lake Stability",
     "In shallow lakes, extensive beds of submerged aquatic macrophytes (like Chara and Vallisneria) help maintain a 'clear-water state' by:",
     "Stabilizing benthic sediments against wave re-suspension, taking up dissolved nutrients, and providing refuge for zooplankton grazers against fish predation",
     ["Excreting concentrated hydrochloric acid into the water column", "Absorbing all incoming atmospheric sound waves", "Preventing rainwater from entering the lake basin"],
     "Submerged macrophytes stabilize sediment, absorb nutrients, and shelter Daphnia from planktivorous fish, reinforcing the clear-water alternative stable state."),
    ("mcq", "Trophic State Index (TSI) by Carlson",
     "Carlson's Trophic State Index (TSI) is a standard limnological scale (0 to 100) that calculates lake trophic status using three independently measured parameters:",
     "Secchi disk transparency, Chlorophyll-a pigment concentration, and Total Phosphorus concentration",
     ["Water temperature, lake surface area, and wind velocity", "Fish body weight, water hardness, and dissolved sodium", "Atmospheric pressure, cloud cover, and water depth"],
     "Carlson's TSI uses Secchi depth (SD), Chlorophyll-a (Chl-a), and Total Phosphorus (TP) on a logarithmic scale to quantify lake trophic state.")
]

# ==============================================================================
# Slot 17: Heavy Metal Toxicity, Biomagnification & Waterborne Diseases
# ==============================================================================
s17_raw = [
    ("mcq", "Biomagnification vs Bioaccumulation",
     "While bioaccumulation refers to the buildup of a toxicant within a single organism over its lifetime, 'Biomagnification' is defined as:",
     "The progressive increase in concentration of a persistent, non-biodegradable toxicant at each successively higher trophic level along a food chain",
     ["The physical evaporation of toxic chemicals into the upper atmosphere", "The dilution of chemicals as they enter large oceanic gyres", "The rapid biological breakdown of pesticides into harmless sugars by soil bacteria"],
     "Biomagnification (biological amplification) occurs when persistent, lipophilic chemicals (like DDT, mercury) increase in concentration at each trophic step."),
    ("stmt", "DDT Biomagnification in Aquatic Food Chain",
     "In the classic aquatic food chain, DDT concentration starts at 0.003 parts per billion (ppb) in water and magnifies up to 25 parts per million (ppm) in fish-eating birds.",
     "High concentrations of DDT in predatory birds disrupt calcium metabolism, causing eggshell thinning and premature breaking, precipitating sharp bird population crashes.", 1,
     "Both Statement I and Statement II are correct. NCERT highlights the biomagnification of DDT from 0.003 ppb in water to 25 ppm in predatory birds (an amplification of over 10 million times)."),
    ("ar", "Minamata Disease Etiology",
     "Minamata disease is a severe neurological syndrome caused by severe mercury poisoning.",
     "In Minamata Bay, Japan, industrial acetaldehyde wastewater containing inorganic mercury was methylated by aquatic anaerobic bacteria into highly toxic, lipid-soluble methylmercury that biomagnified in fish.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Chisso Corporation's discharges were converted into methylmercury by microbes, causing severe neurological ataxia in fish-eating residents."),
    ("match", "Heavy Metal Pollutants and Associated Diseases",
     "Match the toxic chemical pollutant in List I with its characteristic human disease in List II:",
     [("A", "Methylmercury"),
      ("B", "Cadmium (Cd)"),
      ("C", "Arsenic (As)"),
      ("D", "Nitrate (NO3-)")],
     [("I", "Minamata disease (Neurological ataxia, numbness, blindness)"),
      ("II", "Itai-Itai / Ouch-Ouch disease (Severe osteomalacia, painful bone softening, renal failure)"),
      ("III", "Black Foot disease (Peripheral vascular gangrene, hyperkeratosis, skin cancers)"),
      ("IV", "Methemoglobinemia / Blue Baby Syndrome (Infant cyanosis and asphyxiation)")],
     "A-I, B-II, C-III, D-IV",
     "Mercury causes Minamata; Cadmium causes Itai-Itai bone softening; Arsenic causes Black Foot disease; and Nitrates cause infant Methemoglobinemia."),
    ("mcq", "Itai-Itai Disease History and Mechanism",
     "Itai-Itai disease ('Ouch-Ouch' disease) was first recognized in Toyama Prefecture, Japan, in 1912, caused by chronic poisoning from cadmium released from:",
     "Upstream zinc, lead, and silver mining operations that contaminated river water used for irrigating rice paddy fields",
     ["Nuclear testing in the upper atmosphere contaminating rainwater", "Chemical warfare munitions manufactured during World War I", "Excessive consumption of deep-sea whale blubber"],
     "Mitsui Mining discharged cadmium-rich effluents into the Jinzu River; downstream farmers consumed contaminated rice, suffering excruciating bone softening and fractures."),
    ("mcq", "Arsenic Groundwater Crisis in Bengal Basin",
     "Millions of people in West Bengal, Bihar, and Bangladesh suffer chronic arsenicosis because unconfined and semi-confined groundwater aquifers contain high natural geological arsenic released by:",
     "Reductive dissolution of arsenic-rich iron oxyhydroxides in alluvial sediments under anoxic subsurface conditions",
     ["Underground nuclear detonations conducted in the Bay of Bengal", "Extensive spraying of DDT over tea gardens in Darjeeling", "Direct industrial dumping of arsenic into Himalayan glacier meltwater"],
     "Geogenic arsenic is naturally present in alluvial Ganges-Brahmaputra sediments, leached into shallow tube-well drinking water under anaerobic biogeochemical conditions."),
    ("stmt", "Fluorosis and Permissible Fluoride Limits",
     "According to WHO and Bureau of Indian Standards, the permissible limit of fluoride in drinking water is 1.0 to 1.5 mg/L.",
     "Excessive consumption of fluoride above 1.5 mg/L causes dental fluorosis (mottling of enamel) and crippling skeletal fluorosis (bone deformation and joint stiffness).", 1,
     "Both Statement I and Statement II are correct. Low fluoride (<1 mg/L) prevents caries, but >1.5 mg/L damages teeth and bones, affecting millions across arid Indian states."),
    ("seq", "Biomagnification Steps of DDT across Trophic Levels",
     "Arrange the trophic compartments in increasing order of DDT concentration in an aquatic food chain (NCERT model):",
     ["Water column (approx. 0.003 parts per billion / ppb)", "Phytoplankton and Zooplankton (approx. 0.04 parts per million / ppm)", "Small fish (approx. 0.5 ppm)", "Large predatory fish (approx. 2.0 ppm)", "Fish-eating birds / Osprey (approx. 25.0 ppm)"],
     "I -> II -> III -> IV -> V",
     "DDT magnifies from water (0.003 ppb) to zooplankton (0.04 ppm), small fish (0.5 ppm), large fish (2 ppm), and predatory birds (25 ppm)."),
    ("mcq", "Blue Baby Syndrome (Methemoglobinemia) Pathology",
     "In human infants, consuming drinking water containing nitrate levels exceeding 45 mg/L causes 'Blue Baby Syndrome' because:",
     "Gut bacteria reduce nitrate into nitrite (NO2-), which binds with hemoglobin to form methemoglobin, which cannot transport oxygen, causing tissue suffocation",
     ["Nitrates destroy the infant's digestive enzyme pepsin, causing permanent starvation", "Nitrates cause instantaneous calcification of the pulmonary bronchial tubes", "Nitrates transform blood plasma into pure saline within minutes"],
     "Nitrites oxidize Fe2+ in hemoglobin to Fe3+ (methemoglobin), which cannot bind O2, suffocating the infant and imparting a characteristic bluish skin tinge."),
    ("ar", "Lipophilicity and Biomagnification Prerequisite",
     "Water-soluble pollutants that are rapidly metabolized and excreted do not undergo biomagnification in food chains.",
     "A chemical must be environmentally persistent, mobile, and lipid-soluble (fat-soluble) to accumulate in adipose body tissues across trophic levels.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Hydrophilic toxins are excreted in urine, whereas lipophilic toxins (DDT, PCBs, dioxins) lodge in fat deposits and biomagnify."),
    ("mcq", "Lead Toxicity in Human Body",
     "Chronic lead (Pb) poisoning from contaminated water pipes, leaded paints, or industrial batteries damages the human body primarily by:",
     "Inhibiting hemoglobin synthesis (blocking the enzyme ferrochelatase) and inducing irreversible neurotoxic damage to the central nervous system",
     ["Causing hyper-proliferation of skin melanocytes leading to instant albinism", "Accelerating bone density to 50 times natural human strength", "Transforming human liver tissue into pancreatic endocrine cells"],
     "Lead interferes with heme synthesis, causes microcytic anemia, damages kidneys, and causes severe cognitive delays and behavioral disorders in children."),
    ("mcq", "Polychlorinated Biphenyls (PCBs) Environmental Threat",
     "Polychlorinated Biphenyls (PCBs), historically used as dielectric dielectric fluids in electrical transformers, are hazardous environmental pollutants because they are:",
     "Endocrine-disrupting Persistent Organic Pollutants (POPs) that resist degradation and biomagnify, causing reproductive failure and cancer",
     ["Volatile gases that immediately condense into solid gold on contact with water", "Completely non-toxic nutrients that accelerate aquatic biodiversity growth", "Short-lived organic acids that decompose completely in sunlight within 5 seconds"],
     "PCBs are classic POPs listed under the Stockholm Convention; they are bioaccumulative, carcinogenic, and disrupt endocrine hormonal signaling."),
    ("match", "Waterborne Pathogens and Human Illnesses",
     "Match the waterborne biological pathogen in List I with the disease it causes in List II:",
     [("A", "Vibrio cholerae"),
      ("B", "Salmonella typhi"),
      ("C", "Hepatitis A virus"),
      ("D", "Entamoeba histolytica")],
     [("I", "Cholera (Profuse watery diarrhea and life-threatening rapid dehydration)"),
      ("II", "Typhoid fever (Sustained high fever, intestinal ulceration, and rose spots)"),
      ("III", "Infectious Hepatitis / Jaundice (Acute liver inflammation and yellowing of sclera)"),
      ("IV", "Amoebic dysentery / Amoebiasis (Severe abdominal cramps and blood-stained stool)")],
     "A-I, B-II, C-III, D-IV",
     "Vibrio causes cholera; Salmonella causes typhoid; Hepatitis A attacks the liver causing jaundice; and Entamoeba causes amoebic dysentery."),
    ("mcq", "Nalgonda Technique for Defluoridation",
     "The 'Nalgonda Technique', developed in India by CSIR-NEERI for rural community defluoridation of drinking water, uses which two accessible chemicals?",
     "Alum (Aluminium Sulfate) and Lime (Calcium Hydroxide), followed by bleaching powder disinfection",
     ["Concentrated Nitric acid and Liquid Chlorine", "Sodium Cyanide and Potassium Permanganate", "Activated Charcoal and Heavy Crude Oil"],
     "The Nalgonda technique adds alum (for coagulation/adsorption of fluoride) and lime (for pH buffering), allowing flocculation and sedimentation of fluoride."),
    ("mcq", "Arsenic Removal Plant Technologies",
     "In rural West Bengal and Bihar, community Arsenic Removal Plants (ARPs) attached to hand pumps remove arsenic from groundwater primarily through:",
     "Oxidation of As(III) to As(V) followed by coagulation-coprecipitation with iron (ferric salts) or adsorption on activated alumina",
     ["Boiling the water for 10 seconds in household clay pots", "Passing the water through coarse river sand sieves", "Freezing the groundwater into solid ice cubes"],
     "Arsenic removal requires oxidizing arsenite As(III) to arsenate As(V), followed by coprecipitation with ferric chloride/iron oxides or activated alumina adsorption."),
    ("stmt", "Minamata Convention on Mercury",
     "The Minamata Convention on Mercury is a global legally binding treaty adopted under UNEP in 2013 to protect human health and the environment from anthropogenic mercury releases.",
     "The convention mandates the phased elimination of primary mercury mining and bans the manufacture and export of mercury-containing products like dental amalgams and CFLs.", 1,
     "Both Statement I and Statement II are correct. Named after Minamata Bay, the treaty controls the entire lifecycle of mercury, from mining to industrial use and emissions."),
    ("mcq", "Chromium Toxicity in Leather Tanning",
     "In industrial leather tanning hubs like Kanpur and Ranipet, the discharge of untreated effluent contaminates local aquifers with which highly toxic, carcinogenic heavy metal ion?",
     "Hexavalent Chromium [Cr(VI)]",
     ["Trivalent Iron [Fe(III)]", "Magnesium [Mg(2+)]", "Sodium [Na(+)]"],
     "Leather tanneries use basic chromium sulfate; oxidation produces hexavalent chromium [Cr(VI)], a potent soluble carcinogen and mutagen contaminating groundwater."),
    ("seq", "Sequence of Biological Effects in Human Chronic Arsenicosis",
     "Arrange the progressive clinical stages of chronic arsenic poisoning in human populations drinking contaminated tube-well water over years:",
     ["Ingestion of arsenic-contaminated water over 2 to 5 years with cumulative body burden accumulation", "Appearance of melanosis (spotted dark pigmentation on chest and limbs) and diffuse keratosis", "Hyperkeratosis: thickening, nodular roughness, and painful cracked fissures on palms and soles", "Gangrene of extremities ('Black Foot Disease') and malignant skin, bladder, and lung carcinomas"],
     "I -> II -> III -> IV",
     "Arsenicosis progresses from asymptomatic accumulation to skin melanosis, palm/sole keratosis, and finally terminal vascular gangrene and systemic internal cancers."),
    ("mcq", "Endocrine Disrupting Chemicals (EDCs) in Water",
     "Chemicals commonly found in plasticizers and cosmetics (such as Bisphenol A / BPA and Phthalates) that mimic natural hormones and disrupt aquatic wildlife reproduction are termed:",
     "Endocrine Disrupting Chemicals (EDCs)",
     ["Photosynthetic inhibitors", "Inorganic coagulants", "Aerobic biodigesters"],
     "EDCs mimic or block natural hormones (like estrogen), causing feminization of male fish, low sperm counts, and reproductive failures in aquatic wildlife."),
    ("mcq", "Stockholm Convention Dirty Dozen",
     "Adopted in 2001, the Stockholm Convention on Persistent Organic Pollutants (POPs) initially targeted an elite group of 12 highly hazardous, biomagnifying chemicals known as the:",
     "'The Dirty Dozen' (including DDT, Aldrin, Dieldrin, Chlordane, PCBs, Dioxins, and Furans)",
     ["'The Clean Twelve'", "'The Agricultural Shield'", "'The Ozone Twelve'"],
     "The 'Dirty Dozen' POPs are chlorinated hydrocarbons known for environmental persistence, long-range transboundary transport, bioaccumulation, and high toxicity.")
]
'''

with open('scripts/subject_generators/make_evs_s16_20.py', 'w') as f:
    f.write(s16_to_20)

print("make_evs_s16_20.py written.")
