# Slots 36 to 40 Generator
s36_to_40 = '''
CH_TREATIES = "International Environmental Treaties and Indian Policy"

# ==============================================================================
# Slot 36: Environmental Impact Assessment (EIA) Framework
# ==============================================================================
s36_raw = [
    ("mcq", "EIA Statutory Origin in India",
     "In India, Environmental Impact Assessment (EIA) was made statutory under which parent environmental legislation following the landmark EIA Notification of 1994 (later superseded by the comprehensive EIA Notification of 2006)?",
     "The Environment (Protection) Act, 1986 (EPA 1986)",
     ["The Wildlife Protection Act, 1972", "The Indian Forest Act, 1927", "The Factories Act, 1948"],
     "EIA was first made mandatory in India under Section 3 of the Environment (Protection) Act 1986 in 1994, comprehensively restructured by the EIA Notification of 2006."),
    ("stmt", "Category A vs Category B Projects in EIA 2006",
     "Under the EIA Notification 2006, Category 'A' development projects require prior environmental clearance from the central Ministry of Environment, Forest and Climate Change (MoEFCC).",
     "Category 'B' projects are appraised at the state level by the State Environmental Impact Assessment Authority (SEIAA) and State Expert Appraisal Committee (SEAC).", 1,
     "Both Statement I and Statement II are correct. Category A projects are cleared at the Central MoEFCC level; Category B projects are processed at the State SEIAA level."),
    ("ar", "Four Sequential Stages of Environmental Clearance Process",
     "Under the EIA Notification 2006, the environmental clearance process for new projects comprises four sequential stages: Screening, Scoping, Public Consultation, and Appraisal.",
     "Scoping is the stage where the Expert Appraisal Committee (EAC) formulates comprehensive Terms of Reference (ToR) addressing all potential environmental impacts.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The 4 formal statutory stages of EIA are Screening (only for Category B), Scoping (ToR determination), Public Consultation, and final Appraisal."),
    ("match", "EIA Clearance Stages and Operational Functions",
     "Match the EIA clearance stage in List I with its regulatory purpose in List II:",
     [("A", "Stage 1: Screening"),
      ("B", "Stage 2: Scoping"),
      ("C", "Stage 3: Public Consultation"),
      ("D", "Stage 4: Appraisal")],
     [("I", "Determines whether a Category B project requires an EIA study (Category B1) or does not require an EIA (Category B2)"),
      ("II", "Formulation of comprehensive Terms of Reference (ToR) specifying all baseline environmental monitoring requirements"),
      ("III", "Conducting a public hearing by the State Pollution Control Board to address local community and stakeholder concerns"),
      ("IV", "Detailed scientific scrutiny of the final EIA report and public hearing proceedings by the Expert Appraisal Committee (EAC)")],
     "A-I, B-II, C-III, D-IV",
     "Screening categorizes B1 vs B2; Scoping drafts ToRs; Public Consultation records community concerns; and Appraisal evaluates reports for clearance approval."),
    ("mcq", "Category B1 vs B2 Projects Distinction",
     "In the EIA screening stage conducted by the State Expert Appraisal Committee (SEAC), how are Category B1 projects distinguished from Category B2 projects?",
     "Category B1 projects require a full, formal Environmental Impact Assessment (EIA) study and public hearing, whereas Category B2 projects do not require an EIA study",
     ["Category B1 projects are approved by the military, while B2 projects are approved by banks", "Category B1 projects are located exclusively on the moon", "Category B2 projects are 100% exempt from all national environmental laws forever"],
     "Category B projects are screened: B1 requires full EIA and public hearing; B2 (smaller scale, low pollution potential) is appraised without a full EIA report."),
    ("mcq", "Public Hearing Mandate and Execution in EIA",
     "Who is statutory responsible for conducting the mandatory on-site 'Public Hearing' component of the public consultation stage under the EIA Notification 2006?",
     "The concerned State Pollution Control Board (SPCB) or Union Territory Pollution Control Committee, presided over by the District Collector or District Magistrate",
     ["The private commercial project developer's marketing public relations team", "A private foreign investment banking consulting firm", "The local village high school principal"],
     "The public hearing must be conducted by the SPCB within 45 days, presided over by the District Magistrate/Collector, and video-recorded to ensure transparency."),
    ("stmt", "Projects Exempted from Public Hearing under EIA 2006",
     "Certain categories of projects are statutorily exempted from the requirement of a public hearing under the EIA Notification 2006.",
     "Exempted projects include national defense or security projects, strategic offshore installations, expansion of projects within existing notified industrial estates, and small Category B2 projects.", 1,
     "Both Statement I and Statement II are correct. Strategic defense infrastructure and activities inside pre-cleared industrial zones are exempt from public hearings."),
    ("seq", "Sequential Workflow of the EIA Statutory Clearance Cycle",
     "Arrange the sequential statutory steps a project proponent must complete to secure Environmental Clearance (EC) in India:",
     ["Online submission of Form-1 and pre-feasibility project report on the MoEFCC PARIVESH portal", "Scoping: issuance of formalized Terms of Reference (ToR) by the Expert Appraisal Committee (EAC)", "Preparation of Draft EIA report based on 3-season baseline environmental data collection", "Conducting the mandatory Public Hearing and submission of the Final EIA report addressing public concerns to EAC for final Appraisal"],
     "I -> II -> III -> IV",
     "EC workflow: PARIVESH Form-1 submission, Scoping/ToR issuance, baseline data collection/Draft EIA, followed by Public Hearing and final EAC Appraisal."),
    ("mcq", "Baseline Environmental Data Monitoring Period",
     "To prepare a robust Environmental Impact Assessment (EIA) report in India, environmental consultants are standardly required to collect primary baseline environmental data (air, water, noise, ecology) across:",
     "One complete season (three months, non-monsoon), or all four seasons for complex projects",
     ["A single 24-hour observation period on a Sunday", "Ten consecutive calendar years without interruption", "Only during heavy monsoon flood weeks"],
     "Standard EIA guidelines require one full non-monsoon season of primary field monitoring (winter, pre-monsoon, or post-monsoon), while sensitive projects monitor year-round."),
    ("ar", "Environmental Management Plan (EMP) Importance",
     "An Environmental Management Plan (EMP) is the most critical actionable chapter of a final Environmental Impact Assessment report.",
     "The EMP details the specific engineering mitigation measures, budget allocations, institutional responsibilities, and post-project monitoring protocols to mitigate environmental damage.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Without an enforceable EMP, EIA remains merely descriptive; the EMP binds the project proponent to specific mitigation commitments."),
    ("mcq", "PARIVESH Web Portal Role",
     "What is the function of the 'PARIVESH' (Pro-Active and Responsive facilitation by Interactive, Virtuous and Environmental Single-window Hub) portal launched by MoEFCC?",
     "A centralized web-based single-window workflow system for online submission, tracking, and processing of all Environment, Forest, Wildlife, and CRZ clearances",
     ["A commercial travel booking portal for vacations in national parks", "A government shopping website for purchasing industrial timber", "A digital tax filing portal for municipal property taxes"],
     "PARIVESH provides transparent, end-to-end digital tracking of environmental, forest, wildlife, and coastal regulation zone (CRZ) clearances."),
    ("mcq", "Strategic Environmental Assessment (SEA)",
     "How does a 'Strategic Environmental Assessment' (SEA) differ fundamentally from a traditional project-level Environmental Impact Assessment (EIA)?",
     "SEA assesses the environmental and sustainability impacts of broader macro policies, plans, and regional development programs, whereas EIA focuses on a single specific localized project",
     ["SEA is conducted exclusively by the military, while EIA is conducted by farmers", "SEA applies only to space exploration, while EIA applies to farming", "There is zero difference; both terms are identical"],
     "SEA evaluates cumulative environmental impacts of overarching policies, sector plans (e.g. National Highway Plan), and legislative programs upstream before individual projects are designed."),
    ("match", "EIA Terminology and Associated Documents",
     "Match the EIA document/term in List I with its regulatory definition in List II:",
     [("A", "Terms of Reference (ToR)"),
      ("B", "Form-1"),
      ("C", "Executive Summary"),
      ("D", "Half-Yearly Compliance Report")],
     [("I", "Mandated blueprint specifying the exact scope of environmental studies, parameters, and baseline monitoring required for the project"),
      ("II", "Standardized statutory initial application form disclosing project location, capacity, resource requirements, and proposed activities"),
      ("III", "Non-technical summary translated into local vernacular language made available to the public prior to public hearing"),
      ("IV", "Mandatory report submitted every 6 months by project developers detailing compliance with environmental clearance conditions")],
     "A-I, B-II, C-III, D-IV",
     "ToR defines study scope; Form-1 is the initial clearance application; Executive Summary is the public non-technical document; and Compliance Reports track conditions every 6 months."),
    ("mcq", "Post-Environmental Clearance Monitoring",
     "Under the EIA Notification 2006, after securing Environmental Clearance, how frequently must the project proponent submit self-compliance monitoring reports to the MoEFCC Regional Office?",
     "Every six months (on 1st June and 1st December of each calendar year)",
     ["Once every 10 years", "Every week on Monday", "Never; clearance is permanent with zero monitoring"],
     "Project proponents must submit half-yearly compliance reports on clearance conditions to MoEFCC Regional Offices and State Pollution Control Boards."),
    ("mcq", "Cumulative Impact Assessment (CIA) in River Basins",
     "Why do environmental scientists insist on a basin-wide 'Cumulative Impact Assessment' (CIA) rather than standalone project EIAs when evaluating multiple hydroelectric dams on a single river (such as the Bhagirathi or Alaknanda)?",
     "Because a series of cascading dams collectively dries up continuous river stretches, destroys riverine connectivity, and disrupts regional sediment transport far beyond the footprint of any single dam",
     ["Because individual dams do not use water to generate electricity", "Because cascading dams cause volcanic eruptions in river valleys", "Because river water turns into solid granite when passing through a turbine"],
     "Standalone project EIAs ignore cumulative ecosystem fragmentation; cascading dams collectively divert rivers into tunnels for tens of kilometers, destroying continuous river ecology."),
    ("stmt", "National Green Tribunal (NGT) Powers over Environmental Clearances",
     "Under Section 16 of the National Green Tribunal Act, 2010, an aggrieved citizen can appeal against any grant or rejection of Environmental Clearance.",
     "The NGT has judicial powers to quash illegal environmental clearances, halt industrial construction, and mandate independent multi-disciplinary impact audits.", 1,
     "Both Statement I and Statement II are correct. The NGT serves as an appellate body reviewing the merits and legality of environmental clearances issued by MoEFCC/SEIAA."),
    ("mcq", "Draft EIA Notification 2020 Controversies",
     "The proposed Draft EIA Notification 2020 faced widespread public protest and scientific criticism across India primarily because it proposed:",
     "Post-facto environmental clearances for projects that began construction illegally without prior approval, and weakened public consultation exemptions",
     ["Banning all private industrial manufacturing across India permanently", "Requiring that 100% of all Indian citizens obtain EIA degrees", "Mandating that all factories be operated by wild animals"],
     "Draft EIA 2020 sparked intense controversy for allowing post-facto approvals (ex-post regularisation of illegal projects) and expanding categories exempt from public hearings."),
    ("seq", "Public Hearing Procedural Sequence under EIA 2006",
     "Arrange the chronological procedural steps involved in conducting a statutory EIA Public Hearing:",
     ["Project proponent submits Draft EIA report and non-technical Executive Summary in English and local vernacular language to SPCB", "SPCB publishes a formal public notice in two leading local newspapers giving at least 30 days notice specifying the hearing date, venue, and time", "Conducting the public hearing at the project site or district headquarters, presided over by the District Magistrate, with open citizen testimony and video recording", "Preparation of formal minutes reflecting all public objections, signed by the DM, and forwarded within 8 days to the MoEFCC / SEIAA"],
     "I -> II -> III -> IV",
     "Public hearing sequence: draft report submission, 30-day minimum newspaper notice, on-site public proceedings presided by DM, and signed minutes transmission."),
    ("mcq", "Carrying Capacity-Based Regional Planning",
     "Unlike single-project EIA which evaluates an isolated factory, a 'Carrying Capacity-Based Developmental Plan' (such as the Doon Valley ecological zoning):",
     "Determines the maximum sustainable industrial and demographic load an entire regional watershed can support without irreversible ecological collapse",
     ["Mandates the construction of high-speed motor racing tracks across all mountain ridges", "Eliminates all human settlements from the entire state within 24 hours", "Calculates only the maximum weight of freight trains crossing a bridge"],
     "Regional carrying capacity planning evaluates total supportive capacity (resource availability) and assimilative capacity (pollution absorption) to zone development sustainably."),
    ("mcq", "Environmental Clearance Validity Period for Mining Projects",
     "Under the EIA Notification 2006 (as amended), what is the maximum statutory validity period of an Environmental Clearance granted for a commercial mining project?",
     "For the project life as estimated by the EAC, up to a maximum of 30 to 50 years",
     ["For exactly 6 months", "For 500 years with zero renewal requirements", "For 24 hours"],
     "Environmental clearance for mining projects is granted for the operational life of the mine, subject to a maximum period (recently extended up to 50 years with periodic audits).")
]

# ==============================================================================
# Slot 37: Climate Change Science & Global Warming (Greenhouse Effect, IPCC, GWP)
# ==============================================================================
s37_raw = [
    ("mcq", "Natural Greenhouse Effect Temperature Equilibrium",
     "Without the natural atmospheric greenhouse effect (trapping thermal infrared radiation by water vapor, CO2, and methane), what would be the average surface temperature of the Earth?",
     "Approximately -18 degrees Celsius (0 degrees Fahrenheit), rendering Earth a frozen, lifeless planet",
     ["Approximately +50 degrees Celsius", "Absolute zero (-273 degrees Celsius)", "Exactly +15 degrees Celsius (current average)"],
     "Without natural greenhouse gases, Earth's average temperature would drop by 33 C, from comfortable +15 C down to freezing -18 C."),
    ("stmt", "Incoming Solar vs Outgoing Terrestrial Radiation",
     "Solar radiation arrives at Earth predominantly as shortwave radiation (ultraviolet and visible light).",
     "The Earth's surface absorbs solar energy and re-emits it back toward space as longwave thermal infrared radiation.", 1,
     "Both Statement I and Statement II are correct. Greenhouse gases are transparent to incoming shortwave solar radiation but absorb and re-radiate outgoing longwave infrared radiation."),
    ("ar", "Water Vapor as Most Abundant Greenhouse Gas",
     "Water vapor (H2O) is the single most abundant greenhouse gas contributing to the natural greenhouse effect on Earth.",
     "However, anthropogenic climate change is driven primarily by Carbon Dioxide (CO2) and Methane because their atmospheric lifetimes are long and their concentrations are directly controlled by human emissions.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Water vapor has a brief atmospheric residence time (~9 days) acting as an amplifying feedback, whereas CO2 persists for centuries."),
    ("match", "Greenhouse Gases and Global Warming Potentials (GWP)",
     "Match the greenhouse gas in List I with its approximate 100-year Global Warming Potential (GWP) relative to CO2 in List II (IPCC AR6 benchmarks):",
     [("A", "Carbon Dioxide (CO2)"),
      ("B", "Methane (CH4)"),
      ("C", "Nitrous Oxide (N2O)"),
      ("D", "Sulfur Hexafluoride (SF6)")],
     [("I", "1 (The universal baseline standard)"),
      ("II", "27 to 30 (approx. 28 times more heat-trapping per unit mass than CO2)"),
      ("III", "265 to 273 (approx. 270 times more heat-trapping than CO2)"),
      ("IV", "24,300 (one of the most potent synthetic greenhouse gases known)")],
     "A-I, B-II, C-III, D-IV",
     "GWP benchmarks: CO2 = 1, CH4 ~ 28, N2O ~ 273, and synthetic SF6 (electrical insulator gas) = 24,300."),
    ("mcq", "Keeling Curve and Mauna Loa Observatory",
     "Initiated by Charles David Keeling in 1958 at the Mauna Loa Observatory in Hawaii, the 'Keeling Curve' provides the continuous gold-standard record demonstrating:",
     "The relentless rise of atmospheric Carbon Dioxide (CO2) from 315 ppm in 1958 to over 420 ppm today, superimposed on annual seasonal photosynthetic oscillations",
     ["The rapid cooling of the Pacific Ocean into permanent sea ice", "The complete depletion of all nitrogen gas from the atmosphere", "The linear decrease in global automobile manufacturing"],
     "The Keeling Curve tracks the iconic rise of atmospheric CO2 from ~315 ppm to >420 ppm, alongside annual sawtooth seasonal fluctuations driven by Northern Hemisphere vegetation."),
    ("mcq", "Intergovernmental Panel on Climate Change (IPCC) Foundation",
     "The Intergovernmental Panel on Climate Change (IPCC), awarded the Nobel Peace Prize in 2007, was established in 1988 by which two international United Nations bodies?",
     "World Meteorological Organization (WMO) and United Nations Environment Programme (UNEP)",
     ["World Trade Organization (WTO) and International Monetary Fund (IMF)", "North Atlantic Treaty Organization (NATO) and INTERPOL", "International Atomic Energy Agency (IAEA) and FAO"],
     "The IPCC was created in 1988 by WMO and UNEP to provide governments with objective scientific assessments of climate change, impacts, and response options."),
    ("stmt", "Albedo Positive Feedback Mechanism",
     "The Ice-Albedo feedback is a classic self-reinforcing positive feedback loop accelerating Arctic warming.",
     "As global warming melts bright white sea ice (high albedo ~80%), it exposes darker open ocean water (low albedo ~10%), which absorbs more solar heat, melting more ice.", 1,
     "Both Statement I and Statement II are correct. Melting ice lowers regional albedo, converting reflective ice into heat-absorbing open water and accelerating Arctic amplification."),
    ("seq", "Chemical Sequence of Anthropogenic Ocean Acidification",
     "Arrange the chemical reaction steps illustrating how rising atmospheric CO2 causes ocean acidification:",
     ["Anthropogenic fossil fuel emissions elevate atmospheric CO2 concentrations above 420 ppm", "Gaseous CO2 dissolves across the ocean surface, forming weak Carbonic Acid: CO2 + H2O <-> H2CO3", "Carbonic acid dissociates into Bicarbonate and free Hydrogen ions: H2CO3 <-> H+ + HCO3-, driving down oceanic pH", "Excess free Hydrogen ions bind with free Carbonate ions (CO3(2-)), depleting the carbonate saturation needed by corals and shellfish to build calcium carbonate (CaCO3) shells"],
     "I -> II -> III -> IV",
     "Ocean acidification sequence: atmospheric CO2 dissolution, carbonic acid formation, proton release lowering pH, and carbonate ion depletion starving calcifying organisms."),
    ("mcq", "Ocean Acidification and Coral Aragonite Calcification",
     "Why does ocean acidification (ocean pH declining by 0.1 units, representing a 30% increase in acidity since industrialization) threaten marine coral reefs?",
     "It reduces the saturation state of aragonite (a soluble form of CaCO3), making it energetically difficult for corals to secrete calcium carbonate skeletons and dissolving existing reef structures",
     ["It causes ocean water to boil at 30 degrees Celsius", "It turns coral reefs into combustible coal reserves", "It causes all marine fish to lose their eyesight immediately"],
     "Acidification robs seawater of carbonate ions (CO3(2-)), corroding delicate aragonite coral skeletons and pteropod shells in a process termed 'osteoporosis of the sea'."),
    ("ar", "Permafrost Thaw Methane Tipping Point",
     "Thawing of Arctic permafrost is recognized by the IPCC as a dangerous planetary climate 'tipping point'.",
     "Permafrost soils store an estimated 1,500 billion tons of ancient organic carbon; microbial decomposition upon thawing releases immense volumes of methane and CO2, driving runaway feedback warming.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Thawing permafrost awakens dormant anaerobic microbes that digest organic matter, releasing massive methane pulses independent of direct human emissions."),
    ("mcq", "Radiative Forcing Definition (IPCC)",
     "In IPCC climate science, 'Radiative Forcing' (measured in Watts per square meter, W/m2) is defined as:",
     "The net change in the energy balance of the Earth-atmosphere system (downward incoming minus upward outgoing radiation) caused by an external climate driver like greenhouse gases",
     ["The mechanical force exerted by falling raindrops on agricultural soil", "The gravitational pull between the Earth and passing comets", "The electrical voltage measured across national power grids"],
     "Radiative forcing measures the energy imbalance imposed on Earth: positive forcing (from greenhouse gases, ~+2.72 W/m2) warms the planet, while negative forcing (aerosols) cools it."),
    ("mcq", "Shared Socioeconomic Pathways (SSPs) in IPCC AR6",
     "In the IPCC Sixth Assessment Report (AR6, 2021–2023), future climate projections are modeled using 'Shared Socioeconomic Pathways' (SSPs). Which scenario represents the high-mitigation 'Sustainability' pathway?",
     "SSP1-1.9 and SSP1-2.6 (Low challenges to mitigation and adaptation, achieving Net Zero CO2 around 2050)",
     ["SSP5-8.5 (Fossil-fueled development with rampant emissions)", "SSP3-7.0 (Regional rivalry and high fragmentation)", "SSP2-4.5 (Middle of the road pathway)"],
     "SSP1 represents the green sustainability pathway with aggressive decarbonization, aiming to limit warming close to 1.5 C by end of century."),
    ("match", "Anthropogenic Greenhouse Gases and Primary Emission Sources",
     "Match the greenhouse gas in List I with its primary anthropogenic source in List II:",
     [("A", "Carbon Dioxide (CO2)"),
      ("B", "Methane (CH4)"),
      ("C", "Nitrous Oxide (N2O)"),
      ("D", "Fluorinated Gases (HFCs / SF6)")],
     [("I", "Fossil fuel combustion (coal, oil, gas) for electricity and transport, and deforestation"),
      ("II", "Enteric fermentation in livestock cattle, flooded paddy fields, landfills, and fossil fuel venting"),
      ("III", "Synthetic nitrogenous agricultural fertilizers and chemical manufacturing of nitric/adipic acid"),
      ("IV", "Refrigeration, air conditioning, foam blowing, and high-voltage electrical switchgear")],
     "A-I, B-II, C-III, D-IV",
     "CO2 stems from fossil fuels/deforestation; CH4 from cattle, paddy, landfills; N2O from fertilizers; and F-gases from refrigeration and switchgear."),
    ("mcq", "Thermal Expansion and Sea Level Rise",
     "Global sea level rise (currently accelerating above 3.7 mm/year) is driven primarily by which two physical phenomena?",
     "Thermal expansion of seawater as oceans warm, and the melting of land-based ice sheets and glaciers (Greenland, Antarctica, and mountain glaciers)",
     ["Melting of floating Arctic sea ice only", "Expansion of plastic garbage floating on ocean surfaces", "Increased commercial naval ship traffic displacing water"],
     "Sea level rise is driven by thermal expansion (warm water occupies more volume) and mass transfer of melting land-based ice into oceans (melting floating ice does not change sea level)."),
    ("mcq", "Climate Tipping Points Concept",
     "In Earth system science, a 'Climate Tipping Point' is defined as:",
     "A critical threshold where a small additional perturbation triggers a large, self-perpetuating, and often irreversible change in a planetary system (e.g. shutdown of Atlantic Meridional Overturning Circulation)",
     ["The exact date when all fossil fuels become free of cost", "The moment when a thermometer reaches 100 degrees Celsius", "The point when an airplane lands on a runway"],
     "Tipping points (dieback of Amazon, Greenland ice sheet collapse, AMOC shutdown) are thresholds where positive feedbacks drive irreversible, catastrophic shifts."),
    ("stmt", "IPCC Special Report on 1.5 C Warming (SR15)",
     "The IPCC Special Report on Global Warming of 1.5 C (2018) warned that limiting warming to 1.5 C rather than 2.0 C would avoid catastrophic climate risks.",
     "The report established that limiting warming to 1.5 C requires global net anthropogenic CO2 emissions to decline by about 45% from 2010 levels by 2030, reaching 'Net Zero' around 2050.", 1,
     "Both Statement I and Statement II are correct. SR15 proved that every fraction of a degree matters; 2 C warming exposes hundreds of millions more people to climate hazards than 1.5 C."),
    ("mcq", "Carbon Budget Concept",
     "The 'Global Carbon Budget' represents:",
     "The finite cumulative amount of carbon dioxide emissions that humanity can emit while maintaining a given probability of limiting global warming to a specific threshold (e.g., 1.5 C)",
     ["The total monetary budget allocated by the Ministry of Finance for coal mining", "The total amount of carbon dioxide consumed by household soda machines", "The price of refined sugar in international commodities trading"],
     "The carbon budget is the remaining quota of CO2 humanity can burn before permanently locking in 1.5 C or 2.0 C warming (~250 Gt CO2 remaining for 1.5 C)."),
    ("seq", "Milestones in Scientific Discovery of Climate Change",
     "Arrange the pioneering scientific discoveries in climate science in historical order:",
     ["Joseph Fourier discovers the Earth's natural greenhouse effect and atmospheric heat trapping (1824)", "Eunice Newton Foote and John Tyndall identify CO2 and water vapor as the gases that absorb infrared radiation (1850s)", "Svante Arrhenius calculates the first quantitative estimate of global warming caused by doubling atmospheric CO2 from coal burning (1896)", "Charles David Keeling begins continuous baseline atmospheric CO2 monitoring at Mauna Loa Observatory (1958)"],
     "I -> II -> III -> IV",
     "Climate science history: Fourier discovered the greenhouse effect (1824), Foote/Tyndall identified the gases (1850s), Arrhenius calculated CO2 warming (1896), and Keeling began continuous monitoring (1958)."),
    ("mcq", "Atlantic Meridional Overturning Circulation (AMOC) Collapse Risk",
     "Why do climate modelers monitor the 'Atlantic Meridional Overturning Circulation' (AMOC, including the Gulf Stream) with acute concern?",
     "Massive influxes of cold freshwater from melting Greenland ice dilute North Atlantic salinity, which could weaken or collapse the oceanic conveyor belt, destabilizing global monsoon and weather patterns",
     ["AMOC produces electricity that powers the entire North American continent", "AMOC carries all industrial chemical wastewater from the Arctic into Antarctica", "AMOC prevents the Atlantic ocean from evaporating into outer space"],
     "Greenland meltwater lowers seawater density, halting the sinking of dense saline water that drives the global thermohaline conveyor, risking severe monsoon disruptions."),
    ("mcq", "Short-Lived Climate Pollutants (SLCPs)",
     "Targeting 'Short-Lived Climate Pollutants' (SLCPs, such as Methane, Black Carbon, Tropospheric Ozone, and Hydrofluorocarbons) provides immediate near-term climate benefits because:",
     "They have relatively short atmospheric lifespans (from days to a decade); slashing their emissions delivers rapid cooling and public health gains while long-term CO2 decarbonization unfolds",
     ["They completely eliminate the need to ever reduce fossil fuel coal emissions", "They have zero heat-trapping capacity in the atmosphere", "They are naturally destroyed whenever an automobile accelerates"],
     "SLCPs (methane, soot, HFCs) have high warming potency but short atmospheric residence; rapid cuts avoid ~0.6 C near-term warming while saving millions of lives from air pollution.")
]

# ==============================================================================
# Slot 38: International Climate Treaties & Carbon Markets (Kyoto, Paris, COP26)
# ==============================================================================
s38_raw = [
    ("mcq", "UNFCCC Adoption and Ultimate Objective",
     "Adopted at the 1992 Rio Earth Summit, the United Nations Framework Convention on Climate Change (UNFCCC) established which ultimate objective in Article 2?",
     "To achieve the stabilization of greenhouse gas concentrations in the atmosphere at a level that would prevent dangerous anthropogenic interference with the climate system",
     ["To eliminate all national sovereign borders across all developing nations", "To mandate that all automobiles worldwide be converted into coal-burning steam engines", "To ban all agricultural farming worldwide by the year 2000"],
     "Article 2 of UNFCCC sets the foundational goal: stabilizing greenhouse gases within a timeframe sufficient to allow ecosystems to adapt naturally and ensure sustainable food production."),
    ("stmt", "Kyoto Protocol Annex Division Architecture",
     "The Kyoto Protocol (adopted in 1997, entered into force in 2005) established legally binding emissions reduction targets exclusively for developed industrialized nations (Annex I parties).",
     "Developing countries, including India and China (Non-Annex I parties), had zero binding numerical emissions reduction commitments during the first commitment period.", 1,
     "Both Statement I and Statement II are correct. Under the principle of CBDR, Kyoto mandated an average 5.2% emissions cut for Annex I developed nations, exempting developing nations."),
    ("ar", "Clean Development Mechanism (CDM) Under Kyoto Protocol",
     "The Clean Development Mechanism (CDM) under Article 12 of the Kyoto Protocol allowed developed Annex I nations to invest in emission-reduction projects in developing Non-Annex I countries.",
     "Annex I nations earned tradeable Certified Emission Reduction (CER) carbon credits from developing country projects to meet their own Kyoto compliance targets cost-effectively.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). CDM incentivized clean technology transfer to developing nations (like renewable energy in India) while providing flexible compliance credits to Annex I states."),
    ("match", "Kyoto Protocol Flexibility Mechanisms",
     "Match the Kyoto Protocol market mechanism in List I with its operational definition in List II:",
     [("A", "Clean Development Mechanism (CDM)"),
      ("B", "Joint Implementation (JI)"),
      ("C", "International Emissions Trading (IET)"),
      ("D", "Certified Emission Reduction (CER)")],
     [("I", "Annex I country invests in emission reduction projects in a Non-Annex I developing country (Article 12)"),
      ("II", "Annex I country invests in emission reduction projects in another Annex I country (Article 6)"),
      ("III", "Trading of assigned amount units (AAUs) between Annex I countries with emissions targets (Article 17)"),
      ("IV", "Standard unit issued under CDM representing one metric ton of CO2 equivalent reduced or sequestered")],
     "A-I, B-II, C-III, D-IV",
     "CDM is developed-developing; JI is developed-developed; IET is cap-and-trade allowance trading; and a CER represents 1 metric ton of CO2 equivalent."),
    ("mcq", "Paris Agreement Temperature Goals (Article 2)",
     "Adopted at COP21 in December 2015, the landmark Paris Agreement legally commits all global parties to holding the increase in global average temperature to:",
     "Well below 2 degrees Celsius above pre-industrial levels and pursuing efforts to limit the temperature increase to 1.5 degrees Celsius above pre-industrial levels",
     ["Exactly 5 degrees Celsius above pre-industrial levels", "Zero degrees Celsius total atmospheric temperature", "Allowing temperature to fluctuate freely without any limits"],
     "Article 2.1(a) of the Paris Agreement sets the global temperature goal: 'well below 2 C' while striving for the safer '1.5 C' ceiling."),
    ("mcq", "Nationally Determined Contributions (NDCs) Dynamic",
     "Under the Paris Agreement architecture, how do 'Nationally Determined Contributions' (NDCs) operate to drive global climate action?",
     "Each party self-determines and communicates bottom-up national climate mitigation and adaptation targets every 5 years, subject to a mandatory 'ratchet mechanism' requiring progressive ambition",
     ["Top-down numerical quotas are legally imposed on all countries by the UN Secretary-General with military enforcement", "Countries are prohibited from reducing emissions without paying royalties to the World Bank", "Only island nations are allowed to submit climate plans"],
     "NDCs replace Kyoto's top-down targets with a bottom-up pledge system, backed by a 'ratchet mechanism' requiring each successive 5-year NDC to represent an escalation of ambition."),
    ("stmt", "Global Stocktake (GST) under Paris Agreement",
     "Article 14 of the Paris Agreement mandates a 'Global Stocktake' (GST) to take place every five years starting in 2023.",
     "The Global Stocktake assesses the world's collective progress toward achieving the long-term goals of the agreement and informs parties in updating their subsequent NDCs.", 1,
     "Both Statement I and Statement II are correct. The first Global Stocktake concluded at COP28 in Dubai (2023), calling for 'transitioning away from fossil fuels in energy systems'."),
    ("seq", "Chronological Milestones in International Climate Change Diplomacy",
     "Arrange these landmark international climate treaty milestones in chronological order:",
     ["Adoption of the UNFCCC at the Rio Earth Summit in Brazil (1992)", "Adoption of the Kyoto Protocol establishing legally binding Annex I emission cuts (1997)", "Adoption of the Paris Agreement introducing universal NDCs and 1.5 C goal (2015)", "First Global Stocktake concluded at COP28 in Dubai calling for transitioning away from fossil fuels (2023)"],
     "I -> II -> III -> IV",
     "Climate diplomacy progression: Rio UNFCCC (1992), Kyoto Protocol (1997), Paris Agreement (2015), and COP28 Global Stocktake (2023)."),
    ("mcq", "India's Panchamrit Pledges at COP26 Glasgow",
     "At COP26 in Glasgow (November 2021), Prime Minister Narendra Modi presented India's ambitious climate strategy encapsulated as 'Panchamrit' (five nectar elements), committing India to:",
     "Reaching Net Zero carbon emissions by 2070, achieving 500 GW non-fossil capacity by 2030, and meeting 50% of energy requirements from renewables by 2030",
     ["Achieving Net Zero by 2022 by immediately shutting down all Indian factories", "Abolishing all solar and wind farms to return exclusively to coal power", "Paying $100 billion annually to European countries"],
     "India's Panchamrit pledges: 500 GW non-fossil capacity by 2030, 50% energy from renewables, 1 billion ton carbon reduction, 45% carbon intensity reduction, and Net Zero by 2070."),
    ("ar", "Article 6 of the Paris Agreement (Carbon Markets)",
     "Article 6 of the Paris Agreement establishes an international framework for voluntary cooperative approaches and carbon markets.",
     "Article 6.2 and 6.4 enable countries to trade Internationally Transferred Mitigation Outcomes (ITMOs), ensuring robust accounting to prevent double counting of emissions reductions.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Article 6 sets the rules for bilateral carbon trading (6.2) and a centralized UN crediting mechanism (6.4), requiring corresponding adjustments to stop double counting."),
    ("mcq", "Green Climate Fund (GCF) Headquarters",
     "Established under the UNFCCC framework in 2010 to serve as the primary operating entity of the financial mechanism assisting developing countries in adaptation and mitigation, the Green Climate Fund (GCF) is headquartered in:",
     "Songdo, Incheon, Republic of Korea",
     ["Geneva, Switzerland", "Washington DC, USA", "Nairobi, Kenya"],
     "The Green Climate Fund (GCF) is headquartered in Songdo, South Korea, channeling climate finance from developed nations to projects in developing countries."),
    ("mcq", "Loss and Damage Fund Breakthrough at COP27 Sharm El-Sheikh",
     "COP27 in Egypt (2022) achieved a historic breakthrough hailed by developing nations by formally establishing a dedicated international fund for:",
     "'Loss and Damage' to assist vulnerable developing countries severely hit by irreversible climate disasters (rising seas, extreme cyclones, flash floods)",
     ["Subsidizing offshore oil and gas drilling in polar regions", "Funding corporate mergers of international private coal companies", "Banning all renewable solar panels across Africa"],
     "COP27 established the landmark 'Loss and Damage Fund' (operationalized at COP28), providing financial rescue to vulnerable nations enduring irreversible climate catastrophes."),
    ("match", "Key COP Climate Summits and Historic Milestones",
     "Match the Conference of the Parties (COP) in List I with its historic agreement in List II:",
     [("A", "COP3 (1997)"),
      ("B", "COP15 (2009)"),
      ("C", "COP21 (2015)"),
      ("D", "COP28 (2023)"),
     ],
     [("I", "Kyoto, Japan: Adoption of the Kyoto Protocol with binding Annex I targets"),
      ("II", "Copenhagen, Denmark: Copenhagen Accord proposing the $100B annual finance goal"),
      ("III", "Paris, France: Adoption of the Paris Agreement with universal NDCs and 1.5 C goal"),
      ("IV", "Dubai, UAE: UAE Consensus calling for 'transitioning away from fossil fuels' in energy systems")],
     "A-I, B-II, C-III, D-IV",
     "COP3 adopted Kyoto; COP15 agreed to Copenhagen finance goal; COP21 adopted the Paris Agreement; and COP28 achieved the historic UAE Consensus on fossil fuels."),
    ("mcq", "LiFE Movement (Lifestyle for Environment)",
     "Championed by India at COP26 and endorsed globally, the 'Mission LiFE' (Lifestyle for Environment) movement promotes environmental sustainability by:",
     "Mobilizing individuals and communities to adopt mindful, deliberate, and eco-friendly consumer lifestyles that eliminate mindless consumption",
     ["Requiring all citizens to live in underground caves without electricity", "Banning the manufacture of bicycles and walking shoes", "Mandating that all household items be thrown away after one use"],
     "Mission LiFE, launched by PM Modi and UN Secretary-General Antonio Guterres, shifts climate policy toward individual responsibility and sustainable lifestyle choices."),
    ("mcq", "Carbon Credit Equivalency Benchmark",
     "In carbon accounting and international carbon markets, one standard 'Carbon Credit' (or Certified Emission Reduction) is precisely defined as equivalent to:",
     "The reduction, avoidance, or sequestration of one metric ton of Carbon Dioxide equivalent (1 tCO2e)",
     ["One kilogram of pure coal ash", "One million liters of drinking water", "One barrel of unrefined crude petroleum"],
     "A carbon credit is a tradable certificate representing the verified reduction or removal of exactly 1 metric ton of CO2 (or equivalent GHG)."),
    ("stmt", "International Carbon Border Adjustment Mechanism (CBAM) Controversy",
     "Developing countries (including BASIC nations: Brazil, South Africa, India, China) have formally protested the EU's Carbon Border Adjustment Mechanism (CBAM).",
     "Developing nations argue that unilateral carbon border tariffs violate the core UNFCCC principle of Common But Differentiated Responsibilities (CBDR) and represent disguised green protectionism.", 1,
     "Both Statement I and Statement II are correct. Developing nations view CBAM as discriminatory trade barriers that penalize developing economies that cannot rapidly afford expensive green retrofits."),
    ("mcq", "Kigali Amendment to Montreal Protocol and Climate Change",
     "Although negotiated under the Montreal Protocol on Ozone, why is the 2016 'Kigali Amendment' hailed as one of the single most impactful global climate mitigation treaties?",
     "It mandates the phased elimination of Hydrofluorocarbons (HFCs), which do not damage the ozone layer but are super-greenhouse gases; full implementation will avoid up to 0.4 to 0.5 degrees Celsius of global warming by 2100",
     ["It mandates that all air conditioners worldwide be turned off permanently", "It eliminates all international maritime trade by ship", "It replaces all natural food with synthetic chemicals"],
     "HFCs replaced CFCs to save ozone, but are potent greenhouse gases (GWPs in thousands); the Kigali Amendment phases them down, avoiding ~0.5 C of global warming."),
    ("seq", "Process Flow of a Carbon Offset Project under Verra (VCS) or Gold Standard",
     "Arrange the sequential operational steps required to develop and monetize verified carbon credits from a rural solar power project:",
     ["Drafting the Project Design Document (PDD) demonstrating financial additionality and emissions baseline calculations", "Independent third-party validation of the PDD by an accredited Designated Operational Entity (DOE)", "Project execution followed by periodic monitoring of verified renewable megawatt-hours generated", "Third-party verification and issuance of tradeable Verified Carbon Units (VCUs) registered on an international carbon registry"],
     "I -> II -> III -> IV",
     "Carbon offset workflow: PDD formulation with additionality, third-party validation, generation monitoring, and formal issuance/trading of credits on registries."),
    ("mcq", "Additionality Criterion in Carbon Offsets",
     "In carbon offset verification, the fundamental criterion of 'Additionality' requires the project developer to prove that:",
     "The emissions reductions or removals would NOT have occurred in the business-as-usual scenario in the absence of the revenue incentive provided by carbon credits",
     ["The project must add additional tons of plastic garbage into local rivers", "The project must employ additional workers who work 24 hours without sleep", "The project must burn additional coal alongside solar panels"],
     "Additionality is the acid test of carbon credits: if a project would have been built anyway due to attractive commercial returns, it is non-additional and cannot earn valid credits."),
    ("mcq", "Warsaw International Mechanism for Loss and Damage (WIM)",
     "Established at COP19 in 2013, the 'Warsaw International Mechanism for Loss and Damage' (WIM) focuses specifically on:",
     "Promoting the implementation of approaches to address climate change impacts associated with extreme weather events and slow-onset events (sea level rise, glacial retreat) in vulnerable developing countries",
     ["Providing military defense against international pirate attacks", "Subsidizing commercial nuclear missile testing in developing countries", "Constructing luxury private airports on tropical coral atolls"],
     "The WIM was the institutional pioneer under UNFCCC addressing slow-onset events (desertification, sea rise) and sudden disasters that exceed adaptation limits.")
]

# ==============================================================================
# Slot 39: Ozone Depletion Science & Global Treaties (Montreal, ODS, Kigali)
# ==============================================================================
s39_raw = [
    ("mcq", "Ozone Layer Location and Dobson Unit (DU)",
     "The protective ozone layer is located in which atmospheric layer, and what is the standard scientific unit used to measure total columnar atmospheric ozone thickness?",
     "Stratosphere (between 15 and 35 kilometers altitude), measured in Dobson Units (DU)",
     ["Troposphere, measured in Barometric Millibars", "Mesosphere, measured in Decibels", "Thermosphere, measured in Light Years"],
     "Good ozone resides in the stratosphere (15–35 km); 1 Dobson Unit (DU) corresponds to a pure ozone layer thickness of 0.01 mm at standard temperature and pressure (STP). Normal thickness is ~300 DU."),
    ("stmt", "Chapman Photochemical Cycle of Ozone",
     "In the stratosphere, ozone is naturally formed and broken down in a continuous dynamic equilibrium known as the Chapman Cycle.",
     "Solar UV-C radiation photolyzes molecular oxygen (O2) into atomic oxygen (O), which reacts with another O2 molecule to form Ozone (O3).", 1,
     "Both Statement I and Statement II are correct. The Chapman photochemical cycle maintains natural stratospheric ozone balance: O2 + UV-C -> O + O; O + O2 -> O3."),
    ("ar", "CFCs Stability and Stratospheric Transport",
     "Chlorofluorocarbons (CFCs, like Freon-11 and Freon-12) do not break down in the lower troposphere and persist for decades.",
     "CFCs are synthetic compounds that are completely chemically inert, non-toxic, non-flammable, and insoluble in water, allowing them to slowly diffuse unchanged upward into the stratosphere.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Because they do not wash out in rain or react with tropospheric oxidants, CFCs slowly migrate to the stratosphere over decades."),
    ("match", "Ozone Depleting Substances (ODS) and Industrial Uses",
     "Match the Ozone Depleting Substance in List I with its primary historical commercial application in List II:",
     [("A", "CFC-11 / CFC-12 (Freons)"),
      ("B", "Halons (Bromofluorocarbons)"),
      ("C", "Carbon Tetrachloride (CCl4)"),
      ("D", "Methyl Bromide (CH3Br)")],
     [("I", "Refrigerants in domestic fridges, air conditioning, and aerosol spray propellant cans"),
      ("II", "Highly effective fire-extinguishing systems in military aircraft and data centers"),
      ("III", "Industrial cleaning solvent and chemical feedstock in pesticide manufacturing"),
      ("IV", "Agricultural soil fumigant used to eliminate subterranean nematodes and fungi before planting")],
     "A-I, B-II, C-III, D-IV",
     "CFCs were refrigerants/propellants; Halons were fire extinguishants; Carbon tetrachloride was an industrial solvent; and Methyl bromide was a soil fumigant."),
    ("mcq", "Catalytic Destruction of Ozone by Chlorine Radicals",
     "When CFCs reach the mid-stratosphere, high-energy solar UV radiation cleaves them, releasing reactive Chlorine free radicals (Cl). A single chlorine atom can catalytically destroy approximately how many ozone molecules before being deactivated?",
     "Over 100,000 ozone (O3) molecules",
     ["Only 1 ozone molecule", "Exactly 5 ozone molecules", "Zero ozone molecules"],
     "NCERT highlights that chlorine atoms act as a catalytic agent; a single chlorine radical is recycled continuously, destroying >100,000 ozone molecules before diffusing out."),
    ("mcq", "Antarctic Ozone Hole Discovery",
     "In 1985, British Antarctic Survey scientists (led by Joseph Farman, Brian Gardiner, and Jonathan Shanklin) shocked the global scientific community by publishing the discovery of:",
     "A catastrophic, unprecedented seasonal thinning of the stratospheric ozone layer over Antarctica during the Austral spring (September-October), where ozone dropped below 220 DU",
     ["A permanent tropical heatwave at the South Pole", "A massive volcanic lava lake covering the entire Antarctic ice sheet", "The complete disappearance of all gravitational pull over Antarctica"],
     "Farman et al. discovered the Antarctic 'Ozone Hole' in 1985 using Dobson spectrophotometer ground measurements, confirming severe seasonal stratospheric ozone depletion."),
    ("stmt", "Polar Stratospheric Clouds (PSCs) and Chlorine Activation",
     "During the frigid dark Antarctic polar winter, temperatures inside the isolated Polar Vortex drop below -78 degrees Celsius, forming Polar Stratospheric Clouds (PSCs) composed of nitric acid and water ice.",
     "The heterogeneous ice surfaces of PSCs catalyze inactive reservoir chlorine compounds (HCl and ClONO2) into highly active, photolabile molecular chlorine gas (Cl2).", 1,
     "Both Statement I and Statement II are correct. PSCs activate reservoir chlorine; when spring sunrise returns in September, sunlight photolyzes Cl2 into reactive Cl radicals, rapidly destroying ozone."),
    ("seq", "Chemical Steps in the Formation of the Antarctic Spring Ozone Hole",
     "Arrange the sequential atmospheric events leading to the catastrophic Antarctic spring ozone hole:",
     ["Winter Polar Vortex isolates Antarctic stratosphere; temperatures plummet below -78 degrees Celsius, forming Polar Stratospheric Clouds (PSCs)", "Heterogeneous chemical reactions on PSC ice crystals convert inactive chlorine reservoirs (HCl and ClONO2) into molecular chlorine (Cl2)", "Austral spring sunrise in September: sunlight photolyzes Cl2 into reactive Chlorine free radicals (Cl)", "Chlorine catalytic chain reaction proceeds violently: Cl + O3 -> ClO + O2, causing ozone levels to crash below 220 Dobson Units within weeks"],
     "I -> II -> III -> IV",
     "Ozone hole sequence: winter polar vortex isolation, PSC formation, chlorine activation on ice crystals, and rapid catalytic spring photochemical destruction."),
    ("mcq", "Health Hazards of Increased Solar UV-B Exposure",
     "Stratospheric ozone depletion allows increased solar UV-B radiation (wavelength 280–315 nm) to reach Earth's surface, causing severe human health consequences, including:",
     "Non-melanoma and melanoma skin cancers, cataract clouding of the eye lens, corneal snow blindness, and suppression of the immune system",
     ["Rapid human lung expansion allowing people to breathe underwater", "Transformation of all human hair into copper electrical wiring", "Instantaneous immunity to all bacterial and viral infections"],
     "UV-B damages DNA and proteins: it mutates skin cells (causing basal and squamous cell carcinomas and melanoma), induces eye cataracts, and causes corneal blindness."),
    ("ar", "Montreal Protocol Unprecedented Success",
     "The Montreal Protocol on Substances that Deplete the Ozone Layer (adopted in 1987) is celebrated as the single most successful international environmental treaty in history.",
     "The Montreal Protocol achieved universal ratification by all 198 UN member states, established legally binding phase-out timetables backed by trade sanctions, and created the Multilateral Fund to assist developing countries.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Montreal combined universal participation, financial technology transfer, and strict phase-outs, placing the ozone layer on a path to complete mid-century recovery."),
    ("mcq", "Multilateral Fund for the Implementation of the Montreal Protocol",
     "Established in 1990 under the London Amendment, the 'Multilateral Fund' of the Montreal Protocol operates to:",
     "Provide dedicated financial grants and technology transfer to developing Article 5 nations to enable their industries to transition away from Ozone Depleting Substances",
     ["Purchase military defense fighter jets for polar scientific expeditions", "Finance the construction of coal-fired thermal power stations across the Arctic", "Pay monetary compensation directly to multinational aerosol manufacturing companies"],
     "The Multilateral Fund has disbursed over $4 billion to developing countries, financing factory re-tooling, technical training, and chemical transitions to non-ODS alternatives."),
    ("mcq", "Hydrochlorofluorocarbons (HCFCs) as Transitional Substitutes",
     "Why were Hydrochlorofluorocarbons (HCFCs, like HCFC-22) adopted merely as temporary 'transitional substances' rather than permanent replacements for CFCs under the Montreal Protocol?",
     "Because although HCFCs possess lower Ozone Depletion Potential (ODP) than CFCs due to hydrogen atoms allowing some tropospheric breakdown, they still contain chlorine that attacks stratospheric ozone",
     ["Because HCFCs instantly transform into solid gold inside refrigerator compressors", "Because HCFCs cannot be compressed into liquids under any temperature", "Because HCFCs have zero boiling point"],
     "HCFCs contain hydrogen, breaking down partially in the troposphere, but still carry chlorine to the stratosphere, mandating their planned complete phase-out by 2030 (Article 5: 2040)."),
    ("match", "Ozone Conventions, Amendments, and Milestones",
     "Match the international ozone milestone in List I with its historical achievement in List II:",
     [("A", "Vienna Convention (1985)"),
      ("B", "Montreal Protocol (1987)"),
      ("C", "Kigali Amendment (2016)"),
      ("D", "International Day for the Preservation of the Ozone Layer")],
     [("I", "Framework convention establishing international cooperation in scientific research on the ozone layer"),
      ("II", "Legally binding treaty establishing specific phase-out schedules for 96 ozone-depleting chemicals"),
      ("III", "Mandates the phasedown of Hydrofluorocarbons (HFCs), potent greenhouse gases used as non-ozone alternatives"),
      ("IV", "September 16, celebrated annually worldwide to commemorate the signing of the Montreal Protocol")],
     "A-I, B-II, C-III, D-IV",
     "Vienna 1985 set the research framework; Montreal 1987 mandated phase-outs; Kigali 2016 phased down HFCs; and September 16 is World Ozone Day."),
    ("mcq", "Ozone Depletion Potential (ODP) Benchmark",
     "In atmospheric chemistry, the 'Ozone Depletion Potential' (ODP) of an ozone-depleting substance is standardized relative to which chemical reference compound assigned an ODP of 1.0?",
     "CFC-11 (Trichlorofluoromethane, CCl3F)",
     ["Carbon Dioxide (CO2)", "Methane (CH4)", "Nitrous Oxide (N2O)"],
     "ODP measures the relative amount of ozone destruction per unit mass compared to CFC-11, which serves as the reference benchmark with ODP = 1.0."),
    ("mcq", "Ecological Impacts of UV-B on Marine Phytoplankton",
     "How does elevated solar UV-B penetration through the Antarctic ozone hole directly damage Southern Ocean marine ecosystems?",
     "It inhibits photosynthesis, damages cell DNA, and kills marine phytoplankton, the foundational primary producers supporting krill, penguins, seals, and whales",
     ["It causes ocean water to freeze solid into mountain icebergs", "It forces all pelagic whales to permanently migrate onto dry Antarctic land", "It increases phytoplankton primary productivity by 1,000 times"],
     "UV-B radiation penetrates tens of meters into clear Antarctic waters, impairing photosynthesis and survival of diatoms and phytoplankton, undermining the entire polar marine food web."),
    ("stmt", "Ozone Hole Definition Threshold",
     "In atmospheric monitoring by NASA and the British Antarctic Survey, an 'Ozone Hole' does not represent a physical void or hole with zero ozone.",
     "It is technically defined as a geographic area where the total column ozone concentration falls below the threshold of 220 Dobson Units (DU).", 1,
     "Both Statement I and Statement II are correct. 220 DU is the historical baseline threshold; levels below this were never observed prior to 1979."),
    ("mcq", "Hydrofluorocarbons (HFCs) as Ozone-Safe Alternatives",
     "Why were Hydrofluorocarbons (HFCs, like HFC-134a in automobile ACs) initially celebrated and widely commercialized as replacements for CFCs and HCFCs?",
     "Because they contain hydrogen, fluorine, and carbon, but contain zero Chlorine or Bromine atoms, giving them an Ozone Depletion Potential (ODP) of exactly zero",
     ["Because they are completely non-flammable edible food additives", "Because they can be extracted directly from cow milk", "Because they absorb carbon dioxide from the atmosphere"],
     "HFCs have zero chlorine/bromine, so their ODP is zero; however, their high Global Warming Potential (GWP) necessitated their subsequent phase-down under the Kigali Amendment."),
    ("seq", "Chemical Destruction Cycle of Ozone by a Chlorine Atom",
     "Arrange the catalytic reaction cycle steps illustrating how chlorine destroys ozone in the stratosphere:",
     ["A free Chlorine radical (Cl) collides with an Ozone molecule: Cl + O3 -> ClO + O2", "Chlorine monoxide (ClO) intermediate is formed, releasing a stable molecule of oxygen gas (O2)", "Chlorine monoxide reacts with a free atomic oxygen atom: ClO + O -> Cl + O2", "The original reactive Chlorine free radical (Cl) is regenerated unspent, ready to attack another ozone molecule in a catalytic loop"],
     "I -> II -> III -> IV",
     "Chlorine catalytic cycle: Cl attacks O3 forming ClO and O2; ClO then reacts with nascent O, regenerating the active Cl radical to repeat the cycle."),
    ("mcq", "Natural Plant Adaptations to Solar UV Radiation",
     "How do terrestrial plants naturally protect their cellular DNA and photosynthetic chloroplasts against moderate solar UV-B radiation?",
     "By synthesizing and accumulating protective UV-absorbing flavonoid and phenolic pigments in the upper epidermal cell layers, which act like natural sunscreen",
     ["By dropping all their green leaves immediately at sunrise", "By growing underground and emerging only at midnight", "By coating their stems in heavy metallic lead foil"],
     "Plants accumulate UV-absorbing secondary metabolites (flavonoids, anthocyanins) in upper epidermal layers, which filter out harmful UV-B before it penetrates to photosynthetic mesophyll."),
    ("mcq", "Projected Recovery Timeline of the Stratospheric Ozone Layer",
     "According to the 2022 quadrennial assessment by the Scientific Assessment Panel of the Montreal Protocol, if current global policies remain in place, when is the Antarctic ozone hole projected to fully recover to 1980 baseline levels?",
     "Around 2066 over Antarctica (and around 2040 for the rest of the world)",
     ["By the year 2025", "Never; the ozone layer will disappear permanently by 2030", "In the year 3500"],
     "Thanks to the global phase-out of ODSs under the Montreal Protocol, ozone over mid-latitudes will recover by ~2040, the Arctic by ~2045, and the Antarctic hole around ~2066.")
]

# ==============================================================================
# Slot 40: Indian Environmental Jurisprudence & Grassroots Movements
# ==============================================================================
s40_raw = [
    ("mcq", "Constitutional Foundation: Article 48A and Article 51A(g)",
     "Which landmark constitutional amendment in 1976 inserted Article 48A (Directive Principles of State Policy) and Article 51A(g) (Fundamental Duties) into the Constitution of India, mandating environmental protection?",
     "The 42nd Constitutional Amendment Act, 1976",
     ["The 44th Constitutional Amendment Act, 1978", "The 1st Constitutional Amendment Act, 1951", "The 73rd Constitutional Amendment Act, 1992"],
     "The 42nd Amendment (1976) enshrined environmental protection into the Constitution: Article 48A (State shall protect environment, forests, and wildlife) and Article 51A(g) (Fundamental Duty of citizens)."),
    ("stmt", "Article 21 and the Right to a Wholesome Environment",
     "The fundamental Right to Life under Article 21 of the Indian Constitution has been interpreted by the Supreme Court to include the right to a clean, healthy, and pollution-free environment.",
     "In landmark rulings such as Subhash Kumar v. State of Bihar (1991) and Vellore Citizens Welfare Forum (1996), the Supreme Court held that enjoyment of pollution-free water and air is an integral part of the right to live with human dignity.", 1,
     "Both Statement I and Statement II are correct. Judicial activism in India transformed Article 21 into an expansive constitutional charter guaranteeing environmental justice."),
    ("ar", "Environment Protection Act 1986 as Umbrella Legislation",
     "The Environment (Protection) Act, 1986 (EPA 1986) is characterized as an 'Umbrella Legislation'.",
     "Enacted under Article 253 following the Bhopal Gas Disaster, EPA 1986 provides an overarching legal framework coordinating all existing pollution control agencies and empowering the Central Government to set nationwide environmental standards.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). EPA 1986 bridges gaps between the Water and Air Acts, empowering the Centre to take all necessary measures to protect environmental quality."),
    ("match", "Landmark Environmental PILs and Supreme Court Verdicts",
     "Match the landmark Supreme Court environmental case in List I with its legal principle in List II:",
     [("A", "M.C. Mehta v. Union of India (Oleum Gas Leak 1987)"),
      ("B", "Vellore Citizens Welfare Forum v. UOI (1996)"),
      ("C", "M.C. Mehta v. Union of India (Taj Trapezium Case 1996)"),
      ("D", "Subhash Kumar v. State of Bihar (1991)")],
     [("I", "Formulated the doctrine of 'Absolute Liability' for hazardous and inherently dangerous industrial enterprises"),
      ("II", "Integrated the 'Precautionary Principle' and 'Polluter Pays Principle' as part of the law of the land under Article 21"),
      ("III", "Mandated coal-to-gas transition and ordered polluting industries in the Taj Trapezium Zone (TTZ) to relocate to protect Taj Mahal marble"),
      ("IV", "Held that the right to live includes the right of enjoyment of pollution-free water and air for full enjoyment of life under Article 21")],
     "A-I, B-II, C-III, D-IV",
     "Oleum gas leak established Absolute Liability; Vellore tanneries adopted Precautionary/PPP doctrines; TTZ protected the Taj Mahal; and Subhash Kumar recognized clean water/air under Art 21."),
    ("mcq", "Absolute Liability vs Strict Liability (Rylands v. Fletcher)",
     "In the historic Shriram Foods and Fertilizer (Oleum Gas Leak) case (1987), Chief Justice P.N. Bhagwati established the doctrine of 'Absolute Liability', holding that:",
     "An enterprise engaged in a hazardous or inherently dangerous activity owes an absolute, non-delegable duty to society, and is strictly liable for any escape of hazard with ZERO exceptions (no Act of God defense)",
     ["Industries are completely exempt from paying compensation if they pay municipal taxes", "Industries only pay compensation if the accident was caused by deliberate criminal sabotage", "The victim must prove beyond doubt that the company CEO personally broke the pipe"],
     "Absolute Liability discarded the exceptions of the 1868 British Rylands v. Fletcher rule (Act of God, plaintiff's consent), holding hazardous industries strictly and unconditionally liable for all damages."),
    ("mcq", "National Green Tribunal (NGT) Act 2010 Structure",
     "Established under the National Green Tribunal Act, 2010, the NGT is a specialized judicial body that replaces ordinary civil courts for environmental disputes, mandated to dispose of applications within:",
     "Six months of filing",
     ["Ten years", "30 days", "Twenty-four hours"],
     "The NGT is a specialized forum comprising judicial and expert members, mandated by Section 18 to expeditiously dispose of environmental cases within 6 months."),
    ("stmt", "Public Trust Doctrine in Indian Environmental Law",
     "In M.C. Mehta v. Kamal Nath (Span Motels Case, 1997), the Supreme Court of India adopted the 'Public Trust Doctrine'.",
     "The doctrine holds that natural resources like rivers, forests, seashores, and air are held by the State in trust for the general public and cannot be privatized or diverted for commercial hospitality resorts.", 1,
     "Both Statement I and Statement II are correct. Span Motels altered the Beas river flow; the court held that common ecological resources cannot be privatized, invoking the Public Trust Doctrine."),
    ("seq", "Chronological Milestones of Grassroots Environmental Movements in India",
     "Arrange these iconic Indian grassroots environmental struggles in chronological order:",
     ["Amrita Devi Bishnoi leads 363 martyrs sacrificing their lives to save sacred Khejri trees in Rajasthan (1730)", "Gaura Devi and village women hug trees to halt commercial logging in Chamoli, launching the Chipko Movement (1973)", "Kerala Sastra Sahitya Parishad (KSSP) mobilizes the Silent Valley Movement to protect evergreen rainforests from a hydroelectric dam (1970s)", "Medha Patkar and Baba Amte launch the Narmada Bachao Andolan opposing submergence by the Sardar Sarovar Dam (1985)"],
     "I -> II -> III -> IV",
     "Movement chronology: Bishnoi sacrifice (1730), Chipko movement (1973), Silent Valley struggle (late 1970s), and Narmada Bachao Andolan (1985 onwards)."),
    ("mcq", "Chipko Movement Chamoli History",
     "In March 1974 at Reni village in Chamoli district, Uttarakhand, which brave rural woman led 27 village women to confront commercial logging contractors by physically hugging forest trees?",
     "Gaura Devi",
     ["Medha Patkar", "Vandana Shiva", "Amrita Devi"],
     "Gaura Devi, head of the Reni Mahila Mangal Dal, led village women to encircle trees, famously declaring: 'This forest is our mother's home; we will hug the trees and not let them fall.'"),
    ("ar", "Silent Valley Movement Success and National Park Declaration",
     "The proposed hydroelectric dam across the Kunthipuzha river in Silent Valley, Kerala, was ultimately abandoned by the Government of India in 1983.",
     "Massive public mobilization led by the Kerala Sastra Sahitya Parishad (KSSP) and environmental scientists proved that flooding the valley would permanently destroy one of the last undisturbed tropical evergreen rainforests harboring the Lion-tailed Macaque.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Public protest saved Silent Valley, leading Prime Minister Rajiv Gandhi to inaugurate it as an inviolate National Park in 1985."),
    ("mcq", "Appiko Movement of Western Ghats",
     "In September 1983, inspired directly by the Himalayan Chipko movement, villagers in Gubbi Gadde in the Uttara Kannada district of Karnataka launched the 'Appiko Movement' (meaning 'to hug' in Kannada) led by:",
     "Pandurang Hegde",
     ["Chandi Prasad Bhatt", "Sundarlal Bahuguna", "Anna Hazare"],
     "Pandurang Hegde led the Appiko movement in the Western Ghats of Karnataka, using tree-hugging protests to stop commercial felling in tropical evergreen forests."),
    ("mcq", "Narmada Bachao Andolan (NBA) Core Demands",
     "The Narmada Bachao Andolan (NBA), led by social activist Medha Patkar and Gandhian worker Baba Amte, organized mass resistance against the Sardar Sarovar mega-dam project primarily over:",
     "The unjust, uncompensated submergence of hundreds of indigenous tribal villages, fertile agricultural lands, and forests without comprehensive rehabilitation and resettlement (R&R)",
     ["A demand to build nuclear reactors inside the river valley", "A demand to export all river water to international markets", "A desire to ban all irrigation throughout Western India"],
     "NBA protested the displacement of over 250,000 predominantly tribal farmers, challenging the model of destructive mega-dams and demanding democratic rehabilitation and ecological justice."),
    ("match", "Environmental Activists and Flagship Indian Struggles",
     "Match the environmental crusader in List I with their defining social movement in List II:",
     [("A", "Chandi Prasad Bhatt"),
      ("B", "Medha Patkar"),
      ("C", "M.C. Mehta"),
      ("D", "Rajendra Singh")],
     [("I", "Pioneered the Chipko movement and founded the Dasholi Gram Swarajya Mandal (DGSM)"),
      ("II", "Leader of the Narmada Bachao Andolan defending tribal rights against dam submergence"),
      ("III", "Supreme Court advocate whose landmark public interest litigations (PILs) established modern Indian environmental jurisprudence"),
      ("IV", "Revived traditional Johads in Rajasthan, earning the title 'Waterman of India'")],
     "A-I, B-II, C-III, D-IV",
     "Chandi Prasad Bhatt founded DGSM/Chipko; Medha Patkar led NBA; M.C. Mehta won landmark Supreme Court environmental PILs; and Rajendra Singh revived rivers through Johads."),
    ("mcq", "Bhopal Gas Leak Public Liability Insurance Act 1991",
     "Following the tragic aftermath of the 1984 Bhopal disaster where thousands of victims struggled without immediate relief, Parliament enacted the 'Public Liability Insurance Act, 1991' to:",
     "Provide mandatory, immediate, no-fault financial relief to accident victims of hazardous chemical handling through an Environment Relief Fund",
     ["Abolish all chemical manufacturing across India permanently", "Protect multinational corporations from ever paying any civil damages", "Mandate that chemical accident victims pay the medical expenses of factory owners"],
     "The Public Liability Insurance Act 1991 mandates that hazardous industrial enterprises purchase insurance to provide immediate 'no-fault' statutory relief to toxic accident victims."),
    ("mcq", "NGT Principal Bench and Zonal Benches",
     "Where is the Principal Bench of the National Green Tribunal (NGT) located, and where are its four designated zonal regional benches?",
     "Principal Bench in New Delhi; Regional Benches in Bhopal (Central), Pune (Western), Kolkata (Eastern), and Chennai (Southern)",
     ["Principal Bench in Mumbai; Regional Benches in Srinagar, Goa, Patna, and Shimla", "Principal Bench in London; Regional Benches in Paris, Berlin, and Rome", "Only one bench exists, located in the Thar desert"],
     "The NGT operates from its Principal Bench in New Delhi, supported by 4 regional zonal benches in Bhopal, Pune, Kolkata, and Chennai."),
    ("stmt", "National Forest Policy 1952 vs 1988 Paradigm Shift",
     "The National Forest Policy of 1952 viewed forests primarily as a source of state revenue, commercial timber, and raw material for industrial development.",
     "The National Forest Policy of 1988 fundamentally reversed this priority, declaring that environmental stability, ecological balance, and meeting local community fuel/fodder needs must override commercial revenue generation.", 1,
     "Both Statement I and Statement II are correct. The 1988 policy subordinated commercial exploitation to ecological preservation and community subsistence."),
    ("mcq", "Plachimada Coca-Cola Groundwater Struggle",
     "In Plachimada in Palakkad district, Kerala, an iconic local grassroots struggle led by Adivasi women (such as Mayilamma) forced the permanent shutdown of a Coca-Cola bottling plant in 2004 because:",
     "The plant extracted over 1.5 million liters of groundwater daily, drying up local wells and distributing toxic sludge containing high levels of cadmium and lead as 'fertilizer' to farmers",
     ["The factory was manufacturing illegal nuclear missiles", "The factory refused to sell cold drinks to local villagers", "The company attempted to build an international airport on farmland"],
     "The Plachimada struggle proved that local Panchayats have constitutional authority under the 73rd Amendment to cancel operating licenses of industries over-extracting groundwater and polluting soils."),
    ("seq", "Process Flow of Filing an Environmental Grievance before the NGT",
     "Arrange the procedural steps taken by an affected citizen seeking relief against illegal river sand mining before the National Green Tribunal:",
     ["Filing of an application under Section 14/15 of the NGT Act 2010 supported by geotagged photographic and satellite evidence", "Tribunal issues preliminary notice to respondents and constitutes an independent Joint Expert Committee (CPCB, SPCB, District Magistrate) for field inspection", "The Joint Committee conducts physical on-site inspection, computes environmental damage, and submits an evidentiary report to the Tribunal", "Tribunal adjudicates, orders an immediate ban on illegal mining, and imposes environmental compensation under the Polluter Pays Principle"],
     "I -> II -> III -> IV",
     "NGT adjudication workflow: application filing, independent expert committee field inspection, damage assessment report, and binding judicial orders with polluter-pays restitution."),
    ("mcq", "Koel Karo Hydroelectric Project Resistance",
     "The indigenous Munda and Oraon tribal communities of Jharkhand successfully organized a decade-long non-violent resistance against the 'Koel Karo Hydroelectric Project', ultimately forcing its cancellation because:",
     "The proposed twin dams would have submerged over 45,000 hectares of ancestral tribal farmland and destroyed over 150 sacred Sarna burial and worship groves",
     ["The dams were designed to freeze all river water into permafrost", "The tribal villagers wanted to build open-pit uranium mines instead", "The project proposed building a mega-city in the forest"],
     "The Koel-Karo Jan Sangathan fought for decades against displacement, successfully protecting Sarna sacred groves and ancestral agricultural lands from dam inundation."),
    ("mcq", "National Environment Policy (NEP) 2006 Key Tenet",
     "The National Environment Policy (NEP) 2006 adopted by the Government of India serves as an overarching policy guide, explicitly emphasizing that:",
     "Human beings are at the center of sustainable development concerns, and while conservation of environmental resources is necessary, it must not compromise the livelihoods of poor and marginalized communities",
     ["All environmental regulations must be abolished to maximize short-term corporate profits", "All protected areas must be opened for commercial open-cast mineral mining", "Citizens have zero constitutional right to question environmental decisions"],
     "NEP 2006 integrates environmental considerations into socio-economic development, recognizing that environmental degradation disproportionately harms the rural poor.")
]
'''

with open('scripts/subject_generators/make_evs_s36_40.py', 'w') as f:
    f.write(s36_to_40)

print("make_evs_s36_40.py written.")
