# Slots 21 to 25 Generator
s21_to_25 = '''
CH_SUSTAINABLE = "Third World Development and Sustainable Agriculture"

# ==============================================================================
# Slot 21: Municipal Solid Waste Management (Landfills, Composting, Waste-to-Energy)
# ==============================================================================
s21_raw = [
    ("mcq", "Sanitary Landfill Engineering Features",
     "Unlike an open dump, an engineered 'Sanitary Landfill' prevents groundwater contamination and environmental hazards by incorporating:",
     "An impermeable composite basal liner (compacted clay and HDPE geomembrane), a leachate collection and treatment system, and methane gas recovery vents",
     ["Open burning pits that combust all garbage at ground level without filters", "Unlined porous sand pits that allow waste liquids to drain directly into aquifers", "Open trenches situated directly inside floodplain wetlands"],
     "Sanitary landfills isolate waste using low-permeability clay liners (hydraulic conductivity < 10^-7 cm/s), synthetic HDPE geomembranes, leachate sumps, and methane wells."),
    ("stmt", "Leachate Composition and Hazard",
     "Leachate is a highly toxic, dark liquid formed when rainwater percolates through decomposing solid waste, dissolving organic compounds and heavy metals.",
     "If leachate escapes from an unlined landfill, it can form extensive contamination plumes in underlying groundwater aquifers, poisoning drinking wells.", 1,
     "Both Statement I and Statement II are correct. Leachate contains high concentrations of organic matter, ammonia, heavy metals, and chlorinated organics."),
    ("ar", "Landfill Methane Gas Recovery",
     "Sanitary landfills produce substantial quantities of landfill gas (LFG) composed primarily of 50–60% Methane (CH4) and 40–50% Carbon Dioxide (CO2).",
     "Anaerobic methanogenic bacteria thrive in the compacted, oxygen-depleted depths of landfills, breaking down organic biodegradable wastes.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Anaerobic digestion of organic waste in landfills generates methane, which must be captured to prevent explosions and greenhouse warming."),
    ("match", "Solid Waste Management Technologies and Mechanisms",
     "Match the waste processing technology in List I with its operational mechanism in List II:",
     [("A", "Windrow Composting"),
      ("B", "Vermicomposting"),
      ("C", "Incineration (Mass Burn)"),
      ("D", "Pyrolysis")],
     [("I", "Aerobic biological decomposition of segregated organic waste piled in elongated triangular heaps turned regularly"),
      ("II", "Biological composting utilizing specialized surface-dwelling epigeic earthworms (e.g., Eisenia fetida)"),
      ("III", "Controlled high-temperature thermal combustion (850–1,100 degrees Celsius) in excess oxygen, generating steam electricity"),
      ("IV", "Thermal decomposition of carbonaceous waste at elevated temperatures in the total absence of oxygen, yielding bio-oil and syngas")],
     "A-I, B-II, C-III, D-IV",
     "Windrows use turned heaps, vermicomposting uses earthworms, incineration burns with oxygen, and pyrolysis thermally cracks waste without oxygen."),
    ("mcq", "Eisenia fetida in Vermicomposting",
     "The epigeic earthworm species most widely utilized in commercial vermicomposting of organic municipal waste in India due to its voracious organic consumption is:",
     "Eisenia fetida (Red wiggler / Red worm)",
     ["Pheretima posthuma (Indian common earthworm)", "Lumbricus terrestris (Nightcrawler)", "Hirudinaria granulosa (Leech)"],
     "Eisenia fetida (Red worm) lives in top organic layers, tolerates wide temperature ranges, and rapidly digests organic manure into nutrient-rich vermicast."),
    ("mcq", "Incineration Air Pollution Hazard (Dioxins and Furans)",
     "In municipal waste incinerators, the incomplete combustion of chlorinated plastics (such as PVC) at sub-optimal temperatures releases trace emissions of which extremely potent, carcinogenic toxins?",
     "Polychlorinated Dibenzo-p-Dioxins (PCDDs) and Polychlorinated Dibenzofurans (PCDFs)",
     ["Pure molecular oxygen and ozone", "Beneficial mineral calcium carbonate vapors", "Liquid water droplets that cool the atmosphere"],
     "Burning chlorine-containing waste at temperatures below 850 C generates highly toxic, bioaccumulative dioxins and furans, requiring advanced flue-gas cleaning."),
    ("stmt", "Solid Waste Management Rules 2016 Segregation Mandate",
     "Under the Solid Waste Management Rules, 2016, it is mandatory for all waste generators to segregate waste at source into three distinct streams.",
     "The three mandated streams are: Wet (biodegradable food waste), Dry (recyclable plastics, paper, metals), and Domestic Hazardous waste (expired medicines, paints, batteries).", 1,
     "Both Statement I and Statement II are correct. Source segregation into wet, dry, and domestic hazardous streams is the foundation of SWM Rules 2016."),
    ("seq", "Sequence of Operations in a Waste-to-Energy Incineration Plant",
     "Arrange the sequential process steps in a modern municipal mass-burn waste-to-energy plant:",
     ["Unloading of non-recyclable high-calorific municipal solid waste into the enclosed storage bunker", "Controlled feed into the high-temperature moving-grate combustion furnace (operating above 850–1,000 degrees Celsius)", "Recovery of thermal energy in a boiler, generating high-pressure superheated steam to turn a turbine generator", "Multi-stage flue gas treatment (scrubbers, activated carbon injection, baghouses) to capture acid gases, dioxins, and fly ash before stack discharge"],
     "I -> II -> III -> IV",
     "Incineration sequence: waste bunker storage, high-temp combustion, boiler steam power generation, and advanced multi-stage flue gas scrubbing."),
    ("mcq", "Refuse-Derived Fuel (RDF) Composition",
     "In modern waste management, 'Refuse-Derived Fuel' (RDF) produced from municipal solid waste consists primarily of:",
     "The shredded, dried, high-calorific non-recyclable combustible fraction (plastics, textiles, paper, rubber) used in cement kilns",
     ["Pure wet organic kitchen food waste and vegetable peels", "Crushed concrete rocks and demolition gravel", "Toxic liquid chemical solvents from petrochemical refineries"],
     "RDF is processed combustible waste (plastics, paper, cloth) dried and shredded to achieve high calorific value for co-processing in cement kilns."),
    ("ar", "Biomining and Legacy Waste Dumpsites",
     "Biomining and bioremediation are mandated under Swachh Bharat Mission-Urban 2.0 to clear decades-old 'legacy waste' garbage dumpsites across Indian cities.",
     "Biomining utilizes heavy trommel rotary sieves and microbial inoculants to separate legacy dumps into soil-enricher earth, refuse-derived fuel (RDF), and recyclables.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Biomining stabilizes and sorts legacy waste mounds, reclaiming hundreds of acres of valuable urban land."),
    ("mcq", "Landfill Mining Reclaimed Fractions",
     "When an old legacy landfill is excavated and processed through biomining, the separated fine mineral fraction (< 4 mm) rich in stabilized organic matter is typically utilized as:",
     "Soil enricher / construction filler for road embankments and city parks",
     ["Direct human breakfast cereal additive", "High-octane aviation turbine fuel", "Pure drinking spring water"],
     "The fine organic-soil fraction separated by trommel sieves is used as non-agricultural soil enricher, garden topsoil, or road embankment filling."),
    ("mcq", "C/N Ratio in Optimal Composting",
     "For rapid and odor-free aerobic microbial composting of municipal biodegradable waste, what is the scientifically recommended initial Carbon-to-Nitrogen (C:N) ratio of the feedstock mixture?",
     "Approximately 25:1 to 30:1",
     ["1:100", "500:1", "1:1"],
     "A C:N ratio of 25–30 parts carbon to 1 part nitrogen provides optimal energy and protein synthesis for aerobic thermophilic bacteria without ammonia odor."),
    ("match", "Waste Categories and Recommended Disposal Routes",
     "Match the waste stream in List I with its environmentally sound processing method in List II:",
     [("A", "Biodegradable Vegetable / Food Waste"),
      ("B", "High-Calorific Plastics and Dry Packaging"),
      ("C", "Inert Construction and Demolition (C&D) Debris"),
      ("D", "Household Expired Medicines and Cleaners")],
     [("I", "Aerobic composting / Bio-methanation"),
      ("II", "Refuse-Derived Fuel (RDF) for cement kilns"),
      ("III", "Crushing and recycling into paver blocks and aggregate sub-base"),
      ("IV", "Segregated collection for hazardous waste incineration")],
     "A-I, B-II, C-III, D-IV",
     "Food waste is composted/digested, combustible dry waste becomes RDF, C&D waste is recycled into aggregates, and domestic hazardous goes to incineration."),
    ("mcq", "Bio-Methanation Plant Byproducts",
     "An urban anaerobic bio-methanation plant processing wet food waste produces which two valuable circular economy byproducts?",
     "Biogas (rich in methane for clean thermal energy or CNG) and nutrient-rich bio-slurry organic fertilizer",
     ["Synthetic radioactive isotopes and liquid gasoline", "Pure solid plastic pellets and ozone gas", "Crushed granite stone and sulfuric acid"],
     "Bio-methanation digests organic slurry anaerobically, generating methane biogas (converted to Bio-CNG) and pathogen-free liquid organic manure."),
    ("mcq", "Extended Producer Responsibility (EPR) in Waste Rules",
     "Under Indian environmental law, the principle of 'Extended Producer Responsibility' (EPR) legally mandates that:",
     "Producers, brand owners, and importers are financially and operationally responsible for the collection, recycling, and end-of-life management of the packaging and products they put on the market",
     ["Individual municipal sweepers must personally purchase all industrial factories in the district", "Consumers are prohibited from ever discarding any purchased item", "State governments must pay 100% of all marketing costs of multinational soft drink brands"],
     "EPR places cradle-to-grave responsibility on manufacturers and brand owners to fund collection and recycling infrastructure for their post-consumer packaging."),
    ("stmt", "Construction and Demolition (C&D) Waste Rules 2016",
     "The Construction and Demolition Waste Management Rules, 2016, prohibit the dumping of construction debris in municipal solid waste landfills.",
     "The rules mandate bulk generators to submit waste management plans and require municipal bodies to establish specialized C&D recycling plants to produce recycled concrete aggregates.", 1,
     "Both Statement I and Statement II are correct. C&D waste (concrete, bricks, mortar) must be processed separately into recycled sand, tiles, and paver blocks."),
    ("mcq", "Sanitary Landfill Post-Closure Care Period",
     "Under the Solid Waste Management Rules 2016, how long must an engineered sanitary landfill be continuously monitored for groundwater contamination and gas leakage after its final closure?",
     "For at least 15 to 25 years post-closure",
     ["For exactly 24 hours", "Zero days, monitoring ends immediately upon closure", "For 500 years"],
     "Post-closure monitoring of groundwater, leachate collection, and gas flaring is legally mandated for 15 to 25 years to ensure environmental isolation."),
    ("seq", "Process of Vermicomposting Setup",
     "Arrange the practical construction steps of an outdoor vermicomposting bed:",
     ["Placement of a 15–20 cm base drainage layer of broken bricks, gravel, and coarse dry plant stalks", "Addition of a layer of partially pre-decomposed farmyard manure and shredded organic vegetable waste", "Inoculation of the bed with live earthworms (Eisenia fetida) and covering with moist burlap gunny bags", "Periodic water misting to maintain 60–70% moisture content and darkness until rich dark vermicast is harvested"],
     "I -> II -> III -> IV",
     "Vermicomposting requires: drainage bedding, partially decomposed manure/food, earthworm introduction with moist burlap shade, and controlled moisture maintenance."),
    ("mcq", "Fly Ash vs Bottom Ash in Thermal Plants",
     "In pulverized coal thermal plants, 'Fly Ash' refers to the fine particulate powder carried upward in flue gases, whereas 'Bottom Ash' refers to:",
     "The coarser, fused slag particles that fall through the furnace grate to the bottom of the combustion chamber",
     ["The liquid chemicals discharged from the water cooling towers", "The pure sulfur gas emitted from the chimney", "The unburnt coal lumps stored in the outdoor rail yard"],
     "Fly ash is captured from flue gas by ESPs (80% of total ash), while bottom ash is heavier aggregate that falls to the bottom of the furnace (20%)."),
    ("mcq", "Garbage Vulnerability to Groundwater in Karst Regions",
     "Why is the siting of municipal waste landfills strictly prohibited on limestone 'Karst' topography?",
     "Because soluble limestone features interconnected subterranean caverns, sinkholes, and fractures that allow contaminated leachate to travel directly into regional aquifers without filtration",
     ["Because limestone immediately explodes upon contact with paper waste", "Because earthworms cannot survive in calcium-rich rock environments", "Because limestone causes all plastic to decompose into pure water"],
     "Karst terrain contains subterranean sinkholes and rapid underground conduit flow, allowing raw leachate to contaminate regional drinking aquifers instantly.")
]

# ==============================================================================
# Slot 22: Hazardous, Biomedical & Electronic Waste Management
# ==============================================================================
s22_raw = [
    ("mcq", "Biomedical Waste 4-Color Segregation System",
     "Under the Biomedical Waste Management Rules, 2016, which color-coded container is specifically designated for human anatomical waste, animal waste, soiled dressings, and expired cytotoxic drugs?",
     "Yellow non-chlorinated plastic bags (destined for high-temperature Incineration or Plasma Pyrolysis)",
     ["Red plastic bags (destined for autoclaving and recycling)", "Blue cardboard boxes (destined for glassware autoclaving)", "White translucent puncture-proof containers (for needles and sharps)"],
     "Yellow bags are reserved for incinerable wastes: human/animal anatomical waste, soiled cotton dressings, chemical wastes, and discarded cytotoxic drugs."),
    ("stmt", "Red Bag and White Container Biomedical Segregation",
     "Under Biomedical Waste Rules 2016, contaminated recyclable plastics like disposable IV tubes, catheters, syringes (without needles), and urine bags go into Red bags.",
     "Waste sharps, including used hypodermic needles, scalpels, and blades, must be deposited in puncture-proof, leak-proof, tamper-proof White translucent containers.", 1,
     "Both Statement I and Statement II are correct. Red containers are for autoclaving/recycling contaminated plastics; White containers are for sharps to prevent needle-stick injuries."),
    ("ar", "Chlorinated Plastics Ban in Biomedical Waste Bags",
     "The Biomedical Waste Management Rules, 2016, strictly prohibit the use of chlorinated plastic bags and gloves in healthcare establishments.",
     "When chlorinated plastics are burned in biomedical incinerators, they generate extremely carcinogenic Polychlorinated Dibenzo-p-Dioxins (PCDDs) and Dibenzofurans (PCDFs).", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Phase-out of chlorinated bags (like PVC) eliminates dioxin formation during mandatory medical waste incineration."),
    ("match", "Biomedical Waste Color Codes and Treatment Technologies",
     "Match the biomedical waste container color in List I with its mandated treatment method in List II:",
     [("A", "Yellow Bag"),
      ("B", "Red Bag"),
      ("C", "White Translucent Container"),
      ("D", "Blue Box / Pouch")],
     [("I", "Incineration / Plasma Pyrolysis / Deep burial in remote rural areas"),
      ("II", "Autoclaving or Microwaving followed by shredding and plastic recycling"),
      ("III", "Autoclaving / Dry heat sterilization followed by shredding or encapsulation"),
      ("IV", "Disinfection (soaking in sodium hypochlorite) or autoclaving for glass recycling")],
     "A-I, B-II, C-III, D-IV",
     "Yellow is incinerated, Red is autoclaved and shredded, White sharps are shredded/encapsulated, and Blue glass is disinfected/recycled."),
    ("mcq", "Manifest System for Hazardous Waste Tracking",
     "Under the Hazardous and Other Wastes Rules, 2016, what is the 'Manifest System' (Form 10)?",
     "A color-coded 7-copy tracking document that accompanies hazardous waste shipments from the generator to the transporter and final disposal facility (TSDF)",
     ["A public marketing brochure advertising cheap hazardous chemical sales", "A single tax receipt issued by municipal councils for trash pickup", "An export customs declaration for shipping plastic garbage overseas"],
     "The 7-copy manifest system ensures cradle-to-grave tracking, requiring signatures from generator, transporter, and TSDF operator to prevent illegal fly-tipping."),
    ("mcq", "Treatment, Storage, and Disposal Facility (TSDF)",
     "A specialized central environmental infrastructure designed to securely receive, stabilize, neutralize, and permanently store hazardous industrial wastes in engineered double-lined cells is known as a:",
     "Treatment, Storage, and Disposal Facility (TSDF)",
     ["Municipal Composting Depot", "Agricultural Grain Silo", "Urban Sewage Sump"],
     "A TSDF features chemical stabilization units, hazardous waste incinerators, and secured engineered landfills (SLFs) for hazardous industrial sludges."),
    ("stmt", "E-Waste Management Rules 2022 and EPR Targets",
     "The E-Waste (Management) Rules, 2022, mandate that producers of Electrical and Electronic Equipment (EEE) must meet rising Extended Producer Responsibility (EPR) recycling targets.",
     "The rules introduce a market-based EPR credit trading mechanism where registered recyclers generate electronic credits that producers can purchase to meet targets.", 1,
     "Both Statement I and Statement II are correct. The 2022 E-waste rules establish an online portal with digital EPR certificates generated by formal recyclers."),
    ("seq", "Process Flow of Biomedical Waste Management in a Hospital",
     "Arrange the sequential operational chain for biomedical waste generated in an operational theater:",
     ["Immediate segregation at the point of generation into color-coded containers (Yellow, Red, White, Blue)", "Barcoding and secure sealing of bags followed by intra-facility transport to a dedicated, locked central storage room", "Collection and refrigerated GPS-tracked transportation by an authorized Common Biomedical Waste Treatment Facility (CBWTF)", "Final treatment (high-temperature incineration or autoclaving/shredding) within 48 hours of generation"],
     "I -> II -> III -> IV",
     "Biomedical waste lifecycle: point-of-use segregation, barcoding/storage, CBWTF transport, and final treatment within the statutory 48-hour deadline."),
    ("mcq", "Toxic Heavy Metals in Electronic Waste (E-Waste)",
     "Informal backyard dismantling and acid leaching of printed circuit boards (PCBs) and cathode ray tubes (CRTs) in e-waste hubs releases which toxic cocktail of heavy metals?",
     "Lead (Pb), Mercury (Hg), Cadmium (Cd), and Hexavalent Chromium",
     ["Pure non-toxic molecular calcium and potassium", "Beneficial vitamin supplements", "Inert nitrogen and carbon dioxide gases"],
     "E-waste contains lead in solder and CRT glass, mercury in flat-panel backlights, cadmium in SMD resistors, and brominated flame retardants in plastics."),
    ("ar", "Informal E-Waste Recycling Hazards in Seelampur",
     "Informal e-waste recycling clusters (such as Seelampur in Delhi or Moradabad in UP) cause severe health disorders and environmental contamination.",
     "Informal workers use open cyanide-acid baths and primitive open-flame solder torching to extract trace gold and copper without any protective gear or ventilation.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Unregulated acid stripping releases toxic fumes and dumps acid-heavy metal residues directly into drains and soil."),
    ("mcq", "Barcoding System on Biomedical Waste Bags",
     "Why did the Ministry of Environment mandate unique 'Barcode and GPS tracking systems' on all biomedical waste bags collected from hospitals?",
     "To enable real-time tracking of waste bags from generation to final disposal, preventing illegal pilferage, unauthorized reuse, and roadside dumping",
     ["To allow retail patients to purchase discarded surgical syringes online", "To scan prices for municipal property tax assessment", "To allow waste bags to pass through airport customs clearance"],
     "The CPCB barcoding mandate tracks bag weight and transit via mobile apps, ensuring healthcare waste reaches CBWTFs without being siphoned off for illegal resale."),
    ("mcq", "Autoclaving Mechanism in Biomedical Waste",
     "In biomedical waste treatment, an industrial 'Autoclave' sterilizes contaminated plastic waste and surgical equipment by subjecting it to:",
     "Pressurized saturated steam at a temperature of at least 121 degrees Celsius (at 15 psi) for a prescribed residence time",
     ["Sub-zero freezing using liquid nitrogen at -196 degrees Celsius", "Direct exposure to open wood fire flames", "Immersion in room-temperature distilled tap water"],
     "Autoclaving uses high-pressure steam (121 C at 15 psi for 30 min, or 135 C at 30 psi for 15 min) to thermally destroy all bacterial vegetative cells and bacterial endospores."),
    ("match", "E-Waste Components and Toxic Substances",
     "Match the electronic component in List I with its hazardous constituent in List II:",
     [("A", "Cathode Ray Tube (CRT) glass funnel"),
      ("B", "Fluorescent backlights in older LCD monitors"),
      ("C", "Rechargeable Nickel-Cadmium batteries"),
      ("D", "Plastic computer casings and circuit boards")],
     [("I", "High lead oxide (PbO) content shielding X-rays"),
      ("II", "Elemental Mercury vapor (Hg)"),
      ("III", "Cadmium (Cd) toxic heavy metal"),
      ("IV", "Polybrominated Diphenyl Ethers (PBDE flame retardants)")],
     "A-I, B-II, C-III, D-IV",
     "CRTs contain lead, LCD backlights contain mercury, Ni-Cd batteries contain cadmium, and circuit board plastics contain PBDE flame retardants."),
    ("mcq", "Secured Landfill (SLF) for Hazardous Waste",
     "How does a 'Secured Landfill' (SLF) constructed in a hazardous waste TSDF differ from an ordinary municipal solid waste landfill?",
     "It utilizes a double composite liner system (two geomembranes with a leak-detection drainage layer between them) and accepts only chemically stabilized, non-biodegradable wastes",
     ["It is built on wooden rafts floating on coastal estuaries", "It accepts raw kitchen garbage and food wastes mixed with water", "It is left completely open without any top cover forever"],
     "Secured landfills feature double synthetic liners, leak-detection systems between liners, and accept only stabilized, chemically fixed hazardous industrial sludges."),
    ("mcq", "Basel Convention on Hazardous Wastes",
     "Adopted in 1989, the international 'Basel Convention' was negotiated primarily to combat which environmental injustice?",
     "The transboundary movement and dumping of toxic hazardous wastes from developed industrialized nations into developing countries",
     ["The hunting of migratory songbirds in European forests", "The international export of refined olive oil", "The trade in agricultural grain seeds between neighboring states"],
     "The Basel Convention regulates the transboundary movement of hazardous wastes, preventing the 'toxic colonialism' of dumping Western hazardous waste in developing nations."),
    ("stmt", "Common Biomedical Waste Treatment Facility (CBWTF)",
     "Under CPCB guidelines, individual hospitals are discouraged from operating isolated incinerators; instead, healthcare units within a 75 km radius must send waste to a centralized CBWTF.",
     "Centralized CBWTFs ensure continuous emission monitoring, state-of-the-art scrubbers, and high economies of scale that single nursing homes cannot maintain.", 1,
     "Both Statement I and Statement II are correct. Centralized CBWTFs eliminate small, polluting hospital chimneys and allow 24x7 online emission monitoring by pollution boards."),
    ("mcq", "Microwaving in Biomedical Waste Treatment",
     "How does industrial microwave irradiation disinfect infectious medical waste?",
     "Electromagnetic radio waves heat the water molecules contained within microbes and organic waste to boiling temperatures, denaturing all viral and bacterial proteins",
     ["Gamma radiation permanently mutates DNA into synthetic rubber", "High-voltage electric arcs vaporize metal objects into air", "Ultrasound waves physically crush all glass bottles into powder"],
     "Microwaving utilizes thermal disinfection: high-frequency electromagnetic waves rapidly excite water molecules, thermally destroying pathogens in shredded moist waste."),
    ("seq", "Dismantling and Recovery Sequence in a Formal E-Waste Plant",
     "Arrange the formal, environmentally sound processing steps of discarded electronic waste:",
     ["De-manufacturing: manual dismantling to segregate hazardous parts (mercury switches, batteries, capacitors)", "Mechanical shredding of remaining electronic circuit boards and housings into uniform small fragments", "Multi-stage physical separation (magnetic drums, eddy current separators, air classifiers) isolating ferrous and non-ferrous metals", "Hydrometallurgical chemical refining recovering high-purity precious metals (Gold, Silver, Palladium, Copper) with zero toxic emissions"],
     "I -> II -> III -> IV",
     "Formal e-waste recycling: manual hazardous removal, shredding, density/eddy-current sorting, and hydrometallurgical closed-loop metal refining."),
    ("mcq", "Hazardous Waste Characteristic Properties",
     "Under environmental statutory definitions, a waste is legally classified as 'Hazardous' if it exhibits one or more of which four fundamental dangerous characteristics?",
     "Ignitability, Corrosivity, Reactivity, and Toxicity (ICRT)",
     ["Color, Sweetness, Fragrance, and Softness", "Weight, Length, Volume, and Density", "Elasticity, Transparency, Porosity, and Magnetism"],
     "Hazardous waste is defined internationally and under EPA/Indian rules by the 'ICRT' criteria: Ignitability (flashpoint < 60 C), Corrosivity (pH <= 2 or >= 12.5), Reactivity, and Toxicity."),
    ("mcq", "Deep Well Injection of Hazardous Industrial Liquid Wastes",
     "The controversial hazardous waste disposal practice of 'Deep Well Injection' involves:",
     "Pumping liquid industrial wastes under high pressure into deep, isolated porous limestone or sandstone rock formations thousands of meters below freshwater aquifers",
     ["Injecting liquid chemicals directly into domestic drinking water pipelines", "Spraying liquid wastes from airplanes over mountain snowfields", "Pouring chemical effluent into active volcano craters"],
     "Deep well injection forces hazardous liquid waste into subterranean geological strata below impervious shale caprocks, carrying long-term risks of fault seismic leakage.")
]

# ==============================================================================
# Slot 23: Plastic Pollution & Plastic Waste Management Rules
# ==============================================================================
s23_raw = [
    ("mcq", "Nationwide Single-Use Plastic (SUP) Ban in India",
     "Effective from July 1, 2022, the Government of India enacted a nationwide statutory ban under the Plastic Waste Management Rules on the manufacture, import, stocking, distribution, sale, and use of:",
     "Identified Single-Use Plastic (SUP) items having low utility and high littering potential (including plastic earbuds, balloon sticks, candy sticks, thermocol decorations, plastic plates, cups, cutlery, and PVC banners < 100 microns)",
     ["All life-saving plastic medical syringes and blood bags", "All plastic components inside computer laptops and televisions", "All plastic insulation surrounding electrical transmission wires"],
     "The July 1, 2022 ban prohibited 19 specific single-use plastic items with low utility and high environmental littering potential."),
    ("stmt", "Plastic Carry Bag Thickness Evolution in India",
     "Under the Plastic Waste Management (Amendment) Rules, 2021, the minimum thickness of plastic carry bags was increased from 50 microns to 75 microns with effect from September 30, 2021.",
     "The minimum thickness was further increased to 120 microns with effect from December 31, 2022, to make bags durable and economically viable for ragpickers to collect and recycle.", 1,
     "Both Statement I and Statement II are correct. Increasing bag thickness to 120 microns prevents ultrathin plastic bags from being discarded as uncollectible litter."),
    ("ar", "Microplastics Ecological Menace",
     "Microplastics (plastic particles smaller than 5 millimeters in diameter) pose a severe threat to marine and freshwater organisms.",
     "Due to their high surface-area-to-volume ratio and hydrophobic nature, microplastics adsorb persistent organic pollutants (POPs) from water and are ingested by filter feeders, biomagnifying up food chains.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Microplastics act as sponges for toxic chemicals (PCBs, DDT) and enter fish, shellfish, and human food webs."),
    ("match", "Plastic Resin Identification Codes and Polymers",
     "Match the international Resin Identification Code (RIC) in List I with its chemical polymer in List II:",
     [("A", "Number 1 (PET / PETE)"),
      ("B", "Number 2 (HDPE)"),
      ("C", "Number 3 (PVC)"),
      ("D", "Number 5 (PP)")],
     [("I", "Polyethylene Terephthalate (Clear beverage bottles, polyester fibers)"),
      ("II", "High-Density Polyethylene (Milk jugs, shampoo bottles, detergent tubs)"),
      ("III", "Polyvinyl Chloride (Plumbing pipes, cable insulation, window frames)"),
      ("IV", "Polypropylene (Bottle caps, drinking straws, microwaveable food containers)")],
     "A-I, B-II, C-III, D-IV",
     "1 is PET (water bottles), 2 is HDPE (milk jugs), 3 is PVC (pipes), 4 is LDPE (bags), 5 is PP (caps), 6 is PS (thermocol), and 7 is Other."),
    ("mcq", "Plastic Man of India and Plastic Roads",
     "Prof. Rajagopalan Vasudevan of Thiagarajar College of Engineering, Madurai, known as the 'Plastic Man of India', patented which revolutionary sustainable technology?",
     "Blending shredded post-consumer waste plastic with hot aggregate and bitumen to construct durable, pothole-resistant 'Plastic Roads'",
     ["Converting waste plastic into direct human edible vitamins", "Using plastic sheets to completely cover the Himalayan glaciers from melting", "Launching waste plastic rockets into the Sun"],
     "Prof. Vasudevan developed the technology of mixing shredded waste plastic (PP, PE, PS) with hot stone aggregate (170 C) before adding bitumen, creating resilient, water-resistant roads."),
    ("mcq", "Primary vs Secondary Microplastics",
     "What is the difference between 'Primary Microplastics' and 'Secondary Microplastics' in environmental science?",
     "Primary microplastics are intentionally manufactured at microscopic sizes (microbeads in cosmetics, industrial nurdles); Secondary microplastics result from the fragmentation of larger plastic debris via solar UV and mechanical weathering",
     ["Primary microplastics are biodegradable, while secondary microplastics are made of solid steel", "Primary microplastics float in air, while secondary microplastics exist only in volcanic lava", "There is zero difference; both terms are identical"],
     "Primary microplastics are manufactured small (cosmetic microbeads, virgin resin pellets); secondary microplastics fragment from bottles, bags, and fishing nets."),
    ("stmt", "Extended Producer Responsibility (EPR) Plastic Packaging Categories",
     "The Plastic Waste Management (Amendment) Rules, 2022, established mandatory EPR targets across four distinct categories of plastic packaging.",
     "The four categories are: Category I (Rigid plastics), Category II (Flexible single-layer/multi-layer plastics), Category III (Multi-layered plastic packaging with at least one non-plastic layer), and Category IV (Plastic sheets and carry bags/compostable plastics).", 1,
     "Both Statement I and Statement II are correct. CPCB's centralized EPR portal tracks recycling obligations across Categories I, II, III, and IV."),
    ("seq", "Mechanical Recycling Process Flow of Waste PET Bottles",
     "Arrange the sequential operational steps in an industrial bottle-to-fiber mechanical PET recycling plant:",
     ["Collection and optical sorting of post-consumer clear PET bottles, removing caps and PVC labels", "Mechanical granulation and crushing of washed bottles into uniform PET flakes", "Intense hot caustic washing and density separation in float-sink hydro-tanks to remove chemical adhesives", "Drying, melting in an extruder, and spinning molten polymer into recycled polyester staple fiber (rPET) for garments"],
     "I -> II -> III -> IV",
     "Mechanical PET recycling: optical sorting, flake crushing, hot caustic washing/density separation, and extrusion into recycled polyester fiber."),
    ("mcq", "Great Pacific Garbage Patch Mechanism",
     "The 'Great Pacific Garbage Patch', a vast oceanic zone of concentrated plastic debris between California and Hawaii, is formed primarily by:",
     "The circular rotating currents of the North Pacific Subtropical Gyre that pull in and trap floating plastic debris from across the Pacific rim",
     ["A deliberate international treaty establishing an offshore plastic landfill", "An undersea volcanic explosion of molten plastic lava", "Continuous direct dumping by naval aircraft carriers"],
     "Oceanic gyres (driven by global wind patterns and Coriolis forces) act as giant whirlpools, accumulating millions of tons of floating plastic and microplastics."),
    ("ar", "Marine Turtle Ingestion of Plastic Bags",
     "Pelagic marine sea turtles (especially Leatherbacks) frequently ingest floating translucent plastic polythene bags.",
     "Floating plastic bags visually mimic the appearance and movement of marine jellyfish, which constitute the primary natural prey of sea turtles.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Sea turtles mistake floating plastic bags for jellyfish, causing fatal gastrointestinal impaction and starvation."),
    ("mcq", "Plastic Pyrolysis (Chemical Recycling)",
     "In advanced chemical recycling of mixed waste plastics, the thermo-chemical process of 'Pyrolysis' converts non-recyclable plastic polymers into:",
     "Pyrolysis oil (synthetic hydrocarbon crude), flammable gas, and solid carbon char in the absence of oxygen",
     ["Pure non-toxic drinking mineral water and oxygen gas", "Solid gold bars and diamond crystals", "Concentrated hydrochloric acid and nuclear isotopes"],
     "Plastic pyrolysis cracks long-chain polymers into liquid synthetic crude oil (pyrolysis oil) that can be refined into fuels or new virgin-grade chemicals."),
    ("mcq", "Microbeads Ban in Cosmetics",
     "Why have international environmental bodies and several countries banned plastic 'microbeads' in rinse-off cosmetic exfoliating scrubs and toothpastes?",
     "Because billions of tiny spherical polyethylene beads wash directly down household drains, bypass municipal sewage treatment filters, and enter aquatic food chains",
     ["Because microbeads cause tooth enamel to turn into solid diamond", "Because microbeads cause bathroom water pipes to freeze in summer", "Because microbeads are expensive precious gemstones"],
     "Microbeads in facial scrubs and toothpaste pass straight through wastewater treatment screens into rivers and oceans, where fish ingest them as food."),
    ("match", "Plastic Pollution Terms and Descriptions",
     "Match the marine pollution concept in List I with its description in List II:",
     [("A", "Ghost Fishing"),
      ("B", "Nurdles"),
      ("C", "Plastisphere"),
      ("D", "Oxo-degradable Plastic")],
     [("I", "Commercial synthetic fishing nets abandoned or lost at sea that continue trapping and killing marine life indefinitely"),
      ("II", "Pre-production virgin plastic resin pellets spilled during maritime transport that litter global beaches"),
      ("III", "The novel ecological community of microbes, fungi, and invertebrates that live on floating human plastic debris"),
      ("IV", "Conventional plastic blended with metal pro-oxidant additives that rapidly fragments into invisible toxic microplastics rather than truly biodegrading")],
     "A-I, B-II, C-III, D-IV",
     "Ghost fishing describes lost nets, nurdles are raw pellets, plastisphere is the microbial biofilm on ocean plastic, and oxo-degradables fragment into microplastics."),
    ("mcq", "Compostable vs Biodegradable Plastic Standards",
     "Under Indian Standard IS/ISO 17088, what legally distinguishes certified 'Compostable Plastics' from conventional petro-plastics?",
     "They must undergo complete biological degradation into CO2, water, and biomass in an industrial composting facility within 180 days, leaving zero toxic residues",
     ["They can be heated to 1,000 degrees Celsius without melting", "They are made of synthetic lead and cadmium polymers", "They dissolve instantaneously in room air within 5 seconds"],
     "Certified compostable plastics (e.g. PLA, PBAT) must meet IS/ISO 17088 standards, achieving 90% biodegradation in commercial composters within 6 months."),
    ("mcq", "Bhopal Memorial Hospital Plastic Blood Bag Safety",
     "Why were single-use flexible plastic medical devices (such as blood transfusion bags, IV lines, and surgical gloves made of plasticized PVC) exempted from the Single-Use Plastic ban?",
     "Because they provide irreplaceable sterility, bio-compatibility, and life-saving infection control in healthcare where non-plastic alternatives are medically unviable",
     ["Because the government owns all multinational medical corporations", "Because medical plastics instantly dissolve in blood without leaving waste", "Because hospitals do not generate any solid waste"],
     "Medical single-use plastics are vital for sterile infection prevention; their high public health utility exempts them from general single-use consumer bans."),
    ("stmt", "CPCB Centralized EPR Portal for Plastic Packaging",
     "The Central Pollution Control Board (CPCB) operationalized an automated centralized online portal for the registration of Producers, Importers, and Brand Owners (PIBOs).",
     "The portal facilitates the trading and generation of digital EPR certificates, ensuring accountability and cross-checking between recyclers and corporate brand owners.", 1,
     "Both Statement I and Statement II are correct. CPCB's digital portal eliminates fraudulent paper claims by cross-verifying verified recycling volumes with brand targets."),
    ("mcq", "Global Plastics Treaty (UN Plastic Agreement)",
     "In March 2022, at the UN Environment Assembly (UNEA 5.2) in Nairobi, world nations adopted a historic resolution to negotiate a legally binding international treaty to:",
     "End plastic pollution across the entire lifecycle of plastics, from extraction and design to production, consumption, and waste management",
     ["Mandate that all automobiles worldwide be constructed 100% out of plastic", "Ban all recycling of plastics across developed countries", "Relocate all global plastic waste onto artificial floating islands in Antarctica"],
     "Resolution 5/14 mandated an Intergovernmental Negotiating Committee (INC) to craft a legally binding global treaty tackling plastic pollution across its full lifecycle."),
    ("seq", "Environmental Fate of a Discarded Polythene Bag in Nature",
     "Arrange the progressive physical and chemical degradation steps of an ordinary polyethylene bag littered on a beach:",
     ["Solar Ultraviolet (UV) radiation breaks chemical carbon-carbon polymer backbone bonds through photo-oxidation", "The plastic polymer becomes brittle, losing mechanical tensile strength and developing microscopic surface cracks", "Mechanical wave action and wind abrasion shatter the brittle embrittled plastic into millions of microplastic fragments (< 5 mm)", "Microscopic plastic fragments persist in ocean sediments and water column for centuries, adsorbing chemical toxins"],
     "I -> II -> III -> IV",
     "Plastic degradation sequence: UV photo-oxidation, polymer embrittlement, mechanical fragmentation into microplastics, and centuries of environmental persistence."),
    ("mcq", "Bio-PET and Plant-Based Plastics",
     "How do 'Bio-based plastics' (like Bio-PET made from sugarcane ethanol) differ fundamentally from traditional petroleum-based plastics in their environmental footprint?",
     "They are synthesized from renewable biological biomass feedstocks rather than fossil petrochemicals, reducing carbon footprint, although they are chemically identical and non-biodegradable",
     ["They dissolve completely in cold water within 10 seconds", "They produce pure oxygen gas when discarded on roadsides", "They turn into fertile garden loam within 24 hours of manufacture"],
     "Bio-PET uses plant ethanol instead of petroleum, capturing biological carbon during crop growth, but remains chemically identical to standard PET and does not biodegrade."),
    ("mcq", "Thermosetting vs Thermoplastic Polymers in Recycling",
     "Why are 'Thermoplastics' (like Polyethylene and Polypropylene) easily recyclable via melting, whereas 'Thermosetting plastics' (like Bakelite and Melamine) cannot be remelted and reshaped?",
     "Thermoplastics consist of linear or branched polymer chains held by weak intermolecular forces that soften when heated, while Thermosetting plastics possess permanent covalent cross-links that decompose rather than melt",
     ["Thermoplastics are made of water, while thermosets are made of rock", "Thermosetting plastics immediately explode at room temperature", "Thermoplastics contain living bacterial cells that digest the plastic"],
     "Thermoplastics melt reversibly upon heating; thermosetting plastics form permanent three-dimensional cross-linked networks that char and burn instead of melting.")
]

# ==============================================================================
# Slot 24: Sustainable Development Concepts & Historical Milestones
# ==============================================================================
s24_raw = [
    ("mcq", "Brundtland Commission Canonical Definition",
     "The landmark 1987 report 'Our Common Future' by the World Commission on Environment and Development (chaired by Gro Harlem Brundtland) defined Sustainable Development as:",
     "'Development that meets the needs of the present without compromising the ability of future generations to meet their own needs'",
     ["'Maximizing immediate gross domestic product by rapidly liquidating all fossil fuel assets'", "'Halting all technological research and returning human societies to cave-dwelling lifestyles'", "'Relocating all manufacturing industries from developed nations to the deep ocean floor'"],
     "The Brundtland Commission's 1987 definition remains the universal international benchmark for intergenerational equity and sustainable development."),
    ("stmt", "Two Key Concepts of Brundtland Definition",
     "The Brundtland definition contains within it the concept of 'needs', in particular the essential needs of the world's poor, to which overriding priority should be given.",
     "It also incorporates the concept of 'limitations' imposed by the state of technology and social organization on the environment's ability to meet present and future needs.", 1,
     "Both Statement I and Statement II are correct. Brundtland explicitly balances eradicating poverty ('needs') with respecting ecological carrying capacity ('limits')."),
    ("ar", "Club of Rome Limits to Growth Report",
     "The 1972 'Limits to Growth' report published by the Club of Rome used system dynamics computer modeling (World3) to simulate the global future.",
     "The model demonstrated that continued exponential growth in population, industrial output, and pollution within a finite planetary environment would lead to overshoot and economic collapse by the 21st century.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Dennis Meadows and the MIT team warned that unchecked industrial-demographic expansion against finite ecological sinks inevitably drives systemic collapse."),
    ("match", "Landmark International Environmental Conferences",
     "Match the historic international environment conference in List I with its milestone outcome in List II:",
     [("A", "Stockholm Conference (1972)"),
      ("B", "Rio Earth Summit / UNCED (1992)"),
      ("C", "Johannesburg Summit / WSSD (2002)"),
      ("D", "Rio+20 Conference (2012)")],
     [("I", "First global UN conference on human environment; established the UN Environment Programme (UNEP)"),
      ("II", "Adopted Agenda 21, the Rio Declaration, and opened UNFCCC and CBD for signature"),
      ("III", "Focused on sustainable development partnerships, poverty eradication, and water/sanitation access"),
      ("IV", "Adopted the outcome document 'The Future We Want' and initiated the process to formulate the SDGs")],
     "A-I, B-II, C-III, D-IV",
     "Stockholm 1972 created UNEP, Rio 1992 produced Agenda 21 and Rio conventions, Johannesburg 2002 emphasized implementation, and Rio+20 produced 'The Future We Want'."),
    ("mcq", "Three Pillars of Sustainable Development",
     "Sustainable Development is universally conceptualized as the harmonious convergence and balance of which three fundamental pillars ('Triple Bottom Line')?",
     "Economic sustainability, Social equity, and Environmental protection",
     ["Military dominance, Industrial robotics, and Space exploration", "Monetary inflation, Urban gentrification, and Corporate monopolies", "Agricultural monoculture, Chemical fertilizer subsidy, and Deforestation"],
     "True sustainability requires the integration of environmental protection, economic viability, and social inclusion/equity."),
    ("mcq", "Agenda 21 Nature and Scope",
     "Adopted by over 178 governments at the 1992 Rio Earth Summit, 'Agenda 21' is formally defined as:",
     "A comprehensive, non-binding global action blueprint for sustainable development to be implemented at global, national, and local levels by UN organizations, governments, and major groups",
     ["A legally binding military defense pact requiring nuclear disarmament by 2021", "A commercial trade agreement imposing tariffs on agricultural grain exports", "A resolution mandating the privatization of all public freshwater lakes"],
     "Agenda 21 is the foundational UN global action blueprint for the 21st century, addressing social, economic, and ecological dimensions of development."),
    ("stmt", "Intergenerational vs Intragenerational Equity",
     "Intergenerational equity demands that the present generation must hold the Earth in trust and pass it on to future generations in no worse condition than they received it.",
     "Intragenerational equity demands fair and equitable distribution of resources, wealth, and opportunities among different social classes and nations within the present generation.", 1,
     "Both Statement I and Statement II are correct. Sustainability requires justice across time (intergenerational) as well as justice across contemporary societies (intragenerational)."),
    ("seq", "Chronological Milestones of the Global Sustainable Development Architecture",
     "Arrange these historical environmental milestones in chronological order:",
     ["UN Conference on the Human Environment in Stockholm creating UNEP (1972)", "Brundtland Commission releases 'Our Common Future' defining sustainable development (1987)", "UN Conference on Environment and Development (UNCED / Rio Earth Summit) adopting Agenda 21 (1992)", "UN Sustainable Development Summit in New York adopting the 2030 Agenda and 17 SDGs (2015)"],
     "I -> II -> III -> IV",
     "Milestone progression: Stockholm (1972), Brundtland Report (1987), Rio Earth Summit (1992), and UN SDGs adoption (2015)."),
    ("mcq", "Ecology is Permanent Economy Slogan",
     "Which legendary Indian environmental activist and Chipko movement leader popularized the celebrated slogan 'Ecology is permanent economy'?",
     "Sunderlal Bahuguna",
     ["Verghese Kurien", "M.S. Swaminathan", "Amartya Sen"],
     "Sunderlal Bahuguna coined the famous Chipko slogan 'Ecology is permanent economy', reminding planners that ecological stability underpins all economic survival."),
    ("ar", "Human Development Index (HDI) vs Pure GDP",
     "The United Nations Development Programme (UNDP) created the Human Development Index (HDI) to evaluate national progress beyond pure Gross Domestic Product (GDP).",
     "Economic growth measured solely by GDP accounts for monetary transactions but ignores health, life expectancy, educational attainment, and environmental degradation.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Mahbub ul Haq and Amartya Sen developed HDI (combining life expectancy, education, and GNI per capita) to reflect holistic human well-being."),
    ("mcq", "Genuine Progress Indicator (GPI)",
     "Unlike GDP, which counts pollution cleanup and disease expenditures as positive economic growth, the 'Genuine Progress Indicator' (GPI):",
     "Deducts environmental degradation, resource depletion, crime, and social inequality costs while adding value for unpaid domestic and volunteer work",
     ["Measures only the total value of diamond and gold reserves in central banks", "Measures the number of passenger cars manufactured per hour", "Counts all military weapon production as social welfare"],
     "GPI adjusts GDP by subtracting costs of environmental pollution, ozone depletion, and crime, providing a true measure of net sustainable economic welfare."),
    ("mcq", "Weak vs Strong Sustainability Paradigm",
     "In ecological economics, what is the fundamental philosophical distinction between 'Weak Sustainability' and 'Strong Sustainability'?",
     "Weak sustainability assumes that manufactured human capital can completely substitute for natural capital, whereas Strong sustainability asserts that natural capital provides critical, non-substitutable life-support services",
     ["Weak sustainability requires zero economic activity, while strong sustainability requires burning all forests", "Weak sustainability applies only to polar biomes, while strong sustainability applies only to tropical deserts", "Both paradigms are identical in assuming that nature has zero economic value"],
     "Weak sustainability (Hartwick-Solow) assumes manufactured capital can replace depleted nature; Strong sustainability (Daly) insists natural life-support systems are irreplaceable."),
    ("match", "Sustainable Development Concepts and Authors",
     "Match the sustainable economic concept in List I with its pioneer in List II:",
     [("A", "Small is Beautiful: Economics as if People Mattered"),
      ("B", "Steady-State Economy / Ecological Economics"),
      ("C", "The Tragedy of the Commons"),
      ("D", "Natural Capitalism")],
     [("I", "E.F. Schumacher"),
      ("II", "Herman Daly"),
      ("III", "Garrett Hardin"),
      ("IV", "Amory Lovins and Paul Hawken")],
     "A-I, B-II, C-III, D-IV",
     "Schumacher wrote 'Small is Beautiful', Herman Daly founded steady-state economics, Garrett Hardin wrote 'Tragedy of the Commons', and Lovins authored 'Natural Capitalism'."),
    ("mcq", "E.F. Schumacher Intermediate Technology",
     "In his seminal 1973 book 'Small is Beautiful', British economist E.F. Schumacher advocated 'Intermediate Technology' (Appropriate Technology), which is characterized by:",
     "Decentralized, low-cost, labor-intensive, ecologically gentle technologies that empower local communities without causing environmental devastation",
     ["Massive automated nuclear mega-plants controlled by foreign conglomerates", "Reverting entirely to stone-age tools without any mechanical knowledge", "High-speed space shuttles operating on commercial diesel fuel"],
     "Schumacher argued for intermediate technology: human-scale, ecologically sound, affordable tools that enhance employment and local self-reliance."),
    ("mcq", "Steady-State Economy Concept (Herman Daly)",
     "Former World Bank senior economist Herman Daly formulated the concept of a 'Steady-State Economy', defined as an economy with:",
     "A constant population and a constant stock of physical wealth maintained at minimum rates of throughput (resource extraction and waste generation) within ecological limits",
     ["Infinite exponential GDP expansion growing at 15% annually forever", "Complete nationalization of all private enterprises by international bankers", "An economy where money is replaced exclusively by bartering cattle"],
     "Daly's Steady-State Economy operates within thermodynamic limits, maintaining constant stocks of physical capital with minimal metabolic throughput."),
    ("stmt", "Precautionary Principle in Environmental Law",
     "Principle 15 of the 1992 Rio Declaration formally articulates the 'Precautionary Principle'.",
     "The principle dictates that where there are threats of serious or irreversible damage, lack of full scientific certainty shall not be used as a reason for postponing cost-effective measures to prevent environmental degradation.", 1,
     "Both Statement I and Statement II are correct. Precautionary principle shifts the burden of proof to potential polluters to prove their actions will not cause irreversible harm."),
    ("mcq", "Polluter Pays Principle (PPP)",
     "First endorsed by the OECD in 1972 and enshrined in Principle 16 of the Rio Declaration, the 'Polluter Pays Principle' dictates that:",
     "The financial costs of pollution prevention, control, and environmental cleanup should be borne by the party responsible for causing the pollution, rather than by the public or taxpayer",
     ["The government must pay cash subsidies to polluting industries to compensate them for operating in cities", "Citizens who complain about pollution must pay fines to the municipal council", "Polluting factories receive 100% tax exemptions"],
     "The Polluter Pays Principle internalizes environmental costs: polluters must bear the full expense of pollution abatement and environmental remediation."),
    ("seq", "Evolutionary Steps of Corporate Environmental Management",
     "Arrange the historical phases of corporate industrial response to environmental challenges:",
     ["Passive Denial / Dilution: 'The solution to pollution is dilution' via taller smokestacks and open discharge", "End-of-Pipe Treatment: installing downstream filters, scrubbers, and treatment plants to comply with punitive statutory regulations", "Cleaner Production / Pollution Prevention (P2): modifying internal manufacturing processes to minimize waste generation at source", "Circular Economy / Industrial Ecology: designing closed-loop manufacturing where waste from one industry serves as raw material for another"],
     "I -> II -> III -> IV",
     "Corporate environmental response has evolved from denial/dilution to end-of-pipe scrubbers, cleaner production, and circular industrial ecology."),
    ("mcq", "Kuznets Curve in Environmental Economics",
     "The 'Environmental Kuznets Curve' (EKC) hypothesis postulates an inverted U-shaped relationship between economic development and environmental pollution, implying that:",
     "Environmental degradation initially intensifies during early industrialization, but after reaching a threshold per capita income level, pollution begins to decline as environmental quality is prioritized",
     ["Pollution increases exponentially forever regardless of income levels", "Poor nations have zero pollution while wealthy nations have 100% toxic air", "Economic growth has zero measurable correlation with environmental quality"],
     "The EKC posits an inverted-U curve: environmental quality worsens during early growth, then improves as societies become wealthier, cleaner, and service-oriented."),
    ("mcq", "Common But Differentiated Responsibilities (CBDR)",
     "Enshrined in Principle 7 of the Rio Declaration, the principle of 'Common But Differentiated Responsibilities' (CBDR) recognizes that:",
     "All nations share a common duty to protect the global environment, but developed countries must bear a greater burden because of their historical greenhouse emissions and superior technological/financial resources",
     ["Developing countries must pay financial reparations to industrialized Western powers for extracting coal", "All countries must reduce emissions by the exact same absolute tonnage regardless of their size or wealth", "Island nations must accept relocation without any international assistance"],
     "CBDR acknowledges historical emissions: while all states share global responsibility, developed nations must lead in financing and emissions cuts.")
]

# ==============================================================================
# Slot 25: Sustainable Development Goals (UN SDGs 2015–2030, NITI Aayog Index)
# ==============================================================================
s25_raw = [
    ("mcq", "UN 2030 Agenda and Total Number of SDGs",
     "Adopted by all 193 UN Member States at the UN Sustainable Development Summit in September 2015, 'Transforming our world: the 2030 Agenda for Sustainable Development' comprises how many SDGs and associated global targets?",
     "17 Goals and 169 Targets",
     ["8 Goals and 21 Targets", "50 Goals and 500 Targets", "10 Goals and 100 Targets"],
     "The 2030 Agenda encompasses 17 Sustainable Development Goals (SDGs) and 169 specific global targets to be achieved by 2030."),
    ("stmt", "MDGs vs SDGs Evolution",
     "The Millennium Development Goals (MDGs, 2000–2015) comprised 8 goals focused primarily on developing nations.",
     "The Sustainable Development Goals (SDGs, 2015–2030) are universally applicable to both developing and developed countries, integrating economic, social, and environmental dimensions.", 1,
     "Both Statement I and Statement II are correct. SDGs replaced MDGs, expanding from 8 targeted development goals to 17 universal, interconnected sustainability goals."),
    ("ar", "Interconnectedness of SDGs",
     "The Sustainable Development Goals are explicitly designed to be integrated and indivisible.",
     "Progress achieved in one goal (such as SDG 13: Climate Action) directly affects outcomes in other goals (such as SDG 1: No Poverty, SDG 2: Zero Hunger, and SDG 6: Clean Water).", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The SDGs form a holistic web where ecological protection, poverty eradication, and economic equity reinforce one another."),
    ("match", "Key Environmental Sustainable Development Goals",
     "Match the specific SDG number in List I with its official thematic title in List II:",
     [("A", "SDG 6"),
      ("B", "SDG 7"),
      ("C", "SDG 13"),
      ("D", "SDG 14")],
     [("I", "Ensure availability and sustainable management of water and sanitation for all"),
      ("II", "Ensure access to affordable, reliable, sustainable and modern energy for all"),
      ("III", "Take urgent action to combat climate change and its impacts"),
      ("IV", "Conserve and sustainably use the oceans, seas and marine resources for sustainable development (Life Below Water)")],
     "A-I, B-II, C-III, D-IV",
     "SDG 6 is Clean Water & Sanitation, SDG 7 is Affordable & Clean Energy, SDG 13 is Climate Action, and SDG 14 is Life Below Water."),
    ("mcq", "SDG 15 Official Mandate",
     "What is the official focus and title of Sustainable Development Goal 15 (SDG 15)?",
     "'Life on Land': Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt biodiversity loss",
     ["'Industry, Innovation and Infrastructure'", "'Reduced Inequalities between Nations'", "'Peace, Justice and Strong Institutions'"],
     "SDG 15 focuses on terrestrial ecosystems: halting deforestation, restoring degraded land and soil, and reversing biodiversity loss."),
    ("mcq", "SDG 12 Responsible Consumption and Production",
     "Target 12.3 under Sustainable Development Goal 12 (Responsible Consumption and Production) explicitly aims to achieve which food security benchmark by 2030?",
     "Halve per capita global food waste at the retail and consumer levels and reduce food losses along production and supply chains",
     ["Mandate that 100% of all food be produced from synthetic petroleum pills", "Double global consumption of red beef cattle per capita", "Abolish all commercial food packaging worldwide"],
     "SDG 12.3 commits to halving global per capita food waste at retail and consumer levels by 2030, slashing agricultural emissions and resource waste."),
    ("stmt", "NITI Aayog SDG India Index",
     "In India, NITI Aayog is the nodal institution responsible for coordinating, localizing, and monitoring the implementation of the Sustainable Development Goals.",
     "The NITI Aayog 'SDG India Index' computes a composite score (0 to 100) to rank all Indian States and Union Territories on their SDG performance annually.", 1,
     "Both Statement I and Statement II are correct. NITI Aayog monitors national SDG progress and publishes the SDG India Index dashboard ranking states."),
    ("seq", "SDG India Index Performance Categories",
     "Arrange the four official performance classification categories used by NITI Aayog's SDG India Index in increasing order of composite score:",
     ["Aspirant (Composite score between 0 and 49)", "Performer (Composite score between 50 and 64)", "Front Runner (Composite score between 65 and 99)", "Achiever (Composite score of 100)"],
     "I -> II -> III -> IV",
     "NITI Aayog categorizes states into 4 tiers: Aspirant (0–49), Performer (50–64), Front Runner (65–99), and Achiever (100)."),
    ("mcq", "Top Performing State on SDG India Index",
     "Which Indian state has consistently secured the top rank as the best-performing state on NITI Aayog's SDG India Index across multiple editions?",
     "Kerala",
     ["Bihar", "Uttar Pradesh", "Jharkhand"],
     "Kerala consistently leads the SDG India Index (Front Runner category), excelling in healthcare (SDG 3), clean water (SDG 6), and quality education (SDG 4)."),
    ("ar", "Localization of SDGs at Gram Panchayat Level",
     "The Ministry of Panchayati Raj in India adopted a thematic approach to localize the 17 SDGs into 9 localized themes at the Gram Panchayat level.",
     "Grassroots Panchayati Raj Institutions (PRIs) are directly responsible for delivering basic health, sanitation, drinking water, and rural infrastructure under the 11th Schedule.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Localizing SDGs into Gram Panchayat Development Plans (GPDP) operationalizes global goals in rural communities."),
    ("mcq", "Five Ps of the 2030 Agenda",
     "The preamble of the UN 2030 Agenda highlights that the 17 Sustainable Development Goals are structured around which 'Five Ps'?",
     "People, Planet, Prosperity, Peace, and Partnership",
     ["Power, Profit, Production, Politics, and Petroleum", "Pavements, Plastics, Pipelines, Ports, and Pesticides", "Paper, Printing, Packaging, Patents, and Promotion"],
     "The 2030 Agenda is framed around 5 foundational pillars: People (eradicating poverty), Planet (safeguarding ecosystems), Prosperity, Peace, and Partnership."),
    ("mcq", "Leave No One Behind (LNOB) Principle",
     "The transformative overarching operational pledge central to the UN 2030 Agenda for Sustainable Development is to:",
     "'Leave No One Behind' (LNOB), prioritizing the furthest behind first and eliminating structural inequalities",
     ["'Leave Nature to Market Forces'", "'Maximize National Military Exports'", "'Prioritize Mega-Cities over Rural Hamlets'"],
     "The central promise of the 2030 Agenda is 'Leave No One Behind' (LNOB), ensuring that development reaches the most marginalized populations first."),
    ("match", "Socio-Economic SDGs and Target Areas",
     "Match the SDG in List I with its primary objective in List II:",
     [("A", "SDG 1"),
      ("B", "SDG 2"),
      ("C", "SDG 3"),
      ("D", "SDG 5")],
     [("I", "End poverty in all its forms everywhere"),
      ("II", "End hunger, achieve food security, improved nutrition and promote sustainable agriculture"),
      ("III", "Ensure healthy lives and promote well-being for all at all ages"),
      ("IV", "Achieve gender equality and empower all women and girls")],
     "A-I, B-II, C-III, D-IV",
     "SDG 1 is No Poverty, SDG 2 is Zero Hunger, SDG 3 is Good Health & Well-Being, and SDG 5 is Gender Equality."),
    ("mcq", "SDG 11 Sustainable Cities and Communities",
     "Sustainable Development Goal 11 (SDG 11) aims to 'Make cities and human settlements inclusive, safe, resilient and sustainable'. A key target under SDG 11 is to:",
     "Provide access to safe, affordable, accessible, and sustainable transport systems for all, notably by expanding public mass transit",
     ["Demolish all historic architecture to construct private vehicle parking garages", "Ban all non-motorized cycling and walking across city roads", "Cut down all urban street trees to eliminate bird roosting"],
     "SDG 11 emphasizes accessible public transit, reducing the per capita environmental impact of cities (air quality and waste), and safeguarding green public spaces."),
    ("mcq", "High-Level Political Forum (HLPF)",
     "The premier United Nations platform responsible for the global follow-up, review, and thematic monitoring of the Sustainable Development Goals is the:",
     "High-Level Political Forum on Sustainable Development (HLPF), meeting annually under ECOSOC and the General Assembly",
     ["World Trade Organization Appellate Body", "International Criminal Court at The Hague", "International Monetary Fund Executive Board"],
     "The HLPF meets annually under the auspices of ECOSOC (and every 4 years under the General Assembly) to review Voluntary National Reviews (VNRs) of SDG progress."),
    ("stmt", "Voluntary National Reviews (VNRs)",
     "Under the SDG monitoring architecture, member states present regular 'Voluntary National Reviews' (VNRs) to share national experiences, successes, and challenges.",
     "India presented its comprehensive Voluntary National Reviews to the UN HLPF through reports prepared by NITI Aayog in 2017 and 2020.", 1,
     "Both Statement I and Statement II are correct. India's VNRs, led by NITI Aayog, outline flagship national missions mapping onto the 17 SDGs."),
    ("mcq", "SDG 17 Global Partnership Means of Implementation",
     "Sustainable Development Goal 17 (SDG 17) is titled 'Partnerships for the Goals' because it focuses on:",
     "Strengthening the means of implementation through finance, technology transfer, capacity building, fair international trade, and data monitoring",
     ["Merging all 193 nations into a single international corporate entity", "Banning all cross-border communications and internet networks", "Replacing all national currencies with a single global corporate token"],
     "SDG 17 focuses on mobilization of financial resources, technology transfer to developing nations, and multi-stakeholder partnerships to realize the 2030 Agenda."),
    ("seq", "Cascade of SDG Monitoring Hierarchy in India",
     "Arrange the institutional levels of SDG monitoring in India from national oversight down to grassroots implementation:",
     ["NITI Aayog computes the National SDG India Index and coordinates national policy alignment", "State Planning Departments develop State Indicator Frameworks (SIF) mapping state-specific schemes", "District Collectors and District Planning Committees monitor District Indicator Frameworks (DIF)", "Gram Panchayats implement localized Gram Panchayat Development Plans (GPDP) delivering village-level targets"],
     "I -> II -> III -> IV",
     "SDG localization in India cascades from NITI Aayog to State Indicator Frameworks, District monitoring, and Gram Panchayat execution."),
    ("mcq", "SDG 13.a Green Climate Fund Commitment",
     "Under Target 13.a of SDG 13 (Climate Action), developed nations reaffirmed their commitment under the UNFCCC to mobilize what annual funding goal to assist developing countries?",
     "$100 billion per year by 2020 from all sources to address the climate needs of developing nations",
     ["$100 million once every 50 years", "$1 trillion cash payment directly to corporate oil companies", "Zero financial assistance"],
     "Target 13.a reaffirms the COP15 Copenhagen commitment of developed countries to mobilize $100 billion annually to fund climate adaptation and mitigation in the Global South."),
    ("mcq", "SDG Target 14.1 Marine Plastic Pollution",
     "Target 14.1 of Sustainable Development Goal 14 explicitly commits that by 2025, world nations shall:",
     "Prevent and significantly reduce marine pollution of all kinds, in particular from land-based activities, including marine debris and nutrient pollution",
     ["Drain all coastal mangrove wetlands to build seaside luxury hotels", "Permit unrestricted dumping of untreated toxic chemical barrels into international waters", "Encourage deep-sea trawling across all coral reef national parks"],
     "SDG 14.1 specifically targets the urgent elimination of land-based marine debris (plastics) and nutrient pollution (eutrophication) in coastal waters by 2025.")
]
'''

with open('scripts/subject_generators/make_evs_s21_25.py', 'w') as f:
    f.write(s21_to_25)

print("make_evs_s21_25.py written.")
