# Mass Media & Mass Communication (Code 318) - Slots 31 to 35 (100 Questions)
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from slot_helpers import mcq, stmt, ar, match, seq

SLOTS_31_35 = {}

# ==============================================================================
# SLOT 31: Camera Movements, Lighting & Mise-en-scène
# ==============================================================================
SLOTS_31_35[31] = [
    mcq("Film Techniques", "Pan vs Tilt",
        "What is the physical and mechanical distinction between a camera 'Pan' and a camera 'Tilt'?",
        "A Pan rotates the camera horizontally on a fixed axis from side to side; a Tilt pivots the camera vertically up or down on a fixed axis",
        ["A Pan requires throwing the camera in the air; a Tilt submerges it in water",
         "A Pan moves the camera forward on wheels; a Tilt zooms the lens optically",
         "A Pan is only filmed outdoors; a Tilt is only filmed indoors"],
        "Panning is horizontal rotation on a fixed tripod head; Tilting is vertical rotation up or down on a fixed pivot.",
        "Distinguishes camera panning from camera tilting."),
    mcq("Film Techniques", "Tracking Shot / Dolly",
        "How is a 'Dolly / Tracking Shot' mechanically executed, and how does it differ from an optical zoom?",
        "The physical camera itself moves through space mounted on a wheeled dolly or tracks, creating dynamic spatial perspective shifts rather than merely magnifying image size",
        ["The camera stays motionless while the actors run in circles",
         "The camera lens is unscrewed and replaced during filming",
         "The director projects still slides on a white sheet"],
        "A dolly moves the camera physically through space, altering spatial relationships and background parallax, unlike a static zoom lens.",
        "Differentiates a physical dolly/tracking shot from an optical zoom."),
    stmt("Film Techniques", "Steadicam Innovation",
        "Invented by Garrett Brown in 1975, the 'Steadicam' utilizes an articulated counterbalanced harness that isolates the camera from the operator's body movements.",
        "The Steadicam allows silky-smooth, fluid handheld tracking shots over uneven terrain, stairs, and tight corridors without laying mechanical tracks.",
        "both_true",
        "Both statements accurately explain the mechanical invention and aesthetic versatility of the Steadicam.",
        "Evaluates the technological and aesthetic significance of the Steadicam."),
    ar("Film Techniques", "Crane / Jib Shot Impact",
        "Crane and Jib shots are frequently employed to open or close monumental cinematic sequences.",
        "A crane arm elevates the camera high above the ground, executing sweeping vertical and diagonal swoops that transition between intimate human drama and epic environmental grandeur.",
        "both_correct_explain",
        "The vast vertical range of crane arms provides breathtaking transitions between macro environments and individual characters.",
        "Analyzes the dramatic and spatial utility of crane shots."),
    match("Film Techniques", "Camera Movements",
        "Match the camera movement in List-I with its mechanical execution in List-II:",
        ["Pan", "Tilt", "Dolly / Track", "Zoom (Optical)"],
        ["Horizontal swivel on fixed pivot from left to right", "Vertical pivot on fixed head tilting up or down", "Physical camera transportation through space along tracks", "Changing focal length of lens to alter magnification without moving the camera"],
        "A-I, B-II, C-III, D-IV",
        "Pan = horizontal swivel; Tilt = vertical pivot; Dolly = physical transport on tracks; Zoom = focal length magnification.",
        "Matches camera movements to their mechanical executions."),
    mcq("Film Techniques", "Mise-en-scène Meaning",
        "The French theatrical term 'Mise-en-scène' literally translates to 'placing on stage'. In cinema, what does it encompass?",
        "Everything that appears visually before the camera within the frame, including set design, lighting, costumes, props, actor blocking, and makeup",
        ["Only the musical score composed by the orchestra",
         "The legal contract between the film studio and cinema hall owners",
         "The computerized printing of movie tickets at box offices"],
        "Mise-en-scène encompasses all visual elements arranged in front of the lens: sets, lighting, wardrobe, props, and actor staging.",
        "Defines mise-en-scène in film analysis."),
    stmt("Film Techniques", "High-Key vs Low-Key Lighting",
        "'High-Key Lighting' is characterized by bright, even illumination with minimal contrast and soft shadows, standard in comedies and musicals.",
        "'Low-Key Lighting' employs high contrast between bright highlights and deep, dark shadows (chiaroscuro), classic in Film Noir and horror.",
        "both_true",
        "Both statements correctly differentiate high-key lighting from low-key chiaroscuro lighting.",
        "Distinguishes high-key lighting from low-key lighting in cinema."),
    ar("Film Techniques", "German Expressionism & Chiaroscuro",
        "German Expressionist cinema of the 1920s (e.g. The Cabinet of Dr. Caligari) utilized extreme, stylized low-key lighting and distorted angular sets.",
        "Expressionist filmmakers used external visual distortion and deep shadows to project the internal psychological torment, madness, and paranoia of characters.",
        "both_correct_explain",
        "Stylized shadows and warped sets externalized inner psychic trauma, a hallmark of German Expressionist aesthetics.",
        "Explains the aesthetic purpose of chiaroscuro in German Expressionism."),
    seq("Film Techniques", "Setting Up Three-Point Lighting",
        "Arrange the stages of positioning and adjusting a classic Three-Point Lighting setup on a film set:",
        ["Positioning the primary Key Light 45 degrees to the side and 45 degrees above subject to establish form", "Placing the Fill Light on the opposite side to soften dark facial shadows to desired ratio", "Positioning the Back Light behind and above the subject to sculpt shoulders and hair from background", "Illuminating background set walls with separate kicker/background fixtures", "Fine-tuning barn doors, scrims, and diffusion gels to soften shadows"],
        "I -> II -> III -> IV -> V",
        "Lighting setup order: Key light -> Fill light -> Back light -> Background light -> Diffusion/barn door trimming.",
        "Sequences three-point lighting setup workflow."),
    mcq("Film Techniques", "Dolly Zoom / Vertigo Effect",
        "What is the 'Dolly Zoom' (popularized by Alfred Hitchcock in 'Vertigo'), achieved by simultaneously dollying the camera forward while zooming out?",
        "An optical illusion where the foreground subject maintains constant size while the background perspective visibly warps, stretches, or compresses",
        ["A camera lens that cracks under intense sunlight",
         "A sound effect where the actor's voice sounds underwater",
         "A technique where the movie screen rolls down like a window blind"],
        "The Vertigo effect warps perspective and depth planes while keeping the subject scale constant, signaling profound psychological shock.",
        "Defines the Vertigo Dolly Zoom optical effect."),
    stmt("Film Techniques", "Actor Blocking",
        "In film directing, 'Blocking' refers to the precise choreography of actors' physical movements and positioning in relation to the camera within the set.",
        "Blocking requires all actors to remain completely paralyzed in one spot without blinking.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because blocking choreographs purposeful, naturalistic actor movements aligned with camera framing.",
        "Defines actor blocking in film directing."),
    ar("Film Techniques", "Costume as Character Exposition",
        "Costume design in cinema functions as an immediate semiotic tool of character exposition.",
        "Color palette, fabric texture, and clothing style convey social status, psychological evolution, and moral alignment before a character speaks.",
        "both_correct_explain",
        "Wardrobe visual choices communicate socio-economic standing and emotional states instantly, functioning as powerful narrative shorthand.",
        "Analyzes costume design as a narrative and psychological tool."),
    match("Film Techniques", "Lighting Terminology",
        "Match the lighting tool/concept in List-I with its operational function in List-II:",
        ["Barn Doors", "Diffusion Gel / Softbox", "Gobo / Cookie", "Reflector Board"],
        ["Adjustable metal flaps mounted on light housing to cut and shape the light beam", "Translucent material placed before a harsh light to scatter rays and create soft shadows", "A patterned stencil placed before a light to project shadows of blinds or foliage", "A metallic or white bounce surface redirecting natural sunlight into shadow areas"],
        "A-I, B-II, C-III, D-IV",
        "Barn doors = beam cut; Diffusion/softbox = soft light scattering; Gobo = pattern projection; Reflector = bounce board.",
        "Matches lighting equipment to operational functions."),
    mcq("Film Techniques", "Rembrandt Lighting",
        "In cinematic portrait lighting, what defines classic 'Rembrandt Lighting'?",
        "A small, distinctive inverted triangle of light illuminated on the cheek of the subject on the shadow side of the face",
        ["Lighting the actor exclusively with green fluorescent tubes",
         "Placing the key light on the floor pointed straight up into the nostrils",
         "Lighting that leaves the entire face in 100% complete darkness"],
        "Rembrandt lighting creates a signature small luminous triangle on the shadowed cheek, producing dramatic painterly depth.",
        "Identifies classic Rembrandt portrait lighting."),
    stmt("Film Techniques", "Natural Light and Golden Hour",
        "The 'Golden Hour' (Magic Hour) in cinematography refers to the brief period shortly after sunrise or before sunset when sunlight is warm, soft, and diffuse.",
        "Cinematographers avoid the golden hour because sunlight during that time destroys film negative chemicals.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because the golden hour is prized by cinematographers for its luminous, flattering aesthetic quality.",
        "Celebrates the visual qualities of Golden Hour cinematography."),
    ar("Film Techniques", "Hard vs Soft Light Quality",
        "Hard light creates sharp-edged, high-contrast dark shadows, while soft light produces gentle, gradual transitions between light and shadow.",
        "The softness of a light source depends strictly on its relative physical size to the subject; larger diffused light sources produce softer light.",
        "both_correct_explain",
        "A light source that is physically large relative to the subject wraps around contours, diffusing rays and softening shadow edges.",
        "Explains the physics of hard versus soft lighting."),
    mcq("Film Techniques", "Whip Pan / Swish Pan",
        "What is a 'Whip Pan' (or Swish Pan) in cinematography and editing?",
        "An extremely rapid horizontal pan that blurs the image into kinetic visual streaks, used as a dynamic transitional cut between scenes",
        ["An actor cracking a leather whip at the camera operator",
         "A camera dropped accidentally from a high crane",
         "A slow ten-minute pan across a desert"],
        "A whip pan pans so fast that motion blur conceals a cut, creating high-energy, seamless transitions between locations.",
        "Defines a whip pan in cinematography."),
    match("Film Techniques", "Mise-en-scène Elements",
        "Match the element of mise-en-scène in List-I with its analytical focus in List-II:",
        ["Set Design / Decor", "Props (Property)", "Color Palette", "Spatial Composition"],
        ["Architecture, furniture, and environmental physical dressing of the scene", "Physical objects handled or used by characters (e.g. letters, weapons)", "Harmonic or contrasting chromatic scheme establishing emotional atmosphere", "The balance, depth planes, and geometric arrangement of bodies within the frame"],
        "A-I, B-II, C-III, D-IV",
        "Set design = architecture/decor; Props = handled objects; Color palette = chromatic scheme; Spatial composition = body geometry.",
        "Matches elements of mise-en-scène to analytical dimensions."),
    seq("Film Techniques", "Executing a Complex Tracking Shot",
        "Arrange the operational steps of executing a 60-second continuous dolly tracking shot:",
        ["Director and cinematographer walk the location determining camera trajectory and marks", "Grip crew lays precision metal rails and levels dolly track with wooden wedges", "Rehearsing camera movement with camera operator and dolly grip pushing the rig", "Focus puller measures distances and marks focal stops on wireless follow-focus", "Executing the take synchronized with actor blocking and lighting cues"],
        "I -> II -> III -> IV -> V",
        "Dolly workflow: Trajectory scouting -> Track laying/leveling -> Rehearsal -> Focus measuring -> Synchronized execution.",
        "Sequences technical execution of a dolly tracking shot."),
    mcq("Film Techniques", "Motivated Camera Movement",
        "In classical cinematic storytelling, what is meant by 'Motivated Camera Movement'?",
        "Camera movement that is prompted by and follows an onscreen physical action (such as a character standing up and walking across the room)",
        ["A camera that operates only when the director is feeling angry",
         "A movement executed purely because the camera operator was bored",
         "A camera pushed by an automated electric lawnmower"],
        "Motivated movements are visually justified by narrative action, ensuring camera shifts feel natural and invisible to the viewer.",
        "Explains motivated camera movement in film visual grammar.")
]

# ==============================================================================
# SLOT 32: Film Editing & Sound (Continuity, Montage, Sound Design, CBFC)
# ==============================================================================
SLOTS_31_35[32] = [
    mcq("Film Editing & Sound", "Continuity Editing / Invisible Editing",
        "What is the primary aesthetic objective of the classical Hollywood 'Continuity Editing' system (Invisible Editing)?",
        "To maintain seamless spatial, temporal, and narrative coherence across cuts, ensuring the audience remains absorbed in the story without noticing the edits",
        ["To confuse the audience so they do not know what century the film takes place in",
         "To ensure that every cut is accompanied by a loud firecracker explosion",
         "To insert blank black frames for thirty seconds between every shot"],
        "Continuity editing creates seamless spatial and temporal flow, hiding the artificiality of edits behind narrative continuity.",
        "Defines the objective of classical continuity editing."),
    mcq("Film Editing & Sound", "The 180-Degree Rule",
        "In film directing and editing, what is the foundational '180-Degree Rule'?",
        "An imaginary spatial axis connecting two interacting characters; the camera must remain on one side of this axis to preserve consistent screen direction and eye lines",
        ["The rule that actors must turn around 180 degrees every time they speak",
         "The requirement that film sets must be heated to exactly 180 degrees Fahrenheit",
         "The rule that all movies must run for exactly 180 minutes"],
        "The 180-degree rule maintains consistent left-right screen direction and eyelines, preventing disorienting spatial flips across cuts.",
        "Explains the 180-degree rule in camera placement and editing."),
    stmt("Film Editing & Sound", "Crossing the Axis / Line Flaw",
        "When a filmmaker violates the 180-degree rule and 'crosses the line', characters who were looking right suddenly appear to be looking in the same direction, disorienting the viewer.",
        "Filmmakers never cross the line intentionally under any artistic circumstances.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because avant-garde directors (like Godard or Kubrick) deliberately cross the line to induce psychological disorientation.",
        "Evaluates the spatial consequence of crossing the 180-degree line."),
    ar("Film Editing & Sound", "Kuleshov Effect",
        "Lev Kuleshov's famous 1910s editing experiment demonstrated that film viewers derive more meaning from the interaction of two sequential shots than from a single shot in isolation.",
        "Juxtaposing an identical expressionless shot of actor Ivan Mozzhukhin with a bowl of soup, a dead child, and a seductive woman led audiences to perceive hunger, grief, and desire respectively.",
        "both_correct_explain",
        "The Kuleshov effect proved that cinema is psychological; audiences actively project meaning born from the juxtaposition of sequential images.",
        "Analyzes the psychological significance of the Kuleshov Effect."),
    match("Film Editing & Sound", "Eisenstein's Five Methods of Montage",
        "Match Sergei Eisenstein's montage type in List-I with its operational principle in List-II:",
        ["Metric Montage", "Rhythmic Montage", "Tonal Montage", "Intellectual / Ideological Montage"],
        ["Editing based strictly on absolute mathematical shot lengths regardless of content", "Editing dictated by visual movement and tempo within the frame (e.g. soldiers marching down Odessa Steps)", "Editing governed by emotional and atmospheric resonance (light, texture, graphic tone)", "Juxtaposing disparate conceptual images to spark abstract intellectual ideas (e.g. striking workers cut with slaughterhouse cattle)"],
        "A-I, B-II, C-III, D-IV",
        "Metric = mathematical length; Rhythmic = tempo of action; Tonal = emotional resonance; Intellectual = collision of abstract ideas.",
        "Matches Eisenstein's five montage methods to operational definitions."),
    mcq("Film Editing & Sound", "Diegetic vs Non-Diegetic Sound",
        "What is the theoretical distinction between 'Diegetic Sound' and 'Non-Diegetic Sound' in cinematic sound design?",
        "Diegetic sound originates from a source within the fictional world of the film (heard by characters); Non-Diegetic sound originates outside the story world (musical score, narrator VO, heard only by audience)",
        ["Diegetic sound is recorded underwater; Non-diegetic sound is recorded on airplanes",
         "Diegetic sound can only be heard by children; Non-diegetic sound is for adults",
         "Diegetic sound is silent; Non-diegetic sound is loud"],
        "Diegetic sounds exist inside the fictional narrative reality (dialogue, car horn, radio in room); non-diegetic sounds (background orchestral score) exist outside.",
        "Differentiates diegetic sound from non-diegetic sound."),
    stmt("Film Editing & Sound", "Jump Cut & French New Wave",
        "A 'Jump Cut' is an abrupt, non-continuous cut between two sequential shots taken from slightly different camera positions on the same subject.",
        "Jean-Luc Godard famously embraced jarring jump cuts in 'Breathless' (1960) to intentionally shatter bourgeois continuity illusions and inject kinetic modern energy.",
        "both_true",
        "Both statements correctly define the jump cut and its celebrated avant-garde utilization by Jean-Luc Godard.",
        "Validates the jump cut in French New Wave cinema."),
    ar("Film Editing & Sound", "Match on Action",
        "A 'Match on Action' cut preserves the illusion of physical continuity across a cut.",
        "The editor cuts in the middle of a continuous physical motion (e.g. an actor opening a door on a wide shot and walking through on a medium shot), masking the edit with movement.",
        "both_correct_explain",
        "Cutting mid-movement tricks the viewer's eye into following the kinetic action, masking the cut and preserving seamless continuity.",
        "Explains how match-on-action masks editing cuts."),
    seq("Film Editing & Sound", "Film Post-Production Editing Phases",
        "Arrange the developmental phases of narrative film picture editing in sequential order:",
        ["Assembly Cut (all scenes arranged sequentially according to the script)", "Rough Cut (initial trimmed version focusing on basic narrative pacing)", "Fine Cut (nuanced trimming of frame-by-frame timing and rhythm)", "Picture Lock (final editorial approval of visual cuts, freezing shot lengths)", "Sound design, score mixing, color grading, and final export"],
        "I -> II -> III -> IV -> V",
        "Editing workflow: Assembly cut -> Rough cut -> Fine cut -> Picture lock -> Sound/color finishing.",
        "Sequences the post-production picture editing workflow."),
    mcq("Film Editing & Sound", "Eyeline Match",
        "What is an 'Eyeline Match' in continuity editing?",
        "A technique where Shot A shows a character looking at something off-screen, followed by Shot B showing the object positioned precisely where the character's gaze was directed",
        ["An optometrist testing an actor's vision with an eye chart",
         "Two actors wearing matching colored contact lenses",
         "An editing cut that blinds the audience with bright light"],
        "Eyeline match establishes spatial orientation by linking a character's gaze direction to the subsequent shot of the observed object.",
        "Defines an eyeline match in film editing."),
    stmt("Film Editing & Sound", "Foley Sound Recording",
        "Foley artists recreate physical human sound effects (footsteps, fabric rustle, bone snaps) in a specialized studio while watching the film projected on screen.",
        "Foley sound effects are recorded purely using computer algorithms without any physical objects.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because Foley artists physically manipulate real-world objects to perform synchronized sounds.",
        "Describes Foley sound artistry in film production."),
    ar("Film Editing & Sound", "Parallel Editing / Cross-Cutting",
        "Parallel editing (Cross-Cutting), pioneered by D. W. Griffith, is used to build intense dramatic suspense.",
        "Cross-cutting alternates back and forth between two or more events occurring simultaneously in different geographical locations.",
        "both_correct_explain",
        "Intercutting simultaneous events racing toward a convergence (e.g. ticking bomb and rescue hero) generates immense cinematic suspense.",
        "Analyzes parallel editing and cross-cutting in building suspense."),
    match("Film Editing & Sound", "Editing Cuts",
        "Match the editing transition/cut in List-I with its description in List-II:",
        ["L-Cut / J-Cut (Split Edit)", "Smash Cut", "Graphic Match", "Cross-Cutting"],
        ["Audio and video transition at different times, with sound leading or trailing picture", "An abrupt, jarring cut from a quiet scene to a loud, chaotic scene for shock value", "Cutting between two visually similar shapes or contours (e.g. bone turning into satellite)", "Alternating between two simultaneous scenes taking place in different locations"],
        "A-I, B-II, C-III, D-IV",
        "L/J-Cut = split audio/video edit; Smash cut = jarring shock transition; Graphic match = shape similarity cut; Cross-cutting = parallel simultaneous scenes.",
        "Matches editing cuts to descriptions."),
    mcq("Film Editing & Sound", "CBFC Statutory Framework",
        "Under which statutory act is the Central Board of Film Certification (CBFC) in India established to certify films for public exhibition?",
        "The Cinematograph Act, 1952",
        ["The Press Council Act, 1978", "The Copyright Act, 1957", "The Indian Penal Code, 1860"],
        "The CBFC is a statutory regulatory body operating under the Ministry of Information and Broadcasting pursuant to the Cinematograph Act, 1952.",
        "Identifies the Cinematograph Act 1952 as the parent statute of the CBFC."),
    stmt("Film Editing & Sound", "CBFC Certification Categories",
        "Under the Cinematograph Act, CBFC traditionally issued certificates: 'U' (Unrestricted public exhibition), 'UA' (Parental guidance for under 12), 'A' (Adults only), and 'S' (Specialized audiences like doctors/scientists).",
        "The Cinematograph (Amendment) Act 2023 subdivided the 'UA' category into age-based classifications: UA 7+, UA 13+, and UA 16+.",
        "both_true",
        "Both statements are true. The 2023 amendment introduced age-graded parental guidance categories (UA 7+, 13+, 16+).",
        "Evaluates CBFC film certification categories and the 2023 amendment."),
    ar("Film Editing & Sound", "Asynchronous Sound",
        "Asynchronous sound occurs when sound and visual action do not match in literal synchrony.",
        "Filmmakers use asynchronous sound (e.g. an ambulance siren screaming over an image of an unmoving corpse) to evoke symbolic meaning and psychological dread.",
        "both_correct_explain",
        "Decoupling sound from literal physical synchronization creates powerful conceptual, emotional, and symbolic counterpoint.",
        "Explains the symbolic application of asynchronous sound in cinema."),
    mcq("Film Editing & Sound", "Sound Motif",
        "What is a 'Sound Motif' (or Leitmotif) in cinematic sound design?",
        "A recurring musical phrase or distinctive sound effect consistently associated with a specific character, emotion, or looming threat (e.g. Jaws two-note motif)",
        ["The physical metal casing of a movie projector",
         "The sound of popcorn crunching inside a cinema auditorium",
         "A musical composition that is never repeated in the film"],
        "A leitmotif creates subconscious psychological recognition by associating a distinct melody or sound with a character or theme.",
        "Defines a sound motif / leitmotif in film score composition."),
    match("Film Editing & Sound", "CBFC Certificate Categories",
        "Match the CBFC certificate category in List-I with its legal exhibition mandate in List-II:",
        ["'U' Certificate", "'UA' Certificate", "'A' Certificate", "'S' Certificate"],
        ["Unrestricted public exhibition suitable for all age groups", "Unrestricted public exhibition with parental discretion advised for children under 12", "Public exhibition restricted exclusively to adult persons (18+ years of age)", "Public exhibition restricted to specialized professional classes (e.g. medical practitioners)"],
        "A-I, B-II, C-III, D-IV",
        "U = unrestricted all ages; UA = parental guidance under 12; A = adults 18+; S = specialized professional classes.",
        "Matches CBFC certification categories to legal exhibition rules."),
    seq("Film Editing & Sound", "CBFC Film Certification Procedure",
        "Arrange the stages of certifying a feature film before the CBFC in operational sequence:",
        ["Producer submits completed film with application and script to regional CBFC office", "Examining Committee watches film and drafts recommendation report", "CBFC communicates requested excisions (cuts) or certificate category to applicant", "Applicant accepts cuts or appeals decision to Revising Committee", "CBFC issues official digital exhibition censor certificate with category mark"],
        "I -> II -> III -> IV -> V",
        "CBFC process: Application -> Examining Committee -> Recommendation -> Revising appeal/Cuts -> Certificate issuance.",
        "Sequences the CBFC film certification workflow in India."),
    mcq("Film Editing & Sound", "Automated Dialogue Replacement (ADR)",
        "What is 'ADR' (Automated Dialogue Replacement, colloquially called 'Dubbing') in film sound post-production?",
        "Re-recording actors' dialogue in an acoustic studio booth after filming to replace noisy, unusable on-set location audio",
        ["An automated robot that writes screenplays",
         "A program that converts spoken English into classical hieroglyphics",
         "A computerized voice that replaces all human actors in animated films"],
        "ADR replaces poor on-location production dialogue with clean, lip-synced studio vocal recordings.",
        "Defines Automated Dialogue Replacement (ADR) in film sound.")
]

# ==============================================================================
# SLOT 33: Fundamentals of Advertising (Functions, Types, USP)
# ==============================================================================
SLOTS_31_35[33] = [
    mcq("Advertising Fundamentals", "Definition of Advertising",
        "Which celebrated definition of advertising, formulated by the American Marketing Association (AMA), highlights its paid and mediated nature?",
        "'Any paid form of non-personal presentation and promotion of ideas, goods, or services by an identified sponsor'",
        ["'A secret whisper passed between two friends on a public park bench'",
         "'An anonymous unpaid complaint filed in a consumer tribunal'",
         "'A government decree ordering citizens to stop buying luxury shoes'"],
        "The AMA definition identifies three cardinal pillars of advertising: paid sponsorship, non-personal mass presentation, and an identified sponsor.",
        "Recalls the American Marketing Association definition of advertising."),
    mcq("Advertising Fundamentals", "Unique Selling Proposition (USP)",
        "The groundbreaking advertising concept of the 'Unique Selling Proposition' (USP) was formulated in the 1940s by which legendary ad pioneer?",
        "Rosser Reeves of Ted Bates Agency",
        ["David Ogilvy", "Leo Burnett", "Bill Bernbach"],
        "Rosser Reeves defined the USP: every ad must make a specific, unique proposition to the consumer that competing brands cannot or do not offer.",
        "Identifies Rosser Reeves as the father of the Unique Selling Proposition (USP)."),
    stmt("Advertising Fundamentals", "Classified vs Display Advertisements",
        "Classified advertisements in newspapers are small, text-only listings grouped into common categories (matrimonial, property, employment) priced per word or line.",
        "Display advertisements utilize striking visual artwork, photography, typography, and logos, occupying larger column blocks or full pages at premium rates.",
        "both_true",
        "Both statements accurately define and contrast classified listings with visual display advertisements.",
        "Differentiates classified advertisements from display advertisements."),
    ar("Advertising Fundamentals", "Public Service Advertising (PSA)",
        "Public Service Advertisements (PSAs) are not designed to generate commercial sales or corporate product revenues.",
        "The objective of a PSA is to stimulate positive social attitudes, public health behaviors, road safety, and civic consciousness for collective welfare.",
        "both_correct_explain",
        "PSAs promote pro-social causes (anti-smoking, polio immunization) rather than commercial merchandise, explaining their non-commercial nature.",
        "Analyzes the social purpose of Public Service Advertising (PSA)."),
    match("Advertising Fundamentals", "Advertising Typologies",
        "Match the advertising category in List-I with its primary communication goal in List-II:",
        ["Consumer Advertising", "Business-to-Business (B2B)", "Institutional / Corporate Advertising", "Public Service Advertising (PSA)"],
        ["Promoting everyday branded goods directly to individual end-consumers", "Promoting industrial machinery, raw supplies, or enterprise software to companies", "Building long-term corporate reputation, public goodwill, and trust for a company", "Promoting civic awareness, blood donation, environmental hygiene, and safety"],
        "A-I, B-II, C-III, D-IV",
        "Consumer = retail goods to citizens; B2B = industrial trade; Institutional = corporate reputation; PSA = social causes.",
        "Matches advertising categories to communication goals."),
    mcq("Advertising Fundamentals", "Functions of Advertising",
        "Which of the following is a primary economic function of commercial advertising in a free-market economy?",
        "Stimulating consumer demand, accelerating product adoption, creating brand differentiation, and reducing per-unit distribution costs through economies of scale",
        ["Eliminating all competition so only one state-owned brand exists",
         "Preventing consumers from learning product prices",
         "Forcing consumers to spend their entire salary in a single store"],
        "Advertising drives awareness, stimulates market demand, differentiates products, and enables economies of scale for mass production.",
        "Identifies the economic functions of advertising."),
    stmt("Advertising Fundamentals", "Brand vs Product",
        "A product is a physical item manufactured in a factory, whereas a 'Brand' is an emotional and perceptual identity residing in the mind of the consumer.",
        "Products can be easily copied by competitors, but a powerful brand identity creates unique loyalty and intangible equity.",
        "both_true",
        "Both statements are core marketing verities distinguishing generic functional products from symbolic brand identities.",
        "Distinguishes physical products from perceptual brand identities."),
    ar("Advertising Fundamentals", "Surrogate Advertising",
        "Liquor and tobacco companies in India frequently employ 'Surrogate Advertising'.",
        "Direct commercial advertising of alcohol and cigarettes is legally banned on broadcast and print media, compelling brands to promote surrogate items (music CDs, soda, cardamon) carrying identical brand logos.",
        "both_correct_explain",
        "To circumvent statutory bans on advertising harmful products (COTPA), brands market harmless surrogate goods with identical brand names and packaging.",
        "Analyzes the strategy and regulatory controversy of surrogate advertising."),
    seq("Advertising Fundamentals", "Brand Hierarchy Evolution",
        "Arrange the stages of brand relationship development from baseline awareness to deep devotion:",
        ["Brand Awareness (recognizing brand name in a crowded category)", "Brand Preference (choosing the brand over competitors given equal availability)", "Brand Insistence (refusing substitutes and seeking out the brand exclusively)", "Brand Advocacy (passionate customer promoting the brand organically to peers)"],
        "I -> II -> III -> IV",
        "Brand loyalty ladder: Awareness -> Preference -> Insistence -> Advocacy.",
        "Sequences the hierarchy of brand adoption and customer loyalty."),
    mcq("Advertising Fundamentals", "Brand Equity",
        "In marketing communication, what is 'Brand Equity'?",
        "The commercial value that a recognized brand name adds to a product over and above its physical, functional utility",
        ["The physical weight of the product packaging in kilograms",
         "The cash stored inside the retail store's cash register",
         "The total number of factories owned by the corporation"],
        "Brand equity is the premium value derived from consumer perception, brand reputation, and emotional resonance.",
        "Defines brand equity in advertising and marketing."),
    stmt("Advertising Fundamentals", "Institutional Advertising Role",
        "Institutional advertising (corporate image advertising) does not promote any specific product SKU.",
        "It aims to build public trust, showcase philanthropic CSR initiatives, and establish the company as a responsible corporate citizen.",
        "both_true",
        "Both statements correctly describe the objectives of institutional advertising.",
        "Validates the nature of institutional and corporate advertising."),
    ar("Advertising Fundamentals", "Subliminal Advertising Controversy",
        "Subliminal advertising (inserting ultra-fast visual flashes below conscious perceptual thresholds) is banned by advertising regulators worldwide.",
        "Subliminal persuasion is condemned as an unethical violation of cognitive autonomy, attempting to manipulate human desires without conscious awareness.",
        "both_correct_explain",
        "Because subliminal tactics bypass conscious discernment, advertising ethics bodies prohibit them as deceptive and coercive.",
        "Explains the ethical prohibition of subliminal advertising."),
    match("Advertising Fundamentals", "Legendary Ad Pioneers",
        "Match the iconic advertising visionary in List-I with their signature advertising philosophy in List-II:",
        ["David Ogilvy", "Leo Burnett", "Rosser Reeves", "William Bernbach"],
        ["Advocated research-driven informative copy, brand personality, and gentlemanly elegance ('The consumer is not a moron; she is your wife')", "Created folklore archetypes and visual icons of warm American values (Marlboro Man, Jolly Green Giant)", "Championed the hard-sell Unique Selling Proposition (USP) repeated with razor focus", "Pioneered the Creative Revolution blending ironic humor, understated art, and copy (Volkswagen 'Think Small')"],
        "A-I, B-II, C-III, D-IV",
        "Ogilvy = research/brand personality; Burnett = folklore icons/warmth; Reeves = hard-sell USP; Bernbach = creative revolution/humor.",
        "Matches advertising legends to their signature creative philosophies."),
    mcq("Advertising Fundamentals", "Advocacy Advertising",
        "What characterizes 'Advocacy Advertising' by a corporate conglomerate or NGO?",
        "An advertisement taking a firm, public ideological position on a controversial political, economic, or social policy issue (such as climate change carbon taxes)",
        ["An ad announcing a 50% discount sale on washing powder",
         "A notice listing train arrival times",
         "A classified listing offering secondhand furniture"],
        "Advocacy advertising uses media space to champion controversial causes or corporate ideological viewpoints on public policy.",
        "Defines advocacy advertising in public discourse."),
    stmt("Advertising Fundamentals", "Direct-Response Advertising",
        "Direct-response advertising seeks an immediate, measurable behavioral reaction from the consumer (e.g. calling a toll-free number or clicking a digital link).",
        "Brand image advertising focuses on building long-term emotional goodwill rather than demanding immediate transactional purchases.",
        "both_true",
        "Both statements accurately distinguish direct-response advertising from long-term brand-building advertising.",
        "Distinguishes direct-response advertising from brand-building advertising."),
    ar("Advertising Fundamentals", "Comparative Advertising Legalities",
        "Comparative advertising (directly naming a commercial rival in an advertisement) is strictly regulated under Indian trademark and fair-trade laws.",
        "While an advertiser may claim their brand is superior, they must not disparage, slander, or deceptively denigrate a competitor's registered trademark.",
        "both_correct_explain",
        "Courts permit truthful puffery and factual comparison but prohibit trade disparagement that defames a competitor's product.",
        "Analyzes legal boundaries governing comparative advertising."),
    mcq("Advertising Fundamentals", "Puffery in Advertising",
        "What is 'Puffery' in commercial advertising?",
        "Exaggerated, subjective promotional claims (e.g. 'The greatest coffee in the world!') that an average reasonable consumer understands as non-literal hyperbole",
        ["An advertisement printed on puffed wheat grain packaging",
         "A mathematical fraud that violates the national banking code",
         "A smoke screen produced by television studio fireworks"],
        "Puffery represents legal promotional hyperbole that reasonable consumers do not interpret as verified factual claims.",
        "Defines puffery in commercial advertising."),
    match("Advertising Fundamentals", "Advertising Appeals",
        "Match the advertising appeal in List-I with its psychological hook in List-II:",
        ["Emotional Appeal (Pathos)", "Rational / Informational Appeal", "Fear Appeal", "Humor Appeal"],
        ["Evoking love, empathy, nostalgia, or parental protection to connect with a brand", "Highlighting technical specifications, fuel efficiency, price, and warranties", "Warning of severe physical or social penalties if product is not used (e.g. tooth decay, road accidents)", "Using wit, irony, and entertaining comedy to create high brand likeability"],
        "A-I, B-II, C-III, D-IV",
        "Emotional = love/empathy; Rational = specs/price; Fear = hazards/penalties; Humor = wit/likeability.",
        "Matches advertising appeals to psychological mechanisms."),
    seq("Advertising Fundamentals", "Product Life Cycle (PLC) Advertising Strategies",
        "Arrange the stages of advertising strategy as a product moves through the Product Life Cycle (PLC):",
        ["Pioneering / Informative Advertising (establishing awareness of a new product category)", "Competitive / Persuasive Advertising (differentiating brand from rival entrants)", "Comparative / Defensive Advertising (protecting market share and maintaining brand loyalty)", "Reminder / Retentive Advertising (maintaining top-of-mind recall for mature established brands)"],
        "I -> II -> III -> IV",
        "PLC advertising trajectory: Informative introduction -> Persuasive growth -> Defensive maturity -> Reminder retention.",
        "Sequences advertising strategies across the Product Life Cycle."),
    mcq("Advertising Fundamentals", "Ambient Advertising",
        "What is 'Ambient Advertising' (or Guerilla Out-of-Home)?",
        "Placing unexpected, highly creative brand messages in unconventional physical environments (e.g. painting a crosswalk like french fries or placing giant sculptures in shopping malls)",
        ["Broadcasting radio ads exclusively during rainstorms",
         "Printing black text on plain white newsprint paper",
         "Distributing business cards at funeral homes"],
        "Ambient advertising transforms surprising everyday physical environments into creative brand spectacles to disrupt ad blindness.",
        "Defines ambient and guerrilla outdoor advertising.")
]

# ==============================================================================
# SLOT 34: Advertising Models & Campaign Planning (AIDA, DAGMAR, Creative Brief)
# ==============================================================================
SLOTS_31_35[34] = [
    mcq("Ad Models & Planning", "AIDA Model",
        "What sequential psychological stages does the classic 'AIDA Model' (formulated by E. St. Elmo Lewis in 1898) describe?",
        "Attention -> Interest -> Desire -> Action",
        ["Affection -> Intelligence -> Devotion -> Agreement",
         "Analysis -> Investigation -> Deduction -> Acquisition",
         "Audience -> Income -> Demographics -> Advertising"],
        "AIDA outlines the consumer mental journey: grabbing Attention, provoking Interest, stimulating Desire, and compelling Action.",
        "Recalls the four stages of the AIDA model."),
    mcq("Ad Models & Planning", "DAGMAR Model",
        "What does the acronym 'DAGMAR', formulated by Russell Colley in 1961 for measuring advertising effectiveness, stand for?",
        "Defining Advertising Goals for Measured Advertising Results",
        ["Digital Advertising Guidance for Marketing Analytics and Reach",
         "Demographic Assessment Guidelines for Measuring Audience Revenue",
         "Direct Action Goals for Mass Audience Retention"],
        "DAGMAR states that advertising goals must be specific communication tasks with measurable benchmarks rather than vague sales targets.",
        "Identifies the full form and premise of the DAGMAR model."),
    stmt("Ad Models & Planning", "DAGMAR Communication Task vs Sales",
        "Russell Colley argued in DAGMAR that an advertising campaign should be evaluated on communication tasks (awareness, comprehension, conviction) rather than sales volume.",
        "Sales volume is influenced by multiple non-advertising factors such as product quality, price, distribution, competitor moves, and economic climate.",
        "both_true",
        "Both statements are true. Separating communication goals from broader marketing mix variables is DAGMAR's central insight.",
        "Evaluates the communication task premise of the DAGMAR model."),
    ar("Ad Models & Planning", "The Creative Brief's Role",
        "The 'Creative Brief' is regarded as the indispensable bridge connecting client servicing and the creative team.",
        "A creative brief synthesizes market research, competitive landscape, target persona, core consumer insight, and tone of voice into a single strategic document.",
        "both_correct_explain",
        "The creative brief distills strategic marketing goals into focused creative inspiration, keeping copywriters and art directors on target.",
        "Explains the foundational role of the Creative Brief in advertising agencies."),
    match("Ad Models & Planning", "Advertising Models",
        "Match the advertising model/theory in List-I with its core proposition in List-II:",
        ["AIDA Model (Lewis)", "DAGMAR Model (Colley)", "FCB Grid (Vaughn)", "Hierarchy of Effects (Lavidge & Steiner)"],
        ["Linear hierarchy: Attention, Interest, Desire, Action", "Setting measurable communication benchmarks: Awareness, Comprehension, Conviction, Action", "Matrix categorizing purchases by High/Low Involvement and Think/Feel orientation", "Six-stage progression: Awareness, Knowledge, Liking, Preference, Conviction, Purchase"],
        "A-I, B-II, C-III, D-IV",
        "AIDA = Attention to Action; DAGMAR = measured communication results; FCB Grid = involvement/think-feel matrix; Lavidge & Steiner = 6-stage cognitive hierarchy.",
        "Matches advertising planning models to core propositions."),
    mcq("Ad Models & Planning", "FCB Grid Dimensions",
        "In Richard Vaughn's Foot, Cone & Belding (FCB) Grid, what are the two intersecting axes used to map consumer purchase decisions?",
        "Involvement (High vs Low) and Processing Mode (Thinking vs Feeling)",
        ["Price (Cheap vs Expensive) and Color (Red vs Blue)",
         "Weight (Heavy vs Light) and Speed (Fast vs Slow)",
         "Age (Child vs Adult) and Gender (Male vs Female)"],
        "The FCB Grid crosses High/Low Involvement with Thinking (rational) vs Feeling (emotional) motivations across 4 quadrants.",
        "Identifies the dimensions of the FCB advertising grid."),
    stmt("Ad Models & Planning", "Target Audience Demographics vs Psychographics",
        "Demographics define consumer traits by observable statistical data: age, gender, income, education, and geography.",
        "Psychographics define consumers by internal psychological attributes: values, lifestyles, attitudes, interests, and opinions (AIO).",
        "both_true",
        "Both statements correctly distinguish demographic statistical profiles from psychographic lifestyle values.",
        "Differentiates demographics from psychographics in audience segmentation."),
    ar("Ad Models & Planning", "Consumer Insight Power",
        "A brilliant advertising campaign is usually anchored in a profound 'Consumer Insight'.",
        "A consumer insight unearths an unstated, deep-seated emotional truth or friction in the consumer's daily life that the brand uniquely resolves.",
        "both_correct_explain",
        "Grounding a campaign in an authentic emotional truth resonates deeply, making the brand solution irresistible.",
        "Analyzes the strategic power of a consumer insight in campaign planning."),
    seq("Ad Models & Planning", "Advertising Campaign Planning Cycle",
        "Arrange the stages of planning and executing an integrated advertising campaign in sequential order:",
        ["Market research, competitive audit, and client marketing brief", "Formulating target audience persona, consumer insight, and creative brief", "Creative ideation: developing the 'Big Idea', copywriting, and art direction", "Media planning, channel selection, budget allocation, and flighting schedules", "Campaign launch followed by post-testing campaign evaluation against DAGMAR goals"],
        "I -> II -> III -> IV -> V",
        "Campaign sequence: Research/Brief -> Strategy/Insight -> Creative Big Idea -> Media planning -> Execution/Evaluation.",
        "Sequences the advertising campaign planning process."),
    mcq("Ad Models & Planning", "The Big Idea",
        "In advertising agency lore, what is the 'Big Idea' (conceptualized by David Ogilvy and George Lois)?",
        "The central, unifying creative concept that dramatizes the brand promise, cuts through commercial clutter, and is extendable across all media formats",
        ["A gigantic billboard measuring ten kilometers wide",
         "The financial bonus paid to the chief executive officer",
         "A computer hard drive that stores every advertisement ever created"],
        "The Big Idea is the overarching creative hook that gives meaning to the brand and translates across print, TV, outdoor, and digital.",
        "Defines the 'Big Idea' in advertising creative strategy."),
    stmt("Ad Models & Planning", "Brand Positioning Statement",
        "Brand Positioning (pioneered by Al Ries and Jack Trout) is not what you do to a product, but what you do to the mind of the prospect.",
        "A brand positioning statement defines how the brand uniquely occupies a distinct, valued place in the customer's mind relative to competitors.",
        "both_true",
        "Both statements reflect Ries and Trout's definitive formulation of brand positioning theory.",
        "Validates Al Ries and Jack Trout's brand positioning theory."),
    ar("Ad Models & Planning", "Pre-Testing Advertising Effectiveness",
        "Agencies conduct extensive 'Pre-Testing' (such as focus groups and animatics tests) before airing multi-crore television commercials.",
        "Pre-testing identifies confusing copy, offensive double-entendres, or weak branding before massive commercial budgets are committed.",
        "both_correct_explain",
        "Testing rough cuts mitigates financial risk by ensuring the communication message works effectively before buying expensive media time.",
        "Explains the risk-mitigation rationale of advertising pre-testing."),
    match("Ad Models & Planning", "DAGMAR Progression Levels",
        "Match the DAGMAR communication level in List-I with its cognitive state in List-II:",
        ["Awareness", "Comprehension", "Conviction", "Action"],
        ["Consumer becomes conscious of brand existence within category", "Consumer understands the specific attributes, features, and benefits offered", "Consumer develops a favorable mental disposition and emotional intention to buy", "Consumer takes physical or transactional steps to purchase the brand"],
        "A-I, B-II, C-III, D-IV",
        "Awareness = conscious of existence; Comprehension = understanding features; Conviction = intention to buy; Action = purchase.",
        "Matches DAGMAR hierarchy of communication stages."),
    mcq("Ad Models & Planning", "Call to Action (CTA)",
        "In direct-response, print, and digital advertising, what is the 'Call to Action' (CTA)?",
        "A clear, urgent directive instructing the consumer on the exact next step to take (e.g. 'Click Here to Subscribe', 'Call Toll-Free Now')",
        ["The alarm clock that wakes up the copywriter in the morning",
         "A police megaphone ordering traffic to move",
         "The closing music played when a film ends"],
        "The CTA instructs the prospect precisely what behavioral step to execute immediately, closing the conversion loop.",
        "Identifies the role of a Call to Action (CTA) in advertising."),
    stmt("Ad Models & Planning", "High vs Low Involvement Purchases",
        "Buying an automobile or residential apartment is a 'High Involvement' decision involving extensive cognitive search, comparison, and risk evaluation.",
        "Buying a pack of chewing gum or a matchbox is a 'Low Involvement' habitual purchase with minimal cognitive evaluation.",
        "both_true",
        "Both statements accurately illustrate the behavioral difference between high-involvement and low-involvement consumer decisions.",
        "Contrasts high-involvement with low-involvement purchasing behaviors."),
    ar("Ad Models & Planning", "Emotional vs Rational Trajectory",
        "In low-involvement feeling categories (like ice-cream or fashion accessories), ads focus on mood, impulse delight, and visual pleasure.",
        "Consumers in low-involvement impulse categories do not read dense statistical tables or technical engineering blueprints before purchasing.",
        "both_correct_explain",
        "Because impulse purchases are driven by immediate sensory gratification, emotional visual appeals are far more effective than dense technical data.",
        "Analyzes advertising strategy in low-involvement feeling categories."),
    mcq("Ad Models & Planning", "Media Flighting vs Pulsing",
        "In media scheduling, what is the difference between 'Flighting' and 'Pulsing'?",
        "Flighting alternates periods of active advertising with periods of zero advertising; Pulsing maintains a continuous baseline of ads with intermittent heavy bursts",
        ["Flighting is done on airplanes; Pulsing is done on submarines",
         "Flighting uses only print; Pulsing uses only carrier pigeons",
         "Flighting is illegal under tax laws; Pulsing is mandatory"],
        "Flighting runs bursts separated by complete hiatuses; Pulsing maintains a low steady continuous presence boosted by burst waves.",
        "Differentiates media flighting from pulsing schedules."),
    match("Ad Models & Planning", "Creative Brief Components",
        "Match the creative brief section in List-I with its strategic question in List-II:",
        ["Target Audience Persona", "Core Consumer Problem / Barrier", "Single-Minded Proposition (SMP)", "Tone of Voice"],
        ["Who are we speaking to, and what does their daily life look like?", "What obstacle or prejudice prevents them from buying our brand today?", "What is the single most compelling, persuasive promise we must communicate?", "How should our brand sound (e.g. authoritative, witty, empathetic, or rebellious)?"],
        "A-I, B-II, C-III, D-IV",
        "Target persona = who we speak to; Problem = obstacle to purchase; SMP = single compelling promise; Tone = brand personality.",
        "Matches sections of a creative brief to strategic questions."),
    seq("Ad Models & Planning", "FCB Quadrant Strategy Alignment",
        "Arrange the operational consumer strategy progressions across the four quadrants of the FCB Grid:",
        ["Q1: High Involvement / Think: Learn -> Feel -> Do (Car, House)", "Q2: High Involvement / Feel: Feel -> Learn -> Do (Jewelry, Designer Couture)", "Q3: Low Involvement / Think: Do -> Learn -> Feel (Detergent, Engine Oil)", "Q4: Low Involvement / Feel: Do -> Feel -> Learn (Beer, Candy, Soft Drinks)"],
        "I -> II -> III -> IV",
        "FCB Grid learning models: Q1 (Informative: Learn-Feel-Do) -> Q2 (Affective: Feel-Learn-Do) -> Q3 (Habit: Do-Learn-Feel) -> Q4 (Satisfaction: Do-Feel-Learn).",
        "Sequences learning hierarchies across FCB Grid quadrants."),
    mcq("Ad Models & Planning", "Top-of-Mind Awareness (TOMA)",
        "In brand tracking studies, what is 'Top-of-Mind Awareness' (TOMA)?",
        "The very first brand name that spontaneously comes into a consumer's head when asked an unprompted question about a product category",
        ["A hat brand worn by fashion runway models",
         "The final score achieved on a university written test",
         "The highest level of brain wave activity recorded in a hospital"],
        "TOMA measures supreme brand salience: being the first unprompted brand recalled when a category is mentioned.",
        "Defines Top-of-Mind Awareness (TOMA).")
]

# ==============================================================================
# SLOT 35: Advertising Agency Structure & Self-Regulation (ASCI)
# ==============================================================================
SLOTS_31_35[35] = [
    mcq("Ad Agency & Regulation", "Four Pillars of Ad Agency",
        "A traditional full-service advertising agency is structured around which four foundational functional departments?",
        "Account Management (Client Servicing), Account Planning (Strategy), Creative (Copy & Art), and Media Planning & Buying",
        ["Accounting, Cafeteria Management, Security, and Car Washing",
         "Printing, Paper Manufacturing, Truck Driving, and Postal Delivery",
         "Legal Prosecution, Police Intelligence, Foreign Diplomacy, and Military Strategy"],
        "Full-service agencies rest on Account Management (liaison), Strategy (insights), Creative (execution), and Media (placement).",
        "Identifies the four core departments of a full-service advertising agency."),
    mcq("Ad Agency & Regulation", "Account Executive / Client Servicing",
        "What is the primary operational role of an 'Account Executive' (Client Servicing Executive) in an advertising agency?",
        "Acting as the vital bridge between the client and the agency, managing client expectations, schedules, budgets, and briefing internal teams",
        ["Writing all television commercial scripts in rhyming couplets",
         "Designing digital typography on Adobe Illustrator",
         "Fixing paper jams inside office photocopy machines"],
        "Client servicing executives manage the client relationship, interpret client business needs, and coordinate internal agency workflows.",
        "Defines the role of an Account Executive in client servicing."),
    stmt("Ad Agency & Regulation", "Copywriter and Art Director Duo",
        "In an agency creative department, creative concepts are typically birthed by a partnership pairing: a Copywriter and an Art Director.",
        "The Copywriter is responsible for verbal concept, headlines, and written text; the Art Director is responsible for visual aesthetics, layout, and art.",
        "both_true",
        "Both statements correctly describe the legendary creative partnership between copywriters (words) and art directors (visuals).",
        "Explains the creative partnership between the Copywriter and Art Director."),
    ar("Ad Agency & Regulation", "ASCI Mandate",
        "The Advertising Standards Council of India (ASCI), established in 1985, is a voluntary self-regulatory body.",
        "ASCI's code is designed to ensure that commercial advertising in India remains truthful, non-misleading, decent, and fair to competitors.",
        "both_correct_explain",
        "Industry stakeholders established ASCI self-regulation to protect consumer trust by preventing deceptive and offensive advertisements.",
        "Analyzes the self-regulatory role and mandate of ASCI."),
    match("Ad Agency & Regulation", "Agency Departments",
        "Match the advertising agency department in List-I with its core function in List-II:",
        ["Client Servicing", "Account Planning", "Creative Department", "Media Planning & Buying"],
        ["Client liaison, project management, and relationship maintenance", "Consumer research, cultural insights, and creative briefs", "Ideation, copywriting, visualization, and artistic execution", "Audience analysis, media mix selection, and negotiating ad space rates"],
        "A-I, B-II, C-III, D-IV",
        "Client servicing = liaison/project management; Planning = consumer insights; Creative = ideation/execution; Media = rate negotiation/placement.",
        "Matches advertising agency departments to functions."),
    mcq("Ad Agency & Regulation", "Media Planner Role",
        "What is the primary responsibility of a 'Media Planner' in an advertising agency?",
        "Determining the most effective combination of media channels (TV, digital, print, outdoor) to reach the target audience within budget constraints",
        ["Painting billboard posters by hand with oil paints",
         "Writing political speeches for television news anchors",
         "Repairing broken transmission antennas on television broadcast towers"],
        "Media planners analyze demographic habits, GRPs, and CPMs to decide where, when, and how often ads should run to maximize ROI.",
        "Defines the responsibilities of a Media Planner."),
    stmt("Ad Agency & Regulation", "Consumer Complaints Council (CCC) of ASCI",
        "ASCI adjudicates public and industry complaints against misleading advertisements through its 'Consumer Complaints Council' (CCC).",
        "The CCC includes independent eminent citizens from civil society (doctors, lawyers, consumer activists) as well as advertising professionals.",
        "both_true",
        "Both statements are true. ASCI's CCC has a majority of civil society members to ensure unbiased consumer-first adjudication.",
        "Evaluates the composition and role of ASCI's Consumer Complaints Council."),
    ar("Ad Agency & Regulation", "Self-Regulation vs Statutory Control",
        "The advertising industry worldwide strongly champions self-regulation through bodies like ASCI over direct bureaucratic state censorship.",
        "Self-regulation by industry peers is faster, more flexible, and technologically informed, preventing heavy-handed government suppression of commercial speech.",
        "both_correct_explain",
        "Self-regulation offers swift, expert, adaptive dispute resolution without bureaucratic overreach or delays.",
        "Explains the industry rationale for self-regulation over government censorship."),
    seq("Ad Agency & Regulation", "ASCI Complaint Adjudication Workflow",
        "Arrange the stages of an ASCI complaint inquiry in proper sequence:",
        ["Citizen, competitor, or monitoring cell files complaint against deceptive advertisement", "ASCI Secretariat examines complaint and issues formal notice to the advertiser", "Advertiser submits technical evidence, clinical data, and written justification", "Consumer Complaints Council (CCC) reviews evidence and deliberates compliance with code", "CCC issues verdict: complaint upheld (directing withdrawal/modification) or dismissed"],
        "I -> II -> III -> IV -> V",
        "ASCI procedure: Complaint receipt -> Notice to advertiser -> Response submission -> CCC deliberation -> Final verdict/withdrawal order.",
        "Sequences the ASCI complaint handling and adjudication process."),
    mcq("Ad Agency & Regulation", "Agency Commission System",
        "Historically, what was the traditional '15% Agency Commission' system that defined advertising remuneration for decades?",
        "Media owners (newspapers, TV) granted an accredited agency a 15% discount on gross ad space, which the agency retained as its fee",
        ["Clients paid agencies 15% of all corporate stock shares",
         "Governments taxed all advertising agencies 15% of their total employee salaries",
         "Agencies paid consumers 15% cash back for every advertisement watched"],
        "The historic 15% commission rewarded agencies by granting them a 15% discount on media buys; today it is largely replaced by fee/retainer models.",
        "Explains the traditional 15% media commission system in advertising."),
    stmt("Ad Agency & Regulation", "Celebrity Endorsement Guidelines (ASCI)",
        "Under ASCI and Central Consumer Protection Authority (CCPA) guidelines, celebrities must conduct due diligence to verify that claims made in ads are genuine.",
        "Celebrities enjoy absolute legal immunity and are permitted to endorse fraudulent medical cures without any legal liability.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because CPA 2019 and ASCI impose strict liability, including hefty fines and endorsement bans on celebrities endorsing misleading ads.",
        "Evaluates legal and ethical liabilities of celebrity endorsers in advertising."),
    ar("Ad Agency & Regulation", "Greenwashing Scrutiny",
        "ASCI has instituted stringent monitoring guidelines against 'Greenwashing' in commercial advertising.",
        "Companies frequently make vague, unsubstantiated, or exaggerated environmental claims (e.g. '100% eco-friendly') to deceptively exploit climate-conscious consumers.",
        "both_correct_explain",
        "Because unsubstantiated green claims mislead consumers, advertising watchdogs have cracked down on environmental greenwashing.",
        "Analyzes regulatory crackdowns on greenwashing."),
    match("Ad Agency & Regulation", "ASCI Code Chapters",
        "Match the ASCI Code Chapter in List-I with its core ethical mandate in List-II:",
        ["Chapter I: Honesty", "Chapter II: Decency", "Chapter III: Safety", "Chapter IV: Fairness in Competition"],
        ["Ads must be truthful, non-misleading, and substantiated by empirical evidence", "Ads must not offend generally accepted standards of public decency", "Ads must not encourage hazardous practices or endanger children", "Ads must not unfairly denigrate, plagiarize, or attack competitors"],
        "A-I, B-II, C-III, D-IV",
        "Chapter I = Honesty/Truth; Chapter II = Decency; Chapter III = Safety; Chapter IV = Fairness/Competition.",
        "Matches the four fundamental chapters of the ASCI Code to their ethical mandates."),
    mcq("Ad Agency & Regulation", "Media Buying vs Media Planning",
        "What is the distinct function of a 'Media Buyer' as opposed to a 'Media Planner'?",
        "The media buyer negotiates optimal commercial prices, discounts, and placement positioning with television networks and publishers to execute the plan",
        ["The media buyer writes the creative script for the radio show",
         "The media buyer acts as the stunt driver in television commercials",
         "The media buyer prints copies of the newspaper in their own basement"],
        "While planners design the strategic channel blueprint, buyers execute the transactions, leveraging bulk buying power to secure optimal rates.",
        "Differentiates media planning from media buying."),
    stmt("Ad Agency & Regulation", "Agency Pitch (Credentials & Speculative)",
        "An 'Agency Pitch' is a competitive contest where multiple advertising agencies present strategic and creative ideas to win a prospective client's account.",
        "Once an agency wins an account, it holds a permanent monopoly and can never be fired by the client for the rest of eternity.",
        "s1_true_s2_false",
        "Statement 1 is true. Statement 2 is false because agency contracts are subject to periodic review, renewals, and competitive pitches.",
        "Defines the competitive agency pitch process."),
    ar("Ad Agency & Regulation", "Influencer Disclosure Guidelines",
        "ASCI mandates that social media influencers must prominently label paid promotional content with tags like '#Ad', '#Sponsored', or '#PaidPartnership'.",
        "Consumers have a fundamental right to know whether an endorsement reflects an organic personal opinion or a financially paid commercial arrangement.",
        "both_correct_explain",
        "Mandatory disclosure tags prevent deceptive stealth marketing, protecting consumer transparency online.",
        "Explains the rationale for mandatory influencer advertising disclosures."),
    mcq("Ad Agency & Regulation", "Traffic Department in Agency",
        "In the operational workflow of an advertising agency, what is the role of the 'Traffic Department'?",
        "Managing internal production routing, ensuring creative jobs move smoothly between copy, art, client servicing, and media without missing deadlines",
        ["Directing vehicular traffic in the agency parking garage",
         "Issuing driving licenses to television commercial actors",
         "Purchasing commercial airplanes for agency executives"],
        "The traffic department is the internal project management hub tracking job jackets, asset approvals, and print/broadcast deadlines.",
        "Identifies the role of the Traffic Department in an ad agency."),
    match("Ad Agency & Regulation", "Key Regulatory & Industry Bodies",
        "Match the advertising industry association in List-I with its identity in List-II:",
        ["AAAI", "ISA", "ASCI", "CCPA"],
        ["Advertising Agencies Association of India (representing accredited agencies)", "Indian Society of Advertisers (representing corporate advertiser brands)", "Advertising Standards Council of India (voluntary self-regulatory body)", "Central Consumer Protection Authority (statutory body with penal powers against misleading ads)"],
        "A-I, B-II, C-III, D-IV",
        "AAAI = agencies; ISA = advertisers; ASCI = self-regulatory body; CCPA = statutory consumer protection authority under CPA 2019.",
        "Matches advertising industry and statutory oversight bodies."),
    seq("Ad Agency & Regulation", "Ad Agency Creative Development Pipeline",
        "Arrange the operational stages of creating an ad campaign inside an agency:",
        ["Account Planner conducts consumer research and writes Creative Brief", "Creative Director briefs team of Copywriter and Art Director", "Creative team brainstorms diverse concepts and presents ideas to Creative Director", "Winning conceptual layouts and scripts presented to client during pitch meeting", "Client approves concept, triggering studio artwork creation and media production"],
        "I -> II -> III -> IV -> V",
        "Creative development pipeline: Creative brief -> Team briefing -> Brainstorming -> Client presentation -> Production execution.",
        "Sequences internal agency creative development pipeline."),
    mcq("Ad Agency & Regulation", "In-House Advertising Agency",
        "What is an 'In-House Agency' (such as Target's or Apple's internal creative groups)?",
        "An advertising agency established, owned, and operated entirely within a corporate enterprise to serve its own internal branding needs",
        ["An agency that works exclusively on residential apartment interiors",
         "An agency operated by children inside their parents' living room",
         "A printing machine installed inside a kitchen pantry"],
        "In-house agencies operate inside parent companies, providing faster turnaround, institutional alignment, and eliminating external agency markup fees.",
        "Defines an in-house advertising agency.")
]

print("Mass Media Slots 31 to 35 compiled successfully: 5 slots (100 questions).")
