import sys, os
sys.path.insert(0, os.getcwd())
from scripts.subject_generators.slot_helpers import mcq, stmt, ar, match, seq

CH_INEQ = "Patterns of Social Inequality and Exclusion"

def build_slot(ch, items):
    res = []
    for itm in items:
        qtype = itm[0]
        if qtype == "mcq":
            _, top, stem, corr, wrongs, expl = itm
            res.append(mcq(ch, top, stem, corr, wrongs, expl))
        elif qtype == "stmt":
            _, top, s1, s2, rel, expl = itm
            res.append(stmt(ch, top, s1, s2, rel, expl))
        elif qtype == "ar":
            _, top, a, r, rel, expl = itm
            res.append(ar(ch, top, a, r, rel, expl))
        elif qtype == "match":
            _, top, stem, l1, l2, pair, expl = itm
            res.append(match(ch, top, stem, l1, l2, pair, expl))
        elif qtype == "seq":
            _, top, stem, items_list, order_str, expl = itm
            res.append(seq(ch, top, stem, items_list, order_str, expl))
    assert len(res) == 20, f"Slot has {len(res)} items instead of 20"
    return res

# Slot 21: Social Exclusion & Prejudice vs Discrimination (20 Qs)
s21_raw = [
    ("mcq", "Prejudice vs Discrimination", "In sociological theory, what is the core distinction between 'Prejudice' and 'Discrimination'?",
     "Prejudice refers to preconceived attitudes, opinions, or stereotypes, whereas discrimination refers to actual observable differential actions and denial of equal treatment",
     ["Prejudice applies only to legal statutes, while discrimination applies only to spoken dialects",
      "Prejudice is always positive and supportive, whereas discrimination is always accidental",
      "Prejudice is an economic tax rate, while discrimination is an international maritime treaty"],
     "Prejudice is a cognitive/affective attitude; discrimination is overt behavioral denial of equality."),
    ("stmt", "Social Exclusion as Structural",
     "Social exclusion is not accidental, but structural: it is systematically built into societal institutions like caste, class, and gender.",
     "Social exclusion is entirely voluntary: marginalized groups deliberately choose to exclude themselves from healthcare, schools, and civic amenities.", 3,
     "Statement I is correct as exclusion is structural; Statement II is incorrect because exclusion is involuntarily imposed by dominant groups."),
    ("ar", "Stereotypes and Social Distance",
     "Stereotypes homogenize entire social groups, ignoring individual differences and reinforcing prejudice.",
     "Stereotypes categorize individuals based on simplistic, unverified generalizations, creating emotional social distance between communities.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Stereotypes flatten individual diversity, legitimizing prejudice."),
    ("match", "Key Inequality Concepts",
     "Match the sociological concepts in List I with their definitions in List II:",
     [("A", "Prejudice"), ("B", "Discrimination"), ("C", "Stereotype"), ("D", "Social Exclusion")],
     [("I", "Preconceived, unexamined opinion held towards members of an out-group"),
      ("II", "Overt differential treatment and denial of rights or opportunities to a group"),
      ("III", "Fixed, oversimplified mental image or categorization of an entire group"),
      ("IV", "Systemic processes that prevent individuals or groups from full civic participation")],
     "A-I, B-II, C-III, D-IV",
     "Prejudice is attitude; Discrimination is action; Stereotype is oversimplified image; Exclusion is denial of full participation."),
    ("seq", "Escalation of Social Inequality",
     "Arrange the stages through which inter-group bias escalates from cognitive attitude to institutional oppression in logical sequence:",
     [("A", "Formation of ethnocentric cultural stereotypes and cognitive biases"),
      ("B", "Internalization of social prejudices and negative affective attitudes towards out-groups"),
      ("C", "Individual interpersonal acts of discrimination and avoidance in daily interaction"),
      ("D", "Institutionalized social exclusion, legal disabilities, and structural oppression")],
     "A, B, C, D",
     "Bias moves sequentially from stereotypes to prejudice, personal discrimination, and institutional exclusion.")
]

s21_extras = [
    ("Bogardus Social Distance Scale", "In social psychology, the 'Bogardus Social Distance Scale' empirically measures:",
     "The degree of intimacy and social acceptance an individual or group is willing to permit towards members of other social, racial, or ethnic groups",
     ["The physical geographical mileage between two capital cities", "The total number of passenger trains operating in a province", "The depth of ocean trenches measured in nautical fathoms"],
     "Bogardus developed the social distance scale to quantify willingness to interact with out-groups across varying levels of intimacy."),
    ("Institutional Discrimination Concept", "In contemporary sociology, 'Institutional Discrimination' refers to:",
     "Unfair policies and structural practices built into the normal functioning of institutions (banks, courts, schools) that systematically disadvantage minority groups",
     ["A single individual shouting an insult at an opposing sports team", "A traffic police officer giving directions to an automobile driver", "An athletic race conducted on a university track field"],
     "Institutional discrimination operates through systemic norms and procedures, even without individual ill-will."),
    ("Self-Fulfilling Prophecy (Merton)", "Robert K. Merton's concept of the 'Self-Fulfilling Prophecy' explains how social prejudice works by:",
     "A false definition of a situation evoking a new behavior that makes the originally false conception come true",
     ["Predicting volcanic eruptions using astronomical telescopes", "Calculating the exact closing price of commercial corporate stocks", "A religious miracle that violates all physical laws of nature"],
     "A self-fulfilling prophecy shows how prejudiced expectations induce marginalized groups into behaviors that seem to validate the original prejudice."),
    ("Social Exclusion as Involuntary", "Sociologists emphasize that social exclusion is involuntary because:",
     "Individuals are denied access to resources, jobs, and rights regardless of their personal desire to participate in mainstream society",
     ["Everyone in society chooses to live in solitary isolation in forests", "The government forces all wealthy citizens to abandon their private bank accounts", "Marginalized groups refuse to accept free gifts of gold coins"],
     "Exclusion is imposed from above: individuals seek participation but encounter institutional barriers, discrimination, and stigma."),
    ("Multidimensional Nature of Exclusion", "Social exclusion is described as 'Multidimensional' because it encompasses:",
     "The deprivation of economic livelihoods, denial of political voice, social stigmatization, and spatial segregation simultaneously",
     ["Having five different telephone numbers in a private address book", "Speaking three different languages during lunch hours", "Travelling across multiple time zones in an aeroplane"],
     "Social exclusion combines economic poverty, spatial segregation, political powerlessness, and social dishonour."),
    ("Stigma and Erving Goffman", "Sociologist Erving Goffman defined 'Stigma' as:",
     "An attribute that is deeply discrediting, reducing an individual from a whole, usual person to a tainted, discounted one in social interaction",
     ["An official state military medal awarded for bravery in battle", "A high educational diploma granted by a university", "A commercial lottery ticket winning a cash jackpot"],
     "Goffman analyzed stigma as spoiled identity: an attribute that disqualifies a person from full social acceptance."),
    ("Subtle vs Overt Discrimination", "In modern urban professional environments, discrimination against lower castes often manifests in 'subtle' forms such as:",
     "Exclusion from informal professional networks, bias in annual performance reviews, and subjective evaluations of 'merit' and 'cultural fit'",
     ["Physical expulsion from office buildings by armed guards", "Mandatory requirements to wear specialized wooden sandals", "Public proclamations made by town criers in municipal markets"],
     "Subtle discrimination operates through subjective assessments of 'merit', corporate culture fit, and informal elite networking."),
    ("Intersectionality Concept (Crenshaw)", "Legal scholar Kimberlé Crenshaw's theory of 'Intersectionality' argues that:",
     "Multiple social categories (gender, caste, class, race) intersect to create unique, compounded systems of oppression that cannot be understood separately",
     ["All human beings have identical life experiences regardless of gender or caste", "Traffic intersections must be regulated by automated computer cameras", "Social inequality can be completely eliminated by increasing train speeds"],
     "Intersectionality shows how Dalit women experience compounded oppression at the nexus of caste violence, economic exploitation, and patriarchy."),
    ("Spatial Exclusion in Slums", "Urban spatial segregation in Indian cities excludes slum residents from civic citizenship through:",
     "Denial of legal property tenure, lack of piped municipal water and sanitation, and arbitrary demolition without rehabilitation",
     ["Free unlimited access to metropolitan air-conditioned subway systems", "Automatic appointment of all slum residents as municipal city commissioners", "Mandatory free provision of swimming pools and tennis courts"],
     "Slum dwellers suffer spatial exclusion: denied basic water, sewage, and secure tenure despite providing vital urban labour."),
    ("De Facto vs De Jure Discrimination", "What is the key analytical distinction between 'De Jure' and 'De Facto' discrimination?",
     "De Jure discrimination is legally sanctioned by statutory law (e.g. apartheid), while De Facto discrimination occurs in actual social practice despite legal prohibitions",
     ["De Jure applies only to music, while De Facto applies only to cooking", "De Jure is completely invisible, while De Facto is written in ancient Latin texts", "There is zero sociological difference between the two terms"],
     "De jure discrimination is codified in law; de facto discrimination persists in social practice despite constitutional bans."),
    ("Internalized Oppression", "Sociologists use the concept of 'Internalized Oppression' to describe the tragic psychological condition where:",
     "Members of an oppressed group unconsciously absorb and believe the negative stereotypes and inferior status ascribed to them by dominant society",
     ["An individual intentionally forgets their own name to evade criminal prosecution", "A wealthy industrialist pretends to be poor to avoid paying income taxes", "A university professor refuses to publish academic research books"],
     "Internalized oppression occurs when victims of systemic stigma internalize the belief that their subordination is deserved."),
    ("Privilege Blindness Concept", "In stratification studies, 'Privilege Blindness' refers to:",
     "The tendency of dominant, upper-caste, or affluent individuals to view their structural advantages as purely personal talent and remain blind to systemic inequality",
     ["A physical medical condition affecting eyesight in bright sunlight", "A statutory regulation that forbids citizens from owning mirrors", "The total absence of any monetary currency in modern economies"],
     "Privilege blindness naturalizes inherited structural advantages, allowing upper strata to dismiss affirmative action as unfair."),
    ("Social Distance in Urban Rental Housing", "Sociological studies of metropolitan rental housing markets in India reveal persistent social distance through:",
     "Landlords openly denying rental apartments to Dalits, Muslims, and single women under pretexts of vegetarianism or 'family preferences'",
     ["Mandatory government lotteries that assign apartments randomly across all castes", "Free distribution of luxury penthouses to all arriving rural migrant workers", "Complete equality where landlords never inquire about tenant caste or identity"],
     "Urban rental markets reproduce caste and religious exclusion through proxy filters like food habits and community background."),
    ("Affirmative Action as Leveling Tool", "In sociological theory, 'Affirmative Action' (reservation policies) is justified not as charity, but as:",
     "A compensatory justice mechanism designed to dismantle historical exclusion and ensure representation of disadvantaged groups in public power",
     ["A permanent penalty designed to punish children for the actions of ancient monarchs", "A commercial promotion to encourage people to buy corporate shares", "A lottery program for distributing foreign airline tickets"],
     "Reservations provide compensatory representation, counteracting institutional closure and historical denial of educational capital."),
    ("Exclusion and Human Development", "The Amartya Sen capability approach conceptualizes poverty and social exclusion primarily as:",
     "Capability deprivation: the systematic denial of basic freedoms, education, healthcare, and opportunities to lead a life one has reason to value",
     ["A simple temporary shortage of physical paper currency in an individual's wallet", "A biological defect in human chromosomal genetics", "A voluntary preference for ascetic living in wilderness forests"],
     "Sen defines poverty and exclusion as capability deprivation, restricting human freedom and agency beyond mere income figures.")
]
for itm in s21_extras:
    top, stem, corr, wrongs, sol = itm
    s21_raw.append(("mcq", top, stem, corr, wrongs, sol))
SLOT21 = build_slot(CH_INEQ, s21_raw)

# Slot 22: Untouchability - Triad, Article 17, PCR & Atrocities Acts (20 Qs)
s22_raw = [
    ("mcq", "Untouchability Triad of Oppression", "In sociological analysis, the practice of 'Untouchability' against Dalits encompasses which foundational triad of oppression?",
     "Exclusion from common civic spaces, enforcement of humiliating subordination, and severe economic exploitation",
     ["Exemption from all state taxes, appointment to high judicial offices, and free foreign holidays",
      "Mandatory inclusion in elite private clubs, free distribution of agricultural tractors, and double votes",
      "Compulsory attendance at university lectures, free private medical insurance, and diplomatic passports"],
     "Untouchability is a structural triad: exclusion from wells/temples, ritual humiliation, and forced unpaid labour (begar)."),
    ("stmt", "Article 17 of Indian Constitution",
     "Article 17 of the Constitution of India formally abolished 'Untouchability' and forbade its practice in any form.",
     "Article 17 permitted the practice of untouchability in private religious shrines and rural village wells.", 3,
     "Statement I is correct as Article 17 unequivocally abolished untouchability; Statement II is incorrect as no exceptions exist."),
    ("ar", "Persistence of Atrocities Post-Abolition",
     "Despite the constitutional abolition of untouchability, caste atrocities continue to be reported across rural and urban India.",
     "Deep-seated feudal mindsets and dominant caste resentment against assertive Dalits claiming equality provoke violent resistance.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Constitutional law does not automatically erase feudal power dynamics."),
    ("match", "Anti-Untouchability Statutory Acts and Years",
     "Match the landmark anti-caste legislations in List I with their enactment years in List II:",
     [("A", "Article 17 of Constitution"), ("B", "Untouchability (Offences) Act"), ("C", "Protection of Civil Rights (PCR) Act"), ("D", "SC and ST (Prevention of Atrocities) Act")],
     [("I", "1950"), ("II", "1955"), ("III", "1976"), ("IV", "1989")],
     "A-I, B-II, C-III, D-IV",
     "Article 17 in 1950; Untouchability Offences Act in 1955; amended into PCR Act in 1976; PoA Act enacted in 1989."),
    ("seq", "Evolution of Legal Protection Against Untouchability",
     "Arrange the legislative milestones protecting Dalits from untouchability in chronological order:",
     [("A", "Enactment of Article 17 in the Constitution of India abolishing untouchability"),
      ("B", "Parliamentary passage of the Untouchability (Offences) Act"),
      ("C", "Strengthening of the law into the Protection of Civil Rights Act"),
      ("D", "Passage of the comprehensive Scheduled Castes and Scheduled Tribes (Prevention of Atrocities) Act")],
     "A, B, C, D",
     "Legal protection evolved from Article 17 (1950) to 1955 Offences Act, 1976 PCR Act, and 1989 Prevention of Atrocities Act.")
]

s22_extras = [
    ("Special Courts under PoA Act 1989", "A vital procedural feature introduced by the SC/ST (Prevention of Atrocities) Act, 1989 to ensure justice was:",
     "The mandatory establishment of Special Courts in every district for speedy trial of atrocity offenses",
     ["Transferring all trials to international tribunals in Geneva", "Allowing caste panchayats to settle atrocity cases through informal compromise", "Banning all victims from filing formal written complaints"],
     "The 1989 Act mandated Special Courts and Special Public Prosecutors to accelerate trials of violent caste offenses."),
    ("Denial of Common Water Sources", "Historically, the most pervasive daily manifestation of untouchability in rural Indian villages was:",
     "Prohibiting Dalits from drawing water from common village public wells and tanks, forcing them to use distant, contaminated puddles",
     ["Forbidding Dalits from cultivating wheat crops", "Requiring Dalits to speak only classical Sanskrit in village streets", "Banning Dalits from owning domestic chickens"],
     "Denial of shared drinking water sources was the central ritual and physical enforcement of untouchability."),
    ("Temple Entry Movements", "Historical Temple Entry Movements (e.g. Vaikom Satyagraha 1924, Kalaram Temple 1930) were fought primarily to:",
     "Assert the fundamental civic and religious right of Dalits to enter public sacred spaces and walk on public temple roads",
     ["Demolish all Hindu temples across southern and western India", "Convert all temples into commercial grain warehouses", "Forbid upper castes from ever entering any religious shrines"],
     "Temple entry struggles attacked the ideological fortress of untouchability, asserting equal human rights to public sacred spaces."),
    ("Dr. Ambedkar's Mahad Satyagraha 1927", "The historic Mahad Satyagraha led by Dr. B.R. Ambedkar on March 20, 1927 was organized to:",
     "Assert the civic right of Dalits to draw drinking water from the public Chhadar Tank in Mahad",
     ["Demand independence from the British Empire in 1927", "Burn all printed textbooks in regional libraries", "Found an international commercial shipping line"],
     "Mahad Satyagraha was a watershed civic rights mobilization claiming equal access to public drinking water."),
    ("Manusmriti Dahan 1927", "Why did Dr. B.R. Ambedkar and his followers publicly burn a copy of the *Manusmriti* on December 25, 1927?",
     "As a symbolic rejection of the ancient sacred text that canonized caste hierarchy, untouchability, and the subjugation of women",
     ["Because it was printed in an illegible English font", "Because they wanted to replace it with foreign colonial tax registers", "Because the paper had been damaged by monsoon rains"],
     "Manusmriti Dahan was a radical symbolic revolt against the textual sanctification of caste inequality and untouchability."),
    ("Begar (Forced Unpaid Labour)", "The practice of 'Begar' historically forced upon Dalits by dominant caste landlords consisted of:",
     "Compulsory unpaid or underpaid manual labour (cleaning, carcass disposal, agricultural work) under threat of violence",
     ["Voluntary paid overtime employment in commercial manufacturing plants", "A state scholarship granted to university students for research", "A military exercise performed by colonial cavalry officers"],
     "Begar was structural economic bondage: Dalits were coerced into performing menial, polluting tasks without wages."),
    ("Manual Scavenging Prohibition Act 2013", "The Prohibition of Employment as Manual Scavengers and their Rehabilitation Act, 2013 aims to:",
     "Completely eradicate the dehumanizing manual cleaning of human excreta from dry latrines, sewers, and septic tanks, and rehabilitate workers",
     ["Mandate manual cleaning of sewers without any safety gear for all citizens", "Promote manual scavenging as an honourable traditional craft", "Export all sewer cleaning equipment to foreign countries"],
     "The 2013 Act criminalizes manual scavenging, mandating mechanization of sewer cleaning and comprehensive rehabilitation."),
    ("Ambedkar's Conversion to Buddhism 1956", "Why did Dr. B.R. Ambedkar renounce Hinduism and convert to Buddhism with millions of followers at Nagpur in October 1956?",
     "He concluded that untouchability was inextricably rooted in Hindu sacred scriptures, embracing Buddhism for its egalitarian, rational, and ethical values",
     ["He wished to become a sovereign royal monarch of a foreign Buddhist empire", "He was compelled by British colonial military authorities to change his religion", "He wanted to avoid paying taxes to the Indian government"],
     "Ambedkar embraced Buddhism (Navayana) as an egalitarian path to human dignity, rational ethics, and liberation from caste."),
    ("Dalit Panthers Movement 1972", "The Dalit Panthers formed in Maharashtra in 1972 were inspired by:",
     "The radical Black Panther Party in the United States, utilizing militant mass mobilization, assertive literature, and direct resistance against caste atrocities",
     ["Ancient medieval knights fighting for European royal courts", "Commercial advertising agencies designing corporate branding campaigns", "Conservative orthodox religious councils in rural villages"],
     "The Dalit Panthers channeled youth militancy and creative literature to resist atrocities and assert revolutionary anti-caste consciousness."),
    ("Poona Pact 1932 Context", "The historic Poona Pact signed between Mahatma Gandhi and Dr. B.R. Ambedkar in September 1932 resulted in:",
     "Ambedkar giving up separate electorates for Depressed Classes in exchange for increased reserved seats in joint electorates",
     ["The complete abolition of all elections across British India", "The immediate creation of an independent sovereign Dalit republic", "The deportation of all colonial British civil servants from India"],
     "Gandhi's fast unto death led to the Poona Pact, replacing separate electorates with reserved seats within general joint electorates."),
    ("Bonded Labour System (Abolition) Act 1976", "The Bonded Labour System (Abolition) Act, 1976 was enacted to:",
     "Abolish the debt bondage system where generations of Dalit and Adivasi families were forced to work for landlords to repay small loans",
     ["Require all agricultural labourers to sign twenty-year permanent indentured contracts", "Legalize usurious moneylending interest rates up to 1000 percent", "Ban all wage labour across all Indian industries"],
     "The 1976 Act extinguished all bonded debt obligations and liberated generations trapped in hereditary debt servitude."),
    ("Caste-Based Spatial Humiliation", "Historical customs of untouchability enforced spatial deference, requiring Dalits in public roads to:",
     "Remove footwear, hold headcloths in hands, step off paved pathways into ditches, and avoid letting their shadows touch upper castes",
     ["Ride in luxury horse-drawn carriages ahead of village landlords", "Wear expensive gold crowns and carry royal ceremonial swords", "Speak loudly into public megaphones in village squares"],
     "Spatial rituals enforced daily degradation: Dalits were forced to walk barefoot, remove turbans, and maintain physical distance."),
    ("Atrocities Reporting Dilemma", "Sociologists note that official police statistics of caste atrocities often show an increase because:",
     "Increased reporting reflects rising Dalit political consciousness and willingness to register complaints, rather than solely a rise in incidents",
     ["Police officers receive cash bounties for fabricating fake cases against landlords", "The Indian Penal Code was abolished and replaced by corporate rules", "All caste conflicts have completely ceased in real life"],
     "Rising atrocity numbers often indicate greater assertion and formal reporting by Dalits, defying traditional enforced silence."),
    ("Role of Dalit Literature in Emancipation", "Dalit autobiographies (e.g. Omprakash Valmiki's *Joothan*, Bama's *Karukku*) transformed Indian literary sociology by:",
     "Documenting the raw lived reality of untouchability, hunger, institutional humiliation, and revolutionary resistance in first-person narrative",
     ["Writing classical romantic poetry praising royal palaces and monarchies", "Writing fictional space exploration stories about distant planets", "Translating foreign corporate accounting manuals into verse"],
     "Dalit literature exposed the systemic violence of caste and school humiliation (*Joothan*), creating a radical aesthetic of truth and resistance."),
    ("Economic Boycott as Dominant Caste Weapon", "When Dalits in rural villages resist traditional subjugation or demand equal wages, dominant castes often retaliate with an 'Economic Boycott':",
     "Refusing to hire Dalits for farm work, cutting off access to fields for grazing, and banning them from buying provisions in village shops",
     ["Paying Dalits double their normal daily agricultural wages in cash", "Donating fertile agricultural land to all Dalit households in the village", "Voluntarily handing over their private tractors to Dalit youth"],
     "Economic boycotts exploit Dalit landlessness: denying casual wage work and access to fields to coerce communities into submission.")
]
for itm in s22_extras:
    top, stem, corr, wrongs, sol = itm
    s22_raw.append(("mcq", top, stem, corr, wrongs, sol))
SLOT22 = build_slot(CH_INEQ, s22_raw)

# Slot 23: Anti-Caste Thinkers - Phule, Periyar, Ambedkar (20 Qs)
s23_raw = [
    ("mcq", "Jyotirao Phule's Satyashodhak Samaj", "In 1873, social revolutionary Jyotirao Phule founded the 'Satyashodhak Samaj' in Maharashtra with the primary goal of:",
     "Liberating Shudras and Ati-Shudras from the religious hegemony, socio-economic exploitation, and intellectual slavery of Brahminical priesthood",
     ["Promoting the revival of Vedic animal sacrifices and classical ritual chants", "Establishing a private commercial bank for European textile merchants", "Supporting the British colonial military conquest of Afghanistan"],
     "Phule's Satyashodhak Samaj (Truth Seekers' Society) championed education and liberation of lower castes and women from Brahminical hegemony."),
    ("stmt", "Phule's Gulamgiri (Slavery)",
     "In his seminal 1873 book *Gulamgiri* (Slavery), Jyotirao Phule dedicated his work to the American abolitionist movement that ended Black slavery.",
     "Phule argued that the condition of lower castes in India was entirely equal and identical to that of European feudal kings.", 3,
     "Statement I is correct as Phule linked the Dalit struggle to the American anti-slavery movement; Statement II is incorrect."),
    ("ar", "Savitribai Phule and Female Education",
     "Savitribai Phule and Jyotirao Phule opened the first school for girls and marginalized lower castes at Bhide Wada in Pune in 1848.",
     "Orthodox conservative elites welcomed their educational efforts and awarded Savitribai civic honors and public funding.", 3,
     "(A) is true as the Phules pioneered female and lower-caste schooling in 1848. (R) is false as orthodox elites threw stones and mud at Savitribai."),
    ("match", "Anti-Caste Thinkers and Masterpieces",
     "Match the anti-caste revolutionary thinkers in List I with their landmark writings/organizations in List II:",
     [("A", "Jyotirao Phule"), ("B", "E.V. Ramasamy Periyar"), ("C", "Dr. B.R. Ambedkar"), ("D", "Sri Narayana Guru")],
     [("I", "*Annihilation of Caste* and *The Buddha and His Dhamma*"),
      ("II", "*Gulamgiri* and Satyashodhak Samaj"),
      ("III", "Self-Respect Movement and *Kudi Arasu*"),
      ("IV", "SNDP Yogam and 'One Caste, One Religion, One God for Man'")],
     "A-II, B-III, C-I, D-IV",
     "Phule: Gulamgiri; Periyar: Self-Respect Movement; Ambedkar: Annihilation of Caste; Narayana Guru: SNDP Yogam."),
    ("seq", "Chronology of Radical Anti-Caste Movements",
     "Arrange the historic anti-caste milestones in chronological order:",
     [("A", "Foundation of Satyashodhak Samaj by Jyotirao Phule in Pune"),
      ("B", "Aravippuram consecration of Shiva temple by Sri Narayana Guru"),
      ("C", "Launch of the radical Self-Respect Movement by E.V. Ramasamy Periyar in Tamil Nadu"),
      ("D", "Mahad Satyagraha and burning of *Manusmriti* by Dr. B.R. Ambedkar")],
     "A, B, C, D",
     "Milestones progressed from Phule's Samaj (1873) to Narayana Guru (1888), Periyar's Self-Respect (1925), and Ambedkar's Mahad (1927).")
]

s23_extras = [
    ("Periyar's Self-Respect Movement Focus", "E.V. Ramasamy Periyar launched the 'Self-Respect Movement' (Suya Mariyadai Iyakkam) in Tamil Nadu in 1925 to:",
     "Reject Brahminical supremacy, eradicate superstitious rituals, promote rationalism, and advocate radical gender equality and non-Brahmin self-respect",
     ["Restore ancient monarchies and declare classical Sanskrit the sole official language", "Enforce strict vegetarianism across all southern Indian communities", "Hand over all agricultural farming to foreign colonial plantation companies"],
     "Periyar championed rationalism, atheist critique of religion, non-Brahmin pride, and radical women's liberation."),
    ("Self-Respect Marriages (Suyamariyathai)", "What was unique about the 'Self-Respect Marriages' pioneered by Periyar in Tamil Nadu?",
     "They were solemnized without Brahmin priests, without Vedic sacred fire rituals, and without dowry, based on mutual equality between partners",
     ["They required the bride and groom to pay a large fee in pure gold to the colonial government", "They were conducted in complete darkness inside underground caves", "They required the bride to surrender all property to her father-in-law"],
     "Self-Respect marriages discarded priestly rituals and sacred fire, legalizing egalitarian civil unions registered without priests."),
    ("Sri Narayana Guru's Universal Motto", "What was the universal egalitarian motto proclaimed by Sri Narayana Guru in Kerala?",
     "'Oru Jati, Oru Matham, Oru Daivam Manushyanu' (One Caste, One Religion, One God for Man)",
     ["'Divide and Rule'", "'Preserve Caste Purity at All Costs'", "'War is the Natural State of Humanity'"],
     "Narayana Guru preached human unity, rejecting caste hierarchy with his historic motto of one caste, one religion, one God."),
    ("Aravippuram Installation 1888", "In 1888, Sri Narayana Guru defied orthodox Brahminical religious monopolies by:",
     "Installing a consecrated Shiva idol from the Neyyar river at Aravippuram as an Ezhava (lower caste), declaring devotion open to all without caste",
     ["Banning all religious worship across the state of Travancore", "Declaring himself an emperor of a foreign European empire", "Refusing to allow any lower-caste persons to enter his ashram"],
     "Narayana Guru challenged priestly monopolies by consecrating the Aravippuram Shiva lingam, affirming that God belongs to all."),
    ("Ambedkar's *Annihilation of Caste* Thesis", "In his undelivered 1936 speech *The Annihilation of Caste*, Dr. B.R. Ambedkar argued that caste cannot be destroyed without:",
     "Destroying the religious sanctity of the Shastras and scriptures that provide theological legitimacy to the caste system",
     ["Encouraging all citizens to participate in weekly community sports competitions", "Wearing Western European corporate business suits in rural villages", "Building more concrete railway bridges across major rivers"],
     "Ambedkar insisted that caste is a religious notion rooted in the Shastras: real annihilation requires rejecting scriptural authority."),
    ("Division of Labour vs Division of Labourers", "In *Annihilation of Caste*, how did Dr. Ambedkar refute the conservative defense that caste is merely a 'division of labour'?",
     "He showed that caste is not merely a division of labour, but a hierarchical 'division of labourers' into water-tight, involuntary compartments",
     ["He claimed that human beings should never perform any economic work", "He proved that all human beings possess identical physical strength", "He argued that division of labour was invented by computer software"],
     "Ambedkar proved caste is an unnatural division of labourers, grading workers into an involuntary hierarchy without choice."),
    ("Iyothee Thass and Tamil Buddhist Revival", "In the late 19th century, Pandit Iyothee Thass mobilized oppressed Dalits in Tamil Nadu by arguing that:",
     "Untouchables were the original Buddhists of India who were pushed into marginality by Brahminical hegemony, founding the Sakya Buddhist Society",
     ["All Dalits were descendants of ancient Roman emperors", "Dalits should abandon agriculture and become international maritime pirates", "Dalits should adopt orthodox Vedic animal sacrifices"],
     "Iyothee Thass pioneered anti-caste Buddhist revival in South India, arguing Dalits were original indigenous Buddhists."),
    ("Tarabai Shinde's *Stri Purush Tulana*", "In her revolutionary 1882 publication *Stri Purush Tulana* (A Comparison Between Men and Women), Tarabai Shinde:",
     "Mounted a radical feminist critique of patriarchal double standards, male hypocrisy, and the systemic subjugation of women in upper-caste society",
     ["Praised the practice of widow burning as the supreme religious duty of women", "Argued that women should be legally barred from reading and writing", "Claimed that men were biologically incapable of feeling pain"],
     "Tarabai Shinde wrote the first modern feminist critique in India, attacking male double standards on widowhood and morality."),
    ("Pandita Ramabai and Sharada Sadan", "Pandita Ramabai, a pioneering feminist and social reformer, established 'Sharada Sadan' in Bombay in 1889 to:",
     "Provide shelter, education, and vocational training to destitute upper-caste child widows to make them self-reliant",
     ["Train upper-caste women to become soldiers in British colonial cavalry regiments", "Force all widows to perform lifelong penance in isolated mountain caves", "Construct luxury commercial shopping malls for foreign merchants"],
     "Sharada Sadan gave widows education and independence, defying orthodox traditions of widow degradation."),
    ("Ambedkar on Democracy as a Way of Life", "Dr. B.R. Ambedkar defined 'Democracy' not merely as a formal political system of voting, but as:",
     "A mode of associated living, of conjoint communicated experience, rooted in liberty, equality, and fraternity",
     ["A commercial auction where political offices are sold to the highest bidder", "A military dictatorship where the commander-in-chief makes all decisions", "A system where only wealthy landowners are allowed to speak"],
     "Ambedkar envisioned democracy as social democracy: an ethical way of life grounded in equality and fraternity."),
    ("Periyar's Critique of Religious Epics", "Why did Periyar critically dissect and rewrite popular Hindu epics (like the Ramayana)?",
     "To expose how mythological narratives glorified Aryan/Brahminical domination while depicting Dravidians and lower castes as demons (Asuras)",
     ["Because he wanted to replace them with English nursery rhymes", "Because he was hired by foreign television networks to produce cartoons", "Because he believed the epics were written in modern computer programming code"],
     "Periyar analyzed epics as ideological tools of Aryan hegemony, subverting them to awaken Dravidian self-respect."),
    ("Ayyankali's Struggle for Dalit Education", "In early 20th century Kerala, Dalit leader Ayyankali led heroic struggles such as the 'Villuvandi' (bullock cart) protest and school strikes to:",
     "Assert the right of Pulaya Dalit children to walk on public roads and enroll in government primary schools",
     ["Demand that all public schools in Travancore be permanently shut down", "Ban all non-Dalits from learning how to read and write", "Construct private airports in agricultural villages"],
     "Ayyankali led agricultural strikes and rode decorated bullock carts on forbidden public roads, winning school admission for Dalit children."),
    ("Phule's Alternative Myth of King Bali", "In his cultural contestation of Brahminical mythology, Jyotirao Phule inverted the Vamana myth by celebrating:",
     "King Bali (Mahabali) as the benevolent, just, and egalitarian indigenous peasant king deceived by the cunning Vamana",
     ["Alexander the Great as the founding father of Indian agriculture", "Julius Caesar as the patron deity of Maharashtrian weavers", "The British East India Company as ancient Vedic gods"],
     "Phule reclaimed the popular peasant memory of King Bali, symbolizing an egalitarian Golden Age destroyed by Brahminical conquest."),
    ("Ambedkar on Social Democracy", "In his concluding address to the Constituent Assembly on November 25, 1949, Dr. Ambedkar famously warned:",
     "Political democracy cannot last unless there lies at the base of it social democracy—a way of life which recognizes liberty, equality, and fraternity",
     ["That India should abandon its Constitution within six months and appoint a monarch", "That all political parties should be banned and replaced by military courts", "That voting rights should be restricted exclusively to university professors"],
     "Ambedkar warned that political democracy with one-man-one-vote would remain a contradiction without social and economic equality."),
    ("Ambedkar's Three-Word Slogan", "What iconic three-word clarion call did Dr. B.R. Ambedkar give to the oppressed classes for their emancipation?",
     "'Educate, Agitate, Organise'", ["'Pray, Obey, Endure'", "'Submit, Tolerate, Forgive'", "'Borrow, Spend, Consume'"],
     "Ambedkar's famous rallying call 'Educate, Agitate, Organise' mobilized the Dalit movement for self-respect and political power.")
]
for itm in s23_extras:
    top, stem, corr, wrongs, sol = itm
    s23_raw.append(("mcq", top, stem, corr, wrongs, sol))
SLOT23 = build_slot(CH_INEQ, s23_raw)

# Slot 24: Other Backward Classes (OBCs) & Commissions (20 Qs)
s24_raw = [
    ("mcq", "Mandal Commission Reservation Recommendation", "The Second Backward Classes Commission (Mandal Commission) recommended what percentage of reservations for OBCs in central government employment and education?",
     "27 percent reservation", ["50 percent reservation", "15 percent reservation", "7.5 percent reservation"],
     "The Mandal Commission recommended 27% reservation for Other Backward Classes, keeping total quotas under the 50% legal cap."),
    ("stmt", "Kaka Kalelkar Commission 1953",
     "The First Backward Classes Commission was appointed in 1953 under the chairmanship of Kaka Kalelkar.",
     "The Chairman, Kaka Kalelkar, enthusiastically endorsed the commission's final report without any reservations or dissenting letters.", 3,
     "Statement I is correct; Statement II is incorrect as Kalelkar appended an ambiguous dissenting letter repudiating caste criteria."),
    ("ar", "Implementation of Mandal Recommendations in 1990",
     "Prime Minister V.P. Singh announced the implementation of the Mandal Commission's 27% quota for OBCs in central services in August 1990.",
     "The announcement triggered widespread political debates and violent anti-reservation student agitations across northern Indian cities.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The 1990 implementation provoked deep upper-caste anxiety and urban agitations."),
    ("match", "Backward Classes Commissions and Landmarks",
     "Match the Backward Classes commissions and judgments in List I with their defining milestones in List II:",
     [("A", "Kaka Kalelkar Commission"), ("B", "B.P. Mandal Commission"), ("C", "Indra Sawhney Judgment"), ("D", "93rd Constitutional Amendment")],
     [("I", "Second Backward Classes Commission appointed in 1979 under Janata Party government"),
      ("II", "First Backward Classes Commission appointed in 1953 under Article 340"),
      ("III", "Extended 27% OBC reservation to central higher educational institutions (IITs, IIMs, Central Universities)"),
      ("IV", "Landmark 1992 Supreme Court ruling upholding 27% OBC quota while introducing the 'Creamy Layer' exclusion")],
     "A-II, B-I, C-IV, D-III",
     "Kalelkar was 1st Commission (1953); Mandal was 2nd (1979); Indra Sawhney established creamy layer (1992); 93rd Amendment extended to higher education (2006)."),
    ("seq", "Chronology of OBC Reservation Politics",
     "Arrange the historical milestones in the mobilization and implementation of OBC reservations in chronological order:",
     [("A", "Appointment of the First Backward Classes Commission under Kaka Kalelkar"),
      ("B", "Submission of the Second Backward Classes Commission Report by B.P. Mandal"),
      ("C", "Executive announcement of 27% central job reservation for OBCs by V.P. Singh"),
      ("D", "Supreme Court *Indra Sawhney* judgment upholding OBC quota with Creamy Layer rule")],
     "A, B, C, D",
     "Chronology: Kalelkar (1953), Mandal Report (1980), Implementation (1990), and Indra Sawhney ruling (1992).")
]

s24_extras = [
    ("Article 340 Constitutional Mandate", "Under which constitutional provision did the President of India appoint the Backward Classes Commissions?",
     "Article 340 of the Indian Constitution", ["Article 370", "Article 356", "Article 324"],
     "Article 340 empowers the President to appoint a Commission to investigate conditions of socially and educationally backward classes."),
    ("Indicators of Backwardness (Mandal)", "The Mandal Commission developed 11 indicators to identify OBCs, grouped under which three broad categories?",
     "Social, Educational, and Economic indicators (with social indicators carrying the highest relative weightage)",
     ["Physical height, eye color, and running speed", "Astrological birth charts and temple attendance", "Ownership of private jet aircraft and foreign bank accounts"],
     "Mandal evaluated backwardness using 11 indicators weighted across Social (12 points), Educational (6 points), and Economic (3 points)."),
    ("Estimated OBC Population Share (Mandal)", "Based on the 1931 Census data and extrapolation, the Mandal Commission estimated the OBC population of India at approximately:",
     "52 percent of the total population", ["10 percent of the total population", "27 percent of the total population", "85 percent of the total population"],
     "Mandal estimated OBCs constituted 52% of India's population, but recommended 27% to abide by the Supreme Court's 50% ceiling rule."),
    ("Indra Sawhney Creamy Layer Principle", "In the landmark *Indra Sawhney v. Union of India* (1992) ruling, the Supreme Court introduced the 'Creamy Layer' concept to:",
     "Exclude affluent, socially advanced individuals within the OBC category from enjoying reservation benefits so benefits reach the truly needy",
     ["Force all OBC families to sell dairy products to government cooperatives", "Ban all backward class students from attending school", "Provide free dairy cows to all government civil servants"],
     "The Creamy Layer excludes socially and economically advanced OBCs, directing reservations to underprivileged members."),
    ("50 Percent Reservation Ceiling Rule", "The Supreme Court in the *Indra Sawhney* judgment laid down which crucial constitutional boundary regarding affirmative action quotas?",
     "Total reservations under Article 16(4) should ordinarily not exceed 50 percent of the total available vacancies",
     ["Reservations must be 100 percent in all public and private institutions", "Reservations can only be granted to foreign citizens residing in India", "Reservations can never exceed 5 percent under any circumstances"],
     "The Supreme Court established that total quotas must ordinarily remain below 50% to maintain balance with open merit."),
    ("93rd Constitutional Amendment 2005", "The 93rd Constitutional Amendment Act (Article 15(5)) enacted in 2005 empowered the state to make special provisions for OBCs in:",
     "Admission to higher educational institutions (including aided and private unaided educational institutions)",
     ["Appointments to supreme military command councils exclusively", "Purchasing private residential real estate in foreign countries", "Exemption from paying all municipal electricity bills"],
     "Article 15(5) enabled 27% reservations for OBCs in central universities, IITs, IIMs, and medical colleges."),
    ("Central Educational Institutions Act 2006", "The implementation of 27% OBC quotas in central universities (IITs, IIMs, AIIMS) was achieved without reducing general seats by:",
     "Expanding total student enrollment and physical capacity by 54 percent across all central institutions",
     ["Expelling 50 percent of existing upper-caste students", "Banning general category students from taking entrance examinations", "Shutting down all central universities for five years"],
     "The government expanded total institutional seats by 54% so that general category seats were not reduced in absolute terms."),
    ("Social vs Pure Economic Backwardness", "The Constitution of India specifically authorizes affirmative action for 'socially and educationally' backward classes, rather than purely economic criteria, because:",
     "Caste-based social backwardness entails structural institutional stigma and exclusion that cannot be equated merely with temporary income poverty",
     ["Economic poverty does not exist anywhere in the Indian economy", "All Indian citizens possess identical financial bank account balances", "The Constitution was written by foreign commercial bankers"],
     "The Constitution recognizes social backwardness rooted in structural caste disabilities, distinct from transient monetary poverty."),
    ("Regional Precedents: South Indian Quotas", "Long before the Mandal Commission, southern states (Tamil Nadu, Karnataka, Kerala, Andhra) had successfully implemented:",
     "Extensive state-level reservations for Backward Classes dating back to the pre-independence Justice Party and princely Mysore reforms",
     ["Zero reservations of any kind, banning all affirmative action", "Mandatory emigration of all lower-caste citizens to overseas territories", "A complete shutdown of all state colleges and schools"],
     "South India pioneered backward class reservations decades before northern India, integrating non-Brahmins peacefully into bureaucracy."),
    ("National Commission for Backward Classes (NCBC)", "The 102nd Constitutional Amendment Act, 2018 conferred constitutional status on which statutory body under Article 338B?",
     "The National Commission for Backward Classes (NCBC)", ["The Central Board of Direct Taxes", "The Union Public Service Commission", "The Election Commission of India"],
     "The 102nd Amendment gave the NCBC full constitutional status under Article 338B, equivalent to the SC and ST Commissions."),
    ("Sub-Categorization of OBCs: Rohini Commission", "Why did the Government of India appoint the Justice G. Rohini Commission in 2017?",
     "To examine the equitable sub-categorization of OBCs, as a small minority of dominant OBC castes monopolized the bulk of reservation benefits",
     ["To completely dissolve the OBC category and cancel all affirmative action", "To ban all OBC citizens from voting in national democratic elections", "To convert all university campuses into military airfields"],
     "The Rohini Commission was tasked with sub-categorizing OBCs to distribute quotas equitably among extremely backward non-dominant groups."),
    ("Mandalisation of Indian Politics", "In political sociology, the term 'Mandalisation' refers to the historic democratic shift where:",
     "Intermediate peasant castes and OBCs mobilized politically to assert democratic representation, ending upper-caste dominance in state assemblies",
     ["All political parties dissolved and handed power to military generals", "Elections were abolished and replaced by hereditary dynastic kings", "All citizens were mandated to join a single international trade guild"],
     "Mandalisation democratized political power, empowering backward caste leaders and regional parties across northern and eastern India."),
    ("Caste Census Demand Persistence", "In contemporary Indian social policy, the recurring demand for a comprehensive nationwide Caste Census is justified on the grounds that:",
     "Accurate, updated empirical data on caste demographics and socio-economic status is essential for evidence-based policy, fair quotas, and resource allocation",
     ["It will automatically double the speed of all national passenger trains", "It will eliminate the need for having any government ministries or courts", "It is required by international space exploration agencies"],
     "Advocates argue that targeted welfare, equitable sub-categorization, and policy design require objective, updated caste demographic data."),
    ("P.S. Krishnan's Bureaucratic Role", "IAS officer P.S. Krishnan is remembered in Indian administrative sociology as:",
     "The committed civil servant who drafted the historic 1990 Mandal reservation notification and dedicated his career to social justice legislation",
     ["The colonial judge who banned the practice of agriculture in northern India", "A commercial real estate broker who sold forest land to private firms", "A military general who commanded naval fleets in the Arabian Sea"],
     "P.S. Krishnan was the bureaucratic architect of Mandal implementation, SC/ST Atrocities Act, and progressive social justice policies."),
    ("OBC Identity: Horizontal Coalition", "Unlike traditional endogamous Jatis, the category 'OBC' (Other Backward Classes) functions sociologically as:",
     "A modern horizontal political and administrative coalition uniting diverse agrarian, artisan, and service castes for democratic entitlement",
     ["An ancient scriptural Varna category described in Vedic texts", "A hereditary royal dynasty that ruled South Asia centuries ago", "A private corporate monopoly traded on international stock exchanges"],
     "OBC is an administrative and political category, amalgamating hundreds of diverse intermediate castes into a collective democratic interest group.")
]
for itm in s24_extras:
    top, stem, corr, wrongs, sol = itm
    s24_raw.append(("mcq", top, stem, corr, wrongs, sol))
SLOT24 = build_slot(CH_INEQ, s24_raw)

# Slot 25: Disability Rights - Medical vs Social Model & RPWD Act 2016 (20 Qs)
s25_raw = [
    ("mcq", "Medical Model vs Social Model of Disability", "In modern sociology of disability, how does the 'Social Model' differ fundamentally from the traditional 'Medical Model'?",
     "The medical model views disability as an individual biological deficit needing cure, whereas the social model views disability as created by an inaccessible, exclusionary society",
     ["The medical model blames society, while the social model blames biological chromosomes exclusively",
      "The social model views disability as an ancient spiritual blessing that gives magical powers",
      "There is zero conceptual difference between the medical and social models"],
     "The social model establishes that disability is socially constructed by physical barriers, prejudice, and institutional exclusion."),
    ("stmt", "RPWD Act 2016 Landmark Provisions",
     "The Rights of Persons with Disabilities (RPWD) Act, 2016 expanded the number of recognized disabilities from 7 to 21 types.",
     "The RPWD Act 2016 increased reservations for persons with benchmark disabilities in government employment from 3 percent to 4 percent.", 1,
     "Both statements are correct: The 2016 Act aligned Indian law with UNCRPD, expanding disability categories to 21 and raising quotas to 4%."),
    ("ar", "Built Environment as Source of Disability",
     "A person using a wheelchair is not disabled by their physical inability to walk, but by the architectural absence of ramps and elevators in public buildings.",
     "The social model of disability distinguishes between biological 'impairment' (physical variation) and societal 'disability' (institutional barriers).", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The social model locates disability in inaccessible social architecture rather than the body."),
    ("match", "Disability Concepts and Models",
     "Match the disability frameworks in List I with their defining perspectives in List II:",
     [("A", "Charity Model"), ("B", "Medical Model"), ("C", "Social Model"), ("D", "Human Rights Model")],
     [("I", "Disability as an individual bodily pathology to be medically treated, rehabilitated, or cured"),
      ("II", "Disabled persons viewed as objects of pity and benevolence needing passive custodial care"),
      ("III", "Disability viewed as an interaction between impairments and exclusionary societal barriers"),
      ("IV", "Persons with disabilities recognized as equal legal rights-holders entitled to non-discrimination")],
     "A-II, B-I, C-III, D-IV",
     "Charity: pity; Medical: individual deficit; Social: exclusionary barriers; Rights: equal legal entitlement under UNCRPD."),
    ("seq", "Evolution of Disability Rights Legislation in India",
     "Arrange the legislative and international milestones in disability rights in chronological sequence:",
     [("A", "Enactment of the Persons with Disabilities (Equal Opportunities, Protection of Rights) Act"),
      ("B", "Adoption of the UN Convention on the Rights of Persons with Disabilities (UNCRPD)"),
      ("C", "India's ratification of the UNCRPD treaty"),
      ("D", "Enactment of the comprehensive Rights of Persons with Disabilities (RPWD) Act")],
     "A, B, C, D",
     "Chronology: PWD Act (1995), UNCRPD adoption (2006), India ratification (2007), and RPWD Act (2016).")
]

s25_extras = [
    ("UNCRPD Principles", "The United Nations Convention on the Rights of Persons with Disabilities (UNCRPD) 2006 establishes which core paradigm shift?",
     "A shift from viewing disabled persons as objects of charity and medical protection to recognizing them as autonomous subjects with full human rights",
     ["A mandate requiring all disabled individuals to reside permanently in institutional hospitals", "A policy banning disabled persons from attending mainstream schools", "The abolition of all wheelchair ramps in public buildings worldwide"],
     "UNCRPD completed the paradigm shift from paternalistic charity to an inalienable human rights framework."),
    ("Benchmark Disability Definition (RPWD 2016)", "Under the RPWD Act 2016, a person is defined as having a 'Benchmark Disability' if they possess:",
     "Not less than 40 percent of a specified disability, certified by an authorized medical board",
     ["Exactly 100 percent total paralysis in all four limbs", "A temporary headache or seasonal viral cold", "Zero percent impairment with normal physical stamina"],
     "Benchmark disability requires at least 40% certified disability, unlocking legal reservations and entitlements."),
    ("Universal Design Principle", "In inclusive architecture and sociology, 'Universal Design' refers to:",
     "Designing environments, products, and services to be usable by all people to the greatest extent possible, without the need for specialized adaptation",
     ["Designing buildings exclusively for elite athletes with high running speed", "Constructing public doors that can only be opened by military tanks", "Building stairs five meters high without any handrails or ramps"],
     "Universal design creates inherently accessible environments (curb cuts, wide doors, tactile pavements) benefiting all citizens."),
    ("Reasonable Accommodation Mandate", "Under the RPWD Act 2016, the legal concept of 'Reasonable Accommodation' requires employers and schools to:",
     "Make necessary and appropriate modifications and adjustments to enable a disabled person to exercise their rights and work on an equal basis",
     ["Fire all disabled employees whenever they request assistance", "Refuse to alter any work schedule or workplace physical layout under any circumstance", "Require disabled workers to pay double the income tax of non-disabled employees"],
     "Reasonable accommodation obligates institutions to adapt work/study environments unless it causes disproportionate burden."),
    ("Invisible Disabilities Inclusion", "Which of the following conditions was recognized as a specified disability under the expanded RPWD Act 2016?",
     "Specific Learning Disabilities (Dyslexia, Dyscalculia), Autism Spectrum Disorder, and Mental Illness",
     ["Ordinary laziness and procrastination in completing homework", "Temporary physical fatigue after playing sports", "Preference for drinking tea rather than coffee"],
     "RPWD 2016 recognized invisible neurological, developmental, and mental health conditions alongside physical disabilities."),
    ("Acid Attack Victims in RPWD Act", "The RPWD Act 2016 included 'Acid Attack Victims' under specified disabilities primarily to:",
     "Provide legal recognition, access to specialized medical treatment, rehabilitation, and reservations in public employment and education",
     ["Ban acid attack survivors from speaking in public spaces", "Classify acid attack survivors as criminal offenders", "Exclude acid attack survivors from receiving any government welfare"],
     "Recognizing acid attack survivors ensures access to corrective surgeries, disability certificates, and quota entitlements."),
    ("Accessible India Campaign (Sugamya Bharat)", "The 'Accessible India Campaign' (Sugamya Bharat Abhiyan) launched in 2015 aims to achieve universal accessibility across which three pillars?",
     "Built environment (public buildings), Transportation system (railways/airports/buses), and Information & Communication ecosystem (websites/sign language)",
     ["Military weapons, fighter jets, and naval submarines", "Heavy industrial steel blast furnaces and oil refineries", "Private luxury golf courses and casino resorts"],
     "Sugamya Bharat targets barrier-free access across public buildings, transport hubs, and government websites."),
    ("Inclusive Education Mandate", "Section 16 of the RPWD Act 2016 mandates that all government and recognized educational institutions must provide:",
     "Inclusive education, admitting children with disabilities without discrimination and providing education together with non-disabled peers",
     ["Segregated isolation, forcing disabled children to attend schools exclusively on remote islands", "A complete ban on disabled children enrolling in any school", "Expulsion of disabled students if they cannot run a marathon"],
     "The law mandates inclusive schooling: teaching disabled children alongside peers with adaptive aids and trained educators."),
    ("Intersectionality: Disabled Women", "Sociological studies of women with disabilities in India reveal that they experience:",
     "'Triple Marginality'—discrimination based on gender, disability, and poverty, facing high rates of domestic violence, abandonment, and denial of reproductive rights",
     ["Complete social privilege and automatic appointment to corporate executive boards", "Zero vulnerability to any form of discrimination or violence", "Exemption from all domestic chores and family obligations"],
     "Disabled women face compounded marginality: infantilized by society, denied reproductive autonomy, and vulnerable to abuse."),
    ("Linguistic Exclusion: Sign Language", "Why has the disability rights movement demanded the official recognition of Indian Sign Language (ISL)?",
     "To recognize ISL as a legitimate, rich linguistic system, guaranteeing Deaf citizens access to interpreters in courts, news media, and classrooms",
     ["To ban all spoken languages across the Indian subcontinent", "To force all television news broadcasters to speak in total silence", "To prevent Deaf individuals from attending universities"],
     "Recognizing ISL affirms Deaf linguistic identity, enabling access to legal justice, higher education, and information."),
    ("Karma Theory Critique in Disability", "In Indian cultural sociology, the conservative religious belief that disability is caused by 'sins committed in a past life' is critiqued because:",
     "It stigmatizes disabled individuals, blames the victim for their condition, and absolves society and the state from building accessible infrastructure",
     ["It proves that medical doctors are unnecessary in hospitals", "It provides disabled persons with multi-million dollar cash bonuses from temples", "It is an empirical scientific law verified by modern cellular biology"],
     "Karma-based fatalism rationalizes discrimination, shifting the blame onto disabled individuals and excusing societal neglect."),
    ("Legal Capacity and Guardianship", "Under Section 13 of the RPWD Act 2016, persons with disabilities enjoy:",
     "Equal legal capacity, the right to own and inherit property, control financial affairs, and access 'supported decision-making' rather than plenary plenary guardianship",
     ["Zero legal rights, being treated as legal non-persons without the right to own property", "Mandatory transfer of all bank accounts to state police authorities", "A total ban on entering into any legal marriage contracts"],
     "The Act shifted law from paternalistic guardianship to 'supported decision-making', recognizing legal autonomy and property rights."),
    ("Employment Quota Enforcement Gaps", "Despite statutory 4% reservations in public employment, sociologists note that disabled citizens remain heavily underrepresented because:",
     "Hostile interview attitudes, inaccessible examination centers, procedural delays in issuing disability certificates, and non-implementation in private sectors",
     ["Disabled citizens refuse to accept high-paying government employment", "All disabled individuals are already billionaires who do not need jobs", "The Supreme Court abolished all disability reservations in India"],
     "Structural barriers (inaccessible tests, bureaucratic certificate harassment, employer prejudice) keep formal employment low."),
    ("Caregiver Burden and Kinship Reliance", "In the absence of comprehensive state-funded community support services in India, the primary burden of lifelong disability care falls on:",
     "The immediate family, particularly female relatives (mothers, sisters, wives), who perform unpaid, exhausting care work with minimal state respite",
     ["International volunteer tourists visiting on holiday visas", "Automated computer robots manufactured by multinational tech companies", "Private insurance corporations that pay all household living expenses"],
     "India's welfare gap forces families into primary caregiving, where women shoulder unpaid emotional and physical burdens without respite."),
    ("Ableism as Ideology", "In disability studies, the concept of 'Ableism' refers to:",
     "A systemic ideology and prejudice that devalues persons with disabilities, defining non-disabled bodies and minds as the only natural, superior norm",
     ["The scientific ability to run a marathon in under two hours", "A government grant awarded to athletic sports federations", "The study of planetary orbits in astronomy"],
     "Ableism is the structural discrimination that constructs society exclusively for able-bodied norms, treating disabled lives as deficit.")
]
for itm in s25_extras:
    top, stem, corr, wrongs, sol = itm
    s25_raw.append(("mcq", top, stem, corr, wrongs, sol))
SLOT25 = build_slot(CH_INEQ, s25_raw)

SLOTS_21_25 = {
    21: SLOT21,
    22: SLOT22,
    23: SLOT23,
    24: SLOT24,
    25: SLOT25
}

print("Slots 21 to 25 compiled successfully.")
