import sys, os
sys.path.insert(0, os.getcwd())
from scripts.subject_generators.slot_helpers import mcq, stmt, ar, match, seq

def build_slot(ch, items):
    res = []
    for itm in items:
        qtype = itm[0]
        if qtype == "mcq":
            _, top, stem, corr, wrongs, expl = itm
            res.append(mcq(ch, top, stem, corr, wrongs, expl))
        elif qtype == "stmt":
            _, top, s1, s2, rel, expl = itm
            res.append(stmt(ch, top, s1, s2, rel, expl))
        elif qtype == "ar":
            _, top, a, r, rel, expl = itm
            res.append(ar(ch, top, a, r, rel, expl))
        elif qtype == "match":
            _, top, stem, l1, l2, pair, expl = itm
            res.append(match(ch, top, stem, l1, l2, pair, expl))
        elif qtype == "seq":
            _, top, stem, items_list, order_str, expl = itm
            res.append(seq(ch, top, stem, items_list, order_str, expl))
    assert len(res) == 20, f"Slot has {len(res)} items instead of 20"
    return res

CH_STRUC = "Structural Change"
CH_CULT = "Cultural Change"
CH_DEMO = "The Story of Indian Democracy"
CH_RURAL = "Change and Development in Rural Society"

# Slot 31: Structural Change: Colonialism, Industrialisation & Urbanisation
s31_raw = [
    ("mcq", "De-industrialisation", "Which economic phenomenon during British colonial rule refers to the decline of traditional Indian handicrafts and textiles due to factory-produced imports?",
     "De-industrialisation",
     ["Industrial take-off", "Import substitution industrialisation", "Green Revolution"],
     "De-industrialisation destroyed traditional artisanal production due to cheap Manchester cotton imports."),
    ("stmt", "Colonial Urban Patterns",
     "Colonial economic policies caused traditional royal court cities like Murshidabad, Surat, and Thanjavur to decline.",
     "Colonial trade prioritized the development of coastal presidency port cities such as Calcutta, Bombay, and Madras to facilitate raw material exports.", 1,
     "Both Statement I and Statement II are correct. Coastal trade hubs replaced pre-colonial artisanal capitals."),
    ("ar", "Plantation Labour Act",
     "The colonial state enacted the Transport of Native Labourers Act of 1863 to protect the rights of tea garden workers in Assam.",
     "British planters required cheap, captive indentured labour and penal laws to prevent workers from fleeing miserable working conditions.", 4,
     "Assertion (A) is false as the Act served British tea planters' interests by criminalizing flight; Reason (R) is true regarding harsh plantation exploitation."),
    ("match", "Colonial Urban Typologies",
     "Match the colonial city type in List I with its prominent Indian example in List II:",
     [("A", "Coastal Presidency Port"), ("B", "Colonial Hill Station"), ("C", "Planned Industrial Colony"), ("D", "Declining Pre-colonial Court")],
     [("I", "Bombay"), ("II", "Simla"), ("III", "Jamshedpur"), ("IV", "Murshidabad")],
     "A-I, B-II, C-III, D-IV",
     "Bombay was a presidency port; Simla was a colonial hill retreat; Jamshedpur was planned industrial; Murshidabad was a declined royal capital."),
    ("seq", "Milestones in Indian Industrial Policy",
     "Arrange the following milestones in Indian industrial and trade policy in chronological order:",
     [("A", "Destruction of Indian artisanal handlooms by Manchester factory textiles"),
      ("B", "Establishment of the National Planning Commission"),
      ("C", "Industrial Policy Resolution prioritizing basic and heavy capital industries"),
      ("D", "New Economic Policy introducing Liberalisation, Privatisation, and Globalisation (LPG)")],
     "A, B, C, D",
     "Artisanal destruction (19th c.), Planning Commission (1950), Industrial Policy Resolution (1956), New Economic Policy (1991).")
]

s31_extras = [
    ("Colonial Capitalism Definition", "In sociological analysis, how is modern capitalism fundamentally defined?",
     "An economic system based on private ownership of the means of production driven by the pursuit of profit in open competitive markets",
     ["A system where the king owns all land and distributes food rations annually", "A barter economy relying entirely on seashells and salt cakes", "A government-mandated ban on all foreign maritime commerce"],
     "Capitalism is characterized by private capital ownership, commodity production, wage labor, and profit maximization."),
    ("Colonial Railways Impact", "What was the primary economic objective behind the rapid expansion of the railway network by the British in 19th-century India?",
     "To transport agricultural raw materials from inland rural hinterlands to coastal ports and distribute British manufactured goods into the interior",
     ["To provide free leisure vacation travel for Indian peasant families", "To connect all pilgrimage shrines for spiritual national integration", "To promote indigenous handloom textile fairs across villages"],
     "Railways enabled the colonial extraction of raw materials and the penetration of imported industrial goods."),
    ("De-urbanisation Phenomenon", "Which of the following describes the phenomenon of 'de-urbanisation' observed in early colonial India?",
     "The population shift away from decaying traditional court and craft towns back into agriculture",
     ["The migration of all villagers into high-rise metropolitan apartment buildings", "The total evacuation of Bombay and Calcutta during monsoon months", "The conversion of railway stations into botanical flower gardens"],
     "Loss of court patronage and artisanal ruin forced townspeople back into crowded agricultural villages."),
    ("Assam Tea Coolies", "The labour force recruited for tea plantations in colonial Assam was predominantly composed of:",
     "Impoverished tribal peasants recruited from Chota Nagpur and central India under coercive indenture contracts",
     ["Wealthy zamindars from Awadh seeking recreational gardening skills", "European factory workers brought over from Manchester and Leeds", "Aristocratic courtiers from the Mughal imperial palace in Delhi"],
     "Tribal peasants from Chota Nagpur were recruited through deceptive arkatis (recruiters) into penal indenture."),
    ("Hill Stations as Sanatoriums", "Why did the British colonial rulers establish hill stations like Shimla, Darjeeling, and Ootacamund?",
     "To escape hot tropical plains, replicate temperate European climates, and serve as military sanatoriums and summer capitals",
     ["To hide gold treasures inside deep underground volcanic caves", "To construct commercial deep-water submarine shipping docks", "To clear pine trees for mechanized sugarcane and cotton plantations"],
     "Hill stations offered temperate refuges from tropical heat, convalescence for soldiers, and seats of colonial administration."),
    ("Drain of Wealth Concept", "Who formulated the seminal economic critique known as the 'Drain of Wealth' theory regarding colonial extraction from India?",
     "Dadabhai Naoroji in his book 'Poverty and Un-British Rule in India'",
     ["Lord Macaulay in his 1835 Education Minute", "Lord Curzon in the Bengal Partition declaration", "Robert Clive in the Treaty of Allahabad"],
     "Dadabhai Naoroji demonstrated that colonial Britain systematically drained Indian wealth to the home country without economic return."),
    ("Industrial Towns Emergence", "Which of the following is an example of a specialized steel city founded in colonial India through indigenous private enterprise?",
     "Jamshedpur founded by Jamsetji Tata",
     ["Agra founded by Sikandar Lodi", "Varanasi developed on the banks of the Ganges", "Pondicherry founded by François Martin"],
     "Jamshedpur (Tatanagar) was established in 1907 by Tata Iron and Steel Company (TISCO)."),
    ("Colonial Port Enclaves", "How were colonial presidency cities like Bombay, Calcutta, and Madras spatially segregated?",
     "Divided into 'White Towns' for European rulers and 'Black Towns' for native Indian populations",
     ["Divided into four quarters based on ancient Roman grid plans", "Separated by deep defensive moats filled with saltwater crocodiles", "Organized exclusively according to biological blood group categories"],
     "Colonial urban enclaves featured strict racial and spatial segregation between European White Towns and indigenous Black Towns."),
    ("Chawls in Bombay", "What were the 'chawls' that emerged in Bombay during the late 19th and early 20th centuries?",
     "High-density multi-storey tenements constructed to house migrant cotton textile mill workers",
     ["Colonial governor palaces with spacious marble banquet halls", "Military cantonment barracks for British naval officers", "Agricultural grain silos built along the Arabian Sea coastline"],
     "Chawls provided cheap, cramped housing for textile mill labourers migrating from the Konkan and Deccan."),
    ("Import Substitution Strategy", "What was the fundamental goal of independent India's 'Import Substitution Industrialisation' (ISI) strategy?",
     "To develop domestic heavy industries so the nation would not depend on imported foreign industrial products",
     ["To export all raw iron ore to foreign nations without domestic processing", "To permanently close all domestic engineering colleges and universities", "To replace factory machinery with hand-spun khadi wheels exclusively"],
     "ISI sought self-reliance by producing capital goods and basic machinery domestically behind tariff barriers."),
    ("Public Sector in Nehruvian Model", "Why did Jawaharlal Nehru refer to large dams, power plants, and public sector steel mills as the 'Temples of Modern India'?",
     "Because they symbolized technological self-reliance, national economic modernisation, and collective secular progress",
     ["Because religious priests performed daily animal sacrifices inside the blast furnaces", "Because private colonial corporations retained exclusive ownership over them", "Because they were built strictly using ancient Vedic architectural texts"],
     "Nehru viewed heavy industry and major dams as the foundational pillars of modern, secular, and sovereign India."),
    ("Informal Urban Sector", "What characterizes the informal sector in modern Indian urban economies?",
     "Absence of regular written contracts, lack of social security benefits, low capital intensity, and precarious earnings",
     ["Guaranteed lifetime government pensions and fully paid annual foreign holidays", "Mandatory registration on the London Stock Exchange", "Strict 4-hour working weeks enforced by the International Labour Organization"],
     "The informal sector lacks statutory labour protections, fixed wages, job security, and health insurance."),
    ("Class-I Cities Concentration", "Sociological studies show that urbanisation in contemporary India is 'top-heavy' because:",
     "A disproportionate share of the urban population and economic investment is concentrated in Class-I cities and mega-metropolises",
     ["Villages have higher populations of nuclear physicists than metropolitan capitals", "Small towns are growing ten times faster than major metropolitan centers", "All urban municipal corporations have abolished property taxation"],
     "Indian urban growth is skewed toward large metropolises, leaving small towns lagging in infrastructure and capital."),
    ("Gated Communities and Segregation", "In modern Indian metropolitan cities, the rise of 'gated communities' reflects:",
     "Socio-economic spatial segregation where affluent classes insulate themselves from civic public spaces and lower-class populations",
     ["The complete elimination of class and caste distinctions in urban living", "A legal mandate requiring all urban citizens to reside in identical communal dormitories", "A return to medieval feudal village fortresses designed for archers"],
     "Gated communities institutionalize social boundaries, privatizing security and civic amenities for upper-income classes."),
    ("Footloose Labour (Breman)", "Sociologist Jan Breman uses the concept of 'Footloose Labour' to describe:",
     "Migrant rural labourers forced to circulate continuously between temporary, informal, and seasonal casual jobs without security",
     ["Professional athletes who participate in international marathon competitions", "Government bureaucrats transferred between diplomatic embassies abroad", "Wealthy real estate investors purchasing holiday mansions globally"],
     "Footloose labour describes precarious seasonal circular migrants denied roots, legal contracts, or social protection.")
]

SLOT31 = build_slot(CH_STRUC, list(s31_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s31_extras])

# Slot 32: Cultural Change: Sanskritisation & Westernisation
s32_raw = [
    ("mcq", "Sanskritisation Coining", "Who introduced the concept of 'Sanskritisation' to explain cultural mobility in Indian society?",
     "M.N. Srinivas in his 1952 study 'Religion and Society among the Coorgs of South India'",
     ["G.S. Ghurye in 'Caste and Race in India'", "Louis Dumont in 'Homo Hierarchicus'", "D.P. Mukerji in 'Diversities'"],
     "M.N. Srinivas coined Sanskritisation after observing the emulation of upper-caste rites among the Coorgs."),
    ("stmt", "Sanskritisation and Structural Change",
     "Sanskritisation leads to positional change for a particular caste within the local hierarchy.",
     "Sanskritisation leads to structural change by completely abolishing the caste system and hierarchy.", 3,
     "Statement I is correct; Statement II is incorrect because Srinivas explicitly emphasized that Sanskritisation changes positions, not the caste structure itself."),
    ("ar", "Critique of Sanskritisation",
     "Dalit scholars and sociologists argue that Sanskritisation accepts and reinforces the ideology of caste hierarchy.",
     "Sanskritisation involves lower castes adopting upper-caste norms of ritual purity, often devaluing their own egalitarian traditions.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Emulating twice-born customs validates Brahminical purity-pollution dogmas."),
    ("match", "Cultural Change Concepts",
     "Match the sociological concept in List I with its primary feature in List II:",
     [("A", "Sanskritisation"), ("B", "Westernisation"), ("C", "Dominant Caste"), ("D", "De-Sanskritisation")],
     [("I", "Adopting twice-born customs, vegetarianism, and rituals"),
      ("II", "Changes resulting from British rule including technology, institutions, and ideology"),
      ("III", "Caste with substantial land, numerical strength, and local political power"),
      ("IV", "Shedding orthodox rituals or adopting folk and non-Brahminic practices")],
     "A-I, B-II, C-III, D-IV",
     "Sanskritisation is adopting twice-born rites; Westernisation reflects British impact; Dominant caste has land/numbers; De-Sanskritisation sheds orthodoxy."),
    ("seq", "Sociological Formulations by Srinivas",
     "Arrange the formulation and publication of these key sociological concepts and studies by M.N. Srinivas in chronological order:",
     [("A", "Publication of 'Religion and Society among the Coorgs of South India' introducing Sanskritisation"),
      ("B", "Elaboration of the concept of the 'Dominant Caste' in Rampura village studies"),
      ("C", "Publication of 'Social Change in Modern India' analyzing Westernisation"),
      ("D", "Publication of his classic ethnographic monograph 'The Remembered Village'")],
     "A, B, C, D",
     "Coorgs study (1952), Dominant Caste papers (late 1950s), Social Change in Modern India (1966), The Remembered Village (1976).")
]

s32_extras = [
    ("Reference Group Theory", "In sociological theory, Sanskritisation is closely related to which concept formulated by Robert K. Merton?",
     "Reference Group Theory, where a lower-status group emulates the values and behavior of a higher-status group",
     ["Labeling Theory of Deviance", "Organic Solidarity in Division of Labour", "Mechanical Solidarity of Primitive Hordes"],
     "Lower castes take twice-born castes as their reference group, aspiring to their prestige and social standing."),
    ("Three Levels of Westernisation", "According to M.N. Srinivas, Westernisation affects Indian society at which three levels?",
     "Behavioral (dress, food, habits), Cognitive/Value-oriented (humanitarianism, egalitarianism), and Institutional (courts, bureaucracy, schools)",
     ["Astrological, Mythological, and Theocratic", "Feudal, Dynastic, and Imperial", "Vegetarian, Herbal, and Monastic"],
     "Westernisation spans external lifestyles, internal value systems like rationalism, and formal modern institutions."),
    ("Dominant Caste Emulation", "M.N. Srinivas noted that in regions where Brahmins were not dominant, lower castes often Sanskritised by emulating:",
     "Locally dominant Kshatriya, martial, or landed peasant castes",
     ["European colonial sea captains and sailors", "Nomadic hunter-gatherers living in high mountain peaks", "Foreign diplomatic ambassadors residing in Delhi"],
     "Emulation models varied: castes mimicked locally powerful landed Kshatriya or peasant dominant groups."),
    ("Adoption of Pativrata and Dowry", "A major gender critique of Sanskritisation is that when lower castes emulate upper-caste customs, they often:",
     "Restrict women's autonomy, enforce purdah, ban widow remarriage, and replace bride-price with dowry",
     ["Grant women total economic ownership over all agricultural lands", "Abolish marriage entirely and establish matriarchal clans", "Require young men to perform unpaid domestic chores in their wives' homes"],
     "Sanskritisation frequently tightens patriarchal controls over lower-caste women by adopting upper-caste gender taboos."),
    ("Ambedkar on Sanskritisation", "Why did Dr. B.R. Ambedkar vehemently reject Sanskritisation as a strategy for Dalit liberation?",
     "Because imitating oppressors legitimizes the graded inequality of caste; Dalits need political power, education, and legal rights",
     ["Because Vedic rituals were too physically exhausting to perform in the summer", "Because Sanskrit texts were only printed on handmade paper", "Because British colonial officers banned all temple worship"],
     "Ambedkar asserted that mimicking upper castes accepts their ritual superiority instead of eradicating the caste system."),
    ("Multiple Modernities", "Contemporary sociologists use the concept of 'Multiple Modernities' to argue that:",
     "Modernisation in non-Western societies does not simply replicate Western cultural patterns, but synthesizes modernity with local traditions",
     ["All human cultures will eventually adopt the exact English dialect spoken in Oxford", "Industrialisation cannot take place outside of the North Atlantic continent", "Traditional cultures must completely erase their languages to develop"],
     "Modernity takes varied cultural forms in different societies rather than a singular Western blueprint."),
    ("Generational Westernisation", "In urban middle-class families, Westernisation across generations is characterized by:",
     "Adoption of Western lifestyle consumerism, individual career choices, and English medium education alongside selective domestic rituals",
     ["The complete elimination of family kinship ties and ancestral surnames", "Total rejection of all scientific medicine in favor of medieval alchemy", "A legal mandate forbidding children from speaking their mother tongue at home"],
     "Generational changes combine Western education, careerism, and consumer styles with selective cultural traditions."),
    ("Subaltern Critique of Purity", "Subaltern scholars argue that the historical process of Sanskritisation led to:",
     "The systematic marginalization and devaluation of indigenous, non-Brahminic artisanal knowledge, oral folklore, and labour traditions",
     ["The universal distribution of equal wealth across all rural households", "The immediate disappearance of all landlord debt contracts", "The compulsory teaching of Dalit musical instruments in colonial courts"],
     "Sanskritisation stigmatizes manual labour, folk deities, and indigenous craft traditions as 'polluting'."),
    ("Secularisation of Caste Practices", "Sociologist Rajni Kothari argued that in modern democratic elections, caste has become 'secularised' because:",
     "Caste acts as an organized political interest group and vote bank bargaining for state power and resources rather than ritual purity",
     ["Caste councils have banned all political parties from entering villages", "Voters refuse to participate in parliamentary elections", "The Constitution requires every citizen to declare a new gotra annually"],
     "Secularisation of caste transforms ritual status into competitive political mobilization for power and quotas."),
    ("Co-existence of Tradition and Modernity", "Which everyday example illustrates the co-existence of tradition and modernity in contemporary India?",
     "A modern software engineer performing Vedic Griha Pravesh rituals before moving into a high-tech smart apartment",
     ["A village completely isolated from electricity, roads, and modern footwear", "A society where all religious festivals have been legally abolished by parliament", "An economy that has returned entirely to stone-age barter trade"],
     "Tradition and modernity operate simultaneously: individuals utilize modern science while observing sacred rituals."),
    ("Westernisation and Social Mobility", "During colonial rule, Westernisation primarily benefited which social group first?",
     "Upper-caste urban elites who already possessed literary traditions and quickly acquired English education for administrative jobs",
     ["Landless agricultural labourers in remote tribal villages", "Traditional fishermen along coastal islands who had no schooling", "Nomadic pastoralists grazing sheep in Himalayan meadows"],
     "Literate upper castes leveraged English education to capture bureaucratic posts and commercial legal professions."),
    ("Bhagat Movements among Tribes", "In central India, Bhagat movements among tribal groups (such as Bhils and Gonds) represented:",
     "An indigenous form of Sanskritisation where tribals gave up meat and liquor and adopted Hindu ascetic symbols to claim higher social status",
     ["A military rebellion demanding total annexation of Portuguese Goa", "An initiative to establish steam-powered textile mills in dense forests", "A project to translate French literature into tribal dialects"],
     "Bhagat movements involved adopting puritanical Hindu rites, sacred threads, and vegetarianism to elevate status."),
    ("Westernisation without Modernisation", "Sociologists note that it is possible to experience 'Westernisation without Modernisation', which means:",
     "Adopting Western consumer gadgets, luxury cars, and fashion while retaining deeply orthodox, casteist, or patriarchal social attitudes",
     ["Refusing to wear Western clothes while adopting democratic egalitarian principles", "Migrating to London while abandoning all modern banking systems", "Learning English while refusing to speak to anyone outside one's family"],
     "External adoption of Western consumerism does not necessarily mean internalizing democratic or rational modern values."),
    ("Purity and Pollution Dichotomy", "In Louis Dumont's structural analysis of the caste system, the primary religious principle ordering hierarchy is:",
     "The binary opposition between the pure and the impure (purity and pollution)",
     ["The amount of gold deposited in local cooperative banks", "The number of horsepower engines owned by a peasant", "The geographical distance from the equator"],
     "Dumont argued in 'Homo Hierarchicus' that ritual purity-pollution is the fundamental organizing axiom of caste."),
    ("Compartmentalisation (Milton Singer)", "Sociologist Milton Singer observed that urban industrial workers in India handle modernity and tradition through 'compartmentalisation', meaning:",
     "Maintaining modern secular behavior at work in the factory or office, while strictly observing orthodox traditional rituals at home",
     ["Living in separate houses for breakfast, lunch, and dinner", "Working only two days a year and meditating for the remaining ten months", "Refusing to enter any building constructed with reinforced concrete"],
     "Workers compartmentalize life: modern secular rules in the workplace, orthodox ritual customs in the domestic sphere.")
]

SLOT32 = build_slot(CH_CULT, list(s32_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s32_extras])

# Slot 33: Cultural Change: Modernisation, Secularisation & 19th c. Social Reformers
s33_raw = [
    ("mcq", "Secularisation Definition", "In sociology, what does 'secularisation' fundamentally describe?",
     "The process whereby religious institutions, beliefs, and practices lose their social significance and authority in public life",
     ["The state-mandated destruction of all places of worship", "The forced conversion of an entire populace to one orthodox faith", "The mandatory study of ancient theological scriptures in public universities"],
     "Secularisation refers to the shrinking sphere of religious authority over public, legal, and educational institutions."),
    ("stmt", "Secularism Models",
     "The Western model of secularism implies strict institutional separation between Church and State.",
     "The Indian constitutional model of secularism requires equal respect for all religions (Sarva Dharma Sambhava) and non-discrimination.", 1,
     "Both Statement I and Statement II are correct. Indian secularism maintains principled distance and equal minority protection rather than strict isolation."),
    ("ar", "19th Century Reform Agendas",
     "19th-century social reform movements in India focused predominantly on customs affecting upper-caste women such as sati, child marriage, and widowhood.",
     "The prominent early social reformers were educated upper-caste urban men who sought to rationalize practices within their own community circles.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Reform agendas reflected the caste and class background of early male reformers."),
    ("match", "Reform Movements & Headquarters",
     "Match the 19th-century reform movement in List I with its region/origin in List II:",
     [("A", "Brahmo Samaj"), ("B", "Satyashodhak Samaj"), ("C", "Arya Samaj"), ("D", "SNDP Yogam")],
     [("I", "Bengal (Calcutta)"), ("II", "Maharashtra (Pune)"), ("III", "Bombay / Punjab"), ("IV", "Kerala (Aruvippuram)")],
     "A-I, B-II, C-III, D-IV",
     "Brahmo Samaj originated in Bengal; Satyashodhak in Maharashtra; Arya Samaj in Bombay/Punjab; SNDP Yogam in Kerala."),
    ("seq", "Milestones in Women's Rights Enactments",
     "Arrange the following legislative enactments for social and women's reform in chronological order:",
     [("A", "Bengal Sati Regulation declaring Sati illegal and punishable"),
      ("B", "Hindu Widows' Remarriage Act legalizing the remarriage of Hindu widows"),
      ("C", "Child Marriage Restraint Act (Sarda Act) fixing minimum marriage ages"),
      ("D", "Special Marriage Act permitting inter-caste and inter-religious civil marriages")],
     "A, B, C, D",
     "Abolition of Sati (1829), Widow Remarriage Act (1856), Sarda Act (1929), Special Marriage Act (1954).")
]

s33_extras = [
    ("Raja Rammohun Roy and Sati", "Raja Rammohun Roy led the successful public and scriptural campaign that resulted in the legal abolition of Sati in which year?",
     "1829, under Governor-General Lord William Bentinck",
     ["1757, after the Battle of Plassey", "1857, during the Great Rebellion", "1947, on the eve of Indian Independence"],
     "Lord William Bentinck enacted the Bengal Sati Regulation in December 1829 following Rammohun Roy's vigorous advocacy."),
    ("Jyotirao Phule and Satyashodhak Samaj", "Jyotirao Phule established the Satyashodhak Samaj in 1873 with the primary objective of:",
     "Liberating Shudras and Ati-Shudras from Brahminical oppression and promoting rational education",
     ["Promoting Sanskrit grammar lessons for high-caste priests", "Defending the hereditary rights of British district collectors", "Supporting landlord cartels against landless labourers"],
     "Phule's Satyashodhak Samaj (Truth Seekers' Society) championed anti-caste rationalism and education for marginalized groups."),
    ("Tarabai Shinde's Stri Purush Tulana", "What was the significance of Tarabai Shinde's 1882 publication 'Stri Purush Tulana' (Comparison between Women and Men)?",
     "It was one of the earliest radical feminist polemics written by an Indian woman, attacking male patriarchal hypocrisy and double standards",
     ["It was a cookbook containing traditional recipes from western Maharashtra", "It was a British tax handbook calculating land revenue in Bombay", "It was a romantic poem celebrating royal Maratha court dancers"],
     "Tarabai Shinde's powerful essay dismantled patriarchal double standards regarding chastity and morality."),
    ("Pandita Ramabai's Sharada Sadan", "Pandita Ramabai founded the 'Sharada Sadan' in Bombay in 1889 primarily to:",
     "Provide shelter, vocational skills, and modern education to destitute high-caste Hindu widows",
     ["Train British officers in classical Sanskrit poetics", "Manufacture handloom khadi for export to Manchester", "Organize military parades for imperial victory celebrations"],
     "Sharada Sadan (Home for Learning) provided education and vocational independence to young widows."),
    ("SNDP Movement Motto", "Sri Narayana Guru, leader of the anti-caste movement among the Ezhavas in Kerala, propagated the famous motto:",
     "'One Caste, One Religion, One God for Man' (Oru Jathi, Oru Matham, Oru Daivam Manushyanu)",
     ["'Back to the Vedas and Puranas'", "'Vande Mataram and Jai Hind'", "'Workers of the World, Unite'"],
     "Sri Narayana Guru fought against untouchability and proclaimed universal humanist equality."),
    ("Sir Syed Ahmed Khan and Aligarh", "Sir Syed Ahmed Khan established the Muhammadan Anglo-Oriental College (later AMU) in 1875 to:",
     "Promote modern Western scientific education and English literacy among Indian Muslims while preserving Islamic cultural heritage",
     ["Oppose all modern sciences and encourage medieval astrology", "Support the return of British East India Company monopoly trade", "Demand the immediate partition of the Indian subcontinent"],
     "Sir Syed believed modern scientific education was vital for social advancement and religious enlightenment."),
    ("Begum Rokeya's Sultana's Dream", "In her 1905 feminist utopia 'Sultana's Dream', Begum Rokeya Sakhawat Hossain envisioned 'Ladyland', where:",
     "Women run society using scientific solar technology while men are confined to domestic purdah (the 'murdana')",
     ["British viceroys surrender all powers to colonial merchants", "Caste rules are enforced by mechanical steam engines", "All human beings communicate exclusively through musical flutes"],
     "Begum Rokeya inverted gender roles in Ladyland, showcasing women's rational intellect, science, and peace."),
    ("Swami Dayanand and Arya Samaj", "Swami Dayanand Saraswati founded the Arya Samaj in 1875 with which core ideological call?",
     "'Go Back to the Vedas' — rejecting idolatry, polytheism, and hereditary caste while promoting Vedic rationalism",
     ["'Accept the hereditary supremacy of Puranic temple priests'", "'Abandon all Vedic rituals in favor of Western Christianity'", "'Establish a permanent feudal monarchy under the Peshwas'"],
     "Dayanand Saraswati rejected post-Vedic accretions (idolatry, child marriage, untouchability) and championed Vedic purity."),
    ("Veeresalingam Pantulu's Reform", "Kandukuri Veeresalingam Pantulu is revered as the father of modern Telugu social reform because he:",
     "Pioneered the movement for widow remarriage and girls' education in the Madras Presidency (Andhra region)",
     ["Organized armed peasant uprisings against the Nizam of Hyderabad", "Composed classical Carnatic devotional songs for royal courts", "Advocated for the retention of devadasis in temple worship"],
     "Veeresalingam conducted the first recorded widow remarriage in Andhra in 1881 and established schools for girls."),
    ("Savitribai Phule as Teacher", "Savitribai Phule is celebrated in modern Indian history as:",
     "India's first female school teacher who, along with Jyotirao Phule, opened pioneering schools for girls and lower castes in Pune",
     ["The first Indian woman appointed as governor of the Reserve Bank of India", "The founder of the Indian National Army's women's regiment", "The first woman judge of the Supreme Court of India"],
     "Savitribai Phule faced immense social hostility to educate girls and marginalized children in 1848 Pune."),
    ("Arya Samaj and Shuddhi", "The 'Shuddhi' movement launched by the Arya Samaj aimed to:",
     "Re-admit and purify individuals and groups who had converted from Hinduism to Christianity or Islam back into the Hindu fold",
     ["Purify the sacred waters of the Ganges using chemical filtration", "Cleanse all currency notes issued by the Reserve Bank of India", "Dismantle modern railway lines to prevent pollution of sacred soil"],
     "The Shuddhi movement sought reconversion, creating significant communal friction in 20th-century Punjab."),
    ("Karve and SNDT Women's University", "Maharshi Dhondo Keshav Karve founded India's first women's university (SNDT) in 1916 after establishing:",
     "An ashram and school for widows at Hingne near Pune, dedicating his life to widow rehabilitation and education",
     ["A commercial shipping port along the Konkan coastline", "A high-security prison for convicted dacoits", "A stock exchange for trading agricultural commodities"],
     "Karve was a tireless champion of widow remarriage and established the first Indian university dedicated solely to women."),
    ("Periyar's Self-Respect Marriages", "What was unique about the 'Self-Respect Marriages' introduced by E.V. Ramasamy Periyar in Tamil Nadu?",
     "They were conducted without Brahmin priests, Sanskrit mantras, or religious rituals, emphasizing gender equality and mutual respect",
     ["They required the groom to pay a massive dowry in gold bullion", "They were officiated exclusively by British district magistrates", "They mandated that both spouses live in separate villages permanently"],
     "Self-Respect marriages challenged Brahminical hegemony and patriarchal subjugation; legally recognized in Tamil Nadu in 1967."),
    ("Rationalism and Modernity", "In the sociological study of modernisation, 'Rationalisation' (as defined by Max Weber) refers to:",
     "The replacement of traditional beliefs, superstition, and magical thinking with systematic calculated reasoning and scientific logic",
     ["The blind obedience to hereditary astrological horoscopes", "The mandatory memorization of mythological heroic legends", "The permanent closure of all scientific laboratories"],
     "Rationalisation replaces superstition and customary fatalism with methodical calculation, science, and empirical inquiry."),
    ("Towards Equality Report (1974)", "The landmark report titled 'Towards Equality' submitted by the Committee on the Status of Women in India in 1974 highlighted:",
     "The alarming decline in the female sex ratio, worsening economic marginalization of women, and pervasive gender discrimination across India",
     ["That Indian women had achieved complete wage equality with men in all sectors", "That female literacy had surpassed 95% in every Indian province", "That dowry had completely disappeared from Indian marital practices"],
     "The 'Towards Equality' report was a watershed moment, catalyzing the contemporary autonomous women's movement in India.")
]

SLOT33 = build_slot(CH_CULT, list(s33_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s33_extras])

# Slot 34: The Story of Indian Democracy: Constitution & Panchayati Raj
s34_raw = [
    ("mcq", "Fundamental Rights Placement", "Which part of the Indian Constitution enshrines the Fundamental Rights guaranteed to all citizens?",
     "Part III (Articles 12 to 35)",
     ["Part II (Articles 5 to 11)", "Part IV (Articles 36 to 51)", "Part IV-A (Article 51A)"],
     "Part III guarantees fundamental liberties such as equality, freedom of speech, and constitutional remedies."),
    ("stmt", "Justiciability of Rights and DPSPs",
     "Fundamental Rights are legally enforceable by the courts through writs under Articles 32 and 226.",
     "Directive Principles of State Policy are non-justiciable, meaning courts cannot compel the government to enforce them.", 1,
     "Both Statement I and Statement II are correct. Fundamental Rights are justiciable; Directive Principles are guidelines for state policy."),
    ("ar", "73rd Amendment and Women's Representation",
     "The 73rd Constitutional Amendment Act of 1992 mandated at least one-third reservation for women in Panchayati Raj Institutions.",
     "The constitutional mandate aimed to institutionalize women's direct political representation and leadership in local rural governance.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Reserving 33% seats structurally enabled grassroots women's leadership."),
    ("match", "Panchayati Raj Three Tiers",
     "Match the Panchayati Raj level in List I with its institutional name in List II:",
     [("A", "Village Level"), ("B", "Block / Intermediate Level"), ("C", "District Level"), ("D", "General Body of Registered Voters")],
     [("I", "Gram Panchayat"), ("II", "Panchayat Samiti"), ("III", "Zilla Parishad"), ("IV", "Gram Sabha")],
     "A-I, B-II, C-III, D-IV",
     "Village tier is Gram Panchayat; intermediate is Panchayat Samiti; district is Zilla Parishad; voter assembly is Gram Sabha."),
    ("seq", "Panchayati Raj Committees",
     "Arrange the appointment of the following key committees on democratic decentralisation in chronological order:",
     [("A", "Balwant Rai Mehta Committee recommending a 3-tier Panchayati Raj system"),
      ("B", "Ashok Mehta Committee recommending a 2-tier system"),
      ("C", "L.M. Singhvi Committee recommending constitutional status for Panchayats"),
      ("D", "Passing of the 73rd and 74th Constitutional Amendment Acts")],
     "A, B, C, D",
     "Balwant Rai Mehta (1957), Ashok Mehta (1977-78), L.M. Singhvi (1986), 73rd/74th Amendments (1992).")
]

s34_extras = [
    ("Gram Sabha Powers", "In the 73rd Constitutional Amendment framework, the 'Gram Sabha' functions as:",
     "The basic deliberative body of all adult registered voters in a village, exercising social audits and reviewing development works",
     ["A committee composed exclusively of the top five wealthiest village moneylenders", "A judicial bench of High Court judges touring rural districts on horseback", "An executive board appointed directly by the World Bank"],
     "The Gram Sabha is the foundation of participatory democracy where all registered village voters deliberate on plans and audits."),
    ("PESA Act 1996 Mandate", "The Panchayats (Extension to Scheduled Areas) Act, 1996 (PESA) was enacted specifically to:",
     "Extend self-governance and recognize customary rights over land and minor forest produce to tribal communities in Fifth Schedule areas",
     ["Abolish all tribal languages and replace them with English", "Transfer all mineral rights from adivasis to multinational mining corporations", "Disband all local village councils in northeastern states"],
     "PESA protects tribal community autonomy, customary laws, and control over natural resources through empowered Gram Sabhas."),
    ("Karachi Resolution 1931", "Why is the Karachi Resolution passed by the Indian National Congress in 1931 historically momentous?",
     "It articulated the commitment to Fundamental Rights, universal adult suffrage, and socio-economic justice that formed the basis of the Indian Constitution",
     ["It declared that India would retain the British monarch as permanent head of state", "It banned Indian citizens from practicing any religion", "It called for the privatization of all public rivers and forests"],
     "Drafted by Nehru, the Karachi Resolution committed the national movement to democratic civil liberties and social rights."),
    ("Voting Age Lowering (61st Amendment)", "The 61st Constitutional Amendment Act, 1988 (effective 1989) expanded democratic participation by:",
     "Lowering the minimum voting age for citizens from 21 years to 18 years",
     ["Restricting voting rights to property owners paying income tax", "Mandating that only university graduates could vote in parliamentary elections", "Abolishing secret ballots in favor of open verbal voting"],
     "The 61st Amendment brought millions of young citizens into electoral democracy by lowering the voting threshold to 18."),
    ("Right to Information Act 2005", "The enactment of the Right to Information (RTI) Act in 2005 strengthened democratic governance by:",
     "Empowering citizens to inspect public records, question fund expenditures, and conduct social audits to curb corruption",
     ["Exempting all government ministries from public accountability", "Classifying all budget allocations as permanent military secrets", "Restricting investigative journalism to state-approved news channels"],
     "RTI promoted administrative transparency and citizen monitoring of public funds and entitlements."),
    ("Social Audit Phenomenon", "In rural development schemes like MGNREGA, a 'Social Audit' is defined as:",
     "A continuous public audit process where the community and beneficiaries verify project records, muster rolls, and expenditure",
     ["An annual inspection conducted in secret by international private accountants", "A formal ceremony where government officials distribute medals to landlords", "An academic examination administered to village school children"],
     "Social audits enable ordinary citizens to cross-check work muster rolls, wages, and materials against ground reality."),
    ("Sarpanch Pati Phenomenon", "Sociologists studying women in Panchayats use the term 'Sarpanch Pati' to describe:",
     "A patriarchal reality where the husband or male relative of an elected female sarpanch exercises de facto executive authority",
     ["A female sarpanch who governs multiple village councils simultaneously", "A special pension scheme awarded to male panchayat secretaries", "A legal clause disqualifying married women from contesting elections"],
     "Sarpanch Pati refers to informal male usurpation of power belonging to legally elected women representatives."),
    ("Empowerment through Reservation", "Despite initial challenges of proxy rule, empirical studies show that PR reservations for women have resulted in:",
     "Increased female agency, greater spending on drinking water and primary health, and rising political self-confidence among rural women",
     ["The complete withdrawal of women from all public community life", "A total collapse of all rural local administrative machinery", "The abandonment of agricultural farming across southern India"],
     "Over time, reservations foster genuine leadership, voice, and focus on basic community needs among women."),
    ("Constituent Assembly Drafting Committee", "Who was appointed as the Chairman of the Drafting Committee of the Constituent Assembly of India?",
     "Dr. B.R. Ambedkar",
     ["Dr. Rajendra Prasad", "Jawaharlal Nehru", "Sardar Vallabhbhai Patel"],
     "Dr. B.R. Ambedkar chaired the Drafting Committee, expertly synthesizing principles of liberty, equality, and fraternity."),
    ("Article 17 and Untouchability", "Article 17 of the Indian Constitution is of historic sociological significance because it:",
     "Abolishes 'Untouchability' and forbids its practice in any form, making its enforcement a punishable offense by law",
     ["Guarantees the freedom of the press in financial reporting", "Establishes the Supreme Court of India in New Delhi", "Mandates the annual census of livestock and domestic pets"],
     "Article 17 struck down the ancient ritual practice of untouchability, establishing universal dignity for Dalits."),
    ("State Finance Commission Role", "Under Article 243-I of the Constitution, what is the duty of the State Finance Commission?",
     "To review the financial position of Panchayats and recommend principles for devolving state taxes, tolls, and grants-in-aid to local bodies",
     ["To collect commercial taxes from foreign airlines operating in the state", "To finance international real estate ventures across foreign continents", "To regulate the interest rates charged by the International Monetary Fund"],
     "State Finance Commissions ensure fiscal decentralisation and equitable resource allocation to local self-governments."),
    ("Civil Society Concept", "In political sociology, 'Civil Society' refers to:",
     "The sphere of autonomous voluntary associations, citizen groups, NGOs, and movements operating between the family and the state",
     ["The armed military forces defending national borders", "The executive cabinet consisting of sworn government ministers", "The board of directors of profit-maximizing corporate conglomerates"],
     "Civil society comprises independent citizen initiatives that hold the state accountable and advance public causes."),
    ("Compulsory vs Voluntary PR Provisions", "In the 73rd Constitutional Amendment, which of the following is a 'compulsory' (mandatory) provision for all states?",
     "Reservation of one-third seats for women, 5-year fixed tenure, and constitution of State Election and Finance Commissions",
     ["Granting voting rights only to village elders above seventy years", "Mandatory military training for all village panchayat members", "Abolishing all political parties from contesting intermediate panchayat elections"],
     "Mandatory provisions (3-tier structure, 33% women quota, regular elections) cannot be altered at state discretion."),
    ("Representation vs Participation", "Sociologists distinguish between 'Representative Democracy' and 'Participatory Democracy' by noting that:",
     "Representative democracy functions via elected officials, whereas participatory democracy involves direct citizen deliberation in bodies like Gram Sabha",
     ["Representative democracy has no parliaments, while participatory democracy has no citizens", "Representative democracy is practiced only in forests, while participatory is in cities", "Representative democracy bans voting, while participatory enforces hereditary rule"],
     "Participatory democracy gives citizens a direct voice in decision-making rather than relying solely on elected proxies."),
    ("Nyaya Panchayats Jurisdiction", "What is the primary statutory purpose and limitation of 'Nyaya Panchayats' in rural India?",
     "To provide speedy, informal, low-cost resolution for petty civil disputes and minor offenses without complex procedural delays",
     ["To hear appeals against capital punishment sentences passed by High Courts", "To resolve international maritime border disputes with neighboring countries", "To enforce corporate bankruptcy liquidation on multinational companies"],
     "Nyaya Panchayats offer accessible local dispute resolution for petty civil claims and minor grievances.")
]

SLOT34 = build_slot(CH_DEMO, list(s34_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s34_extras])

# Slot 35: Rural Society: Land Reforms & Agrarian Structure
s35_raw = [
    ("mcq", "Permanent Settlement Landlords", "Under the Permanent Settlement of 1793 introduced by Lord Cornwallis in Bengal, who were recognized as legal proprietors of the soil?",
     "Zamindars (hereditary revenue-collecting intermediaries)",
     ["Peasant cultivators (ryots)", "Village headmen (lambardars)", "British district collectors exclusively"],
     "The Permanent Settlement converted intermediary revenue collectors into proprietary landlords with fixed revenue demands."),
    ("stmt", "Agrarian Reforms Success and Failure",
     "The Zamindari Abolition Act was broadly successful across India in eliminating the topmost layer of parasitic feudal intermediaries.",
     "Land Ceiling Acts were universally successful across all Indian states in acquiring surplus land and distributing it to all landless labourers.", 3,
     "Statement I is correct; Statement II is incorrect because land ceiling laws failed in most states due to benami transfers and political collusion."),
    ("ar", "Tenancy Reform Evictions",
     "Tenancy reform legislation in several Indian states paradoxically resulted in large-scale eviction of tenant farmers.",
     "Landlords exploited the legal loophole allowing resumption of land for 'personal cultivation' (khudkasht), turning tenants into informal unrecorded sharecroppers.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Resumption clauses incentivized landlords to throw out recorded tenants."),
    ("match", "Colonial Land Revenue Tenures",
     "Match the colonial land revenue system in List I with its primary characteristic in List II:",
     [("A", "Zamindari System"), ("B", "Ryotwari System"), ("C", "Mahalwari System"), ("D", "Bhoodan Movement")],
     [("I", "Revenue settled with intermediary landlords in Bengal and Bihar"),
      ("II", "Revenue settled directly with individual peasant cultivators in Madras and Bombay"),
      ("III", "Revenue settled with village estates or community bodies in Punjab and UP"),
      ("IV", "Voluntary donation and redistribution of agricultural land initiated by Vinoba Bhave")],
     "A-I, B-II, C-III, D-IV",
     "Zamindari recognized landlord intermediaries; Ryotwari settled with peasant ryots; Mahalwari settled with village communities; Bhoodan was voluntary land gifting."),
    ("seq", "Milestones in Agrarian Land Reforms",
     "Arrange the following land and agrarian developments in India in chronological order:",
     [("A", "Introduction of the Permanent Settlement in Bengal by Lord Cornwallis"),
      ("B", "Launch of the Bhoodan Movement at Pochampally by Acharya Vinoba Bhave"),
      ("C", "Enactment of National Land Ceiling guidelines across Indian states"),
      ("D", "Launch of Operation Barga in West Bengal to register sharecroppers")],
     "A, B, C, D",
     "Permanent Settlement (1793), Bhoodan (1951), Land Ceilings (early 1970s), Operation Barga (1978).")
]

s35_extras = [
    ("Operation Barga in West Bengal", "What was the landmark accomplishment of 'Operation Barga' launched by the Left Front in West Bengal in 1978?",
     "It recorded over a million sharecroppers (bargadars), conferring permanent hereditary cultivation rights and legal crop shares (75%)",
     ["It evicted all small farmers to create state-owned mechanized farms", "It abolished all agricultural credit societies in rural Bengal", "It prohibited farmers from growing paddy and jute"],
     "Operation Barga provided security of tenure and legal crop shares, protecting sharecroppers from eviction."),
    ("Benami Transfers Evasion", "In agrarian sociology, what were 'Benami transfers' used by landlords to thwart Land Ceiling laws?",
     "Fictitious or fraudulent land title registrations in the names of distant relatives, deceased ancestors, domestic servants, or pets",
     ["Legal donations of agricultural land to the United Nations Food and Agriculture Organization", "Voluntary sale of surplus fields to scheduled caste agricultural workers", "Converting farmland into government bird sanctuaries"],
     "Landowners retained de facto control over vast estates by dividing titles on paper among straw owners (benamidars)."),
    ("Kerala Radical Land Reforms", "Why is the land reform program implemented in Kerala under the 1969 Amendment Act regarded as the most radical in India?",
     "It completely abolished landlordism, conferring ownership rights on occupying tenants and hutment dwellers (kudikidappukars)",
     ["It converted all rural farmland into tea and coffee plantations", "It forced all agricultural labourers to migrate to Persian Gulf states", "It banned the use of modern tractors and electrical water pumps"],
     "Kerala successfully eradicated absentee landlordism and distributed homestead land to the most deprived rural households."),
    ("Agrarian Class Structure (Thorner)", "Economist Daniel Thorner categorized India's agrarian structure into which three broad social classes?",
     "Malik (landlords/proprietors), Kisan (working peasant owners), and Mazdur (landless agricultural labourers)",
     ["Aristocrats, Bourgeoisie, and Proletariat", "Priests, Warriors, and Merchants", "Bureacrats, Clerks, and Peons"],
     "Thorner's tripartite model (Malik, Kisan, Mazdur) highlighted differing relationships to land ownership and manual work."),
    ("Halipratha Bonded Labour", "The traditional 'Halipratha' system studied by sociologists in southern Gujarat was a form of:",
     "Hereditary debt bondage where lower-caste Dubla labourers were permanently bonded to high-caste Anavil Brahmin landlords",
     ["Cooperative organic farming practiced by modern university graduates", "An international fair for trading high-yielding cotton varieties", "A seasonal religious dance performed exclusively by village headmen"],
     "Halipratha institutionalized hereditary unfree debt servitude between patron landlords and bonded labourers."),
    ("Jajmani System Breakdown", "The traditional 'Jajmani system' in Indian villages began disintegrating primarily due to:",
     "The spread of a cash economy, commercialisation of agriculture, modern transport, and alternative urban wage employment",
     ["The complete drying up of all monsoon rainfall across the subcontinent", "A decree passed by the British Parliament banning all village festivals", "The refusal of village blacksmiths to manufacture iron ploughshares"],
     "Monetisation, factory goods, and urban wage work weakened customary hereditary patron-client reciprocity."),
    ("Feminisation of Agriculture Context", "What structural economic reality explains the 'feminisation of agriculture' in rural India?",
     "Men increasingly migrate to urban centers for non-farm work, leaving women behind to perform manual cultivation without owning the land",
     ["Women have legally inherited 90% of all agricultural land in India", "Men are prohibited by law from driving tractors and operating water pumps", "Women receive double the daily wages that male farm labourers earn"],
     "Distress male out-migration leaves women managing farm labour while patrilineal customs deny them title ownership."),
    ("Commercialisation Vulnerability", "How did the British commercialisation of agriculture aggravate rural peasant vulnerability to famines?",
     "It forced peasants to grow export cash crops (indigo, opium, cotton) instead of food grains, leaving them helpless when food prices spiked",
     ["It distributed free food grain rations to all rural households year-round", "It prohibited the collection of any land revenue during drought years", "It forced British merchants to buy Indian crops at ten times world market prices"],
     "Cash crop cultivation displaced subsistence food security, making peasants prey to market volatility and harvest failures."),
    ("Bhoodan and Gramdan Movement", "What was the philosophical premise of Acharya Vinoba Bhave's Bhoodan and Gramdan movements?",
     "Appealing to the conscience of landowners to voluntarily gift one-sixth of their land to landless families as an act of moral sharing (Dan)",
     ["Using armed guerilla combat to overthrow district administrative headquarters", "Selling agricultural plots to multinational corporate investors via auction", "Converting all rural villages into heavy chemical manufacturing complexes"],
     "Vinoba Bhave sought peaceful agrarian redistribution through moral persuasion and voluntary land surrender."),
    ("Agrarian Distress and Suicides", "Sociological investigations into the epidemic of farmers' suicides in states like Maharashtra, Andhra Pradesh, and Karnataka highlight:",
     "High debt burden, volatile global crop prices for cash crops (cotton), spurious inputs, and withdrawal of state agricultural subsidies",
     ["Excessive rainfall leading to uncontrollable bumper harvests of wheat", "The complete absence of private moneylenders in rural banking", "A government law guaranteeing free electricity and free hybrid seeds to all"],
     "Suicides stem from severe agrarian distress: debt traps, input costs, crop failures, and neoliberal price fluctuations."),
    ("Footloose Labourers Vulnerability", "Why are seasonal circular migrant agricultural workers particularly vulnerable to exploitation?",
     "They lack local voter cards, are excluded from local public distribution ration benefits, and have no union bargaining power",
     ["They receive double the minimum wage mandated by the central government", "They reside in luxury air-conditioned railway inspection cars", "They are legally protected by international diplomatic passports"],
     "Footloose migrants suffer social invisibility, poor living conditions, and lack access to local welfare schemes."),
    ("Land Fragmentation and Viability", "In rural India, the continuous division of family land through inheritance across generations results in:",
     "Severe subdivision and fragmentation of holdings, making plots economically unviable and difficult to cultivate efficiently",
     ["The automatic consolidation of entire districts into massive single farms", "The complete elimination of marginal and small peasant holdings", "The exponential increase in agricultural crop yields per acre"],
     "Inheritance fragmentation creates tiny, scattered plots that are uneconomic for mechanisation and investment."),
    ("Chakbandi (Land Consolidation)", "What was the agricultural objective of government 'Chakbandi' programs in northern India?",
     "To consolidate scattered, fragmented land parcels of a farmer into one or two compact, contiguous plots",
     ["To divide all large rivers into private irrigation ponds for wealthy landlords", "To dig deep trenches along all village borders to prevent livestock entry", "To replace all fertile alluvial topsoil with crushed limestone and river sand"],
     "Chakbandi combined scattered fragments into unified fields, reducing irrigation disputes and travel time."),
    ("Absentee Landlordism Definition", "In agrarian sociology, an 'Absentee Landlord' is one who:",
     "Owns agricultural land and extracts rent from tenant cultivators but resides elsewhere and takes no part in farm management",
     ["Cultivates land personally with his own family labour from dawn to dusk", "Drives a tractor daily to provide free ploughing for landless neighbours", "Refuses to collect any rent or share of produce from his tenant farmers"],
     "Absentee landlords live in urban centers, purely enjoying unearned ground rent without productive investment."),
    ("Kisan Movements (Champaran & Bardoli)", "Historic peasant struggles like the Champaran Satyagraha (1917) and Bardoli Satyagraha (1928) demonstrated:",
     "The capacity of peasant masses to organize non-violent resistance against colonial exploitation and exorbitant revenue hikes under national leadership",
     ["That Indian peasants demanded the permanent continuation of British colonial rule", "That peasants rejected Mahatma Gandhi's philosophy of non-violent civil disobedience", "That agricultural farmers refused to pay any wages to their hired farm workers"],
     "Peasant mobilizations integrated rural agrarian grievances with the broader anti-imperialist freedom struggle.")
]

SLOT35 = build_slot(CH_RURAL, list(s35_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s35_extras])

SLOTS_31_35 = {
    31: SLOT31,
    32: SLOT32,
    33: SLOT33,
    34: SLOT34,
    35: SLOT35
}

print("Slots 31 to 35 compiled successfully.")
