import sys, os
sys.path.insert(0, os.getcwd())
from scripts.subject_generators.slot_helpers import mcq, stmt, ar, match, seq

CH_DIV = "The Challenges of Cultural Diversity"

def build_slot(ch, items):
    res = []
    for itm in items:
        qtype = itm[0]
        if qtype == "mcq":
            _, top, stem, corr, wrongs, expl = itm
            res.append(mcq(ch, top, stem, corr, wrongs, expl))
        elif qtype == "stmt":
            _, top, s1, s2, rel, expl = itm
            res.append(stmt(ch, top, s1, s2, rel, expl))
        elif qtype == "ar":
            _, top, a, r, rel, expl = itm
            res.append(ar(ch, top, a, r, rel, expl))
        elif qtype == "match":
            _, top, stem, l1, l2, pair, expl = itm
            res.append(match(ch, top, stem, l1, l2, pair, expl))
        elif qtype == "seq":
            _, top, stem, items_list, order_str, expl = itm
            res.append(seq(ch, top, stem, items_list, order_str, expl))
    assert len(res) == 20, f"Slot has {len(res)} items instead of 20"
    return res

# Slot 26: Cultural Diversity - Pluralism & Nation-Building (20 Qs)
s26_raw = [
    ("mcq", "Cultural Diversity as Nation Asset", "In modern sociological and political theory, cultural diversity in a democratic nation like India is viewed as:",
     "A source of cultural richness and democratic strength that requires pluralistic accommodation rather than forced homogenization",
     ["An absolute catastrophe that makes democratic governance completely impossible",
      "A temporary condition that must be eliminated by enforcing a single national religion",
      "An economic tax burden that drains state revenues"],
     "Pluralism recognizes cultural diversity as an enriching asset that deepens democracy through constitutional accommodation."),
    ("stmt", "Minority Rights in Indian Constitution",
     "The Indian Constitution provides special cultural and educational safeguards for religious and linguistic minorities under Articles 29 and 30.",
     "Articles 29 and 30 require minority educational institutions to surrender all administrative autonomy to state-appointed priests.", 3,
     "Statement I is correct as Articles 29 and 30 guarantee minority rights; Statement II is incorrect as they preserve administrative autonomy."),
    ("ar", "Why Minorities Require Special Safeguards",
     "Religious and linguistic minorities require explicit constitutional safeguards in a majoritarian democracy.",
     "In a majoritarian parliamentary system, the numerical majority can use electoral power to suppress minority cultures and languages.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Constitutional safeguards prevent the 'tyranny of the majority'."),
    ("match", "Constitutional Articles on Cultural Rights",
     "Match the constitutional provisions in List I with their descriptions in List II:",
     [("A", "Article 29"), ("B", "Article 30"), ("C", "Article 25"), ("D", "Article 28")],
     [("I", "Right of minorities to establish and administer educational institutions of their choice"),
      ("II", "Protection of distinct language, script, or culture of any section of citizens"),
      ("III", "Freedom of conscience and free profession, practice, and propagation of religion"),
      ("IV", "Freedom as to attendance at religious instruction in state-funded educational institutions")],
     "A-II, B-I, C-III, D-IV",
     "Article 29 protects language/culture; Article 30 grants right to establish institutions; Article 25 guarantees religious freedom; Article 28 regulates instruction."),
    ("seq", "Phases of Nation-Building and Pluralism",
     "Arrange the stages of accommodation of diversity in modern Indian history in chronological order:",
     [("A", "Adoption of the Constitution guaranteeing fundamental cultural and minority rights"),
      ("B", "Linguistic reorganisation of Indian states accommodating regional linguistic identities"),
      ("C", "Resolution of regional autonomy movements through sub-state institutional accords"),
      ("D", "Recognition of indigenous forest tenure and local self-governance under PESA and FRA")],
     "A, B, C, D",
     "Chronology: 1950 Constitution, 1956 Linguistic Reorganisation, 1980s Autonomy Accords, and modern PESA/FRA.")
]

s26_extras = [
    ("Community Identity as Ascriptive", "In sociological theory, community identity (membership based on birth in a family, caste, or religious community) is characterized as:",
     "Ascriptive: it is not chosen by the individual, but shapes emotional belonging and deeply felt primordial attachments",
     ["Achieved through competitive written examinations", "Purchased annually from commercial banking corporations", "Temporary and discarded every five years"],
     "Community identity is ascriptive and unconditional, providing profound emotional security and sense of belonging."),
    ("Threat of Majoritarianism", "In the sociology of politics, 'Majoritarianism' is defined as:",
     "An ideology that asserts that the numerical majority community has a natural right to dominate society and impose its values on minorities",
     ["A system where every citizen receives an equal cash grant from the state", "A philosophy that advocates dividing the nation into twenty independent republics", "A legal requirement that all government decisions be made by children"],
     "Majoritarianism equates democracy with majority dominance, undermining pluralism, equal citizenship, and minority rights."),
    ("Linguistic Diversity of India", "According to the People's Linguistic Survey of India (PLSI), India's linguistic landscape is characterized by:",
     "Over 780 spoken languages belonging to five distinct language families, demonstrating immense linguistic pluralism",
     ["Exactly two spoken languages across the entire subcontinent", "A complete absence of any regional dialects", "All citizens speaking only modern computer code"],
     "India exhibits extraordinary linguistic diversity across Indo-Aryan, Dravidian, Austro-Asiatic, Tibeto-Burman, and Semito-Hamitic families."),
    ("Article 29(2) Non-Discrimination", "Article 29(2) of the Constitution explicitly prohibits educational institutions maintained by the state or receiving state aid from:",
     "Denying admission to any citizen on grounds only of religion, race, caste, language, or any of them",
     ["Charging any tuition fees to foreign tourists", "Teaching modern science and mathematics", "Conducting sports competitions on weekends"],
     "Article 29(2) guarantees non-discrimination in state-aided educational admissions based on religion, caste, or language."),
    ("Cultural Pluralism vs Melting Pot", "How does the Indian concept of 'Cultural Pluralism' (Salad Bowl model) differ from the American 'Melting Pot' model?",
     "Pluralism encourages distinct cultural groups to maintain their unique identities within a united nation, whereas the melting pot expects minorities to assimilate completely",
     ["Pluralism forces all citizens to live in underground caves", "The melting pot model allows every citizen to declare war on neighboring countries", "There is zero sociological difference between the two models"],
     "The salad bowl preserves distinct ingredients/identities in a shared bowl, unlike the melting pot which dissolves distinct cultures."),
    ("Civil Society in Diversity Protection", "Sociologists define 'Civil Society' as:",
     "The non-state, non-market sphere of voluntary associations, NGOs, trade unions, and citizen groups that mobilize to protect citizen rights and democratic accountability",
     ["The private commercial corporations listed on the stock exchange", "The armed police and military apparatus of the state", "The official cabinet of government ministers exclusively"],
     "Civil society operates in the public sphere between the state and the market, defending civil liberties and pluralism."),
    ("Right to Information (RTI) 2005 Role", "The enactment of the Right to Information Act, 2005 was a triumph of civil society mobilization (MKSS in Rajasthan) that:",
     "Empowered ordinary citizens to demand administrative transparency, inspect government records, and expose public corruption",
     ["Classified all government documents as permanent military secrets", "Banned journalists from reporting on public budget expenditures", "Abolished all democratic elections across India"],
     "RTI 2005 transformed citizens from passive subjects to active monitors of state transparency and accountability."),
    ("Nationalism vs Cosmopolitanism", "In political sociology, 'Cosmopolitanism' differs from narrow chauvinistic nationalism by:",
     "Affirming that all human beings belong to a single global community and respecting diverse cultural traditions beyond narrow national borders",
     ["Requiring all human beings to hold passports from the same European country", "Demanding the immediate physical destruction of all national borders by military force", "Advocating that all human beings live on international ships"],
     "Cosmopolitanism embraces universal human solidarity, intercultural dialogue, and ethical responsibility beyond borders."),
    ("Sub-State Nationalisms in India", "How has the Indian democratic federal structure historically handled strong sub-state regional identities (e.g. Tamil, Bengali, Odia)?",
     "By accommodating linguistic and cultural pride through federal state boundaries and regional language governance, strengthening national unity",
     ["By brutally outlawing all regional languages and burning regional literature", "By expelling entire linguistic provinces from the Indian Union", "By appointing foreign monarchs to rule over linguistic states"],
     "Accommodating linguistic identities within federal democracy defused secessionism, turning regional pride into a pillar of national unity."),
    ("Inclusive Citizenship Concept", "The concept of 'Inclusive Citizenship' in a pluralistic democracy ensures that:",
     "Citizenship is defined by shared constitutional values and equal civic rights, rather than belonging to a dominant religion, ethnicity, or language",
     ["Citizenship is granted only to individuals who own luxury commercial real estate", "Citizenship is revoked whenever an individual changes their residential address", "Citizenship is inherited exclusively through royal maternal bloodlines"],
     "Civic nationalism defines citizenship through constitutional loyalty and equal rights, rejecting ethnic or religious chauvinism."),
    ("Religious Demographics of India (Census 2011)", "According to the 2011 Census of India, the religious composition of the national population is approximately:",
     "79.8% Hindu, 14.2% Muslim, 2.3% Christian, 1.7% Sikh, 0.7% Buddhist, 0.4% Jain, and 0.9% other religions/unspecified",
     ["50% Hindu and 50% Buddhist exclusively", "100% belonging to a single religious denomination", "Zero religious believers across the entire population"],
     "Census 2011 records India's multi-religious reality, with Hindus forming the majority alongside substantial religious minorities."),
    ("Minority Complex and Vulnerability", "Sociologist T.K. Oommen observed that minority communities in majoritarian political climates frequently experience:",
     "A sense of psychological vulnerability, fear of cultural assimilation, and anxiety regarding the protection of their identity and security",
     ["Universal political supremacy and absolute control over national armed forces", "Complete indifference to their cultural traditions and sacred shrines", "The immediate disappearance of all minority cultural expressions"],
     "Minorities experience vulnerability when political discourse threatens their equal standing or cultural survival."),
    ("Language Controversies: Three-Language Formula", "The 'Three-Language Formula' adopted in Indian educational policy was designed to:",
     "Promote national integration by requiring students to study Hindi, English, and a regional language (a modern South Indian language in Hindi states)",
     ["Force all students to study ancient Greek and Latin exclusively", "Ban the teaching of all Indian languages in schools", "Require all university exams to be written in total silence"],
     "The Three-Language Formula sought to balance regional languages, the national link language (Hindi), and international English."),
    ("Identity Politics Function", "Sociologists analyze 'Identity Politics' in contemporary India as a mechanism through which:",
     "Marginalized communities organize around shared social identity (caste, religion, gender, ethnicity) to demand dignity, political voice, and state resources",
     ["Private corporate monopolies buy out all political parties", "Citizens renounce their constitutional voting rights", "Foreign nations dictate domestic election outcomes"],
     "Identity politics gives voice to historically suppressed groups, enabling democratic negotiation against structural marginality."),
    ("Amartya Sen on Plural Identities", "In *Identity and Violence: The Illusion of Destiny*, Amartya Sen warned that:",
     "Reducing an individual's rich, multifaceted identity to a single, solitarist categorization (such as religion) fuels sectarian hatred and conflict",
     ["Human beings possess only one biological identity that can never change", "All violent conflicts are caused by astronomical solar flares", "Human beings should be classified into thirty separate physical species"],
     "Sen argued that humans belong to multiple cross-cutting communities: solitarist reductionism into religious camps generates violence.")
]
for itm in s26_extras:
    top, stem, corr, wrongs, sol = itm
    s26_raw.append(("mcq", top, stem, corr, wrongs, sol))
SLOT26 = build_slot(CH_DIV, s26_raw)

# Slot 27: Communalism - Definition, Colonial Construction & Ideology (20 Qs)
s27_raw = [
    ("mcq", "Sociological Definition of Communalism", "In South Asian sociology and political science, 'Communalism' is defined as:",
     "An aggressive political ideology that asserts that religious identity is the primary basis of social, economic, and political loyalty, generating hostility toward other religious groups",
     ["A peaceful system of community organic farming practiced in village communes",
      "The scientific study of astronomical communication between distant stars",
      "A municipal program for building public parks and playgrounds in cities"],
     "In South Asia, communalism is the political mobilization of religious identity against other communities, generating sectarian conflict."),
    ("stmt", "Colonial Construction of Communalism",
     "Historians demonstrate that British colonial administrative practices (such as separate electorates and communal census classifications) deepened communal divisions in India.",
     "Communalism has existed identically in its modern political form since the Stone Age without any colonial or modern political influence.", 3,
     "Statement I is correct as colonial divide-and-rule solidified communal boundaries; Statement II is incorrect as modern communalism is modern."),
    ("ar", "Communalism as a Political Instrument",
     "Communalism is not fundamentally about spiritual or religious faith, but about secular political and economic power.",
     "Communal leaders mobilize religious symbols and historical grievances to unite cross-class vote banks and capture state power.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Sociologists follow Bipan Chandra in showing communalism is an ideology of power."),
    ("match", "Theorists and Communalism Concepts",
     "Match the scholars in List I with their sociological analyses of communalism in List II:",
     [("A", "Bipan Chandra"), ("B", "Asghar Ali Engineer"), ("C", "Paul Brass"), ("D", "T.K. Oommen")],
     [("I", "Analysis of 'Institutionalized Riot Systems' and elite political engineering of communal violence"),
      ("II", "Historical analysis of communalism as a modern false consciousness and political ideology"),
      ("III", "Distinction between religious consciousness, communal consciousness, and majoritarian chauvinism"),
      ("IV", "Socio-economic analysis of competition, petty-bourgeois rivalry, and religious riots")],
     "A-II, B-IV, C-I, D-III",
     "Bipan Chandra analyzed false consciousness; Engineer analyzed socio-economic roots; Brass analyzed riot systems; Oommen analyzed chauvinism."),
    ("seq", "Escalation of Communal Mobilization",
     "Arrange the historical phases of communal mobilization in colonial and post-colonial India in chronological sequence:",
     [("A", "Introduction of Separate Electorates under the Morley-Minto Reforms (1909)"),
      ("B", "The tragic Partition of the Indian subcontinent accompanied by mass communal massacres (1947)"),
      ("C", "Post-independence secular constitutional framework and initial decades of communal quiescence"),
      ("D", "Resurgence of competitive communal politics and majoritarian mobilization in the late 1980s and 1990s")],
     "A, B, C, D",
     "Chronology: 1909 separate electorates, 1947 Partition, post-independence secular decades, and 1980s-90s resurgence.")
]

s27_extras = [
    ("Morley-Minto Reforms 1909 Separate Electorates", "How did the Morley-Minto Reforms (Indian Councils Act 1909) institutionalize communalism in Indian politics?",
     "By creating separate electorates for Muslims, where Muslim candidates were elected exclusively by Muslim voters, institutionalizing communal political identities",
     ["By banning all religious worship in public temples and mosques", "By making Hindi the compulsory national language of the British Empire", "By granting complete independence to the Indian subcontinent"],
     "Separate electorates fragmented the national electorate along religious lines, institutionalizing communal constituencies."),
    ("Communalism vs Religiosity Distinction", "How do sociologists differentiate 'Religiosity' from 'Communalism'?",
     "Religiosity refers to personal spiritual faith, ethical conduct, and private devotion, whereas communalism is the political weaponization of religion to assert superiority over others",
     ["Religiosity applies only to ancient Greek mythology, while communalism applies to modern banking", "Religiosity is strictly illegal under the Indian Constitution, while communalism is mandated", "There is zero sociological difference between the two concepts"],
     "Deeply religious persons can be fiercely secular; communalism is not piety, but an antagonistic political ideology."),
    ("Paul Brass: Institutionalized Riot Systems", "Political scientist Paul Brass developed the concept of 'Institutionalized Riot Systems' (IRS) to demonstrate that communal riots are:",
     "Not spontaneous outbursts of ancient hatreds, but carefully orchestrated events planned by political actors, provocateurs, and local networks for electoral gain",
     ["Random natural disasters caused by seismic earthquake faults", "Accidental medical emergencies caused by viral infections in drinking water", "Spontaneous cultural celebrations where citizens exchange gifts"],
     "Brass showed riots are politically manufactured: maintained through specialized networks that activate violence for electoral consolidation."),
    ("Bipan Chandra's Three Stages of Communalism", "Historian Bipan Chandra categorized the evolution of communalism into three stages: Communal Consciousness, Liberal Communalism, and:",
     "Extreme or Fascist Communalism (asserting that different religious communities cannot live together peacefully)",
     ["Cosmopolitan Globalism", "Universal Buddhist Asceticism", "Marxist Revolutionary Socialism"],
     "Bipan Chandra mapped communalism from mutual interest consciousness to liberal negotiation and extreme/fascist exclusionary hatred."),
    ("Economic Roots of Communal Rivalry", "Socio-economic analyses of communal violence in industrial towns (e.g. Moradabad brassware, Bhiwandi powerlooms) reveal that riots often conceal:",
     "Economic competition between emerging minority entrepreneurs and established dominant merchants over business monopolies",
     ["Disputes over the grammar of classical Sanskrit literature", "Scientific rivalries between competing nuclear physics laboratories", "Conflicts over international commercial airline routes"],
     "Economic competition between business rivals frequently fuels communal tension, weaponizing religion to destroy competitors."),
    ("Media and Fake News in Communal Incitement", "In contemporary digital sociology, communal flare-ups are increasingly exacerbated by:",
     "Social media disinformation, manipulated videos, viral rumours, and hate speech designed to polarize communities rapidly",
     ["Printed encyclopedias published by university academic presses", "Weather forecast reports broadcast by meteorological stations", "Educational documentary films on marine wildlife"],
     "Social media algorithms and coordinated digital disinformation accelerate communal polarization, spreading fear and incendiary rumours."),
    ("Ghettoisation of Urban Space", "Following recurring episodes of communal violence in cities (e.g. Ahmedabad, Mumbai), residential patterns exhibit 'Ghettoisation', meaning:",
     "Minority communities withdraw from mixed neighborhoods into segregated, homogeneous spatial enclaves out of fear for physical safety",
     ["All urban citizens are granted free luxury suburban estates by municipal corporations", "Slums are completely eliminated and replaced by public botanical gardens", "Citizens are prohibited from residing in brick or concrete buildings"],
     "Ghettoisation is defensive spatial segregation: minorities cluster in secure enclaves, deepening inter-community alienation."),
    ("Partition of India 1947 Trauma", "Sociologists and oral historians emphasize that the 1947 Partition of India was characterized by:",
     "Catastrophic mass violence, abduction and sexual violence against women, and the forced displacement of over 14 million refugees",
     ["A peaceful administrative referendum conducted entirely through postal voting without any casualties", "A commercial merger between two private railway companies", "An international sports tournament held in London"],
     "Partition remains the foundational trauma of South Asian communalism: mass slaughter, sexual violence, and colossal refugee migration."),
    ("Women as Symbolic Victims in Communal Riots", "Sociologists analyze gendered violence during communal riots (rape, abduction, public humiliation) as:",
     "An assault on the symbolic 'honor' of the target community, where women's bodies are weaponized as territory in communal warfare",
     ["A random biological accident with zero connection to community politics", "A custom mandated by constitutional civil law", "A commercial transaction verified by banking receipts"],
     "In patriarchal communalism, women symbolize community purity: sexual violence is deployed to dishonour and terrorize the rival group."),
    ("Peace Committees and Grassroots Secularism", "Sociological studies of riot-resistant neighborhoods show that communal violence is successfully prevented by:",
     "Inter-community peace committees (Mohalla Committees), shared economic interdependence, and proactive civil society interventions",
     ["Deploying heavy military tanks to demolish all homes in the neighborhood", "Banning all human beings from speaking to their neighbors", "Shutting down all electricity and water supplies permanently"],
     "Active mohalla committees, cross-communal business ties, and vigilant citizens defuse rumours, keeping neighborhoods peaceful."),
    ("Majoritarian vs Minority Communalism", "In political sociology, majoritarian communalism is particularly dangerous because:",
     "It easily masquerades as authentic 'nationalism' or 'patriotism', using state machinery to legitimize the marginalization of minorities",
     ["It is supported exclusively by foreign hostile governments", "It completely abolishes the national police force and army", "It has zero voters or supporters in democratic elections"],
     "Majoritarian communalism can capture the state, redefining the nation in its own image while branding minority rights as 'appeasement'."),
    ("Minority Communalism Dynamics", "Minority communalism, according to sociologists, typically emerges as:",
     "A defensive, reactive retreat into religious conservatism, orthodoxy, and fear of assimilation in response to majoritarian aggression",
     ["An aggressive military campaign to conquer overseas continents", "A plan to establish international space stations in orbit", "A strategy to eliminate all religious worship entirely"],
     "Minority communalism is often reactive: driven by insecurity, it rallies around conservative orthodoxy to resist cultural erasure."),
    ("Secular Anti-Communal Movements", "Progressive civil society organizations combat communalism through:",
     "Counter-cultural street theatre, composite cultural celebrations, peace marches, fact-checking disinformation, and legal justice for riot victims",
     ["Purchasing nuclear weapons for private armies", "Enforcing compulsory religious conversion across all cities", "Demolishing historical heritage monuments"],
     "Civil society resists communalism by rebuilding composite culture (Ganga-Jamuni Tehzeeb) and demanding legal accountability for riots."),
    ("Composite Culture (Ganga-Jamuni Tehzeeb)", "The concept of 'Ganga-Jamuni Tehzeeb' in North Indian cultural sociology represents:",
     "The syncretic, shared cultural heritage, music, poetry, and mutual respect forged over centuries of Hindu-Muslim co-existence",
     ["An ancient river irrigation canal constructed by British engineers", "A specialized legal treaty regulating boat traffic on the Ganges river", "A private corporate brand of bottled drinking water"],
     "Ganga-Jamuni Tehzeeb celebrates syncretism: shared language (Urdu/Hindustani), music, festivals, and architecture bridging faiths."),
    ("Statutory Secular Protections", "The Indian Penal Code (Section 153A and 295A) penalizes communal hate speech by:",
     "Criminalizing acts that promote enmity, hatred, or ill-will between different religious groups and deliberate insults to religious feelings",
     ["Awarding national literary prizes to individuals who publish hate speech", "Banning all printed books and newspapers across the country", "Requiring all citizens to attend court hearings every morning"],
     "Sections 153A and 295A provide legal sanctions against promoting communal enmity, though enforcement is often politically contentious.")
]
for itm in s27_extras:
    top, stem, corr, wrongs, sol = itm
    s27_raw.append(("mcq", top, stem, corr, wrongs, sol))
SLOT27 = build_slot(CH_DIV, s27_raw)

# Slot 28: Regionalism - Linguistic States & Sub-Nationalism (20 Qs)
s28_raw = [
    ("mcq", "Linguistic Reorganisation of States 1956", "The States Reorganisation Act, 1956 was historic in Indian federalism because it:",
     "Redrew state boundaries primarily along linguistic lines, fulfilling regional democratic aspirations while preserving national unity",
     ["Abolished all state governments and created a unitary dictatorship run from New Delhi",
      "Divided India into fifty identical square geographical blocks without regard to culture",
      "Declared English as the sole language permitted to be spoken across the subcontinent"],
     "The 1956 Act reorganized state boundaries along linguistic lines, stabilizing Indian federal democracy."),
    ("stmt", "Potti Sreeramulu's Sacrifice",
     "Potti Sreeramulu undertook a historic 58-day hunger strike unto death in 1952 demanding a separate Andhra state for Telugu speakers.",
     "His death triggered widespread public mobilization that compelled Prime Minister Nehru to concede the formation of Andhra State in 1953.", 1,
     "Both statements are correct: Potti Sreeramulu's martyrdom forced the government to create Andhra State, catalyzing national linguistic reorganization."),
    ("ar", "Regionalism as Democratic Accommodation",
     "Regionalism in India has generally strengthened rather than weakened national democratic integration.",
     "By accommodating linguistic and cultural pride within federal states, the Indian Union defused centrifugal secessionist pressures.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Sociologists show that recognizing regional identities solidifies national belonging."),
    ("match", "States Reorganisation Commission and Landmarks",
     "Match the commissions and state creation milestones in List I with their years in List II:",
     [("A", "Creation of Andhra State"), ("B", "States Reorganisation Commission (Fazal Ali) Report"), ("C", "Bifurcation of Bombay into Gujarat and Maharashtra"), ("D", "Creation of Punjab and Haryana")],
     [("I", "1953"), ("II", "1955"), ("III", "1960"), ("IV", "1966")],
     "A-I, B-II, C-III, D-IV",
     "Andhra in 1953; SRC Report in 1955; Bombay bifurcated into Maharashtra/Gujarat in 1960; Punjab/Haryana bifurcated in 1966."),
    ("seq", "Milestones in Indian Linguistic Federalism",
     "Arrange the historical milestones of state reorganization in chronological sequence:",
     [("A", "Martyrdom of Potti Sreeramulu and creation of Telugu-speaking Andhra State"),
      ("B", "Implementation of the nationwide States Reorganisation Act"),
      ("C", "Bifurcation of bilingual Bombay State following the Samyukta Maharashtra and Mahagujarat movements"),
      ("D", "Reorganisation of the Northeast into distinct tribal states (Nagaland, Meghalaya, Mizoram)")],
     "A, B, C, D",
     "Milestones: Andhra (1953), SRC Act (1956), Maharashtra/Gujarat (1960), and Northeastern statehoods (1963-1972).")
]

s28_extras = [
    ("Fazal Ali Commission Composition", "The States Reorganisation Commission (SRC) appointed in 1953 was headed by Justice Fazal Ali and included which other prominent members?",
     "K.M. Panikkar and H.N. Kunzru", ["Jawaharlal Nehru and Sardar Patel", "B.R. Ambedkar and Mahatma Gandhi", "Lord Mountbatten and Cyril Radcliffe"],
     "The three-member Fazal Ali Commission comprised Justice Fazal Ali, historian K.M. Panikkar, and parliamentarian H.N. Kunzru."),
    ("Samyukta Maharashtra Movement", "The 'Samyukta Maharashtra Movement' (1956-1960) mobilized millions of citizens to demand:",
     "A separate Marathi-speaking state including Mumbai (Bombay) as its capital, resisting proposals to make Mumbai a Union Territory",
     ["The annexation of Sri Lanka into the state of Maharashtra", "The complete abolition of all railways in western India", "The declaration of Mumbai as an independent sovereign kingdom"],
     "The Samyukta Maharashtra Movement united Marathi speakers, successfully securing Maharashtra with Mumbai as capital in 1960."),
    ("Mahagujarat Movement", "The parallel 'Mahagujarat Movement' led by Indulal Yagnik campaigned for:",
     "The creation of a separate Gujarati-speaking state carved out of bilingual Bombay State",
     ["The incorporation of Gujarat into foreign overseas empires", "A statutory ban on all maritime trade along the Arabian Sea", "The conversion of all agricultural farms into textile mills"],
     "Indulal Yagnik led the Mahagujarat movement, securing statehood for Gujarat alongside Maharashtra in May 1960."),
    ("Punjab Reorganisation Act 1966", "The trifurcation of historic Punjab in 1966 under the Punjab Reorganisation Act created:",
     "Punjabi-speaking Punjab, Hindi-speaking Haryana, and transferred hilly areas to Himachal Pradesh, with Chandigarh as shared capital",
     ["Three independent sovereign republics with separate military forces", "A single unified province ruled directly by military martial law", "A commercial trading zone owned by foreign railway companies"],
     "The 1966 reorganisation created Punjab and Haryana along linguistic lines following the Punjabi Suba movement."),
    ("Sons of the Soil Ideology", "In regional political sociology, the 'Sons of the Soil' (Bhumiputra) doctrine asserts that:",
     "Local regional inhabitants have an exclusive, prior right to local educational admissions, government employment, and business opportunities over migrants",
     ["All agricultural land must be cultivated exclusively by infants under three years old", "All citizens must live on houseboats in international waters", "Migrants should receive free luxury housing while locals are expelled"],
     "Sons of the soil movements (e.g. Shiv Sena in 1960s Mumbai, Asom Gana Parishad) mobilize against migrant competition for jobs."),
    ("Anti-Hindi Agitations in Tamil Nadu (1965)", "The massive anti-Hindi agitations in Tamil Nadu in 1965 erupted primarily because:",
     "The constitutional deadline for Hindi to become the sole official language of the Union was perceived as imposing North Indian hegemony and disadvantaging non-Hindi speakers",
     ["Tamil speakers were legally forbidden from cultivating rice crops", "The central government banned the screening of all regional cinema", "The state was ordered to adopt classical Latin as its official language"],
     "The 1965 agitations compelled Parliament to pass the Official Languages Amendment Act 1967, guaranteeing indefinite continuation of English."),
    ("Regional Disparities and Internal Migration", "Unequal regional economic development in India drives large-scale circular migration from:",
     "Poorer, agrarian northern and eastern states (Bihar, UP, Odisha) toward industrialized western and southern states (Maharashtra, Gujarat, Tamil Nadu)",
     ["Industrial metropolitan cities into isolated wilderness mountain peaks", "Foreign nations into rural agricultural villages exclusively", "Coastal fishing harbors into underground coal mines"],
     "Regional imbalances create economic pipelines: surplus agrarian labor from the east and north fuels western and southern urban growth."),
    ("Creation of Small States in 2000", "The creation of Chhattisgarh, Uttarakhand, and Jharkhand in November 2000 was justified primarily on grounds of:",
     "Administrative efficiency, regional developmental neglect, and tribal/ecological aspirations, rather than pure linguistic identity",
     ["Linguistic disputes between speakers of classical Sanskrit and Latin", "Orders issued by foreign international banking cartels", "The complete collapse of all railway transportation across India"],
     "The 2000 statehoods were driven by development deficits, geographic terrain (hills/plateaus), and tribal identity rather than language."),
    ("Telangana Statehood Struggle", "The historic struggle culminating in the creation of Telangana in June 2014 was sparked by:",
     "Persistent perceptions of economic neglect, educational discrimination, and unequal allocation of Krishna-Godavari water resources within united Andhra Pradesh",
     ["A linguistic disagreement regarding the Telugu alphabet", "A demand to abolish the Indian Constitution across southern India", "An executive order issued by the United Nations"],
     "Telangana emerged from protracted popular struggles highlighting regional economic exploitation within a shared linguistic state."),
    ("Regional Political Parties Ascendance", "In Indian political sociology, the rise of powerful regional parties (DMK, AIADMK, TMC, TDP, BJD, AAP) has:",
     "Deepened federal coalition governance, forcing national parties to negotiate and accommodate diverse regional priorities",
     ["Completely destroyed the Indian federal union and restored British colonial rule", "Abolished the Supreme Court of India and all state high courts", "Banned all citizens from speaking regional languages in Parliament"],
     "Regional parties federalized Indian democracy: national governments rely on coalitions, institutionalizing regional bargaining power."),
    ("Inter-State River Water Disputes", "Contentious disputes over river water sharing (e.g. Cauvery dispute between Tamil Nadu and Karnataka) demonstrate how:",
     "Regional resource scarcity can trigger intense sub-national mobilization, bandhs, and inter-state legal battles that challenge federal arbitration",
     ["Rivers in India flow strictly in reverse directions from the sea into mountains", "State governments have banned all human consumption of drinking water", "Water is declared an illegal substance under the Indian Penal Code"],
     "River disputes pit regional agrarian interests against each other, testing federal tribunal dispute mechanisms."),
    ("Article 371 Special Federal Provisions", "The Constitution of India incorporates asymmetrical federalism through Article 371 (A to J) to:",
     "Provide specialized protective governance, customary law recognition, and development boards for specific states (Nagaland, Mizoram, Assam, Karnataka-Hyderabad)",
     ["Mandate that all citizens living in these states pay double income taxes", "Prohibit residents of these states from travelling to other Indian provinces", "Abolish all local legislative assemblies permanently"],
     "Article 371 embeds asymmetrical federalism: protecting indigenous customs, land alienation, and regional development boards."),
    ("Regional Stereotyping and Discrimination", "Sociologists study regional stereotyping in metropolitan cities (e.g. discrimination faced by Northeastern youth in Delhi) as:",
     "A form of racialized regional chauvinism and social distance that violates constitutional promises of equal national citizenship",
     ["A compulsory civic ceremony celebrated during national public holidays", "An automated scientific discovery made by international astronomers", "A policy funded by the Ministry of External Affairs"],
     "Racialized stereotyping against Northeastern citizens reflects majoritarian ignorance, prompting committees (Bezbaruah) and hate-crime reforms."),
    ("Sub-National Identity and National Patriotism", "Sociological studies demonstrate that strong sub-national cultural pride (e.g. being proudly Bengali, Marathi, or Tamil) is:",
     "Completely compatible with, and often reinforces, deep emotional patriotism and commitment to the Indian national union",
     ["A treasonous criminal offense punishable by life imprisonment under military law", "Incompatible with any form of national citizenship or constitutional loyalty", "Invented by foreign commercial advertising agencies in the twentieth century"],
     "Indian federalism embodies 'nested identities': citizens hold passionate regional linguistic loyalty alongside deep Indian national identity."),
    ("Federal Finance: Finance Commission Role", "Under Article 280, the Finance Commission of India balances regional disparities by:",
     "Recommending the constitutional devolution of central tax revenues to states using weighted criteria like population, income distance, and forest cover",
     ["Confiscating all revenue from poorer states and giving it to billionaire industrialists", "Abolishing all public health and education budgets nationwide", "Investing all national tax revenues in foreign space stations"],
     "The Finance Commission uses progressive devolution formulas to transfer resources from affluent to poorer states, mitigating regional disparity.")
]
for itm in s28_extras:
    top, stem, corr, wrongs, sol = itm
    s28_raw.append(("mcq", top, stem, corr, wrongs, sol))
SLOT28 = build_slot(CH_DIV, s28_raw)

# Slot 29: Secularism - Western vs Indian (Principled Distance) (20 Qs)
s29_raw = [
    ("mcq", "Indian vs Western Secularism Model", "How does the Indian constitutional model of 'Secularism' differ fundamentally from the classical Western (French laïcité) model?",
     "Western secularism mandates strict mutual exclusion between church and state, while Indian secularism practices 'principled distance' and equal respect for all religions (Sarva Dharma Sambhava)",
     ["Indian secularism bans all religious worship, while Western secularism forces all citizens to attend church",
      "Indian secularism establishes Hinduism as the official state religion, while Western secularism is governed by the Pope",
      "There is zero theoretical or constitutional difference between the two models"],
     "Western secularism enforces strict separation; Indian secularism practices principled distance, equal respect, and progressive social reform."),
    ("stmt", "Principled State Intervention in Religion",
     "Under the Indian model of secularism, the state is permitted to intervene in traditional religious practices for progressive social reform (e.g. abolishing untouchability and triple talaq).",
     "In strict French laïcité, the state cannot financially aid religious schools or intervene in internal theological doctrines.", 1,
     "Both statements are correct: Indian secularism permits principled intervention to eradicate social evils, unlike rigid Western separation."),
    ("ar", "State Aid to Minority Institutions",
     "The Indian state is constitutionally authorized to provide financial aid to religious and linguistic minority educational institutions.",
     "Article 30(2) of the Constitution mandates that the state shall not discriminate against any educational institution on the ground that it is under minority management.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Indian secularism supports all religions equitably rather than rejecting state aid."),
    ("match", "Secularism Models and Defining Principles",
     "Match the models of secularism in List I with their defining principles in List II:",
     [("A", "Western (Wall of Separation)"), ("B", "French Laïcité"), ("C", "Indian Secularism"), ("D", "Sarva Dharma Sambhava")],
     [("I", "Equal respect for all religious faiths and spiritual traditions"),
      ("II", "Strict prohibition of all visible religious symbols in public civic institutions and schools"),
      ("III", "Complete mutual non-interference: state has no religious role and religion has no state role"),
      ("IV", "Principled distance allowing non-discriminatory state intervention for social justice and reform")],
     "A-III, B-II, C-IV, D-I",
     "Wall of separation is mutual non-interference; Laïcité bans visible symbols; Indian is principled distance; Sarva Dharma Sambhava is equal respect."),
    ("seq", "Constitutional Evolution of Indian Secularism",
     "Arrange the milestones in the constitutional jurisprudence of Indian secularism in chronological order:",
     [("A", "Adoption of the Constitution guaranteeing freedom of conscience under Articles 25-28"),
      ("B", "Explicit insertion of the word 'SECULAR' into the Preamble via the 42nd Constitutional Amendment"),
      ("C", "Supreme Court *S.R. Bommai* landmark judgment declaring secularism a 'Basic Structure' of the Constitution"),
      ("D", "Judicial struck down of arbitrary dismissals of elected state governments on secular grounds")],
     "A, B, C, D",
     "Evolution: 1950 Articles 25-28, 1976 42nd Amendment, and 1994 *S.R. Bommai* ruling enshrining secularism as Basic Structure.")
]

s29_extras = [
    ("S.R. Bommai Landmark Judgment 1994", "In the landmark *S.R. Bommai v. Union of India* (1994) judgment, the Supreme Court ruled that:",
     "Secularism is a foundational 'Basic Feature' of the Constitution, and any state government that acts against secularism is liable to dismissal under Article 356",
     ["India must immediately adopt an official state religion", "The Constitution was invalid and should be replaced by colonial law", "State governments have absolute power to ban religious worship"],
     "The Bommai ruling declared secularism part of the unalterable Basic Structure, barring political parties from using religion for state power."),
    ("Rajeev Bhargava on Principled Distance", "Political philosopher Rajeev Bhargava conceptualized the unique nature of Indian secularism through the concept of:",
     "'Principled Distance'—where the state maintains distance from all religions, but intervenes when necessary to uphold social justice, equality, and human rights",
     ["'Absolute Atheism' where the state demolishes all religious buildings", "'Majoritarian Hegemony' where the largest religion dictates all laws", "'Religious Monopoly' where the state is governed by hereditary priests"],
     "Rajeev Bhargava's 'principled distance' explains that the state may engage or disengage with religion based on justice and non-discrimination."),
    ("Preamble 42nd Amendment 1976", "The word 'SECULAR' was explicitly added to the Preamble of the Indian Constitution by which landmark amendment?",
     "The 42nd Constitutional Amendment Act, 1976", ["The 1st Amendment Act, 1951", "The 44th Amendment Act, 1978", "The 86th Amendment Act, 2002"],
     "The 42nd Amendment (1976) explicitly inscribed 'Secular' and 'Socialist' into the Preamble, formalizing pre-existing constitutional principles."),
    ("Uniform Civil Code Debate (Article 44)", "In constitutional sociology, the debate around Article 44 (Directive Principle regarding a Uniform Civil Code) centers on:",
     "The tension between gender justice and uniform civil rights on one hand, and minority anxieties over the protection of cultural identity on the other",
     ["A requirement that all citizens wear identical military uniforms in public", "A plan to abolish all private commercial banks across the country", "A statutory ban on citizens owning private residential homes"],
     "The UCC debate balances gender equality and universal civil law with minority community autonomy and freedom of religion."),
    ("Special Marriage Act 1954 as Secular Space", "How does the Special Marriage Act, 1954 institutionalize secular citizenship in India?",
     "By providing a legal framework for civil marriage where two adults can marry without converting their religion or undergoing religious rites",
     ["By forcing both partners to convert to a single state-chosen religion", "By mandating that all marriages be approved by village caste panchayats", "By prohibiting individuals from different religions from ever speaking to each other"],
     "The Special Marriage Act creates a secular legal space for inter-faith and inter-caste unions under neutral civil contract law."),
    ("Haj Subsidy Abolition and Temple Boards", "The abolition of the central Haj subsidy alongside state management of major Hindu temple shrines (e.g. Tirupati) illustrates that:",
     "The Indian state actively engages with religious institutions for administrative logistics and equal treatment, unlike Western non-intervention",
     ["The Indian state has completely banned all religious pilgrimages", "The government has declared all temples and mosques state military barracks", "India is governed by foreign international church councils"],
     "Indian secularism involves state logistics, pilgrimage security, and statutory temple trusts, reflecting complex regulatory engagement."),
    ("Freedom of Conscience (Article 25)", "Article 25 of the Constitution guarantees freedom of conscience and the right freely to profess, practice, and propagate religion, subject to:",
     "Public order, morality, health, and other fundamental rights provisions in Part III of the Constitution",
     ["Zero restrictions of any kind, allowing human sacrifice and violence", "The approval of foreign commercial multinational corporations", "The permission of local village moneylenders"],
     "Religious freedom under Article 25 is not absolute: it is constitutionally circumscribed by public order, health, morality, and fundamental rights."),
    ("T.N. Madan's Critique of Secularism", "Sociologist T.N. Madan famously provoked academic debates by arguing that in deeply religious South Asian societies:",
     "Secularism as an imported Western doctrine is an inadequate and alien ideology that cannot easily grasp South Asian living faiths",
     ["All human beings are naturally atheists who hate religious rituals", "South Asia should be placed under foreign colonial administration", "Religion has zero influence on human social behavior in India"],
     "T.N. Madan critiqued secularism as an elite transplant, arguing it failed to connect with the deep religious tapestry of South Asian life."),
    ("Ashis Nandy on Religious Tolerance", "Political psychologist Ashis Nandy argued that genuine communal peace in India historically relied more on:",
     "Traditional religious tolerance, popular syncretism, and everyday folk morality rather than westernized, state-sponsored secularism",
     ["Totalitarian military policing and armed surveillance towers", "A statutory ban on all religious texts and literature", "High-frequency electronic financial trading on Wall Street"],
     "Ashis Nandy contrasted everyday religious tolerance of ordinary people with modern state-managed secularism that provoked fundamentalism."),
    ("Dharma Nirpekshata vs Panth Nirpekshata", "In Hindi constitutional vocabulary, 'Panth Nirpekshata' is preferred over 'Dharma Nirpekshata' to translate 'Secularism' because:",
     "'Dharma' encompasses broad moral duty and cosmic righteousness, whereas 'Panth' denotes specific sectarian religious denominations",
     ["'Dharma' is a modern English word borrowed from European philosophy", "'Panth' is a foreign word used only in South America", "There is zero linguistic difference between the two terms"],
     "Panth Nirpekshata (sectarian neutrality) clarifies that the state is neutral toward sectarian creeds while upholding moral duty (Dharma)."),
    ("Bans on Female Degrading Practices", "Under secular social reform, the Indian state enacted laws prohibiting Sati (1829/1987), child marriage (1929/2006), and Devadasi dedication because:",
     "Religious freedom cannot be used as a shield to practice severe human rights violations and patriarchal violence against women",
     ["The state wished to destroy all Indian cultural traditions permanently", "Foreign governments ordered the immediate closure of all temples", "The Supreme Court abolished all forms of marriage in India"],
     "Secular democracy subordinates religious custom to human dignity, invalidating practices that harm women or violate life."),
    ("State Funding of Secular Education", "Article 28(1) of the Indian Constitution lays down that:",
     "No religious instruction shall be provided in any educational institution wholly maintained out of State funds",
     ["All state schools must conduct compulsory morning prayers in classical Sanskrit", "All universities must teach only theological scriptures exclusively", "State funds can only be spent on building private religious shrines"],
     "Article 28(1) ensures that public state-funded schools remain completely secular, barring mandatory religious indoctrination."),
    ("Secularisation Thesis in Sociology", "The classic sociological 'Secularisation Thesis' (Bryan Wilson, Peter Berger) predicted that modern industrialisation would:",
     "Invariably lead to the decline of religious belief, privatization of faith, and retreat of religion from the public sphere",
     ["Result in every human being becoming an orthodox monastic hermit", "Cause all scientific technology and factories to be dismantled", "Force all citizens to worship medieval feudal kings"],
     "The classical secularisation thesis argued that science, urbanisation, and rationalisation would diminish religion's public power."),
    ("Desecularisation and Religious Resurgence", "In recent decades, sociologists (including Peter Berger himself) revised the secularisation thesis because:",
     "Religion has experienced a powerful resurgence in global politics, public mobilization, and modern media, defying predictions of its demise",
     ["All human beings have stopped believing in medical science and technology", "The United Nations declared that science was illegal worldwide", "All universities across the world shut down their science departments"],
     "Berger acknowledged the world remains furiously religious: modern technology and democracy often revitalize public religious politics."),
    ("Constitutional Secularism as Compromise", "Sociologists view Indian secularism as an extraordinary historical compromise between:",
     "The universal individual rights of liberal democracy and the collective cultural rights of distinct communities to maintain their heritage",
     ["Two foreign imperial armies fighting for territorial conquest", "Private commercial real estate developers and airline companies", "Ancient nomadic hunting bands and modern computer programmers"],
     "Indian secularism creatively synthesizes individual equality with group-differentiated rights to protect composite nationhood.")
]
for itm in s29_extras:
    top, stem, corr, wrongs, sol = itm
    s29_raw.append(("mcq", top, stem, corr, wrongs, sol))
SLOT29 = build_slot(CH_DIV, s29_raw)

# Slot 30: Nation-State vs State-Nation - Assimilationist vs Integrationist Policies (20 Qs)
s30_raw = [
    ("mcq", "Nation-State vs State-Nation Models", "In political sociology (Alfred Stepan, Juan Linz, Yogendra Yadav), how does a 'State-Nation' differ from a classic 'Nation-State'?",
     "A Nation-State enforces cultural and linguistic homogenization to create one nation, while a State-Nation fosters multiple cultural identities within a single democratic constitutional state",
     ["A State-Nation has zero territory or citizens and exists only in outer space",
      "A Nation-State permits every village to secede and form an independent empire",
      "There is zero theoretical difference between the two concepts"],
     "Stepan, Linz, and Yadav formulated 'State-Nation' for India: fostering democratic loyalty while embracing multiple cultural identities."),
    ("stmt", "Assimilationist vs Integrationist Policies",
     "Assimilationist policies seek to absorb cultural minorities into the dominant culture, suppressing distinct minority traditions and languages.",
     "Integrationist policies encourage diverse cultural communities to maintain their distinct heritages while sharing a common public civic loyalty.", 1,
     "Both statements are correct: Assimilation forces cultural conformity; Integration respects private/communal pluralism within shared civic citizenship."),
    ("ar", "Why State-Nation Model Fits India",
     "The 'State-Nation' model has preserved India's democratic unity far more successfully than a rigid 'Nation-State' model would have.",
     "Forced cultural homogenization in a deeply diverse society like India would have triggered violent civil wars, secessionist rebellions, and national disintegration.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Cultural pluralism and federal accommodation prevented secessionist collapse."),
    ("match", "Integration Policies and Models",
     "Match the policies toward diversity in List I with their descriptions in List II:",
     [("A", "Assimilationist Policy"), ("B", "Integrationist Policy"), ("C", "State-Nation Model"), ("D", "Classic Nation-State")],
     [("I", "Fosters multiple cultural identities (e.g. Tamil and Indian) alongside shared democratic allegiance"),
      ("II", "Demands complete erasure of minority distinctiveness and adoption of dominant majority culture"),
      ("III", "Premised on 'one nation, one culture, one language' within sovereign borders (e.g. classic European model)"),
      ("IV", "Protects cultural diversity in private/community life while building shared civic citizenship in public space")],
     "A-II, B-IV, C-I, D-III",
     "Assimilation is forced conformity; Integration is pluralism with shared civic space; State-Nation fosters dual loyalty; Nation-State is one-culture/one-state."),
    ("seq", "Trajectory of Democratic State-Nation Consolidation",
     "Arrange the phases of Indian state-nation consolidation in logical sequence:",
     [("A", "Drafting of an egalitarian Constitution guaranteeing group rights alongside individual rights"),
      ("B", "Linguistic reorganization of provinces enabling regional cultures to govern within federal units"),
      ("C", "Institutionalization of affirmative action (reservations) for marginalized castes and tribes"),
      ("D", "Continuous democratic negotiation and accommodation of emerging regional and identity aspirations")],
     "A, B, C, D",
     "Consolidation progressed from constitutional guarantees to linguistic federalism, affirmative representation, and ongoing negotiation.")
]

s30_extras = [
    ("Stepan, Linz, and Yadav Comparative Study", "In *Crafting State-Nations*, Stepan, Linz, and Yadav compared India's political stability with:",
     "Multi-ethnic states like Sri Lanka and Yugoslavia that collapsed into violent civil war because they attempted majoritarian homogenization",
     ["Monolingual European island states with zero cultural diversity", "Ancient feudal empires governed by hereditary monarchs", "Nomadic pastoralist communities living in Arctic regions"],
     "The authors proved that India survived as a united democracy because it chose the State-Nation model over majoritarian homogenization."),
    ("Sri Lanka's Failure of Nation-State Model", "Why did Sri Lanka descend into decades of bloody ethnic civil war following its 1956 'Sinhala Only Act'?",
     "Because the majoritarian state attempted to enforce an assimilationist nation-state, suppressing the linguistic and political rights of the Tamil minority",
     ["Because Sri Lanka was completely flooded by ocean tidal waves", "Because foreign commercial airlines refused to land on the island", "Because all citizens voluntarily gave up their citizenship"],
     "The Sinhala Only Act excluded the Tamil minority, sparking ethnic alienation, militancy, and a devastating 26-year civil war."),
    ("Dual or Multiple Loyalties Legitimacy", "In a State-Nation framework, an individual's identification as simultaneously 'proudly Tamil' and 'proudly Indian' is viewed as:",
     "Mutually reinforcing and legitimate, rather than contradictory or disloyal to the nation",
     ["A treasonous criminal conspiracy punishable by military courts", "An impossibility that violates all mathematical laws of physics", "A temporary psychological illness that requires medical sedation"],
     "The State-Nation model normalizes multiple, complementary attachments: regional cultural pride and national civic allegiance coexist harmoniously."),
    ("Threat of Cultural Imperialism", "In cultural sociology, 'Cultural Imperialism' within a nation-state occurs when:",
     "The dominant majority community uses state power, public education, and state media to impose its language and customs on cultural minorities",
     ["A country imports foreign agricultural vegetables from overseas", "Citizens learn foreign computer programming languages in university", "Private companies advertise sports shoes on television"],
     "Cultural imperialism treats the majority culture as the only authentic national identity, relegating minorities to second-class status."),
    ("Federalism as a Diversity Safeguard", "Federalism in India (Article 1: 'India, that is Bharat, shall be a Union of States') acts as a diversity safeguard because:",
     "It decentralizes power, allowing regionally concentrated cultural and linguistic groups to govern themselves through elected state assemblies",
     ["It concentrates all executive decisions in the hands of a single appointed emperor", "It mandates that all citizens move to New Delhi permanently", "It eliminates all state borders and creates a military dictatorship"],
     "Federalism grants regional groups self-rule in their state while participating in shared-rule at the national center."),
    ("Civilian Nationalism vs Ethnic Nationalism", "How does 'Civic Nationalism' contrast with 'Ethnic Nationalism'?",
     "Civic nationalism defines the nation by adherence to constitutional values and democratic laws, while ethnic nationalism defines it by shared blood, race, or religion",
     ["Civic nationalism applies only to sports teams, while ethnic nationalism applies to commercial banks", "Civic nationalism bans all citizens from reading newspapers", "There is zero sociological difference between the two terms"],
     "Civic nationalism is inclusive and based on equal citizenship; ethnic nationalism is exclusionary, defining membership by ancestry or faith."),
    ("Assimilationist Pressure in Schools", "How do assimilationist education policies harm children from linguistic minority or tribal backgrounds?",
     "By imposing the dominant language as the sole medium of instruction, stigmatizing their mother tongues and causing high dropout rates",
     ["By giving all minority children free university doctoral scholarships", "By paying minority students a monthly salary in pure gold", "By teaching minority children ten foreign languages simultaneously"],
     "Monolingual schooling alienates minority children: failing to recognize their mother tongue causes cognitive loss and educational exclusion."),
    ("Multilingual Governance in Switzerland and India", "Both India and Switzerland demonstrate that a multilingual democracy survives by:",
     "Granting official recognition to multiple regional languages and conducting administrative business in the languages of the people",
     ["Forcing all citizens to communicate only in ancient sign languages", "Banning all printed books in regional dialects", "Requiring all parliamentary debates to be conducted in total silence"],
     "Institutional multilingualism enables democratic participation, proving that multiple languages do not threaten national unity."),
    ("The National Anthem and Pluralism", "Rabindranath Tagore's composition of *Jana Gana Mana* as India's National Anthem celebrates:",
     "The unity of India emerging through the harmonious symphony of its diverse provinces, regions, and rivers (Punjab, Sindh, Gujarat, Maratha, Dravida, Utkala, Banga)",
     ["A single dominant dialect spoken in a single village in northern India", "The commercial profits of a private colonial shipping company", "A military victory won by foreign colonial generals"],
     "Tagore's anthem is a geographic and cultural hymn to Indian pluralism, weaving distinct regions and peoples into a unified nation."),
    ("Democracy Deficit in Monocultural States", "Political sociologists note that modern democratic states that attempt to enforce a single monocultural identity inevitably suffer a 'Democracy Deficit' because:",
     "They must resort to censorship, police repression, and discriminatory laws to suppress natural cultural diversity",
     ["They become too wealthy and run out of space to store their money", "All citizens become professional Olympic athletes", "The state government dissolves itself voluntarily"],
     "Enforcing cultural uniformity requires coercion: authoritarian laws must suppress natural diversity, eroding democratic freedoms."),
    ("Secessionist Rebellions and Accommodation", "The historical resolution of violent insurgencies in Mizoram (1986 Accord) and Assam (Bodo Accords) proves that:",
     "Democratic negotiation, autonomous district councils, and constitutional power-sharing can transform former rebels into committed democratic leaders",
     ["Military violence is the only way to solve any human disagreement in society", "Autonomous councils are unconstitutional and illegal under international law", "All political accords must be approved by foreign monarchs"],
     "Political accommodation works: granting constitutional autonomy within the federal Union brought armed insurgencies into democratic governance."),
    ("The Dangers of Assimilation in Tribes", "Anthropologists warn that forced assimilation of small tribal communities into the mainstream often results in:",
     "'Deculturation'—the loss of their native language, traditional music, and ecological knowledge, leaving them as impoverished, demoralized wage laborers",
     ["Their transformation into billionaires owning international airlines", "Their immediate appointment as supreme commanders of naval fleets", "The complete elimination of all diseases from their bodies"],
     "Deculturation erases indigenous heritage without providing genuine socio-economic equality, leaving communities marginalized at the bottom."),
    ("Cultural Rights as Human Rights", "In contemporary international human rights jurisprudence, the protection of cultural and linguistic identity is recognized as:",
     "An essential component of basic human dignity, personal freedom, and non-discrimination",
     ["A luxury privilege granted only to wealthy citizens who pay extra taxes", "A criminal violation punishable under international maritime piracy laws", "A concept that applies strictly to non-human wildlife in national parks"],
     "Cultural rights are fundamental human rights: depriving a person of their mother tongue and heritage violates basic human dignity."),
    ("State-Nation Model in Spain and Canada", "In comparative global politics, which other democratic nations successfully utilize the 'State-Nation' approach to accommodate deep diversity?",
     "Canada (accommodating Francophone Quebec) and Spain (accommodating Catalonia and the Basque Country)",
     ["Monolingual Japan and Iceland exclusively", "Ancient city-states of medieval Europe", "Uninhabited desert islands in the Pacific Ocean"],
     "Canada and Spain, like India, practice state-nation accommodation, granting asymmetric federal autonomy to distinct cultural regions."),
    ("The Living Symphony of Indian Unity", "Sociologist M.N. Srinivas concluded that Indian national unity is best understood not as a rigid mechanical monolith, but as:",
     "A complex, living, pluralistic web of regional and cultural interdependencies held together by shared civilizational values and democratic constitutional faith",
     ["A single iron chain forged by a colonial military commander", "A random collection of unrelated warring tribes that have never met", "An imaginary illusion that does not exist in real life"],
     "Srinivas characterized Indian unity as an organic civilizational mosaic, strengthened by diversity rather than threatened by it.")
]
for itm in s30_extras:
    top, stem, corr, wrongs, sol = itm
    s30_raw.append(("mcq", top, stem, corr, wrongs, sol))
SLOT30 = build_slot(CH_DIV, s30_raw)

SLOTS_26_30 = {
    26: SLOT26,
    27: SLOT27,
    28: SLOT28,
    29: SLOT29,
    30: SLOT30
}

print("Slots 26 to 30 compiled successfully.")
