import sys, os
sys.path.insert(0, os.getcwd())
from scripts.subject_generators.slot_helpers import mcq, stmt, ar, match, seq

def build_slot(ch, items):
    res = []
    for itm in items:
        qtype = itm[0]
        if qtype == "mcq":
            _, top, stem, corr, wrongs, expl = itm
            res.append(mcq(ch, top, stem, corr, wrongs, expl))
        elif qtype == "stmt":
            _, top, s1, s2, rel, expl = itm
            res.append(stmt(ch, top, s1, s2, rel, expl))
        elif qtype == "ar":
            _, top, a, r, rel, expl = itm
            res.append(ar(ch, top, a, r, rel, expl))
        elif qtype == "match":
            _, top, stem, l1, l2, pair, expl = itm
            res.append(match(ch, top, stem, l1, l2, pair, expl))
        elif qtype == "seq":
            _, top, stem, items_list, order_str, expl = itm
            res.append(seq(ch, top, stem, items_list, order_str, expl))
    assert len(res) == 20, f"Slot has {len(res)} items instead of 20"
    return res

CH_RURAL = "Change and Development in Rural Society"
CH_INDUS = "Change and Development in Industrial Society"
CH_GLOB = "Globalisation and Social Change"
CH_MEDIA = "Mass Media and Communications"
CH_MOVEM = "Social Movements"

# Slot 36: Rural Society: Green Revolution, Regional Inequalities & Commercial Agriculture
s36_raw = [
    ("mcq", "Green Revolution Package", "The Green Revolution agricultural strategy introduced in the 1960s was based on a technological package consisting of:",
     "High Yielding Varieties (HYV) of seeds, chemical fertilizers, pesticides, and assured irrigation",
     ["Organic composting, wooden hand ploughs, and rain-fed dryland farming", "Mandatory collective state farming modeled on Soviet kolkhozes", "The complete abolition of chemical inputs and mechanised tractors"],
     "The Green Revolution was an input-intensive package combining HYV seeds, fertilizers, pesticides, and tube-well irrigation."),
    ("stmt", "Social Impact of Green Revolution",
     "The Green Revolution significantly increased national food grain production, helping India achieve food self-sufficiency.",
     "The Green Revolution eliminated all economic inequalities between rich farmers and marginal peasants in rural areas.", 3,
     "Statement I is correct; Statement II is incorrect because Green Revolution disproportionately enriched large farmers who could afford expensive inputs, widening rural inequalities."),
    ("ar", "Regional Disparity Green Revolution",
     "The first phase of the Green Revolution exacerbated inter-regional economic disparities in India.",
     "The modern agricultural package was deliberately concentrated in regions with assured irrigation such as Punjab, Haryana, and Western Uttar Pradesh.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Public subsidies and infrastructure targeted endowed irrigated zones, leaving dryland eastern and central India behind."),
    ("match", "Green Revolution Dimensions",
     "Match the agrarian phenomenon in List I with its sociological description in List II:",
     [("A", "HYV Seeds"), ("B", "Capital-intensive farming"), ("C", "Circulation of Labour"), ("D", "Ecological Degradation")],
     [("I", "Dwarf genetically engineered seeds requiring abundant water and chemical nutrients"),
      ("II", "Heavy financial investment in tube wells, tractors, and commercial fertilizers"),
      ("III", "Seasonal migration of farm workers from Bihar and UP to Punjab during harvest"),
      ("IV", "Depletion of water tables, soil salinity, and loss of indigenous crop biodiversity")],
     "A-I, B-II, C-III, D-IV",
     "HYV seeds require chemical inputs; capital-intensive farming relies on machinery; circulation of labour is seasonal migration; ecological degradation affects soils and water."),
    ("seq", "Agrarian Policy Timeline",
     "Arrange the following stages of agricultural and rural transformation in India in chronological order:",
     [("A", "Initial introduction of the Green Revolution package in Punjab and Haryana"),
      ("B", "Second phase of Green Revolution extending to dryland and rice-growing eastern regions"),
      ("C", "New agricultural policy under economic liberalisation exposing crops to global markets"),
      ("D", "Widespread reporting of farmers' distress and suicides in cash-crop belts")],
     "A, B, C, D",
     "Phase 1 Green Revolution (1960s), Phase 2 (1980s), Liberalisation of agriculture (1990s), Agrarian suicide crisis (late 1990s-2000s).")
]

s36_extras = [
    ("M.S. Swaminathan's Role", "Dr. M.S. Swaminathan is widely acclaimed in India's agricultural history as:",
     "The geneticist and father of the Green Revolution in India who collaborated with Norman Borlaug to introduce dwarf Mexican wheat varieties",
     ["The founder of the Indian Space Research Organisation (ISRO)", "The architect who designed the city of Chandigarh", "The author of the Constitution's Panchayati Raj amendment"],
     "Dr. M.S. Swaminathan spearheaded the scientific breeding and deployment of HYV wheat in India."),
    ("Ecological Fallout of HYV", "Which severe ecological crisis has emerged in Punjab and Haryana as a consequence of prolonged Green Revolution practices?",
     "Catastrophic depletion of the groundwater table due to excessive tube-well pumping and soil toxicity from over-fertilization",
     ["Encroachment of dense tropical rainforests over wheat fields", "The freezing over of all rivers into perpetual glaciers", "Complete disappearance of sunlight during winter months"],
     "Excessive tube-well irrigation and chemical usage caused steep water table declines and soil degradation."),
    ("Commercialisation of Farm Wages", "Following the Green Revolution, the mode of paying agricultural labourers shifted primarily from:",
     "Traditional payments in kind (shares of grain) to monetized daily cash wages",
     ["Payments in gold jewellery to free overseas holidays", "Payments in company stocks to shares in international airlines", "Payments in books of poetry to classical musical instruments"],
     "Green Revolution commercialized rural labour, replacing traditional grain shares with cash wages."),
    ("Circulation of Labour Concept", "What does sociologist Jan Breman mean by the 'circulation of labour' in Green Revolution agriculture?",
     "Poor migrant labourers from backward regions migrate seasonally to harvest crops and return home when work finishes, denied permanent roots",
     ["Farmers traveling around the globe to attend international academic conferences", "Factory workers trading places with government cabinet ministers every six months", "Village priests exchanging temples across different continents annually"],
     "Circulation of labour refers to the seasonal ebb and flow of impoverished migrant farm workers across states."),
    ("Market Dependence of Farmers", "A critical structural change brought by the Green Revolution is that farmers became dependent on the market for:",
     "Both agricultural inputs (commercial seeds, fertilizers, diesel) and the sale of agricultural output",
     ["Only sacred incense sticks and pilgrimage tickets", "Only imported luxury sports cars and designer suits", "None of these; farmers became 100% self-sufficient without touching money"],
     "Farmers transitioned from self-reliant subsistence inputs to complete market dependence for seeds, chemicals, power, and crop sales."),
    ("Reverse Tenancy Phenomenon", "In modern Green Revolution areas, 'reverse tenancy' refers to a trend where:",
     "Small and marginal farmers lease out their land to large, rich capitalist farmers who possess modern machinery and capital to cultivate large tracts",
     ["Wealthy landlords give up all their land to poor labourers as free gifts", "The government seizes all tractors and returns them to factory warehouses", "Tenant farmers evict their landlords and build shopping malls on farmland"],
     "In reverse tenancy, smallholders lease land to affluent commercial farmers who consolidate large operational holdings."),
    ("Loss of Indigenous Seed Varieties", "One major biodiversity impact of monoculture under the Green Revolution was:",
     "The replacement of thousands of native, drought-resistant indigenous seed varieties with a few uniform hybrid strains",
     ["The sudden multiplication of ten thousand new wild rice species", "The total disappearance of wheat and rice from Indian diet", "The transformation of all cereal crops into fruit-bearing mango trees"],
     "Monocropping HYV seeds marginalized diverse traditional indigenous varieties resilient to local pests and climate."),
    ("Agrarian Crisis and Debt Traps", "Why are farmers cultivating cash crops like Bt cotton in Vidarbha and Telangana particularly vulnerable to debt traps?",
     "Cash crop seeds and pesticides are very expensive; if rains fail or pest attacks occur, farmers face devastating losses that informal moneylenders exploit with exorbitant interest",
     ["Because cotton cannot be woven into cloth anywhere in the world", "Because the government pays cotton farmers in foreign currency that cannot be spent in India", "Because cotton plants absorb all gold particles from the soil"],
     "High input costs coupled with yield volatility or pest shocks force cash-crop farmers into catastrophic debt spirals."),
    ("Contract Farming Dynamics", "In contract farming, what is the typical relationship between multinational agribusiness corporations and small farmers?",
     "Corporations provide seeds and inputs and guarantee purchase at fixed prices, but pass the risks of crop failure and quality rejection onto farmers",
     ["Corporations transfer full ownership of the company to the village panchayat", "Small farmers receive free life-long air travel tickets without growing any crops", "The government bans all private companies from buying any agricultural produce"],
     "Agribusiness contracts tie farmers to strict corporate specifications, bearing all agricultural production risks."),
    ("Withdrawal of State Subsidies", "Under post-1991 economic liberalisation policies, rural agrarian distress was exacerbated by:",
     "Reduction in state fertilizer subsidies, cuts in public agricultural investment, and privatization of rural credit",
     ["The government tripling all rural pension payouts to farm labourers", "A state ban on all imports of foreign agricultural machinery", "The free distribution of imported diesel engines to every peasant"],
     "Structural adjustment shrank public agricultural extensions, bank credit, and input subsidies, leaving farmers to market vagaries."),
    ("Dominant Castes Economic Power", "How did the Green Revolution reinforce the socio-political power of dominant castes in states like Punjab, Haryana, and Maharashtra?",
     "Land-owning dominant castes (Jats, Marathas) accumulated surplus agrarian capital, dominating local politics, cooperatives, and rural enterprises",
     ["They abandoned all rural land and emigrated permanently to uninhabited islands", "They surrendered all their wealth to local agricultural labour unions", "They were legally stripped of their voting rights by state legislatures"],
     "Agrarian surpluses allowed dominant landholding castes to consolidate political power and control rural cooperative institutions."),
    ("Minimum Support Price (MSP)", "What is the primary policy purpose of the 'Minimum Support Price' (MSP) announced by the Government of India?",
     "To provide a price safety floor that protects farmers against distress sales in times of bumper harvest and market price crashes",
     ["To fix the maximum retail price of luxury sports cars in metropolitan cities", "To tax farmers 90% of their total agricultural income", "To prevent agricultural food grains from being consumed by humans"],
     "MSP guarantees a state-backed procurement benchmark, shielding farmers against drastic market collapses."),
    ("Kisan Sabhas and Agrarian Demands", "In the contemporary era, farmers' associations (like BKU) have shifted their primary protest demands towards:",
     "Remunerative crop prices, guaranteed MSP, debt waivers, affordable electricity, and reduction of input costs",
     ["The immediate restoration of British colonial zamindari rights", "The mandatory conversion of all farmland into commercial golf courses", "A total ban on the construction of rural roads and canals"],
     "Modern agrarian unions prioritize trade terms, price floors, power subsidies, and protection against corporate monopolies."),
    ("Gender Bias in Extension Services", "Sociologists note that agricultural extension programs and technological training in India predominantly suffer from:",
     "Gender bias, where training and credit are targeted exclusively at male heads of households despite women performing the majority of farm tasks",
     ["Total exclusion of all male farmers from government offices", "Mandatory requirement that only children under ten years manage tractors", "Banning the use of vernacular languages in all agricultural colleges"],
     "State agricultural extension programs routinely overlook women farmers, treating men as sole agricultural decision-makers."),
    ("Agrarian Stratification Deepening", "The overall long-term sociological impact of the Green Revolution on rural stratification has been:",
     "Deepening class differentiation between rich capital-accumulating farmers and a growing mass of land-poor or landless agricultural labourers",
     ["The total erasure of all class, caste, and income differences in Indian villages", "The complete elimination of the market economy in rural districts", "The return of self-contained, completely isolated barter communities"],
     "Capitalist commercial farming accentuated economic disparities and created sharp rural class polarization.")
]

SLOT36 = build_slot(CH_RURAL, list(s36_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s36_extras])

# Slot 37: Industrial Society: Organised/Unorganised Sector, Disinvestment & Labour Relations
s37_raw = [
    ("mcq", "Organised Sector Definition", "In the Indian economy, the 'Organised Sector' is characterized by which of the following features?",
     "Units registered with the government, employing ten or more workers using power, with statutory job security, fixed wages, and social security",
     ["Unregistered roadside stalls operating without written accounts or labour laws", "Farming plots cultivated entirely by family labour without wages", "Voluntary charities that pay workers purely with spiritual blessings"],
     "The organised sector consists of formally registered enterprises complying with labour legislations like the Factories Act."),
    ("stmt", "Informalisation of Labour",
     "Informalisation of labour refers to the trend where even formal/organised sector enterprises increasingly hire temporary contract workers without job security.",
     "Over 90% of India's total workforce is employed in the formal organised sector with full pension rights.", 3,
     "Statement I is correct; Statement II is incorrect because over 90% of India's workforce is actually in the unorganised/informal sector."),
    ("ar", "Disinvestment of PSUs",
     "Under economic liberalisation policies, the government initiated disinvestment in public sector enterprises.",
     "Disinvestment involves the government selling its equity shares in state-owned enterprises to private investors and corporations.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Disinvestment reduces state equity to mobilize funds and promote private management."),
    ("match", "Industrial Concepts",
     "Match the industrial term in List I with its sociological description in List II:",
     [("A", "Taylorism / Scientific Management"), ("B", "Outsourcing"), ("C", "Lockout"), ("D", "Informalisation")],
     [("I", "Breaking work into timed, standardized minute tasks to maximize managerial control"),
      ("II", "Contracting out business operations and services to third-party external suppliers"),
      ("III", "Temporary closure of a workplace by the employer during an industrial dispute"),
      ("IV", "Growing proportion of employment lacking formal contracts, benefits, and protection")],
     "A-I, B-II, C-III, D-IV",
     "Taylorism standardizes minute work steps; Outsourcing contracts out services; Lockout is employer workplace closure; Informalisation is casualisation of labour."),
    ("seq", "Industrial Milestones in India",
     "Arrange the following industrial and labour developments in India in chronological order:",
     [("A", "Establishment of the first cotton textile mill in Bombay"),
      ("B", "Enactment of the Factories Act setting standard working hours and safety standards"),
      ("C", "The historic Bombay Textile Strike led by Dr. Datta Samant"),
      ("D", "Adoption of Voluntary Retirement Schemes (VRS) and industrial disinvestment post-1991")],
     "A, B, C, D",
     "First Bombay mill (1854), Factories Act (1948), Bombay Textile Strike (1982), Disinvestment and VRS (post-1991).")
]

s37_extras = [
    ("Unorganised Sector Share", "Approximately what proportion of India's total workforce is engaged in the unorganised or informal sector?",
     "Over 90%",
     ["Less than 10%", "Exactly 25%", "Around 40%"],
     "Over 90% of the Indian labour force works in informal agriculture, construction, petty trade, and unrecorded enterprises."),
    ("Voluntary Retirement Scheme (VRS)", "During industrial restructuring and public sector disinvestment, what was the 'Golden Handshake' or Voluntary Retirement Scheme (VRS)?",
     "A financial package offered to employees to induce them to retire voluntarily and reduce workforce size without formal retrenchment",
     ["A gold medal presented to all employees upon completing fifty years of service", "A mandatory transfer of factory workers to diplomatic embassies abroad", "A government grant to purchase personal airplanes for factory managers"],
     "VRS provided monetary severance to downsize workforces in privatizing or restructuring enterprises."),
    ("Bombay Textile Strike (1982)", "What was the long-term sociological outcome of the Great Bombay Textile Strike of 1982 involving nearly 2.5 lakh mill workers?",
     "The mills closed or relocated, trade union power was crushed, and vast mill lands were privatized into luxury malls and skyscrapers",
     ["The government nationalized all cotton fields across the globe", "All textile mill workers were appointed as senior directors of the Reserve Bank of India", "Bombay became a 100% agrarian village with zero modern buildings"],
     "The collapse of the strike devastated the working-class culture of Girangaon and paved the way for speculative real estate redevelopment."),
    ("Taylorism and Alienation", "Sociologist Karl Marx and later labour theorists argued that Frederick Winslow Taylor's 'Scientific Management' (Taylorism):",
     "Separates conception from execution, de-skilling workers and increasing alienation by turning human beings into mechanical cogs",
     ["Empowers factory workers to decide corporate profit dividends independently", "Allows every factory worker to work from home on flexible hours", "Eliminates all differences between capital owners and manual labourers"],
     "Taylorism timed work with stopwatches, stripping autonomy from workers and concentrating control in managerial hands."),
    ("Outsourcing and Call Centres", "Why did India become a major global destination for Business Process Outsourcing (BPO) and call centres post-1990s?",
     "Availability of a large pool of English-speaking educated youth willing to work at lower wages across differing time zones",
     ["A constitutional mandate requiring all foreign companies to relocate to New Delhi", "The complete absence of computers and telecommunications in Western nations", "Indian call centres being operated entirely by automated mechanical robots"],
     "Low labor costs, English fluency, and time-zone differences made India an IT and BPO services hub."),
    ("Night Shifts and Social Isolation", "Sociological studies of young workers in IT and BPO call centres reveal that working graveyard/night shifts frequently leads to:",
     "Social disruption of family life, altered biological sleep cycles, burnout, and emotional estrangement from traditional social networks",
     ["Total immunity from all physical illnesses and stress", "An automatic lifetime government pension after two years of work", "Universal ownership of private luxury residential villas"],
     "Working inverted night hours disrupts domestic routines, circadian rhythms, and community ties."),
    ("Contractualisation of Labour", "What is the primary reason why modern private corporations prefer employing contract labour over permanent workers?",
     "Contract workers can be hired and fired flexibly according to demand, without providing lifetime pensions, health insurance, or severance pay",
     ["Contract workers are legally required to own 50% of the company's equity shares", "Permanent workers are strictly prohibited from entering factory premises", "Contract workers receive ten times the salary of permanent executive directors"],
     "Contractualisation reduces employer overheads, evades labour unions, and allows easy retrenchment during downturns."),
    ("Working Conditions in Home-Based Work", "In informal home-based industries like bidi rolling, agarbatti making, and zari embroidery, workers:",
     "Work long hours for piece-rate wages in cramped domestic spaces without health benefits, frequently involving women and child labour",
     ["Receive fully paid annual sick leave and free five-star dining", "Are provided company cars and air-conditioned luxury penthouses", "Are required to work only thirty minutes per week by national law"],
     "Home-based piece-rate workers suffer low earnings, lack of occupational safety, and physical exploitation in domestic settings."),
    ("Mines and Occupational Safety", "What are the major occupational hazards faced by workers in unorganised mining sectors (such as coal 'rat-hole' mining in Meghalaya)?",
     "Mine cave-ins, asphyxiation from toxic gases, chronic respiratory silicosis, and complete absence of emergency safety equipment",
     ["Excessive exposure to freezing polar blizzards and icebergs", "Overeating of nutritious food provided by mining executives", "Severe sunburn while operating deep underwater submarines"],
     "Informal mining involves lethal safety risks, poisonous fumes, roof collapses, and severe occupational lung diseases."),
    ("Role of Trade Unions Post-1991", "In the post-liberalisation era, traditional trade unions in India have generally witnessed:",
     "A decline in bargaining power due to privatization, casualisation of labour, subcontracting, and hostile state regulatory policies",
     ["A massive increase in membership covering 100% of all agricultural labourers", "Total control over the appointment of Supreme Court judges and prime ministers", "A complete replacement of private corporate boards with workers' soviets"],
     "Liberalisation weakened organised labour through casualisation, plant relocations, and legal curbs on strikes."),
    ("Hawkers and Urban Space", "The struggle of urban street hawkers and vendors to earn a livelihood frequently brings them into conflict with:",
     "Municipal corporations and police who treat them as illegal encroachments on public pavements",
     ["International space research agencies launching communication satellites", "Rural agricultural farmers demanding their immediate return to wheat fields", "High-seas fishing trawlers operating in the Indian Ocean"],
     "Urban street vendors face daily eviction drives, harassment, and extortion due to lack of formal vending rights."),
    ("Special Economic Zones (SEZs) Labour Laws", "Governments promote Special Economic Zones (SEZs) by offering multinational companies:",
     "Tax exemptions, world-class infrastructure, and relaxed or non-enforced labour regulations and public utility strike prohibitions",
     ["Mandatory 100% worker control over all corporate executive boards", "Doubling of statutory minimum wages every six months", "Permanent lifetime government housing for every manual worker"],
     "SEZs attract capital by offering tax holidays, infrastructure subsidies, and restrictions on trade union activity."),
    ("Emotional Labour in Service Sector", "Sociologist Arlie Hochschild coined the term 'Emotional Labour' (visible in air hostesses and call-centre agents) to describe:",
     "The requirement for workers to manage, manipulate, and display specific emotions (smiling, pleasantness, deference) as part of their paid job",
     ["Physical weightlifting performed by construction workers on scaffolding", "Mathematical computations performed by aerospace engineers using slide rules", "The physical repair of diesel railway locomotive engines"],
     "Service jobs commodify personal feelings, demanding continuous emotional cheerfulness and customer deference."),
    ("Gender Wage Gap in Industry", "Across both organized and unorganized industrial sectors in India, empirical data consistently demonstrates:",
     "A persistent gender wage gap where women workers are paid significantly lower wages than men for identical or comparable tasks",
     ["Women workers receiving double the pay of their male counterparts in every factory", "The total absence of any male workers in the manufacturing sector", "Statutory laws requiring male workers to surrender all earnings to female colleagues"],
     "Women face pervasive wage discrimination and are pigeonholed into lower-paid, informal, and precarious jobs."),
    ("Gig Economy and App-Based Work", "In the contemporary 'Gig Economy' (app-based delivery and ride services), workers are categorized as 'independent partners', which legally means:",
     "Companies evade traditional employer obligations such as minimum wage laws, provident fund contributions, and health insurance",
     ["Workers receive lifetime pension packages backed by the central bank", "Workers own equal shares in the global multinational software corporation", "Workers are prohibited from using mobile smartphones or electronic navigation"],
     "Platform companies designate gig workers as independent contractors to shed statutory responsibilities for healthcare and pensions.")
]

SLOT37 = build_slot(CH_INDUS, list(s37_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s37_extras])

# Slot 38: Globalisation and Social Change: Economic Liberalisation & Cultural Consumption
s38_raw = [
    ("mcq", "Globalisation Definition", "In sociological terms, 'Globalisation' is best understood as:",
     "The growing interdependence and interconnectedness of world economies, cultures, technologies, and populations across national borders",
     ["The complete isolation of all nation-states behind impenetrable fortified concrete walls", "The permanent cancellation of all international trade and communication networks", "A mandatory treaty requiring all humans to live in a single designated desert city"],
     "Globalisation involves the worldwide compression of time and space, linking distant localities through capital, culture, and information."),
    ("stmt", "Globalisation and Culture",
     "Cultural homogenization refers to the spread of a standardized, commercially driven global culture (often associated with Americanisation or Western consumerism).",
     "Cultural heterogenization/glocalisation refers to the process where global cultural products are creatively adapted, hybridized, and infused with local meanings.", 1,
     "Both Statement I and Statement II are correct. Globalisation produces both standardized global consumer culture and vibrant local hybridizations (glocalisation)."),
    ("ar", "Economic Liberalisation 1991",
     "In 1991, India initiated comprehensive New Economic Policies of Liberalisation, Privatisation, and Globalisation (LPG).",
     "India faced an unprecedented balance of payments crisis and complied with structural adjustment conditionalities of the IMF and World Bank.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). The 1991 foreign exchange crisis led India to dismantle the 'Licence Raj' and liberalize."),
    ("match", "Globalisation Dimensions",
     "Match the globalisation concept in List I with its sociological description in List II:",
     [("A", "Transnational Corporation (TNC)"), ("B", "Glocalisation"), ("C", "Consumerism"), ("D", "Digital Divide")],
     [("I", "Corporation operating across multiple sovereign national territories with global supply chains"),
      ("II", "Intersection and mutual adaptation of global cultural forms with local traditions"),
      ("III", "Cultural ideology equating personal happiness and self-worth with the purchase of commodities"),
      ("IV", "Inequality in access to information and communication technologies between classes and regions")],
     "A-I, B-II, C-III, D-IV",
     "TNC operates internationally; Glocalisation is local adaptation; Consumerism equates worth with purchases; Digital divide is technological inequality."),
    ("seq", "Global Integration Timeline",
     "Arrange the following milestones in India's global economic and technological integration in chronological order:",
     [("A", "Establishment of the World Trade Organization (WTO) with India as a founding member"),
      ("B", "Launch of private satellite television broadcasting and foreign channels in India"),
      ("C", "Abolition of industrial licensing and reduction of import tariffs under New Economic Policy"),
      ("D", "Explosive rollout of low-cost 4G mobile broadband and national digital payments (UPI)")],
     "C, B, A, D",
     "Industrial de-licensing (1991), Satellite TV boom (early 1990s), WTO establishment (1995), 4G/UPI revolution (2016 onwards).")
]

s38_extras = [
    ("Culture of Consumption", "Sociologists argue that under globalisation, a 'Culture of Consumption' has emerged in urban India, where:",
     "Identity, social status, and lifestyle are increasingly signaled through brand-name commodities, fashion, shopping malls, and leisure spending",
     ["Individuals abandon all private possessions and live in community monasteries", "All retail shops are banned from selling clothing and packaged food", "Families refuse to purchase any goods manufactured outside their village"],
     "Global consumerism elevates lifestyle consumption, shopping malls, and branded commodities as primary markers of social prestige."),
    ("Glocalisation in Food Culture", "Which of the following is a classic culinary example of 'Glocalisation' in contemporary India?",
     "Global fast-food chains introducing vegetarian McAloo Tikki burgers and paneer pizzas tailored to Indian dietary preferences",
     ["A law prohibiting the import of any foreign spices or vegetables", "The replacement of all Indian wheat with freeze-dried Arctic lichen", "A ban on cooking food using heat or firewood"],
     "Glocalisation modifies global commercial products (McDonald's, Domino's) to align with local taste profiles and religious food taboos."),
    ("Electronic Economy and Capital Flows", "In the globalisation literature, the 'Electronic Economy' refers to:",
     "The instantaneous movement of trillions of dollars of financial capital across international borders via computer networks at the touch of a button",
     ["Manufacturing mechanical pocket watches inside water mills", "Printing currency notes exclusively using wooden printing presses", "Trading physical cowrie shells on coastal fishing beaches"],
     "Electronic finance enables instant speculative capital transfers around the globe, creating hyper-fluid global markets."),
    ("Transnational Corporations Power", "Transnational Corporations (TNCs) differ from traditional domestic companies primarily because:",
     "They locate design, raw material sourcing, manufacturing, and marketing across several different countries to minimize costs and maximize profits",
     ["They are owned entirely by the United Nations General Assembly", "They are legally forbidden from selling products outside their home town", "They operate without the use of money or written contracts"],
     "TNCs disperse specialized production stages globally to leverage cheap labor, raw materials, and favorable tax regimes."),
    ("Knowledge Economy Concept", "In a 'Knowledge Economy', the primary source of economic wealth and productivity shifts from:",
     "Physical manufacturing and manual agriculture to information, software, intellectual property, and high-tech innovation",
     ["Gold mining and coal extraction to subsistence bullock cart transport", "Handmade pottery and basket weaving to stone-tool chipping", "The breeding of carrier pigeons to manual letter delivery"],
     "A knowledge economy values intellectual capital, software algorithms, and scientific research over physical industrial labour."),
    ("Digital Divide in India", "In Indian society, the 'Digital Divide' is evident in the stark disparities in ICT access between:",
     "Urban educated affluent classes and poor, rural, lower-caste, or female populations lacking devices and digital literacy",
     ["Those who prefer listening to the radio and those who prefer reading poetry", "People who own dogs and people who own cats in metropolitan cities", "Train passengers traveling in sleeper class versus general unreserved coaches"],
     "Inequalities in internet access, device ownership, and digital literacy mirror and reinforce existing socio-economic fault lines."),
    ("Cultural Hybridity Example", "Indipop, fusion cuisine, and 'Hinglish' advertising slogans (e.g., 'Yeh Dil Maange More') are sociological examples of:",
     "Cultural Hybridity, where global styles merge with indigenous languages and cultural motifs",
     ["The complete destruction of all indigenous Indian languages", "The total rejection of any Western cultural influence whatsoever", "A secret military cipher code used during international conflict"],
     "Hybridity blends local and global cultural idioms, creating innovative commercial and linguistic forms."),
    ("Corporate Media Consolidation", "What is a major sociological concern regarding the globalisation of mass media?",
     "A small handful of giant transnational corporate conglomerates control global news, films, and music, threatening cultural diversity",
     ["Every single citizen now owns their own satellite broadcasting television station", "Governments have completely banned all books, newspapers, and cinema", "All global news is written exclusively in ancient Latin"],
     "Media oligopolies concentrate narrative power, promoting corporate consumerism and marginalizing non-commercial voices."),
    ("Globalisation and Indigenous Knowledge", "The patenting of indigenous Indian medicinal plants (like neem and turmeric) by foreign corporations was criticized as:",
     "'Biopiracy' — the unauthorized commercial expropriation of traditional collective community knowledge by multinational patents",
     ["A charitable donation to preserve ancient Ayurvedic scriptures", "A scientific project to relocate all neem trees to North America", "A United Nations initiative to eradicate all medicinal herbs"],
     "Biopiracy involves corporations privatizing age-old communal biological knowledge without compensation."),
    ("Time-Space Compression (Harvey)", "Geographer David Harvey's concept of 'Time-Space Compression' explains how globalisation:",
     "Shrinks physical distances and accelerates the pace of social life through high-speed telecommunications, jet aviation, and digital networks",
     ["Physically causes the earth's tectonic plates to collide into a single supercontinent", "Slows down time so that a single day feels like ten years", "Eliminates the four seasons and creates perpetual autumn globally"],
     "Time-space compression highlights how modern transport and digital media annihilate spatial and temporal barriers."),
    ("Disinvestment and Public Services", "How has economic globalisation impacted public welfare provisioning (healthcare, higher education) in India?",
     "Led to rising commercialisation, privatization, and user fees, making quality healthcare and education harder for the poor to afford",
     ["Resulted in 100% free private university education for every citizen in India", "Abolished all private hospitals in favor of village herbal medicine centres", "Eliminated all differences between public and private medical facilities"],
     "Neoliberal policies rolled back state social spending, fostering expensive corporate hospitals and commercial colleges."),
    ("Globalisation and National Sovereignty", "Political sociologists point out that economic globalisation constraints national sovereignty because:",
     "National economic policies must conform to the regulations, credit ratings, and trade mandates of global bodies like the WTO and IMF",
     ["Nations are forced to dissolve their national parliaments and armies", "All national borders have been officially erased from world maps", "Presidents and prime ministers are appointed by international corporate CEOs"],
     "Global financial surveillance and multilateral trade pacts restrict the autonomy of nation-states to implement protectionist policies."),
    ("Diaspora and Long-Distance Nationalism", "The Indian diaspora in North America and Europe connects with their homeland through:",
     "Transnational remittances, cultural philanthropy, participation in overseas community bodies, and digital political mobilization",
     ["Permanently severing all communication and legal ties with family in India", "Refusing to allow any Indian cultural films to be screened abroad", "Surrendering their ancestral property to foreign municipal councils"],
     "Global communication links diaspora communities intimately with homeland cultural politics and religious institutions."),
    ("Feminisation of Global Labour", "In the global manufacturing supply chain (garment export factories, electronics assembly), employers favor young women because:",
     "They are stereotyped as docile, nimble-fingered, less likely to unionize, and willing to accept lower piece-rate wages",
     ["They are legally appointed as the permanent chief executives of the corporations", "They receive double the overtime pay of male industrial workers", "They are exempt from all managerial oversight and working hour regulations"],
     "Global assembly lines exploit patriarchal gender norms to extract cheap, flexible, and non-unionized female labor."),
    ("Resistance to Globalisation", "The World Social Forum (WSF) and anti-globalisation movements mobilize around the rallying slogan:",
     "'Another World is Possible' — opposing neoliberal corporate globalisation and demanding social justice, ecological sustainability, and fair trade",
     ["'Let Giant Corporations Rule the Entire Planet'", "'Abolish All Schools and Return to Stone-Age Hunting'", "'Ban All Forms of Renewable Wind and Solar Energy'"],
     "The WSF unites grassroots unions, indigenous groups, and environmentalists against neoliberal deregulation and corporate hegemony.")
]

SLOT38 = build_slot(CH_GLOB, list(s38_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s38_extras])

# Slot 39: Mass Media and Communications: Print, Radio, Television & Digital Media
s39_raw = [
    ("mcq", "Print Capitalism (Anderson)", "Benedict Anderson famously argued in 'Imagined Communities' that which modern development was foundational for the rise of national consciousness?",
     "Print Capitalism — the mass publication of books and daily newspapers in standardized vernacular languages",
     ["The construction of high-speed magnetic levitation trains", "The invention of steam-powered textile weaving looms", "The creation of international private commercial banks"],
     "Anderson argued that mass vernacular print media allowed widely dispersed citizens to imagine themselves as a single national community."),
    ("stmt", "Growth of Indian Print Media",
     "While newspaper circulations have sharply declined in the West, the Indian regional vernacular press experienced explosive growth since the 1980s.",
     "The growth of vernacular newspapers in India was driven by rising rural literacy, local political awareness, and tailored regional reporting.", 1,
     "Both Statement I and Statement II are correct. Vernacular dailies boomed in India due to rural literacy, decentralised editions, and local news coverage."),
    ("ar", "Television Boom Post-1991",
     "Prior to 1991, television broadcasting in India was a state monopoly operated exclusively through Doordarshan.",
     "The economic liberalisation and satellite telecommunications revolution of the 1990s allowed private commercial cable and satellite television channels to enter the market.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Private satellite channels ended the state monopoly, dramatically transforming Indian media."),
    ("match", "Mass Media Forms & Pioneers",
     "Match the mass media milestone in List I with its pioneer/feature in List II:",
     [("A", "First Indian Printed Newspaper"), ("B", "Father of Indian Cinema"), ("C", "All India Radio (AIR)"), ("D", "Doordarshan")],
     [("I", "Hicky's Bengal Gazette (1780)"),
      ("II", "Dadasaheb Phalke (Raja Harishchandra, 1913)"),
      ("III", "Akashvani — state public radio broadcasting network"),
      ("IV", "State public television network launched experimentally in Delhi (1959)")],
     "A-I, B-II, C-III, D-IV",
     "Hicky's Bengal Gazette was first newspaper; Dadasaheb Phalke pioneered cinema; Akashvani is AIR; Doordarshan was state TV."),
    ("seq", "Mass Media Evolution Timeline",
     "Arrange the following milestones in Indian mass communications in chronological order:",
     [("A", "Publication of James Augustus Hicky's 'Bengal Gazette' in Calcutta"),
      ("B", "Release of India's first full-length indigenous silent feature film 'Raja Harishchandra'"),
      ("C", "Introduction of nationwide colour television broadcasting during the Asian Games in Delhi"),
      ("D", "Commercial launch of private 24-hour satellite news networks in India")],
     "A, B, C, D",
     "Bengal Gazette (1780), Raja Harishchandra (1913), Colour TV / Asian Games (1982), Satellite 24-hr news (1990s).")
]

s39_extras = [
    ("Vernacular Press Act 1878", "The Vernacular Press Act was enacted in 1878 by Viceroy Lord Lytton primarily to:",
     "Gag and suppress indigenous language newspapers that criticized British colonial administrative and famine policies",
     ["Provide free printing presses and imported paper to Indian journalists", "Mandate that all newspapers must be printed in Urdu calligraphy", "Translate Shakespeare's plays into all regional Indian dialects"],
     "Lord Lytton passed the notorious 'Gagging Act' to silence nationalist criticism in vernacular periodicals."),
    ("SITE Experiment 1975-76", "What was the landmark educational initiative known as the 'Satellite Instructional Television Experiment' (SITE) in India?",
     "Using NASA's ATS-6 satellite to broadcast developmental, agricultural, and educational programs directly to 2,400 rural villages",
     ["A commercial cable network broadcasting Hollywood movies to metropolitan elites", "A military space mission to photograph lunar craters", "An experimental radio broadcast transmitting classical Carnatic music to Europe"],
     "SITE demonstrated the potential of satellite television for mass rural literacy, farming knowledge, and national development."),
    ("Radio as Development Tool", "In post-independence India, All India Radio's 'Vividh Bharati' service was launched in 1957 primarily to:",
     "Compete with Radio Ceylon by providing popular film music alongside national public service announcements",
     ["Broadcast top-secret diplomatic dispatches to foreign embassies", "Transmit weather warnings solely to high-altitude mountain climbers", "Provide live stock market price quotations for London traders"],
     "Vividh Bharati won back listeners from Radio Ceylon by broadcasting Hindi film songs, skits, and public messages."),
    ("Infotainment Phenomenon", "In modern commercial television news, the concept of 'Infotainment' refers to:",
     "The blending of hard investigative news reporting with sensational entertainment, celebrity trivia, melodrama, and spectacle to boost TRP ratings",
     ["Pure mathematical scientific lectures broadcast without visual images", "A complete ban on all commercial advertisements on news channels", "Broadcasting parliamentary debates in ancient Classical Greek"],
     "Infotainment prioritizes drama, crime, astrologers, and celebrity gossip over substantive policy reporting to capture viewership."),
    ("Target Rating Point (TRP)", "In commercial television broadcasting, what does 'TRP' stand for and why is it crucial for media channels?",
     "Target Rating Point, which measures program viewership numbers used by corporate advertisers to allocate lucrative commercial advertising revenue",
     ["Total Radio Power, measuring the wattage of high-frequency transmission towers", "Technological Relay Protocol, controlling satellite transponder orbital trajectories", "Trade Registry Permit, granting legal permission to construct cinema multiplexes"],
     "TRPs quantify audiences, dictating ad pricing and driving sensationalist programming."),
    ("Citizen Journalism", "What is 'Citizen Journalism' enabled by smartphones and internet social media platforms?",
     "Ordinary citizens recording, reporting, and disseminating news, injustice, or events directly to the public without traditional media gatekeepers",
     ["Professional journalists who have been appointed as lifetime members of parliament", "A government department that inspects private diaries of citizens", "Newspaper printing press technicians operating heavy rotary machinery"],
     "Smartphones allow ordinary people to document and publish real-time news, bypassing corporate editorial filters."),
    ("Digital Divide in Media", "How does the digital shift in mass media impact rural and marginal communities in India?",
     "While mobile internet access has expanded rapidly, quality digital news literacy and high-speed infrastructure remain skewed towards urban, affluent populations",
     ["It has completely eradicated all poverty and illiteracy in every rural district", "It has forced all rural citizens to stop speaking their native languages", "It has made traditional folk music illegal across all states"],
     "The digital divide persists in speed, device quality, and the ability to critically navigate online misinformation."),
    ("Print Media Boom in Hindi Heartland", "Sociologist Robin Jeffrey attributed the phenomenal boom of Hindi dailies (e.g., Dainik Jagran, Dainik Bhaskar) to:",
     "Decentralised local editions, hyper-local news coverage, aggressive doorstep distribution, and tailored consumer advertising",
     ["Translating British newspapers verbatim without mentioning any Indian events", "Distributing free televisions with every five copies of the newspaper", "Operating printing presses without using any human workers or ink"],
     "Robin Jeffrey showed that localized regional reporting and rural literacy spurred explosive print readership in India."),
    ("Media Convergence", "In communications theory, 'Media Convergence' describes:",
     "The merging of previously distinct media technologies (print, radio, television, telephone) into unified digital platforms accessible on smartphones and computers",
     ["The physical collision of two television transmission towers during storms", "A legal mandate forbidding journalists from writing for more than one newspaper", "The total replacement of all written alphabets with pictorial hieroglyphics"],
     "Convergence unites text, audio, video, and social interaction onto single digital devices."),
    ("Sensationalism and Trial by Media", "The phrase 'Trial by Media' refers to an ethical crisis where:",
     "Television channels and news portals conduct aggressive parallel investigations, declaring an accused guilty before a court of law delivers its verdict",
     ["Judges conduct formal criminal trials inside commercial television studios", "Accused prisoners are allowed to vote on the guilt of other prisoners", "Courts ban all journalists from entering judicial buildings permanently"],
     "Media trials jeopardize due process, creating public hysteria and prejudicing fair judicial outcomes."),
    ("Censorship during Emergency (1975-77)", "During the Internal Emergency (1975-1977), how did the Indian state control mass media?",
     "Imposed strict pre-censorship on newspapers, stationed government censors in newsrooms, and cut electricity to defiant printing presses",
     ["Purchased all private printing presses and distributed free gold to reporters", "Banned the use of the English language across all radio broadcasts", "Forced journalists to broadcast only international football matches"],
     "The Emergency saw draconian press censorship, forcing newspapers like The Indian Express to leave editorial columns blank in protest."),
    ("Social Media and Public Sphere (Habermas)", "Jürgen Habermas conceptualized the 'Public Sphere' as an open democratic space for rational public debate; contemporary sociologists note that social media:",
     "Offers democratic voice to marginalized groups, but simultaneously creates polarized echo chambers, hate speech, and viral disinformation",
     ["Guarantees 100% truthful, factual, and scientifically verified information globally", "Completely eliminates all disagreements between differing political ideologies", "Prevents private corporations from advertising consumer products"],
     "Social media expands grassroots participation but facilitates algorithmic polarization and fake news."),
    ("Soap Operas and Cultural Norms", "Sociological studies of televised daily soap operas (e.g., 'Kyunki Saas Bhi Kabhi Bahu Thi') showed that they:",
     "Popularized consumerist lifestyles, opulent domestic aesthetics, and traditional patriarchies, while also sparking family discussions on female agency",
     ["Forced all viewers to abandon their homes and move into mud huts", "Taught viewers how to construct nuclear power generators at home", "Caused the total collapse of all wedding ceremonies in India"],
     "Mega-soaps constructed homogenized images of affluent joint families, shaping consumer aspirations and gender ideals."),
    ("Community Radio Role", "Community Radio Stations in rural India play a vital democratic role because they:",
     "Broadcast in local dialects, addressing hyper-local farming concerns, health awareness, and folk music managed by the community itself",
     ["Broadcast commercial Hollywood film soundtracks twenty-four hours a day", "Compete with international Wall Street financial news channels", "Are owned and operated exclusively by multinational corporate investors"],
     "Community radio empowers local communities to voice grassroots problems in their own dialects."),
    ("Algorithmization of News", "On modern digital platforms, the 'algorithmization of news' means:",
     "Automated computer algorithms curate and feed users content designed to maximize engagement and outrage, trapping users in filter bubbles",
     ["A committee of retired historians manually inspects every social media post", "All news stories are translated into computer programming source code", "News can only be published once every seven years by law"],
     "Algorithmic curation amplifies emotionally charged content, reinforcing cognitive biases and creating polarized echo chambers.")
]

SLOT39 = build_slot(CH_MEDIA, list(s39_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s39_extras])

# Slot 40: Social Movements: Theory, Peasant, Chipko, Dalit & Women's Movements
s40_raw = [
    ("mcq", "Social Movement Definition", "In sociological theory, a 'Social Movement' is defined by which key characteristics?",
     "Sustained collective mobilization, shared ideology, clear organizational leadership, and an orientation towards social change or resistance",
     ["A spontaneous, disorganized riot that disperses within twenty minutes without goals", "A government bureau passing routine administrative circulars from an office", "A corporate marketing campaign to sell commercial toothpastes"],
     "Social movements require sustained collective action, organisational structure, shared ideology, and a program for change."),
    ("stmt", "Old vs New Social Movements",
     "Old social movements (like early trade union and peasant struggles) focused primarily on economic redistribution and capturing state power.",
     "New social movements (environmental, feminist, civil rights) emphasize quality of life, identity, human rights, and social justice beyond mere class.", 1,
     "Both Statement I and Statement II are correct. Sociologists contrast material/class-based Old movements with identity/rights-based New movements."),
    ("ar", "Chipko Movement Significance",
     "The Chipko movement in Uttarakhand was an ecological movement as well as a women's movement for survival.",
     "Rural women depended directly on forest resources for fodder, fuel, and water, and physically hugged trees to prevent commercial logging.", 1,
     "Both (A) and (R) are true, and (R) correctly explains (A). Chipko linked ecological protection directly to women's everyday livelihood sustenance."),
    ("match", "Social Movements & Leaders",
     "Match the social movement in List I with its prominent leader/organization in List II:",
     [("A", "Chipko Movement"), ("B", "Narmada Bachao Andolan"), ("C", "Dalit Panthers"), ("D", "Bhartiya Kisan Union (BKU)")],
     [("I", "Sundarlal Bahuguna / Gaura Devi"),
      ("II", "Medha Patkar / Baba Amte"),
      ("III", "Namdeo Dhasal / J.V. Pawar"),
      ("IV", "Mahendra Singh Tikait")],
     "A-I, B-II, C-III, D-IV",
     "Chipko led by Bahuguna/Gaura Devi; NBA led by Medha Patkar; Dalit Panthers founded by Namdeo Dhasal; BKU led by Mahendra Singh Tikait."),
    ("seq", "Social Movement Timeline",
     "Arrange the following landmark social and ecological movements in India in chronological order:",
     [("A", "Tebhaga Peasant Movement in Bengal demanding two-thirds crop share"),
      ("B", "Chipko Movement in the Garhwal Himalayas hugging trees against commercial felling"),
      ("C", "Formation of the Dalit Panthers in Maharashtra inspired by Black Panthers"),
      ("D", "Launch of the Narmada Bachao Andolan opposing large dam submergence")],
     "A, B, C, D",
     "Tebhaga (1946-47), Chipko (1973), Dalit Panthers (1972), Narmada Bachao Andolan (mid-1980s).")
]

s40_extras = [
    ("Types of Social Movements", "Sociologists classify social movements into Reformist, Redemptive, and Revolutionary. A 'Revolutionary Movement' aims to:",
     "Completely overthrow existing state power and radically restructure fundamental social, economic, and political institutions",
     ["Encourage individuals to change their personal religious meditation habits", "Make minor, gradual improvements to existing municipal traffic bylaws", "Distribute free school bags to kindergarten students annually"],
     "Revolutionary movements (e.g., French Revolution, Naxalbari uprising) seek total structural transformation of society and the state."),
    ("Redemptive Social Movements", "A 'Redemptive' or Transformative social movement (such as certain religious revival movements) focuses on:",
     "Transforming the inner consciousness, moral character, and spiritual habits of individual members rather than changing external state laws",
     ["Capturing the national defense ministry through armed guerrilla warfare", "Constructing national highways connecting commercial seaports", "Imposing import tariffs on foreign manufactured industrial machinery"],
     "Redemptive movements target personal inner renewal and lifestyle reform among followers."),
    ("Reformist Social Movements", "A 'Reformist Movement' (such as the Right to Information movement or campaigns for reservations) seeks to:",
     "Change specific laws, social practices, or institutional policies within the existing constitutional and democratic framework",
     ["Completely abolish all courts, parliaments, and police departments", "Establish a hereditary feudal dynasty under a military general", "Force all citizens to abandon modern cities and live in caves"],
     "Reformist movements work within existing legal systems to modify specific practices and expand rights."),
    ("Relative Deprivation Theory", "In the sociological study of social movements, 'Relative Deprivation' theory posits that people mobilize when:",
     "They perceive a painful gap between what they believe they legitimately deserve and the actual opportunities and resources they possess relative to others",
     ["They possess 100% of all national wealth and have no unfulfilled wishes", "The government gives them free gold coins every morning at sunrise", "They live in total isolation without any knowledge of other human beings"],
     "Mobilization stems from perceived injustice and relative disadvantage compared to a reference standard or group."),
    ("Resource Mobilization Theory", "According to 'Resource Mobilization Theory', the success of a social movement depends critically on:",
     "The movement's ability to mobilize tangible resources such as leadership, organizational networks, funds, volunteers, and communications",
     ["Having no members, no money, and no leaders whatsoever", "Waiting passively for external magical intervention to solve all grievances", "The amount of rainfall received during the previous winter season"],
     "Resource Mobilization theory emphasizes organizational capacity, resources, and tactical strategy over mere shared discontent."),
    ("Narmada Bachao Andolan Demands", "What was the central grievance articulated by the Narmada Bachao Andolan against large mega-dams like Sardar Sarovar?",
     "Massive submergence of fertile farmlands and forests, displacement of adivasis without just rehabilitation, and destruction of river ecology",
     ["That the dam was not painted in bright primary colours", "That the dam reservoir was too small to host international yacht races", "That electricity generated would be sold exclusively to Antarctic scientists"],
     "NBA highlighted the human and ecological costs: involuntary tribal displacement, lack of resettlement, and environmental damage."),
    ("Dalit Panthers Radicalism", "Formed in 1972 in Bombay, how did the 'Dalit Panthers' revolutionize the anti-caste movement?",
     "By combining militant self-defense, radical Marxist-Ambedkarite ideology, assertive protest literature, and uncompromising resistance to caste atrocities",
     ["By appealing quietly to upper-caste landowners for small financial loans", "By advocating that Dalits permanently withdraw from all political activities", "By demanding that only classical Sanskrit literature be taught in schools"],
     "The Dalit Panthers injected revolutionary militancy and vibrant Dalit literature into the anti-caste struggle."),
    ("Autonomous Women's Movement", "The emergence of the 'Autonomous Women's Movement' in India during the late 1970s was distinct because:",
     "Women organized independent groups autonomous from male-dominated political parties to campaign against dowry deaths, custodial rape, and domestic violence",
     ["It demanded that women be exempted from attending schools and universities", "It was funded and led entirely by colonial British officers", "It focused solely on promoting traditional patriarchal purdah customs"],
     "Autonomous groups (e.g., Saheli, Forum Against Oppression of Women) organized independently around gender-specific violence."),
    ("Mathura Rape Case (1979)", "The nationwide protest triggered by the Supreme Court verdict in the Mathura custodial rape case led to:",
     "Historic legal reforms in the Indian Penal Code, shifting the burden of proof in custodial rape and redefining sexual assault laws",
     ["The complete abolition of all police stations across India", "A ban on women entering public government offices", "The immediate dissolution of the Supreme Court of India"],
     "The open letter by law professors on Mathura ignited mass mobilizations that forced the state to overhaul rape laws in 1983."),
    ("Chipko's 'Hugging' Tactic", "In 1974, Gaura Devi and rural women in Reni village, Uttarakhand, famously protected their community forests by:",
     "Clinging their bodies to trees (hugging) to challenge armed commercial loggers, declaring they would sacrifice their lives before trees were cut",
     ["Selling timber concessions to multinational paper corporations", "Using bulldozers to clear all trees for luxury tourist resorts", "Refusing to allow any rainfall to enter their mountain valley"],
     "Gaura Devi and village women mobilized non-violent ecological resistance, physically encircling trees against axes."),
    ("Appiko Movement in Karnataka", "Inspired by the Himalayan Chipko movement, which ecological struggle was launched in the Western Ghats of Karnataka in 1983?",
     "Appiko Chaluvali (meaning 'to embrace' in Kannada), protesting commercial deforestation in the fragile Western Ghats",
     ["Narmada Bachao Movement", "Silent Valley Hydroelectric Project", "Tebhaga Sharecroppers League"],
     "Appiko adapted the tree-hugging protest technique in Karnataka to conserve natural tropical rainforests."),
    ("Silent Valley Movement", "The historic 'Save Silent Valley' movement in Kerala (1970s-80s) was organized to:",
     "Prevent the construction of a hydroelectric dam that would have submerged pristine tropical moist evergreen rainforest and endangered Lion-tailed Macaques",
     ["Construct a nuclear weapons testing facility in a crowded coastal town", "Drain all freshwater rivers into deep underground caverns", "Clear sacred groves to build international casino resorts"],
     "Silent Valley was a landmark ecological victory where civil society prevented ecological devastation, creating a National Park."),
    ("New Farmers' Movements (1980s)", "Sociologists distinguish 'New Farmers' Movements' (like Sharad Joshi's Shetkari Sanghatana) from earlier peasant struggles by their focus on:",
     "The urban-rural divide ('Bharat vs India'), remunerative prices for crops, cheaper diesel/power, and protection against state exploitation of farm terms of trade",
     ["Abolishing all private land ownership in favor of medieval communal clans", "Demanding that all farm labourers be paid in foreign gold bullion", "Refusing to sell food grains to anyone living in the same state"],
     "New Farmers' Movements focused on market-oriented issues: crop prices, state procurement, and terms of trade between rural Bharat and urban India."),
    ("Anti-Arrack Movement in Andhra", "The historic Anti-Arrack Movement launched by rural women in Nellore, Andhra Pradesh in the 1990s started from:",
     "A literacy primer lesson that galvanized women to protest domestic violence, household debt, and health destruction caused by state-licensed country liquor (arrack)",
     ["A commercial advertising campaign promoting foreign wine consumption", "A government plan to construct modern breweries in every primary school", "An initiative to import foreign vodka using national space rockets"],
     "National Literacy Mission classes sparked women to unite, successfully forcing the state government to ban arrack."),
    ("Right to Information (MKSS) Movement", "The Mazdoor Kisan Shakti Sangathan (MKSS) led by Aruna Roy in Rajasthan spearheaded the struggle for the Right to Information by:",
     "Organizing 'Jan Sunwais' (public hearings) to demand inspection of panchayat development muster rolls, exposing ghost workers and wage corruption",
     ["Demanding that all village records be written in secret invisible ink", "Refusing to allow any government development schemes to be implemented", "Demanding that only corporate executives be allowed to audit public funds"],
     "MKSS connected grassroots corruption in famine relief works directly to citizen rights to state information, culminating in the 2005 RTI Act.")
]

SLOT40 = build_slot(CH_MOVEM, list(s40_raw) + [("mcq", top, stem, corr, wrongs, expl) for top, stem, corr, wrongs, expl in s40_extras])

SLOTS_36_40 = {
    36: SLOT36,
    37: SLOT37,
    38: SLOT38,
    39: SLOT39,
    40: SLOT40
}

print("Slots 36 to 40 compiled successfully.")
